Repository pingcap/tiflow, pull requests merged in 2019-12, with the labels that each got.

#164 update readme
  README.md
  cmd/client.go
Labels: LGT2

#163 owner: fix checkpoint ts calculate in owner
  cdc/owner.go
  cdc/schema/storage.go
Labels: LGT2

#169 cmd: add ctrl command to encapsulate some etcd query
  cmd/client.go
  cmd/ctrl.go
Labels: LGT2

#170 Add coverage report and more badges
  .codecov.yml
  Makefile
  README.md
Labels: LGT1

#167 mark processor down for some time not updating resolve ts
  cdc/owner.go
  cdc/owner_test.go
Labels: LGT2

#173 CLI: add a cli tool can delete all keys created by CDC in PD
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cmd/ctrl.go
Labels: LGT2

#176 *: Trace error
  .gitignore
  cdc/capture.go
  cdc/kv/client.go
  cdc/kv/etcd.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/puller/puller.go
  cdc/roles/storage/etcd.go
  cdc/scheduler.go
  cdc/sink/mysql.go
  cdc/txn/txn.go
Labels: LGT2

#177 fix endless retry in singleEventFeed
  cdc/kv/client.go
Labels: LGT2

#179 Add a IsResolved field for RawTxn so that we can reuse it for a fake resolved txn
  cdc/model/txn.go
  cdc/processor.go
  cdc/processor_test.go
Labels: LGT1, LGT2

#181 get tso from pd, remove useless command
  cmd/cdc.go
  cmd/client.go
  cmd/root.go
  tests/_cli_tools/get_tso.go
  tests/multi_capture/run.sh
  tests/prepare_tools.sh
  tests/simple/run.sh
  tests/split_region/run.sh
Labels: LGT2

#178 support integration test in CI
  Makefile
  main_test.go
  tests/_utils/run_cdc_server
  tests/_utils/start_tidb_cluster
  tests/multi_capture/conf/workload1
  tests/multi_capture/conf/workload2
  tests/multi_capture/run.sh
  tests/simple/run.sh
  tests/split_region/run.sh
Labels: LGT2

#184 fix get-tso in integration test
  cmd/ctrl.go
  tests/_cli_tools/get_tso.go
  tests/multi_capture/run.sh
  tests/prepare_tools.sh
  tests/simple/run.sh
  tests/split_region/run.sh
Labels: LGT2

#185 test: remove mock_tidb
  cdc/cdc_test.go
  cdc/entry/kv_entry_test.go
  cdc/mock/mock_tidb.go
  cdc/mock/mock_tidb_test.go
Labels: LGT1

#183 Get Sink.Emit ready for bulk processing
  cdc/processor_test.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
Labels: LGT2

#186 Return value for model.Txn
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/processor.go
  cdc/processor_test.go
Labels: LGT2

#188 owner: fix startTs in processor table info dispatched from owner
  cdc/owner.go
Labels: LGT2

#187 support resign owner, add is-owner field in capture list result
  cdc/capture.go
  cdc/capture_info.go
  cdc/cdc_test.go
  cdc/http_handler.go
  cdc/http_status.go
  cdc/http_status_test.go
  cdc/kv/etcd.go
  cdc/owner.go
  cdc/roles/manager.go
  cdc/roles/manager_test.go
  cdc/roles/mock_manager.go
  cmd/ctrl.go
Labels: LGT2

#189 Emit in bulk in syncResolved
  cdc/processor.go
Labels: LGT2

#191 Refactor, changeFeedInfo -> changeFeed
  cdc/owner.go
  cdc/owner_test.go
Labels: LGT2

#194 Flush pending txns when the buffers are empty
  cdc/processor.go
Labels: LGT1

#197 tests: wait cdc server exits in integration test
  tests/_utils/cleanup_process
  tests/multi_capture/run.sh
  tests/simple/run.sh
  tests/split_region/run.sh
Labels: LGT2

#192 Merge cdc/txn into cdc/puller to reduce the number of packages
  cdc/puller/puller.go
  cdc/puller/txn_test.go
  cdc/txn/txn.go
Labels: LGT2

#198 Fix deadlock while successive drop tables
  cdc/kv/client.go
  cdc/kv/metrics.go
  cdc/metrics_processor.go
  cdc/owner.go
  cdc/processor.go
  cdc/processor_test.go
Labels: LGT2

#193 Move txn filtering out of mysqlSink
  cdc/filter.go
  cdc/filter_test.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: LGT2

#195 wait all processors exit in capture
  cdc/capture.go
  cdc/processor.go
  cdc/scheduler.go
  cdc/scheduler_test.go
  cdc/server.go
Labels: LGT2

#200 Add grafana dashboard ticdc.json
  ticdc.json
Labels: LGT2

#180 test: switch on binlog test, part 1
  cdc/entry/mounter.go
  cdc/model/txn.go
  cdc/owner_operator.go
  cdc/schema/storage.go
  tests/cdc/cdc.go
  tests/cdc/run.sh
  tests/dailytest/case.go
  tests/dailytest/dailytest.go
  tests/run.sh
  tests/util/db.go
Labels: LGT2

#202 Add a metric to track the number of txns resolved in one go
  cdc/puller/metrics.go
  cdc/puller/puller.go
Labels: LGT2

#196 Refactor, extract functions to simplify loadChangeFeeds
  cdc/model/changefeed.go
  cdc/owner.go
Labels: LGT2

#205 processor: make the buffer larger in processor and puller to improve performance
  cdc/processor.go
  cdc/puller/buffer.go
  cdc/puller/buffer_test.go
Labels: LGT2

#203 cdc: support recover table and fix test
  cdc/owner.go
  tests/_utils/start_tidb_cluster
  tests/_utils/test_prepare
  tests/cdc/run.sh
  tests/dailytest/case.go
  tests/multi_capture/run.sh
  tests/simple/run.sh
  tests/split_region/run.sh
Labels: LGT2

#207 test: merge new binlog test
  tests/dailytest/case.go
Labels: LGT2

#199 Split DMLs into independent groups, execute them concurrently
  cdc/owner_operator.go
  cdc/processor.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/sink.go
Labels: LGT2

#209 test: fix ci and close the unstable test case
  tests/cdc/run.sh
  tests/dailytest/case.go
Labels: LGT2

#211 Fix TestShouldSplitByTable
  cdc/sink/mysql_test.go
Labels: LGT2

#210 Delete from map directly
  cdc/owner.go
Labels: LGT2

#208 test: open the updatePKUK test
  tests/dailytest/case.go
Labels: LGT2

#212 bug fix: fix case UpdateWhileDroppingCol
  cdc/entry/kv_entry.go
  cdc/entry/kv_entry_test.go
  cdc/entry/mounter.go
  cdc/puller/mock_puller.go
  cdc/schema/storage.go
  cdc/sink/cached_inspector.go
  cdc/sink/cached_inspector_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/sink.go
  cdc/sink/util.go
  cdc/sink/util_test.go
  tests/dailytest/case.go
Labels: LGT2

#204 Add support for specifying database and table filter rules
  cdc/filter.go
  cdc/filter_test.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/processor.go
Labels: LGT2

#213 Add capture ID and process pid in status API
  cdc/http_status.go
Labels: LGT2

#214 owner rebalance tables when marking processor down
  cdc/capture.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/owner.go
  cdc/server.go
  cmd/server.go
  pkg/util/log.go
  pkg/util/log_test.go
Labels: LGT2

#216 fix table management when owner starts up
  cdc/owner.go
Labels: LGT2

#217 close channel p.executedTxns where we use it as sender
  cdc/processor.go
Labels: LGT2

#219 Remove unused code copied from binlog
  cdc/entry/mounter_test.go
  cdc/processor.go
  cdc/schema/storage.go
  cdc/schema/storage_test.go
Labels: LGT2

#215 Replace tableInspector with infoGetter
  cdc/schema/storage.go
  cdc/schema/storage_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/sink.go
  cdc/sink/util.go
Labels: LGT2
