Repository pingcap/tiflow, pull requests merged in 2020-03, with the labels that each got.

#293 puller: support to output sorted row-based changed event, part one
  cdc/model/errors.go
  cdc/model/kv.go
  cdc/puller/entry_sorter.go
  cdc/puller/entry_sorter_test.go
  cdc/puller/mock_puller.go
  cdc/puller/puller.go
  tests/run.sh
Labels: LGT1

#294 mounter: support to handle row-based changed event for mounter, part two
  cdc/entry/codec.go
  cdc/entry/codec_test.go
  cdc/entry/kv_entry.go
  cdc/entry/kv_entry_test.go
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/entry/schema_builder.go
  cdc/entry/schema_builder_test.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/model/row.go
  cdc/schema/storage_test.go
Labels: LGT1

#296 processor: handle row-based changed event in processor, part three
  cdc/filter.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/processor_test.go
  cdc/roles/storage/etcd.go
  cdc/scheduler.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/sink.go
Labels: LGT1

#281 add a rfc about mq protocol in chinese
  docs/design/2020-02-24-ticdc-mq-protocol-chinese-version.md
Labels: LGT1

#289 kv-client: add gRPC conn array
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: LGT1, PTAL

#291 Fix lowercase schema name in ddl mounter
  cdc/entry/mounter.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/sink/mysql.go
Labels: LGT1, PTAL

#297 Configurable worker count
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: LGT2

#299 Reduce the RTO by watching the liveness of processors
  cdc/capture.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/model/processor.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/scheduler.go
  cmd/ctrl.go
Labels: LGT2

#309 rfc: add ticdc design document
  docs/design/2020-03-04-ticdc-design-and-architecture-cn.md
  docs/media/capture_architecture.png
  docs/media/tikv_cdc_stream_init.png
Labels: PTAL

#310 sink: handle row-based changed event in sink, part four
  cdc/entry/kv_entry_test.go
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/entry/schema_builder.go
  cdc/entry/schema_builder_test.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/filter_test.go
  cdc/model/owner_test.go
  cdc/model/row.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/processor_test.go
  cdc/puller/entry_sorter.go
  cdc/puller/entry_sorter_test.go
  cdc/puller/mock_puller_test.go
  cdc/puller/puller.go
  cdc/roles/storage/etcd.go
  cdc/roles/storage/etcd_test.go
  cdc/scheduler.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/sink.go
  go.mod
Labels: LGT1

#300 cmd: check start ts larger than tikv_gc_safe_point
  cmd/client.go
Labels: LGT1, PTAL

#315 bug fix: panic about schema builder
  cdc/entry/schema_builder.go
Labels: LGT1

#314 manager: use a less TTL value
  cdc/roles/manager.go
Labels: LGT2

#290 sink: refine mysql log, remove redundant SQL count log
  cdc/processor.go
  cdc/scheduler.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  tests/run.sh
Labels: LGT1

#319 Refactor/capture watcher
  cdc/capture.go
  cdc/capture_info_test.go
  cdc/kv/etcd.go
  cdc/owner.go
  cdc/processor.go
Labels: LGT2

#306 improve span_frontier performance
  cdc/puller/span_frontier.go
  cdc/puller/span_frontier_bench_test.go
  cdc/puller/span_frontier_test.go
  cdc/sink/metrics.go
  go.mod
  pkg/interval/interval.go
  tests/_utils/start_tidb_cluster
Labels: LGT1, PTAL

#322 sink: implement kafka sink
  Makefile
  cdc/entry/mounter.go
  cdc/model/mq.go
  cdc/model/row.go
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/scheduler.go
  cdc/sink/black_hole.go
  cdc/sink/mq.go
  cdc/sink/mqProducer/kafka.go
  cdc/sink/mqProducer/mq_producer.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  go.mod
  go.sum
  kafka_consumer/main.go
  tests/dailytest/case.go
Labels: LGT1

#323 bug fix: panic in storagebuilder sometimes
  cdc/model/owner.go
  cdc/owner.go
  cdc/processor.go
Labels: LGT1, bug-fix

#328 sink: use chan to notify resolved ts forward in mysql sink
  cdc/sink/mysql.go
Labels: C: Sink, LGT1

#326 kafka sink: support more params in sink-uri
  cdc/sink/mq.go
  cdc/sink/sink.go
Labels: C: Sink, LGT1

#329 kafka sink: implement print status interface
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
Labels: C: Sink, LGT1

#333 add issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: PTAL

#335 bug fix: set changedfeed id into sink options mistakenly
  cdc/scheduler.go
Labels: C: Scheduler, LGT1, bug-fix

#325 sink : support filter in sink
  cdc/model/changefeed.go
  cdc/model/config.go
  cdc/owner.go
  cdc/scheduler.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  cmd/client.go
  cmd/cmd_test.go
  cmd/debug.go
  kafka_consumer/main.go
  pkg/util/filter.go
  pkg/util/filter_test.go
Labels: C: Sink, LGT1

#308 client: Implement batch client
  cdc/kv/client.go
  go.mod
  go.sum
  tests/simple/run.sh
Labels: C: KV-client, LGT2, P0

#334 cmd: refactor command line interface
  README.md
  cdc/server.go
  cmd/client.go
  cmd/ctrl.go
  cmd/debug.go
  cmd/server.go
  cmd/test.go
  cmd/version.go
  tests/cdc/run.sh
  tests/multi_capture/run.sh
  tests/row_format/run.sh
  tests/run.sh
  tests/simple/run.sh
  tests/split_region/run.sh
Labels: PTAL, S: Usability

#331 Kafka sink: create a topic or get partition number automatically
  cdc/processor.go
  cdc/sink/mq.go
  cdc/sink/mqProducer/kafka.go
  cdc/sink/mqProducer/mq_producer.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
Labels: C: Sink, LGT1

#332 add Changelog for v4.0.0-beta.2 release
  CHANGELOG.md
Labels: PTAL

#327 kafka sink: support partition by rowid or unique value
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/model/sink.go
  cdc/sink/mq.go
Labels: C: Sink, LGT1

#336 mysql sink: add a batch size limiter
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: C: Sink, LGT1

#338 sink: fix parse DSN as URI by mistake
  cdc/sink/sink.go
  tests/cdc/run.sh
Labels: LGT1

#345 ci: move jenkins_ci script into the repo
  scripts/jenkins_ci/cdc_ghpr_build.groovy
  scripts/jenkins_ci/cdc_ghpr_check.groovy
  scripts/jenkins_ci/cdc_ghpr_integration_test.groovy
  scripts/jenkins_ci/cdc_ghpr_test.groovy
  tools/check/check-tidy.sh
Labels: LGT1

#346 ci: add kafka integration test
  Makefile
  kafka_consumer/main.go
  scripts/jenkins_ci/cdc_ghpr_integration_test.groovy
  scripts/jenkins_ci/cdc_ghpr_kafka_integration_test.groovy
  scripts/jenkins_ci/integration_test_common.groovy
  tests/_utils/run_kafka_consumer
  tests/cdc/run.sh
  tests/multi_capture/run.sh
  tests/row_format/run.sh
  tests/run.sh
  tests/simple/run.sh
  tests/split_region/run.sh
Labels: LGT1

#339 docker: support quick start
  .dockerignore
  .gitignore
  README.md
  docker-compose.yml
  docker/Dockerfile
  docker/config/pd.toml
  docker/config/tidb.toml
  docker/config/tikv.toml
Labels: LGT2

#353 sink/mysql: remove default schema in mysql dsn
  cdc/sink/mysql.go
Labels: C: Sink, PTAL

#351 cli: support interactive cmd
  cmd/client.go
  cmd/ctrl.go
  go.mod
  go.sum
Labels: LGT2, PTAL

#356 refine log output
  cdc/entry/schema_storage.go
  cdc/owner.go
  cdc/processor.go
Labels: LGT1

#337 capture: implement the task watcher
  cdc/capture.go
  cdc/kv/etcd.go
  cdc/owner.go
  cdc/processor.go
  cdc/scheduler.go
  cdc/scheduler_test.go
  cdc/task.go
  cdc/task_test.go
  tests/_utils/ensure
  tests/_utils/random_kill_process
  tests/availability/run.sh
Labels: LGT2, PTAL

#368 Support to check whether the table can be duplicated by CDC
  cdc/capture.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/kv/store_op.go
  cdc/model/sink.go
  cdc/owner.go
  cdc/processor.go
  cdc/puller/mock_puller.go
  cmd/client.go
  tests/dailytest/case.go
Labels: LGT1

#370 puller: fix listen add index ddl
  cdc/entry/mounter.go
  cdc/owner_operator.go
  cdc/processor.go
  pkg/util/span.go
Labels: LGT1

#364 tests: start tiflash server on CI
  .gitignore
  scripts/jenkins_ci/integration_test_common.groovy
  tests/_utils/start_tidb_cluster
  tests/_utils/stop_tidb_cluster
  tests/_utils/tiflash-users.toml
  tests/run.sh
Labels: LGT1

#377 task: fix to parse task when the status is not created
  cdc/task.go
Labels: C: Scheduler, LGT2, P0

#344 sink: implement an async kafka sink
  cdc/owner.go
  cdc/scheduler.go
  cdc/sink/mq.go
  cdc/sink/mqProducer/kafka.go
  cdc/sink/mqProducer/mq_producer.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  kafka_consumer/main.go
  pkg/util/ctx.go
Labels: C: Sink, LGT1, S: Performance

#381 fix block when the `run` function of `owner` returns an error
  cdc/capture.go
  cdc/owner.go
  cdc/sink/sink.go
Labels: LGT1

#374 bug fix: fix schema builder may remove unapplied DDL job
  cdc/entry/mounter.go
  cdc/entry/schema_builder.go
  cdc/entry/schema_storage.go
  cdc/model/errors.go
  cdc/processor.go
Labels: LGT1

#382 capture: print log after the processor being started
  cdc/capture.go
Labels: C: Scheduler, LGT1

#393 sink: fix Run in black hole sink
  cdc/owner.go
  cdc/processor.go
  cdc/sink/black_hole.go
Labels: C: Sink, LGT1

#386 puller: fix sorter may panic because of bad usage of chan
  cdc/puller/entry_sorter.go
  cdc/puller/puller.go
  cdc/sink/mqProducer/kafka.go
  kafka_consumer/main.go
Labels: PTAL, bug-fix, bug-from-user

#388 scripts: support specify tidb/pd/tikv version in test
  scripts/jenkins_ci/integration_test_common.groovy
Labels: PTAL

#390 Add retry to gRPC stream client getter
  cdc/kv/client.go
Labels: C: KV-client, PTAL, bug-fix

#396 fix entry sorter metrics
  cdc/puller/entry_sorter.go
  ticdc.json
Labels: PTAL

#395 increase chan size, fix grafana template
  cdc/entry/mounter.go
  cdc/processor.go
  cdc/puller/buffer.go
  cdc/puller/entry_sorter.go
  cdc/puller/puller.go
  cdc/sink/mq.go
  ticdc.json
Labels: LGT1

#398 kv-client: remove kv sorter
  cdc/kv/client.go
Labels: C: KV-client, PTAL

#358 Combine the session of captures, manager and processors
  cdc/capture.go
  cdc/capture_info.go
  cdc/capture_info_test.go
  cdc/changefeed.go
  cdc/http_handler.go
  cdc/http_status.go
  cdc/kv/etcd.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/roles/manager.go
  cdc/roles/manager_test.go
  cdc/roles/mock_manager.go
  cdc/scheduler.go
  cdc/server.go
  cmd/ctrl.go
  go.mod
  tests/_utils/start_tidb_cluster
Labels: LGT1, S: HA, enhancement

#371 Remove the processor watcher
  cdc/changefeed.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/model/processor.go
  cdc/owner.go
  cdc/processor.go
  cdc/scheduler.go
  cdc/scheduler_test.go
  cmd/client.go
  cmd/ctrl.go
Labels: LGT1, S: HA, enhancement

#417 kafka: crop message size of kafka producer
  cdc/entry/mounter.go
  cdc/model/mq.go
  cdc/model/sink.go
  cdc/processor.go
  cdc/sink/mq.go
  cdc/sink/mqProducer/kafka.go
  cdc/sink/mysql.go
Labels: C: Sink, LGT1, enhancement

#418 ci: add availability into the jenkins test
  scripts/jenkins_ci/integration_test_common.groovy
Labels: LGT1, S: HA

#416 util: Add RegionRangeLock
  go.mod
  pkg/util/region_range_lock.go
  pkg/util/region_range_lock_test.go
Labels: LGT2

#412 sorter: Improve sorter performance and avoid performance regressions caused by data backlogs
  cdc/kv/client.go
  cdc/processor.go
  cdc/puller/entry_sorter.go
  cdc/puller/entry_sorter_test.go
  cdc/puller/puller.go
  cdc/sink/mq.go
  pkg/util/ctx.go
Labels: PTAL

#415 fix restore table panic
  cdc/changefeed.go
Labels: LGT1

#411 sink/kafka: decrease max retry time in producer and metadata
  cdc/sink/mqProducer/kafka.go
Labels: C: Sink, LGT1

#399 kv-client: decrease metrics init cpu consume
  cdc/kv/client.go
Labels: C: KV-client, PTAL

#419 Add more resolved ts related metrics
  cdc/entry/metrics.go
  cdc/entry/mounter.go
  cdc/metrics.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/puller/buffer.go
  cdc/puller/entry_sorter.go
  cdc/puller/metrics.go
  cdc/puller/puller.go
  cdc/sink/metrics.go
  cdc/sink/mq.go
  ticdc.json
Labels: PTAL
