Repository pingcap/tiflow, pull requests merged in 2020-10, with the labels that each got.

#980 tests: add minio link in test/README.md
  tests/README.md
Labels: PTAL, status/LGT2

#983 pipeline: implement a pipeline framework
  pkg/pipeline/context.go
  pkg/pipeline/message.go
  pkg/pipeline/node.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/runner.go
Labels: status/LGT1

#979 owner, errors: ignore update gc safepoint error
  cdc/owner.go
  cdc/owner_test.go
  pkg/errors/errors.go
Labels: bug-fix, internal-test, status/LGT2, status/can-merge

#986 metrics: reduce mounter alerts
  metrics/alertmanager/ticdc.rules.yml
Labels: internal-test, status/LGT2, status/can-merge

#987 processor: fix incorrect fatal detect in processor
  cdc/processor.go
  cdc/sink/mysql.go
  cdc/sink/producer/kafka/kafka.go
  tests/processor_resolved_ts_fallback/conf/diff_config.toml
  tests/processor_resolved_ts_fallback/run.sh
Labels: C: Replica-model, status/LGT2, status/can-merge

#989 model: fix json name typo
  cdc/model/sink.go
Labels: status/LGT2

#988 scripts/ci: use fileserver to transfer third_party binaries
  scripts/jenkins_ci/integration_test_common.groovy
Labels: PTAL, status/LGT2, status/can-merge

#990 tests: fix session variable is not reload in row format case
  tests/row_format/data/step1.sql
  tests/row_format/data/step2.sql
  tests/row_format/data/step3.sql
  tests/row_format/data/step4.sql
  tests/row_format/run.sh
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#998 cmd: add more sink protocol config
  cmd/changefeed.toml
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1007 *: use tiup lib to generate errors toml
  Makefile
  errors.toml
  pkg/errors/errors.go
  tools/check/check-errdoc.sh
  tools/check/go.mod
  tools/check/go.sum
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1005 *: support to replicate tables without explicit row id
  cdc/changefeed.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/model/schema_storage.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cmd/client_changefeed.go
  cmd/util.go
  errors.toml
  pkg/config/config.go
  pkg/errors/errors.go
  tests/force_replicate_table/conf/changefeed.toml
  tests/force_replicate_table/conf/tidb_config.toml
  tests/force_replicate_table/data/test.sql
  tests/force_replicate_table/run.sh
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1011 makefile: pass ldflags in integration test build
  Makefile
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1017 processor: fix task status is always flushed because of incorrect mod revision cache
  cdc/processor.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, release-blocker, status/LGT2, status/can-merge

#1018 changefeed: record only once if both ticker and ddl trigger syncpoint
  cdc/changefeed.go
Labels: bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1021 sink: ignore duplicated syncpoint
  cdc/sink/mysql.go
Labels: bug-fix, needs-cherry-pick-4.0, status/LGT2

#1023 sink/mysql: fix statistics print status missing in MySQL sink
  cdc/sink/mysql.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2

#996 cli: add show metadata sub command
  cdc/capture.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cmd/client.go
  cmd/client_unsafe.go
  pkg/etcd/etcd.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1030 sink/mysql: support to pass a timezone dsn parameter
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  kafka_consumer/main.go
Labels: PTAL, needs-cherry-pick-4.0, release-blocker, status/LGT2, status/can-merge

#1031 *: fix many goroutine leak
  cdc/kv/client.go
  cdc/owner.go
  cdc/processor.go
  cdc/server.go
  pkg/notify/notify.go
  pkg/util/ctx.go
Labels: PTAL, needs-cherry-pick-4.0, release-blocker, status/LGT2, status/can-merge

#1037 [release-4.0] kv: fix unexpected skipping in batch resolved ts
  cdc/kv/client.go
Labels: C: KV-client, PTAL, bug-fix, release-blocker, status/LGT2

#1036 kv: fix unexpected skipping in batch resolved ts
  cdc/kv/client.go
Labels: C: KV-client, PTAL, bug-fix, status/LGT2, status/can-merge

#995 pipeline: implement a pipeline framework for processor
  pkg/pipeline/context.go
  pkg/pipeline/message.go
  pkg/pipeline/node.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/runner.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1029 pkg: add entrypoint to some unit test
  pkg/flags/urls_test.go
  pkg/util/test_helper_test.go
  pkg/version/check.go
  pkg/version/check_test.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2

#1013 sink: support Canal Json protocol
  .github/workflows/integration.yml
  cdc/model/sink.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/codec/interface.go
  cdc/sink/mq.go
  docker-compose-canal.yml
  go.mod
  go.sum
  integration/framework/canal/kafka_single_table.go
  integration/framework/docker_compose_op.go
  integration/integration.go
  scripts/canal/docker/start.sh
Labels: C: Sink, PTAL, enhancement, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1009 scripts/jenkins_ci: change default branch of tidb cluster to release-4.0
  scripts/jenkins_ci/integration_test_common.groovy
Labels: S: TEST, status/LGT2, status/can-merge
