Repository pingcap/tiflow, pull requests merged in 2020-09, with the labels that each got.

#901 tests: disable clustered index in integration test
  tests/_utils/start_tidb_cluster_impl
Labels: PTAL, status/LGT2, status/can-merge

#902 api: return immediately when meeting non leader error
  cdc/http_handler.go
  cdc/http_status_test.go
Labels: PTAL, status/LGT2, status/can-merge

#904 test: add test for docker build
  .github/workflows/docker_build_test.yml
Labels: PTAL, status/LGT2, status/can-merge

#913 tests: disable clustered index in all tidb in integration test
  tests/_utils/start_tidb_cluster_impl
  tests/_utils/start_tls_tidb_cluster_impl
Labels: S: TEST, status/LGT2, status/can-merge

#886 cdc, pkg/util: add an HTTP API to change log level
  cdc/http_handler.go
  cdc/http_status.go
  cdc/owner.go
  cmd/client.go
  cmd/server.go
  cmd/util.go
  kafka_consumer/main.go
  pkg/logutil/log.go
  pkg/logutil/log_test.go
  tests/cli/run.sh
Labels: release-blocker, status/LGT2, status/can-merge

#898 sink/kafka: fix checkpoint forward too much when producer meets error
  cdc/sink/mq.go
  cdc/sink/producer/kafka/kafka.go
  tests/kafka_sink_error_resume/conf/diff_config.toml
  tests/kafka_sink_error_resume/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#921 cdc: add region id to events to improve debuggability
  cdc/kv/client.go
  cdc/model/kv.go
  cdc/model/mounter.go
  cdc/processor.go
  cdc/puller/entry_sorter.go
  cdc/puller/entry_sorter_test.go
  cdc/puller/file_sorter.go
  cdc/puller/puller.go
  cdc/puller/rectifier.go
Labels: PTAL, status/LGT2, status/can-merge

#912 sink/kafka: fix send on closed channel panic
  cdc/sink/producer/kafka/kafka.go
Labels: C: Sink, bug-fix, status/LGT2, status/can-merge

#917 tests: fix some compatibility with tidb 4.0.x
  tests/_utils/start_tidb_cluster_impl
  tests/_utils/start_tls_tidb_cluster_impl
  tests/common_1/data/test.sql
  tests/common_1/data/test_finish.sql
  tests/common_1/data/test_v5.sql
  tests/common_1/run.sh
  tests/ddl_reentrant/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#899 refactor: revised EventBatchEncoder interface for mqSink
  .github/workflows/integration.yml
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/codec/maxwell.go
  cdc/sink/codec/maxwell_test.go
  cdc/sink/mq.go
  docker-compose-avro.yml
  integration/framework/avro_kafka_docker_env.go
  integration/framework/avro_kafka_single_table.go
  integration/framework/sql_batch_op.go
  integration/framework/sql_helper.go
Labels: C: Open-protocol, C: Sink, PTAL, status/LGT2, status/can-merge

#925 kv-client: fix entry variable wrong usage
  cdc/kv/client.go
Labels: C: KV-client, PTAL, status/LGT2, status/can-merge

#914 test: add go make build and check for github action
  .github/workflows/check_and_build.yml
  .github/workflows/docker_build_test.yml
  Makefile
  cdc/model/owner.go
  tests/dailytest/parser.go
  tools/check/go.mod
  tools/check/go.sum
Labels: PTAL, status/LGT2, status/can-merge

#910 cdc, pkg/txnutil: skip resolve lock during puller initialization
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/testing.go
  cdc/puller/mock_puller.go
  cdc/puller/puller.go
  pkg/txnutil/lock_resolver.go
Labels: PTAL, status/LGT2, status/can-merge

#909 *: fix clone function of some structs
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: PTAL, bug-fix, status/LGT2, status/can-merge

#927 kvclient: fix CRTs less than resolvedTs in puller
  cdc/kv/client.go
  pkg/regionspan/region_range_lock.go
  pkg/regionspan/region_range_lock_test.go
Labels: bug-fix, status/LGT2, status/can-merge

#916 fix: Remove globalResolvedTs > localResolvedTs fatal & update localResolvedTs before startPuller
  cdc/processor.go
  tests/_utils/run_cdc_server
  tests/processor_panic/config.toml
  tests/processor_panic/diff_config.toml
  tests/processor_panic/main.go
  tests/processor_panic/run.sh
Labels: PTAL, bug-fix, status/LGT2, status/can-merge

#926 make jenkins job compatible with QA jobs
  scripts/jenkins_ci/integration_test_common.groovy
Labels: PTAL, status/LGT2, status/can-merge

#922 *: use rfc error in all sub modules of cdc/.*
  cdc/changefeed.go
  cdc/entry/codec.go
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/kv/client.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/kv/store_op.go
  cdc/model/capture.go
  cdc/model/changefeed.go
  cdc/model/owner.go
  cdc/model/string.go
  cdc/puller/buffer.go
  cdc/puller/buffer_test.go
  cdc/puller/entry_sorter.go
  cdc/puller/file_sorter.go
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/json.go
  cdc/sink/codec/maxwell.go
  cdc/sink/codec/schema_registry.go
  cdc/sink/dispatcher/interface.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/pulsar/producer.go
  cdc/sink/sink.go
  pkg/errors/errors.go
  pkg/regionspan/span.go
Labels: PTAL, status/LGT2, status/can-merge

#929 test: clean the flash_cluster_manager up when finished the test
  tests/_utils/stop_tidb_cluster
Labels: PTAL, status/LGT2, status/can-merge

#923 processor: fix deadlock between sorter input and output
  cdc/processor.go
Labels: PTAL, status/LGT2, status/can-merge

#920 kv/client: Lock region ID as well as range in the range lock.
  cdc/kv/client.go
  pkg/regionspan/region_range_lock.go
  pkg/regionspan/region_range_lock_test.go
Labels: C: KV-client, PTAL, release-blocker, status/LGT2, status/can-merge

#938 gomod: upgrade tidb/parser/pd to latest release-4.0
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/testing.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/puller/puller.go
  cdc/server.go
  cdc/sink/cdclog/s3.go
  cdc/sink/mysql.go
  cmd/client.go
  cmd/test.go
  go.mod
  go.sum
  pkg/security/credential.go
  pkg/util/check.go
  pkg/util/check_test.go
  tests/resolve_lock/main.go
Labels: PTAL, release-blocker, status/LGT2

#933 mounter: handle NaN Inf in mounter
  cdc/entry/mounter.go
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#893 pkg, cdc: add retry to etcd APIs
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  go.mod
  go.sum
  pkg/etcd/client.go
  pkg/etcd/client_test.go
  pkg/etcd/etcd.go
Labels: PTAL, release-blocker, status/LGT2

#939 go mod: update tidb-tools, remove temp replace
  go.mod
  go.sum
Labels: PTAL, release-blocker, status/LGT2

#931 cdc: use rfc errors in files under module cdc
  cdc/capture.go
  cdc/changefeed.go
  cdc/http_handler.go
  cdc/http_status.go
  cdc/http_status_test.go
  cdc/owner.go
  cdc/processor.go
  cdc/server.go
  cdc/server_test.go
  cdc/task.go
  pkg/errors/errors.go
Labels: PTAL, release-blocker, status/LGT2

#936 sink/mysql: add db read/write timeout
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  go.mod
Labels: C: Sink, PTAL, release-blocker, status/LGT2

#941 *: update tidb dependence
  go.mod
  go.sum
Labels: PTAL, release-blocker, status/LGT2

#937 */: add pd write frequency control from cdc server parameter
  cdc/capture.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/kv/metrics.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/server.go
  cdc/task_test.go
  cmd/client.go
  cmd/server.go
  metrics/grafana/ticdc.json
  pkg/etcd/client.go
  pkg/etcd/client_test.go
Labels: release-blocker, status/LGT2

#942 owner: fix mem leak in changefeed
  cdc/changefeed.go
  cdc/owner.go
Labels: PTAL, bug-fix, release-blocker, status/LGT2

#946 fix: unsupported ddl test & checkpointTs = 0
  cdc/processor.go
  tests/common_1/run.sh
  tests/ddl_reentrant/run.sh
Labels: PTAL, Priority/P0, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#948 go mod: upgrade tidb/parser to latest release-4.0
  cdc/sink/mysql.go
  go.mod
  go.sum
Labels: PTAL, release-blocker, status/LGT2

#947 kc/client: correct grpc Dail option to allow large messages
  cdc/kv/client.go
  cdc/kv/client_test.go
  go.mod
  go.sum
Labels: bug-fix, needs-cherry-pick-4.0, release-blocker, status/LGT2

#934 *: add version to request and move {version, check}.go to package version
  Makefile
  cdc/http_status.go
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/server.go
  cmd/client.go
  cmd/server.go
  cmd/version.go
  pkg/version/check.go
  pkg/version/check_test.go
  pkg/version/version.go
Labels: status/LGT2, status/can-merge

#950 .editorconfig: add .editorconfig file, make tab_size = 4
  .editorconfig
Labels: status/LGT2, status/can-merge

#928 sink: refine s3/file sink
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/cdclog/utils.go
  cdc/sink/sink.go
Labels: status/LGT2

#952 dispatcher: refine table operation log, add status field in table operation
  cdc/changefeed.go
  cdc/model/owner.go
  cdc/processor.go
Labels: PTAL, status/LGT2, status/can-merge

#955 sink/mysql: support translated to insert SQL if old value enabled
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/sink.go
Labels: C: Sink, PTAL, status/LGT2

#957 tests: fix the args err in makefile and tests/run.sh to make 'make integration_test' work
  Makefile
  tests/run.sh
Labels: PTAL, status/LGT2

#961 fix: Kafka producer error handling
  cdc/sink/producer/kafka/kafka.go
Labels: PTAL, bug-fix, status/LGT2

#960 fix: Avro cannot delete
  cdc/model/sink.go
  cdc/sink/codec/avro.go
  integration/framework/avro_kafka_docker_env.go
  integration/framework/docker_compose_op.go
  integration/framework/sql_helper.go
Labels: C: Sink, PTAL, bug-fix, status/LGT2

#935 kv/client: reducing message of resolved ts
  cdc/kv/client.go
  cdc/kv/metrics.go
  metrics/grafana/ticdc.json
Labels: C: KV-client, PTAL, release-blocker, status/LGT2

#959 tests: add new ci collation integration test
  tests/new_ci_collation/conf/changefeed.toml
  tests/new_ci_collation/conf/diff_config.toml
  tests/new_ci_collation/conf/tidb_config.toml
  tests/new_ci_collation/data/test1.sql
  tests/new_ci_collation/data/test2.sql
  tests/new_ci_collation/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#963 metrics: delete metrics when close the puller
  cdc/puller/puller.go
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#958 go mod: upgrade pingcap/tidb and pingcap/errors to latest release-4.0
  cdc/sink/mysql.go
  go.mod
  go.sum
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#966 sink: fix Canal sink bugs
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
Labels: C: Sink, bug-fix, bug-from-poc, status/LGT2

#965 changefeed: simplify debug log, put task position only value changes
  cdc/changefeed.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/processor.go
Labels: PTAL, status/LGT2, status/can-merge

#970 cmd: add pd addr in pd connect failed error message
  cmd/client.go
  cmd/util.go
Labels: PTAL, status/LGT2, status/can-merge

#978 sink: fix Maxwell empty messages
  cdc/sink/codec/maxwell.go
  cdc/sink/codec/maxwell_test.go
Labels: C: Sink, PTAL, bug-from-user, status/LGT2, status/can-merge

#976 sink: support canal old value & fix bug
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
  cdc/sink/mq.go
  cmd/client_changefeed.go
Labels: C: Sink, PTAL, bug-fix, status/LGT3, status/can-merge
