Repository pingcap/tiflow, pull requests merged in 2020-04, with the labels that each got.

#385 client: Support region merge
  cdc/entry/codec.go
  cdc/kv/client.go
  cdc/kv/metrics.go
  cdc/kv/testing.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/puller/puller.go
  cmd/client.go
  cmd/test.go
  go.mod
  go.sum
Labels: C: KV-client

#425 Fix/capture suicide
  cdc/capture.go
  cdc/owner.go
  cdc/server.go
Labels: LGT1, PTAL, S: HA

#432 schema: support multi-version storage for schema storage
  cdc/changefeed.go
  cdc/entry/mounter.go
  cdc/entry/schema_builder.go
  cdc/entry/schema_builder_test.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/kv/store_op.go
  cdc/kv/store_op_test.go
  cdc/owner.go
  cdc/processor.go
  cdc/puller/buffer.go
  cdc/puller/mock_puller.go
  cdc/puller/puller.go
  cmd/client.go
Labels: LGT1, S: Performance

#420 integration: add ha test for owner
  tests/_utils/start_tidb_cluster
  tests/availability/owner.sh
  tests/availability/run.sh
Labels: LGT1, S: HA, S: TEST

#436 pre allocate prometheus labels to reduce cpu consume
  cdc/puller/metrics.go
  cdc/puller/puller.go
Labels: LGT1

#363 Add a cmd for outputting statistics periodically
  cdc/model/owner.go
  cdc/processor.go
  cdc/sink/black_hole.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  cmd/client.go
  cmd/ctrl.go
  go.sum
Labels: LGT1, S: Usability

#435 mounter: a new mounter implement
  cdc/entry/metrics.go
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/model/mounter.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/puller/entry_sorter.go
  cdc/puller/entry_sorter_test.go
  cdc/puller/metrics.go
  cdc/puller/mock_puller.go
  cdc/puller/puller.go
  cdc/puller/txn_test.go
Labels: LGT1, S: Performance, internal-test

#428 ci: add capture HA test
  tests/availability/capture.sh
  tests/availability/run.sh
Labels: LGT2, S: HA, S: TEST

#441 owner: add lock for adding table
  cdc/changefeed.go
  cdc/owner.go
  cdc/processor.go
  cdc/roles/storage/etcd.go
  cdc/roles/storage/etcd_test.go
Labels: C: Scheduler, LGT1

#433 kv-client: support p-c out of order before initialized
  cdc/kv/client.go
  cdc/kv/matcher.go
  cdc/kv/matcher_test.go
Labels: C: KV-client, LGT1

#438 schema: fix `table not found` when `startTS` = 0
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/kv/store_op.go
  cdc/kv/store_op_test.go
  cdc/owner.go
  cdc/processor.go
  cdc/puller/mock_puller.go
  cdc/sink/mysql.go
  cmd/client.go
Labels: C: DDL, LGT1, bug-fix

#434 unittest: add failpoint for watchers
  cdc/owner.go
  cdc/task.go
  cdc/task_test.go
  go.mod
Labels: LGT1, S: HA, S: TEST

#437 kv/client: Print log when region worker channel is stuck
  cdc/kv/client.go
Labels: C: KV-client

#445 owner: check if the returned event is nil
  cdc/owner_operator.go
Labels: LGT2, bug-fix

#431 ci: add processor HA test
  cdc/processor.go
  tests/availability/capture.sh
  tests/availability/processor.sh
  tests/availability/run.sh
Labels: LGT1, S: HA, S: TEST

#426 sink/kafka: batch send messages
  cdc/entry/codec.go
  cdc/metrics.go
  cdc/model/mq.go
  cdc/model/mq_test.go
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/sink/mq.go
  cdc/sink/mqProducer/kafka.go
  cdc/sink/mqProducer/metrics.go
  cdc/sink/mqProducer/mq_producer.go
  kafka_consumer/main.go
Labels: LGT1, S: Performance

#448 kv-client: ignore commit log without prewrite before initialized
  cdc/kv/client.go
Labels: C: KV-client, LGT1

#446 kv client: ignore prewrite event if value is empty
  cdc/kv/matcher.go
Labels: C: KV-client, LGT1, bug-fix

#450 owner: fix a bug about wrong timing sequence of DDL when add a table to processor
  cdc/changefeed.go
  cdc/processor.go
  scripts/jenkins_ci/integration_test_common.groovy
  tests/ddl_sequence/conf/diff_config.toml
  tests/ddl_sequence/data/prepare.sql
  tests/ddl_sequence/run.sh
Labels: C: Replica-model, LGT1

#447 cmd: readd processor list command
  cdc/kv/etcd.go
  cdc/model/owner.go
  cmd/client.go
  cmd/ctrl.go
Labels: LGT1, S: Usability

#455 add a metrics about mount duration
  cdc/entry/metrics.go
  cdc/entry/mounter.go
  cdc/metrics_processor.go
  cdc/processor.go
  cdc/puller/puller.go
Labels: LGT1

#451 kv-client: use correct region in log
  cdc/kv/client.go
Labels: C: KV-client, LGT1

#456 sink: add retry mechanism for dml execution
  cdc/sink/mysql.go
  scripts/jenkins_ci/integration_test_common.groovy
  tests/sink_retry/conf/diff_config.toml
  tests/sink_retry/conf/workload
  tests/sink_retry/run.sh
Labels: C: Sink, LGT1

#457 refine some prometheus metrics, update grafana template
  cdc/metrics_processor.go
  cdc/puller/puller.go
  cdc/sink/black_hole.go
  ticdc.json
Labels: LGT1

#458 schema: fix snapshot getter blocks too long when cdc exits
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
Labels: LGT1

#376 add white list ddl filter
  cdc/changefeed.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/processor.go
  cmd/changefeed.toml
  cmd/client.go
  cmd/cmd_test.go
  pkg/util/filter.go
  pkg/util/filter_test.go
Labels: C: DDL, PTAL

#460 kv-client: increase upper limit of retry count.
  cdc/kv/client.go
  cdc/sink/mysql.go
Labels: C: KV-client, LGT1

#459 kvclient: support resolve lock for ticdc
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/testing.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/puller/puller.go
  scripts/jenkins_ci/integration_test_common.groovy
  tests/_utils/stop_tidb_cluster
  tests/resolve_lock/config.toml
  tests/resolve_lock/diff_config.toml
  tests/resolve_lock/main.go
  tests/resolve_lock/run.sh
  tests/util/config.go
Labels: C: KV-client, LGT2

#464 fix owner panic when update task status failed
  cdc/roles/storage/etcd.go
Labels: LGT1

#462 open_protocol: fix version and key lenght format
  cdc/model/mq.go
  cdc/model/mq_test.go
  cdc/sink/mqProducer/kafka.go
  kafka_consumer/main.go
Labels: C: Sink, LGT1, bug-fix

#470 add integration test for droping more than one table in a DDL
  scripts/jenkins_ci/integration_test_common.groovy
  tests/drop_many_tables/conf/diff_config.toml
  tests/drop_many_tables/data/prepare.sql
  tests/drop_many_tables/run.sh
Labels: LGT1

#469 schema: recount ineligible table set when start the changefeed
  cdc/entry/schema_storage.go
  cdc/owner.go
  cmd/client.go
Labels: LGT1

#478 owner: fix the issue about getting the wrong schema snap when start changefeed
  cdc/changefeed.go
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/owner.go
  cdc/puller/mock_puller.go
  cmd/client.go
Labels: LGT1

#476 kvclient: Reduce unnecessary operations when start a event feed
  cdc/capture.go
  cdc/kv/client.go
  cdc/owner.go
  cdc/processor.go
  cdc/server.go
Labels: LGT1

#480 close ticker to fix ticker resource leak
  cdc/kv/client.go
  cdc/sink/mqProducer/kafka.go
Labels: LGT1, S: Performance

#483 sink: fix count in blackhole
  cdc/sink/black_hole.go
Labels: C: Sink, LGT1

#477 Support file sort in puller
  cdc/model/changefeed.go
  cdc/model/mounter.go
  cdc/processor.go
  cdc/puller/entry_sorter.go
  cdc/puller/entry_sorter_test.go
  cdc/puller/file_sorter.go
  cdc/puller/sorter.go
  cmd/client.go
  scripts/jenkins_ci/integration_test_common.groovy
  tests/file_sort/conf/diff_config.toml
  tests/file_sort/conf/workload
  tests/file_sort/run.sh
Labels: LGT1

#491 kafka-consumer: add DockerFile
  Dockerfile
  kafka_consumer/Dockerfile
Labels: LGT2

#489 add rule for alert manager
  metrics/alertmanager/ticdc.rules.yml
  metrics/grafana/ticdc.json
Labels: LGT1

#490 puller: fix cache file name but no sorted file created in file sorter
  cdc/puller/file_sorter.go
Labels: LGT2

#492 update tidb related dep to latest
  cdc/entry/codec.go
  cdc/entry/codec_test.go
  cdc/kv/client.go
  go.mod
  go.sum
  tests/resolve_lock/main.go
Labels: LGT1

#488 owner: fix task status not deleted when capture is crashed
  cdc/owner.go
Labels: LGT1, S: HA

#479 puller: optimize spanFrontier
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_bench_test.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/frontier/heap.go
  cdc/puller/frontier/heap_test.go
  cdc/puller/frontier/list.go
  cdc/puller/frontier/list_test.go
  cdc/puller/puller.go
  cdc/puller/span_frontier.go
  cdc/puller/span_frontier_bench_test.go
Labels: LGT1, S: Performance

#495 ci: update tiflash download address
  scripts/jenkins_ci/integration_test_common.groovy
Labels: LGT1

#494 fix last sorted file assignment in file sorter
  cdc/puller/file_sorter.go
Labels: LGT1, PTAL

#497 sink: add log when executing DDL failed during retry
  cdc/sink/mysql.go
Labels: C: Sink, LGT1

#496 owner: fix global checkpointts stopping when it 's not exist changefees
  cdc/changefeed.go
Labels: LGT1

#487 update minimal checkpointTS as gc safepoint to PD
  cdc/owner.go
  cdc/server.go
  cmd/server.go
Labels: LGT1

#499 kv/client: Fix incorrect behaviors when reconnecting the stream
  cdc/kv/client.go
Labels: C: KV-client, LGT2, bug-fix

#465 sink : add a function that user can switch partition rule in mq sink
  cdc/entry/mounter.go
  cdc/model/sink.go
  cdc/owner.go
  cdc/processor.go
  cdc/sink/dispatcher/default.go
  cdc/sink/dispatcher/default_test.go
  cdc/sink/dispatcher/interface.go
  cdc/sink/dispatcher/rowid.go
  cdc/sink/dispatcher/rowid_test.go
  cdc/sink/dispatcher/table.go
  cdc/sink/dispatcher/table_test.go
  cdc/sink/dispatcher/ts.go
  cdc/sink/dispatcher/ts_test.go
  cdc/sink/mq.go
  cdc/sink/sink.go
  cmd/changefeed.toml
  cmd/cmd_test.go
  kafka_consumer/main.go
  pkg/util/filter.go
Labels: C: Sink, LGT1

#500 metrics: update grafana template
  metrics/grafana/ticdc.json
Labels: LGT1, PTAL

#505 kv/client: Reduce some logs
  cdc/kv/client.go
  cdc/sink/mq.go
Labels: C: KV-client

#498 *: support to config time zone
  cdc/entry/codec.go
  cdc/entry/mounter.go
  cdc/server.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  cmd/server.go
  kafka_consumer/main.go
  pkg/util/ctx.go
Labels: LGT2, PTAL

#507 mounter: skip put index event in unmarshalIndexKVEntry
  cdc/entry/mounter.go
Labels: LGT1, S: Performance

#506 metrics: add tikv metrics
  metrics/grafana/ticdc.json
Labels: LGT2

#503 owner: batch add table when start a changefeed
  cdc/changefeed.go
  scripts/jenkins_ci/integration_test_common.groovy
  tests/batch_add_table/conf/diff_config.toml
  tests/batch_add_table/data/prepare.sql
  tests/batch_add_table/data/test.sql
  tests/batch_add_table/run.sh
Labels: LGT1

#504 owner: fix stale tasks cleanup
  Makefile
  cdc/owner.go
  scripts/jenkins_ci/integration_test_common.groovy
  tests/availability/capture.sh
  tests/availability/owner.sh
Labels: LGT1, PTAL, S: HA

#502 sink/mysql: use pk/uk to refine concurrent execution
  cdc/entry/mounter.go
  cdc/model/sink.go
  cdc/sink/causality.go
  cdc/sink/causality_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: LGT2

#508 sink: remove verbose log if DDL execution is successful
  cdc/sink/mysql.go
Labels: C: Sink, PTAL

#510 *: optimize mounter decode and fix some bugs
  cdc/changefeed.go
  cdc/entry/mounter.go
  cdc/processor.go
  cmd/cmd_test.go
  pkg/util/filter.go
Labels: LGT1, S: Performance

#512 *: fix wrong timezone when env `TZ` is not set
  cdc/server.go
  cdc/sink/mysql.go
  cmd/server.go
  pkg/util/tz.go
Labels: C: Sink, LGT1

#515 cancel all sub routines when a server suicide
  cdc/capture.go
Labels: LGT1, S: HA

#516 file-sorter: fix unsorted files gc, add auto resolved ts output
  cdc/puller/file_sorter.go
  tests/file_sort/conf/workload
  tests/file_sort/run.sh
Labels: LGT1

#519 cmd: refine create changefeed message
  cmd/client.go
Labels: LGT1

#521 cmd: refine error msg when load timezone failed
  cmd/server.go
Labels: LGT1

#520 kafka sink: fix a bug about advancing checkpointTs mistakenly
  cdc/sink/mq.go
  cdc/sink/mqProducer/kafka.go
Labels: C: Sink, LGT2, bug-fix

#511 Add metrics and alerts
  cdc/metrics_processor.go
  cdc/processor.go
  cdc/sink/metrics.go
  cdc/sink/mysql.go
  metrics/alertmanager/ticdc.rules.yml
  metrics/grafana/ticdc.json
Labels: LGT2
