Repository pingcap/tiflow, pull requests merged in 2020-06, with the labels that each got.

#604 test: sleep 5 sec in test case to fix unstable ci
  tests/multi_source/main.go
Labels: LGT1

#605 kvclient: advance the max receive msg size of GRPC
  cdc/kv/client.go
Labels: LGT1, PTAL

#600 owner: ignore the invalid admin jobs
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/owner.go
  cmd/client_changefeed.go
Labels: LGT1

#613 Add timezone data in Dockerfile
  Dockerfile
Labels: LGT1

#612 gomod: update tidb dependency to latest
  cdc/entry/codec.go
  cdc/entry/codec_test.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/kv/client_test.go
  cdc/puller/mock_puller.go
  go.mod
  go.sum
  tests/resolve_lock/main.go
Labels: LGT2

#614 test: refine integration test, part 3
  tests/common_1/data/test.sql
  tests/common_1/run.sh
  tests/dailytest/case.go
Labels: LGT1

#615 *: refine cdc server log and sink statistics log
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cmd/server.go
Labels: LGT1, S: Usability

#616 sink: limit the txn size
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: C: Sink, LGT1

#601 filter: import the new table filter
  cdc/changefeed.go
  cdc/kv/etcd.go
  cdc/kv/sorter.go
  cdc/kv/sorter_test.go
  cdc/model/changefeed_test.go
  cdc/model/errors.go
  cdc/owner.go
  cdc/sink/dispatcher/interface.go
  cdc/sink/dispatcher/switcher_test.go
  cdc/sink/mq.go
  cmd/changefeed.toml
  cmd/cmd_test.go
  go.mod
  go.sum
  pkg/config/config.go
  pkg/config/filter.go
  pkg/config/outdated/v1.go
  pkg/config/sink.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: LGT1, release-blocker

#621 util: fix local timezone parse error
  pkg/util/tz.go
  pkg/util/tz_test.go
Labels: LGT1, bug-fix

#622 tests: fix some env variable names in integration test
  tests/_utils/start_tidb_cluster
  tests/_utils/test_prepare
Labels: LGT1

#623 sink: close the sink and release the db connect
  cdc/processor.go
  cdc/sink/mysql.go
Labels: LGT1, bug-fix

#624 Add task workload cleanup
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/owner.go
  cdc/processor.go
Labels: PTAL

#627 pkg/util: fix check version in git describe format
  pkg/util/check.go
  pkg/util/check_test.go
Labels: LGT2, QA-case, bug-fix

#630 dockerfile: fix the docker image lost the git hash
  Dockerfile
Labels: LGT1

#632 Decrease data size and increase wait time in file sort test
  tests/file_sort/conf/workload
  tests/file_sort/run.sh
Labels: LGT1

#611 cyclic: create mark tables if cyclic is enabled
  cdc/changefeed.go
  cdc/entry/schema_storage.go
  cdc/model/sink.go
  cdc/owner.go
  cdc/owner_test.go
  cmd/client.go
  cmd/client_changefeed.go
  cmd/util.go
  pkg/cyclic/mark.go
  tests/cyclic_ab/run.sh
  tests/cyclic_loopback/run.sh
Labels: LGT1, S: Usability, enhancement

#631 Add some backward compatibility to cdc cli
  cdc/capture.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner.go
  pkg/filter/filter.go
Labels: LGT1, S: Usability

#641 tests: calculate cdc cli coverage
  .codecov.yml
  tests/_utils/run_cdc_cli
  tests/availability/run.sh
  tests/batch_add_table/run.sh
  tests/cdc/run.sh
  tests/cli/run.sh
  tests/common_1/run.sh
  tests/cyclic_ab/run.sh
  tests/cyclic_loopback/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/file_sort/run.sh
  tests/generate_column/run.sh
  tests/many_pk_or_uk/run.sh
  tests/multi_capture/run.sh
  tests/multi_source/run.sh
  tests/partition_table/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/simple/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/tiflash/run.sh
Labels: LGT1

#628 Enable support for AutoRandom in tidb sink
  cdc/changefeed.go
  cdc/sink/mysql.go
  tests/_utils/start_tidb_cluster
  tests/autorandom/conf/diff_config.toml
  tests/autorandom/data/test.sql
  tests/autorandom/run.sh
  tests/cli/run.sh
Labels: LGT2

#647 Fix crts maybe less than emit resolved ts in processor
  cdc/processor.go
Labels: C: Replica-model, LGT1, bug-fix

#652 cmd: add a command to delete CDC GC TTL
  cdc/owner.go
  cmd/client_meta.go
  tests/_utils/run_cdc_cli
  tests/cli/run.sh
Labels: LGT1, S: Usability

#653 tests: add ddl reentrant test
  Makefile
  cdc/processor.go
  cdc/sink/mysql.go
  scripts/jenkins_ci/integration_test_common.groovy
  tests/_utils/start_tidb_cluster
  tests/autorandom/conf/tidb_config.toml
  tests/autorandom/run.sh
  tests/availability/run.sh
  tests/batch_add_table/run.sh
  tests/cdc/run.sh
  tests/cli/run.sh
  tests/common_1/run.sh
  tests/cyclic_ab/run.sh
  tests/cyclic_loopback/run.sh
  tests/ddl_reentrant/conf/diff_config.toml
  tests/ddl_reentrant/conf/tidb_config.toml
  tests/ddl_reentrant/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/file_sort/run.sh
  tests/generate_column/run.sh
  tests/many_pk_or_uk/run.sh
  tests/multi_capture/run.sh
  tests/multi_source/run.sh
  tests/partition_table/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/run.sh
  tests/simple/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/tiflash/run.sh
Labels: C: DDL, LGT2

#651 test: kill the process to avoid port occupancy issues
  tests/_utils/stop_tidb_cluster
Labels: LGT1, S: TEST

#656 cyclic: fix 3 clusters replication
  cdc/sink/mysql.go
  pkg/cyclic/replication.go
  tests/_utils/start_third_tidb_cluster
  tests/_utils/test_prepare
  tests/cyclic_abc/conf/diff_config_down_third.toml
  tests/cyclic_abc/conf/diff_config_up_down.toml
  tests/cyclic_abc/run.sh
Labels: LGT1, bug-fix

#649 Feature/sink canal protocol
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/java.go
  cdc/sink/mq.go
  cmd/cmd_test.go
  go.mod
  pkg/config/config.go
  pkg/config/sink.go
  proto/CanalProtocol.proto
  proto/EntryProtocol.proto
  proto/canal/CanalProtocol.pb.go
  proto/canal/EntryProtocol.pb.go
  proto/generate-proto.sh
  scripts/check-copyright.sh
Labels: C: Sink, LGT2, PTAL, enhancement

#666 remove pb files from coverage stats
  Makefile
Labels: LGT2

#648 mysql sink: fix some bugs and reduce some structures in mysql sink
  cdc/model/sink.go
  cdc/sink/codec/json_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  pkg/cyclic/mark.go
  pkg/cyclic/mark_test.go
  pkg/cyclic/replication.go
  tests/cyclic_abc/run.sh
Labels: C: Sink, LGT2, S: Performance, bug-fix

#662 owner: fast fail on error when it is meaningless to retry
  cdc/model/changefeed.go
  cdc/owner.go
  cmd/client_changefeed.go
  pkg/filter/errors.go
  tests/changefeed_error/conf/diff_config.toml
  tests/changefeed_error/conf/workload
  tests/changefeed_error/run.sh
Labels: LGT2, bug-fix, release-blocker

#669 remove events count check in cyclic test
  tests/cyclic_ab/run.sh
  tests/cyclic_abc/run.sh
  tests/cyclic_loopback/run.sh
Labels: LGT1

#670 sink: support config tidb txn mode in mysql sink
  cdc/sink/mysql.go
  tests/resolve_lock/run.sh
Labels: C: Sink, LGT1

#674 Support tz parameter when creating changefeed
  cmd/client_changefeed.go
  cmd/server.go
  tests/cli/run.sh
Labels: LGT2, bug-fix

#672 kv,util: check TiKV version before event feed and refine version check
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/server.go
  cmd/client.go
  pkg/util/check.go
  pkg/util/check_test.go
Labels: LGT2, release-blocker

#675 Fix start-ts in row changed event emitted from kafka consumer
  cdc/model/sink.go
  kafka_consumer/main.go
Labels: LGT2, bug-fix

#665 support to balance subtasks to new captures
  cdc/changefeed.go
  cdc/processor.go
  pkg/config/config.go
  pkg/scheduler/interface.go
  pkg/scheduler/table_number.go
  pkg/scheduler/table_number_test.go
Labels: C: Scheduler, LGT2, enhancement, release-blocker

#654 puller: support to decrease ts for frontier
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/frontier/heap.go
  cdc/puller/frontier/heap_test.go
  cdc/puller/puller.go
Labels: C: Puller, LGT2, bug-fix, release-blocker

#676 pkg: quote schema.table to avoid error in SQL syntax
  pkg/cyclic/mark.go
  tests/cli/run.sh
Labels: LGT2, bug-from-poc

#680 sink: fix wait group is not updated when exec with error
  cdc/server.go
  cdc/sink/mysql.go
Labels: C: Sink, LGT1

#682 *: fix cyclic replication issues with filter and ineligible tables
  cdc/changefeed.go
  cdc/entry/mounter.go
  cdc/model/changefeed.go
  cdc/model/sink.go
  cdc/owner.go
  cdc/sink/mysql.go
  cmd/client_changefeed.go
  cmd/util.go
  pkg/cyclic/filter.go
  pkg/cyclic/filter_test.go
  pkg/cyclic/mark/mark.go
  pkg/cyclic/mark/mark_test.go
  pkg/cyclic/replication.go
  pkg/cyclic/replication_test.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/quotes/quotes.go
  tests/cli/run.sh
  tests/cyclic_ab/conf/only_test_simple.toml
  tests/cyclic_ab/run.sh
Labels: LGT2, bug-fix

#688 *: fix typo of rebalance
  cdc/changefeed.go
  cdc/http_handler.go
  cdc/http_status.go
  cdc/owner.go
Labels: LGT2

#686 *: replace capture ID with address in metrics
  cdc/capture.go
  cdc/entry/mounter.go
  cdc/kv/client.go
  cdc/kv/etcd.go
  cdc/kv/metrics.go
  cdc/metrics_processor.go
  cdc/processor.go
  cdc/puller/entry_sorter.go
  cdc/puller/puller.go
  cdc/roles/storage/etcd.go
  cdc/server.go
  cdc/server_test.go
  cdc/sink/mqProducer/kafka.go
  cdc/sink/mqProducer/kafka_test.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  cdc/sink/statistics.go
  metrics/grafana/ticdc.json
  pkg/util/ctx.go
  pkg/util/ctx_test.go
  scripts/check-copyright.sh
  tests/availability/capture.sh
  tests/availability/owner.sh
  tests/multi_capture/run.sh
  tests/run.sh
Labels: LGT2, S: Usability

#693 processor: fix processor doesn't fully exit after `p.stop` is called
  cdc/processor.go
Labels: LGT2

#694 Fix chinese document link
  README.md
Labels: LGT2

#698 *: replace ddl-white-list with ddl-allow-list
  cdc/model/changefeed_test.go
  cmd/cmd_test.go
  pkg/config/filter.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: LGT2

#689 Stop changefeed automatically if one of processor exits
  cdc/model/changefeed.go
  cdc/model/errors.go
  cdc/model/owner.go
  cdc/owner.go
  cdc/processor.go
  tests/changefeed_auto_stop/conf/diff_config.toml
  tests/changefeed_auto_stop/conf/workload
  tests/changefeed_auto_stop/run.sh
Labels: LGT1, PTAL
