Repository pingcap/tiflow, pull requests merged in 2020-12, with the labels that each got.

#1139 *: update the tidb dependence and remove the replace line in go mod
  go.mod
  go.sum
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1135 *: refine capture and changefeed field in log
  cdc/capture.go
  cdc/changefeed.go
  cdc/kv/etcd.go
  cdc/owner.go
  cdc/processor.go
  cdc/puller/puller.go
  cdc/server.go
  cdc/sink/black_hole.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/statistics.go
  cdc/task.go
  pkg/util/ctx.go
  pkg/util/ctx_test.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1133 DDL: fix ErrSchemaStorageUnresolved
  cdc/entry/schema_storage.go
  cdc/processor.go
  pkg/retry/retry.go
  pkg/retry/retry_test.go
  tests/ddl_puller_lag/run.sh
Labels: C: DDL, PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT3, status/can-merge

#1073 *: enable oldvalue by default in master
  cdc/model/changefeed_test.go
  integration/framework/avro/kafka_single_table.go
  integration/framework/docker_env.go
  pkg/config/config.go
  tests/_utils/start_tidb_cluster_impl
  tests/_utils/start_tls_tidb_cluster_impl
Labels: PTAL, status/LGT2, status/can-merge

#1157 github: update issue template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/pull_request_template.md
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1155 cmd: remove default sink-uri and check for empty sink-uri before trying to create sink
  cmd/client_changefeed.go
  cmd/client_changefeed_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1154 *:some helper functions add error return value and add some unit tests in ctx_test.go
  cdc/owner.go
  cdc/processor.go
  pkg/util/ctx.go
  pkg/util/ctx_test.go
Labels: needs-cherry-pick-4.0, status/LGT3, status/can-merge

#1156 tests: add unit tests for cdc/puller/puller.go
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/testing.go
  cdc/model/kv.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/util/ctx_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1129 maxwell: fix some bug and refine output
  cdc/sink/codec/maxwell.go
  cdc/sink/codec/maxwell_test.go
Labels: C: Sink, PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1166 tests: add leak test check in Makefile, complete leak tests
  Makefile
  cdc/entry/mounter_test.go
  cdc/model/capture_test.go
  cdc/model/changefeed_test.go
  cdc/model/kv_test.go
  cdc/model/mounter_test.go
  cdc/model/owner_test.go
  cdc/model/schema_storage_test.go
  cdc/model/sink_test.go
  cdc/model/string_test.go
  cdc/owner_test.go
  cdc/puller/sorter_test.go
  cdc/sink/codec/json_test.go
  cmd/server_test.go
  pkg/util/gc_service_test.go
  pkg/util/testleak/leaktest.go
  scripts/add-leaktest.sh
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1180 Makefile: fix goimports not found in leak test check
  Makefile
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2

#1177 tests: add unit tests for mysql sink
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  pkg/cyclic/replication.go
  pkg/cyclic/replication_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1163 owner: fix owner doesn't clean up stale tasks
  cdc/owner.go
  cdc/owner_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1172 pipeline: refine pipeline, refactor processor part one
  errors.toml
  pkg/context/context.go
  pkg/context/context_test.go
  pkg/errors/errors.go
  pkg/pipeline/context.go
  pkg/pipeline/message.go
  pkg/pipeline/node.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/runner.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1190 processor: fix task status flushed too many before table is initialized
  cdc/model/owner.go
  cdc/processor.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2

#1194 tests: turn on the tidb_enable_change_multi_schema switch in some tests
  tests/common_1/run.sh
  tests/ddl_reentrant/run.sh
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1196 kv/client: fix gRPC connection pool, don't close conn when meeting error
  cdc/kv/client.go
Labels: PTAL, Priority/P0, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1185 pkg/notify: fix create receiver on closed notifier
  cdc/processor.go
  cdc/puller/entry_sorter.go
  cdc/puller/puller_test.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/producer/kafka/kafka.go
  errors.toml
  pkg/errors/errors.go
  pkg/notify/notify.go
  pkg/notify/notify_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1161 refactor: EtcdWorker
  errors.toml
  pkg/errors/errors.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/interfaces.go
  pkg/orchestrator/jsonstate/json_reactor_state.go
  pkg/orchestrator/jsonstate/json_reactor_state_test.go
  pkg/orchestrator/util/key_utils.go
  pkg/orchestrator/util/key_utils_test.go
Labels: C: Replica-model, PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT2, status/can-merge

#1209 *: update tidb dependence for release-4.0
  go.mod
  go.sum
Labels: PTAL, status/LGT2

#1212 owner: wait all task metadata cleaned before creating new changefeed
  cdc/owner.go
  cdc/processor.go
  tests/processor_stop_delay/conf/diff_config.toml
  tests/processor_stop_delay/run.sh
Labels: bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT2, status/can-merge

#1201 context: fix unstable tests
  pkg/context/context_test.go
Labels: PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT2, status/can-merge

#1217 *: Using the global singleton for pd client and tikv client, and fix pd client freeze
  cdc/capture.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/server.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT2

#1218 cpature: fix session done is not considered during handling task event
  cdc/capture.go
  tests/capture_session_done_during_task/conf/diff_config.toml
  tests/capture_session_done_during_task/run.sh
Labels: bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT2, status/can-merge

#1224 owner: fix memory accumulated when owner consume etcd update slow
  cdc/owner.go
Labels: bug-fix, severity/critical, status/LGT2

#1136 *: Update the errors dependence for release-4.0
  Makefile
  errors.toml
  go.mod
  go.sum
  tools/check/go.mod
  tools/check/go.sum
Labels: PTAL, status/LGT2, status/can-merge

#1225 owner: fix memory accumulated when owner consume etcd update slow
  cdc/owner.go
  cdc/owner_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2

#1210 sorter: Stabilize Unified Sorter
  .gitignore
  Makefile
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/backend_pool_test.go
  cdc/puller/sorter/file_backend.go
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/unified_sorter.go
  cdc/puller/sorter_test.go
  cdc/server.go
  cmd/client_changefeed.go
  cmd/server.go
  errors.toml
  pkg/config/sorter.go
  pkg/errors/errors.go
  pkg/workerpool/async_pool.go
  pkg/workerpool/async_pool_impl.go
  pkg/workerpool/async_pool_test.go
  pkg/workerpool/context.go
  pkg/workerpool/context_test.go
  pkg/workerpool/hash.go
  pkg/workerpool/pool.go
  pkg/workerpool/pool_impl.go
  pkg/workerpool/pool_test.go
  testing_utils/many_sorters_test/many_sorters.go
  testing_utils/many_sorters_test/many_sorters_test.go
  testing_utils/sorter_stress_test/sorter_stress.go
  tests/_utils/run_cdc_server
  tests/cdclog_s3/run.sh
  tests/ddl_puller_lag/run.sh
  tests/kafka_messages/run.sh
  tests/processor_panic/run.sh
  tests/unified_sorter/conf/workload
  tests/unified_sorter/run.sh
Labels: C: Puller, PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1151 test: add cases for clustered index
  tests/clustered_index/data/test.sql
Labels: PTAL, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1233 tests: add more unit tests in kv client
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/model/kv.go
  cdc/model/kv_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1237 capture: fix incorrect session aliveness detection
  cdc/capture.go
  cdc/capture_test.go
  cdc/processor.go
  pkg/etcd/client.go
  pkg/etcd/client_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1242 CI: enable specific tiflash branch in CI
  scripts/jenkins_ci/integration_test_common.groovy
  tests/clustered_index/run.sh
Labels: PTAL, S: TEST, status/LGT2, status/can-merge

#1246 CI: enable specific tiflash branch in CI
  scripts/jenkins_ci/integration_test_common.groovy
  tests/clustered_index/run.sh
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2

#1251 CI: fix tiflash parameter
  scripts/jenkins_ci/integration_test_common.groovy
Labels: PTAL, status/LGT2

#1250 sink: fix max-batch-size
  cdc/sink/mq.go
Labels: C: Sink, PTAL, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1226 docs: add metrics document and enhance TiCDC dashboard
  Makefile
  cdc/kv/metrics.go
  cdc/metrics.go
  cdc/metrics_owner.go
  cdc/metrics_processor.go
  cdc/owner.go
  cdc/puller/entry_sorter.go
  cdc/server.go
  cdc/sink/metrics.go
  docs/data-flow.dot
  docs/data-flow.svg
  docs/media/ticdc-dashboard-changefeed-1.png
  docs/media/ticdc-dashboard-changefeed-2.png
  docs/media/ticdc-dashboard-changefeed-3.png
  docs/media/ticdc-dashboard-events-1.png
  docs/media/ticdc-dashboard-events-2.png
  docs/media/ticdc-dashboard-events-3.png
  docs/media/ticdc-dashboard-overview.png
  docs/media/ticdc-dashboard-server.png
  docs/media/ticdc-dashboard-tikv-1.png
  docs/media/ticdc-dashboard-tikv-2.png
  docs/ticdc-grafana-dashboard.md
  metrics/alertmanager/ticdc.rules.yml
  metrics/grafana/ticdc.json
Labels: C: Docs, PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge
