Repository pingcap/tiflow, pull requests merged in 2020-08, with the labels that each got.

#816 Fix auto random enable detect
  cdc/sink/mysql.go
Labels: PTAL, status/LGT2, status/can-merge

#808 Support auto create sort dir in file sort mode, fix owner data race
  cdc/http_handler.go
  cdc/http_status.go
  cdc/owner.go
  cdc/processor.go
  cdc/server.go
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#799 mounter: support to output pre table info in ddl events
  cdc/changefeed.go
  cdc/entry/codec.go
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/model/schema_storage.go
  cdc/model/sink.go
  cdc/owner.go
  cdc/puller/mock_puller.go
  cdc/sink/black_hole.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#813 Fix bugs in Avro implementation
  cdc/sink/codec/schema_registry.go
  cdc/sink/codec/schema_registry_test.go
Labels: C: Sink, bug-fix, release-blocker, status/LGT2, status/can-merge

#708 sink: support to output old value
  cdc/entry/mounter.go
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/matcher.go
  cdc/kv/matcher_test.go
  cdc/kv/testing.go
  cdc/model/kv.go
  cdc/model/sink.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/puller/puller.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/json.go
  cdc/sink/common/common.go
  cdc/sink/common/common_test.go
  cdc/sink/dispatcher/default.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  pkg/config/config.go
  pkg/regionspan/span.go
  pkg/regionspan/span_test.go
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#801 perf: optimize get tso frequency
  cdc/kv/client.go
  cdc/kv/store_op.go
Labels: C: KV-client, status/LGT2, status/can-merge

#797 owner: includes stopped changefeed when calculating gc safepoint
  cdc/owner.go
  tests/gc_safepoint/conf/diff_config.toml
  tests/gc_safepoint/run.sh
Labels: PTAL, bug-fix, release-blocker, status/LGT2, status/can-merge

#815 owner: doesn't exit when creating changefeed failed
  cdc/owner.go
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#819 cdc: add metrics about pending rows and txn execution duration
  cdc/kv/client.go
  cdc/puller/puller.go
  cdc/sink/black_hole.go
  cdc/sink/common/common.go
  cdc/sink/metrics.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/sink.go
  cdc/sink/statistics.go
  metrics/grafana/ticdc.json
  pkg/regionspan/span.go
Labels: status/LGT2, status/can-merge

#796 mounter: support more column flag
  cdc/entry/mounter.go
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#818 Improve the performance of file sorter.
  cdc/puller/file_sorter.go
  go.mod
  go.sum
Labels: C: Puller, PTAL, S: Performance, status/LGT2, status/can-merge

#771 fix the bug about correctness of table migration when remove a table
  cdc/changefeed.go
  cdc/kv/etcd.go
  cdc/model/puller.go
  cdc/owner.go
  cdc/processor.go
  cdc/puller/entry_sorter.go
  cdc/puller/rectifier.go
  cdc/puller/rectifier_test.go
  cdc/roles/storage/etcd.go
  cdc/roles/storage/etcd_test.go
  cdc/sink/statistics.go
  tests/multi_source/main.go
  tests/multi_source/run.sh
Labels: C: Scheduler, PTAL, bug-fix, release-blocker, status/LGT2, status/can-merge

#820 README: update architecture diagram
  README.md
  docs/design/2020-03-04-ticdc-design-and-architecture-cn.md
  docs/media/cdc_architecture.png
  docs/media/cdc_architecture.svg
Labels: PTAL, status/LGT2, status/can-merge

#804 Add TicdcEventDataReader to parse ticdc data which consumed from kafka.
  demo/java/.gitignore
  demo/java/README.md
  demo/java/pom.xml
  demo/java/src/main/java/com/pingcap/ticdc/cdc/KafkaMessage.java
  demo/java/src/main/java/com/pingcap/ticdc/cdc/TicdcEventData.java
  demo/java/src/main/java/com/pingcap/ticdc/cdc/TicdcEventDecoder.java
  demo/java/src/main/java/com/pingcap/ticdc/cdc/TicdcEventFilter.java
  demo/java/src/main/java/com/pingcap/ticdc/cdc/key/TicdcEventKey.java
  demo/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventBase.java
  demo/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventColumn.java
  demo/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventDDL.java
  demo/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventResolve.java
  demo/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventRowChange.java
  demo/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventType.java
  demo/java/src/test/java/com/pingcap/ticdc/cdc/TicdcEventDecoderTest.java
  demo/java/src/test/resources/data/key/ddl_key_0
  demo/java/src/test/resources/data/key/ddl_key_1
  demo/java/src/test/resources/data/key/ddl_key_2
  demo/java/src/test/resources/data/key/row_key_0
  demo/java/src/test/resources/data/key/row_key_1
  demo/java/src/test/resources/data/key/row_key_2
  demo/java/src/test/resources/data/key/rts_key_0
  demo/java/src/test/resources/data/key/rts_key_1
  demo/java/src/test/resources/data/key/rts_key_2
  demo/java/src/test/resources/data/value/ddl_value_0
  demo/java/src/test/resources/data/value/ddl_value_1
  demo/java/src/test/resources/data/value/ddl_value_2
  demo/java/src/test/resources/data/value/row_value_0
  demo/java/src/test/resources/data/value/row_value_1
  demo/java/src/test/resources/data/value/row_value_2
  demo/java/src/test/resources/data/value/rts_value_0
  demo/java/src/test/resources/data/value/rts_value_1
  demo/java/src/test/resources/data/value/rts_value_2
Labels: PTAL, status/LGT2, status/can-merge

#822 fix the bug about adding table
  cdc/processor.go
  cdc/puller/rectifier.go
  tests/changefeed_auto_stop/run.sh
Labels: status/LGT2, status/can-merge

#825 Fix mysql sink may be blocked by network io wait
  cdc/sink/mysql.go
  tests/sink_hang/conf/diff_config.toml
  tests/sink_hang/run.sh
Labels: C: Sink, PTAL, status/LGT2, status/can-merge

#829 filter: using tidb-tools.filter to filter the system schemas
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: PTAL, status/LGT2, status/can-merge

#834 Fix compatibility of libzstd with different gcc version
  Makefile
  scripts/fix_lib_zstd.sh
Labels: PTAL, S: TEST, status/LGT2, status/can-merge

#831 Remove checkpoint ts tick and refine task status updater in processor
  cdc/changefeed.go
  cdc/kv/etcd.go
  cdc/owner.go
  cdc/processor.go
  scripts/jenkins_ci/integration_test_common.groovy
Labels: C: Replica-model, PTAL, status/LGT2, status/can-merge

#839 fix DDL may be lost if owner exits
  cdc/changefeed.go
  cdc/processor.go
  cdc/sink/mysql.go
  tests/kill_owner_with_ddl/conf/diff_config.toml
  tests/kill_owner_with_ddl/run.sh
Labels: C: Replica-model, PTAL, status/LGT2, status/can-merge

#830 sink & mounter: refine the struct of row changed events
  cdc/entry/mounter.go
  cdc/model/schema_storage.go
  cdc/model/sink.go
  cdc/owner_test.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/dispatcher/default_test.go
  cdc/sink/dispatcher/index_value.go
  cdc/sink/dispatcher/index_value_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  pkg/cyclic/filter.go
  pkg/cyclic/filter_test.go
Labels: PTAL, status/LGT2, status/can-merge

#833 *: add metric for FlushRowChangedEvents in sinkDriver
  cdc/metrics_processor.go
  cdc/processor.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge

#841 remove the delete field in row change event
  cdc/entry/mounter.go
  cdc/model/sink.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/json.go
  cdc/sink/mysql_test.go
Labels: PTAL, status/LGT2, status/can-merge

#835 cmd: fix cmd TLS usage
  cmd/client_changefeed.go
  cmd/util.go
  pkg/security/credential.go
  tests/cyclic_abc/run.sh
Labels: bug-fix, status/LGT2, status/can-merge

#826 Support write TiCDC log to S3.
  Makefile
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/model/kv.go
  cdc/model/sink.go
  cdc/owner.go
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/cdclog/utils.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/sink.go
  go.mod
  pkg/util/log_test.go
  proto/generate-proto.sh
  scripts/jenkins_ci/integration_test_common.groovy
  tests/cdclog_file/run.sh
  tests/cdclog_s3/run.sh
Labels: C: Sink, status/LGT3, status/can-merge

#827 Use batch replace in mysql sink to increase performance
  cdc/entry/mounter.go
  cdc/model/schema_storage.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: C: Sink, PTAL, status/LGT2, status/can-merge

#840 fix unstable test in sink hang
  cdc/sink/mysql.go
  tests/sink_hang/run.sh
Labels: PTAL, S: TEST, status/LGT2, status/can-merge

#848 fix panic when a columns that are not null by default are null
  cdc/entry/mounter.go
  tests/common_1/data/test.sql
Labels: bug-fix, status/LGT2, status/can-merge

#847 cdclog: fix ci
  tests/cdclog_file/run.sh
  tests/cdclog_s3/run.sh
Labels: status/LGT2, status/can-merge

#837 update tidb to 4.0
  cdc/entry/codec.go
  cdc/entry/codec_test.go
  cdc/entry/schema_storage_test.go
  cdc/kv/client_test.go
  cdc/model/schema_storage.go
  cdc/owner_test.go
  cdc/puller/mock_puller.go
  go.mod
  go.sum
  tests/resolve_lock/main.go
Labels: PTAL, status/LGT2, status/can-merge

#852 Support to configure multiple PDs in cdc cli
  cmd/client.go
  tests/_utils/start_tidb_cluster
  tests/_utils/start_tidb_cluster_impl
  tests/_utils/stop_tidb_cluster
  tests/_utils/test_prepare
  tests/autorandom/run.sh
  tests/availability/run.sh
  tests/batch_add_table/run.sh
  tests/cdc/run.sh
  tests/cdclog_file/run.sh
  tests/cdclog_s3/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/changefeed_error/run.sh
  tests/changefeed_finish/run.sh
  tests/changefeed_pause_resume/run.sh
  tests/changefeed_reconstruct/run.sh
  tests/cli/run.sh
  tests/common_1/run.sh
  tests/cyclic_ab/run.sh
  tests/cyclic_abc/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/file_sort/run.sh
  tests/gc_safepoint/run.sh
  tests/generate_column/run.sh
  tests/kill_owner_with_ddl/run.sh
  tests/many_pk_or_uk/run.sh
  tests/multi_capture/run.sh
  tests/multi_source/run.sh
  tests/partition_table/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/simple/run.sh
  tests/sink_hang/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/tiflash/run.sh
Labels: status/LGT2, status/can-merge

#845 revoke all leases when delete meta in cli
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cmd/client_meta.go
Labels: PTAL, status/LGT2, status/can-merge

#850 refine file gc in file sorter
  cdc/puller/file_sorter.go
  tests/file_sort/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#842 remove the indie-mark-col field in row change event
  cdc/entry/mounter.go
  cdc/model/schema_storage.go
  cdc/model/sink.go
  cdc/sink/dispatcher/default.go
  cdc/sink/dispatcher/default_test.go
  cdc/sink/dispatcher/interface.go
  cmd/client_changefeed.go
Labels: PTAL, status/LGT2, status/can-merge

#856 minor optimization for table number scheduler
  pkg/scheduler/table_number.go
  pkg/scheduler/table_number_test.go
Labels: C: Scheduler, PTAL, status/LGT2, status/can-merge

#854 filter: fix a bug about ignore the DDL mistakenly
  cdc/sink/mq.go
  cdc/sink/mysql.go
  go.mod
  go.sum
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: PTAL, bug-fix, status/LGT2, status/can-merge

#853 cdc/kv: limit EventFeed retry
  cdc/kv/client.go
Labels: C: KV-client, PTAL, status/LGT2, status/can-merge

#836 New integration test framework with Avro integration tests.
  Dockerfile
  Makefile
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/schema_registry.go
  cdc/sink/codec/schema_registry_test.go
  cdc/sink/mq.go
  docker-compose-avro.yml
  go.mod
  go.sum
  integration/README.md
  integration/case_alter.go
  integration/case_simple.go
  integration/framework/avro_kafka_docker_env.go
  integration/framework/avro_kafka_docker_env_test.go
  integration/framework/avro_kafka_single_table.go
  integration/framework/avro_kafka_single_table_test.go
  integration/framework/docker_compose_op.go
  integration/framework/docker_compose_op_test.go
  integration/framework/dsl.go
  integration/framework/env.go
  integration/framework/sql_batch_op.go
  integration/framework/sql_helper.go
  integration/framework/task.go
  integration/integration.go
  scripts/avro-local-test.sh
Labels: C: Sink, PTAL, S: TEST, status/LGT2, status/can-merge

#855 *: enhance metrics and exit log
  cdc/metrics_processor.go
  cdc/processor.go
  cdc/sink/mysql.go
  cdc/sink/statistics.go
  metrics/grafana/ticdc.json
  pkg/cyclic/filter.go
Labels: PTAL, enhancement, status/LGT2, status/can-merge

#851 cli: add unsafe sub command and hide it from the default help info
  cmd/client.go
  cmd/client_unsafe.go
Labels: PTAL, status/LGT2, status/can-merge

#843 remove keys field in row change event and move the `genKeys` function to mysql sink
  cdc/entry/mounter.go
  cdc/model/sink.go
  cdc/owner_test.go
  cdc/sink/causality.go
  cdc/sink/causality_test.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/codec/schema_registry_test.go
  cdc/sink/common/common.go
  cdc/sink/common/common_test.go
  cdc/sink/dispatcher/default.go
  cdc/sink/dispatcher/default_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  kafka_consumer/main.go
  pkg/cyclic/filter.go
  pkg/cyclic/filter_test.go
Labels: PTAL, status/LGT2, status/can-merge

#861 support force remove a changefeed, check removed/finished changefeed when creating
  cdc/http_handler.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/model/owner.go
  cdc/owner.go
  cmd/client.go
  cmd/client_changefeed.go
  cmd/util.go
  tests/cli/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#844 use S3 related API by import BR
  cdc/sink/cdclog/s3.go
  cdc/sink/codec/json.go
  go.mod
  go.sum
  tests/cdclog_s3/run.sh
Labels: C: Sink, status/LGT2, status/WIP, status/can-merge

#874 fix service gc safepoint key name
  tests/gc_safepoint/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#865 Hide sink uri in changefeed info
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner.go
  cdc/processor.go
Labels: PTAL, status/LGT2, status/can-merge

#879 owner: increase gc safepoint update frequency to 2s
  cdc/owner.go
  tests/gc_safepoint/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#882 ci: fix broken CI
  Makefile
Labels: status/LGT2, status/can-merge

#877 sink: rename mq producer package
  cdc/sink/mq.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  cdc/sink/producer/mq_producer.go
  cdc/sink/producer/pulsar/doc.go
  cdc/sink/producer/pulsar/option.go
  cdc/sink/producer/pulsar/producer.go
Labels: PTAL, status/LGT2, status/can-merge

#863 Add an option to support list paused/finished changefeed
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cmd/client.go
  cmd/client_changefeed.go
Labels: PTAL, S: Usability, status/LGT2, status/can-merge

#876 refine ssl option in sink scheme
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  tests/simple/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#881 mounter: fix three bugs about old value
  cdc/entry/codec.go
  cdc/entry/mounter.go
  cdc/kv/client.go
  cdc/kv/matcher.go
Labels: PTAL, status/LGT2, status/can-merge

#870 test: add a case about many types of column
  cdc/entry/mounter.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  tests/row_format/data/prepare.sql
  tests/row_format/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#889 filter: support add drop columns ddl
  pkg/filter/filter.go
  tests/common_1/data/test.sql
  tests/ddl_reentrant/run.sh
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#871 sink: update go mod && fix encoder bug in s3 sink
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  go.mod
  go.sum
Labels: C: Sink, bug-fix, release-blocker, status/LGT2, status/can-merge

#887 cmd: refine some update config usage
  cmd/client_changefeed.go
  cmd/util.go
  tests/cli/run.sh
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#867 sink: refine sink interface and mysql sink checkpoint reprting
  cdc/processor.go
  cdc/sink/black_hole.go
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  cdc/sink/txns_heap.go
  cdc/sink/txns_heap_test.go
  kafka_consumer/main.go
Labels: C: Replica-model, PTAL, release-blocker, status/LGT2, status/can-merge

#892 sink/kafka: zero partition is not valid
  cdc/sink/producer/kafka/kafka.go
Labels: PTAL, status/LGT2, status/can-merge

#875 Processor: fix Fatals and other potential problems when localResolvedTs < globalResolvedTs
  cdc/processor.go
  tests/processor_panic/run.sh
Labels: PTAL, bug-fix, release-blocker, status/LGT2, status/can-merge

#896 docs/media: add Apache Pulsar to cdc architecture
  docs/media/cdc_architecture.svg
Labels: status/LGT2, status/can-merge

#894 sink: fix table dispatcher
  cdc/sink/dispatcher/interface.go
  cdc/sink/dispatcher/switcher_test.go
Labels: PTAL, bug-fix, release-blocker, status/LGT2, status/can-merge

#897 kafka: fix get kafka partition of topic
  cdc/sink/producer/kafka/kafka.go
Labels: status/LGT2, status/can-merge
