Repository pingcap/tiflow, pull requests merged in 2020-11, with the labels that each got.

#1033 test: refine the integration tests script
  Makefile
  scripts/jenkins_ci/cdc_ghpr_integration_test.groovy
  scripts/jenkins_ci/cdc_ghpr_kafka_integration_test.groovy
  scripts/jenkins_ci/integration_test_common.groovy
  tests/run.sh
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1052 tests: fix syncpoint check in ddl
  tests/syncpoint/run.sh
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2

#1053 docs: Protocols Supported by TiCDC
  docs/design/2020-11-04-ticdc-protocol-list.md
Labels: C: Docs, PTAL, status/LGT2, status/can-merge

#968 entry: support decode kv from clustered index tables
  cdc/entry/codec.go
  cdc/entry/codec_test.go
  cdc/entry/mounter.go
  cdc/entry/schema_storage_test.go
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/testing.go
  cdc/model/schema_storage.go
  cdc/model/sink.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/puller/mock_puller.go
  go.mod
  go.sum
  tests/_utils/start_tidb_cluster_impl
  tests/_utils/start_tls_tidb_cluster_impl
  tests/_utils/stop_tidb_cluster
  tests/autorandom/conf/tidb_config.toml
  tests/changefeed_auto_stop/run.sh
  tests/clustered_index/conf/diff_config.toml
  tests/clustered_index/data/test.sql
  tests/clustered_index/run.sh
  tests/resolve_lock/main.go
Labels: PTAL, since-5.0, status/LGT2, status/can-merge

#1070 tests: add more test cases in pkg, remove unused functions
  pkg/flags/urls.go
  pkg/flags/urls_test.go
  pkg/httputil/_certificates/ca.pem
  pkg/httputil/_certificates/client-key.pem
  pkg/httputil/_certificates/client.pem
  pkg/httputil/_certificates/server-key.pem
  pkg/httputil/_certificates/server.pem
  pkg/httputil/httputil_test.go
  pkg/quotes/quotes_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1066 changefeed: fix goroutine leak when changefeed is paused or stopped
  cdc/changefeed.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/processor.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1068 tests: fix unstable test because of running concurrently
  cdc/puller/buffer_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1087 ci/action: upgrade golangci-lint-action to v2
  .github/workflows/check_and_build.yml
Labels: S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1089 tests: add more unit tests in cdc/model/sink.go
  cdc/model/sink_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1085 tests: add more unit tests in cdc/model/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/model/schema_storage_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1084 kafka_consumer: fix wrong timezone when 'TZ' env is not set and downstream is mysql
  kafka_consumer/main.go
Labels: bug-fix, first-time-contributor, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1045 owner: check if the checkpoint ts is less then gc safe time when create the changefeed
  cdc/model/changefeed_test.go
  cdc/owner.go
  cmd/client.go
  cmd/client_changefeed.go
  cmd/cmd_test.go
  cmd/util.go
  errors.toml
  integration/framework/docker_compose_op.go
  pkg/config/config.go
  pkg/errors/errors.go
  pkg/util/gc_service.go
  pkg/util/gc_service_test.go
  tools/check/go.mod
  tools/check/go.sum
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1072 owner: fix multiple owners exist when owner campaign key is deleted
  cdc/owner.go
  cdc/owner_test.go
  errors.toml
  pkg/errors/errors.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1081 tests: add more unit tests in cdc/model package
  cdc/model/capture_test.go
  cdc/model/changefeed_test.go
  cdc/model/kv_test.go
  cdc/model/mounter_test.go
  cdc/model/owner_test.go
  cdc/model/sink.go
  cdc/model/string.go
  cdc/model/string_test.go
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/cdclog/utils.go
  cdc/sink/mysql.go
  pkg/cyclic/replication.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1108 README: update build status badge link
  README.md
Labels: PTAL, status/LGT2, status/can-merge

#1079 sink: Kafka message length and batch size limit for Open Protocol
  cdc/sink/codec/avro.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/codec/maxwell.go
  cdc/sink/mq.go
  cdc/sink/producer/kafka/kafka.go
  integration/framework/avro/kafka_single_table.go
  integration/framework/canal/kafka_single_table.go
  integration/framework/task.go
  kafka_consumer/main.go
  tests/kafka_messages/conf/diff_config.toml
  tests/kafka_messages/conf/workload
  tests/kafka_messages/run.sh
Labels: C: Open-protocol, C: Sink, status/LGT2

#1069 Temporary fix for ErrSnapshotSchemaNotFound and ErrSchemaStorageGCed
  cdc/changefeed.go
  cdc/owner.go
  cdc/processor.go
  pkg/notify/notify_test.go
  tests/move_table/conf/diff_config.toml
  tests/move_table/conf/workload
  tests/move_table/main.go
  tests/move_table/run.sh
Labels: C: Replica-model, C: Scheduler, PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1100 kafka sink: increase the max retry of the producer of kafka
  cdc/sink/producer/kafka/kafka.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1116 metrics: add alert for tikv hibernate regions
  metrics/alertmanager/ticdc.rules.yml
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1111 tests: add unit tests in Kafka producer
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  pkg/util/testleak/leaktest.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT3, status/can-merge

#1119 server: disable tikv batch client in tidb library
  cmd/server.go
  cmd/server_test.go
Labels: enhancement, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1117 processor: remove redundant task stop operation
  cdc/processor.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1115 schemaStorage: reduce memory usage and add unit tests
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  go.mod
  go.sum
  pkg/filter/filter.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1126 sorter: disable failpoint in integration tests & fix code quality issues
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/memory_backend.go
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/unified_sorter.go
  tests/unified_sorter/run.sh
Labels: C: Puller, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1121 *: upgrade tidb to 4.0.9
  cdc/kv/testing.go
  go.mod
  go.sum
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT1

#1064 Update the errors dependence to the latest version
  Makefile
  cdc/kv/store_op.go
  cdc/kv/testing.go
  cdc/sink/cdclog/s3.go
  errors.toml
  go.mod
  go.sum
  tools/check/go.mod
  tools/check/go.sum
Labels: PTAL, status/LGT2, status/can-merge

#1131 tests: add unit tests in sink/mq module
  cdc/sink/mq.go
  cdc/sink/mq_test.go
  cdc/sink/statistics.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1132 mounter: add unit test in mounter
  cdc/entry/kv_entry_test.go
  cdc/entry/mounter_test.go
  cdc/entry/schema_storage_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1137 cmd: enable old value if protocol is maxwell
  cmd/client_changefeed.go
  cmd/client_changefeed_test.go
Labels: enhancement, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1138 .*: replace log.Fatal with log.Panic in CDC logic code
  cdc/changefeed.go
  cdc/kv/client.go
  cdc/model/sink.go
  cdc/processor.go
  cdc/puller/buffer.go
  cdc/puller/frontier/list.go
  cdc/puller/mock_puller.go
  cdc/puller/puller.go
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/file_backend.go
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/memory_backend.go
  cdc/puller/sorter/merger.go
  cdc/puller/sorter_test.go
  cdc/sink/black_hole.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/json.go
  cdc/sink/common/common.go
  cdc/sink/dispatcher/interface.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/producer/kafka/kafka.go
  pkg/config/config.go
  pkg/cyclic/filter.go
  pkg/hash/position_inertia.go
  pkg/regionspan/region_range_lock.go
  pkg/regionspan/span.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge
