Repository pingcap/tiflow, pull requests merged in 2020-07, with the labels that each got.

#703 Remove fmt.Sprintf when assembling SQLs
  cdc/sink/mysql.go
Labels: PTAL

#702 mysql-sink: add more performance related metrics
  cdc/sink/metrics.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  metrics/grafana/ticdc.json
Labels: C: Sink, LGT2

#706 sink: support to configure kafka-client-id in mq sink-uri
  cdc/sink/mq.go
  cdc/sink/mqProducer/kafka.go
  cdc/sink/mqProducer/kafka_test.go
  tests/simple/run.sh
Labels: C: Sink, LGT2

#699 cmd: support update changefeed config, in non-online way
  cmd/client_changefeed.go
  go.mod
  go.sum
  tests/cli/run.sh
Labels: LGT2, PTAL, S: Usability

#710 fix some tiny bugs in canal test cases
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/json_test.go
Labels: LGT1, S: TEST

#705 Refine some state transition when handling admin job
  cdc/http_handler.go
  cdc/http_status.go
  cdc/model/changefeed.go
  cdc/owner.go
  cmd/client.go
  cmd/client_changefeed.go
  cmd/util.go
  tests/cli/run.sh
Labels: LGT2, PTAL, S: Usability

#712 Add readme in integration test
  README.md
  tests/README.md
  tests/autorandom/run.sh
  tests/batch_add_table/run.sh
  tests/cdc/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/changefeed_error/run.sh
  tests/cli/run.sh
  tests/common_1/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/file_sort/run.sh
  tests/generate_column/run.sh
  tests/many_pk_or_uk/run.sh
  tests/multi_capture/run.sh
  tests/multi_source/run.sh
  tests/partition_table/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/simple/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/tiflash/run.sh
Labels: LGT1

#701 cyclic, cmd: qoute cyclic table name, fatal if loopback and fix a data race
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cmd/client.go
  cmd/root.go
  cmd/server.go
  cmd/util.go
  pkg/cyclic/filter.go
  pkg/cyclic/replication.go
  tests/cyclic_ab/run.sh
  tests/cyclic_loopback/run.sh
Labels: LGT2

#704 puller: fix a memory leak bug in the frontier
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_bench_test.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/frontier/heap.go
  cdc/puller/frontier/heap_test.go
  cdc/puller/frontier/list.go
  cdc/puller/frontier/list_test.go
  cdc/puller/puller.go
Labels: LGT2, bug-fix

#692 cdc: support partition table in cyclic replication
  cdc/changefeed.go
  cdc/processor.go
  tests/cyclic_abc/run.sh
Labels: C: Replica-model, LGT2

#715 Add log-level to cli command, replace sarama logger
  cmd/client.go
  pkg/util/log.go
Labels: LGT2, S: Usability

#717 Update tests guide for mac os
  Makefile
  tests/README.md
Labels: LGT2

#687 Kafka Connect Avro Support Part 1: AvroSchemaManager
  cdc/sink/codec/schema_registry.go
  cdc/sink/codec/schema_registry_test.go
  go.mod
  go.sum
  proto/canal/EntryProtocol.pb.go
Labels: C: Sink, LGT2

#713 Add rate limit to changefeed error, refine owner rate limit
  cdc/capture.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/server.go
  cdc/task_test.go
Labels: LGT2, PTAL

#720 puller: fix the encode bytes in span and add a fail-fast
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/testing.go
  cdc/model/kv.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/puller/buffer_test.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_bench_test.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/mock_puller.go
  cdc/puller/puller.go
  pkg/regionspan/region.go
  pkg/regionspan/region_range_lock.go
  pkg/regionspan/region_range_lock_test.go
  pkg/regionspan/region_test.go
  pkg/regionspan/span.go
  pkg/regionspan/span_test.go
Labels: LGT2

#721 Add changefeed summary in list command, add some shortcut
  cdc/http_handler.go
  cmd/client.go
  cmd/client_changefeed.go
  cmd/client_processor.go
Labels: LGT2, S: Usability

#735 remove incorrect kafka parameter
  cdc/sink/mqProducer/kafka.go
Labels: C: Sink, LGT1, PTAL

#732 Refine ddl execute log
  cdc/changefeed.go
  cdc/model/errors.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
Labels: LGT2, S: Usability

#737 Remove some unnecessary error log
  cdc/kv/client.go
  cdc/processor.go
Labels: S: Usability, status/LGT2, status/can-merge

#727 cdc, cmd: allow customized changefeed id
  cdc/http_handler.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/model/changefeed.go
  cdc/model/errors.go
  cmd/client_changefeed.go
  pkg/util/check.go
  pkg/util/check_test.go
  tests/cli/run.sh
Labels: S: Usability, status/LGT2, status/can-merge

#347 support TLS in cdc components
  cdc/capture.go
  cdc/http_status.go
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/store_op.go
  cdc/kv/testing.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/puller/puller.go
  cdc/server.go
  cmd/client.go
  cmd/client_changefeed.go
  cmd/root.go
  cmd/server.go
  cmd/test.go
  cmd/util.go
  go.mod
  pkg/httputil/httputil.go
  pkg/security/security.go
  pkg/util/check.go
  pkg/util/check_test.go
  pkg/util/log.go
  scripts/jenkins_ci/cdc_ghpr_integration_test.groovy
  tests/_utils/run_cdc_server
  tests/_utils/start_tidb_cluster
  tests/_utils/start_tls_tidb_cluster
  tests/_utils/test_prepare
  tests/enable_tls/certificates/ca.pem
  tests/enable_tls/certificates/client-key.pem
  tests/enable_tls/certificates/client.pem
  tests/enable_tls/certificates/server-key.pem
  tests/enable_tls/certificates/server.pem
  tests/enable_tls/run.sh
Labels: release-blocker, status/LGT2, status/can-merge

#741 Refine some metrics, remove name from TableReplicaInfo
  cdc/changefeed.go
  cdc/metrics_processor.go
  cdc/model/owner.go
  cdc/model/sink.go
  cdc/processor.go
  metrics/grafana/ticdc.json
Labels: release-blocker, status/LGT2, status/can-merge

#738 Fix incomplete changefeed schema info when owner reconstructs
  cdc/owner.go
  tests/changefeed_reconstruct/conf/diff_config.toml
  tests/changefeed_reconstruct/conf/workload
  tests/changefeed_reconstruct/run.sh
Labels: C: Scheduler, release-blocker, status/LGT2, status/can-merge

#733 Kafka Connect Avro Support Part 2: AvroEventBatchEncoder
  cdc/changefeed.go
  cdc/entry/mounter.go
  cdc/model/sink.go
  cdc/puller/mock_puller.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/schema_registry.go
  cdc/sink/codec/schema_registry_test.go
Labels: C: Sink, status/LGT2, status/can-merge

#744 docs: update the doc link of filter
  cmd/changefeed.toml
  cmd/cmd_test.go
Labels: status/LGT2, status/can-merge

#742 *: support ssl mysql sink
  cdc/owner.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/server.go
  cdc/server_test.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  cmd/client.go
  cmd/client_changefeed.go
  cmd/util.go
  kafka_consumer/main.go
  pkg/cyclic/mark/mark.go
  pkg/security/credential.go
  tests/_utils/run_sql
  tests/_utils/start_third_tidb_cluster
  tests/_utils/start_tidb_cluster
  tests/_utils/start_tls_tidb_cluster
  tests/_utils/test_prepare
  tests/cyclic_ab/run.sh
  tests/cyclic_abc/certificates/ca.pem
  tests/cyclic_abc/certificates/client-key.pem
  tests/cyclic_abc/certificates/client.pem
  tests/cyclic_abc/certificates/server-key.pem
  tests/cyclic_abc/certificates/server.pem
  tests/cyclic_abc/conf/diff_config_down_tls.toml
  tests/cyclic_abc/run.sh
  tests/enable_tls/run.sh
Labels: release-blocker, status/LGT2, status/can-merge

#751 support pulsar's sink.
  cdc/sink/mq.go
  cdc/sink/pulsar/doc.go
  cdc/sink/pulsar/option.go
  cdc/sink/pulsar/producer.go
  cdc/sink/sink.go
  go.mod
  go.sum
Labels: C: Sink, release-blocker, status/LGT2, status/can-merge

#753 Kafka Connect Avro Support Part 3: Basic Avro support
  cdc/changefeed.go
  cdc/entry/mounter.go
  cdc/model/sink.go
  cdc/owner.go
  cdc/sink/black_hole.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/schema_registry.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
Labels: C: Sink, release-blocker, status/LGT2, status/can-merge

#755 upgrade go.etcd.io/etcd to fix panic in unit test with go1.14
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge

#756 ci: retry when failed to start tidb cluster
  tests/_utils/start_tidb_cluster
  tests/_utils/start_tidb_cluster_impl
  tests/_utils/start_tls_tidb_cluster
  tests/_utils/start_tls_tidb_cluster_impl
Labels: PTAL, status/LGT2, status/can-merge

#759 Add a changefeed pause/resume test
  tests/changefeed_pause_resume/conf/diff_config.toml
  tests/changefeed_pause_resume/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#758 Fix Avro timestamp & duration
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/mq.go
Labels: PTAL, status/LGT3, status/can-merge

#761 fix the wrong metric which the checkpointts is stop
  cdc/processor.go
Labels: PTAL, status/LGT2, status/can-merge

#757 Write msyqlType to canal packets and add special handling for Blob & Text field types.
  cdc/entry/mounter.go
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
  pkg/util/bitflag.go
  pkg/util/bitflag_test.go
Labels: status/LGT2, status/can-merge

#747 *: support verify client cert common name
  cdc/http_status.go
  cmd/client.go
  cmd/server.go
  cmd/util.go
  pkg/security/credential.go
  tests/_utils/run_cdc_server
  tests/cyclic_abc/run.sh
Labels: C: Status-server, PTAL, status/LGT2, status/can-merge

#769 Fix statistics command panic
  cmd/client_changefeed.go
Labels: bug-fix, status/LGT2, status/can-merge

#762 Design doc for Avro support
  docs/design/2020-07-16-ticdc-avro-protocol-design.md
Labels: C: Docs, status/LGT2, status/can-merge

#777 mounter: ignore the error when the index info is not found
  cdc/entry/mounter.go
Labels: bug-from-poc, needs-cherry-pick-4.0, release-blocker, status/LGT2, status/can-merge

#780 mounter: ignore the error when the index info is not found (#777)
  cdc/entry/mounter.go
Labels: status/LGT1

#723 docs: add design document for new ha mechanism
  docs/design/2020-03-25-ticdc-high-availability-new-design-cn.md
  docs/media/ha-image1.png
  docs/media/ha-image2.png
  docs/media/ha-image3.png
  docs/media/ha-image4.png
  docs/media/ha-image5.png
  docs/media/ha-image6.png
  docs/media/ha-image7.png
Labels: C: Docs, status/LGT2, status/can-merge

#779 Fix data race in processor tables operation
  cdc/processor.go
Labels: PTAL, bug-fix, status/LGT2, status/can-merge

#750 Add check to sort dir when creating changefeed
  cdc/owner.go
  cdc/processor.go
  pkg/util/fileutil.go
  pkg/util/fileutil_test.go
Labels: PTAL, status/LGT2, status/can-merge

#760 Only record error history when error in admin job is not nil
  cdc/owner.go
Labels: PTAL, status/LGT2, status/can-merge

#764 cdc/sink: support Kafka SSL connection
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/schema_registry.go
  cdc/sink/codec/schema_registry_test.go
  cdc/sink/mq.go
  cdc/sink/mqProducer/kafka.go
  cmd/client.go
  kafka_consumer/main.go
  pkg/httputil/httputil.go
  scripts/jenkins_ci/cdc_ghpr_kafka_integration_test.groovy
  tests/_certificates/ca.pem
  tests/_certificates/client-key.pem
  tests/_certificates/client.pem
  tests/_certificates/kafka.server.keystore.jks
  tests/_certificates/kafka.server.truststore.jks
  tests/_certificates/server-key.pem
  tests/_certificates/server.pem
  tests/_utils/start_tidb_cluster_impl
  tests/cli/run.sh
  tests/cyclic_abc/run.sh
Labels: C: Sink, PTAL, status/LGT2, status/can-merge

#752 fix unit test in entry sorter
  cdc/puller/entry_sorter_test.go
Labels: status/LGT2, status/can-merge

#773 mounter: skip the DML of ineligible table
  cdc/entry/mounter.go
Labels: PTAL, bug-fix, status/LGT2, status/can-merge

#724 docs: add design document about auto gc safepoint
  docs/design/2020-04-13-ticdc-auto-gc-safepoint-1-cn.md
  docs/design/2020-04-13-ticdc-auto-gc-safepoint-2-cn.md
Labels: C: Docs, PTAL, status/LGT2, status/can-merge

#785 sink/mysql: fix wait group is not correctly updated when panic
  cdc/sink/mysql.go
Labels: C: Sink, PTAL, bug-fix, status/LGT2, status/can-merge

#789 cyclic: add start_timestamp to mark tables
  cdc/sink/mysql.go
  pkg/cyclic/mark/mark.go
  pkg/cyclic/replication.go
  tests/_utils/check_contains
  tests/cyclic_ab/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#778 *: refine the struct about row and ddl event
  cdc/changefeed.go
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/model/sink.go
  cdc/puller/mock_puller.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
Labels: PTAL, status/LGT2, status/can-merge

#782 owner: fix failed changefeed can't be removed
  cdc/owner.go
  tests/changefeed_error/run.sh
Labels: PTAL, S: Usability, status/LGT2, status/can-merge

#786 Fix docker-compose.yml and add support to start local Avro testing environment
  Dockerfile
  cdc/sink/codec/schema_registry.go
  docker-compose-avro.yml
  docker-compose.yml
  docker/config/jdbc-sink-connector.json
  scripts/avro-local-test.sh
Labels: PTAL, status/LGT2, status/can-merge

#793 file-sorter: fix fake resolved ts event breaks CRTs restraint
  cdc/puller/file_sorter.go
  tests/file_sort/conf/diff_config.toml
  tests/file_sort/run.sh
Labels: PTAL, bug-fix, status/LGT2, status/can-merge

#783 test: integration test for add and drop index
  tests/multi_source/main.go
Labels: PTAL, status/LGT2, status/can-merge

#357 proposal: update ticdc-mq-protocol-cn
  docs/design/2020-02-24-ticdc-mq-protocol-cn.md
  docs/design/2020-03-04-ticdc-design-and-architecture-cn.md
Labels: PTAL, status/LGT2, status/can-merge

#763 Support stop changefeed after checkpoint reaches target ts
  cdc/model/changefeed.go
  cdc/model/owner.go
  cdc/owner.go
  cdc/processor.go
  cdc/task.go
  cmd/client_changefeed.go
  cmd/util.go
  tests/changefeed_finish/conf/diff_config.toml
  tests/changefeed_finish/run.sh
Labels: PTAL, bug-fix, status/LGT2, status/can-merge

#770 Refactor: Let the encoder control sink's output related operation
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/mq.go
Labels: C: Sink, PTAL, status/LGT2, status/can-merge

#800 kafka: partition number can't be negative
  cdc/sink/mqProducer/kafka.go
Labels: PTAL, bug-fix, status/LGT2, status/can-merge

#802 Fix dml with database not found error in test
  tests/multi_source/main.go
Labels: PTAL, status/LGT2, status/can-merge

#809 Upgrade tidb related go modules to latest
  cdc/entry/mounter.go
  cdc/kv/client.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/java.go
  go.mod
  go.sum
  tests/dailytest/db.go
Labels: status/LGT2, status/can-merge

#814 update go mod to fix const value compatibilty in parser
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge

#805 sink/mysql: refactor, add background sink worker
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: PTAL, S: Performance, status/LGT2, status/can-merge
