Repository pingcap/tiflow, pull requests merged in 2020-05, with the labels that each got.

#529 Update dockerfile path in docker-compose.yml
  docker-compose.yml
Labels: LGT1

#532 *: decouple util from model
  cdc/changefeed.go
  cdc/entry/kv_entry_test.go
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/entry/schema_storage.go
  cdc/kv/client.go
  cdc/kv/etcd.go
  cdc/kv/testing.go
  cdc/model/changefeed.go
  cdc/model/kv.go
  cdc/model/string.go
  cdc/model/string_test.go
  cdc/model/txn.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/puller/buffer_test.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_bench_test.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/mock_puller.go
  cdc/puller/mock_puller_test.go
  cdc/puller/puller.go
  cdc/sink/dispatcher/interface.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  cmd/client.go
  cmd/cmd_test.go
  kafka_consumer/main.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/regionspan/region.go
  pkg/regionspan/region_range_lock.go
  pkg/regionspan/region_range_lock_test.go
  pkg/regionspan/region_test.go
  pkg/regionspan/span.go
  pkg/regionspan/span_test.go
Labels: LGT1, enhancement

#536 owner: fix cleanup tasks in some corner case
  cdc/owner.go
  tests/availability/capture.sh
  tests/availability/owner.sh
  tests/availability/processor.sh
  tests/availability/run.sh
Labels: LGT2, PTAL, S: HA

#534 schema: reduce memory usage when init the schema
  cdc/changefeed.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/kv/store_op.go
  cdc/kv/store_op_test.go
  cdc/owner.go
  cdc/processor.go
  cdc/puller/mock_puller.go
  cmd/client.go
Labels: LGT2, S: Performance

#528 owner: fix resouce cleanup when an owner exits
  cdc/capture.go
  cdc/owner.go
  cdc/server.go
  tests/availability/owner.sh
Labels: LGT2, S: HA

#531 client: Fix the issue that TiKV reconnecting may make CDC stuck for a while
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: C: KV-client, LGT2, bug-fix

#524 sink: the implements of the new sink interface
  cdc/changefeed.go
  cdc/entry/mounter.go
  cdc/kv/client_test.go
  cdc/metrics.go
  cdc/model/mounter.go
  cdc/model/mq.go
  cdc/model/mq_test.go
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/owner.go
  cdc/processor.go
  cdc/sink/black_hole.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/metrics.go
  cdc/sink/mq.go
  cdc/sink/mqProducer/kafka.go
  cdc/sink/mqProducer/metrics.go
  cdc/sink/mqProducer/mq_producer.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  cdc/sink/statistics.go
  kafka_consumer/main.go
  pkg/notify/notify.go
  pkg/notify/notify_test.go
Labels: C: Sink, LGT2

#545 owner: only dispatch stale task status during clean up
  cdc/owner.go
  tests/_utils/run_cdc_server
Labels: LGT1, S: HA, bug-fix

#481 cdc: update position and status as soon as possible
  cdc/changefeed.go
  cdc/kv/etcd.go
  cdc/owner.go
  cdc/processor.go
  cdc/roles/storage/etcd.go
  cdc/roles/storage/etcd_test.go
  cdc/sink/mq.go
  cdc/sink/mqProducer/kafka.go
  cdc/sink/mysql.go
  cdc/task.go
  cmd/ctrl.go
  pkg/notify/notify.go
  pkg/notify/notify_test.go
Labels: C: Replica-model, LGT1, P0, S: Performance

#547 task: use start-ts if changefeed status doesn't exist
  cdc/task.go
Labels: LGT1

#548 processor: refine log output when stopped by admin command
  cdc/processor.go
Labels: LGT1, S: Usability

#546 cmd: support pause/resume/remove changefeed
  cdc/capture.go
  cdc/http_handler.go
  cdc/http_status.go
  cdc/http_status_test.go
  cdc/model/capture.go
  cdc/owner.go
  cdc/server.go
  cdc/server_test.go
  cdc/task_test.go
  cmd/cli_changefeed.go
  cmd/client.go
  cmd/ctrl.go
  cmd/server.go
  cmd/util.go
  scripts/jenkins_ci/integration_test_common.groovy
  tests/_utils/run_cdc_server
  tests/availability/capture.sh
  tests/availability/owner.sh
  tests/availability/processor.sh
  tests/batch_add_table/run.sh
  tests/cdc/run.sh
  tests/cli/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/file_sort/run.sh
  tests/multi_capture/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/run.sh
  tests/simple/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/tiflash/run.sh
Labels: LGT2, S: Usability

#554 mounter: use a chan list to avoid CPU cost with select lock
  cdc/entry/mounter.go
Labels: LGT1, S: Performance

#553 test: refine integration test
  scripts/jenkins_ci/integration_test_common.groovy
  tests/dailytest/case.go
  tests/many_pk_or_uk/config.toml
  tests/many_pk_or_uk/diff_config.toml
  tests/many_pk_or_uk/main.go
  tests/many_pk_or_uk/run.sh
  tests/multi_data_type/conf/diff_config.toml
  tests/multi_data_type/data/prepare.sql
  tests/multi_data_type/run.sh
  tests/util/db.go
Labels: LGT1

#555 *: use TableName and rename Ts to CRTs
  cdc/changefeed.go
  cdc/entry/mounter.go
  cdc/kv/client.go
  cdc/kv/testing.go
  cdc/model/kv.go
  cdc/model/mounter.go
  cdc/model/sink.go
  cdc/model/txn.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/processor_test.go
  cdc/puller/buffer_test.go
  cdc/puller/entry_group.go
  cdc/puller/entry_group_test.go
  cdc/puller/entry_sorter.go
  cdc/puller/entry_sorter_test.go
  cdc/puller/file_sorter.go
  cdc/puller/mock_puller.go
  cdc/puller/puller.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/dispatcher/default.go
  cdc/sink/dispatcher/default_test.go
  cdc/sink/dispatcher/interface.go
  cdc/sink/dispatcher/rowid_test.go
  cdc/sink/dispatcher/table.go
  cdc/sink/dispatcher/table_test.go
  cdc/sink/dispatcher/ts.go
  cdc/sink/dispatcher/ts_test.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cmd/client_changefeed.go
  kafka_consumer/main.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  tests/_utils/run_cdc_server
Labels: LGT1

#565 kafka sink: fix data race in kafka sink
  cdc/sink/mqProducer/kafka.go
Labels: C: Sink, LGT1

#566 notify: fix data race and send on close chan in receiveCh
  pkg/notify/notify.go
  pkg/notify/notify_test.go
Labels: LGT1, PTAL

#551 fix replicate when pk/unique index is a generated column
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  tests/generate_column/conf/diff_config.toml
  tests/generate_column/data/prepare.sql
  tests/generate_column/run.sh
Labels: LGT1, bug-fix

#561 cmd: add dial timeout and verify sink connection status
  cdc/capture.go
  cdc/server.go
  cdc/sink/mysql.go
  cmd/client.go
  cmd/client_capture.go
  cmd/client_changefeed.go
  cmd/client_meta.go
  cmd/client_processor.go
  cmd/client_tso.go
  cmd/util.go
  tests/_utils/start_tidb_cluster
  tests/cli/run.sh
Labels: LGT2

#509 Cyclic replication
  cdc/changefeed.go
  cdc/entry/mounter.go
  cdc/kv/client.go
  cdc/kv/testing.go
  cdc/model/changefeed.go
  cdc/model/kv.go
  cdc/model/mounter.go
  cdc/model/txn.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/processor_test.go
  cdc/puller/buffer_test.go
  cdc/puller/entry_sorter.go
  cdc/puller/entry_sorter_test.go
  cdc/puller/file_sorter.go
  cdc/puller/mock_puller.go
  cdc/puller/puller.go
  cdc/sink/codec/json.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cmd/client.go
  cmd/client_changefeed.go
  go.mod
  pkg/cyclic/mark.go
  pkg/cyclic/mark_test.go
  pkg/cyclic/replication.go
  pkg/cyclic/replication_test.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  scripts/jenkins_ci/integration_test_common.groovy
  tests/cyclic_ab/conf/diff_config.toml
  tests/cyclic_ab/run.sh
  tests/cyclic_loopback/run.sh
Labels: LGT2

#538 support replicate DML of partition table
  cdc/changefeed.go
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/model/owner.go
  cdc/owner.go
  tests/partition_table/conf/diff_config.toml
  tests/partition_table/data/prepare.sql
  tests/partition_table/run.sh
Labels: LGT2

#574 sink: when context is done, send to chan will be block
  cdc/sink/mysql.go
Labels: C: Sink, LGT2

#570 *: check cluster version
  cdc/owner.go
  cdc/processor.go
  cdc/server.go
  cmd/client.go
  cmd/server.go
  go.mod
  go.sum
  pkg/util/check.go
  pkg/util/check_test.go
  tests/resolve_lock/main.go
Labels: LGT1

#581 *: update tidb/pd/parser/tidb-tools to the latest release-4.0
  cdc/entry/codec.go
  cdc/entry/codec_test.go
  go.mod
  go.sum
  tests/resolve_lock/main.go
Labels: LGT2

#577 metrics: some metrics optimization
  cdc/metrics_processor.go
  cdc/processor.go
  cdc/puller/puller.go
  metrics/grafana/ticdc.json
Labels: LGT2

#572 *: a new table migration mechanism
  cdc/changefeed.go
  cdc/entry/schema_storage.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/model/capture.go
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/owner.go
  cdc/processor.go
  cdc/roles/storage/etcd.go
  cdc/roles/storage/etcd_test.go
  pkg/notify/notify_test.go
  tests/_utils/run_cdc_server
  tests/_utils/start_tidb_cluster
  tests/availability/owner.sh
  tests/cyclic_ab/conf/diff_config.toml
  tests/resolve_lock/main.go
Labels: C: Replica-model, LGT1, P0

#578 process sorted RowChangedEvent in batch to increase throughput
  cdc/processor.go
Labels: C: Replica-model, LGT1, PTAL

#579 cmd: prevent ongoing requests being canceled by deadline exceeded
  cmd/client.go
  cmd/client_capture.go
  cmd/client_changefeed.go
  cmd/client_meta.go
  cmd/client_processor.go
  cmd/client_tso.go
  cmd/root.go
  cmd/server.go
  cmd/util.go
Labels: PTAL

#587 tests: enable unit test in puller module
  cdc/puller/entry_sorter_test.go
Labels: PTAL

#582 cyclic: fix panic on duplicate rows
  pkg/cyclic/mark.go
  pkg/cyclic/mark_test.go
  tests/resolve_lock/main.go
Labels: LGT1, bug-fix

#586 sink: refine close in kafka sink
  cdc/sink/mqProducer/kafka.go
Labels: C: Sink, LGT1

#559 test: Refine integration test, part two
  cdc/model/config.go
  cdc/model/txn.go
  cdc/puller/mock_puller.go
  tests/_utils/check_table_exists
  tests/cdc/cdc.go
  tests/dailytest/dailytest.go
  tests/dailytest/ddl.go
  tests/many_pk_or_uk/config.toml
  tests/many_pk_or_uk/main.go
  tests/multi_source/config.toml
  tests/multi_source/diff_config.toml
  tests/multi_source/main.go
  tests/multi_source/run.sh
  tests/resolve_lock/config.toml
  tests/resolve_lock/main.go
  tests/util/config.go
  tests/util/db.go
Labels: LGT1

#588 config: reduce the structure of config file
  cdc/changefeed.go
  cdc/model/changefeed.go
  cdc/owner.go
  cdc/processor.go
  cdc/sink/dispatcher/interface.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/sink.go
  cmd/changefeed.toml
  cmd/client_changefeed.go
  cmd/cmd_test.go
  cmd/util.go
  kafka_consumer/main.go
  pkg/config/config.go
  pkg/config/cyclic.go
  pkg/config/filter.go
  pkg/config/mounter.go
  pkg/config/sink.go
  pkg/cyclic/replication.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: PTAL

#585 *: add some fail-fast checks
  cdc/kv/client.go
  cdc/processor.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/frontier/list_test.go
  cdc/puller/puller.go
  cdc/sink/black_hole.go
  cdc/sink/codec/json.go
  cdc/sink/dispatcher/default.go
  tests/multi_source/run.sh
Labels: LGT2

#583 schedule: a schedule framework
  cdc/changefeed.go
  cdc/http_handler.go
  cdc/http_status.go
  cdc/kv/client.go
  cdc/kv/etcd.go
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/owner.go
  cdc/processor.go
  pkg/scheduler/interface.go
  pkg/scheduler/table_number.go
  pkg/scheduler/table_number_test.go
  pkg/scheduler/workload.go
  pkg/scheduler/workload_test.go
Labels: P0, PTAL

#595 scheduler: support to scheduler with cyclic replication
  cdc/changefeed.go
  cdc/kv/etcd_test.go
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/owner.go
  cdc/processor.go
  cdc/roles/storage/etcd_test.go
  pkg/cyclic/replication.go
  pkg/scheduler/interface.go
  pkg/scheduler/table_number.go
  pkg/scheduler/table_number_test.go
Labels: PTAL

#598 kvclient: avoid some atomic manipulation
  cdc/kv/client.go
Labels: LGT1

#594 schema: support to sync view ddl
  cdc/entry/schema_storage.go
  tests/common_1/conf/diff_config.toml
  tests/common_1/data/test.sql
  tests/common_1/run.sh
Labels: PTAL

#597 cli: log some critical information to stdout but not log file
  cmd/client.go
  cmd/root.go
  cmd/server.go
Labels: LGT1

#593 scheduler: support to scheduler manually
  cdc/changefeed.go
  cdc/http_handler.go
  cdc/http_status.go
  cdc/owner.go
  cmd/cmd_test.go
  pkg/config/config.go
  pkg/config/scheduler.go
  pkg/scheduler/interface.go
  pkg/scheduler/table_number.go
  pkg/scheduler/table_number_test.go
  pkg/util/check.go
  pkg/util/check_test.go
Labels: PTAL
