Repository pingcap/tiflow, pull requests merged in 2021-01, with the labels that each got.

#1264 *: fix copyright check
  scripts/check-copyright.sh
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1206 refactor: EtcdWorker adjustment
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/interfaces.go
  pkg/orchestrator/jsonstate/json_reactor_state.go
  pkg/orchestrator/jsonstate/json_reactor_state_test.go
  pkg/orchestrator/util/key_utils.go
  pkg/orchestrator/util/key_utils_test.go
Labels: C: Replica-model, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1248 support old values deserialize
  demo/java/src/main/java/com/pingcap/ticdc/cdc/TicdcEventDecoder.java
  demo/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventRowChange.java
Labels: PTAL, first-time-contributor, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1272 *: fix copyright check (#1264)
  scripts/check-copyright.sh
Labels: PTAL, status/LGT2, status/can-merge, type/4.0-cherry-pick

#1276 github: update pull request template
  .github/pull_request_template.md
Labels: PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1269 owner: fix cleanup stale tasks before capture info is constructed
  cdc/owner.go
  cdc/owner_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1262 sorter: unified sorter metrics adjustments
  cdc/owner.go
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/file_backend.go
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/memory_backend.go
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/metrics.go
  cdc/puller/sorter/unified_sorter.go
  cmd/server.go
  docs/ticdc-grafana-dashboard.md
  metrics/grafana/ticdc.json
Labels: C: Puller, PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1279 sink/mysql: rollback txn to recycle db conn, refine timeout param in db conn
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: C: Sink, PTAL, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1249 owner: add more observations for owner operation
  cdc/metrics.go
  cdc/metrics_server.go
  cdc/owner.go
  cdc/processor.go
  cdc/server.go
  cdc/server_test.go
  docs/media/ticdc-dashboard-server.png
  docs/ticdc-grafana-dashboard.md
  metrics/grafana/ticdc.json
  pkg/httputil/httputil.go
Labels: PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1291 owner: add error message for owner ddl errors
  cdc/changefeed.go
  cdc/owner.go
  tests/changefeed_error/run.sh
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1289 ci: refine ci script to make downloading logs easier
  scripts/jenkins_ci/integration_test_common.groovy
Labels: PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0-rc, status/LGT2, status/can-merge

#1301 sink: Encoder configuration unit tests
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/mq_test.go
  cdc/sink/producer/pulsar/producer.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1267 kv/client: remove unnecessary blocking parameter
  cdc/kv/client.go
Labels: C: KV-client, PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1313 test: fix github action no space left
  .github/workflows/integration.yml
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1320 tests: cleanup binaries and cluster data before each run
  tests/run.sh
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2

#1247 *: fix the output in changefeed out of order
  cdc/changefeed.go
  cdc/metrics.go
  cdc/metrics_processor.go
  cdc/processor.go
  cdc/puller/rectifier.go
  cdc/puller/rectifier_test.go
  cdc/sink/manager.go
  cdc/sink/manager_test.go
  cdc/sink/metrics.go
  docs/data-flow.dot
  docs/data-flow.svg
  docs/ticdc-grafana-dashboard.md
  metrics/grafana/ticdc.json
  tests/owner_remove_table_error/conf/diff_config.toml
  tests/owner_remove_table_error/run.sh
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1309 processor: fix error chan buffer full will block the whole server
  cdc/processor.go
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/mq.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/pulsar/producer.go
  tests/processor_err_chan/conf/diff_config.toml
  tests/processor_err_chan/run.sh
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1293 tests: test gRPC stream send error in kv client
  cdc/kv/client_test.go
Labels: C: KV-client, PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1319 tests: test prewrite and commit out of order before initialized
  cdc/kv/client_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1311 sorter: unified sorter metrics adjustments (#1262)
  cdc/owner.go
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/file_backend.go
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/memory_backend.go
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/metrics.go
  cdc/puller/sorter/unified_sorter.go
  cmd/server.go
  docs/ticdc-grafana-dashboard.md
  metrics/grafana/ticdc.json
Labels: status/LGT1, status/can-merge, type/4.0-cherry-pick

#1327 ci: support specific kafka version in integration test
  scripts/jenkins_ci/cdc_ghpr_kafka_integration_test.groovy
  scripts/jenkins_ci/integration_test_common.groovy
  tests/_utils/test_prepare
  tests/autorandom/run.sh
  tests/batch_add_table/run.sh
  tests/capture_session_done_during_task/run.sh
  tests/cdc/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/changefeed_error/run.sh
  tests/changefeed_finish/run.sh
  tests/changefeed_pause_resume/run.sh
  tests/changefeed_reconstruct/run.sh
  tests/cli/run.sh
  tests/clustered_index/run.sh
  tests/common_1/run.sh
  tests/ddl_puller_lag/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/force_replicate_table/run.sh
  tests/gc_safepoint/run.sh
  tests/generate_column/run.sh
  tests/kafka_messages/run.sh
  tests/kafka_sink_error_resume/run.sh
  tests/many_pk_or_uk/run.sh
  tests/move_table/run.sh
  tests/multi_capture/run.sh
  tests/multi_source/run.sh
  tests/new_ci_collation/run.sh
  tests/partition_table/run.sh
  tests/processor_err_chan/run.sh
  tests/processor_panic/run.sh
  tests/processor_resolved_ts_fallback/run.sh
  tests/processor_stop_delay/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/simple/run.sh
  tests/sink_hang/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/tiflash/run.sh
  tests/unified_sorter/run.sh
Labels: PTAL, S: TEST, status/LGT2, status/can-merge

#1298 tests: test TiKV is not compatible with TiCDC to simulate rolling update
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: C: KV-client, PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1325 tests: kv client should handle event with invalid request id
  cdc/kv/client_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1335 processor: fix race when exit the processor
  cdc/processor.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1317 tests: kv client returns error when meets Compatibility error
  cdc/kv/client_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1304 kvclient: filter the old value if old-value is disabled
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/matcher.go
  cdc/kv/matcher_test.go
  tests/multi_changefeed/conf/changefeed1.toml
  tests/multi_changefeed/conf/changefeed2.toml
  tests/multi_changefeed/run.sh
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1303 http_status: fix debug info panic on none owner node
  cdc/http_status.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/processor_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1340 metrics: grafana dashboards support multiple cluster
  metrics/grafana/ticdc.json
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1312 metrics: cleanup when table removed or processor stopped if necessary
  cdc/processor.go
  metrics/grafana/ticdc.json
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1353 metrics: use tidb_cluster label get variable values
  metrics/grafana/ticdc.json
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1356 test: fix unstable multi changefeed integration test cases
  tests/multi_changefeed/run.sh
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1332 processor: fix addTable waiting for done
  cdc/processor.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1352 owner: prevent table start-ts regressions (#1236)
  cdc/changefeed.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/processor.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/interfaces.go
  pkg/orchestrator/jsonstate/json_reactor_state.go
  testing_utils/cdc_state_checker/cdc_monitor.go
  testing_utils/cdc_state_checker/main.go
  testing_utils/cdc_state_checker/reactor.go
  testing_utils/cdc_state_checker/state.go
  tests/_utils/check_cdc_state_log
  tests/_utils/start_tidb_cluster_impl
  tests/_utils/start_tls_tidb_cluster_impl
  tests/_utils/stop_tidb_cluster
  tests/autorandom/run.sh
  tests/availability/run.sh
  tests/batch_add_table/run.sh
  tests/capture_session_done_during_task/run.sh
  tests/cdc/run.sh
  tests/cdclog_file/run.sh
  tests/cdclog_s3/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/changefeed_error/run.sh
  tests/changefeed_finish/run.sh
  tests/changefeed_pause_resume/run.sh
  tests/changefeed_reconstruct/run.sh
  tests/cli/run.sh
  tests/common_1/run.sh
  tests/cyclic_ab/run.sh
  tests/cyclic_abc/run.sh
  tests/ddl_puller_lag/run.sh
  tests/ddl_reentrant/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/force_replicate_table/run.sh
  tests/gc_safepoint/run.sh
  tests/generate_column/run.sh
  tests/kafka_messages/run.sh
  tests/kafka_sink_error_resume/run.sh
  tests/kill_owner_with_ddl/run.sh
  tests/many_pk_or_uk/run.sh
  tests/move_table/run.sh
  tests/multi_capture/run.sh
  tests/multi_source/run.sh
  tests/new_ci_collation/run.sh
  tests/partition_table/run.sh
  tests/processor_panic/run.sh
  tests/processor_resolved_ts_fallback/run.sh
  tests/processor_stop_delay/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/simple/run.sh
  tests/sink_hang/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/syncpoint/run.sh
  tests/tiflash/run.sh
  tests/unified_sorter/run.sh
Labels: C: Replica-model, PTAL, bug-fix, status/LGT1, status/can-merge, type/4.0-cherry-pick

#1338 README: add info and fix typos
  README.md
Labels: needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1343 tests: check kv client can resolve lock as expected
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1282 owner: check update safepoint error
  cdc/changefeed.go
  cdc/owner.go
  cdc/owner_test.go
  errors.toml
  pkg/errors/errors.go
  pkg/filter/errors.go
  pkg/util/gc_service.go
  pkg/util/gc_service_test.go
  tests/changefeed_error/run.sh
Labels: C: Replica-model, PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1345 tests: check kv client can handle some assert normally
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1342 *: show version in capture info and changefeed info
  cdc/capture.go
  cdc/model/capture.go
  cdc/model/capture_test.go
  cdc/model/changefeed.go
  cdc/processor.go
  cmd/client_changefeed.go
  tests/processor_err_chan/run.sh
Labels: PTAL, status/LGT2, status/can-merge

#1357 tests: check kv client can drop events after region feed is stopped
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1362 ci: fix rm return error cannot remove
  tests/run.sh
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1358 cli: adjust default sort-dir and add warnings
  cmd/client_changefeed.go
  cmd/client_changefeed_test.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1336 kv-client: fix stream is not recycled when meeting recv error
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1371 sink: fix atomicity of transactions is broken
  cdc/sink/common/common.go
  cdc/sink/common/common_test.go
  cdc/sink/mysql_test.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1374 tests: fix data race in unit test
  cdc/kv/client_test.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1379 metrics: enable all/multi query for changefeed, enable multi for capture
  metrics/grafana/ticdc.json
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1382 *: update tidb version to 4.0.11
  go.mod
  go.sum
Labels: PTAL, status/LGT1
