Repository pingcap/tiflow, pull requests merged in 2021-09, with the labels that each got.

#2697 tests: use small scale to stabilize region merge test
  tests/region_merge/run.sh
Labels: component/test, status/LGT2, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2689 github workflow: add a auto assign bug github action
  .github/workflows/assign_bugs_questions_project.yml
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#2665 sorter: fix memory leak in memoryBackEnd
  cdc/puller/sorter/memory_backend.go
  cdc/puller/sorter/memory_backend_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2652 *: clean old owner related codes
  cdc/server.go
  cdc/server_test.go
  cdc/sink/mysql.go
  pkg/config/config.go
  pkg/cyclic/filter.go
  tests/cyclic_abc/run.sh
Labels: status/ptal, component/replica-model, status/LGT1, status/can-merge, size/M, cherry-pick-approved, require-LGT1, release-note-none

#2645 sink: clean up useless WaitPrepare call
  cdc/model/mounter.go
  cdc/processor/pipeline/cyclic_mark.go
  cdc/processor/pipeline/cyclic_mark_test.go
  cdc/processor/pipeline/sink.go
Labels: status/LGT2, status/can-merge, size/L, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2214 puller/sorter: remove manual GC settings
  cdc/puller/sorter/backend_pool.go
Labels: type/bugfix, status/LGT1, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, require-LGT1, needs-cherry-pick-release-5.1, component/sorter, needs-cherry-pick-release-5.2

#2699 kv: reduce gRPC window size to avoid OOM
  cdc/kv/client.go
Labels: type/bugfix, component/kv-client, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2716 pipeline: set table status to stopped after sink is closed
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table.go
  pkg/pipeline/message.go
Labels: subject/correctness, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2686 metrics: add more metrics about kv client and gRPC stream
  cdc/kv/client.go
  cdc/kv/metrics.go
  cdc/kv/region_worker.go
  cdc/kv/token_region.go
  cdc/processor/pipeline/puller.go
  metrics/grafana/ticdc.json
Labels: status/ptal, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, component/metrics-logging, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2717 tests: fix unstable integration_test gc_safepoint
  tests/gc_safepoint/run.sh
Labels: component/test, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, first-time-contributor, needs-cherry-pick-release-5.0, size/S, contribution, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2696 cli(refactor): enable new cmds and cleanup old cmds
  cmd/cdc/main.go
  cmd/client.go
  cmd/client_capture.go
  cmd/client_changefeed.go
  cmd/client_changefeed_test.go
  cmd/client_processor.go
  cmd/client_tso.go
  cmd/client_unsafe.go
  cmd/cmd_test.go
  cmd/root.go
  cmd/util.go
  cmd/util_test.go
  pkg/cmd/cli/cli_capture.go
  pkg/cmd/cli/cli_changefeed.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/cmd/cli/cli_changefeed_helper_test.go
  pkg/cmd/cli/cli_processor.go
  pkg/cmd/cmd.go
  pkg/cmd/util/changefeed.toml
  pkg/cmd/util/helper.go
  pkg/cmd/util/helper_test.go
  pkg/cmd/util/ticdc.toml
Labels: status/LGT2, status/can-merge, size/XXL, component/cli, release-note-none, needs-cherry-pick-release-5.2

#2732 tests: clean old owner integration tests
  cdc/kv/client_v2.go
  tests/availability/owner.sh
  tests/capture_session_done_during_task/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/changefeed_error/run.sh
  tests/ddl_puller_lag/run.sh
  tests/gc_safepoint/run.sh
  tests/kill_owner_with_ddl/run.sh
  tests/owner_remove_table_error/run.sh
  tests/processor_err_chan/run.sh
  tests/processor_panic/run.sh
  tests/processor_stop_delay/run.sh
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note-none

#2491 *: update tidb and tikv/client-go
  cdc/capture/http_handler.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/puller/mock_puller.go
  cdc/sink/cdclog/s3.go
  cdc/sink/cdclog/utils.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_test.go
  go.mod
  go.sum
  pkg/errors/helper_test.go
  pkg/txnutil/lock_resolver.go
  pkg/util/gc_service_test.go
  proto/EntryProtocol.proto
  proto/benchmark/CraftBenchmark.pb.go
  proto/canal/CanalProtocol.pb.go
  proto/canal/EntryProtocol.pb.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#2617 sink: reduce lock competition during flushBackendSink
  cdc/sink/manager.go
  cdc/sink/manager_test.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2753 go-mod: upgrade pulsar-client-go
  Makefile
  go.mod
  go.sum
  scripts/fix_lib_zstd.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none

#2769 github: fix feature request label in issue template
  .github/ISSUE_TEMPLATE/feature-request.md
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#2764 sink: fix codec json encoding with non binary string
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
Labels: status/ptal, type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2602 http: add unit test for http validator
  cdc/capture/http_validator.go
  cdc/capture/http_validator_test.go
  cdc/capture/main_test.go
  go.mod
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-5.2

#2778 server: when init data dir, skip if get changefeed info failed.
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/server.go
  cdc/server_test.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2756 lint: bump lint version and remove useless tools and test code
  .golangci.yml
  Makefile
  pkg/pipeline/pipeline_test.go
  tests/resolve_lock/main.go
  tools/check/go.mod
  tools/check/go.sum
  tools/check/revive.toml
Labels: status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none

#2780 github: add flaking test report template
  .github/ISSUE_TEMPLATE/flaking-test.md
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#2772 fix(test): remove use-rowid key in test/*/conf/*.toml
  tests/autorandom/conf/diff_config.toml
  tests/availability/owner.sh
  tests/batch_add_table/conf/diff_config.toml
  tests/capture_session_done_during_task/conf/diff_config.toml
  tests/capture_suicide_while_balance_table/conf/diff_config.toml
  tests/changefeed_auto_stop/conf/diff_config.toml
  tests/changefeed_error/conf/diff_config.toml
  tests/changefeed_finish/conf/diff_config.toml
  tests/changefeed_pause_resume/conf/diff_config.toml
  tests/changefeed_reconstruct/conf/diff_config.toml
  tests/clustered_index/conf/diff_config.toml
  tests/common_1/conf/diff_config.toml
  tests/cyclic_ab/conf/diff_config.toml
  tests/cyclic_abc/conf/diff_config_down_tls.toml
  tests/cyclic_abc/conf/diff_config_up_down.toml
  tests/ddl_reentrant/conf/diff_config.toml
  tests/ddl_sequence/conf/diff_config.toml
  tests/drop_many_tables/conf/diff_config.toml
  tests/gc_safepoint/conf/diff_config.toml
  tests/generate_column/conf/diff_config.toml
  tests/kafka_messages/conf/diff_config.toml
  tests/kafka_sink_error_resume/conf/diff_config.toml
  tests/kill_owner_with_ddl/conf/diff_config.toml
  tests/kv_client_stream_reconnect/conf/diff_config.toml
  tests/many_pk_or_uk/diff_config.toml
  tests/move_table/conf/diff_config.toml
  tests/multi_capture/conf/diff_config.toml
  tests/multi_source/diff_config.toml
  tests/new_ci_collation/conf/diff_config.toml
  tests/owner_remove_table_error/conf/diff_config.toml
  tests/partition_table/conf/diff_config.toml
  tests/processor_err_chan/conf/diff_config.toml
  tests/processor_panic/diff_config.toml
  tests/processor_resolved_ts_fallback/conf/diff_config.toml
  tests/processor_stop_delay/conf/diff_config.toml
  tests/region_merge/conf/diff_config.toml
  tests/resolve_lock/diff_config.toml
  tests/row_format/conf/diff_config.toml
  tests/sink_hang/conf/diff_config.toml
  tests/sink_retry/conf/diff_config.toml
  tests/split_region/conf/diff_config.toml
  tests/tiflash/conf/diff_config.toml
  tests/unified_sorter/conf/diff_config.toml
Labels: status/LGT2, status/can-merge, first-time-contributor, size/M, release-note-none, needs-cherry-pick-release-5.2

#2801 owner: refine some typos
  cdc/model/changefeed.go
  cdc/owner/async_sink.go
  cdc/owner/feed_state_manager.go
  cdc/owner/owner.go
  cdc/owner/scheduler.go
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#2807 github: fix broken templeate
  .github/ISSUE_TEMPLATE/flaking-test.md
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#2779 test: fix TestTaskError and TestMultiError flaky tests
  pkg/workerpool/pool_test.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2806 owner: remove deprecated done operation
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/owner/scheduler_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  pkg/scheduler/table_number_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#2763 metrics: add data flow metrics
  cdc/entry/metrics.go
  cdc/entry/mounter.go
  cdc/processor/pipeline/sink.go
  cdc/processor/processor.go
  cdc/sink/manager.go
  cdc/sink/manager_test.go
  cdc/sink/metrics.go
  cdc/sink/statistics.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, component/metrics-logging, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2827 cli(fix): ignore the global flag for changefeed update command
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_changefeed_update_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-5.2

#2838 tests: fix stop sequence of test binaries
  tests/_utils/stop_tidb_cluster
Labels: component/test, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2833 test(entry): migrate test-infra to testify for cdc/entry pkg
  cdc/entry/codec_test.go
  cdc/entry/main_test.go
  cdc/entry/mounter_test.go
  cdc/entry/schema_storage_test.go
  go.mod
  go.sum
Labels: component/test, status/LGT2, status/can-merge, size/XXL, release-note

#2824 tests: fix unstable integration_test in kafka consumer
  tests/capture_session_done_during_task/run.sh
  tests/changefeed_finish/run.sh
  tests/changefeed_pause_resume/run.sh
  tests/changefeed_reconstruct/run.sh
  tests/gc_safepoint/run.sh
  tests/kafka_sink_error_resume/run.sh
  tests/kv_client_stream_reconnect/run.sh
  tests/processor_err_chan/run.sh
  tests/processor_stop_delay/run.sh
  tests/sink_hang/run.sh
Labels: component/test, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2837 puller: refine some typos
  cdc/puller/frontier/frontier.go
  cdc/puller/puller.go
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#2512 owner, gcutil: always update service GC safepoint when owner finds new changefeeds
  cdc/capture/capture.go
  cdc/capture/http_validator.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/gc_manager_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  docs/ticdc-gc-safepoint.svg
  docs/ticdc-gc-safepoint.wsd
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_unsafe_delete_service_gc_safepoint.go
  pkg/cmd/cli/cli_unsafe_reset.go
  pkg/txnutil/gc/doc.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_manager_test.go
  pkg/txnutil/gc/gc_service.go
  pkg/txnutil/gc/gc_service_test.go
  pkg/txnutil/gc/testing.go
  pkg/util/gc_service.go
  tests/changefeed_error/run.sh
  tests/gc_safepoint/run.sh
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2840 cli: better prompting for flags that cannot be updated
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_changefeed_update_test.go
  pkg/util/testleak/leaktest.go
Labels: status/LGT2, status/can-merge, size/M, release-note

#2754 action: fix chaos workflow
  .github/workflows/chaos.yaml
  chaos/manifests/upstream.yaml
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#2823 kv: Remove old kvclient related code.
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
Labels: status/LGT2, status/can-merge, size/XXL, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2841 *: fix dml not replicate when add partition about partition table without valid index
  cdc/entry/schema_storage.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, first-time-contributor, needs-cherry-pick-release-5.0, size/XS, contribution, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2842 tests: iterate all cases in http api test
  tests/http_api/run.sh
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-5.2

#2713 check: refine CheckClusterVersion
  cdc/model/owner.go
  cdc/server.go
  pkg/cmd/factory/factory_impl.go
  pkg/version/check.go
  pkg/version/check_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, type/enhancement

#2835 *: clean useless code && improvement the code struct
  cdc/capture/capture.go
  cdc/capture/http_handler.go
  cdc/http_status.go
  cdc/kv/client_test.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/kv/grpc_pool_impl_test.go
  cdc/kv/metrics.go
  cdc/metrics.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/owner/scheduler.go
  cdc/owner/scheduler_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/server.go
  cdc/server_test.go
  pkg/cmd/cli/cli_capture_list.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/cmd/cli/cli_changefeed_list.go
  pkg/cmd/cli/cli_changefeed_pause.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_changefeed_remove.go
  pkg/cmd/cli/cli_changefeed_resume.go
  pkg/cmd/cli/cli_changefeed_statistics.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_processor_list.go
  pkg/cmd/cli/cli_processor_query.go
  pkg/cmd/cli/cli_unsafe_reset.go
  pkg/cmd/cli/cli_unsafe_show_metadata.go
  pkg/cmd/factory/factory.go
  pkg/cmd/factory/factory_impl.go
  pkg/cmd/util/helper.go
  pkg/context/context.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/etcdkey.go
  pkg/etcd/metrics.go
  pkg/orchestrator/reactor_state.go
  pkg/orchestrator/reactor_state_test.go
  testing_utils/cdc_state_checker/cdc_monitor.go
  testing_utils/cdc_state_checker/main.go
  testing_utils/cdc_state_checker/state.go
  tests/move_table/main.go
Labels: status/ptal, component/kv-client, status/LGT2, status/can-merge, size/XXL, release-note-none, needs-cherry-pick-release-5.2, type/enhancement

#2839 cli: ignore the global flag for changefeed update command
  cmd/client_changefeed.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, cherry-pick-approved, type/cherry-pick-for-release-5.1, release-note

#2862 test(pkg/context): migrate test-infra to testify for pkg/context pkg
  pkg/context/context_test.go
  pkg/context/main_test.go
  pkg/util/leak_helper.go
Labels: component/test, status/LGT2, status/can-merge, size/L, release-note

#2816 kv: enable new kv client in release-5.0 branch.
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: status/LGT2, status/can-merge, type/cherry-pick-for-release-5.0, size/XS, cherry-pick-approved, release-note-none

#2881 test(pkg/leakutil): extract leak helper func to a new pkg
  pkg/leakutil/leak_helper.go
  pkg/leakutil/leak_helper_test.go
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note

#2742 Add NoArgs to all commands
  cmd/client.go
  cmd/client_capture.go
  cmd/client_changefeed.go
  cmd/client_processor.go
  cmd/client_tso.go
  cmd/client_unsafe.go
  cmd/cmd_test.go
  cmd/root.go
  cmd/server.go
  cmd/util_test.go
  cmd/version.go
  tests/_utils/run_cdc_cli_tso_query
  tests/availability/run.sh
  tests/batch_add_table/run.sh
  tests/capture_session_done_during_task/run.sh
  tests/cdc/run.sh
  tests/cdclog_file/run.sh
  tests/cdclog_s3/run.sh
  tests/changefeed_error/run.sh
  tests/cli/run.sh
  tests/common_1/run.sh
  tests/cyclic_ab/run.sh
  tests/cyclic_abc/run.sh
  tests/ddl_puller_lag/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/generate_column/run.sh
  tests/http_proxies/run.sh
  tests/kafka_messages/run.sh
  tests/many_pk_or_uk/run.sh
  tests/move_table/run.sh
  tests/multi_capture/run.sh
  tests/multi_source/run.sh
  tests/partition_table/run.sh
  tests/processor_panic/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/simple/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/syncpoint/run.sh
  tests/tiflash/run.sh
  tests/unified_sorter/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, cherry-pick-approved, component/cli, release-note-none

#2880 test(pkg/cyclic): migrate test-infra to testify for pkg/cyclic pkg
  pkg/cyclic/filter_test.go
  pkg/cyclic/main_test.go
  pkg/cyclic/mark/main_test.go
  pkg/cyclic/mark/mark_test.go
  pkg/cyclic/replication_test.go
Labels: component/test, status/LGT2, status/can-merge, size/L, release-note

#2799 tests: add test case to cover varchar default value
  tests/multi_source/main.go
  tests/row_format/data/step3.sql
  tests/row_format/data/step4.sql
Labels: status/ptal, component/test, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2896 lint: make revive happy
  Makefile
  pkg/etcd/metrics.go
  pkg/util/leak_helper.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2898 github: use yml template
  .github/ISSUE_TEMPLATE/bug-report.md
  .github/ISSUE_TEMPLATE/bug-report.yml
  .github/ISSUE_TEMPLATE/feature-request.md
  .github/ISSUE_TEMPLATE/feature-request.yml
  .github/ISSUE_TEMPLATE/flaking-test.md
  .github/ISSUE_TEMPLATE/flaking-test.yml
  .github/ISSUE_TEMPLATE/question.md
  .github/ISSUE_TEMPLATE/question.yml
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#2924 test(scheduler): migrate test-infra to testify for pkg/scheduler pkg
  pkg/scheduler/main_test.go
  pkg/scheduler/table_number_test.go
  pkg/scheduler/workload_test.go
Labels: component/test, status/LGT2, status/can-merge, size/L, release-note

#2775 kv: enable use new kv client in release-4.0
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
Labels: status/LGT2, status/can-merge, size/S, cherry-pick-approved, type/cherry-pick-for-release-4.0, release-note-none

#2938 perf(pkg/flags): migrate test-infra to testify for pkg/flags pkg
  pkg/flags/main_test.go
  pkg/flags/urls_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#2941 test(pkg/httputil): migrate test-infra to testify for pkg/httputil pkg
  pkg/httputil/httputil_test.go
  pkg/httputil/main_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#2922 test(pkg/types): migrate test-infra to testify for pkg/types pkg
  pkg/types/main_test.go
  pkg/types/urls_test.go
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note

#2931 test(pkg/notify): migrate test-infra to testify for pkg/notify pkg
  pkg/notify/main_test.go
  pkg/notify/notify_test.go
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note-none

#2929 test(pkg/quotes): migrate test-infra to testify for pkg/quotes pkg
  pkg/quotes/main_test.go
  pkg/quotes/quotes_test.go
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note-none

#2940 test(pkg/hash): migrate test-infra to testify for pkg/hash pkg
  pkg/hash/position_inertia_test.go
Labels: component/test, status/LGT2, status/can-merge, size/S, release-note-none

#2918 kv: Remove old kvclient related code in release-5.0
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
Labels: component/kv-client, status/LGT2, status/can-merge, size/XXL, cherry-pick-approved, release-note-none

#2926 test(pkg/retry):migrate test-infra to testify for pkg/retry pkg
  pkg/retry/main_test.go
  pkg/retry/retry_test.go
Labels: component/test, status/LGT2, status/can-merge, size/L, release-note-none

#2956 integration: update integration docker compose file.
  docker-compose-avro.yml
  docker-compose-canal.yml
  docker-compose-mysql.yml
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note-none

#2939 sink: add a method to validate sink
  cdc/capture/http_validator.go
  cdc/capture/http_validator_test.go
  cdc/owner/async_sink.go
  cdc/processor/processor.go
  cdc/sink/sink.go
  cdc/sink/sink_test.go
  cmd/kafka-consumer/main.go
  integration/integration.go
  pkg/cmd/cli/cli_changefeed_create.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none

#2943 pkg: rm retry.Run, retry.RunWithInfiniteRetry func since been announced Deprecated for a while
  cdc/kv/client_test.go
  pkg/retry/retry.go
  pkg/retry/retry_test.go
Labels: status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none

#2945 kv: Remove old kvclient related code in release-4.0
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
Labels: status/LGT2, size/XXL, cherry-pick-approved, release-note-none

#2961 sink: trivial cleanup
  cdc/sink/codec/interface.go
  cdc/sink/dispatcher/dispatcher.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/mq_producer.go
  cdc/sink/producer/pulsar/producer.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2959 tests: make integration test case http_api more stable
  tests/http_api/util/test_case.py
Labels: type/bugfix, component/test, status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-5.2

#2744 cli: Add NoArgs to all commands
  pkg/cmd/cli/cli.go
  pkg/cmd/cli/cli_capture.go
  pkg/cmd/cli/cli_capture_list.go
  pkg/cmd/cli/cli_changefeed.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_cyclic_create_marktables.go
  pkg/cmd/cli/cli_changefeed_list.go
  pkg/cmd/cli/cli_changefeed_pause.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_changefeed_remove.go
  pkg/cmd/cli/cli_changefeed_resume.go
  pkg/cmd/cli/cli_changefeed_statistics.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_processor.go
  pkg/cmd/cli/cli_processor_list.go
  pkg/cmd/cli/cli_processor_query.go
  pkg/cmd/cli/cli_test.go
  pkg/cmd/cli/cli_tso_query.go
  pkg/cmd/cli/cli_unsafe_delete_service_gc_safepoint.go
  pkg/cmd/cli/cli_unsafe_reset.go
  pkg/cmd/cli/cli_unsafe_show_metadata.go
  pkg/cmd/server/server.go
  pkg/cmd/version/version.go
  tests/_utils/run_cdc_cli_tso_query
  tests/availability/run.sh
  tests/bank/bank.go
  tests/batch_add_table/run.sh
  tests/capture_session_done_during_task/run.sh
  tests/cdc/run.sh
  tests/cdclog_file/run.sh
  tests/cdclog_s3/run.sh
  tests/changefeed_error/run.sh
  tests/cli/run.sh
  tests/common_1/run.sh
  tests/cyclic_ab/run.sh
  tests/cyclic_abc/run.sh
  tests/ddl_puller_lag/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/generate_column/run.sh
  tests/http_proxies/run.sh
  tests/kafka_messages/run.sh
  tests/many_pk_or_uk/run.sh
  tests/move_table/run.sh
  tests/multi_capture/run.sh
  tests/multi_source/run.sh
  tests/partition_table/run.sh
  tests/processor_panic/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/simple/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/syncpoint/run.sh
  tests/tiflash/run.sh
  tests/unified_sorter/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#2937 test(pkg/filter): migrate test-infra to testify for pkg/filter pkg
  pkg/filter/filter_test.go
  pkg/filter/main_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#2960 *: move from deprecated ioutil to os and io packages
  cdc/http_handler.go
  cdc/http_router.go
  cdc/http_status_test.go
  cdc/sink/codec/schema_registry.go
  cdc/sink/codec/schema_registry_test.go
  integration/framework/avro/kafka_docker_env.go
  integration/framework/avro/kafka_single_table.go
  integration/framework/canal/kafka_docker_env.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/cmd/cli/cli_changefeed_helper_test.go
  pkg/cmd/cli/cli_changefeed_update_test.go
  pkg/cmd/server/server_test.go
  pkg/cmd/util/helper_test.go
  pkg/httputil/httputil_test.go
  pkg/util/fileutil.go
  pkg/util/fileutil_test.go
  pkg/version/check.go
  tests/move_table/main.go
  tests/resolve_lock/main.go
Labels: status/LGT2, status/can-merge, first-time-contributor, size/L, contribution, release-note-none

#2891 test(pkg/workerpool): migrate test-infra to testify for pkg/workerpool
  pkg/workerpool/async_pool_test.go
  pkg/workerpool/main_test.go
  pkg/workerpool/pool_test.go
Labels: component/test, status/LGT2, status/can-merge, size/L, release-note

#2809 redolog : redolog storage layer data model & common util
  cdc/model/sink.go
  cdc/model/sink_gen.go
  cdc/model/sink_gen_test.go
  cdc/redo/common/redo.go
  cdc/redo/common/redo_gen.go
  cdc/redo/common/redo_gen_test.go
  cdc/redo/common/util.go
  cdc/redo/common/util_test.go
  errors.toml
  pkg/errors/errors.go
  scripts/check-copyright.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none
