Repository pingcap/tiflow, pull requests merged in 2021-12, with the labels that each got.

#3680 docs: update verify-ci trigger commands
  docs/ci/command.md
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#3599 sink: remove cdclog.
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/cdclog/utils.go
  cdc/sink/sink.go
  errors.toml
  pkg/errors/errors.go
  proto/generate-proto.sh
  tests/cdclog_file/run.sh
  tests/cdclog_s3/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#3683 sink(ticdc): add TestSetParams test
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#3682 cdc/sink: remove Initialize method from the sink interface
  cdc/owner/async_sink.go
  cdc/owner/async_sink_test.go
  cdc/owner/changefeed.go
  cdc/processor/pipeline/sink_test.go
  cdc/sink/black_hole.go
  cdc/sink/manager_test.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/simple_mysql_tester.go
  cdc/sink/sink.go
  cdc/sink/table_sink.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#3675 security(dm): fix some security problems
  dm/_utils/terror_gen/gen.go
  dm/dm/ctl/master/config.go
  dm/dm/ctl/master/get_config.go
  dm/relay/binlog_writer.go
  dm/relay/relay.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#3647 deployments(ticdc): refine the network and volumes
  deployments/ticdc/docker-compose/docker-compose-kafka-integration.yml
  deployments/ticdc/docker-compose/docker-compose-mysql-integration.yml
  deployments/ticdc/docker/integration-test.Dockerfile
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#3623 pkg/p2p(cdc): implement MessageServer
  errors.toml
  pkg/errors/errors.go
  pkg/p2p/metrics.go
  pkg/p2p/server.go
  pkg/p2p/server_test.go
  pkg/p2p/server_wrapper_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#3705 black hole sink manage checkpointTs per table
  cdc/processor/pipeline/sink_test.go
  cdc/sink/black_hole.go
  cdc/sink/simple_mysql_tester.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#3664 pkg/db(ticdc): add pebble db
  cdc/sorter/leveldb/cleaner_test.go
  cdc/sorter/leveldb/leveldb_test.go
  cdc/sorter/leveldb/system/system.go
  go.mod
  pkg/db/db_test.go
  pkg/db/leveldb.go
  pkg/db/pebble.go
Labels: subject/performance, status/LGT2, status/can-merge, size/XL, component/sorter, release-note-none, area/ticdc

#3693 sink(ticdc): add tests for enable-tidb-extension and extract the config out
  cdc/sink/mq.go
  cdc/sink/producer/kafka/config.go
  cdc/sink/producer/kafka/config_test.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  pkg/errors/errors.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#3701 test: fix upgrade test
  .github/workflows/upgrade_dm_via_tiup.yaml
  Makefile
  dm/tests/tiup/lib.sh
  dm/tests/tiup/upgrade-from-v2.sh
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#3681 batch (ticdc): add etcdTxnMaxOps to limit the ops number of an etcd txn
  errors.toml
  pkg/errors/errors.go
  pkg/orchestrator/batch.go
  pkg/orchestrator/batch_test.go
Labels: status/ptal, type/bugfix, component/replica-model, status/LGT2, status/can-merge, size/M, release-note

#3704 owner(ticdc): integrate scheduler(v2) with the Owner (Part I)
  cdc/owner/changefeed.go
  cdc/owner/scheduler.go
  cdc/owner/scheduler_v1.go
  cdc/owner/scheduler_v1_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#3707 test: revert trigger for upgrade test
  .github/workflows/upgrade_dm_via_tiup.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#3668 pkg/p2p(cdc): implement MessageClient
  errors.toml
  pkg/errors/errors.go
  pkg/p2p/client.go
  pkg/p2p/client_test.go
  pkg/p2p/metrics.go
  pkg/p2p/mock_grpc_client.go
  pkg/p2p/server.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#3710 relay(dm): use binlog name comparison
  dm/relay/relay.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm, needs-cherry-pick-release-5.3

#3709 sink(ticdc): add tests for validateMaxMessageBytesAndCreateTopic
  cdc/sink/mq.go
  cdc/sink/mq_test.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  pkg/kafka/cluster_admin_client.go
  pkg/kafka/cluster_admin_client_mock_impl.go
  pkg/kafka/config.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#3720 tests(ticdc): move testing_utils into tests
  tests/integration_tests/_utils/start_tidb_cluster_impl
  tests/integration_tests/_utils/start_tls_tidb_cluster_impl
  tests/utils/cdc_state_checker/cdc_monitor.go
  tests/utils/cdc_state_checker/main.go
  tests/utils/cdc_state_checker/reactor.go
  tests/utils/cdc_state_checker/state.go
  tests/utils/many_sorters_test/many_sorters.go
  tests/utils/many_sorters_test/many_sorters_test.go
  tests/utils/sorter_stress_test/sorter_stress.go
Labels: status/LGT1, size/XS, require-LGT1, release-note-none

#3723 chore(dm): grpc.WithBackoffMaxDelay has been deprecated
  dm/dm/master/workerrpc/rawgrpc.go
Labels: status/LGT2, status/can-merge, size/XS, contribution, release-note-none, area/dm

#3700 security(cdc): fix some security problems
  cdc/server.go
  cdc/sink/producer/kafka/config.go
  cdc/sorter/unified/file_backend.go
  cdc/sorter/unified/unified_sorter.go
  cmd/kafka-consumer/main.go
  pkg/filelock/filelock.go
  tests/integration_tests/bank/case.go
  tests/integration_tests/resolve_lock/main.go
  tests/utils/many_sorters_test/many_sorters.go
  tests/utils/sorter_stress_test/sorter_stress.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#3724 capture(cdc): put OwnerRevision into context
  cdc/capture/capture.go
  pkg/context/context.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#3721 pkg/p2p(cdc): fix minor bugs and add basic integration tests
  errors.toml
  pkg/errors/errors.go
  pkg/p2p/client.go
  pkg/p2p/client_batch_sender.go
  pkg/p2p/client_test.go
  pkg/p2p/server.go
  pkg/p2p/server_client_integration_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none

#3725 tests(ticdc): set up the sync diff output directory correctly
  tests/integration_tests/_utils/check_sync_diff
  tests/integration_tests/autorandom/conf/diff_config.toml
  tests/integration_tests/batch_add_table/conf/diff_config.toml
  tests/integration_tests/capture_session_done_during_task/conf/diff_config.toml
  tests/integration_tests/capture_suicide_while_balance_table/conf/diff_config.toml
  tests/integration_tests/changefeed_auto_stop/conf/diff_config.toml
  tests/integration_tests/changefeed_error/conf/diff_config.toml
  tests/integration_tests/changefeed_finish/conf/diff_config.toml
  tests/integration_tests/changefeed_pause_resume/conf/diff_config.toml
  tests/integration_tests/changefeed_reconstruct/conf/diff_config.toml
  tests/integration_tests/clustered_index/conf/diff_config.toml
  tests/integration_tests/common_1/conf/diff_config.toml
  tests/integration_tests/consistent_replicate_nfs/conf/diff_config.toml
  tests/integration_tests/consistent_replicate_s3/conf/diff_config.toml
  tests/integration_tests/cyclic_ab/conf/diff_config.toml
  tests/integration_tests/cyclic_abc/conf/diff_config_down_tls.toml
  tests/integration_tests/cyclic_abc/conf/diff_config_up_down.toml
  tests/integration_tests/ddl_attributes/conf/diff_config.toml
  tests/integration_tests/ddl_reentrant/conf/diff_config.toml
  tests/integration_tests/ddl_sequence/conf/diff_config.toml
  tests/integration_tests/drop_many_tables/conf/diff_config.toml
  tests/integration_tests/gc_safepoint/conf/diff_config.toml
  tests/integration_tests/generate_column/conf/diff_config.toml
  tests/integration_tests/kafka_messages/conf/diff_config.toml
  tests/integration_tests/kafka_sink_error_resume/conf/diff_config.toml
  tests/integration_tests/kill_owner_with_ddl/conf/diff_config.toml
  tests/integration_tests/kv_client_stream_reconnect/conf/diff_config.toml
  tests/integration_tests/many_pk_or_uk/diff_config.toml
  tests/integration_tests/move_table/conf/diff_config.toml
  tests/integration_tests/multi_capture/conf/diff_config.toml
  tests/integration_tests/multi_source/diff_config.toml
  tests/integration_tests/new_ci_collation_with_old_value/conf/diff_config.toml
  tests/integration_tests/new_ci_collation_without_old_value/conf/diff_config.toml
  tests/integration_tests/owner_remove_table_error/conf/diff_config.toml
  tests/integration_tests/partition_table/conf/diff_config.toml
  tests/integration_tests/processor_err_chan/conf/diff_config.toml
  tests/integration_tests/processor_panic/diff_config.toml
  tests/integration_tests/processor_resolved_ts_fallback/conf/diff_config.toml
  tests/integration_tests/processor_stop_delay/conf/diff_config.toml
  tests/integration_tests/region_merge/conf/diff_config.toml
  tests/integration_tests/resolve_lock/diff_config.toml
  tests/integration_tests/row_format/conf/diff_config.toml
  tests/integration_tests/sink_hang/conf/diff_config.toml
  tests/integration_tests/sink_retry/conf/diff_config.toml
  tests/integration_tests/split_region/conf/diff_config.toml
  tests/integration_tests/syncpoint/conf/diff_config_final.toml
  tests/integration_tests/syncpoint/conf/diff_config_part1.toml
  tests/integration_tests/tiflash/conf/diff_config.toml
  tests/integration_tests/unified_sorter/conf/diff_config.toml
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3492 sorter/leveldb: add table sorter
  cdc/sorter/leveldb/buffer.go
  cdc/sorter/leveldb/table_sorter.go
  cdc/sorter/leveldb/table_sorter_test.go
  cdc/sorter/sorter.go
  errors.toml
  pkg/errors/errors.go
Labels: status/LGT2, status/can-merge, size/XXL, component/sorter, release-note-none, area/ticdc

#3625 cdc/sink: buffer sink manage checkpoint ts per table
  cdc/sink/buffer_sink.go
  cdc/sink/buffer_sink_test.go
  cdc/sink/manager.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none

#3575 syncer(dm) : fix default collation with upstream in create table statement
  dm/pkg/binlog/event/util.go
  dm/pkg/binlog/event/util_test.go
  dm/pkg/utils/db.go
  dm/syncer/dbconn/upstream_db.go
  dm/syncer/ddl.go
  dm/syncer/ddl_test.go
  dm/syncer/filter_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm, needs-cherry-pick-release-5.3

#3740 test: add workflow dispatch for github action
  .github/workflows/dm_binlog_999999.yaml
  .github/workflows/dm_chaos.yaml
  .github/workflows/dm_upstream_switch.yaml
  .github/workflows/upgrade_dm_via_tiup.yaml
  dm/tests/tiup/upgrade-from-v2.sh
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#3713 docs(ticdc): add documentation for running integration tests in docker
  CONTRIBUTING.md
  README.md
  tests/integration_tests/README.md
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#3686 master(dm): check subtask status when `stop-task` instead of exit quickly
  dm/dm/master/server.go
  dm/dm/master/server_test.go
Labels: status/LGT2, status/can-merge, size/M, contribution, release-note-none, area/dm

#3496 relay, syncer(dm): stricter GTID check when retry replication
  dm/chaos/cases/db.go
  dm/chaos/cases/task.go
  dm/pkg/binlog/event/util.go
  dm/pkg/binlog/reader/util.go
  dm/relay/file_util.go
  dm/relay/local_reader.go
  dm/relay/local_reader_test.go
  dm/relay/relay.go
  dm/relay/relay_test.go
  dm/relay/relay_writer.go
  dm/syncer/syncer.go
  dm/tests/duplicate_event/run.sh
  dm/tests/others_integration_1.txt
  dm/tests/slow_relay_writer/conf/diff_config.toml
  dm/tests/slow_relay_writer/conf/dm-master.toml
  dm/tests/slow_relay_writer/conf/dm-task.yaml
  dm/tests/slow_relay_writer/conf/dm-worker1.toml
  dm/tests/slow_relay_writer/conf/source1.yaml
  dm/tests/slow_relay_writer/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm, needs-cherry-pick-release-5.3

#3667 etcd_worker: add timeout for etcd txn and watchCh
  pkg/etcd/client.go
  pkg/etcd/client_test.go
  pkg/orchestrator/etcd_worker.go
Labels: status/ptal, type/bugfix, component/replica-model, status/LGT2, status/can-merge, size/L, release-note

#3738 pkg/p2p(cdc): Add MessageRouter
  pkg/p2p/client.go
  pkg/p2p/message_router.go
  pkg/p2p/message_router_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#3748 pkg/db(ticdc): fix nil store panic
  pkg/db/db_test.go
  pkg/db/pebble.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/M, component/sorter, release-note-none, area/ticdc

#3752 pkg/p2p(cdc): stabilize tests
  pkg/p2p/server_client_integration_test.go
  pkg/p2p/server_test.go
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#3773 sink(ticdc): omit empty field in tidbExtension
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#3736 test(dm): enable new charset for TiDB in test
  dm/step_by_step_contribute.md
  dm/tests/_utils/check_sync_diff
  dm/tests/_utils/run_dm_ctl_with_tls_and_retry
  dm/tests/_utils/run_tidb_server
  dm/tests/online_ddl/data/gho.db1.prepare.sql
  dm/tests/online_ddl/data/gho.db2.prepare.sql
  dm/tests/online_ddl/data/pt.db1.prepare.sql
  dm/tests/online_ddl/data/pt.db2.prepare.sql
  dm/tests/safe_mode/data/db2.prepare.sql
  dm/tests/sequence_safe_mode/data/db1.prepare.sql
  dm/tests/sequence_safe_mode/data/db2.prepare.sql
  dm/tests/sequence_sharding/data/db1.prepare.sql
  dm/tests/sequence_sharding/data/db2.prepare.sql
  dm/tests/sequence_sharding_removemeta/data/db1.prepare.sql
  dm/tests/sequence_sharding_removemeta/data/db2.prepare.sql
  dm/tests/shardddl1/run.sh
  dm/tests/shardddl2/run.sh
  dm/tests/shardddl3/conf/tidb-alter-pk-config.toml
  dm/tests/shardddl3/run.sh
  dm/tests/shardddl3_1/run.sh
  dm/tests/shardddl4_1/run.sh
  dm/tests/sharding/data/db1.increment2.sql
  dm/tests/sharding/data/db1.prepare.sql
  dm/tests/sharding/data/db2.increment2.sql
  dm/tests/sharding/data/db2.prepare.sql
  dm/tests/tls/run.sh
  go.mod
  go.sum
  pkg/txnutil/lock_resolver.go
Labels: status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none, area/dm

#3747 config(ticdc): Fix old value configuration check for maxwell protocol
  cdc/sink/codec/avro.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/craft.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/interface_test.go
  cdc/sink/codec/json.go
  cdc/sink/codec/maxwell.go
  cdc/sink/mq.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/config/mq_sink_protocol.go
  pkg/config/mq_sink_protocol_test.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/config/sink_test.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3772 pkg/config(cdc): add MessagesConfig for configuring peer-messages
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/messages.go
  pkg/config/messages_test.go
  pkg/config/server_config.go
  pkg/config/server_config_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#3775 workerpool: limit the rate to output deadlock warning
  pkg/workerpool/pool_impl.go
  pkg/workerpool/pool_test.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, component/metrics-logging, needs-cherry-pick-release-5.1, component/sorter, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3746 mq (ticdc): mq sink manage checkpoint ts per table
  cdc/sink/mq.go
  cdc/sink/mq_test.go
Labels: type/bugfix, component/sink, status/LGT2, status/can-merge, size/L, release-note, area/ticdc

#3788 cdc/integration: Add unsigned test to row format
  tests/integration_tests/row_format/data/step3.sql
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#3770 checker(dm): move checker from tidb-tools to dm
  dm/checker/checker.go
  dm/pkg/checker/binlog.go
  dm/pkg/checker/mysql_server.go
  dm/pkg/checker/mysql_server_test.go
  dm/pkg/checker/privilege.go
  dm/pkg/checker/privilege_test.go
  dm/pkg/checker/real_checker.go
  dm/pkg/checker/table_structure.go
  dm/pkg/checker/table_structure_test.go
  dm/pkg/checker/utils.go
  dm/pkg/checker/utils_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#3751 sorter(ticdc): skip check sorter dir in unified sorter
  cdc/processor/pipeline/sorter.go
  cdc/server.go
  cdc/server_test.go
  cdc/sorter/unified/sorter_test.go
  cdc/sorter/unified/unified_sorter.go
Labels: status/LGT2, status/can-merge, size/L, component/sorter, release-note-none, area/ticdc

#3806 sink(ticdc): better name for config complete func
  cdc/sink/mq.go
  cdc/sink/mq_test.go
  cdc/sink/producer/kafka/config.go
  cdc/sink/producer/kafka/config_test.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
Labels: component/sink, status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none, area/ticdc

#3645 cdc/sink: mysql sink manage checkpoint per table
  cdc/sink/common/common.go
  cdc/sink/common/common_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_params_test.go
  cdc/sink/mysql_test.go
  cdc/sink/mysql_worker.go
  cdc/sink/mysql_worker_test.go
  cmd/kafka-consumer/main.go
  tests/integration_tests/sink_hang/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#3776 pkg,sorter(ticdc): gather fs related functions
  cdc/server.go
  cdc/sorter/unified/backend_pool.go
  cdc/sorter/unified/backend_pool_test.go
  pkg/errors/errors.go
  pkg/fsutil/disk_info_freebsd.go
  pkg/fsutil/disk_info_generic.go
  pkg/fsutil/filelock.go
  pkg/fsutil/filelock_test.go
  pkg/fsutil/fileutil.go
  pkg/fsutil/fileutil_test.go
  pkg/util/fileutil_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#3609 ticdc/mq: accurately demonstrate txn_batch_size metric for MQ sink
  cdc/sink/codec/craft.go
  cdc/sink/codec/craft/model.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/mq.go
Labels: type/bugfix, status/LGT2, status/can-merge, first-time-contributor, size/M, release-note-none

#3549 docs(both): update format of the commit message
  CONTRIBUTING.md
  dm/CONTRIBUTING.md
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#3809 ticdc/alert: add no owner alert rule
  metrics/alertmanager/ticdc.rules.yml
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, component/metrics-logging, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3201 cdc,pkg(ticdc): integrate leveldb sorter to processor
  cdc/capture/capture.go
  cdc/processor/pipeline/sorter.go
  pkg/config/db.go
  pkg/config/debug.go
  pkg/config/server_config.go
  pkg/context/context.go
  tests/integration_tests/sorter/conf/diff_config.toml
  tests/integration_tests/sorter/conf/ticdc_leveldb_sorter.toml
  tests/integration_tests/sorter/conf/workload
  tests/integration_tests/sorter/run.sh
  tests/integration_tests/unified_sorter/run.sh
Labels: status/LGT2, status/can-merge, size/XL, component/sorter, release-note-none

#3846 mounter(ticdc): fix mounter add default value type unsupported
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
Labels: type/bugfix, status/LGT2, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3814 parser(dm): use TiDB special comment for DROP INDEX IF EXISTS
  dm/pkg/parser/common.go
  dm/pkg/parser/common_test.go
  dm/syncer/ddl_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note, area/dm

#3449 webui(dm): initial implementation
  .github/workflows/dm_ui_lint.yaml
  .gitignore
  Makefile
  dm/README.md
  dm/dm/master/server.go
  dm/ui/.eslintrc.js
  dm/ui/.husky/pre-commit
  dm/ui/.lintstagedrc.js
  dm/ui/.prettierrc.js
  dm/ui/README.md
  dm/ui/embedded_asserts.go
  dm/ui/empty_asserts.go
  dm/ui/index.html
  dm/ui/locales/en.json
  dm/ui/locales/zh.json
  dm/ui/package.json
  dm/ui/server.go
  dm/ui/src/App.tsx
  dm/ui/src/assets/logo.png
  dm/ui/src/components/CreateOrUpdateSource.tsx
  dm/ui/src/i18n.ts
  dm/ui/src/layouts/Header.tsx
  dm/ui/src/layouts/SiderMenu.tsx
  dm/ui/src/main.tsx
  dm/ui/src/models/api.ts
  dm/ui/src/models/index.ts
  dm/ui/src/models/source.ts
  dm/ui/src/pages/_layout.tsx
  dm/ui/src/pages/migration/source.tsx
  dm/ui/src/theme.less
  dm/ui/src/uikit/icons.tsx
  dm/ui/src/uikit/index.tsx
  dm/ui/src/utils/unimplemented.ts
  dm/ui/tsconfig.json
  dm/ui/vite.config.js
  dm/ui/yarn.lock
  scripts/check-copyright.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#3800 test(dm): fix testServer.TestServer data race
  dm/dm/ctl/common/config.go
  dm/dm/ctl/common/util.go
  dm/dm/worker/server.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#3620 ha(dm): support store task config in Etcd
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/common/common.go
  dm/dm/common/common_test.go
  dm/errors.toml
  dm/openapi/task.go
  dm/pkg/ha/openapi_task_config.go
  dm/pkg/ha/openapi_task_config_test.go
  dm/pkg/terror/error_list.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note, area/dm

#3848 etcd_worker: fix missed watch events caused by progress notifications
  pkg/etcd/client.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_bank_test.go
Labels: status/ptal, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3481 redolog: add metric
  cdc/metrics.go
  cdc/redo/writer/file.go
  cdc/redo/writer/file_test.go
  cdc/redo/writer/metric.go
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XXL, release-note, component/redolog, needs-cherry-pick-release-5.3, area/ticdc

#3525 redolog: add a precleanup process when s3 enable
  cdc/redo/writer/file.go
  cdc/redo/writer/file_test.go
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note, component/redolog, needs-cherry-pick-release-5.3, area/ticdc

#3792 owner, scheduler, pkg/p2p(cdc): integrate Scheduler(V2) with the Owner (Part II)
  cdc/owner/changefeed.go
  cdc/owner/owner.go
  cdc/owner/scheduler.go
  cdc/owner/scheduler_test.go
  cdc/owner/scheduler_v1.go
  pkg/context/context.go
  pkg/p2p/client.go
  pkg/p2p/mock_cluster.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#3824 http_api (ticdc): filter out metrics related log
  cdc/http_router.go
Labels: status/ptal, status/LGT2, status/can-merge, component/status-server, size/XS, release-note-none, area/ticdc

#3628 http_api (ticdc): check --cert-allowed-cn before add server common name
  cdc/capture/capture.go
  cdc/capture/http_handler.go
  cdc/http_status.go
  cdc/http_status_test.go
  pkg/security/test_util.go
Labels: status/ptal, status/LGT2, status/can-merge, component/status-server, size/XL, release-note, needs-cherry-pick-release-5.3

#3811 sink(ticdc): add ProtocolOpen to replace default protocol
  cdc/sink/codec/interface.go
  cdc/sink/codec/interface_test.go
  cdc/sink/codec/json.go
  cdc/sink/mq.go
  errors.toml
  pkg/config/mq_sink_protocol.go
  pkg/config/mq_sink_protocol_test.go
  pkg/errors/errors.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#3803 openapi(dm): add genereated client code
  Makefile
  dm/openapi/gen.client.go
  dm/openapi/spec/client-gen-cfg.yaml
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#3222 syncer(dm): support async checkpoint flush
  dm/syncer/causality.go
  dm/syncer/causality_test.go
  dm/syncer/checkpoint.go
  dm/syncer/checkpoint_flush_worker.go
  dm/syncer/checkpoint_test.go
  dm/syncer/compactor.go
  dm/syncer/compactor_test.go
  dm/syncer/dml_worker.go
  dm/syncer/job.go
  dm/syncer/job_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#3849 cdc/tests: Add more canal json test
  scripts/canal/docker/Dockerfile
  tests/integration_tests/row_format/data/step3.sql
  tests/integration_tests/row_format/data/step4.sql
  tests/mq_protocol_tests/cases/case_many_types.go
  tests/mq_protocol_tests/main.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#3887 tz (ticdc): fix timezone error
  pkg/util/tz.go
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3904 orchestrator, capture(cdc): add capture add/remove hooks in GlobalReactorState
  cdc/owner/owner_test.go
  cdc/processor/manager_test.go
  pkg/orchestrator/reactor_state.go
  pkg/orchestrator/reactor_state_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#3494 ticdc/redo: should cleanup redo logs when removing a paused changefeed
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  pkg/context/context.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note, component/redolog, needs-cherry-pick-release-5.3

#3917 version(ticdc): fix wrong version of ChangefeedStateFromAdminJob gate
  pkg/version/creator_version_gate.go
  pkg/version/creator_version_gate_test.go
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, area/ticdc

#3921 Revert "mounter(ticdc): fix mounter add default value type unsupported (#3846)"
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
Labels: status/LGT2, status/can-merge, size/XL, cherry-pick-approved, release-note-none

#3851 etcd/client (ticdc): Prevent revision in WatchWitchChan fallback.
  pkg/etcd/client.go
  pkg/etcd/client_test.go
  pkg/etcd/util.go
  pkg/etcd/util_test.go
Labels: status/ptal, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, type/enhancement, needs-cherry-pick-release-5.3, area/ticdc

#3896 owner, scheduler(cdc): expose information from scheduler
  cdc/owner/changefeed.go
  cdc/owner/owner.go
  cdc/scheduler/info_provider.go
  cdc/scheduler/info_provider_test.go
Labels: component/scheduler, status/LGT2, status/can-merge, component/status-server, size/L, release-note-none, area/ticdc

#3897 doc(both): update project docs
  CODE_OF_CONDUCT.md
  CONTRIBUTING.md
  SECURITY.md
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#3598 owner(ticdc): asynchronously create sink
  cdc/owner/async_sink.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_puller.go
  cdc/owner/ddl_sink.go
  cdc/owner/ddl_sink_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/sink/producer/kafka/kafka.go
  cmd/kafka-consumer/main.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#3916 scheduler(cdc): fix missed automatic rebalance
  cdc/scheduler/schedule_dispatcher.go
  cdc/scheduler/schedule_dispatcher_test.go
Labels: status/ptal, component/scheduler, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#3911 dumpling(dm): move dumpling/utils.go to pkg/dumpling/utils.go
  dm/dumpling/dumpling.go
  dm/dumpling/dumpling_test.go
  dm/dumpling/util.go
  dm/dumpling/util_test.go
  dm/pkg/dumpling/utils.go
  dm/pkg/dumpling/utils_test.go
  dm/tests/safe_mode/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, type/enhancement, area/dm

#3769 syncer(dm) : fix default collation with upstream in create table‘s columns
  dm/pkg/binlog/event/util.go
  dm/pkg/utils/db.go
  dm/syncer/dbconn/upstream_db.go
  dm/syncer/ddl.go
  dm/syncer/ddl_test.go
  dm/syncer/syncer.go
  dm/tests/others_integration_1.txt
  dm/tests/sync_collation/conf/dm-master.toml
  dm/tests/sync_collation/conf/dm-task.yaml
  dm/tests/sync_collation/conf/dm-worker1.toml
  dm/tests/sync_collation/conf/dm-worker2.toml
  dm/tests/sync_collation/conf/source1.yaml
  dm/tests/sync_collation/conf/source2.yaml
  dm/tests/sync_collation/data/clean_data.sql
  dm/tests/sync_collation/data/db1.increment.sql
  dm/tests/sync_collation/data/db1.increment_err.sql
  dm/tests/sync_collation/data/db1.prepare.sql
  dm/tests/sync_collation/data/db1.prepare_err.sql
  dm/tests/sync_collation/data/db2.increment.sql
  dm/tests/sync_collation/data/db2.increment_err.sql
  dm/tests/sync_collation/data/db2.prepare.sql
  dm/tests/sync_collation/data/db2.prepare_err.sql
  dm/tests/sync_collation/data/tidb.checktable.increment.prepare.sql
  dm/tests/sync_collation/data/tidb.checktable.prepare.sql
  dm/tests/sync_collation/run.sh
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#3914 dep(dm): update go-mysql
  dm/tests/all_mode/run.sh
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XS, release-note, area/dm

#3902 pkg,cdc: do not use log package
  .golangci.yml
  cdc/puller/frontier/list.go
  cdc/scheduler/util/table_set.go
  cdc/sink/codec/canal.go
  cdc/sink/common/flow_control.go
  pkg/context/context.go
  pkg/context/context_test.go
  pkg/etcd/etcdkey.go
  pkg/orchestrator/util/key_utils.go
  tests/mq_protocol_tests/cases/case_date_time.go
Labels: status/LGT1, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, component/metrics-logging, require-LGT1, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3694 dm: add dumpstatus in query-status
  dm/dm/pb/dmworker.pb.go
  dm/dm/proto/dmworker.proto
  dm/dumpling/dumpling.go
  dm/dumpling/dumpling_test.go
Labels: status/LGT2, status/can-merge, size/XL, contribution, release-note-none, area/dm

#3899 sink(ticdc): optimize buffer sink flush from O(N^2) to O(N)
  cdc/sink/buffer_sink.go
  cdc/sink/buffer_sink_test.go
  cdc/sink/manager.go
  cdc/sink/metrics.go
  cdc/sink/sink.go
  cdc/sink/table_sink.go
Labels: component/sink, subject/performance, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3933 readme(dm): update dm test readme
  dm/tests/README.md
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#3965 github: replace pingcap/ticdc with pingcap/tiflow in workflow
  .github/ISSUE_TEMPLATE/flaking-test.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/workflows/assign_bugs_questions_project.yaml
  .github/workflows/dm_binlog_999999.yaml
  .github/workflows/dm_chaos.yaml
  .github/workflows/dm_upstream_switch.yaml
  .github/workflows/upgrade_dm_via_tiup.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-5.3

#3845 ticdc/owner: Fix ddl special comment syntax error
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  tests/integration_tests/ddl_reentrant/run.sh
Labels: type/bugfix, component/ddl, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3895 changefeed(ticdc): Fix the problem that the protocol may not be recognized when upgrading
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/sink/mq.go
  cdc/sink/producer/kafka/config.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/config/config_test_data.go
  pkg/config/mq_sink_protocol.go
  pkg/config/replica_config.go
  pkg/version/creator_version_gate.go
  pkg/version/creator_version_gate_test.go
Labels: component/configuration, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#3993 metrics(ticdc): fix EtcdWorker row
  metrics/grafana/ticdc.json
Labels: type/bugfix, status/LGT2, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, component/metrics-logging, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3656 openapi(dm): add task config template releated openapi
  dm/dm/master/openapi.go
  dm/dm/master/openapi_test.go
  dm/openapi/gen.client.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#3922 Revert "mounter(ticdc): fix mounter add default value type unsupported (#3846)"
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
Labels: size/XL, cherry-pick-approved, release-note-none

#3995 errorutil,sink,syncer: add errorutil to handle ignorable error (#3264)
  cdc/sink/mysql.go
  cdc/sink/simple_mysql_tester.go
  dm/syncer/error.go
  dm/syncer/error_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  pkg/errorutil/ignore.go
  pkg/errorutil/ignore_test.go
Labels: status/LGT2, status/can-merge, size/L, cherry-pick-approved, release-note, needs-cherry-pick-release-5.3

#3980 owner, processor(cdc): fix reporting ErrPeerMessageClientClosed to user erroneously
  cdc/owner/scheduler.go
  cdc/owner/scheduler_test.go
  cdc/processor/agent.go
  cdc/processor/agent_test.go
  pkg/p2p/client.go
  pkg/p2p/client_test.go
Labels: status/LGT2, status/can-merge, size/L, bug-from-internal-test, release-note-none, area/ticdc

#3985 worker(dm): worker has higher priority to config relay dir
  dm/dm/worker/config.go
  dm/dm/worker/dm-worker.toml
  dm/dm/worker/server.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/source_worker_test.go
  dm/dm/worker/task_checker_test.go
  dm/tests/dmctl_basic/conf/get_worker1.toml
  dm/tests/dmctl_basic/conf/get_worker2.toml
  dm/tests/print_status/conf/dm-worker1.toml
  dm/tests/print_status/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note, area/dm

#3813 loader(dm): simplify lightning checkpoint and add clean meta
  dm/dm/master/server.go
  dm/dm/master/server_test.go
  dm/loader/checkpoint.go
  dm/loader/checkpoint_test.go
  dm/loader/lightning.go
  dm/pkg/conn/basedb.go
  dm/pkg/cputil/table.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#3986 sorter/leveldb(ticdc): fix input regression panic
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/sorter/leveldb/table_sorter.go
  cdc/sorter/leveldb/table_sorter_test.go
  cdc/sorter/sorter.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/M, component/sorter, release-note-none, area/ticdc

#4002 config(ticdc): No longer set open-protocol as default value for kafka sink protocol
  cdc/owner/feed_state_manager_test.go
  cdc/processor/processor_test.go
  cdc/sink/mq_test.go
  docs/design/2021-10-13-ticdc-mq-sink-column-selector.md
  pkg/cmd/util/changefeed.toml
  pkg/cmd/util/helper_test.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/orchestrator/reactor_state_test.go
  tests/integration_tests/autorandom/run.sh
  tests/integration_tests/batch_add_table/run.sh
  tests/integration_tests/capture_session_done_during_task/run.sh
  tests/integration_tests/cdc/run.sh
  tests/integration_tests/changefeed_auto_stop/run.sh
  tests/integration_tests/changefeed_error/run.sh
  tests/integration_tests/changefeed_finish/run.sh
  tests/integration_tests/changefeed_pause_resume/run.sh
  tests/integration_tests/changefeed_reconstruct/run.sh
  tests/integration_tests/cli/run.sh
  tests/integration_tests/clustered_index/run.sh
  tests/integration_tests/common_1/run.sh
  tests/integration_tests/consistent_replicate_nfs/run.sh
  tests/integration_tests/consistent_replicate_s3/run.sh
  tests/integration_tests/ddl_attributes/run.sh
  tests/integration_tests/ddl_puller_lag/run.sh
  tests/integration_tests/ddl_sequence/run.sh
  tests/integration_tests/drop_many_tables/run.sh
  tests/integration_tests/force_replicate_table/run.sh
  tests/integration_tests/gc_safepoint/run.sh
  tests/integration_tests/generate_column/run.sh
  tests/integration_tests/kafka_messages/run.sh
  tests/integration_tests/kafka_sink_error_resume/run.sh
  tests/integration_tests/kv_client_stream_reconnect/run.sh
  tests/integration_tests/many_pk_or_uk/run.sh
  tests/integration_tests/move_table/run.sh
  tests/integration_tests/multi_capture/run.sh
  tests/integration_tests/multi_source/run.sh
  tests/integration_tests/new_ci_collation_with_old_value/run.sh
  tests/integration_tests/new_ci_collation_without_old_value/run.sh
  tests/integration_tests/partition_table/run.sh
  tests/integration_tests/processor_err_chan/run.sh
  tests/integration_tests/processor_panic/run.sh
  tests/integration_tests/processor_resolved_ts_fallback/run.sh
  tests/integration_tests/processor_stop_delay/run.sh
  tests/integration_tests/region_merge/run.sh
  tests/integration_tests/resolve_lock/run.sh
  tests/integration_tests/row_format/run.sh
  tests/integration_tests/simple/run.sh
  tests/integration_tests/sink_hang/run.sh
  tests/integration_tests/sink_retry/run.sh
  tests/integration_tests/sorter/run.sh
  tests/integration_tests/split_region/run.sh
  tests/integration_tests/tiflash/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#3860 syncer(dm): use an early location to reset binlog and open safemode
  dm/syncer/syncer.go
  dm/tests/_utils/check_sync_diff
  dm/tests/duplicate_event/run.sh
  dm/tests/others_integration_2.txt
Labels: status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note, area/dm

#4007 owner,scheduler(cdc): fix nil pointer panic in owner scheduler (#2980)
  cdc/owner/scheduler_v1.go
  cdc/owner/scheduler_v1_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3677 cdc/codec: Fix canal json encoding
  cdc/model/sink.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/java.go
  cdc/sink/codec/json.go
  tests/integration_tests/row_format/data/step3.sql
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note

#3837 sorter/leveldb(ticdc): trigger compact by deletion to speed up read
  cdc/sorter/leveldb/cleaner.go
  cdc/sorter/leveldb/cleaner_test.go
  cdc/sorter/leveldb/compactor.go
  cdc/sorter/leveldb/compactor_test.go
  cdc/sorter/leveldb/leveldb.go
  cdc/sorter/leveldb/leveldb_test.go
  cdc/sorter/leveldb/metrics.go
  cdc/sorter/leveldb/system/system.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/db.go
  pkg/config/server_config.go
  pkg/db/db.go
  pkg/db/db_test.go
  pkg/db/leveldb.go
  pkg/db/pebble.go
Labels: status/LGT2, status/can-merge, size/XXL, component/sorter, release-note-none, area/ticdc

#4019 Clean old owner and old processor in release 5.2 branch
  cdc/capture.go
  cdc/capture_test.go
  cdc/changefeed.go
  cdc/changefeed_test.go
  cdc/metrics.go
  cdc/metrics_owner.go
  cdc/metrics_processor.go
  cdc/owner.go
  cdc/owner_operator.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/processor_test.go
  cdc/server.go
  cdc/sink/mysql.go
  cdc/task.go
  cdc/task_test.go
  pkg/config/config.go
  pkg/util/testleak/fake.go
  pkg/util/testleak/leaktest.go
  tests/integration_tests/availability/owner.sh
  tests/integration_tests/capture_session_done_during_task/run.sh
  tests/integration_tests/changefeed_auto_stop/run.sh
  tests/integration_tests/changefeed_error/run.sh
  tests/integration_tests/ddl_puller_lag/run.sh
  tests/integration_tests/gc_safepoint/run.sh
  tests/integration_tests/kill_owner_with_ddl/run.sh
  tests/integration_tests/owner_remove_table_error/run.sh
  tests/integration_tests/processor_err_chan/run.sh
  tests/integration_tests/processor_panic/run.sh
  tests/integration_tests/processor_stop_delay/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, cherry-pick-approved, needs-cherry-pick-release-5.1, release-note-none

#3992 ticdc/processor: Fix backoff base delay misconfiguration
  cdc/processor/processor.go
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#4031 test(dm): fix unexpected sync-diff temporarily
  dm/tests/shardddl4/run.sh
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/dm

#3880 ticdc/pipeline: puller table actor refactor
  cdc/processor/pipeline/actor_node_context.go
  cdc/processor/pipeline/actor_node_context_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/system/system.go
  cdc/processor/pipeline/system/system_test.go
Labels: component/puller, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#3898 misc(ticdc): add more linters and fix issues found by misspell
  .golangci.yml
  Makefile
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/model/kv.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/processor.go
  cdc/sink/common/common_test.go
  cdc/sorter/encoding/key.go
  cdc/sorter/leveldb/table_sorter_test.go
  pkg/cmd/cli/cli_changefeed_cyclic_create_marktables.go
  pkg/cyclic/mark/mark.go
  pkg/cyclic/replication.go
  pkg/pipeline/node.go
  pkg/pipeline/pipeline_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#3674 RFC(dm): Add enhanced pre-check rfc
  dm/docs/RFCS/20211130_enhanced_pre_checker.md
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#4011 dm: add a query-status it-test
  dm/tests/many_tables/run.sh
Labels: status/LGT2, status/can-merge, size/XS, contribution, release-note-none, area/dm

#3968 github: add issue requirement to pull request template
  .github/pull_request_template.md
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#3932 capture(cdc), tcpserver: integrate P2P with server & capture
  cdc/capture/capture.go
  cdc/http_status.go
  cdc/http_status_test.go
  cdc/server.go
  pkg/tcpserver/tcp_server.go
  pkg/tcpserver/tcp_server_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#4039 owner(cdc): add a warning for owner DDL puller being stuck
  cdc/owner/ddl_puller.go
  cdc/owner/ddl_puller_test.go
Labels: status/ptal, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#4037 pipeline(ticdc): disable table actor before GA
  pkg/cmd/server/main_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#3778 log(ticdc): output the zap internal errors to stderr
  go.mod
  go.sum
  pkg/cmd/server/server.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
  pkg/logutil/log.go
  pkg/logutil/log_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#3888 pipeline(ticdc): sink node actor refactor
  cdc/processor/pipeline/sink.go
Labels: component/sink, status/LGT2, status/can-merge, size/M, release-note-none

#4053 Revert "test(dm): fix unexpected sync-diff temporarily"
  dm/tests/shardddl4/run.sh
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/dm

#4036 sink(ticdc): set max-message-bytes default to 10m
  cdc/sink/codec/craft.go
  cdc/sink/codec/craft_test.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/producer/kafka/config.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  pkg/config/sink.go
  pkg/kafka/cluster_admin_client_mock_impl.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3853 ddl(ticdc): allow to rename tables
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/model/sink.go
  cdc/redo/common/util.go
  cdc/sink/codec/canal.go
  errors.toml
  go.mod
  go.sum
  pkg/errors/errors.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  tests/integration_tests/ddl_reentrant/run.sh
Labels: type/bugfix, component/ddl, status/LGT2, status/can-merge, first-time-contributor, size/L, release-note-none

#4056 owner(ticdc): fix typo
  cdc/owner/changefeed.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#4042 pkg/p2p(cdc), tests: fix unstable TestClientSendAnomalies
  pkg/p2p/client_test.go
Labels: component/test, status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc

#4010 processor(cdc): do not write to workload keys if new scheduler is enabled
  cdc/processor/processor.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#4008 cdc,regionspan(ticdc): more logs about eventfeed retry rate limit
  cdc/kv/client.go
Labels: component/kv-client, status/LGT2, status/can-merge, size/S, component/metrics-logging, release-note-none, type/enhancement

#4070 protocol(ticdc): remove useless code and setup DefaultMaxMessageBytes
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  errors.toml
  pkg/config/mq_sink_protocol.go
  pkg/config/mq_sink_protocol_test.go
  pkg/config/sink.go
  pkg/errors/errors.go
  pkg/kafka/cluster_admin_client_mock_impl.go
  pkg/kafka/config.go
Labels: type/bugfix, component/sink, status/LGT2, status/can-merge, size/XL, cherry-pick-approved, release-note-none

#4074 codec(cdc): fix encoder `max-message-bytes`
  cdc/sink/codec/craft.go
  cdc/sink/codec/craft_test.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/mq.go
  cdc/sink/mq_test.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
Labels: type/bugfix, status/LGT1, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#4049 worker(dm): adjust error to warning when bin_log OFF
  dm/dm/worker/source_worker.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#3883 ticdc/pipeline: sorter Node actor refactor
  cdc/processor/pipeline/actor_node_context.go
  cdc/processor/pipeline/actor_node_context_test.go
  cdc/processor/pipeline/sorter.go
Labels: status/LGT2, status/can-merge, size/M, component/sorter, release-note-none

#3920 ticdc/cli: use cdc OpenAPI instead of etcd for some cli commands (Part Ⅰ)
  errors.toml
  pkg/api/internal/rest/client.go
  pkg/api/internal/rest/client_test.go
  pkg/api/internal/rest/config.go
  pkg/api/internal/rest/config_test.go
  pkg/api/internal/rest/request.go
  pkg/api/internal/rest/request_test.go
  pkg/errors/errors.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, component/cli, release-note-none, area/ticdc

#4084 sink (ticdc): fix a deadlock due to checkpointTs fall back in sinkNode
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/sink/table_sink.go
  pkg/pipeline/test.go
Labels: type/bugfix, component/sink, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, component/sorter, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#4038 metrics(ticdc): add resolved ts and add changefeed to dataflow
  cdc/owner/changefeed.go
  cdc/owner/metrics.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, component/metrics-logging, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#4072 kv(ticdc): reduce eventfeed rate limited log
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
Labels: type/bugfix, component/kv-client, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, component/metrics-logging, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#4083 sink(ticdc): cherry pick sink bug fix to release 5.3
  cdc/owner/async_sink_test.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/sink/black_hole.go
  cdc/sink/buffer_sink.go
  cdc/sink/buffer_sink_test.go
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/common/common.go
  cdc/sink/common/common_test.go
  cdc/sink/manager.go
  cdc/sink/manager_test.go
  cdc/sink/mq.go
  cdc/sink/mq_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/mysql_worker_test.go
  cdc/sink/simple_mysql_tester.go
  cdc/sink/sink.go
  cdc/sink/table_sink.go
  cmd/kafka-consumer/main.go
  pkg/applier/redo.go
  tests/integration_tests/sink_hang/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, cherry-pick-approved, release-note, type/cherry-pick-for-release-5.3, do-not-merge/needs-linked-issue

#4091 pkg/p2p(cdc), tests: disable flushing for MessageClient's UT
  pkg/p2p/client_test.go
Labels: component/test, status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc

#4058 db,sorter/leveldb(ticdc): remove snapshot
  cdc/sorter/leveldb/cleaner.go
  cdc/sorter/leveldb/cleaner_test.go
  cdc/sorter/leveldb/leveldb.go
  cdc/sorter/leveldb/leveldb_test.go
  cdc/sorter/leveldb/message/task.go
  cdc/sorter/leveldb/metrics.go
  cdc/sorter/leveldb/system/system.go
  cdc/sorter/leveldb/table_sorter.go
  cdc/sorter/leveldb/table_sorter_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/db.go
  pkg/config/server_config.go
  pkg/db/db.go
  pkg/db/db_test.go
  pkg/db/leveldb.go
  pkg/db/pebble.go
Labels: status/LGT2, status/can-merge, size/XXL, component/sorter, release-note-none, type/enhancement

#4117 http_api (ticdc): fix http api 'get processor' panic.
  cdc/capture/http_errors.go
  cdc/capture/http_handler.go
  tests/integration_tests/http_api/util/test_case.py
Labels: type/bugfix, status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#4071 pkg/actor(ticdc): stable tests by extending timeout
  pkg/actor/system_test.go
Labels: component/test, status/LGT2, status/can-merge, size/S, release-note-none

#3990 syncer(dm): support GBK replication
  dm/pkg/binlog/event/util.go
  dm/pkg/parser/common.go
  dm/pkg/utils/common.go
  dm/syncer/dml.go
  dm/syncer/dml_test.go
  dm/syncer/expr_filter_group_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/tests/_utils/run_sql
  dm/tests/_utils/test_prepare
  dm/tests/gbk/conf/diff_config.toml
  dm/tests/gbk/conf/dm-master.toml
  dm/tests/gbk/conf/dm-task.yaml
  dm/tests/gbk/conf/dm-worker1.toml
  dm/tests/gbk/conf/dm-worker2.toml
  dm/tests/gbk/conf/source1.yaml
  dm/tests/gbk/conf/source2.yaml
  dm/tests/gbk/data/db1.increment.sql
  dm/tests/gbk/data/db1.prepare.sql
  dm/tests/gbk/data/db2.increment.sql
  dm/tests/gbk/data/db2.prepare.sql
  dm/tests/gbk/run.sh
  dm/tests/others_integration_2.txt
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm

#4120 tests(cdc): use HTTP API in move_table case
  tests/integration_tests/move_table/main.go
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#4093 loader: fix wrong progress in query-status for loader
  dm/loader/loader.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note, area/dm, needs-cherry-pick-release-5.3

#4004 master(dm): clean and treat invalid load task
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/master/server.go
  dm/tests/_utils/test_prepare
  dm/tests/load_task/conf/dm-task-standalone.yaml
  dm/tests/load_task/conf/dm-task2-standalone.yaml
  dm/tests/load_task/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm, needs-cherry-pick-release-5.3

#4108 pkg/p2p, metrics(cdc): add dashboard panels for Peer Messages
  cdc/capture/capture.go
  cdc/metrics.go
  metrics/grafana/ticdc.json
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/messages.go
  pkg/p2p/metrics.go
  pkg/p2p/server.go
Labels: status/LGT2, status/can-merge, size/XXL, component/metrics-logging, release-note-none, area/ticdc

#3889 scheduler(dm): support auto pause/resume task when transfer source
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/master/openapi.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/master/scheduler/worker.go
  dm/dm/master/server.go
  dm/errors.toml
  dm/pkg/terror/error_list.go
  dm/tests/ha/run.sh
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note, area/dm

#4144 test(dm): add retry to avoid query-status test failed
  dm/tests/many_tables/run.sh
Labels: status/LGT2, status/can-merge, size/XS, contribution, release-note-none, area/dm

#3836 openapi(dm): add openapi conifg in dm-master config file
  dm/dm/master/config.go
  dm/dm/master/config_test.go
  dm/dm/master/dm-master.toml
  dm/dm/master/openapi_test.go
  dm/dm/master/server.go
  dm/tests/dmctl_basic/conf/get_master1.toml
  dm/tests/openapi/conf/dm-master1.toml
  dm/tests/openapi/conf/dm-master2.toml
Labels: status/LGT2, status/can-merge, size/M, release-note, area/dm

#4148 metrics(ticdc): add db metrics
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XXL, component/metrics-logging, component/sorter, release-note-none, area/ticdc

#4125 tests(ticdc): add tests for kafka max-message-bytes
  deployments/ticdc/docker-compose/docker-compose-kafka-integration.yml
  tests/integration_tests/kafka_big_messages/conf/diff_config.toml
  tests/integration_tests/kafka_big_messages/run.sh
  tests/integration_tests/kafka_messages/conf/diff_config.toml
  tests/integration_tests/kafka_messages/run.sh
  tests/utils/gen_kafka_big_messages/main.go
  tests/utils/gen_kafka_big_messages/main_test.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#4151 config(cdc): add a switch EnableNewScheduler
  cdc/capture/capture.go
  cdc/owner/scheduler.go
  cdc/processor/manager.go
  cdc/processor/processor.go
  cdc/server.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
Labels: component/configuration, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#3886 ticdc/pipeline: cyclic node actor refactor
  cdc/processor/pipeline/cyclic_mark.go
  cdc/processor/pipeline/cyclic_mark_test.go
  cdc/processor/pipeline/main_test.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, component/cyclic

#4121 syncer(dm): add collation config "collation_compatible"
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/config/subtask.go
  dm/dm/config/task.go
  dm/dm/config/task_converters.go
  dm/dm/config/task_test.go
  dm/dumpling/dumpling.go
  dm/errors.toml
  dm/pkg/terror/error_list.go
  dm/syncer/ddl.go
  dm/syncer/ddl_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
  dm/tests/sync_collation/conf/dm-task.yaml
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm

#4052 processor(ticdc): ignore error when querying a processor with no attached tables
  cdc/capture/http_handler.go
  tests/integration_tests/http_api/run.sh
  tests/integration_tests/http_api/util/test_case.py
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#4152 pkg/cmd(ticdc): add more tests about ignore debug config
  pkg/cmd/server/server_test.go
  pkg/cmd/util/helper_test.go
Labels: component/configuration, component/test, status/LGT2, status/can-merge, size/M, release-note-none

#3930 mounter(ticdc): fix mounter default value panic and data inconsistency
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  tests/integration_tests/multi_source/diff_config.toml
Labels: status/LGT2, size/XL, do-not-merge/hold, release-note, area/ticdc

#4147 sorter/leveldb(ticdc): optimize write and read throughput
  cdc/processor/pipeline/sorter.go
  cdc/sorter/leveldb/system/system.go
  cdc/sorter/leveldb/table_sorter.go
  cdc/sorter/leveldb/table_sorter_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
Labels: subject/performance, status/LGT2, status/can-merge, size/XXL, component/sorter, release-note-none, area/ticdc

#4085 owner(ticdc): Fix a nil pointer access bug when appending DataPatches
  cdc/owner/changefeed.go
  cdc/owner/feed_state_manager.go
  cdc/owner/owner.go
  cdc/owner/scheduler_v1.go
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3931 ticdc/cli: use cdc OpenAPI instead of etcd for some cli commands (Part Ⅱ)
  cdc/capture/http_handler.go
  cdc/model/http_model.go
  pkg/api/internal/rest/request.go
  pkg/api/internal/rest/request_test.go
  pkg/api/v1/api_client.go
  pkg/api/v1/capture.go
  pkg/api/v1/changefeed.go
  pkg/api/v1/processor.go
  pkg/cmd/cli/cli_changefeed_statistics.go
  pkg/cmd/cli/cli_processor_list.go
  pkg/cmd/cli/cli_processor_query.go
  pkg/version/check.go
Labels: status/LGT2, status/can-merge, size/XXL, component/cli, release-note-none, area/ticdc
