Repository pingcap/tiflow, pull requests merged in 2021-08, with the labels that each got.

#2383 cmd(refactor): add server cmd and cleanup old server and test cmds
  cmd/root.go
  cmd/server.go
  cmd/test.go
  cmd/version.go
  pkg/cmd/cmd.go
  pkg/cmd/factory/factory_impl.go
  pkg/cmd/server/server.go
  pkg/cmd/server/server_test.go
  pkg/cmd/util/helper.go
  pkg/cmd/util/helper_test.go
Labels: component/cli, release-note-none, size/XXL, status/LGT2, status/can-merge

#2415 pipeline: use Message value to reduce GC pressure
  cdc/processor/pipeline/cyclic_mark_test.go
  cdc/processor/pipeline/mounter.go
  cdc/processor/pipeline/mounter_test.go
  cdc/processor/pipeline/sink_test.go
  pkg/pipeline/context.go
  pkg/pipeline/message.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/runner.go
  pkg/pipeline/test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, release-note-none, size/L, status/LGT2, status/can-merge, subject/performance

#2431 logSink: revert defaultBufferChanSize, add a trigger to flush logSink.units when chennal is full
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
Labels: component/pitr, contribution, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, release-note, size/XS, status/LGT2, status/can-merge, type/bugfix

#2430 cmd(refactor): add capture cmd
  pkg/cmd/cli/cli.go
  pkg/cmd/cli/cli_capture.go
  pkg/cmd/cli/cli_capture_list.go
  pkg/cmd/util/helper.go
  pkg/cmd/util/helper_test.go
Labels: component/cli, release-note-none, size/XL, status/LGT2, status/can-merge

#2443 processor: cleanup some unnecessary error logs
  cdc/processor/processor.go
  pkg/pipeline/pipeline.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, release-note-none, require-LGT1, size/XS, status/LGT1, status/can-merge, status/ptal

#2429 changefeed: Fix cannot remove changefeed when err gcttl exceeded
  cdc/owner/changefeed.go
  cdc/owner/gc_manager.go
  cdc/owner/gc_manager_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cmd/util.go
Labels: component/scheduler, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, release-note, size/L, status/LGT2, status/can-merge, type/bugfix

#2423 owner: ignore duplicated DDL job in ddl puller
  cdc/owner/ddl_puller.go
  cdc/owner/ddl_puller_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, release-note, size/S, status/LGT2, status/can-merge, type/bugfix

#2416 *: add some open API to cdc.
  cdc/capture/capture.go
  cdc/capture/http_handler.go
  cdc/http_api_handler.go
  cdc/http_handler.go
  cdc/http_router.go
  cdc/http_status.go
  cdc/http_status_test.go
  cdc/model/changefeed.go
  cdc/model/http_model.go
  cdc/server.go
  docs/api/docs.go
  docs/api/swagger.json
  docs/api/swagger.yaml
  errors.toml
  go.mod
  go.sum
  pkg/context/context.go
  pkg/errors/errors.go
  pkg/httputil/httputil.go
Labels: release-note, size/XXL, status/LGT2, status/can-merge, status/ptal

#2447 server: close session if old capture dead.
  cdc/server.go
Labels: cherry-pick-approved, needs-cherry-pick-release-5.0, release-note, size/S, status/LGT2, status/can-merge, type/bugfix

#2473 cli(refactor): add cli cmds for processor, tso and unsafe
  pkg/cmd/cli/cli.go
  pkg/cmd/cli/cli_processor.go
  pkg/cmd/cli/cli_processor_list.go
  pkg/cmd/cli/cli_processor_query.go
  pkg/cmd/cli/cli_tso.go
  pkg/cmd/cli/cli_tso_query.go
  pkg/cmd/cli/cli_unsafe.go
  pkg/cmd/cli/cli_unsafe_delete_service_gc_safepoint.go
  pkg/cmd/cli/cli_unsafe_reset.go
  pkg/cmd/cli/cli_unsafe_show_metadata.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#2467 makefile: bump release version to 5.2.0-master when built from master
  Makefile
  pkg/version/check_test.go
Labels: status/ptal, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#2475 kv/client: change some error log to warn log
  cdc/kv/client.go
  cdc/kv/client_v2.go
Labels: status/ptal, component/kv-client, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, release-note-none

#2201 workerpool: remove mergeContext
  pkg/workerpool/context.go
  pkg/workerpool/context_test.go
  pkg/workerpool/pool.go
  pkg/workerpool/pool_impl.go
  pkg/workerpool/pool_test.go
Labels: status/ptal, subject/performance, release-blocker, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, needs-cherry-pick-release-5.1, needs-cherry-pick-5.2

#2417 sink: add barrier in underlying sink to support accruate stop
  cdc/changefeed.go
  cdc/owner.go
  cdc/owner/async_sink.go
  cdc/owner/async_sink_test.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/processor.go
  cdc/sink/black_hole.go
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/manager.go
  cdc/sink/manager_test.go
  cdc/sink/mq.go
  cdc/sink/mq_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/simple_mysql_tester.go
  cdc/sink/sink.go
  cmd/util.go
Labels: type/bugfix, release-blocker, status/LGT1, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, require-LGT1, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2474 *: use values to reduce GC pressure
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/kv/testing.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  errors.toml
  pkg/errors/errors.go
  pkg/pipeline/pipeline_test.go
  pkg/workerpool/pool_impl.go
  pkg/workerpool/pool_test.go
Labels: subject/performance, release-blocker, status/LGT1, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, require-LGT1, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2503 client,server:check all pd versions
  cdc/server.go
  cmd/client.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, contribution, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2501 tests: fix unified_sorter_sort_dir_conflict
  tests/unified_sorter_sort_dir_conflict/run.sh
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/S, cherry-pick-approved, release-note-none

#2453 metrics: optimize prometheus metrics label
  cdc/kv/client.go
  cdc/kv/metrics.go
  cdc/kv/token_region.go
  cdc/metrics_processor.go
  cdc/processor.go
  cdc/processor/pipeline/metrics.go
  cdc/processor/pipeline/sorter.go
  cdc/puller/metrics.go
  cdc/puller/puller.go
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/metrics.go
  cdc/puller/sorter/unified_sorter.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, component/metrics-logging, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2471 owner, changefeed: backport async sink to old owner
  cdc/async_sink.go
  cdc/async_sink_test.go
  cdc/changefeed.go
  cdc/owner.go
  cdc/owner_test.go
  tests/ddl_async/conf/block_cf_config.toml
  tests/ddl_async/conf/diff_config.toml
  tests/ddl_async/conf/normal_cf_config.toml
  tests/ddl_async/data/prepare.sql
  tests/ddl_async/run.sh
  tests/ddl_reentrant/run.sh
Labels: status/ptal, component/replica-model, status/LGT2, status/can-merge, size/XXL, cherry-pick-approved, release-note-none

#2523 http: enable all sub paths matching in pprof
  cdc/http_router.go
  cdc/http_status_test.go
Labels: status/ptal, release-blocker, status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, needs-cherry-pick-release-5.2

#2511 kv/client: add global grpc connection pool
  cdc/capture.go
  cdc/capture/capture.go
  cdc/capture_test.go
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/grpc_pool.go
  cdc/kv/grpc_pool_impl.go
  cdc/kv/grpc_pool_impl_test.go
  cdc/kv/metrics.go
  cdc/kv/testing.go
  cdc/owner.go
  cdc/owner/ddl_puller.go
  cdc/owner_operator.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/processor/pipeline/puller.go
  cdc/processor/processor.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/context/context.go
Labels: component/kv-client, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2472 http_*: add create and update changefeed API
  cdc/capture/http_handler.go
  cdc/capture/http_validatior.go
  cdc/http_router.go
  cdc/http_status.go
  cdc/model/http_model.go
  cmd/util.go
  docs/api/docs.go
  docs/api/swagger.json
  docs/api/swagger.yaml
  errors.toml
  pkg/errors/errors.go
  tests/cli/run.sh
Labels: status/ptal, release-blocker, subject/new-feature, status/LGT1, status/can-merge, component/status-server, size/XXL, require-LGT1, release-note, needs-cherry-pick-release-5.2

#2528 *: replace unified sorter dir conflict test with unit tests
  cdc/processor/pipeline/sorter_test.go
  cdc/puller/sorter/sorter_test.go
  cdc/puller/sorter/unified_sorter.go
  tests/unified_sorter_sort_dir_conflict/run.sh
Labels: component/test, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, component/sorter, release-note-none, needs-cherry-pick-release-5.2

#2555 chore: remove useless CHANGELOG.md and uniform actions file ext
  .github/workflows/check_and_build.yaml
  .github/workflows/integration.yaml
  CHANGELOG.md
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#2510 EtcdWorker: fix EtcdWorker snapshot isolation
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_test.go
Labels: type/bugfix, component/scheduler, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2556 owner, async_sink: fix ddl sink error does not stop changefeed
  cdc/async_sink.go
  cdc/owner.go
  tests/changefeed_error/run.sh
Labels: type/bugfix, component/replica-model, status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note-none

#2567 kvclient: Fix grpc pool error handling
  cdc/kv/grpc_pool_impl.go
Labels: component/kv-client, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2576 Old Replicate Model: remove the old owner and old changefeed
  cdc/changefeed.go
  cdc/changefeed_test.go
  cdc/metrics.go
  cdc/metrics_owner.go
  cdc/owner.go
  cdc/owner/gc_manager.go
  cdc/owner/gc_manager_test.go
  cdc/owner_operator.go
  cdc/owner_test.go
  cdc/server.go
  cmd/client_unsafe.go
  pkg/cmd/cli/cli_unsafe_delete_service_gc_safepoint.go
  pkg/cmd/cli/cli_unsafe_reset.go
Labels: component/replica-model, status/LGT2, status/can-merge, size/XXL, release-note-none

#2569 tests: fix more events could be sent after a table is removed
  cdc/sink/manager_test.go
Labels: status/ptal, component/test, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2525 test: fix unstable test TestUpdateTs
  cdc/puller/frontier/heap_test.go
Labels: component/test, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2568 test: fix TestStreamSendWithError unstable test
  cdc/kv/client_test.go
Labels: component/test, status/LGT1, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, cherry-pick-approved, require-LGT1, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2566 tests: fix unstable test in ddl puller test
  cdc/owner/ddl_puller_test.go
Labels: status/ptal, component/test, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, cherry-pick-approved, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2590 Old Replicate Model: delete old capture and old processor related codes
  cdc/capture.go
  cdc/capture_test.go
  cdc/metrics.go
  cdc/metrics_processor.go
  cdc/processor.go
  cdc/processor_test.go
  cdc/task.go
  cdc/task_test.go
Labels: component/replica-model, status/LGT2, status/can-merge, size/XXL, release-note-none

#2563 tests: Add integration test for http api
  cdc/capture/http_handler.go
  cdc/http_router.go
  tests/http_api/run.sh
  tests/http_api/util/test_case.py
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-5.2

#2604 owner: fix schema snapshot read from TiKV
  cdc/owner/changefeed.go
  cdc/owner/schema.go
  tests/ddl_reentrant/run.sh
Labels: status/ptal, type/bugfix, component/replica-model, release-blocker, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2539 cli(refactor): add create changefeed cmd
  pkg/cmd/cli/cli.go
  pkg/cmd/cli/cli_changefeed.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_helper.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, needs-cherry-pick-release-5.2

#2615 sink/mq: fix empty value in open protocol
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/mq_test.go
Labels: component/open-protocol, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, cherry-pick-approved, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2618 test: fix TestRemoveNode timeout
  cdc/puller/frontier/heap_test.go
Labels: component/test, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2626 owner: fix scheduling tables too early
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
Labels: type/bugfix, component/replica-model, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2639 owner: fix gc safepoint larger by one
  cdc/owner/gc_manager.go
  cdc/owner/gc_manager_test.go
  tests/gc_safepoint/run.sh
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note-none

#2664 test: Make sure the server is really started
  tests/_utils/run_cdc_server
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#2671 metrics: add ddl execution duration metrics
  cdc/sink/metrics.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/statistics.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, component/metrics-logging, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#2663 capture: refine some comments and simplify IsOwner func
  cdc/capture/capture.go
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#2605 async_sink: backport async sink to 5.0-branch old owner
  cdc/async_sink.go
  cdc/async_sink_test.go
  cdc/changefeed.go
  cdc/owner.go
  cdc/owner_test.go
  tests/changefeed_error/run.sh
  tests/cyclic_abc/run.sh
  tests/ddl_async/conf/block_cf_config.toml
  tests/ddl_async/conf/diff_config.toml
  tests/ddl_async/conf/normal_cf_config.toml
  tests/ddl_async/data/prepare.sql
  tests/ddl_async/run.sh
  tests/ddl_reentrant/run.sh
Labels: status/ptal, component/replica-model, status/LGT2, status/can-merge, size/XXL, cherry-pick-approved, release-note
