Repository pingcap/tiflow, pull requests merged in 2021-05, with the labels that each got.

#1722 http_server: add http handler for failpoint
  cdc/http_status.go
  cdc/http_status_test.go
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/M, status/LGT2, status/can-merge

#1680 *: sink flow control
  cdc/kv/client.go
  cdc/processor/pipeline/metrics.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/sink/common/flow_control.go
  cdc/sink/common/flow_control_test.go
  cmd/server_test.go
  errors.toml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/errors/errors.go
  pkg/pipeline/pipeline.go
Labels: component/replica-model, component/sink, needs-cherry-pick-release-5.0, ptal, size/XXL, status/LGT2, status/can-merge

#1663 sorter: Unified Sorter clean up stale temporary files
  Makefile
  cdc/processor.go
  cdc/processor/pipeline/sorter.go
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/backend_pool_test.go
  cdc/puller/sorter/file_backend.go
  cdc/puller/sorter/sorter_test.go
  cdc/puller/sorter/unified_sorter.go
  docker-compose-avro.yml
  errors.toml
  pkg/errors/errors.go
  pkg/filelock/filelock.go
  pkg/filelock/filelock_test.go
  testing_utils/many_sorters_test/many_sorters.go
  testing_utils/sorter_stress_test/sorter_stress.go
  tests/_utils/run_cdc_server
  tests/availability/capture.sh
  tests/unified_sorter_sort_dir_conflict/run.sh
Labels: component/puller, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XXL, status/LGT2, status/can-merge

#1738 tests: add random region merge test
  tests/_utils/start_tidb_cluster
  tests/_utils/start_tidb_cluster_impl
  tests/region_merge/conf/diff_config.toml
  tests/region_merge/conf/pd_config.toml
  tests/region_merge/run.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/L, status/LGT2, status/can-merge, subject/test

#1730 sorter: cherry-pick Unified Sorter changes to release-4.0
  cdc/owner.go
  cdc/processor.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/backend_pool_test.go
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/merger_test.go
  cdc/puller/sorter/sorter_test.go
  cdc/puller/sorter/unified_sorter.go
  cmd/client_changefeed.go
  cmd/server.go
  cmd/server_test.go
  errors.toml
  go.sum
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/sorter.go
  pkg/errors/errors.go
  testing_utils/many_sorters_test/many_sorters.go
  testing_utils/sorter_stress_test/sorter_stress.go
Labels: cherry-pick-approved, size/XXL, status/LGT2, status/can-merge, type/4.0-cherry-pick

#1731 owner: Modified the update strategy of gcSafePoint
  cdc/owner.go
  cdc/owner_test.go
  errors.toml
  pkg/errors/errors.go
Labels: contribution, first-time-contributor, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/L, status/LGT2, status/can-merge

#1727 lock-resolver: fix the overhead in region cache api
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/puller/mock_puller.go
  go.mod
  go.sum
  pkg/txnutil/lock_resolver.go
Labels: ptal, size/L, status/LGT2, status/can-merge

#1744 new_owner: a tso barriers mechanism
  cdc/owner/barrier.go
  cdc/owner/barrier_test.go
  cdc/owner/changefeed_state.go
  cdc/owner/changefeed_state_test.go
  cdc/owner/owner_state.go
  cdc/owner/owner_state_test.go
  cdc/owner/scheduler.go
  cdc/owner/scheduler_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XXL, status/LGT2, status/can-merge

#1751 *: sink flow control for old processor
  Makefile
  cdc/metrics_processor.go
  cdc/processor.go
  cdc/processor/pipeline/metrics.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/sink/common/flow_control.go
  cdc/sink/common/flow_control_test.go
  cmd/server_test.go
  errors.toml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/errors/errors.go
  pkg/pipeline/pipeline.go
Labels: cherry-pick-approved, component/replica-model, ptal, size/XXL, status/LGT2, status/can-merge, type/cherry-pick-for-release-4.0

#1764 go/mod: upgrade tidb/parser to latest release-4.0
  go.mod
  go.sum
Labels: cherry-pick-approved, size/S, status/LGT2, status/can-merge, type/cherry-pick-for-release-4.0

#1752 metrics: update TiKV metrics
  metrics/grafana/ticdc.json
Labels: component/metrics, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, status/LGT2, status/can-merge

#1459 *: refine the vars in context.Context
  cdc/capture.go
  cdc/capture_test.go
  cdc/owner_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/pipeline/cyclic_mark.go
  cdc/processor/pipeline/cyclic_mark_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/server.go
  pkg/config/config.go
  pkg/context/context.go
  pkg/context/context_test.go
  pkg/pipeline/pipeline_test.go
  pkg/util/ctx.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, require-LGT1, size/XXL, status/LGT1, status/can-merge

#1773 context: uniform the import naming of context, part 1
  cdc/processor/pipeline/cyclic_mark_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/M, status/LGT2, status/can-merge

#1779 *: fix flow control deadlock (release-4.0)
  cdc/sink/common/flow_control.go
  cdc/sink/common/flow_control_test.go
Labels: cherry-pick-approved, release-blocker, size/M, status/LGT2, status/can-merge, type/bugfix

#1783 *: fix a typo
  cdc/processor/state.go
  pkg/etcd/etcdkey.go
  pkg/etcd/etcdkey_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/S, status/LGT2, status/can-merge

#1755 tests: use normal mysql user in integration test
  tests/_utils/start_tidb_cluster_impl
  tests/autorandom/run.sh
  tests/availability/run.sh
  tests/batch_add_table/run.sh
  tests/capture_session_done_during_task/run.sh
  tests/capture_suicide_while_balance_table/run.sh
  tests/cdc/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/changefeed_error/run.sh
  tests/changefeed_finish/run.sh
  tests/changefeed_pause_resume/run.sh
  tests/changefeed_reconstruct/run.sh
  tests/cli/run.sh
  tests/clustered_index/run.sh
  tests/common_1/run.sh
  tests/ddl_puller_lag/run.sh
  tests/ddl_reentrant/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/force_replicate_table/run.sh
  tests/gc_safepoint/run.sh
  tests/generate_column/run.sh
  tests/kill_owner_with_ddl/run.sh
  tests/kv_client_stream_reconnect/run.sh
  tests/many_pk_or_uk/run.sh
  tests/move_table/run.sh
  tests/multi_capture/run.sh
  tests/multi_source/run.sh
  tests/new_ci_collation/run.sh
  tests/owner_remove_table_error/run.sh
  tests/partition_table/run.sh
  tests/processor_err_chan/run.sh
  tests/processor_panic/run.sh
  tests/processor_resolved_ts_fallback/run.sh
  tests/processor_stop_delay/run.sh
  tests/region_merge/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/run.sh
  tests/simple/run.sh
  tests/sink_hang/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/syncpoint/run.sh
  tests/tiflash/run.sh
  tests/unified_sorter/run.sh
  tests/unified_sorter_sort_dir_conflict/run.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/L, status/LGT2, status/can-merge, subject/test

#1777 *:refine log output
  cdc/kv/client.go
  cdc/puller/sorter/merger.go
  cmd/client_changefeed.go
Labels: cherry-pick-approved, size/XS, status/LGT2, status/can-merge

#1784 cmd: hide --sort-dir in changefeed command. (deprecated warning exists)
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/processor/state_test.go
  cmd/client_changefeed.go
  tests/unified_sorter/run.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, status/LGT2, status/can-merge

#1720 kv/client: use ephemeral goroutine to handle region range request
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/L, status/LGT2, status/can-merge, type/bugfix

#1481 kv-client: use worker pool in region worker
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/server.go
  cmd/server_test.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/kvclient.go
  pkg/util/testleak/leaktest.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XXL, status/LGT2, status/can-merge

#1787 config: hidden the ddl-allow-list config entry
  pkg/config/config_test.go
  pkg/config/filter.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XS, status/LGT2, status/can-merge

#1797 mysql: refine log - Deleted useless log info that may cause confusion for users.
  cdc/sink/mysql.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XS, status/LGT2, status/can-merge

#1747 etcd_worker: support update multi-keys in a DataPatch
  cdc/processor/processor_test.go
  cdc/processor/state.go
  cdc/processor/state_test.go
  pkg/orchestrator/doc.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/interfaces.go
  pkg/orchestrator/jsonstate/json_reactor_state.go
  pkg/orchestrator/jsonstate/json_reactor_state_test.go
  pkg/orchestrator/reactor_state_tester.go
  testing_utils/cdc_state_checker/state.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XXL, status/LGT2, status/can-merge

#1810 new_owner: let processor and owner use the same reactor state
  cdc/model/reactor_state.go
  cdc/model/reactor_state_test.go
  errors.toml
  pkg/errors/errors.go
  pkg/etcd/etcdkey.go
  pkg/orchestrator/reactor_state_tester.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XXL, status/LGT2, status/can-merge

#1813 etcd_worker: fix a bug that etcd worker maybe lost data at starting
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_bank_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/L, status/LGT2, status/can-merge

#1814 owner: fix a bug which lead to replication stopped and no error report
  cdc/changefeed.go
  cdc/changefeed_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/L, status/LGT2, status/can-merge, subject/replication-interruption, type/bugfix

#1766 new_owner: a schema wrapper for owner
  Makefile
  cdc/entry/schema_storage.go
  cdc/entry/schema_test_helper.go
  cdc/owner/schema.go
  cdc/owner/schema_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XL, status/LGT2, status/can-merge

#1818 build: upgrade to go1.16.4
  .github/workflows/check_and_build.yml
  .github/workflows/integration.yml
  Dockerfile
  Dockerfile.development
  Makefile
  go.mod
  go.sum
  tools/check/go.mod
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/M, status/LGT2, status/can-merge

#1836 tests: fix tiflash storage engine in integration test
  tests/_utils/start_tidb_cluster_impl
  tests/processor_panic/main.go
Labels: needs-cherry-pick-release-5.0, require-LGT1, size/XS, status/LGT1, status/can-merge, subject/test

#1819 new_owner: implement gc manager
  cdc/model/changefeed.go
  cdc/owner/gc_manager.go
  cdc/owner/gc_manager_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XL, status/LGT2, status/can-merge

#1776 new_owner: a ddl puller wrapper for owner
  cdc/owner/ddl_puller.go
  cdc/owner/ddl_puller_test.go
  pkg/context/context.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XL, status/LGT2, status/can-merge

#1835 changefeed: log start-ts when applying ddl job
  cdc/changefeed.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XS, status/LGT2, status/can-merge

#1847 kv/client: fix time is not updated when receiving committed event
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, status/LGT2, status/can-merge, type/bugfix

#1837 *: fix flow control deadlock (port to master)
  cdc/sink/common/flow_control.go
  cdc/sink/common/flow_control_test.go
Labels: component/replica-model, needs-cherry-pick-release-5.0, ptal, release-blocker, size/M, status/LGT2, status/can-merge, type/bugfix

#1759 owner: Modified the update strategy of gcSafePoint (#1731)
  cdc/owner.go
  cdc/owner_test.go
  errors.toml
  pkg/errors/errors.go
Labels: cherry-pick-approved, contribution, release-blocker, size/L, status/LGT2, status/can-merge, type/cherry-pick-for-release-5.0

#1854 sorter: reduce memory malloc to avoid too much CPU overhead
  cdc/puller/sorter/heap_sorter.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, release-blocker, size/XS, status/LGT2, status/can-merge

#1840 *: port sink flow control for old processor & new processor to release-5.0
  cdc/metrics_processor.go
  cdc/processor.go
  cdc/processor/pipeline/metrics.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/sink/common/flow_control.go
  cdc/sink/common/flow_control_test.go
  cmd/server_test.go
  errors.toml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/errors/errors.go
  pkg/pipeline/pipeline.go
Labels: cherry-pick-approved, component/replica-model, ptal, release-blocker, size/XXL, status/LGT2, status/can-merge, type/cherry-pick-for-release-5.0

#1860 build: update tidb/pd/parser dep to latest release-5.0
  go.mod
  go.sum
Labels: cherry-pick-approved, release-blocker, size/L, status/LGT2, status/can-merge

#1855 sorter: fix unstable unit tests
  cdc/puller/sorter/sorter_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, status/LGT2, status/can-merge

#1861 Owner: Fix gcttl bug
  cdc/owner.go
  cdc/owner_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, release-blocker, size/L, status/LGT2, status/can-merge

#1782 new_owner: an async sink for owner
  cdc/owner/async_sink.go
  cdc/owner/async_sink_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, require-LGT1, size/XL, status/LGT1, status/can-merge

#1834 docs: fix typo in design of new processor
  cdc/processor/doc.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XS, status/LGT2, status/can-merge

#1845 README: remove the TiDB Monthly link
  README.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, status/LGT2, status/can-merge

#1826 new_owner: a feed state manager for owner
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  pkg/errors/helper.go
  pkg/filter/errors.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, require-LGT1, size/XXL, status/LGT1, status/can-merge

#1846 metrics: add metrics for table memory consumption
  metrics/grafana/ticdc.json
Labels: component/metrics, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/L, status/LGT2, status/can-merge

#1820 new_owner: a table task scheduler for the owner
  cdc/owner/scheduler.go
  cdc/owner/scheduler_test.go
  errors.toml
  pkg/errors/errors.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XXL, status/LGT2, status/can-merge

#1886 new owner: port metrics from the old owner
  cdc/metrics.go
  cdc/owner/metrics.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/M, status/LGT2, status/can-merge

#1821 new_owner: refine processor
  cdc/capture.go
  cdc/owner/async_sink_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/state.go
  cdc/processor/state_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, require-LGT1, size/XXL, status/LGT1, status/can-merge

#1883 mysql sink: refine log
  cdc/sink/mysql.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, status/LGT2, status/can-merge
