Repository pingcap/tiflow, pull requests merged in 2021-06, with the labels that each got.

#1894 new_owner: a changefeed implement
  cdc/entry/schema_storage.go
  cdc/owner.go
  cdc/owner/async_sink.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/schema.go
  cmd/client_changefeed.go
  cmd/util.go
  errors.toml
  pkg/context/context.go
  pkg/errors/errors.go
  pkg/errors/helper.go
  pkg/util/gc_service.go
  pkg/util/gc_service_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XXL, status/LGT2, status/can-merge

#1890 sink: disable external storage check-path for cdc log
  cdc/sink/cdclog/s3.go
Labels: component/sink, first-time-contributor, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XS, status/LGT2, status/can-merge

#1909 new_owner: a owner implement, the owner is a manager of changefeeds
  cdc/owner/metrics.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XL, status/LGT2, status/can-merge

#1903 kv/client: fix region worker exited error
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  errors.toml
  pkg/errors/errors.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/M, status/LGT2, status/can-merge

#1914 new_owner: a capture implement, the capture manages and runs the owner and processor
  cdc/capture/capture.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_puller.go
  cdc/owner/ddl_puller_test.go
  cdc/owner/gc_manager.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XL, status/LGT2, status/can-merge

#1932 sorter: fix unstable test
  cdc/puller/sorter/sorter_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, status/LGT2

#1927 new_owner: switch on the new owner
  cdc/capture/capture.go
  cdc/http_handler.go
  cdc/http_status.go
  cdc/model/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/server.go
  cmd/server.go
  pkg/orchestrator/etcd_worker_bank_test.go
  tests/availability/owner.sh
  tests/availability/processor.sh
  tests/changefeed_auto_stop/run.sh
  tests/changefeed_error/run.sh
  tests/changefeed_finish/run.sh
  tests/cli/run.sh
  tests/cyclic_abc/conf/changefeed.toml
  tests/cyclic_abc/run.sh
  tests/ddl_reentrant/run.sh
  tests/gc_safepoint/run.sh
  tests/kafka_sink_error_resume/run.sh
  tests/kill_owner_with_ddl/run.sh
  tests/owner_remove_table_error/run.sh
  tests/processor_err_chan/run.sh
  tests/sink_hang/run.sh
  tests/syncpoint/run.sh
  tests/unified_sorter_sort_dir_conflict/run.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XXL, status/LGT2, status/can-merge

#1643 file: add a O_TRUNC flag when create a new log.meta
  cdc/sink/cdclog/file.go
Labels: component/pitr, contribution, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XS, status/LGT2, status/can-merge

#1789 sink/kafka: add sasl scram support for kafka sink
  cdc/sink/mq.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  go.mod
  go.sum
  pkg/security/sasl_scram.go
  pkg/security/scram_client.go
Labels: contribution, first-time-contributor, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/L, status/LGT2, status/can-merge

#1916 tests: fix leak test in embeded etcd test
  pkg/etcd/etcd_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/S, status/LGT2, status/can-merge, subject/test

#1929 sink/mysql: adjust producer/consumer exit sequence to avoid goroutine leak
  cdc/sink/manager_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: component/sink, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, status/LGT2, status/can-merge

#1940 tests: fix a unstable test in CI
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  pkg/etcd/client.go
  tests/processor_resolved_ts_fallback/run.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, require-LGT1, size/S, status/LGT1, status/can-merge

#1906 kv/client: decrease standby gRPC connection count
  cdc/kv/client.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/XS, status/LGT2, status/can-merge

#1952 owner: fix a changefeed can not removed when the changefeed status is not exist
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, ptal, size/M, status/LGT2, status/can-merge

#1917 http_*: add a HTTP API to list changefeed info
  cdc/http_api_handler.go
  cdc/http_handler.go
  cdc/http_status.go
  errors.toml
  pkg/errors/errors.go
  pkg/httputil/httputil.go
Labels: needs-cherry-pick-release-5.0, ptal, size/L, status/LGT2, status/can-merge

#1915 sorter: fix unified sorter magic numbers & reduce memory consumption by channels
  cdc/puller/sorter/file_backend.go
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/unified_sorter.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, status/LGT2, status/can-merge

#1964 owner: fix the owner panic
  cdc/model/reactor_state.go
  cdc/model/reactor_state_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, size/XS, status/LGT2, status/can-merge

#1949 kv/client: refine region reconnect and resolve lock strategy
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, size/XL, status/LGT2, status/can-merge

#1969 sorter: provide more information on sorter IO errors
  cdc/puller/sorter/file_backend.go
  cdc/puller/sorter/file_backend_test.go
  pkg/errors/errors.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge

#1981 kv/client: add incremental scan region count limit
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/metrics.go
  cdc/kv/region_worker.go
  cdc/kv/token_region.go
  cdc/kv/token_region_test.go
  tests/move_table/conf/workload
Labels: cherry-pick-approved, size/XXL, status/LGT2, status/can-merge, type/cherry-pick-for-release-5.0

#1980 owner: fix owner ship metrics
  cdc/owner/owner.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, size/XS, status/LGT2, status/can-merge

#1989 *: fix err docs
  errors.toml
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#2004 owner: fix some nil panic when switch off the new owner
  cdc/http_handler.go
  cdc/http_status.go
  cdc/owner/owner.go
  cdc/server.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, size/M, status/LGT2, status/can-merge

#1926 kv/client: add incremental scan region count limit
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/metrics.go
  cdc/kv/region_worker.go
  cdc/kv/token_region.go
  cdc/kv/token_region_test.go
  tests/move_table/conf/workload
Labels: cherry-pick-approved, component/kv-client, release-blocker, size/XXL, status/LGT2, status/can-merge, type/cherry-pick-for-release-4.0

#1988 owner: fix etcd error too many operations in txn request
  cdc/model/reactor_state.go
  cdc/model/reactor_state_test.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/owner.go
  cdc/processor/manager.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_bank_test.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/interfaces.go
  pkg/orchestrator/reactor_state_tester.go
  testing_utils/cdc_state_checker/state.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/L, status/LGT1, status/can-merge

#1999 *: reduce memory consumption by reducing channel sizes
  cdc/kv/region_worker.go
  pkg/workerpool/pool_impl.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, require-LGT1, size/XS, status/LGT1, status/can-merge

#1987 *: fix deadlock in new processor
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/merger_test.go
  cdc/puller/sorter/unified_sorter.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, size/XL, status/LGT2, status/can-merge

#2003 owner: check the version of the ticdc cluster
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  pkg/context/context.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, size/M, status/LGT2, status/can-merge

#2014 sorter: fix panic when getting memory pressure fails
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/backend_pool_test.go
Labels: internal-test, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, size/M, status/LGT2, status/can-merge, type/bugfix

#1076 tests/bank: add bank case
  tests/bank/bank.go
  tests/bank/case.go
  tests/bank/run.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XXL, status/LGT2, status/can-merge, subject/test

#1922 kv/client: cherry pick #1591,#1674,#1682,#1481,#1847,#1903 to release-5.0
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/kv/resolvedts_heap.go
  cdc/kv/resolvedts_heap_test.go
  cdc/server.go
  cmd/server_test.go
  errors.toml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/kvclient.go
  pkg/errors/errors.go
  pkg/util/testleak/leaktest.go
Labels: cherry-pick-approved, component/kv-client, ptal, size/XXL, status/LGT2, status/can-merge, type/cherry-pick-for-release-5.0

#1985 owner: Fix owner exit due to emit checkpoint failure
  cdc/changefeed.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/server.go
  cdc/sink/cdclog/s3.go
  cdc/sink/mq.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  cdc/sink/sink.go
  errors.toml
  pkg/errors/errors.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, size/L, status/LGT2, status/can-merge

#1979 kv/client: fix token counter in region scan limiter
  cdc/kv/client.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, size/M, status/LGT2, status/can-merge

#2029 gc_manager: refine update gc service safe point
  cdc/owner/changefeed.go
  cdc/owner/gc_manager.go
  cdc/owner/gc_manager_test.go
  errors.toml
  pkg/errors/errors.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, size/M, status/LGT2, status/can-merge

#2034 black_hole:Delete an unnecessary check that will cause panic.
  cdc/sink/black_hole.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, size/XS, status/LGT2, status/can-merge

#2038 kv/client: send resovled ts in advance when region is locked
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/puller/frontier/frontier_test.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, size/L, status/LGT2, status/can-merge

#2039 metrics: use go_goroutines to get the tidb_cluster label
  metrics/grafana/ticdc.json
Labels: first-time-contributor, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, size/XS, status/LGT2, status/can-merge

#1990 owner: deprecate the removed changefeed state
  cdc/model/changefeed.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  tests/cli/run.sh
  tests/gc_safepoint/run.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, size/M, status/LGT2, status/can-merge

#2054 cli: fix changefeed-id need to be limit max length
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cmd/client_changefeed.go
  errors.toml
  pkg/errors/errors.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge

#2059 processor: prevents individual table pipelines to block the entire processor
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  errors.toml
  pkg/errors/errors.go
  pkg/pipeline/pipeline.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, release-blocker, severity/critical, size/M, status/LGT2, status/can-merge, type/bugfix

#1879 CDC Server support data-dir
  cdc/processor.go
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/backend_pool_test.go
  cdc/puller/sorter/sorter_test.go
  cdc/server.go
  cdc/server_test.go
  cmd/client_changefeed.go
  cmd/client_changefeed_test.go
  cmd/server.go
  cmd/server_test.go
  errors.toml
  go.mod
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/errors/errors.go
  pkg/util/fileutil.go
  pkg/util/fileutil_test.go
  tests/_utils/run_cdc_server
  tests/unified_sorter_sort_dir_conflict/run.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, release-blocker, size/XXL, status/LGT2, status/can-merge

#2060 kv/client: set drop resolved ts log to debug level
  cdc/kv/client.go
  cdc/kv/client_v2.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, size/XS, status/LGT2, status/can-merge

#2077 puller: ignore fallen back resolved ts
  cdc/puller/puller.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, size/XS, status/LGT2, status/can-merge

#2078 table_pipeline: Fix blocking entire pipeline when DDL puller is lagging behind
  cdc/processor/pipeline/mounter.go
  cdc/processor/pipeline/mounter_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
Labels: component/replica-model, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, severity/critical, size/XL, status/LGT2, status/can-merge, type/bugfix

#2089 processor: cancel all tables all at once
  cdc/processor/processor.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.1, release-blocker, size/XS, status/LGT2, status/can-merge

#2084 readme: Update the expired docker-compose startup command
  README.md
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#2085 sorter: add close check to AddEntry
  cdc/puller/sorter/sorter_test.go
  cdc/puller/sorter/unified_sorter.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, release-blocker, size/M, status/LGT2, status/can-merge

#2090 puller: try to fix bad permission for backend test .
  cdc/puller/sorter/backend_pool_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#2050 kv_client: fix unit tests deadlocked when panicking
  cdc/kv/client_test.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, require-LGT1, size/M, status/LGT1, status/can-merge, subject/test

#2109 *: update tidb
  cdc/entry/mounter_test.go
  cdc/entry/schema_storage_test.go
  cdc/entry/schema_test_helper.go
  cdc/http_api_handler.go
  cdc/http_handler.go
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/kv/store_op.go
  cdc/kv/testing.go
  cdc/kv/token_region_test.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/gc_manager.go
  cdc/owner/gc_manager_test.go
  cdc/owner/owner_test.go
  cdc/owner/schema_test.go
  cdc/owner_test.go
  cdc/processor.go
  cdc/processor/pipeline/puller.go
  cdc/processor/processor.go
  cdc/puller/mock_puller.go
  cdc/puller/mock_puller_test.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  cdc/puller/sorter/merger.go
  cdc/sink/codec/interface.go
  cmd/client_changefeed.go
  cmd/client_tso.go
  cmd/cmd_test.go
  cmd/test.go
  cmd/util.go
  go.mod
  go.sum
  pkg/context/context.go
  pkg/txnutil/lock_resolver.go
  tests/resolve_lock/main.go
Labels: size/L, status/LGT2, status/can-merge

#2121 error: fix wrong error message of ErrGCTTLExceeded
  errors.toml
  pkg/errors/errors.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#2122 cli: make error message compatible with pd flag name when PD address unreachable
  cmd/client.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#2117 cli: prevent invalid filter rules from being applied, which would lead to an irrecoverable changefeed failure
  cmd/client_changefeed.go
  cmd/cmd_test.go
  cmd/util.go
  pkg/filter/filter.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, type/bugfix

#2139 cli: make error message compatible with pd flag name
  cmd/client.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#2141 makefile: make clean also cleanup the bin dir
  Makefile
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#2142 *: merge new processor related deadlock fixes to 5.0 branch
  cdc/processor/pipeline/mounter.go
  cdc/processor/pipeline/mounter_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/merger_test.go
  cdc/puller/sorter/sorter_test.go
  cdc/puller/sorter/unified_sorter.go
Labels: cherry-pick-approved, size/XXL, status/LGT2, status/can-merge, type/cherry-pick-for-release-5.0

#1848 pkg: add a new retry to support the error isRetryable or not
  errors.toml
  pkg/errors/errors.go
  pkg/retry/options.go
  pkg/retry/retry.go
  pkg/retry/retry_test.go
  pkg/retry/retry_with_opt.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, size/XL, status/LGT2, status/can-merge

#2135 kv/client: keep using kv client v1 in 5.0
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: cherry-pick-approved, component/kv-client, ptal, size/M, status/LGT2, status/can-merge, type/cherry-pick-for-release-5.0

#2161 cdc: fix server etcd may nil by create a new local client.
  cdc/server.go
  cdc/server_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge

#2163 tools: only diff the go.mod and go.sum
  tools/check/check-tidy.sh
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#2160 doc: change readme support Go version to Go >= 1.16
  README.md
Labels: needs-cherry-pick-release-5.1, ptal, size/XS, status/LGT2, status/can-merge

#2172 *: Make unconvert linter happy and locking golangci-lint version
  .golangci.yml
  Makefile
  cdc/model/changefeed.go
  cdc/model/sink.go
  cdc/owner.go
  cdc/processor/processor.go
  cdc/server.go
  cdc/sink/codec/craft/model.go
  cmd/util.go
  tools/check/go.mod
  tools/check/go.sum
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XXL, status/LGT2, status/can-merge

#2138 client,server: better err msg when PD endpoint missing certificate
  cmd/client.go
  cmd/server.go
  cmd/server_test.go
  cmd/util.go
  cmd/util_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge

#2182 config: Add log configuration items to the config file
  cmd/server.go
  cmd/server_test.go
  cmd/ticdc.toml
  pkg/config/config.go
  pkg/config/config_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/L, status/LGT2, status/can-merge

#2169 config: cherry-pick capture-session-ttl config into release-4.0
  cdc/capture.go
  cdc/capture/capture.go
  cdc/owner_test.go
  cdc/server.go
  cmd/server_test.go
  pkg/config/config.go
  pkg/config/config_test.go
Labels: cherry-pick-approved, size/M, status/LGT1, type/cherry-pick-for-release-4.0
