Repository pingcap/tiflow, pull requests merged in 2021-07, with the labels that each got.

#2200 cmd(refactoring): move applications into cmd
  Makefile
  cmd/cdc/main.go
  cmd/cdc/main_test.go
  cmd/kafka-consumer/main.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge

#2203 cdc/capture: add session disconnect log and remove verbose logs
  cdc/capture.go
  cdc/capture/capture.go
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/merger.go
  pkg/pipeline/pipeline.go
Labels: component/replica-model, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT1

#2193 cmd: fix typo and stop using deprecated API
  cmd/client.go
  cmd/client_tso.go
  cmd/root.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#2210 test: fix CI for the new owner
  cdc/model/changefeed.go
  tests/availability/owner.sh
  tests/availability/processor.sh
  tests/capture_session_done_during_task/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/changefeed_error/run.sh
  tests/changefeed_finish/run.sh
  tests/cli/run.sh
  tests/cyclic_abc/run.sh
  tests/ddl_reentrant/run.sh
  tests/gc_safepoint/run.sh
  tests/kafka_sink_error_resume/run.sh
  tests/kill_owner_with_ddl/run.sh
  tests/owner_remove_table_error/run.sh
  tests/processor_err_chan/run.sh
  tests/processor_stop_delay/run.sh
  tests/sink_hang/run.sh
  tests/syncpoint/run.sh
  tests/unified_sorter_sort_dir_conflict/run.sh
Labels: size/L

#2226 pipeline: reduce tick message in-use objects
  pkg/pipeline/message.go
Labels: component/replica-model, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, subject/performance

#2115 changefeed: Fix changefeed fails immediately after being created successfully.
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, size/S, status/LGT2, status/can-merge

#2222 cmd: Make changefeed sort dir visible
  cdc/kv/etcd_test.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/server.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, type/bugfix

#2225 config: Add log configuration items to the config file
  cmd/server.go
  cmd/server_test.go
  cmd/ticdc.toml
  pkg/config/config.go
  pkg/config/config_test.go
Labels: cherry-pick-approved, size/L, status/LGT2, status/can-merge, type/cherry-pick-for-release-4.0

#2223 etcd_worker: big txn
  errors.toml
  pkg/errors/errors.go
  pkg/orchestrator/etcd_txn.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_bank_test.go
  pkg/orchestrator/etcd_worker_big_txn_test.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/reactor_state_tester.go
  tests/processor_stop_delay_2/run.sh
Labels: size/XXL, status/wip

#2209 replication_model: split keys for task status
  cdc/model/owner.go
  cdc/model/reactor_state.go
  cdc/model/reactor_state_test.go
  pkg/etcd/etcdkey.go
  pkg/etcd/etcdkey_test.go
  tests/availability/owner.sh
  tests/capture_suicide_while_balance_table/run.sh.skip
  tests/changefeed_reconstruct/run.sh.skip
Labels: size/XL, type/dnm

#2218 filter: support for synchronizing user permission-related tables
  cdc/owner/schema_test.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  tests/capture_suicide_while_balance_table/conf/ingore_user_system_tables.toml
  tests/capture_suicide_while_balance_table/run.sh.skip
  tests/changefeed_reconstruct/run.sh.skip
Labels: size/L, status/LGT1

#2197 cdc_*: delete some code that use old owner
  cdc/http_handler.go
  cdc/http_status.go
  cdc/server.go
  cdc/task_test.go
Labels: ptal, size/XL, status/LGT2, status/can-merge

#2198 gc_manager: add a log to output gcSafePoint update record.
  cdc/owner/feed_state_manager.go
  cdc/owner/gc_manager.go
Labels: component/metrics-logging, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, ptal, size/S, status/LGT2, status/can-merge

#2189 metrics: update tikv metrics
  metrics/grafana/ticdc.json
Labels: component/metrics-logging, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XXL, status/LGT2, status/can-merge

#2205 changefeed: fix add partition in old owner
  cdc/changefeed.go
  cdc/changefeed_test.go
Labels: cherry-pick-approved, needs-cherry-pick-release-5.0, release-blocker, size/M, status/LGT2, status/can-merge, status/ptal, type/cherry-pick-for-release-4.0

#2235 kv/client: don't resolve lock immediately after a region is initialized
  cdc/kv/region_worker.go
  cdc/kv/resolvedts_heap.go
  cdc/kv/resolvedts_heap_test.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, status/ptal

#2267 owner, metrics: add changefeed status in metrics and grafana
  cdc/model/changefeed.go
  cdc/owner.go
  cdc/owner/metrics.go
  cdc/owner/owner.go
  metrics/grafana/ticdc.json
Labels: component/metrics-logging, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XL, status/LGT2, status/can-merge

#1900 new_owner: add comments for async sink
  cdc/owner/async_sink.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge, status/ptal

#2280 pkg: fix retry getBackoffInMs panic when sleep overflowed
  pkg/retry/retry_with_opt.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge

#2252 owner: fix new owner updating checkpoint too early with pending DDL
  cdc/owner/changefeed.go
  cdc/owner/schema.go
  tests/kill_owner_with_ddl/run.sh
Labels: component/ddl, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, status/ptal, type/bugfix

#2249 sink: fix concurrent map access in sink manager
  cdc/sink/manager.go
  cdc/sink/manager_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge, status/ptal, type/bugfix

#2271 puller,mounter,processor: always pull the old value internally
  cdc/entry/codec.go
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/model/schema_storage.go
  cdc/processor.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  pkg/regionspan/span.go
  pkg/regionspan/span_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XXL, status/LGT2, status/can-merge, status/ptal, subject/usability

#2308 filter: refine comments and function visibility
  pkg/filter/filter.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/S, status/LGT1, status/can-merge

#2177 owner/processor: delete metric when changefeed or processor stops
  cdc/owner.go
  cdc/processor.go
Labels: cherry-pick-approved, needs-cherry-pick-release-4.0, require-LGT1, size/XS, status/LGT1, status/can-merge, status/ptal, type/cherry-pick-for-release-5.0

#1928 sink: fix issue, Fail-fast for unrecoverable DML errors
  cdc/entry/schema_storage.go
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/etcd.go
  cdc/owner/async_sink_test.go
  cdc/owner/ddl_puller_test.go
  cdc/processor.go
  cdc/processor/pipeline/mounter_test.go
  cdc/processor/processor.go
  cdc/puller/puller_test.go
  cdc/puller/sorter/sorter_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  integration/framework/docker_compose_op.go
  integration/framework/docker_env.go
  pkg/errors/helper.go
  pkg/errors/helper_test.go
  pkg/etcd/client.go
  pkg/etcd/client_test.go
  pkg/retry/retry.go
  pkg/workerpool/async_pool_impl.go
  tests/bank/case.go
  tests/move_table/main.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XXL, status/LGT2, status/can-merge, status/ptal

#2272 kv: add grpc client metrics
  cdc/kv/client.go
  cdc/kv/metrics.go
  go.mod
  metrics/grafana/ticdc.json
Labels: component/kv-client, component/metrics-logging, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, status/ptal

#2309 puller: clean up unused parameter
  cdc/owner/ddl_puller.go
  cdc/owner_operator.go
  cdc/processor.go
  cdc/processor/pipeline/puller.go
  cdc/processor/processor.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge

#2114 sorter: remove file sorter
  cdc/owner.go
  cdc/processor.go
  cdc/processor/pipeline/sorter.go
  cdc/puller/file_sorter.go
  cmd/client_changefeed.go
  errors.toml
  go.mod
  go.sum
  pkg/errors/errors.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XXL, status/LGT2, status/can-merge, status/ptal

#2281 processor, pipeline: reduce channel buffer
  cdc/processor/pipeline/mounter_test.go
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/runner.go
Labels: component/replica-model, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, subject/performance

#2321 flow_control_test: fix some test case fail
  cdc/processor/pipeline/sorter.go
  cdc/sink/common/flow_control_test.go
Labels: component/test, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XS, status/LGT2, status/can-merge, status/ptal

#2341 refactor(cli): add client construction factory abstraction
  pkg/cmd/context/context.go
  pkg/cmd/factory/factory.go
  pkg/cmd/factory/factory_impl.go
  pkg/cmd/util/helper.go
  pkg/cmd/util/helper_test.go
Labels: size/XL, status/LGT2, status/can-merge

#2354 scripts: clean up unused pipeline files
  scripts/jenkins_ci/cdc_ghpr_build.groovy
  scripts/jenkins_ci/cdc_ghpr_check.groovy
  scripts/jenkins_ci/cdc_ghpr_integration_test.groovy
  scripts/jenkins_ci/cdc_ghpr_kafka_integration_test.groovy
  scripts/jenkins_ci/cdc_ghpr_leak_test.groovy
  scripts/jenkins_ci/cdc_ghpr_test.groovy
  scripts/jenkins_ci/integration_test_common.groovy
Labels: require-LGT1, size/XL, status/LGT1, status/can-merge

#2253 *: add some logs to help debug error.
  cdc/model/owner.go
  cdc/owner/feed_state_manager.go
  cdc/owner/scheduler.go
  errors.toml
  pkg/errors/errors.go
  pkg/orchestrator/etcd_worker.go
Labels: component/metrics-logging, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge, status/ptal

#2339 scripts: check merge conflicts
  Makefile
  scripts/check-merge-conflicts.sh
Labels: component/test, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/S, status/LGT1, status/can-merge

#1858 action: Integrate chaos mesh into ticdc
  .github/workflows/chaos.yaml
  Makefile
  chaos/Dockerfile.chaos
  chaos/checker.sh
  chaos/manifests/downstream.yaml
  chaos/manifests/io-chaos-cdc.yaml
  chaos/manifests/network-emulation-cdc.yaml
  chaos/manifests/network-partition-cdc.yaml
  chaos/manifests/pod-failure-cdc.yaml
  chaos/manifests/pod-kill-cdc.yaml
  chaos/manifests/ticdc.yaml
  chaos/manifests/upstream.yaml
  chaos/manifests/workload.yaml
  chaos/sorter-config.toml
  tests/bank/case.go
Labels: size/XXL, status/LGT2, status/can-merge

#2334 cmd: add more logs to debug cdc data-dir set up.
  cdc/server.go
  cmd/server.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/S, status/LGT2, status/can-merge

#2342 utils: make CheckSafetyOfStartTs retry.
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/owner.go
  cdc/owner/gc_manager.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  pkg/util/gc_service.go
  pkg/util/gc_service_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/M, status/LGT2, status/can-merge

#2285 kv/client: exit region worker if there is no region maintained
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
Labels: component/kv-client, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, size/XL, status/LGT2, status/can-merge, status/ptal

#2365 cli(refactor): add version cmd
  pkg/cmd/cmd.go
  pkg/cmd/version/version.go
Labels: size/M, status/LGT2, status/can-merge

#2368 *: enable unparam static check
  .golangci.yml
  cdc/changefeed.go
  cdc/kv/client.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/processor/processor.go
  cdc/puller/sorter/sorter_test.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/codec/schema_registry_test.go
  cdc/sink/mysql.go
  cdc/sink/producer/pulsar/option.go
  cdc/task.go
  cdc/task_test.go
  cmd/cdc/main_test.go
  cmd/client_changefeed.go
  cmd/util.go
  pkg/httputil/httputil_test.go
  pkg/orchestrator/etcd_worker.go
  pkg/regionspan/region_range_lock_test.go
  testing_utils/many_sorters_test/many_sorters_test.go
  tests/bank/case.go
  tests/dailytest/db.go
  tests/dailytest/job.go
  tests/dailytest/parser.go
Labels: require-LGT1, size/L, status/LGT1, status/can-merge

#2392 github: update pull request template to use new release note fmt
  .github/pull_request_template.md
Labels: require-LGT1, size/S, status/LGT1, status/can-merge

#2328 puller: remove memory buffer and buffer limitter
  cdc/processor.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  cdc/puller/buffer.go
  cdc/puller/buffer_test.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/XL, status/LGT1, status/can-merge, status/ptal

#2367 sink(refactor): Refine functions and improve event splitting code
  cdc/processor/pipeline/sink.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, require-LGT1, size/L, status/LGT1, status/can-merge

#2402 github: cleanup duplicate lint job
  .github/workflows/check_and_build.yml
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, release-note-none, require-LGT1, size/S, status/LGT1, status/can-merge

#2384 cli: Fix cli using memory sorter when working on 4.0.x cluster
  cmd/client_changefeed.go
  pkg/version/check.go
  pkg/version/check_test.go
Labels: component/cli, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, release-note, size/L, status/LGT2, status/can-merge, type/bugfix

#2410 github: enable concurrency mode
  .github/workflows/check_and_build.yml
  .github/workflows/integration.yml
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, release-note-none, size/S, status/LGT2, status/can-merge

#2406 pipeline: skip stack backtrace in hot path
  pkg/pipeline/pipeline.go
Labels: needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, needs-cherry-pick-release-5.1, release-note-none, size/XS, status/LGT2, status/can-merge, subject/performance
