Repository pingcap/tiflow, pull requests merged in 2021-02, with the labels that each got.

#1385 go mod: add indirect version of shirou/gopsutil to fix freebsd build
  go.mod
  go.sum
Labels: PTAL, status/LGT1, status/can-merge

#1389 ci: build on both ubuntu and macOS
  .github/workflows/check_and_build.yml
Labels: PTAL, S: TEST, needs-cherry-pick-4.0, status/LGT3, status/can-merge

#1395 sink: increase statistics interval
  cdc/sink/statistics.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1176 processor: a new processor using pipeline, refactor processor part two
  cdc/processor/pipeline/mounter.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  errors.toml
  pkg/context/context.go
  pkg/errors/errors.go
  pkg/pipeline/context.go
  pkg/pipeline/message.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/test.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1402 fix the memory leak in sink manager (#1401)
  cdc/sink/manager.go
Labels: PTAL, bug-fix, release-blocker, status/LGT2, status/can-merge, type/4.0-cherry-pick

#1396 owner: cleanup checkpoint lag metric when owner exits
  cdc/owner.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1401 sink: fix the memory leak in sink manager
  cdc/sink/manager.go
Labels: PTAL, bug-fix, status/LGT2, status/can-merge

#1408 test: add a script for checking data race
  tests/_utils/check_logs
  tests/autorandom/run.sh
  tests/availability/run.sh
  tests/batch_add_table/run.sh
  tests/capture_session_done_during_task/run.sh
  tests/cdc/run.sh
  tests/cdclog_file/run.sh
  tests/cdclog_s3/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/changefeed_error/run.sh
  tests/changefeed_finish/run.sh
  tests/changefeed_pause_resume/run.sh
  tests/changefeed_reconstruct/run.sh
  tests/cli/run.sh
  tests/clustered_index/run.sh
  tests/common_1/run.sh
  tests/cyclic_ab/run.sh
  tests/cyclic_abc/run.sh
  tests/ddl_puller_lag/run.sh
  tests/ddl_reentrant/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/force_replicate_table/run.sh
  tests/gc_safepoint/run.sh
  tests/generate_column/run.sh
  tests/kafka_messages/run.sh
  tests/kafka_sink_error_resume/run.sh
  tests/kill_owner_with_ddl/run.sh
  tests/many_pk_or_uk/run.sh
  tests/move_table/run.sh
  tests/multi_capture/run.sh
  tests/multi_source/run.sh
  tests/new_ci_collation/run.sh
  tests/partition_table/run.sh
  tests/processor_panic/run.sh
  tests/processor_resolved_ts_fallback/run.sh
  tests/processor_stop_delay/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/simple/run.sh
  tests/sink_hang/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/syncpoint/run.sh
  tests/tiflash/run.sh
  tests/unified_sorter/run.sh
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1407 codec: fix Avro schema cache data race
  cdc/sink/codec/schema_registry.go
  cdc/sink/codec/schema_registry_test.go
Labels: C: Sink, Priority/P0, bug-fix, bug-from-user, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1412 sink/mysql: fix confused error log when creating new changefeed
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1354 processor: a processor state based etcd worker, refactor processor part three
  cdc/processor/state.go
  cdc/processor/state_test.go
  pkg/etcd/etcdkey.go
  pkg/etcd/etcdkey_test.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1421 pipeline: refine pipeline, refactor processor part one (#1172)
  pkg/context/context.go
  pkg/context/context_test.go
  pkg/pipeline/context.go
  pkg/pipeline/message.go
  pkg/pipeline/node.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/runner.go
Labels: PTAL, status/LGT1, status/can-merge, type/4.0-cherry-pick

#1388 make: add build-failpoint command and fix failpoint build
  Makefile
  scripts/fix_lib_zstd.sh
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1416 table_pipeline: add cyclic mark node and fix some bugs
  cdc/entry/mounter.go
  cdc/model/mounter.go
  cdc/model/sink.go
  cdc/processor/pipeline/cyclic_mark.go
  cdc/processor/pipeline/cyclic_mark_test.go
  cdc/processor/pipeline/metrics.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1427 Fix error type in Pulsar sink
  cdc/sink/producer/pulsar/producer.go
Labels: PTAL, first-time-contributor, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1429 kv-client: filter key overflow region before sending to puller
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
Labels: C: KV-client, PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1387 etcd worker: some features and bugfix for etcd worker
  errors.toml
  pkg/errors/errors.go
  pkg/etcd/client.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/jsonstate/json_reactor_state_test.go
  testing_utils/cdc_state_checker/cdc_monitor.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1418 kv-client: don't maintain need reload info for region
  cdc/kv/client.go
Labels: C: KV-client, PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1440 pipeline: fix panic message could be ignore when pipeline is exiting
  cdc/sink/common/common.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  scripts/jenkins_ci/integration_test_common.groovy
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1445 github-action: use specific go version
  .github/workflows/check_and_build.yml
  .github/workflows/integration.yml
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1447 sink: fix float support in Avro
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  integration/tests/case_many_types.go
Labels: bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1420 processor: a new processor based etcd worker, refactor processor part four
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/processor.go
  cdc/processor/doc.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/metrics.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  pkg/context/context.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1426 kv-client: add resolved ts heap for quick resolve lock
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
  cdc/kv/resolvedts_heap.go
  cdc/kv/resolvedts_heap_test.go
  pkg/regionspan/span.go
  pkg/regionspan/span_test.go
Labels: C: KV-client, PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1187 processor: switch on the new processor, refactor processor part five
  Makefile
  cdc/capture.go
  cdc/capture_test.go
  cdc/http_status.go
  cdc/metrics.go
  cdc/owner.go
  cdc/processor.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  cdc/processor_test.go
  cdc/server.go
  cdc/sink/mysql.go
  cdc/task_test.go
  pkg/config/config.go
  pkg/orchestrator/etcd_worker.go
  tests/capture_session_done_during_task/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/cli/run.sh
  tests/cyclic_ab/run.sh
  tests/cyclic_abc/run.sh
  tests/ddl_puller_lag/run.sh
  tests/processor_panic/run.sh
  tests/processor_stop_delay/run.sh
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge
