Repository pingcap/tiflow, pull requests merged in 2021-04, with the labels that each got.

#1589 kv/client: support reconnect regions when no event received too long
  cdc/kv/client.go
  cdc/kv/client_test.go
  scripts/jenkins_ci/integration_test_common.groovy
  tests/kv_client_stream_reconnect/conf/diff_config.toml
  tests/kv_client_stream_reconnect/run.sh
Labels: C: KV-client, PTAL, release-blocker, size/L, status/LGT2

#1597 cmd: fix pd parameter in update config
  cmd/client_changefeed.go
  tests/cli/run.sh
Labels: PTAL, bug-fix, release-blocker, size/XS, status/LGT1, type/4.0-cherry-pick

#1574 sorter: avoid blocking in thread pool
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/merger_test.go
  cdc/puller/sorter/unified_sorter.go
  tests/http_proxies/run.sh.skip
Labels: PTAL, needs-cherry-pick-5.0, release-blocker, size/XL, status/LGT2, status/can-merge

#1596 cmd: fix pd parameter in update config
  cmd/client_changefeed.go
  tests/cli/run.sh
Labels: PTAL, needs-cherry-pick-5.0, release-blocker, size/XS, status/LGT2, status/can-merge

#1607 metrics: update TiKV metrics #1604
  metrics/grafana/ticdc.json
Labels: PTAL, release-blocker, size/L, status/LGT1, type/5.0-cherry-pick

#1604 metrics: update TiKV metrics
  metrics/grafana/ticdc.json
Labels: PTAL, needs-cherry-pick-4.0, release-blocker, size/L, status/LGT2, status/can-merge

#1506 Fix local file sink flush
  cdc/sink/cdclog/file.go
Labels: Component/PiTR, PTAL, first-time-contributor, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XS, status/LGT2, status/can-merge

#1423 Restore cdc log failed due to excess version part in ddl file when using s3 sink
  cdc/sink/cdclog/s3.go
Labels: Component/PiTR, PTAL, first-time-contributor, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/S, status/LGT2, status/can-merge, type/bugfix

#1469 s3: increase defaultBufferChanSize
  cdc/sink/cdclog/s3.go
Labels: Component/PiTR, PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XS, status/LGT2, status/can-merge

#1611 kv/client: remove redundant log
  cdc/kv/client.go
Labels: PTAL, size/XS, status/LGT2, status/can-merge, type/5.0-cherry-pick

#1616 pkg/version.go: mod CheckClusterVersion: fix StatusCode check issue
  pkg/version/check.go
  pkg/version/check_test.go
Labels: contribution, first-time-contributor, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/M, status/LGT2, status/can-merge

#1528 delete needless words
  docs/design/2020-03-04-ticdc-design-and-architecture-cn.md
Labels: first-time-contributor, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XS, status/LGT2, status/can-merge

#1640 metrics: correct TiKV CDC endpoint CPU
  metrics/grafana/ticdc.json
Labels: component/metrics, needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/XS, status/LGT2, status/can-merge, type/bugfix

#1641 kv/client: fix the error handling for io.EOF may miss region reconnect
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
Labels: component/kv-client, needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/L, status/LGT2, status/can-merge, type/bugfix

#1603 sink: Decrease the default value of `MaxBatchSize` to avoid `Kafka Msg too large`
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
Labels: component/sink, needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/XS, status/LGT2, status/can-merge

#1618 metrics: add old value metrics
  metrics/grafana/ticdc.json
Labels: component/metrics, needs-cherry-pick-5.0, ptal, size/XL, status/LGT2, status/can-merge

#1609 pipeline: fix unstable unit test
  pkg/pipeline/pipeline_test.go
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/M, status/LGT2, status/can-merge, subject/test

#1646 kvclient: port no pending region fix to master branch
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
Labels: component/kv-client, ptal, size/L, status/LGT2, status/can-merge, type/bugfix

#1638 sink/mysql: explicit_defaults_for_timestamp compatibility with mysql
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/L, status/LGT2, status/can-merge, type/bugfix

#1656 fix panic issue in update changefeed config.
  cmd/client_changefeed.go
Labels: contribution, needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/XS, status/LGT2, status/can-merge

#1660 github/action: insert/update SQL could meet duplicated entry error
  cdc/sink/simple_mysql_tester.go
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/XS, status/LGT2, status/can-merge, subject/test

#1553 kvclientv2: fix resolvedts go back
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  pkg/util/failpoint.go
  pkg/version/version.go
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/L, status/LGT2, status/can-merge

#1591 kv/client: support reconnect regions when no event received too long
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
  scripts/jenkins_ci/integration_test_common.groovy
  tests/kv_client_stream_reconnect/conf/diff_config.toml
  tests/kv_client_stream_reconnect/run.sh
Labels: component/kv-client, needs-cherry-pick-4.0, ptal, size/XL, status/LGT2, status/can-merge

#1593 cdc: fix text type decode for old row format
  cdc/entry/codec.go
Labels: needs-cherry-pick-5.0, ptal, size/XS, status/LGT2, status/can-merge

#1477 s3Sink: cancel create existing table directory on s3 when initialize s3Sink
  cdc/owner.go
  cdc/sink/cdclog/s3.go
  tests/cdclog_s3/run.sh
Labels: component/pitr, needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/S, status/LGT2, status/can-merge

#1619 sorter: fix Unified Sorter error handling & add more unit test cases
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/sorter_test.go
  cdc/puller/sorter/unified_sorter.go
  errors.toml
  pkg/errors/errors.go
Labels: component/puller, needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/L, status/LGT2, status/can-merge, type/bugfix

#1674 kv/client: fix unstable unit test, where request id is not accurate
  cdc/kv/client_test.go
Labels: needs-cherry-pick-4.0, ptal, size/M, status/LGT2, status/can-merge, subject/test

#1686 tests: fix mock server sends event before kv client is ready
  cdc/kv/client_test.go
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/S, status/LGT2, status/can-merge, subject/test

#1689 Makefile: fix incorrect version number on macOS
  Makefile
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/S, status/LGT2, status/can-merge

#1688 Action: make github action run in parallel
  .github/workflows/integration.yml
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/XS, status/LGT2, status/can-merge

#1697 cmd: fix wrong usage in cdc server cli flag, --cert-allowed-cn
  cmd/util.go
Labels: first-time-contributor, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/XS, status/LGT2, status/can-merge

#1468 context: refine error handler
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  pkg/context/context.go
  pkg/context/context_test.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/L, status/LGT2, status/can-merge

#1615 sink: fix avro timezone
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/mq.go
  docker-compose-avro.yml
  integration/integration.go
  integration/tests/case_date_time.go
Labels: bug-from-user, component/sink, needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/L, status/LGT2, status/can-merge

#1592 tests: give http_proxies enough time to bootstrap and use randomized port
  tests/http_proxies/run.sh
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, ptal, size/S, status/LGT2, status/can-merge

#1682 kv/client: fix force reconnect in client v2
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
  cdc/kv/resolvedts_heap.go
  cdc/kv/resolvedts_heap_test.go
Labels: component/kv-client, needs-cherry-pick-4.0, ptal, size/XXL, status/LGT2, status/can-merge
