Repository pingcap/tiflow, pull requests merged in 2021-03, with the labels that each got.

#1462 processor: switch on the new processor, refactor processor part five (#1187)
  Makefile
  cdc/capture.go
  cdc/capture_test.go
  cdc/http_status.go
  cdc/metrics.go
  cdc/owner.go
  cdc/processor.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  cdc/processor_test.go
  cdc/server.go
  cdc/sink/mysql.go
  cdc/task_test.go
  pkg/config/config.go
  pkg/orchestrator/etcd_worker.go
  tests/capture_session_done_during_task/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/cli/run.sh
  tests/cyclic_ab/run.sh
  tests/cyclic_abc/run.sh
  tests/ddl_puller_lag/run.sh
  tests/processor_panic/run.sh
  tests/processor_stop_delay/run.sh
Labels: C: Replica-model, PTAL, needs-cherry-pick-4.0, status/LGT1, status/can-merge

#1437 owner: refactor part I
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner/changefeed_state.go
  cdc/owner/changefeed_state_test.go
  cdc/owner/owner_state.go
  cdc/owner/owner_state_test.go
  cdc/owner/scheduler.go
  cdc/owner/scheduler_test.go
  errors.toml
  pkg/errors/errors.go
  pkg/orchestrator/reactor_state_tester.go
Labels: C: Scheduler, PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1442 sink: Pass extra meta about the event to MQ producer
  cdc/model/sink.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/interface_test.go
  cdc/sink/codec/json.go
  cdc/sink/codec/maxwell.go
  cdc/sink/mq.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  cdc/sink/producer/mq_producer.go
  cdc/sink/producer/pulsar/option.go
  cdc/sink/producer/pulsar/producer.go
Labels: C: Sink, PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1461 new processor: make sure that resolvedTs will be updated when handling an add table operation
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/puller/sorter/merger.go
Labels: C: Replica-model, PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1464 sink manager: fix a resolved ts event disorder problems caused by concurrency
  cdc/sink/manager.go
  cdc/sink/manager_test.go
Labels: C: Sink, PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1467 processor: fix nil pointer panic
  cdc/processor/processor.go
  cdc/processor/processor_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1439 kv-client: use multiple sync.Map to reduce lock contention
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
Labels: C: KV-client, PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1448 kv-client: add benchmark for kv client
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_mock_test.go
  cdc/kv/client_test.go
Labels: C: KV-client, PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1473 kv-client: fix reentrant onRegionFail causes duplicated range unlock
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/client_v2.go
  cdc/kv/region_worker.go
Labels: C: KV-client, PTAL, bug-fix, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1489 cdclog: fix lint warning
  cdc/sink/cdclog/utils.go
Labels: PTAL, needs-cherry-pick-4.0, status/LGT2, status/can-merge

#1341 cli: change default value according to the ticdc cluster version
  Makefile
  cdc/capture.go
  cdc/model/capture.go
  cdc/model/capture_test.go
  cdc/model/changefeed.go
  cdc/processor.go
  cdc/processor/pipeline/sorter.go
  cmd/client_changefeed.go
  cmd/client_changefeed_test.go
  pkg/version/check.go
  pkg/version/check_test.go
  tests/processor_err_chan/run.sh
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#1497 cmd: check changefeed start-ts when creating or resuming
  cmd/client_changefeed.go
  cmd/cmd_test.go
  cmd/util.go
Labels: PTAL, needs-cherry-pick-4.0, release-blocker, status/LGT2, status/can-merge

#1490 *: update tidb and br dependency
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/entry/schema_storage_test.go
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/kv/store_op.go
  cdc/kv/testing.go
  cdc/sink/cdclog/s3.go
  cmd/test.go
  go.mod
  go.sum
  tests/resolve_lock/main.go
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#1513 schema storage: get the schema snap of `commit ts -1` to support async commit
  cdc/entry/mounter.go
  tests/autorandom/data/test.sql
  tests/multi_source/main.go
Labels: release-blocker, status/LGT2, status/can-merge

#1503 *: update tidb to int pk not handle
  cdc/kv/client_test.go
  cdc/kv/store_op.go
  go.mod
  go.sum
Labels: release-blocker, status/LGT2, status/can-merge

#1493 *: add config file for server
  cdc/http_status.go
  cdc/http_status_test.go
  cdc/owner_test.go
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/backend_pool_test.go
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/unified_sorter.go
  cdc/puller/sorter_test.go
  cdc/server.go
  cdc/server_test.go
  cmd/client.go
  cmd/client_changefeed.go
  cmd/cmd_test.go
  cmd/server.go
  cmd/server_test.go
  cmd/ticdc.toml
  cmd/util.go
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/sorter.go
  testing_utils/many_sorters_test/many_sorters.go
  testing_utils/sorter_stress_test/sorter_stress.go
  tests/_utils/run_cdc_server
  tests/cyclic_abc/run.sh
Labels: PTAL, release-blocker, status/LGT2, status/can-merge

#1500 mounter: fix a compatibility issue after tidb#23092
  cdc/entry/mounter.go
Labels: PTAL, release-blocker, status/LGT1, status/can-merge

#1508 owner: fix data loss when capture restarts with table scheduler
  cdc/changefeed.go
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/processor/processor_test.go
  tests/capture_suicide_while_balance_table/conf/diff_config.toml
  tests/capture_suicide_while_balance_table/run.sh
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, release-blocker, status/LGT2, status/can-merge

#1525 tests: use global tidb_enable_clustered_index variable
  tests/clustered_index/data/test.sql
  tests/clustered_index/run.sh
Labels: PTAL, S: TEST, release-blocker, status/LGT2, status/can-merge

#1526 *: update tidb depend
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge

#1516 *: disable kvclient v2 and new processor
  cdc/kv/client.go
  pkg/config/config.go
  tests/capture_session_done_during_task/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/ddl_puller_lag/run.sh
  tests/processor_err_chan/run.sh
  tests/processor_panic/run.sh
  tests/processor_stop_delay/run.sh
Labels: release-blocker, status/LGT2, status/can-merge

#1479 sorter: add more unit tests & fix minor bugs
  cdc/processor.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/puller/sorter/backend_pool.go
  cdc/puller/sorter/backend_pool_test.go
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/memory_backend.go
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/merger_test.go
  cdc/puller/sorter/sorter_test.go
  cdc/puller/sorter/unified_sorter.go
  go.sum
  testing_utils/many_sorters_test/many_sorters.go
  testing_utils/sorter_stress_test/sorter_stress.go
Labels: C: Puller, PTAL, bug-fix, needs-cherry-pick-5.0, release-blocker, status/LGT2, status/can-merge

#1531 kv/client: fix panic caused by reentrant unlock pending region
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT2, status/can-merge

#1530 kv/client: fix lock range may block when context is cancelled
  cdc/kv/client.go
  pkg/regionspan/region_range_lock.go
  pkg/regionspan/region_range_lock_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0, status/LGT2, status/can-merge

#1547 processor: fix a concurrency issues and goroutine leak when processor stopped
  cdc/processor.go
  tests/changefeed_auto_stop/run.sh
  tests/processor_stop_delay_2/conf/diff_config.toml
  tests/processor_stop_delay_2/run.sh
Labels: needs-cherry-pick-5.0, release-blocker, size/L, status/LGT2, status/can-merge

#1527 sorter: adjust unified sorter config
  cdc/owner.go
  cdc/processor.go
  cdc/processor/pipeline/sorter.go
  cdc/puller/sorter/sorter_test.go
  cdc/puller/sorter/unified_sorter.go
  cmd/client_changefeed.go
  cmd/server.go
  cmd/server_test.go
  errors.toml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/sorter.go
  pkg/errors/errors.go
Labels: PTAL, needs-cherry-pick-5.0, release-blocker, size/L, status/LGT2, status/can-merge

#1524 sink/mysql: fix txn wg counter is not updated correctly
  cdc/model/sink.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: C: Sink, PTAL, Priority/P0, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0, release-blocker, size/L, status/LGT2, status/can-merge

#1540 owner: fix multiple owner co-exist when pd has jitter
  cdc/capture.go
  cdc/capture_test.go
  cdc/changefeed.go
  cdc/kv/etcd.go
  cdc/kv/etcd_test.go
  cdc/owner.go
  cdc/owner_test.go
  cdc/server.go
  cmd/server_test.go
  errors.toml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/errors/errors.go
Labels: PTAL, bug-fix, needs-cherry-pick-5.0, release-blocker, size/XL, status/LGT2, status/can-merge

#1554 cmd: make update config conservative, only update listed parameter
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cmd/client_changefeed.go
  tests/cli/run.sh
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0, release-blocker, size/L, status/LGT2

#1564 metrics: add owner in memory table count metrics
  cdc/metrics_owner.go
  cdc/owner.go
  metrics/grafana/ticdc.json
Labels: PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0, release-blocker, size/L, status/LGT1

#1571 metrics/grafana: add more panels for old value
  metrics/grafana/ticdc.json
Labels: size/L, status/LGT2, status/can-merge

#1558 sorter: fix Unified Sorter resource release
  cdc/puller/sorter/heap_sorter.go
  cdc/puller/sorter/merger.go
  cdc/puller/sorter/merger_test.go
  cdc/puller/sorter/sorter_test.go
  cdc/puller/sorter/unified_sorter.go
  errors.toml
  pkg/errors/errors.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, needs-cherry-pick-5.0, release-blocker, size/XL, status/LGT2, status/can-merge

#1569 kv/client: fix ErrNoPendingRegion because of shared map operation
  cdc/kv/client.go
  cdc/kv/client_test.go
Labels: PTAL, bug-fix, needs-cherry-pick-4.0, release-blocker, size/L, status/LGT2, status/can-merge

#1492 cmd: add log to http proxy environment variables
  cmd/client.go
  cmd/server.go
  cmd/util.go
  cmd/util_test.go
  go.mod
  go.sum
  tests/http_proxies/run-proxy.go
  tests/http_proxies/run.sh
  tools/check/go.mod
  tools/check/go.sum
Labels: PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0, size/L, status/LGT2, status/can-merge

#1582 processor: flow control for controlling sorter output speed
  cdc/kv/client.go
  cdc/processor.go
  cdc/puller/puller.go
  cdc/puller/sorter/unified_sorter.go
Labels: PTAL, needs-cherry-pick-4.0, needs-cherry-pick-5.0, release-blocker, size/L, status/LGT2, status/can-merge

#1584 docs: update metrics dashboard and docs
  docs/media/dashboard/changefeed-1.png
  docs/media/dashboard/changefeed-2.png
  docs/media/dashboard/changefeed-3.png
  docs/media/dashboard/changefeed-4.png
  docs/media/dashboard/events-1.png
  docs/media/dashboard/events-2.png
  docs/media/dashboard/events-3.png
  docs/media/dashboard/events-4.png
  docs/media/dashboard/overview.png
  docs/media/dashboard/server.png
  docs/media/dashboard/tikv-1.png
  docs/media/dashboard/tikv-2.png
  docs/media/dashboard/unified-sorter-1.png
  docs/media/dashboard/unified-sorter-2.png
  docs/media/ticdc-dashboard-changefeed-1.png
  docs/media/ticdc-dashboard-changefeed-2.png
  docs/media/ticdc-dashboard-changefeed-3.png
  docs/media/ticdc-dashboard-events-1.png
  docs/media/ticdc-dashboard-events-2.png
  docs/media/ticdc-dashboard-events-3.png
  docs/media/ticdc-dashboard-overview.png
  docs/media/ticdc-dashboard-server.png
  docs/media/ticdc-dashboard-tikv-1.png
  docs/media/ticdc-dashboard-tikv-2.png
  docs/ticdc-grafana-dashboard.md
  metrics/grafana/ticdc.json
Labels: needs-cherry-pick-4.0, needs-cherry-pick-5.0, release-blocker, size/XL, status/LGT2, status/can-merge
