Repository pingcap/tiflow, pull requests merged in 2021-11, with the labels that each got.

#3167 dm: support generate multiple-rows dmls in syncer.
  Makefile
  dm/chaos/cases/conf/task-optimistic.yaml
  dm/chaos/cases/conf/task-pessimistic.yaml
  dm/chaos/cases/conf/task-single.yaml
  dm/dm/config/task.go
  dm/syncer/dml.go
  dm/syncer/dml_test.go
  dm/syncer/dml_worker.go
  dm/tests/dmctl_basic/conf/dm-task.yaml
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
  dm/tests/shardddl1/conf/single-source-no-sharding.yaml
  dm/tests/shardddl1/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note, component/dm

#3105 tests: add `max-message-bytes` to kafka integration tests
  tests/autorandom/run.sh
  tests/batch_add_table/run.sh
  tests/capture_session_done_during_task/run.sh
  tests/cdc/run.sh
  tests/changefeed_auto_stop/run.sh
  tests/changefeed_error/run.sh
  tests/changefeed_finish/run.sh
  tests/changefeed_pause_resume/run.sh
  tests/changefeed_reconstruct/run.sh
  tests/cli/run.sh
  tests/clustered_index/run.sh
  tests/common_1/run.sh
  tests/dailytest/case.go
  tests/ddl_puller_lag/run.sh
  tests/ddl_sequence/run.sh
  tests/drop_many_tables/run.sh
  tests/force_replicate_table/run.sh
  tests/gc_safepoint/run.sh
  tests/generate_column/run.sh
  tests/kafka_messages/run.sh
  tests/kafka_sink_error_resume/run.sh
  tests/kv_client_stream_reconnect/run.sh
  tests/many_pk_or_uk/run.sh
  tests/move_table/run.sh
  tests/multi_capture/run.sh
  tests/multi_source/run.sh
  tests/new_ci_collation_with_old_value/run.sh
  tests/new_ci_collation_without_old_value/run.sh
  tests/partition_table/run.sh
  tests/processor_err_chan/run.sh
  tests/processor_panic/run.sh
  tests/processor_resolved_ts_fallback/run.sh
  tests/processor_stop_delay/run.sh
  tests/region_merge/run.sh
  tests/resolve_lock/run.sh
  tests/row_format/run.sh
  tests/simple/run.sh
  tests/sink_hang/run.sh
  tests/sink_retry/run.sh
  tests/split_region/run.sh
  tests/tiflash/run.sh
  tests/unified_sorter/run.sh
Labels: status/LGT2, size/L, release-note-none

#3214 ticdc/redolog: refine configuration in redo log
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  pkg/applier/redo.go
  pkg/applier/redo_test.go
  pkg/cmd/redo/apply.go
  pkg/cmd/redo/meta.go
  pkg/cmd/redo/redo.go
  pkg/cmd/util/changefeed.toml
  pkg/config/config.go
  pkg/config/config_test.go
  pkg/config/consistent.go
  tests/consistent_replicate_local/conf/changefeed.toml
  tests/consistent_replicate_local/run.sh
  tests/consistent_replicate_s3/conf/changefeed.toml
  tests/consistent_replicate_s3/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, component/redolog

#3218 bug-fix: fix duplicate key for insert with compactor is enabled
  Makefile
  dm/docs/RFCS/20211008_dml_execution_optimization.md
  dm/syncer/compactor.go
  dm/syncer/compactor_test.go
  dm/tests/shardddl1/run.sh
Labels: status/ptal, type/bugfix, status/LGT2, status/can-merge, size/S, release-note-none, component/dm

#3050 sink: refactor the initialization of encoder
  cdc/sink/codec/avro.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/craft.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/codec/maxwell.go
  cdc/sink/mq.go
  cdc/sink/mq_test.go
Labels: status/ptal, component/sink, status/LGT2, status/can-merge, size/XL, release-note-none, type/enhancement

#3164 dm/relay: fix intermediate meta info written to meta file
  dm/pkg/streamer/file.go
  dm/relay/relay.go
  dm/relay/relay_test.go
Labels: status/LGT2, status/can-merge, size/M, contribution, release-note, component/dm

#3221 github: speed up the arm build
  .github/workflows/check_and_build.yaml
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#3156 p2p: implement pkg/p2p (Part I)
  errors.toml
  go.mod
  go.sum
  pkg/errors/errors.go
  pkg/p2p/main_test.go
  pkg/p2p/model.go
  pkg/p2p/serializer.go
  pkg/p2p/serializer_test.go
  pkg/p2p/server_wrapper.go
  pkg/p2p/server_wrapper_test.go
  proto/CDCPeerToPeer.proto
  proto/generate-proto.sh
  proto/p2p/CDCPeerToPeer.pb.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none

#3223 model: cleanup hi-rustin's todos
  cdc/model/schema_storage.go
  cdc/processor/pipeline/puller.go
Labels: status/LGT1, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, require-LGT1, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2

#3204 deployments(ticdc): move all docker related files into deployments
  .github/workflows/check_and_build.yaml
  .github/workflows/ticdc_integration.yaml
  .github/workflows/ticdc_integration_cron.yaml
  .gitignore
  README.md
  deployments/ticdc/docker-compose/configs/canal-test-config.toml
  deployments/ticdc/docker-compose/configs/enable-oldvalue-config.toml
  deployments/ticdc/docker-compose/configs/jdbc-sink-connector.json
  deployments/ticdc/docker-compose/configs/pd.toml
  deployments/ticdc/docker-compose/configs/tidb.toml
  deployments/ticdc/docker-compose/configs/tikv.toml
  deployments/ticdc/docker-compose/docker-compose-avro.yml
  deployments/ticdc/docker-compose/docker-compose-canal.yml
  deployments/ticdc/docker-compose/docker-compose-mysql.yml
  deployments/ticdc/docker/.dockerignore
  deployments/ticdc/docker/Dockerfile
  deployments/ticdc/docker/dev.Dockerfile
  integration/framework/avro/kafka_docker_env.go
  integration/framework/canal/kafka_docker_env.go
  integration/framework/canal/kafka_docker_env_test.go
  integration/framework/canal/kafka_single_table.go
  integration/framework/docker_compose_op.go
  integration/framework/mysql/docker_env.go
  integration/framework/mysql/single_table.go
  scripts/avro-local-test.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#3217 scheduler_v2: implement a data structure for storing table status
  cdc/scheduler/util/table_set.go
  cdc/scheduler/util/table_set_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none

#3240 tests: fix MySQL error that redo applier may meet
  pkg/applier/redo_test.go
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/XS, release-note-none

#3085 schema storage shallow copy DBInfo
  cdc/entry/schema_storage.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#3228 dm/test: fix openapi test client
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/run.sh
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#3250 p2p: fix unstable test TestServerWrapperDelayed
  pkg/p2p/server_wrapper_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none

#3237 sink: trivial fix for mq sink
  cdc/sink/mq.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  cdc/sink/producer/mq_producer.go
  cdc/sink/producer/pulsar/producer.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#3168 dm/syncer: use downstream PK/UK to generate DML
  dm/_utils/terror_gen/errors_release.txt
  dm/errors.toml
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
  dm/pkg/terror/error_list.go
  dm/pkg/utils/db.go
  dm/syncer/causality_test.go
  dm/syncer/compactor_test.go
  dm/syncer/dml.go
  dm/syncer/dml_test.go
  dm/syncer/expr_filter_group_test.go
  dm/syncer/filter_test.go
  dm/syncer/job_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/tests/downstream_diff_index/conf/dm-master.toml
  dm/tests/downstream_diff_index/conf/dm-task.yaml
  dm/tests/downstream_diff_index/conf/dm-worker1.toml
  dm/tests/downstream_diff_index/conf/dm-worker2.toml
  dm/tests/downstream_diff_index/conf/source1.yaml
  dm/tests/downstream_diff_index/conf/source2.yaml
  dm/tests/downstream_diff_index/data/db1.increment.sql
  dm/tests/downstream_diff_index/data/db1.prepare.sql
  dm/tests/downstream_diff_index/data/db2.increment.sql
  dm/tests/downstream_diff_index/data/db2.prepare.sql
  dm/tests/downstream_diff_index/data/tidb.prepare.sql
  dm/tests/downstream_diff_index/run.sh
  dm/tests/others_integration_1.txt
Labels: status/LGT2, status/can-merge, first-time-contributor, size/XXL, contribution, release-note, component/dm, needs-cherry-pick-release-5.3

#3255 github: use ARM64 self runner for build job
  .github/workflows/check_and_build.yaml
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#3153 *: support verify CI
  .gitignore
  Makefile
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#3219 CDC/etcd_worker: add rate limiter to limit EtcdWorker tick frequency
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_test.go
Labels: component/replica-model, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3172 schema_storage: fix schema GC threshold & improve memory management
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/metrics.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  metrics/grafana/ticdc.json
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2

#3259 compactor: fix performance issue caused by golang gc
  dm/dm/dm-ansible/scripts/DM-Monitor-Professional.json
  dm/syncer/compactor.go
  dm/syncer/compactor_test.go
  dm/syncer/dml_worker.go
  dm/syncer/job.go
  dm/syncer/metrics/metrics.go
  dm/syncer/syncer.go
  dm/tests/metrics/run.sh
Labels: subject/performance, status/LGT2, status/can-merge, size/L, release-note-none, component/dm, needs-cherry-pick-release-5.3

#3266 dm/openapi: support config experimental feature
  dm/dm/master/config.go
  dm/dm/master/config_test.go
  dm/dm/master/dm-master.toml
  dm/dm/master/openapi_test.go
  dm/dm/master/server.go
  dm/tests/dmctl_basic/conf/get_master1.toml
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/conf/dm-master1.toml
  dm/tests/openapi/conf/dm-master2.toml
Labels: status/LGT2, status/can-merge, size/M, release-note, component/dm, needs-cherry-pick-release-5.3

#3284 kafka_consumer: remove useless kafka_consumer Dockerfile
  kafka_consumer/Dockerfile
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#3281 kv/client: fix region loss in single region handler
  cdc/kv/region_worker.go
Labels: component/kv-client, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3282 github: add template for dm and refine other templates
  .github/ISSUE_TEMPLATE/dm-bug-report.yml
  .github/ISSUE_TEMPLATE/flaking-test.yml
  .github/ISSUE_TEMPLATE/question.yml
  .github/ISSUE_TEMPLATE/ticdc-bug-report.yml
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm, area/ticdc

#3243 dm-relay/streamer: move binlog log reader into relay
  dm/dm/worker/relay.go
  dm/dm/worker/relay_test.go
  dm/dm/worker/server_test.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/source_worker_test.go
  dm/dm/worker/subtask.go
  dm/dm/worker/subtask_test.go
  dm/pkg/binlog/writer/writer.go
  dm/pkg/streamer/util.go
  dm/pkg/streamer/util_test.go
  dm/relay/binlog_writer.go
  dm/relay/binlog_writer_test.go
  dm/relay/config.go
  dm/relay/error.go
  dm/relay/error_test.go
  dm/relay/file.go
  dm/relay/file_test.go
  dm/relay/file_util.go
  dm/relay/file_util_test.go
  dm/relay/local_reader.go
  dm/relay/local_reader_test.go
  dm/relay/purge_strategy.go
  dm/relay/purger.go
  dm/relay/purger/strategy.go
  dm/relay/purger/strategy_filename.go
  dm/relay/purger/strategy_inactive.go
  dm/relay/purger/strategy_space.go
  dm/relay/purger/strategy_time.go
  dm/relay/purger_helper.go
  dm/relay/purger_helper_test.go
  dm/relay/purger_test.go
  dm/relay/relay.go
  dm/relay/relay_test.go
  dm/relay/relay_writer.go
  dm/relay/relay_writer_test.go
  dm/relay/remote_retry.go
  dm/relay/remote_retry_test.go
  dm/relay/streamer.go
  dm/relay/streamer_test.go
  dm/relay/upstream_reader.go
  dm/relay/upstream_reader_test.go
  dm/relay/util.go
  dm/relay/util_test.go
  dm/relay/writer/writer.go
  dm/syncer/streamer_controller.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/tests/dmctl_basic/run.sh
  dm/tests/duplicate_event/run.sh
  dm/tests/only_dml/run.sh
  dm/tests/relay_interrupt/run.sh
  dm/tests/sharding2/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, contribution, release-note-none, area/dm

#3076 sink: canal json support encode checkpoint event.
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/mq.go
  cdc/sink/mq_test.go
  cdc/sink/mysql.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  cdc/sink/sink.go
  integration/framework/canal/kafka_single_table.go
  integration/integration.go
  pkg/filter/filter.go
  proto/EntryProtocol.proto
Labels: status/ptal, component/sink, status/LGT2, status/can-merge, size/XL, release-note-none

#2997 http_*: add log for http api and refine the err handle logic
  cdc/capture/http_errors.go
  cdc/capture/http_errors_test.go
  cdc/capture/http_handler.go
  cdc/capture/http_validator.go
  cdc/http_router.go
  cdc/http_router_test.go
  cdc/http_status.go
  cdc/sink/mysql.go
  cdc/sink/simple_mysql_tester.go
  cdc/sink/sink_test.go
  pkg/config/config_test.go
Labels: status/ptal, status/LGT2, status/can-merge, component/status-server, size/XL, component/metrics-logging, release-note-none, needs-cherry-pick-release-5.2, type/enhancement, needs-cherry-pick-release-5.3, area/ticdc

#3272 leveldb: add message, config and metrics
  cdc/metrics.go
  cdc/sorter/leveldb/message/task.go
  cdc/sorter/leveldb/message/task_test.go
  cdc/sorter/leveldb/metrics.go
  cdc/sorter/metrics.go
  cdc/sorter/unified/backend_pool.go
  cdc/sorter/unified/merger.go
  cdc/sorter/unified/metrics.go
  errors.toml
  go.mod
  go.sum
  pkg/actor/message/message.go
  pkg/actor/message/message_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config.go
  pkg/config/config_data_test.go
  pkg/config/config_test.go
  pkg/config/sorter.go
  pkg/errors/errors.go
Labels: component/configuration, status/LGT2, status/can-merge, size/XXL, component/sorter, release-note-none, area/ticdc

#3300 metrics: add changefeed checkepoint catch-up ETA
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, component/metrics-logging, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3317 api: move the API specs file into right place
  api/docs.go
  api/swagger.json
  api/swagger.yaml
  cdc/http_router.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc

#3315 integration: extracts duplicate constants
  integration/framework/avro/kafka_docker_env.go
  integration/framework/avro/kafka_docker_env_test.go
  integration/framework/avro/kafka_single_table.go
  integration/framework/canal/kafka_docker_env.go
  integration/framework/canal/kafka_docker_env_test.go
  integration/framework/canal/kafka_single_table.go
  integration/framework/docker_env.go
  integration/framework/mysql/docker_env.go
  integration/framework/mysql/docker_env_test.go
  integration/framework/mysql/single_table.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#3320 puller,kv: trivial fix for puller
  cdc/kv/client.go
  cdc/puller/puller.go
  pkg/regionspan/span.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#3304 github: use x64 self runner for build and check job
  .github/workflows/check_and_build.yaml
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#3295 dm: load table structure from dump files
  dm/loader/util.go
  dm/syncer/syncer.go
  dm/tests/downstream_more_column/run.sh
  dm/tests/shardddl1/run.sh
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#3319 actor: add profile label and per worker cpu seconds
  pkg/actor/metrics.go
  pkg/actor/system.go
Labels: status/LGT2, status/can-merge, size/M, component/metrics-logging, release-note-none, type/enhancement, area/ticdc

#3241 dm/tracker: also ignore some safe error for tracker
  dm/syncer/error.go
  dm/syncer/syncer.go
  dm/tests/drop_column_with_index/data/db1.increment2.sql
  dm/tests/drop_column_with_index/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note, area/dm

#3298 redolog: close tmp file after use & refactor
  cdc/redo/reader/file.go
  cdc/redo/reader/file_test.go
  cdc/redo/reader/reader.go
  cdc/redo/reader/reader_test.go
  cdc/redo/writer/writer.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, component/redolog, needs-cherry-pick-release-5.3, area/ticdc

#3299 cdc/model: a protocol for owner/processor interaction
  cdc/model/protocol.go
  cdc/model/protocol_test.go
Labels: status/ptal, component/scheduler, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#3318 sink: split mysql sink into multiple files
  cdc/sink/mysql.go
  cdc/sink/mysql_params.go
  cdc/sink/mysql_params_test.go
  cdc/sink/mysql_syncpoint_store.go
  cdc/sink/mysql_test.go
  cdc/sink/mysql_worker.go
  cdc/sink/mysql_worker_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#3308 dm/syncer: multiple rows use downstream schema
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
  dm/syncer/causality_test.go
  dm/syncer/compactor_test.go
  dm/syncer/dml.go
  dm/syncer/dml_test.go
  dm/syncer/job_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#3345 dm/worker: don't exit when failed to read checkpoint in relay
  dm/dm/worker/server.go
  dm/dm/worker/source_worker.go
  dm/pkg/schema/tracker.go
  dm/tests/new_relay/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note, area/dm

#3343 ticdc/redolog: add nfs as storage
  cdc/redo/applier.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  pkg/cmd/redo/redo.go
  pkg/cmd/util/changefeed.toml
  tests/consistent_replicate_local/conf/changefeed.toml
  tests/consistent_replicate_nfs/conf/changefeed.toml
  tests/consistent_replicate_nfs/conf/diff_config.toml
  tests/consistent_replicate_nfs/conf/workload
  tests/consistent_replicate_nfs/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, component/redolog, needs-cherry-pick-release-5.3

#3334 redolog: add DeleteAllLogs api
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner.go
  cdc/redo/common/util.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/reader/file_test.go
  cdc/redo/reader/reader.go
  cdc/redo/reader/reader_test.go
  cdc/redo/writer/blackhole_writer.go
  cdc/redo/writer/file.go
  cdc/redo/writer/file_test.go
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
  go.mod
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, component/redolog, needs-cherry-pick-release-5.3, area/ticdc

#3365 dm-test: fix unstable case
  dm/tests/ha_cases2/run.sh
Labels: status/LGT2, status/can-merge, size/XS, contribution, release-note-none, area/dm

#3357 sink: add log when skip the empty row event
  cdc/processor/pipeline/sink.go
Labels: status/LGT1, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, component/metrics-logging, require-LGT1, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3202 sorter/leveldb: add leveldb actor
  cdc/sorter/leveldb/leveldb.go
  cdc/sorter/leveldb/leveldb_test.go
  cdc/sorter/metrics.go
  cdc/sorter/unified/backend_pool.go
  cdc/sorter/unified/merger.go
  errors.toml
  pkg/cmd/server/server_test.go
  pkg/config/config.go
  pkg/config/config_data_test.go
  pkg/config/sorter.go
  pkg/errors/errors.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, component/sorter, release-note-none, area/ticdc

#3376 dm-test: fix unstable unit test
  dm/relay/relay_test.go
Labels: status/LGT2, status/can-merge, size/S, contribution, release-note-none, area/dm

#3277 etcd_worker: batch etcd patch
  cdc/capture/capture.go
  cdc/metrics.go
  errors.toml
  metrics/grafana/ticdc.json
  pkg/errors/errors.go
  pkg/orchestrator/batch.go
  pkg/orchestrator/batch_test.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_bank_test.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/interfaces.go
  pkg/orchestrator/metrics.go
  pkg/orchestrator/reactor_state.go
  testing_utils/cdc_state_checker/cdc_monitor.go
Labels: status/ptal, component/replica-model, subject/performance, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3396 docs: add command.md for ci
  .github/workflows/docs_lint.yaml
  CONTRIBUTING.md
  docs/.gitignore
  docs/ci/command.md
  docs/design/README.md
  docs/package-lock.json
  docs/package.json
  docs/ticdc-grafana-dashboard.md
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#3388 dm/scheduler: remove a false-positive DPanic
  dm/dm/master/scheduler/scheduler.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm, needs-cherry-pick-release-5.3

#3414 ticdc/processor: don't close error channel in receiver
  cdc/processor/processor.go
Labels: status/ptal, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3413 dm/test: swap upstream and downstream of sync_diff in some cases
  dm/tests/_utils/test_prepare
  dm/tests/adjust_gtid/conf/diff_config_revert_1.toml
  dm/tests/adjust_gtid/conf/diff_config_revert_2.toml
  dm/tests/adjust_gtid/run.sh
  dm/tests/dm_syncer/run.sh
  dm/tests/full_mode/conf/diff_config_revert_1.toml
  dm/tests/full_mode/conf/diff_config_revert_2.toml
  dm/tests/full_mode/run.sh
  dm/tests/incremental_mode/conf/diff_config_revert_1.toml
  dm/tests/incremental_mode/conf/diff_config_revert_2.toml
  dm/tests/incremental_mode/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#3316 sink: fix wrong comments
  cdc/sink/mysql.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#3423 redolog: alwasy set running to false when close
  cdc/redo/writer/file.go
  cdc/redo/writer/file_test.go
Labels: status/LGT2, status/can-merge, size/M, component/redolog, needs-cherry-pick-release-5.3, area/ticdc

#3279 sorter/leveldb: add cleaner
  cdc/sorter/leveldb/cleaner.go
  cdc/sorter/leveldb/cleaner_test.go
  cdc/sorter/leveldb/message/task.go
  cdc/sorter/leveldb/message/task_test.go
  pkg/actor/actor.go
  pkg/actor/actor_test.go
  pkg/actor/system.go
  pkg/actor/system_test.go
  pkg/actor/testing.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, component/sorter, release-note-none, area/ticdc

#3395 test: add test for needSwitchDB
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#3257 scheduler: unify modification of s.bounds and s.unbounds
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#3418 *: fix some typos
  cdc/kv/region_worker.go
  cdc/processor/pipeline/sink.go
  cdc/redo/manager.go
Labels: status/ptal, status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, area/ticdc

#3192 cdc/sink: adjust kafka initialization logic
  cdc/sink/mq.go
  cdc/sink/mq_test.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
Labels: status/ptal, component/sink, status/LGT2, status/can-merge, size/XL, release-note

#3436 cdc/sorter: make unified sorter cgroup aware
  cdc/sorter/unified/backend_pool.go
  cdc/sorter/unified/backend_pool_test.go
  go.mod
  go.sum
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, component/sorter, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3435 CI: update config for sync diff
  dm/tests/dmctl_basic/conf/diff_config.toml
  dm/tests/online_ddl/conf/diff_config.toml
  dm/tests/print_status/conf/diff_config.toml
  dm/tests/safe_mode/conf/diff_config.toml
  dm/tests/sequence_safe_mode/conf/diff_config.toml
  dm/tests/sequence_sharding/conf/diff_config.toml
  dm/tests/sequence_sharding_optimistic/conf/diff_config.toml
  dm/tests/sequence_sharding_removemeta/conf/diff_config.toml
  dm/tests/sharding/conf/diff_config.toml
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm, needs-cherry-pick-release-5.3

#3190 dm: turn on/off relay by source config
  Makefile
  dm/dm/config/source_config.go
  dm/dm/config/source_config_test.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/master/server.go
  dm/dm/worker/server.go
  dm/dm/worker/source_worker.go
  dm/pkg/ha/ops.go
  dm/tests/all_mode/run.sh
  dm/tests/dmctl_basic/check_list/config.sh
  dm/tests/dmctl_basic/conf/get_source1.yaml
  dm/tests/dmctl_basic/conf/get_source2.yaml
  dm/tests/dmctl_basic/conf/source1.yaml
  dm/tests/dmctl_basic/conf/source2.yaml
  dm/tests/drop_column_with_index/run.sh
  dm/tests/ha_cases/conf/source1.yaml
  dm/tests/ha_cases/conf/source2.yaml
  dm/tests/ha_cases2/conf/source1.yaml
  dm/tests/ha_cases2/conf/source2.yaml
  dm/tests/ha_cases3/conf/source1.yaml
  dm/tests/ha_cases3/conf/source2.yaml
  dm/tests/ha_cases3_1/run.sh
  dm/tests/ha_cases_1/conf/source1.yaml
  dm/tests/ha_cases_1/conf/source2.yaml
  dm/tests/ha_cases_2/conf/source1.yaml
  dm/tests/ha_cases_2/conf/source2.yaml
  dm/tests/ha_master/conf/source2.yaml
  dm/tests/handle_error/run.sh
  dm/tests/http_apis/run.sh
  dm/tests/import_v10x/run.sh
  dm/tests/new_relay/conf/source1.yaml
  dm/tests/new_relay/configs/sources/mysql-replica-01.yaml
  dm/tests/new_relay/run.sh
  dm/tests/safe_mode/run.sh
  dm/tests/sequence_sharding_optimistic/run.sh
  dm/tests/shardddl2/run.sh
  dm/tests/shardddl4_1/run.sh
  dm/tests/sharding2/conf/source2.yaml
  dm/tests/tracker_ignored_ddl/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm

#3463 dm/test: align CI behaviour with enable-relay
  dm/tests/compatibility/start.sh
Labels: component/test, status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-5.3

#3451 scheduler_v2: util for implementing agent
  cdc/scheduler/agent_mock.go
  cdc/scheduler/agent_mock_test.go
  cdc/scheduler/checkpoint_sender.go
  cdc/scheduler/checkpoint_sender_test.go
  go.mod
Labels: status/ptal, component/scheduler, status/LGT2, status/can-merge, size/XL, release-note-none

#3444 sorter: rename some structures and methods to make revive happy
  cdc/processor/pipeline/sorter.go
  cdc/sorter/unified/merger.go
  cdc/sorter/unified/sorter_test.go
  cdc/sorter/unified/unified_sorter.go
  pkg/cmd/server/server.go
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none

#3327 dm-relay: create binlog reader from relay, refactor relay
  dm/dm/worker/relay.go
  dm/dm/worker/relay_test.go
  dm/dm/worker/server_test.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/source_worker_test.go
  dm/dm/worker/subtask.go
  dm/dm/worker/subtask_holder.go
  dm/dm/worker/subtask_test.go
  dm/pkg/binlog/reader/tcp.go
  dm/pkg/binlog/reader/util.go
  dm/pkg/parser/common.go
  dm/pkg/parser/common_test.go
  dm/relay/binlog_writer.go
  dm/relay/binlog_writer_test.go
  dm/relay/common/util.go
  dm/relay/common/util_test.go
  dm/relay/file_util.go
  dm/relay/local_reader.go
  dm/relay/local_reader_test.go
  dm/relay/purger_test.go
  dm/relay/relay.go
  dm/relay/relay_test.go
  dm/relay/relay_writer.go
  dm/relay/relay_writer_test.go
  dm/relay/remote_retry_test.go
  dm/relay/transformer/transformer.go
  dm/relay/transformer/transformer_test.go
  dm/relay/upstream_reader_test.go
  dm/relay/util_test.go
  dm/syncer/streamer_controller.go
  dm/syncer/streamer_controller_test.go
  dm/syncer/syncer.go
  dm/syncer/util.go
  dm/syncer/util_test.go
Labels: status/LGT2, status/can-merge, size/XXL, contribution, release-note-none, area/dm

#3454 sorter/leveldb: stable flakey test and fix iterator leak
  cdc/sorter/leveldb/cleaner.go
  cdc/sorter/leveldb/cleaner_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/S, component/sorter, release-note-none, area/ticdc

#3462 dm/test: align test behaviour for enable-relay
  dm/tests/upstream_switch/case.sh
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#3459 dm/load: fix concurrent call Loader.Status
  dm/loader/loader.go
  dm/loader/status.go
  dm/loader/status_test.go
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note, area/dm, needs-cherry-pick-release-5.3

#3460 ticdc/config: add feature debug configuration
  pkg/cmd/server/server.go
  pkg/cmd/server/server_test.go
  pkg/cmd/util/helper.go
  pkg/cmd/util/helper_test.go
  pkg/config/config.go
  pkg/config/config_data_test.go
  pkg/config/debug.go
Labels: component/configuration, status/LGT2, status/can-merge, size/L, release-note-none

#3466 scheduler_v2: moveTableManager
  cdc/scheduler/move_table_manager.go
  cdc/scheduler/move_table_manager_test.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#3260 dm/loader: support dump tls certs from dm-master
  dm/dm/config/security.go
  dm/dm/config/security_test.go
  dm/dm/config/subtask.go
  dm/dm/worker/subtask.go
  dm/loader/lightning.go
  dm/roadmap.md
  dm/tests/tls/conf/dm-task.yaml
  dm/tests/tls/conf/task-ca.pem
  dm/tests/tls/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm

#3442 sorter: extract methods and add tests
  cdc/sorter/memory/entry_sorter.go
  cdc/sorter/memory/entry_sorter_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#3163 scheduler_v2: implement the basic logic for agent (the schedule receiver in Processor)
  cdc/scheduler/agent.go
  cdc/scheduler/agent_mock.go
  cdc/scheduler/agent_mock_test.go
  cdc/scheduler/agent_test.go
  cdc/scheduler/util/sort_table_ids.go
  errors.toml
  pkg/errors/errors.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none

#3406 leveldb: add leveldb sorter system
  cdc/metrics.go
  cdc/sorter/leveldb/system/metrics.go
  cdc/sorter/leveldb/system/system.go
  cdc/sorter/leveldb/system/system_test.go
  errors.toml
  pkg/errors/errors.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, component/sorter, release-note-none

#3472 dm/pkg/retry: modify ReplicationErrMsgs and add relevant unit test
  dm/dm/worker/task_checker_test.go
  dm/pkg/retry/errors.go
Labels: status/LGT2, status/can-merge, size/XS, contribution, release-note, area/dm

#3474 dm/scheduler: fix inconsistent of relay status
  dm/dm/master/scheduler/scheduler.go
  dm/tests/new_relay/conf/source2.yaml
  dm/tests/new_relay/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm, needs-cherry-pick-release-5.3

#3471 dm/syncer : fix unstable test in shardddl1
  dm/dm/master/shardddl/optimist.go
  dm/dm/master/shardddl/pessimist.go
  dm/tests/shardddl1/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note, area/dm

#3467 dm/syncer : fix wrong causality key when schema has prefix index
  dm/syncer/causality_test.go
  dm/syncer/dml.go
  dm/syncer/dml_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm

#3203 codec: canal-json support batch decoder
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/codec/json.go
  go.mod
  go.sum
Labels: status/ptal, component/sink, status/LGT2, status/can-merge, size/XL, release-note

#3475 cdc/sorter: add non-blocking function TryAddEntry
  cdc/sorter/memory/entry_sorter.go
  cdc/sorter/memory/entry_sorter_test.go
  cdc/sorter/sorter.go
  cdc/sorter/unified/unified_sorter.go
  cdc/sorter/unified/unified_sorter_test.go
  errors.toml
  pkg/errors/errors.go
Labels: status/LGT2, status/can-merge, size/L, component/sorter, release-note-none, area/ticdc

#3501 cdc/sink: only check max-message-bytes for default protocol & craft protocol
  cdc/sink/producer/kafka/kafka.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#3499 cdc/capture: init table actor system if it is enabled
  cdc/capture/capture.go
  cdc/processor/pipeline/system/system.go
  cdc/processor/pipeline/system/system_test.go
  pkg/context/context.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#3486 sorter/leveldb: add output buffer
  cdc/sorter/leveldb/buffer.go
  cdc/sorter/leveldb/buffer_test.go
Labels: status/LGT2, status/can-merge, size/L, component/sorter, release-note-none, area/ticdc

#3500 cdc/scheduler_v2: implement balancer
  cdc/scheduler/agent.go
  cdc/scheduler/balancer.go
  cdc/scheduler/balancer_test.go
  cdc/scheduler/util/sort_table_ids.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#3515 ticdc/reactor: log capture info when remote capture is offline
  pkg/orchestrator/reactor_state.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, component/metrics-logging, release-note-none, area/ticdc

#3490 owner: fix owner tick block http request
  cdc/owner/owner.go
  cdc/owner/owner_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-5.3

#3013 *: fix changefeed checkpoint lag negative value error
  cdc/capture/capture.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/processor/manager.go
  cdc/processor/processor.go
  pkg/context/context.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/pdtime/acquirer.go
  pkg/pdtime/acquirer_test.go
  pkg/pdtime/main_test.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_manager_test.go
Labels: status/ptal, type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, component/metrics-logging, bug-from-internal-test, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3434 dm/syncer : add integration test for dml using downstream schema
  dm/syncer/compactor.go
  dm/tests/_utils/test_prepare
  dm/tests/shardddl1/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#3333 dm/openapi: use gin as http router instead of echo
  Makefile
  dm/dm/master/openapi.go
  dm/dm/master/openapi_test.go
  dm/dm/master/server.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/logger.go
  dm/openapi/logger_test.go
  dm/openapi/spec/server-gen-cfg.yaml
  dm/tests/openapi/run.sh
  go.mod
  go.sum
  tools/check/go.mod
  tools/check/go.sum
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#3498 dm/election: fix datarace when campaign slow
  dm/pkg/election/election.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#3544 cdc/scheduler_v2: refine TableSet for scheduler
  cdc/scheduler/util/table_set.go
  cdc/scheduler/util/table_set_test.go
Labels: status/ptal, component/scheduler, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#3547 examples(ticdc): move java demo into examples
  examples/java/.gitignore
  examples/java/README.md
  examples/java/pom.xml
  examples/java/src/main/java/com/pingcap/ticdc/cdc/KafkaMessage.java
  examples/java/src/main/java/com/pingcap/ticdc/cdc/TicdcEventData.java
  examples/java/src/main/java/com/pingcap/ticdc/cdc/TicdcEventDecoder.java
  examples/java/src/main/java/com/pingcap/ticdc/cdc/TicdcEventFilter.java
  examples/java/src/main/java/com/pingcap/ticdc/cdc/key/TicdcEventKey.java
  examples/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventBase.java
  examples/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventColumn.java
  examples/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventDDL.java
  examples/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventResolve.java
  examples/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventRowChange.java
  examples/java/src/main/java/com/pingcap/ticdc/cdc/value/TicdcEventType.java
  examples/java/src/test/java/com/pingcap/ticdc/cdc/TicdcEventDecoderTest.java
  examples/java/src/test/resources/data/key/ddl_key_0
  examples/java/src/test/resources/data/key/ddl_key_1
  examples/java/src/test/resources/data/key/ddl_key_2
  examples/java/src/test/resources/data/key/row_key_0
  examples/java/src/test/resources/data/key/row_key_1
  examples/java/src/test/resources/data/key/row_key_2
  examples/java/src/test/resources/data/key/rts_key_0
  examples/java/src/test/resources/data/key/rts_key_1
  examples/java/src/test/resources/data/key/rts_key_2
  examples/java/src/test/resources/data/value/ddl_value_0
  examples/java/src/test/resources/data/value/ddl_value_1
  examples/java/src/test/resources/data/value/ddl_value_2
  examples/java/src/test/resources/data/value/row_value_0
  examples/java/src/test/resources/data/value/row_value_1
  examples/java/src/test/resources/data/value/row_value_2
  examples/java/src/test/resources/data/value/rts_value_0
  examples/java/src/test/resources/data/value/rts_value_1
  examples/java/src/test/resources/data/value/rts_value_2
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#3548 chaos(ticdc): remove all chaos files
  .github/workflows/ticdc_chaos.yaml
  chaos/Dockerfile.chaos
  chaos/checker.sh
  chaos/manifests/downstream.yaml
  chaos/manifests/io-chaos-cdc.yaml
  chaos/manifests/network-emulation-cdc.yaml
  chaos/manifests/network-partition-cdc.yaml
  chaos/manifests/pod-failure-cdc.yaml
  chaos/manifests/pod-kill-cdc.yaml
  chaos/manifests/ticdc.yaml
  chaos/manifests/upstream.yaml
  chaos/manifests/workload.yaml
  chaos/sorter-config.toml
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#3543 ticdc/metrics: fix processor checkpoint-ts lag expr
  metrics/grafana/ticdc.json
Labels: status/ptal, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, component/metrics-logging, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3540 processor,sink(cdc): let sink report resolved ts and do not skip buffer sink flush
  cdc/processor/pipeline/table.go
  cdc/sink/manager.go
  cdc/sink/table_sink.go
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, cherry-pick-approved, needs-cherry-pick-release-5.1, component/sorter, release-note-none, needs-cherry-pick-release-5.2

#3502 test: Make mysql and kakfa integration tests locally runnable
  Makefile
  deployments/ticdc/docker-compose/docker-compose-kafka-integration.yml
  deployments/ticdc/docker-compose/docker-compose-mysql-integration.yml
  deployments/ticdc/docker/integration-test.Dockerfile
  scripts/download-integration-test-binaries.sh
Labels: component/test, status/LGT2, status/can-merge, size/L, release-note-none

#3570 test(ticdc): separate statistics for unit tests and integration tests
  Makefile
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#3551 cdc/scheduler_v2: interfaces and mocks for ScheduleDispatcher
  cdc/scheduler/scheduler_dispatcher.go
  cdc/scheduler/scheduler_dispatcher_test.go
Labels: status/ptal, component/scheduler, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#3484 master: add declare for start/stop relay commands
  dm/dm/master/server.go
  dm/dm/pb/dmmaster.pb.go
  dm/dm/proto/dmmaster.proto
  dm/tests/adjust_gtid/run.sh
  dm/tests/all_mode/run.sh
  dm/tests/dmctl_basic/check_list/start_relay.sh
  dm/tests/dmctl_basic/check_list/stop_relay.sh
  dm/tests/dmctl_basic/run.sh
  dm/tests/duplicate_event/run.sh
  dm/tests/full_mode/run.sh
  dm/tests/gtid/run.sh
  dm/tests/ha/run.sh
  dm/tests/ha_cases/run.sh
  dm/tests/ha_cases2/run.sh
  dm/tests/ha_cases3/run.sh
  dm/tests/ha_cases_1/run.sh
  dm/tests/ha_cases_2/run.sh
  dm/tests/ha_master/run.sh
  dm/tests/incremental_mode/run.sh
  dm/tests/initial_unit/run.sh
  dm/tests/lightning_mode/run.sh
  dm/tests/new_relay/run.sh
  dm/tests/online_ddl/run.sh
  dm/tests/only_dml/run.sh
  dm/tests/relay_interrupt/run.sh
  dm/tests/sharding2/run.sh
  dm/tests/tiup/lib.sh
  dm/tests/upstream_switch/case.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#3469 dm-relay: optimize cpu usage when enabling relay
  dm/dm/worker/relay_test.go
  dm/pkg/binlog/position.go
  dm/pkg/utils/util.go
  dm/relay/binlog_writer.go
  dm/relay/binlog_writer_test.go
  dm/relay/error.go
  dm/relay/error_test.go
  dm/relay/file.go
  dm/relay/file_test.go
  dm/relay/local_reader.go
  dm/relay/local_reader_test.go
  dm/relay/relay.go
  dm/relay/relay_test.go
  dm/relay/relay_writer.go
  dm/relay/relay_writer_test.go
  dm/relay/streamer.go
  dm/relay/upstream_reader.go
  dm/relay/upstream_reader_test.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XXL, contribution, release-note, area/dm

#3262 dm/loader/syncer: support extend column
  dm/loader/convert_data.go
  dm/loader/convert_data_test.go
  dm/loader/loader.go
  dm/syncer/dml.go
  dm/syncer/syncer.go
  dm/tests/extend_column/conf/dm-master.toml
  dm/tests/extend_column/conf/dm-task.yaml
  dm/tests/extend_column/conf/dm-worker1.toml
  dm/tests/extend_column/conf/dm-worker2.toml
  dm/tests/extend_column/conf/source1.yaml
  dm/tests/extend_column/conf/source2.yaml
  dm/tests/extend_column/data/db1.delete.sql
  dm/tests/extend_column/data/db1.increment.sql
  dm/tests/extend_column/data/db1.prepare.sql
  dm/tests/extend_column/data/db1.update.sql
  dm/tests/extend_column/data/db2.delete.sql
  dm/tests/extend_column/data/db2.increment.sql
  dm/tests/extend_column/data/db2.prepare.sql
  dm/tests/extend_column/data/db2.update.sql
  dm/tests/extend_column/data/tidb.prepare.sql
  dm/tests/extend_column/run.sh
  dm/tests/others_integration_2.txt
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, first-time-contributor, size/XXL, contribution, release-note, area/dm

#3582 openapi(dm): fix swagger doc
  dm/dm/master/openapi.go
  dm/openapi/gen.server.go
  dm/openapi/spec/dm.yaml
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#3573 config(ticdc): add column-selectors for sink and split config file
  docs/design/2021-10-13-ticdc-mq-sink-column-selector.md
  pkg/cmd/util/changefeed.toml
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/server_config.go
  pkg/config/server_config_test.go
  pkg/config/sink.go
Labels: component/sink, status/LGT2, status/can-merge, size/XL, release-note-none

#3216 cdc/scheduler_v2: implement the basic logic for the new schedule dispatcher
  cdc/scheduler/schedule_dispatcher.go
  cdc/scheduler/schedule_dispatcher_test.go
  cdc/scheduler/scheduler_dispatcher.go
  cdc/scheduler/scheduler_dispatcher_test.go
Labels: status/ptal, component/replica-model, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#3576 pkg/p2p: streamHandle for implementing MessageServer
  errors.toml
  pkg/errors/errors.go
  pkg/p2p/server_stream_handle.go
  pkg/p2p/server_stream_handle_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#3560 dm/syncer: fix directly use types.NewDatum
  dm/syncer/causality.go
  dm/syncer/causality_test.go
  dm/syncer/dml.go
  dm/syncer/dml_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#3587 deployments(ticdc): fix typo
  deployments/ticdc/docker-compose/docker-compose-mysql-integration.yml
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#3422 ticdc.rules: fix alertmanager rules
  metrics/alertmanager/ticdc.rules.yml
Labels: status/ptal, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, component/metrics-logging, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3585 dm/test: fix tiup upgrade test
  .github/workflows/upgrade_dm_via_tiup.yaml
  dm/tests/tiup/lib.sh
Labels: component/test, status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#3574 pkg/p2p: ackManager for implementing MessageServer
  pkg/p2p/server_ack_manager.go
  pkg/p2p/server_ack_manager_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#3432 compactor: fix duplicate entry in safemode
  dm/syncer/compactor.go
  dm/syncer/compactor_test.go
  dm/syncer/dml.go
  dm/syncer/dml_test.go
  dm/syncer/syncer_test.go
  dm/tests/shardddl1/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/dm, needs-cherry-pick-release-5.3

#3552 sorter(ticdc): remove useless field
  cdc/sorter/unified/unified_sorter.go
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#3554 tests(cdc): support start and stop test tidb on mac
  tests/_utils/start_tidb_cluster_impl
  tests/_utils/stop_tidb_cluster
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note-none

#3614 cdc/tests: adjust ddl_reentrant test case
  tests/ddl_reentrant/run.sh
Labels: component/test, status/LGT1, status/can-merge, size/XS, cherry-pick-approved, require-LGT1, release-note-none

#3613 cdc/sink: Refine sink interface
  cdc/owner/async_sink_test.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table.go
  cdc/sink/black_hole.go
  cdc/sink/buffer_sink.go
  cdc/sink/cdclog/file.go
  cdc/sink/cdclog/s3.go
  cdc/sink/manager.go
  cdc/sink/manager_test.go
  cdc/sink/mq.go
  cdc/sink/mq_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/simple_mysql_tester.go
  cdc/sink/sink.go
  cdc/sink/table_sink.go
  cmd/kafka-consumer/main.go
  pkg/applier/redo.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#3226 *(dm): support start/stop relay cmd without worker name
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/ctl/master/start_stop_relay.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/master/server.go
  dm/dm/worker/server.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/source_worker_test.go
  dm/errors.toml
  dm/pkg/terror/error_list.go
  dm/pkg/utils/util.go
  dm/tests/adjust_gtid/run.sh
  dm/tests/all_mode/run.sh
  dm/tests/dmctl_basic/check_list/start_relay.sh
  dm/tests/dmctl_basic/check_list/stop_relay.sh
  dm/tests/dmctl_basic/run.sh
  dm/tests/duplicate_event/conf/source2.yaml
  dm/tests/full_mode/run.sh
  dm/tests/gtid/run.sh
  dm/tests/ha/conf/source2.yaml
  dm/tests/incremental_mode/conf/source1.yaml
  dm/tests/incremental_mode/conf/source2.yaml
  dm/tests/initial_unit/run.sh
  dm/tests/lightning_mode/run.sh
  dm/tests/online_ddl/run.sh
  dm/tests/only_dml/run.sh
  dm/tests/relay_interrupt/run.sh
  dm/tests/tiup/lib.sh
  dm/tests/tracker_ignored_ddl/run.sh
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm

#3358 dmctl(dm): list all task even when some worker offline
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/master/openapi.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/server.go
  dm/errors.toml
  dm/pkg/terror/error_list.go
  dm/tests/dmctl_basic/check_list/query_status.sh
  dm/tests/dmctl_basic/run.sh
  dm/tests/ha_cases/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note, area/dm

#3464 ticdc/kvclient: make multiple cdc kv clients share one RegionCache
  cdc/capture/capture.go
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/testing.go
  cdc/owner/ddl_puller.go
  cdc/processor/pipeline/puller.go
  cdc/processor/processor.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/context/context.go
Labels: component/kv-client, subject/performance, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, first-time-contributor, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3600 openapi(dm): support config relay when create source
  dm/dm/config/source_converter.go
  dm/dm/config/source_converter_test.go
  dm/dm/master/openapi.go
  dm/openapi/fixtures/source.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note, area/dm

#3638 cdc/redo: redo applier flush resolvedTs per table
  pkg/applier/redo.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#3643 Fix handling of JSON columns
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
Labels: type/bugfix, component/sink, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3610 sorter/leveldb(cdc): add leveldb-like interfaces
  cdc/metrics.go
  cdc/sorter/leveldb/cleaner.go
  cdc/sorter/leveldb/cleaner_test.go
  cdc/sorter/leveldb/leveldb.go
  cdc/sorter/leveldb/leveldb_test.go
  cdc/sorter/leveldb/message/task.go
  cdc/sorter/leveldb/metrics.go
  cdc/sorter/leveldb/system/metrics.go
  cdc/sorter/leveldb/system/system.go
  cdc/sorter/leveldb/system/system_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/db.go
  pkg/config/debug.go
  pkg/config/server_config.go
  pkg/config/server_config_test.go
  pkg/config/sorter.go
  pkg/db/db.go
  pkg/db/db_test.go
  pkg/db/leveldb.go
  pkg/db/metrics.go
Labels: status/LGT2, status/can-merge, size/XXL, component/sorter, release-note-none, area/ticdc

#3601 owner_test (ticdc): fix unstable case TestHandleJobsDontBlock
  cdc/owner/owner.go
  cdc/owner/owner_test.go
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#3630 test(dm): fix failed test caused by new stop-relay
  dm/tests/upstream_switch/case.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#3520 ticdc/server: output the cdc server cmd error to stderr
  dm/dm/ctl/ctl.go
  go.mod
  go.sum
  pkg/cmd/cmd.go
Labels: status/LGT2, status/can-merge, first-time-contributor, size/M, release-note-none

#3612 kvclient(ticdc): fix kvclient takes too long time to recover
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
Labels: component/kv-client, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3

#3622 ticdc/pkg/p2p: basic data structures to implement MessageClient
  pkg/p2p/client_batch_sender.go
  pkg/p2p/client_batch_sender_test.go
  pkg/p2p/client_connector.go
  pkg/p2p/client_connector_test.go
  pkg/p2p/metrics.go
  pkg/p2p/mock_grpc_client.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#3648 status(dm): fix update mariadb source status
  dm/dm/worker/source_worker.go
Labels: status/LGT2, status/can-merge, size/XS, release-note, area/dm

#3619 ticdc/pkg: refine wrap error message
  pkg/errors/helper.go
  pkg/errors/helper_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none

#3665 sink(ticdc): Set config.Metadata.Timeout correctly
  cdc/sink/producer/kafka/kafka.go
Labels: component/sink, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc

#3586 ci: migrete ut to verifyCI
  .codecov.yml
  .github/workflows/check_and_build.yaml
  Makefile
  docs/ci/command.md
  tools/check/go.mod
  tools/check/go.sum
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none

#3655 processor, scheduler_v2(cdc): integrate the Processor with Scheduler(V2) Part I
  cdc/model/owner.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/agent.go
  cdc/scheduler/agent_mock_test.go
  cdc/scheduler/agent_test.go
  pkg/config/server_config.go
Labels: status/ptal, component/replica-model, status/LGT2, status/can-merge, size/XL, release-note-none

#3605 doc(dm): add dm v5.3.0 changelog
  dm/CHANGELOG.md
Labels: status/LGT2, status/can-merge, size/M, release-note, area/dm

#3516 processor: let sorter output events less or equal to barrier ts
  cdc/entry/schema_storage.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  tests/_utils/ensure
  tests/cyclic_ab/run.sh
  tests/force_replicate_table/run.sh
Labels: status/LGT2, status/can-merge, size/L, component/sorter, release-note-none, area/ticdc

#3621 cdc/sink: Sink manager manage checkpoint per table
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/sink/manager.go
  cdc/sink/manager_test.go
  cdc/sink/table_sink.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none
