Repository pingcap/tiflow, pull requests merged in 2022-02, with the labels that each got.

#4502 sink(ticdc): fix duplicated replace when batch-replace is disabled
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
Labels: type/bugfix, component/sink, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#3903 Optimistic: support start task with inconsistent upstream table schema
  Makefile
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/common/common.go
  dm/dm/common/common_test.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/master/server.go
  dm/dm/master/server_test.go
  dm/dm/master/shardddl/optimist.go
  dm/dm/master/shardddl/optimist_test.go
  dm/errors.toml
  dm/pkg/shardddl/optimism/info.go
  dm/pkg/shardddl/optimism/info_test.go
  dm/pkg/shardddl/optimism/keeper.go
  dm/pkg/shardddl/optimism/keeper_test.go
  dm/pkg/shardddl/optimism/lock.go
  dm/pkg/shardddl/optimism/lock_test.go
  dm/pkg/shardddl/optimism/ops.go
  dm/pkg/shardddl/optimism/ops_test.go
  dm/pkg/shardddl/optimism/schema.go
  dm/pkg/shardddl/optimism/schema_test.go
  dm/pkg/terror/error_list.go
  dm/syncer/checkpoint.go
  dm/syncer/optimist.go
  dm/syncer/schema.go
  dm/syncer/shardddl/optimist.go
  dm/syncer/shardddl/optimist_test.go
  dm/syncer/syncer.go
  dm/tests/_utils/shardddl_lib.sh
  dm/tests/_utils/test_prepare
  dm/tests/downstream_more_column/run.sh
  dm/tests/others_integration_2.txt
  dm/tests/sequence_sharding_optimistic/run.sh
  dm/tests/shardddl1/run.sh
  dm/tests/shardddl_optimistic/conf/diff_config.toml
  dm/tests/shardddl_optimistic/conf/dm-master.toml
  dm/tests/shardddl_optimistic/conf/dm-worker1.toml
  dm/tests/shardddl_optimistic/conf/dm-worker2.toml
  dm/tests/shardddl_optimistic/conf/double-source-optimistic-incr.yaml
  dm/tests/shardddl_optimistic/conf/double-source-optimistic.yaml
  dm/tests/shardddl_optimistic/conf/source1.yaml
  dm/tests/shardddl_optimistic/conf/source2.yaml
  dm/tests/shardddl_optimistic/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#4500 syncer(dm): Fix async flush log message
  dm/syncer/syncer.go
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note, needs-cherry-pick-release-5.4

#4412 dm(ui): support start/pause/resume/delete task
  dm/ui/locales/en.json
  dm/ui/locales/zh.json
  dm/ui/package.json
  dm/ui/src/components/BatchImportTaskConfig/index.tsx
  dm/ui/src/components/CreateTaskConfig/MigrateRule.tsx
  dm/ui/src/components/CreateTaskConfig/TargetInfo.tsx
  dm/ui/src/components/CreateTaskConfig/index.tsx
  dm/ui/src/components/StartTaskWithListSelection/index.tsx
  dm/ui/src/layouts/SiderMenu.tsx
  dm/ui/src/models/index.ts
  dm/ui/src/models/task.ts
  dm/ui/src/models/taskConfig.ts
  dm/ui/src/pages/cluster/relay-log.tsx
  dm/ui/src/pages/migration/replication-detail.tsx
  dm/ui/src/pages/migration/task-config.tsx
  dm/ui/src/pages/migration/task.tsx
  dm/ui/yarn.lock
Labels: status/LGT1, status/can-merge, size/XXL, require-LGT1, release-note-none, area/dm

#4376 pkg(both): a separate library for DML row change
  dm/pkg/log/log.go
  dm/pkg/schema/tracker.go
  dm/pkg/utils/common.go
  dm/syncer/causality_test.go
  dm/syncer/compactor_test.go
  dm/syncer/dml_test.go
  dm/syncer/syncer.go
  pkg/sqlmodel/causality.go
  pkg/sqlmodel/causality_test.go
  pkg/sqlmodel/multivalue.go
  pkg/sqlmodel/multivalue_test.go
  pkg/sqlmodel/reduce.go
  pkg/sqlmodel/reduce_test.go
  pkg/sqlmodel/row_change.go
  pkg/sqlmodel/row_change_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm, area/ticdc

#4402 metrics(ticdc): add some log and metrics to owner and processorManage…
  cdc/owner/changefeed.go
  cdc/owner/metrics.go
  cdc/processor/manager.go
  cdc/processor/metrics.go
  cdc/processor/processor.go
  cdc/sink/sink.go
  pkg/orchestrator/interfaces.go
Labels: status/LGT2, status/can-merge, size/L, component/metrics-logging, release-note, area/ticdc

#4259 syncer(dm): enhance error handling about add inject at dml event
  dm/syncer/err-operator/operator.go
  dm/syncer/err-operator/operator_test.go
  dm/syncer/handle_error.go
  dm/syncer/syncer.go
  dm/tests/handle_error/run.sh
Labels: status/can-merge, size/L, release-note, area/dm

#4493 master(dm): add cluster id as unique identification of dm-cluster and optimize error message of code:30008
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/common/common.go
  dm/dm/master/election.go
  dm/dm/master/election_test.go
  dm/dm/master/openapi.go
  dm/dm/master/openapi_test.go
  dm/dm/master/server.go
  dm/errors.toml
  dm/openapi/gen.client.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/pkg/retry/strategy.go
  dm/pkg/terror/error_list.go
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm

#4474 etcd/client(ticdc): add retry operation for etcd transaction api (#4248)
  dm/pkg/etcdutil/etcdutil.go
  pkg/errorutil/ignore.go
  pkg/errorutil/ignore_test.go
  pkg/etcd/client.go
  pkg/etcd/client_test.go
  pkg/etcd/etcd.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, component/owner

#4535 .github(ticdc): request TiKV version
  .github/ISSUE_TEMPLATE/ticdc-bug-report.yml
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/ticdc

#4359 sink(cdc): kafka producer use default configuration.
  cdc/model/schema_storage.go
  cdc/owner/ddl_sink.go
  cdc/processor/processor.go
  cdc/sink/mq.go
  cdc/sink/producer/kafka/config.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  cdc/sink/sink.go
  cmd/kafka-consumer/main.go
  pkg/applier/redo.go
  pkg/util/ctx.go
  pkg/util/identity.go
Labels: component/sink, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, type/enhancement, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#4421 openapi(dm): add error_msg in task status
  dm/dm/master/openapi.go
  dm/dm/master/openapi_test.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#4494 api,owner(ticdc): return error when api fails
  Makefile
  cdc/api/open.go
  cdc/api/open_test.go
  cdc/api/owner.go
  cdc/api/status.go
  cdc/api/util.go
  cdc/capture/capture.go
  cdc/http_test.go
  cdc/owner/mock/owner_mock.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/owner/status_provider.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/server_test.go
  errors.toml
  pkg/errors/errors.go
  scripts/check-copyright.sh
Labels: type/bugfix, status/LGT2, status/can-merge, size/XXL, component/cli, release-note, component/owner

#4313 syncer(dm): use DML library
  dm/pkg/schema/tracker.go
  dm/syncer/causality.go
  dm/syncer/causality_test.go
  dm/syncer/checkpoint_flush_worker.go
  dm/syncer/compactor.go
  dm/syncer/compactor_test.go
  dm/syncer/ddl_test.go
  dm/syncer/dml.go
  dm/syncer/dml_test.go
  dm/syncer/dml_worker.go
  dm/syncer/dml_worker_test.go
  dm/syncer/job.go
  dm/syncer/job_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/tests/downstream_diff_index/run.sh
  dm/tests/shardddl1/run.sh
  pkg/sqlmodel/causality_test.go
  pkg/sqlmodel/reduce.go
  pkg/sqlmodel/reduce_test.go
  pkg/sqlmodel/row_change.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm, area/ticdc

#4558 tests(ticdc): fix canal_json_basic charset issue
  scripts/download-integration-test-binaries.sh
  tests/integration_tests/_utils/check_sync_diff
  tests/integration_tests/canal_json_basic/data/data.sql
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#4520 cdc/metrics: Integrate sarama producer metrics
  cdc/metrics.go
  cdc/owner/ddl_sink.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/metrics.go
  go.mod
  metrics/grafana/ticdc.json
  pkg/etcd/etcd_test.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, component/metrics-logging, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#4386 syncer(dm): fix startGTID is equal to endGTID
  dm/pkg/binlog/position.go
  dm/pkg/binlog/position_test.go
  dm/syncer/binlog_locations.go
  dm/syncer/binlog_locations_test.go
  dm/syncer/syncer.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#4536 docs/media(ticdc): update cdc architecture
  docs/media/cdc_architecture.svg
Labels: component/docs, status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none, area/ticdc, do-not-merge/needs-triage-completed

#4551 etcd (ticdc): fix a data race in unit test
  pkg/etcd/client_test.go
  pkg/etcd/etcd_test.go
Labels: component/test, status/LGT1, status/can-merge, needs-cherry-pick-release-5.0, size/M, require-LGT1, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc, needs-cherry-pick-release-5.4

#3975 checker(dm): support concurrent check
  dm/checker/check_test.go
  dm/checker/checker.go
  dm/pkg/checker/mysql_server.go
  dm/pkg/checker/privilege.go
  dm/pkg/checker/privilege_test.go
  dm/pkg/checker/table_structure.go
  dm/pkg/checker/table_structure_test.go
  dm/pkg/checker/utils.go
  dm/pkg/utils/db.go
  dm/pkg/utils/db_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#4479 validation(dm): manage validator life cycle
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/common/common.go
  dm/dm/config/subtask.go
  dm/dm/config/subtask_test.go
  dm/dm/config/task.go
  dm/dm/config/task_converters.go
  dm/dm/config/task_test.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/pb/dmworker.pb.go
  dm/dm/proto/dmworker.proto
  dm/dm/worker/server_test.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/source_worker_test.go
  dm/dm/worker/subtask.go
  dm/dm/worker/subtask_holder.go
  dm/dm/worker/subtask_test.go
  dm/dm/worker/task_checker_test.go
  dm/dm/worker/utils.go
  dm/dm/worker/utils_test.go
  dm/errors.toml
  dm/pkg/ha/ops.go
  dm/pkg/ha/ops_test.go
  dm/pkg/ha/source.go
  dm/pkg/ha/stage.go
  dm/pkg/ha/stage_test.go
  dm/pkg/ha/subtask.go
  dm/pkg/ha/subtask_test.go
  dm/pkg/terror/error_list.go
  dm/syncer/data_validator.go
  dm/syncer/streamer_controller.go
  dm/syncer/syncer.go
  dm/syncer/util.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#4556 test(dm): fix unsteable test TestRedirectRequestToLeader
  dm/dm/master/openapi_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none

#4566 test(dm): fix unsteable test TestFailToStartLeader
  dm/dm/master/election_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note, area/dm

#4485 syncer(dm): implement start-task --start-time
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/config/task.go
  dm/dm/config/task_cli_args.go
  dm/dm/master/server.go
  dm/dm/worker/source_worker.go
  dm/errors.toml
  dm/pkg/binlog/pos_finder.go
  dm/pkg/terror/error_list.go
  dm/syncer/checkpoint.go
  dm/syncer/syncer.go
  dm/tests/duplicate_event/run.sh
  dm/tests/start_task/conf/dm-worker2.toml
  dm/tests/start_task/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm

#4329 checker(dm): support optimistic checker
  dm/checker/check_test.go
  dm/checker/checker.go
  dm/dm/worker/subtask.go
  dm/pkg/checker/table_structure.go
  dm/pkg/checker/table_structure_test.go
  dm/tests/dmctl_basic/conf/diff_config2.toml
  dm/tests/dmctl_basic/conf/dm-task4.yaml
  dm/tests/dmctl_basic/data/db1.prepare.sql
  dm/tests/dmctl_basic/run.sh
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm

#4569 sink(ticdc): fix `Unknown system variable 'transaction_isolation'` for some mysql versions
  cdc/sink/mysql_params.go
  cdc/sink/mysql_params_test.go
  cdc/sink/mysql_test.go
  pkg/applier/redo_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note

#4517 cdc/sink: kafka sink integrate broker level metrics
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/metrics.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#4515 test(ticdc): migrate test-infra to testify for cdc/kv pkg (#2899)
  cdc/kv/client_test.go
  cdc/kv/grpc_pool_impl_test.go
  cdc/kv/main_test.go
  cdc/kv/matcher_test.go
  cdc/kv/region_worker_test.go
  cdc/kv/resolvedts_heap_test.go
  cdc/kv/store_op.go
  cdc/kv/token_region_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#4585 pkg/actor(ticdc): reduce metrics overhead
  metrics/grafana/ticdc.json
  pkg/actor/metrics.go
  pkg/actor/system.go
Labels: subject/performance, status/LGT2, status/can-merge, size/XXL, component/metrics-logging, release-note-none, area/ticdc

#4596 ticdc(sink): remove useless AppendResolvedEvent
  cdc/sink/codec/avro.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/codec/craft.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/maxwell.go
  cdc/sink/mq.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#4358 dm: new router compatible with regular expression
  dm/_utils/terror_gen/errors_release.txt
  dm/checker/checker.go
  dm/dm/config/subtask.go
  dm/errors.toml
  dm/loader/convert_data.go
  dm/loader/convert_data_test.go
  dm/loader/loader.go
  dm/pkg/router/router.go
  dm/pkg/router/router_test.go
  dm/pkg/terror/error_list.go
  dm/pkg/utils/common.go
  dm/pkg/utils/common_test.go
  dm/syncer/ddl_test.go
  dm/syncer/syncer.go
  dm/tests/all_mode/conf/regexpr-task.yaml
  dm/tests/all_mode/conf/regexpr_diff_config.toml
  dm/tests/all_mode/data/db1.regexpr.sql
  dm/tests/all_mode/data/db2.regexpr.sql
  dm/tests/all_mode/run.sh
Labels: status/LGT2, status/can-merge, first-time-contributor, size/XXL, release-note, area/dm

#4599 loader(dm): skip feature for nil etcd client
  dm/loader/util.go
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, area/dm

#4035 unit(dm): add Kill func for unit
  dm/dm/unit/unit.go
  dm/dm/worker/hub_test.go
  dm/dm/worker/join.go
  dm/dm/worker/server.go
  dm/dm/worker/server_test.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/source_worker_test.go
  dm/dm/worker/subtask.go
  dm/dm/worker/subtask_holder.go
  dm/dm/worker/subtask_test.go
  dm/dumpling/dumpling.go
  dm/loader/lightning.go
  dm/loader/loader.go
  dm/syncer/dml_worker.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/tests/_utils/ha_cases_lib.sh
  dm/tests/all_mode/run.sh
  dm/tests/checkpoint_transaction/conf/dm-worker1.toml
  dm/tests/checkpoint_transaction/run.sh
  dm/tests/expression_filter/run.sh
  dm/tests/full_mode/run.sh
  dm/tests/load_interrupt/run.sh
  dm/tests/new_relay/run.sh
  dm/tests/safe_mode/run.sh
  dm/tests/start_task/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/dm, needs-cherry-pick-release-5.4

#4606 cdc/sink: decouple opt out of statistics
  cdc/sink/black_hole.go
  cdc/sink/buffer_sink_test.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/sink.go
  cdc/sink/statistics.go
Labels: component/sink, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#4602 ticdc(mounter): remove unnecessary delete event decode logic
  cdc/entry/mounter.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#4557 dm: update to latest tidb to fix lightning loader
  cdc/entry/codec.go
  cdc/sink/codec/avro.go
  dm/pkg/schema/tracker.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#4568 dm: update hint msg
  dm/checker/cmd.go
  dm/dm/ctl/common/util.go
  dm/dm/master/server.go
  dm/dm/master/server_test.go
  dm/dm/pb/dmmaster.pb.go
  dm/dm/proto/dmmaster.proto
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#3812 checker(dm): change checker to more smart and gentle
  dm/checker/check_test.go
  dm/checker/checker.go
  dm/checker/cmd.go
  dm/dm/config/checking_item.go
  dm/dm/master/server.go
  dm/dm/worker/source_worker.go
  dm/pkg/checker/binlog.go
  dm/pkg/checker/binlog_test.go
  dm/pkg/checker/mysql_server.go
  dm/pkg/checker/table_structure.go
  dm/pkg/checker/table_structure_test.go
  dm/pkg/checker/utils.go
  dm/pkg/checker/utils_test.go
  dm/pkg/utils/db.go
  dm/pkg/utils/db_test.go
  dm/relay/relay.go
  dm/syncer/dbconn/upstream_db.go
  dm/syncer/dbconn/upstream_db_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#4628 integration(ticdc): temporary ignore `Error 1105` for default_value integration test
  tests/integration_tests/default_value/main.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#4608 dm-master(dm): use advertise address for ETCD client
  dm/dm/master/election_test.go
  dm/dm/master/etcd.go
  dm/dm/master/etcd_test.go
  dm/dm/master/openapi_test.go
  dm/dm/master/server.go
  dm/dm/master/server_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#4634 *(ticdc): enable exported function/variable comment check
  .golangci.yml
  cdc/api/open.go
  cdc/api/owner.go
  cdc/capture/capture.go
  cdc/processor/pipeline/actor_node.go
  cdc/processor/pipeline/actor_node_context.go
  cdc/processor/pipeline/actor_node_context_test.go
  cdc/processor/pipeline/actor_node_test.go
  cdc/processor/pipeline/cyclic_mark.go
  cdc/processor/pipeline/cyclic_mark_test.go
  cdc/processor/pipeline/system/system.go
  cdc/scheduler/agent_mock.go
  cdc/scheduler/agent_test.go
  cdc/scheduler/util/table_set.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/codec/craft/model.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/manager.go
  cdc/sink/mysql_params.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/metrics.go
  cdc/sink/producer/pulsar/producer.go
  cdc/sorter/memory/entry_sorter.go
  pkg/api/internal/rest/client.go
  pkg/api/internal/rest/request.go
  pkg/api/v1/changefeed.go
  pkg/config/messages.go
  pkg/config/sink.go
  pkg/context/context.go
  pkg/errorutil/ignore.go
  pkg/etcd/client.go
  pkg/etcd/client_test.go
  pkg/etcd/etcd.go
  pkg/p2p/mock_cluster.go
  pkg/pdtime/clock.go
  pkg/sqlmodel/reduce.go
  pkg/sqlmodel/row_change.go
  pkg/util/identity.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#4641 cdc/kafka: 5.3-manaual-cherry-pick-for-kafka-configuration
  cdc/model/schema_storage.go
  cdc/owner/ddl_sink.go
  cdc/processor/processor.go
  cdc/sink/mq.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  cdc/sink/sink.go
  cmd/kafka-consumer/main.go
  pkg/applier/redo.go
  pkg/util/ctx.go
  pkg/util/identity.go
Labels: status/LGT1, status/can-merge, size/XL, cherry-pick-approved, require-LGT1, release-note-none

#4638 tracker(dm): respect CHARSET when build TableInfo
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
  dm/tests/downstream_diff_index/data/db1.increment.sql
  dm/tests/downstream_diff_index/data/db1.prepare.sql
  dm/tests/downstream_diff_index/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#4140 pipeline(ticdc): Init table actor
  cdc/processor/pipeline/actor_node_context.go
  cdc/processor/pipeline/actor_node_context_test.go
  cdc/processor/pipeline/cyclic_mark.go
  cdc/processor/pipeline/cyclic_mark_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/processor/pipeline/system/system.go
  cdc/processor/pipeline/system/system_test.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/sink/manager.go
Labels: component/replica-model, status/LGT2, status/can-merge, size/XXL, release-note-none

#4630 sink(ticdc): remove useless op return value of AppendRowChangedEvent
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/codec_test.go
  cdc/sink/codec/craft.go
  cdc/sink/codec/craft_test.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/codec/maxwell.go
  cdc/sink/codec/maxwell_test.go
  cdc/sink/mq.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#4651 sorter(ticdc): fix the issue of using wrong values for writeCount and dataSize
  cdc/http_test.go
  cdc/sorter/unified/file_backend.go
  cdc/sorter/unified/file_backend_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#4653 sink/codec(ticdc): remove useless MixedBuild and Reset funcs
  cdc/sink/codec/avro.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/craft.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/codec/maxwell.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#4498 validation(dm): dmctl commands for validation
  dm/dm/ctl/ctl.go
  dm/dm/ctl/master/operate_validation.go
  dm/dm/ctl/master/query_validation.go
  dm/dm/ctl/master/start_stop_validation.go
  dm/dm/ctl/master/validation_cmd.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/server.go
  dm/dm/pb/dmmaster.pb.go
  dm/dm/proto/dmmaster.proto
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#4540 sink(ticdc): Add a topic expression when dispatching messages (Part I)
  cdc/sink/dispatcher/topic/expression.go
  cdc/sink/dispatcher/topic/expression_test.go
  errors.toml
  pkg/errors/errors.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#4659 cdc/kafka: remove skip-auto-create failpoint in kafka test
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  pkg/kafka/cluster_admin_client.go
  pkg/kafka/cluster_admin_client_mock_impl.go
  pkg/kafka/config.go
Labels: status/LGT2, status/can-merge, size/XXL, cherry-pick-approved, release-note-none

#4563 cdc: always ignore sequence tables
  cdc/api/validator.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
  cdc/owner/schema.go
  cdc/owner/schema_test.go
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/filter/filter_test.go
  tests/integration_tests/sequence/conf/diff_config.toml
  tests/integration_tests/sequence/conf/force_replicate.toml
  tests/integration_tests/sequence/data/test.sql
  tests/integration_tests/sequence/run.sh
Labels: type/bugfix, component/ddl, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc, needs-cherry-pick-release-5.4

#4621 .github: update the default label
  .github/ISSUE_TEMPLATE/feature-request.yml
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#4664 config(ticdc): make table actor batch size configurable
  cdc/processor/pipeline/actor_node_context.go
  cdc/processor/pipeline/actor_node_context_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  pkg/config/table_actor.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#4632 sorter/leveldb(ticdc): replace cleaner with delete range
  cdc/capture/capture.go
  cdc/processor/pipeline/sorter.go
  cdc/sorter/leveldb/cleaner.go
  cdc/sorter/leveldb/cleaner_test.go
  cdc/sorter/leveldb/compactor.go
  cdc/sorter/leveldb/compactor_test.go
  cdc/sorter/leveldb/leveldb.go
  cdc/sorter/leveldb/leveldb_test.go
  cdc/sorter/leveldb/message/task.go
  cdc/sorter/leveldb/message/task_test.go
  cdc/sorter/leveldb/system/system.go
  cdc/sorter/leveldb/system/system_test.go
  cdc/sorter/leveldb/table_sorter.go
  cdc/sorter/leveldb/table_sorter_test.go
  cdc/sorter/unified/backend_pool.go
  cdc/sorter/unified/backend_pool_test.go
  cdc/sorter/unified/sorter_test.go
  errors.toml
  go.mod
  go.sum
  metrics/grafana/ticdc.json
  pkg/actor/system.go
  pkg/actor/system_test.go
  pkg/cmd/server/server.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/db.go
  pkg/config/server_config.go
  pkg/config/server_config_test.go
  pkg/config/sorter.go
  pkg/db/db.go
  pkg/db/db_test.go
  pkg/db/leveldb.go
  pkg/db/metrics.go
  pkg/db/pebble.go
  pkg/errors/errors.go
  tests/utils/many_sorters_test/many_sorters.go
  tests/utils/sorter_stress_test/sorter_stress.go
Labels: subject/performance, status/LGT2, status/can-merge, size/XXL, component/sorter, release-note-none, type/enhancement

#4636 checker(dm): add auto increment id check in optimistic
  dm/pkg/checker/table_structure.go
  dm/pkg/checker/table_structure_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#4662 test(ticdc): revert canal json basic test changes
  cdc/sorter/leveldb/table_sorter_test.go
  tests/integration_tests/canal_json_basic/data/data.sql
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#4605 pkg/workerpool(cdc): fix race between handling error and unregistering handler
  pkg/workerpool/pool_impl.go
  pkg/workerpool/pool_test.go
Labels: status/ptal, type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc, needs-cherry-pick-release-5.4

#4673 remove skipAutoCreate failpoint from kafka test.
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  pkg/kafka/cluster_admin_client.go
  pkg/kafka/cluster_admin_client_mock_impl.go
  pkg/kafka/config.go
Labels: status/LGT1, status/can-merge, size/XXL, cherry-pick-approved, require-LGT1, release-note-none

#4633 sink(ticdc): add flush worker to flush row changed events
  cdc/sink/mq.go
  cdc/sink/mq_flush_worker.go
  cdc/sink/mq_flush_worker_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#4690 syncer(dm): support more about Syncer with nil etcdcli
  dm/syncer/syncer.go
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#4643 kv,cmd(ticdc): refinement about resolve lock
  cdc/kv/client.go
  cdc/kv/region_worker.go
  cdc/metrics.go
  metrics/grafana/ticdc.json
  pkg/cmd/cli/cli_unsafe.go
  pkg/cmd/cli/cli_unsafe_resolve_lock.go
  pkg/cmd/factory/factory.go
  pkg/cmd/factory/factory_impl.go
  pkg/txnutil/lock_resolver.go
  tests/integration_tests/cli/run.sh
Labels: component/kv-client, status/LGT2, status/can-merge, size/XXL, component/metrics-logging, component/cli, release-note-none, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#4361 dm: support s3 use dumpling and lightning
  Makefile
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/config/subtask.go
  dm/dm/config/subtask_test.go
  dm/dumpling/dumpling.go
  dm/errors.toml
  dm/loader/lightning.go
  dm/loader/loader.go
  dm/loader/util.go
  dm/pkg/dumpling/utils.go
  dm/pkg/dumpling/utils_test.go
  dm/pkg/storage/utils.go
  dm/pkg/storage/utils_test.go
  dm/pkg/terror/error_list.go
  dm/syncer/checkpoint.go
  dm/syncer/checkpoint_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/tests/README.md
  dm/tests/others_integration_1.txt
  dm/tests/s3_dumpling_lighting/conf/dm-master.toml
  dm/tests/s3_dumpling_lighting/conf/dm-task.yaml
  dm/tests/s3_dumpling_lighting/conf/dm-worker1.toml
  dm/tests/s3_dumpling_lighting/conf/dm-worker2.toml
  dm/tests/s3_dumpling_lighting/conf/source1.yaml
  dm/tests/s3_dumpling_lighting/conf/source2.yaml
  dm/tests/s3_dumpling_lighting/data/clean_data.sql
  dm/tests/s3_dumpling_lighting/data/db1.increment.sql
  dm/tests/s3_dumpling_lighting/data/db1.prepare.sql
  dm/tests/s3_dumpling_lighting/data/db2.increment.sql
  dm/tests/s3_dumpling_lighting/data/db2.prepare.sql
  dm/tests/s3_dumpling_lighting/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#4458 rfc(dm): add rfc doc of enhancing task manageability
  dm/docs/RFCS/20220124_enhance_task_manageability.md
  dm/docs/media/dm-new-task-lifecycle.png
  dm/docs/media/dm-old-task-lifecycle.png
  dm/docs/media/new-dmctl.svg
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#4663 sink(ticdc): Add a topic expression when dispatching messages (Part II)
  cdc/model/changefeed_test.go
  cdc/sink/dispatcher/default.go
  cdc/sink/dispatcher/dispatcher.go
  cdc/sink/dispatcher/event_router.go
  cdc/sink/dispatcher/event_router_test.go
  cdc/sink/dispatcher/partition/default.go
  cdc/sink/dispatcher/partition/default_test.go
  cdc/sink/dispatcher/partition/dispatcher.go
  cdc/sink/dispatcher/partition/index_value.go
  cdc/sink/dispatcher/partition/index_value_test.go
  cdc/sink/dispatcher/partition/table.go
  cdc/sink/dispatcher/partition/table_test.go
  cdc/sink/dispatcher/partition/ts.go
  cdc/sink/dispatcher/partition/ts_test.go
  cdc/sink/dispatcher/switcher_test.go
  cdc/sink/dispatcher/topic/dispatcher.go
  cdc/sink/dispatcher/topic/dispatcher_test.go
  cdc/sink/mq.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/util/changefeed.toml
  pkg/cmd/util/helper_test.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#4598 sink/kafka(ticdc): remove useless partition flush logic
  cdc/sink/mq.go
  cdc/sink/mq_flush_worker.go
  cdc/sink/mq_flush_worker_test.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
Labels: component/sink, status/LGT2, size/L, release-note-none, area/ticdc

#4702 cdc/metrics: fix kafka producer metrics in release-5.3 branch
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XL, cherry-pick-approved, release-note-none

#4686 sorter/leveldb(ticdc): separate write from table sorter
  cdc/processor/pipeline/sorter.go
  cdc/sorter/leveldb/message/task.go
  cdc/sorter/leveldb/system/system.go
  cdc/sorter/leveldb/system/system_test.go
  cdc/sorter/leveldb/table_sorter.go
  cdc/sorter/leveldb/table_sorter_test.go
  cdc/sorter/leveldb/writer.go
  cdc/sorter/leveldb/writer_test.go
  tests/integration_tests/_utils/start_tidb_cluster_impl
  tests/integration_tests/_utils/start_tls_tidb_cluster_impl
Labels: subject/performance, status/LGT2, status/can-merge, size/XL, component/sorter, release-note-none, area/ticdc

#4658 metrics: support multi-k8s in grafana dashboards
  metrics/grafana/ticdc.json
Labels: status/LGT1, status/can-merge, first-time-contributor, needs-cherry-pick-release-5.0, size/XL, component/metrics-logging, require-LGT1, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#4609 sink(ticdc): refact kafka sink initialization and add some test.
  cdc/sink/codec/avro.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/codec/codec_test.go
  cdc/sink/codec/config.go
  cdc/sink/codec/config_test.go
  cdc/sink/codec/craft.go
  cdc/sink/codec/craft_test.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/codec/maxwell.go
  cdc/sink/mq.go
  cdc/sink/mq_flush_worker_test.go
  cdc/sink/mq_test.go
  cdc/sink/producer/kafka/config.go
  cdc/sink/producer/kafka/config_test.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  errors.toml
  pkg/config/replica_config.go
  pkg/errors/errors.go
  pkg/kafka/cluster_admin_client_mock_impl.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#4496 metrics(dm): incr lag metric when syncer blocked
  dm/syncer/dml_worker.go
  dm/syncer/syncer.go
  dm/tests/metrics/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#4601 syncer(dm): support more task cli args
  dm/dm/config/task_cli_args.go
  dm/dm/config/task_cli_args_test.go
  dm/syncer/data_validator.go
  dm/syncer/dml_worker.go
  dm/syncer/safe_mode.go
  dm/syncer/safe_mode_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#4717 integration(test): fix sync_diff_inspector compatible error
  tests/integration_tests/cyclic_ab/conf/diff_config.toml
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none
