Repository pingcap/tiflow, pull requests merged in 2022-03, with the labels that each got.

#4728 test(ticdc): skip kafka test for integration test clustered_index temporarily
  tests/integration_tests/clustered_index/run.sh
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#4703 owner(cdc): fix two metrics problems
  cdc/capture/capture.go
  cdc/owner/changefeed.go
  cdc/owner/owner.go
  cdc/owner/scheduler_test.go
  cdc/scheduler/info_provider.go
  cdc/scheduler/info_provider_test.go
  cdc/scheduler/util/table_set.go
  cdc/scheduler/util/table_set_test.go
  pkg/pdtime/clock.go
  pkg/pdtime/clock_test.go
  pkg/txnutil/gc/gc_manager_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/L, release-note, needs-cherry-pick-release-5.4

#4726 dm(metrics): move dashboard from dm-ansible
  dm/metrics/DM-Monitor-Professional.json
  dm/metrics/DM-Monitor-Standard.json
Labels: status/LGT1, status/can-merge, size/XXL, require-LGT1, release-note-none, area/dm

#4741 cdc/codec: fix nil value in canal codec.
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/codec/canal_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-5.4

#4747 cdc: fix pd health API
  cdc/server.go
Labels: type/bugfix, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/ticdc

#4753 ut(ticdc): fix TestMySQLSinkFlushResolvedTs
  cdc/sink/mysql_test.go
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#4750 pkg/pipeline(ticdc): optimize CPU usage by withMessage
  pkg/pipeline/context.go
  pkg/pipeline/node.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, type/enhancement, area/ticdc

#4510 master(dm): support create a task in `stopped` state
  dm/chaos/cases/task.go
  dm/dm/ctl/master/stop_task.go
  dm/dm/master/bootstrap.go
  dm/dm/master/openapi_controller.go
  dm/dm/master/openapi_view.go
  dm/dm/master/openapi_view_test.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/master/server.go
  dm/dm/master/server_test.go
  dm/dm/pb/dmworker.pb.go
  dm/dm/proto/dmworker.proto
  dm/dm/worker/source_worker.go
  dm/dm/worker/source_worker_test.go
  dm/dm/worker/subtask.go
  dm/tests/openapi/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#4712 sorter/leveldb(ticdc): separate read from table sorter
  cdc/processor/pipeline/sorter.go
  cdc/sorter/leveldb/leveldb.go
  cdc/sorter/leveldb/leveldb_test.go
  cdc/sorter/leveldb/message/task.go
  cdc/sorter/leveldb/sorter.go
  cdc/sorter/leveldb/sorter_test.go
  cdc/sorter/leveldb/system/system.go
  cdc/sorter/leveldb/table_sorter.go
  cdc/sorter/leveldb/table_sorter_test.go
  cdc/sorter/sorter.go
Labels: subject/performance, status/LGT2, status/can-merge, size/XXL, component/sorter, release-note, area/ticdc

#4539 validator(dm): full mode validator, part 1
  dm/dm/config/task.go
  dm/pkg/binlog/position.go
  dm/pkg/conn/mockdb.go
  dm/syncer/data_validator.go
  dm/syncer/data_validator_test.go
  dm/syncer/syncer.go
  dm/syncer/validator_cond.go
  dm/syncer/validator_cond_test.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#4685 ha: add new etcd keys to support worker bound to multi-sources
  dm/dm/common/common.go
  dm/dm/common/common_test.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/master/scheduler/worker.go
  dm/dm/worker/server.go
  dm/pkg/ha/bound.go
  dm/pkg/ha/bound_test.go
  dm/pkg/ha/ops_test.go
  dm/pkg/ha/relay.go
  dm/pkg/ha/worker.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#4759 owner(ticdc): fix prometheus panic
  cdc/owner/metrics.go
  cdc/owner/owner.go
  cdc/processor/pipeline/metrics.go
  cdc/sorter/leveldb/metrics.go
  metrics/grafana/ticdc.json
Labels: type/bugfix, status/LGT1, status/can-merge, size/M, component/metrics-logging, require-LGT1, release-note-none, area/ticdc

#4768 scheduler(cdc): add ProcessorEpoch
  cdc/model/protocol.go
  cdc/model/protocol_test.go
  cdc/owner/scheduler.go
  cdc/processor/agent.go
  cdc/processor/agent_test.go
  cdc/scheduler/agent.go
  cdc/scheduler/agent_mock.go
  cdc/scheduler/agent_test.go
  cdc/scheduler/schedule_dispatcher.go
  cdc/scheduler/schedule_dispatcher_test.go
  errors.toml
  pkg/errors/errors.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note, needs-cherry-pick-release-5.4

#4297 Optimistic: dm-master support conflict DDL in optimistic mode.
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/master/shardddl/optimist.go
  dm/errors.toml
  dm/pkg/shardddl/optimism/column.go
  dm/pkg/shardddl/optimism/column_test.go
  dm/pkg/shardddl/optimism/lock.go
  dm/pkg/shardddl/optimism/lock_test.go
  dm/pkg/shardddl/optimism/operation.go
  dm/pkg/terror/error_list.go
  dm/syncer/optimist.go
  dm/tests/shardddl4_1/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#4751 cdc/test: integration test add default null for unsigned type
  tests/integration_tests/canal_json_basic/data/data.sql
  tests/integration_tests/clustered_index/data/test.sql
  tests/integration_tests/common_1/data/test.sql
  tests/integration_tests/common_1/data/test_v5.sql
  tests/integration_tests/ddl_attributes/data/prepare.sql
  tests/integration_tests/ddl_sequence/data/prepare.sql
  tests/integration_tests/new_ci_collation_without_old_value/data/test1.sql
  tests/integration_tests/row_format/data/step1.sql
  tests/integration_tests/tiflash/data/prepare.sql
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#4783 sorter/leveldb(ticdc): fix duplicate events
  cdc/sorter/leveldb/table_sorter.go
  cdc/sorter/leveldb/table_sorter_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/L, component/sorter, release-note-none, area/ticdc

#4738 tests(ticdc): add table actor integration test
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  tests/integration_tests/_utils/start_tidb_cluster_impl
  tests/integration_tests/bank_table_actor/conf/ticdc_table_actor.toml
  tests/integration_tests/bank_table_actor/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#4773 test: fix binlog 999999
  .github/workflows/dm_binlog_999999.yaml
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#4775 owner(cdc): clean up stale metrics
  cdc/owner/owner.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#4766 sorter(ticdc): rename files for better readability
  cdc/sorter/leveldb/reader.go
  cdc/sorter/leveldb/reader_test.go
  cdc/sorter/leveldb/sorter_test.go
Labels: status/LGT2, status/can-merge, size/L, component/sorter, release-note-none, area/ticdc

#4704 codec(ticdc): fix some avro encoding bugs
  cdc/entry/mounter.go
  cdc/model/sink.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/canal_test.go
Labels: type/bugfix, component/sink, status/LGT2, status/can-merge, size/L, release-note

#4781 scripts(ticdc): limit file width
  Makefile
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  scripts/add-leaktest.sh
  scripts/check-diff-line-width.sh
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/ticdc

#4791 metrics(dm): move alert rules from dm-ansible
  dm/metrics/alertmanager/dm_worker.rules.yml
  dm/metrics/grafana/DM-Monitor-Professional.json
  dm/metrics/grafana/DM-Monitor-Standard.json
Labels: status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none, area/dm

#4793 cdc/consumer: add some logs to help debug consumer.
  cdc/sink/mq.go
  cmd/kafka-consumer/main.go
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#4744 syncer(dm): fix log flood and performance when frequently call Snapshot
  dm/syncer/checkpoint.go
  dm/syncer/syncer.go
Labels: status/LGT2, status/can-merge, size/XS, release-note, area/dm, needs-cherry-pick-release-5.4

#4732 tracker(dm): write unistore files in working dir and clean it
  dm/pkg/schema/tracker.go
  dm/tests/expression_filter/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#4802 scripts(ticdc): refine check diff line
  scripts/check-diff-line-width.sh
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#4538 test(dm): add async checkpoint flush integration test
  dm/syncer/checkpoint_flush_worker.go
  dm/tests/async_checkpoint_flush/conf/diff_config.toml
  dm/tests/async_checkpoint_flush/conf/dm-master.toml
  dm/tests/async_checkpoint_flush/conf/dm-task.yaml
  dm/tests/async_checkpoint_flush/conf/dm-worker1.toml
  dm/tests/async_checkpoint_flush/conf/source1.yaml
  dm/tests/async_checkpoint_flush/data/db1.prepare.sql
  dm/tests/async_checkpoint_flush/run.sh
  dm/tests/others_integration_1.txt
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#4808 pkg/p2p(cdc,dataflow): Make it safe to write to the same topic concurrently
  pkg/p2p/client.go
  pkg/p2p/client_test.go
  pkg/p2p/internal/send_chan.go
  pkg/p2p/internal/send_chan_test.go
  pkg/p2p/server_client_integration_test.go
Labels: size/XL, release-note-none

#4815 dep(dm): update tidb
  dm/pkg/schema/tracker_test.go
  dm/syncer/error.go
  go.mod
  go.sum
  pkg/errorutil/ignore.go
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/dm, area/ticdc

#4817 test(master/scheduler): migrate test-infra to testify for master/scheduler pkg
  dm/dm/master/scheduler/latch_test.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/master/scheduler/worker_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#4767 validation(dm): full validation mode part 2
  dm/syncer/data_validator.go
  dm/syncer/data_validator_test.go
  dm/syncer/validate_worker.go
  dm/syncer/validate_worker_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#4830 unit_test: fix concurrency test cause etcd race
  dm/dm/master/shardddl/optimist_test.go
Labels: status/ptal, component/test, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/dm

#4826 OperateSchema: change default value of operate-schema --sync to true
  dm/dm/ctl/master/operate_schema.go
  dm/dm/ctl/master/source_table_schema.go
  dm/syncer/schema.go
  dm/tests/shardddl1/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note, area/dm, needs-update-docs

#4824 online-ddl: change default value of online-ddl to true
  dm/dm/config/task.go
  dm/tests/dmctl_basic/conf/get_task.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note, needs-update-docs

#4833 sorter/levelb(ticdc): fix data lose when reader mailbox is full
  cdc/sorter/leveldb/reader.go
  cdc/sorter/leveldb/reader_test.go
  cdc/sorter/leveldb/writer.go
  cdc/sorter/leveldb/writer_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/L, component/sorter, release-note-none, area/ticdc

#4771 ut(ticdc): add table actor ut
  cdc/processor/pipeline/actor_node.go
  cdc/processor/pipeline/actor_node_test.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  tests/integration_tests/canal_json_adapter_compatibility/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#4760 master/worker(dm): suppport update config when task not run
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/master/openapi_controller.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/master/scheduler/worker.go
  dm/dm/master/workerrpc/interface.go
  dm/dm/master/workerrpc/rawgrpc.go
  dm/dm/pb/dmworker.pb.go
  dm/dm/pbmock/dmmaster.go
  dm/dm/pbmock/dmworker.go
  dm/dm/proto/dmworker.proto
  dm/dm/worker/server.go
  dm/dm/worker/server_test.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/source_worker_test.go
  dm/dm/worker/subtask.go
  dm/dm/worker/task_checker_test.go
  dm/errors.toml
  dm/pkg/terror/error_list.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#4837 test: add a test for binary column
  tests/integration_tests/canal_json_adapter_compatibility/conf/diff_config.toml
  tests/integration_tests/canal_json_adapter_compatibility/data/data.sql
  tests/integration_tests/canal_json_adapter_compatibility/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-5.4

#4087 Optimistic: support unlock-ddl-lock for Optimistic Sharding DDL
  Makefile
  dm/dm/ctl/master/shard_ddl_lock.go
  dm/dm/ctl/master/unlock_ddl_lock.go
  dm/dm/master/server.go
  dm/dm/master/shardddl/optimist.go
  dm/dm/master/shardddl/optimist_test.go
  dm/dm/pb/dmmaster.pb.go
  dm/dm/pb/dmworker.pb.go
  dm/dm/proto/dmmaster.proto
  dm/dm/proto/dmworker.proto
  dm/pkg/shardddl/optimism/lock.go
  dm/pkg/shardddl/optimism/operation.go
  dm/pkg/shardddl/optimism/operation_test.go
  dm/pkg/shardddl/optimism/ops_test.go
  dm/syncer/optimist.go
  dm/syncer/shardddl/optimist_test.go
  dm/syncer/status.go
  dm/syncer/status_test.go
  dm/tests/handle_error/run.sh
  dm/tests/sequence_sharding_optimistic/run.sh
  dm/tests/shardddl1/run.sh
  dm/tests/shardddl1_1/run.sh
  dm/tests/shardddl2/run.sh
  dm/tests/shardddl2_1/run.sh
  dm/tests/shardddl3_1/run.sh
  dm/tests/shardddl4/run.sh
  dm/tests/shardddl4_1/run.sh
  scripts/check-copyright.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note, area/dm, needs-update-docs

#4820 test(ticdc): fix mysqlSink data race
  cdc/sink/mysql.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#4829 cdc/codec: fix converting not null column to avro nullable union
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note

#4836 *(ticdc): enable new scheduler by default
  cdc/owner/changefeed_test.go
  cdc/scheduler/info_provider.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
  tests/utils/cdc_state_checker/reactor.go
Labels: status/ptal, component/scheduler, status/LGT2, status/can-merge, size/M, release-note, area/ticdc

#4822 cdc/owner: add some logs to help debug puller / kvclient / lock resolver
  cdc/entry/mounter_test.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/kv/testing.go
  cdc/model/kv.go
  cdc/model/owner.go
  cdc/owner/changefeed.go
  cdc/owner/ddl_puller.go
  cdc/owner/ddl_sink.go
  cdc/owner/schema.go
  cdc/owner/schema_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/processor.go
  cdc/puller/puller.go
  cdc/sink/mysql.go
  pkg/cmd/cli/cli_unsafe_resolve_lock.go
  pkg/etcd/client.go
  pkg/etcd/etcd.go
  pkg/txnutil/lock_resolver.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XL, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#4810 sink(ticdc): add topic manager
  cdc/sink/dispatcher/event_router.go
  cdc/sink/dispatcher/event_router_test.go
  cdc/sink/manager/kafka/manager.go
  cdc/sink/manager/kafka/manager_test.go
  cdc/sink/manager/manager.go
  cdc/sink/manager/pulsar/manager.go
  cdc/sink/mq.go
  cdc/sink/producer/kafka/config.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  pkg/kafka/client.go
  pkg/kafka/client_mock_impl.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#4819 pkg,sorter,processor(ticdc): support graceful close
  cdc/processor/pipeline/actor_node_context_test.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/sorter/leveldb/compactor.go
  cdc/sorter/leveldb/compactor_test.go
  cdc/sorter/leveldb/leveldb.go
  cdc/sorter/leveldb/leveldb_test.go
  cdc/sorter/leveldb/reader.go
  cdc/sorter/leveldb/sorter.go
  cdc/sorter/leveldb/sorter_test.go
  cdc/sorter/leveldb/writer.go
  pkg/actor/actor.go
  pkg/actor/message/message.go
  pkg/actor/system.go
  pkg/actor/system_test.go
  pkg/errors/errors.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/XL, component/sorter, release-note-none, area/ticdc, needs-cherry-pick-release-5.4

#4626 tests(ticdc): migrate test-infra to testify for several pkg
  cdc/puller/frontier/frontier_test.go
  cdc/puller/frontier/heap_test.go
  cdc/puller/frontier/list_test.go
  cdc/puller/frontier/main_test.go
  cdc/puller/main_test.go
  cdc/puller/puller_test.go
  cdc/sorter/memory/entry_sorter_test.go
  cdc/sorter/memory/main_test.go
  cdc/sorter/unified/backend_pool_test.go
  cdc/sorter/unified/main_test.go
  cdc/sorter/unified/memory_backend_test.go
  cdc/sorter/unified/merger_test.go
  cdc/sorter/unified/sorter_test.go
Labels: component/test, status/LGT2, status/can-merge, size/XXL, release-note-none

#4827 p2p,processor(cdc): fix two unstable tests
  cdc/processor/agent_test.go
  pkg/p2p/client_test.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#4874 tracker(dm): add UT and fix uncleaned folder
  dm/pkg/schema/tracker_test.go
  pkg/sqlmodel/row_change.go
  pkg/sqlmodel/row_change_test.go
  pkg/sqlmodel/utils.go
  pkg/sqlmodel/utils_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#4754 validator(dm): fast mode validation
  dm/dm/worker/subtask.go
  dm/syncer/validate_worker.go
  dm/syncer/validate_worker_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#4786 DM: lightning checkpoint use s3 and change lightning tls dump path
  dm/dm/config/security.go
  dm/dm/config/subtask.go
  dm/dm/worker/subtask.go
  dm/loader/lightning.go
  dm/pkg/storage/utils.go
  dm/pkg/storage/utils_test.go
  dm/syncer/syncer.go
  dm/tests/s3_dumpling_lighting/conf/dm-task.yaml
  dm/tests/s3_dumpling_lighting/run.sh
  dm/tests/tls/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#4896 syncer/: set dml worker timeout to 5 minutes
  dm/syncer/dml_worker.go
  dm/syncer/syncer.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-2.0.5, needs-cherry-pick-release-2.0.6, needs-cherry-pick-release-2.0.7

#4831 sorter/leveldb(ticdc): fix system stop blocks forever
  cdc/processor/pipeline/sorter.go
  cdc/sorter/leveldb/leveldb.go
  cdc/sorter/leveldb/message/task.go
  cdc/sorter/leveldb/reader.go
  cdc/sorter/leveldb/sorter.go
  cdc/sorter/leveldb/sorter_test.go
  cdc/sorter/leveldb/system/system.go
  cdc/sorter/leveldb/system/system_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/L, component/sorter, release-note, area/ticdc, needs-cherry-pick-release-5.4

#4725 ui(dm): rewrite for spec v2
  .github/workflows/dm_ui_lint.yaml
  .gitignore
  dm/ui/locales/en.json
  dm/ui/locales/zh.json
  dm/ui/package.json
  dm/ui/public/mockServiceWorker.js
  dm/ui/src/components/BatchImportTaskConfig/index.tsx
  dm/ui/src/components/CreateOrUpdateSource/index.tsx
  dm/ui/src/components/CreateOrUpdateTask/BasicInfo.tsx
  dm/ui/src/components/CreateOrUpdateTask/CreateTaskEditorMode.tsx
  dm/ui/src/components/CreateOrUpdateTask/EventFilter.tsx
  dm/ui/src/components/CreateOrUpdateTask/MigrateRule.tsx
  dm/ui/src/components/CreateOrUpdateTask/SourceInfo.tsx
  dm/ui/src/components/CreateOrUpdateTask/TargetInfo.tsx
  dm/ui/src/components/CreateOrUpdateTask/index.tsx
  dm/ui/src/components/CreateOrUpdateTask/shared.tsx
  dm/ui/src/components/CreateTaskConfig/BasicInfo.tsx
  dm/ui/src/components/CreateTaskConfig/index.tsx
  dm/ui/src/components/SimpleTaskPanel/TaskUnitTag.tsx
  dm/ui/src/components/SimpleTaskPanel/index.tsx
  dm/ui/src/components/StartTaskWithListSelection/index.tsx
  dm/ui/src/layouts/SiderMenu.tsx
  dm/ui/src/mock.ts
  dm/ui/src/models/cluster.ts
  dm/ui/src/models/global.ts
  dm/ui/src/models/index.ts
  dm/ui/src/models/source.ts
  dm/ui/src/models/task.ts
  dm/ui/src/models/taskConfig.ts
  dm/ui/src/pages/cluster/member.tsx
  dm/ui/src/pages/index.tsx
  dm/ui/src/pages/migration/replication-detail.tsx
  dm/ui/src/pages/migration/source.tsx
  dm/ui/src/pages/migration/task-config.tsx
  dm/ui/src/pages/migration/task.tsx
  dm/ui/src/pages/migration/task/create.tsx
  dm/ui/src/pages/migration/task/edit.tsx
  dm/ui/src/pages/migration/task/index.tsx
  dm/ui/src/utils/isEmptyObject.ts
  dm/ui/vite.config.js
  dm/ui/yarn.lock
Labels: status/LGT1, status/can-merge, size/XXL, require-LGT1, release-note, area/dm

#4892 metrics(ticdc): add lag analyze panels
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XXL, component/metrics-logging, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc, needs-cherry-pick-release-5.4

#4884 sink(ticdc): add batch buffer for flush worker
  cdc/sink/mq_flush_worker.go
  cdc/sink/mq_flush_worker_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#4888 pkg,cdc: remove actor system stop errors
  cdc/capture/capture.go
  cdc/processor/pipeline/actor_node_context_test.go
  cdc/processor/pipeline/system/system.go
  cdc/processor/pipeline/system/system_test.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/sorter/leveldb/system/system.go
  pkg/actor/system.go
  pkg/actor/system_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#4890 config,cmd(ticdc): enable leveldb sorter by default
  cdc/processor/pipeline/sorter_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  tests/integration_tests/sorter/conf/ticdc_leveldb_sorter.toml
  tests/integration_tests/sorter/conf/ticdc_unified_sorter.toml
  tests/integration_tests/sorter/run.sh
Labels: component/configuration, status/LGT2, status/can-merge, size/S, component/sorter, release-note-none

#4814 cdc/sink: fix kafka consumer update globalResolvedTs too early, and adjust ddl sink processing logic.
  cdc/owner/changefeed.go
  cdc/owner/ddl_sink.go
  cdc/sink/mq.go
  cdc/sink/mysql.go
  cmd/kafka-consumer/main.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, type/enhancement

#4912 chore(dm): tweak build command for webui
  Makefile
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/dm

#4627 openapi(dm): adjust openapi for webui
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/config/source.yaml
  dm/dm/config/source_config.go
  dm/dm/config/source_converter.go
  dm/dm/config/source_converter_test.go
  dm/dm/config/task.go
  dm/dm/config/task_converters.go
  dm/dm/config/task_converters_test.go
  dm/dm/master/config.go
  dm/dm/master/openapi_controller.go
  dm/dm/master/openapi_controller_test.go
  dm/dm/master/openapi_view.go
  dm/dm/master/openapi_view_test.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/server.go
  dm/dm/master/server_test.go
  dm/dm/pb/dmworker.pb.go
  dm/dm/proto/dmworker.proto
  dm/dm/worker/server.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/subtask.go
  dm/errors.toml
  dm/openapi/gen.client.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/openapi/task.go
  dm/openapi/task_test.go
  dm/pkg/terror/error_list.go
  dm/syncer/schema.go
  dm/syncer/syncer.go
  dm/tests/dmctl_basic/conf/get_source1.yaml
  dm/tests/dmctl_basic/conf/get_source2.yaml
  dm/tests/new_relay/configs/sources/mysql-replica-01.yaml
  dm/tests/openapi/client/openapi_source_check
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/run.sh
  dm/ui/server.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#4893 test(master/shardddl): migrate test-infra to testify for master/shardddl pkg
  dm/dm/master/shardddl/info_test.go
  dm/dm/master/shardddl/optimist.go
  dm/dm/master/shardddl/optimist_test.go
  dm/dm/master/shardddl/pessimist_test.go
Labels: type/bugfix, component/test, status/LGT2, status/can-merge, severity/minor, size/XXL, release-note-none, area/dm

#4900 log(ddl(ticdc)): add more related logs for ddl on the critical path
  cdc/kv/client.go
  cdc/kv/region_worker.go
  cdc/owner/changefeed.go
  cdc/owner/ddl_puller.go
  cdc/owner/ddl_sink.go
  cdc/owner/schema.go
  cdc/puller/puller.go
  pkg/regionspan/region_range_lock.go
Labels: status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none

#4897 DM: adjust loader's dir to be add subdirectory
  dm/dm/config/subtask.go
  dm/dm/config/subtask_test.go
  dm/dm/config/task_converters.go
  dm/pkg/storage/utils.go
  dm/pkg/storage/utils_test.go
  dm/tests/s3_dumpling_lighting/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#4910 *(both): bump golang to 1.18
  .github/workflows/check_and_build.yaml
  .github/workflows/dm_binlog_999999.yaml
  .github/workflows/dm_chaos.yaml
  .github/workflows/dm_upstream_switch.yaml
  .github/workflows/ticdc_integration.yaml
  .github/workflows/ticdc_integration_cron.yaml
  .github/workflows/upgrade_dm_via_tiup.yaml
  Makefile
  cdc/capture/capture.go
  cdc/model/owner_test.go
  cdc/owner/owner_test.go
  cdc/owner/scheduler_v1.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/sink/mysql.go
  cdc/sink/mysql_syncpoint_store.go
  cdc/sorter/leveldb/reader_test.go
  cdc/sorter/leveldb/system/system.go
  cmd/kafka-consumer/main.go
  deployments/ticdc/docker/Dockerfile
  deployments/ticdc/docker/dev.Dockerfile
  deployments/ticdc/docker/integration-test.Dockerfile
  dm/Dockerfile
  dm/dm/master/scheduler/scheduler.go
  dm/loader/checkpoint.go
  dm/pkg/binlog/position_test.go
  dm/pkg/conn/baseconn_test.go
  dm/pkg/conn/basedb_test.go
  dm/pkg/gtid/gtid.go
  dm/pkg/retry/strategy.go
  dm/pkg/utils/db_test.go
  dm/pkg/utils/printer_test.go
  dm/syncer/checkpoint.go
  dm/syncer/compactor.go
  go.mod
  go.sum
  pkg/actor/system.go
  pkg/cmd/cli/cli_changefeed_cyclic_create_marktables.go
  pkg/p2p/server.go
  pkg/pipeline/node.go
  tests/integration_tests/tidb_mysql_test/build.sh
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#4916 fix(dm): some minor changes from checklist
  dm/ui/locales/en.json
  dm/ui/src/components/CreateOrUpdateTask/BasicInfo.tsx
  dm/ui/src/components/CreateOrUpdateTask/index.tsx
  dm/ui/src/models/index.ts
  dm/ui/src/pages/cluster/member.tsx
  dm/ui/src/pages/migration/replication-detail.tsx
  dm/ui/src/pages/migration/task/index.tsx
  dm/ui/src/uikit/message.tsx
Labels: size/L, release-note-none

#4883 dm/optimistic: make errors which isn't sync error handled by 'binlog skip' command
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/master/shardddl/optimist.go
  dm/errors.toml
  dm/pkg/shardddl/optimism/lock.go
  dm/pkg/shardddl/optimism/operation.go
  dm/pkg/terror/error_list.go
  dm/syncer/optimist.go
  dm/tests/shardddl2/run.sh
  dm/tests/shardddl2_1/run.sh
  dm/tests/shardddl3_1/run.sh
  dm/tests/shardddl4_1/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#4922 config(dm): fix convert when migrate rule is null
  dm/dm/config/task_converters.go
  dm/dm/config/task_converters_test.go
Labels: size/L, release-note, area/dm

#4931 fix(dm): tweak manual chunk to fix code load error
  dm/ui/package.json
  dm/ui/src/main.tsx
  dm/ui/vite.config.js
Labels: size/S, do-not-merge/release-note-label-needed

#4929 webui(dm): some mirror fix
  dm/dm/config/task_converters.go
  dm/dm/config/task_converters_test.go
  dm/ui/locales/en.json
  dm/ui/package.json
  dm/ui/src/components/CreateOrUpdateTask/BasicInfo.tsx
  dm/ui/src/components/CreateOrUpdateTask/index.tsx
  dm/ui/src/main.tsx
  dm/ui/src/models/index.ts
  dm/ui/src/pages/cluster/member.tsx
  dm/ui/src/pages/migration/replication-detail.tsx
  dm/ui/src/pages/migration/task/index.tsx
  dm/ui/src/uikit/message.tsx
  dm/ui/vite.config.js
Labels: status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none, area/dm

#4936 config(dm): fix can't downgrade config
  dm/dm/config/task.go
  dm/tests/new_relay/configs/tasks/test.yaml
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#4497 Optimsitic: refine optimstic create/drop table
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/master/shardddl/optimist.go
  dm/dm/master/shardddl/optimist_test.go
  dm/errors.toml
  dm/pkg/shardddl/optimism/keeper.go
  dm/pkg/shardddl/optimism/keeper_test.go
  dm/pkg/shardddl/optimism/lock.go
  dm/pkg/shardddl/optimism/lock_test.go
  dm/pkg/shardddl/optimism/ops.go
  dm/pkg/shardddl/optimism/ops_test.go
  dm/pkg/shardddl/optimism/table.go
  dm/pkg/shardddl/optimism/table_test.go
  dm/pkg/terror/error_list.go
  dm/syncer/optimist.go
  dm/syncer/shardddl/optimist.go
  dm/syncer/shardddl/optimist_test.go
  dm/syncer/syncer.go
  dm/tests/shardddl1_1/run.sh
  dm/tests/shardddl_optimistic/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#4911 router(dm): migrate router from dm to tidb-tools
  dm/checker/checker.go
  dm/dm/config/subtask.go
  dm/loader/convert_data.go
  dm/loader/convert_data_test.go
  dm/loader/loader.go
  dm/pkg/router/router.go
  dm/pkg/router/router_test.go
  dm/pkg/utils/common.go
  dm/pkg/utils/common_test.go
  dm/syncer/data_validator_test.go
  dm/syncer/ddl_test.go
  dm/syncer/syncer.go
  dm/tests/all_mode/conf/regexpr-task-lightning.yaml
  dm/tests/all_mode/run.sh
  go.mod
  go.sum
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#4933 cdc/deployment: add kafka consumer docker file
  deployments/ticdc/docker/kafka-consumer.Dockerfile
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#4944 docker(ticdc): fix broken sha256 check
  deployments/ticdc/docker/integration-test.Dockerfile
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#4925 docs(ticdc): add db sorter design doc
  docs/design/2022-03-16-ticdc-db-sorter.md
  docs/media/db-sorter-class.svg
  docs/media/db-sorter-sequence.svg
Labels: component/docs, status/LGT2, status/can-merge, size/XL, component/sorter, release-note-none, area/ticdc

#4847 cdc: support placement rules
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/sink/mysql_params.go
  cdc/sink/mysql_params_test.go
  cdc/sink/mysql_test.go
  go.mod
  go.sum
  pkg/applier/redo_test.go
  scripts/check-diff-line-width.sh
  tests/integration_tests/ddl_attributes/data/prepare.sql
  tests/integration_tests/ddl_attributes/run.sh
Labels: component/ddl, status/LGT2, status/can-merge, size/L, release-note, area/ticdc

#4947 DM: fix unit test's s3 url format to avoid errors when use `git secrets` check
  dm/pkg/storage/utils.go
  dm/pkg/storage/utils_test.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#4913 sink(ticdc): support multi topics
  cdc/sink/dispatcher/event_router.go
  cdc/sink/dispatcher/event_router_test.go
  cdc/sink/dispatcher/topic/dispatcher.go
  cdc/sink/dispatcher/topic/dispatcher_test.go
  cdc/sink/mq.go
  cdc/sink/mq_flush_worker.go
  cdc/sink/mq_flush_worker_test.go
  cdc/sink/mq_test.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/kafka_test.go
  cdc/sink/producer/mq_producer.go
  cdc/sink/producer/pulsar/producer.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#4950 scripts,owner(ticdc): correct line width limit
  cdc/owner/changefeed_test.go
  scripts/check-diff-line-width.sh
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#4955 kv/client(ticdc): remove dead code and fix some typos
  Makefile
  cdc/kv/client_bench_test.go
  cdc/kv/grpc_pool.go
  cdc/kv/grpc_pool_impl.go
  cdc/kv/matcher.go
  cdc/kv/testing.go
Labels: component/kv-client, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#4957 no need review just for trigger ci
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/sink/mysql_params.go
  cdc/sink/mysql_params_test.go
  cdc/sink/mysql_test.go
  deployments/ticdc/docker/integration-test.Dockerfile
  dm/dm/config/task_converters.go
  dm/dm/config/task_converters_test.go
  dm/dm/master/openapi_controller.go
  dm/openapi/gen.client.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/syncer/syncer.go
  dm/ui/yarn.lock
  docs/design/2022-03-16-ticdc-db-sorter.md
  docs/media/db-sorter-class.svg
  docs/media/db-sorter-sequence.svg
  go.mod
  go.sum
  pkg/applier/redo_test.go
  scripts/check-diff-line-width.sh
  tests/integration_tests/ddl_attributes/data/prepare.sql
  tests/integration_tests/ddl_attributes/run.sh
  tools/check/go.sum
Labels: size/XXL, release-note, area/dm, do-not-merge/needs-triage-completed

#4971 *: upgrade linters to support go 1.18
  .golangci.yml
  cdc/entry/mounter_test.go
  cdc/entry/schema_storage.go
  cdc/owner/changefeed_test.go
  cdc/owner/owner_test.go
  cdc/owner/schema.go
  cdc/processor/pipeline/actor_node_context.go
  cdc/processor/pipeline/actor_node_test.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/sink/dispatcher/event_router.go
  cdc/sink/mq.go
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/simple_mysql_tester.go
  cdc/sink/sink.go
  dm/chaos/cases/cases.go
  dm/chaos/cases/task.go
  dm/dm/config/task_converters.go
  dm/dm/ctl/common/util.go
  dm/dm/master/bootstrap.go
  dm/dm/master/etcd.go
  dm/dm/master/openapi_view_test.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/server.go
  dm/dm/master/shardddl/optimist.go
  dm/dm/master/shardddl/pessimist_test.go
  dm/dm/worker/source_worker_test.go
  dm/loader/db.go
  dm/openapi/gen.server.go
  dm/pkg/conn/baseconn.go
  dm/pkg/ha/load_task.go
  dm/pkg/ha/ops.go
  dm/pkg/ha/relay.go
  dm/pkg/ha/stage.go
  dm/pkg/retry/strategy.go
  dm/pkg/shardddl/optimism/info.go
  dm/pkg/shardddl/optimism/info_test.go
  dm/pkg/shardddl/optimism/lock_test.go
  dm/pkg/shardddl/optimism/operation.go
  dm/pkg/shardddl/optimism/table.go
  dm/pkg/shardddl/pessimism/operation.go
  dm/pkg/utils/db.go
  dm/relay/file_util_test.go
  dm/relay/relay_test.go
  dm/syncer/shardddl/optimist.go
  dm/syncer/sharding_group.go
  pkg/etcd/client.go
  pkg/p2p/server.go
  pkg/scheduler/table_number.go
  pkg/txnutil/lock_resolver.go
  pkg/version/check.go
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm, area/ticdc

#4968 tests(ticdc): add multi topic kafka test
  cdc/owner/changefeed.go
  cdc/sink/mq.go
  deployments/ticdc/docker-compose/docker-compose-kafka-integration.yml
  deployments/ticdc/docker-compose/docker-compose-mysql-integration.yml
  tests/integration_tests/multi_topics/conf/changefeed.toml
  tests/integration_tests/multi_topics/conf/diff_config.toml
  tests/integration_tests/multi_topics/data/data.sql
  tests/integration_tests/multi_topics/run.sh
Labels: component/test, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#4978 test: remove ansible in upgrade test
  .github/workflows/upgrade_dm_via_tiup.yaml
Labels: component/test, status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, area/dm

#4982 dm(ui): only request when hit check button
  dm/ui/src/components/CreateOrUpdateTask/index.tsx
  dm/ui/src/pages/migration/replication-detail.tsx
  dm/ui/src/pages/migration/source.tsx
Labels: size/L, release-note

#4969 [DNM] cdc/kafka: fix kafka metrics collector
  cdc/sink/producer/kafka/kafka.go
  cdc/sink/producer/kafka/metrics.go
  errors.toml
  pkg/errors/errors.go
Labels: type/bugfix, component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, needs-cherry-pick-release-6.0

#4977 config(dm): fix can't downgrade
  dm/dm/config/source_config.go
  dm/tests/new_relay/configs/sources/mysql-replica-01.yaml
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, area/dm, needs-cherry-pick-release-6.0

#4980 Makefile,tests(ticdc): adjust version and print version in tests
  Makefile
  tests/integration_tests/_utils/start_tidb_cluster_impl
  tests/integration_tests/_utils/start_tls_tidb_cluster_impl
Labels: component/test, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#4991 checker(dm): skip check for mariadb some version
  dm/pkg/checker/binlog.go
  dm/pkg/checker/binlog_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note, area/dm, needs-cherry-pick-release-6.0

#4997 dm: remove operations to offline cluster member
  dm/ui/locales/en.json
  dm/ui/locales/zh.json
  dm/ui/package.json
  dm/ui/src/pages/cluster/member.tsx
  dm/ui/yarn.lock
Labels: size/L, release-note

#4981 sink/producer(ticdc): migrate test-infra to testify for kafka producer
  cdc/sink/producer/kafka/config_test.go
  cdc/sink/producer/kafka/kafka_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#4942 scheduler(ticdc): Fix lost finish operation
  cdc/processor/agent.go
  cdc/processor/agent_test.go
  cdc/scheduler/agent.go
  cdc/scheduler/agent_mock.go
  cdc/scheduler/agent_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/messages.go
Labels: status/ptal, type/bugfix, status/LGT2, status/can-merge, size/XL, release-note, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4885 *(dm): move downstream table info logic into sqlmodel
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
  dm/syncer/dml.go
  pkg/sqlmodel/causality.go
  pkg/sqlmodel/causality_test.go
  pkg/sqlmodel/reduce.go
  pkg/sqlmodel/reduce_test.go
  pkg/sqlmodel/row_change.go
  pkg/sqlmodel/row_change_test.go
  pkg/sqlmodel/where_handle.go
  pkg/sqlmodel/where_handle_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#4996 sink/mq(cdc): Fix mq flush worker deadlock
  cdc/sink/mq.go
  cdc/sink/mq_flush_worker.go
  cdc/sink/mq_flush_worker_test.go
  errors.toml
  pkg/errors/errors.go
  tests/integration_tests/multi_topics/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc, needs-cherry-pick-release-6.0

#4877 master(dm): fix relay log may turn off introduced in v5.3.1
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
Labels: status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note, area/dm

#5014 dm: fix form data consistency issue
  dm/ui/src/components/CreateOrUpdateTask/MigrateRule.tsx
  dm/ui/src/components/CreateOrUpdateTask/index.tsx
Labels: size/S, release-note

#4881 validator(dm): checkpoint, persist pending/error row change data, and table status
  dm/dm/config/subtask.go
  dm/dm/config/task.go
  dm/dm/worker/subtask.go
  dm/pkg/cputil/table.go
  dm/syncer/checkpoint.go
  dm/syncer/checkpoint_test.go
  dm/syncer/data_validator.go
  dm/syncer/data_validator_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/syncer/validate_worker.go
  dm/syncer/validate_worker_test.go
  dm/syncer/validator_checkpoint.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
  dm/tests/start_task/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5004 task_checker(dm): refactor and expose an auto resume function
  dm/dm/worker/task_checker.go
  dm/dm/worker/task_checker_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#5011 scheduler(cdc), tests: fix TestNoFinishOperationBeforeSyncIsReceived and TestClientSendAnomalies
  cdc/processor/agent_test.go
  pkg/p2p/client_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-6.0

#4583 tests(ticdc): enable hibernate-regions-compatible by default
  tests/integration_tests/_utils/start_tidb_cluster_impl
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#4946 webui(dm): add many fix of webui
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/config/task_converters.go
  dm/dm/config/task_converters_test.go
  dm/dm/master/openapi_controller.go
  dm/errors.toml
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/pkg/terror/error_list.go
  dm/syncer/syncer.go
  dm/ui/locales/en.json
  dm/ui/locales/zh.json
  dm/ui/package.json
  dm/ui/src/components/CreateOrUpdateTask/MigrateRule.tsx
  dm/ui/src/components/CreateOrUpdateTask/index.tsx
  dm/ui/src/models/source.ts
  dm/ui/src/models/task.ts
  dm/ui/src/pages/cluster/member.tsx
  dm/ui/src/pages/migration/replication-detail.tsx
  dm/ui/src/pages/migration/source.tsx
  dm/ui/yarn.lock
  tools/check/go.sum
Labels: status/LGT1, status/can-merge, size/XXL, require-LGT1, release-note-none, area/dm, needs-cherry-pick-release-6.0

#5006 DM(syncer): fix lost lost dml under special sharding ddls
  dm/syncer/sharding_group.go
  dm/syncer/sharding_group_test.go
  dm/tests/handle_error/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-2.0.5, needs-cherry-pick-release-2.0.6, needs-cherry-pick-release-2.0.7, needs-cherry-pick-release-6.0

#5031 cdc/cli: hidden sorter parameters from server command.
  pkg/cmd/server/server.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, type/cherry-pick-for-release-6.0

#5041 cdc/cli: hidden sorter parameters from server command. (#5031)
  pkg/cmd/server/server.go
Labels: status/LGT1, status/can-merge, size/S, cherry-pick-approved, require-LGT1, release-note-none

#5040 owner,scheduler(ticdc): fix some typos and add log
  cdc/owner/feed_state_manager.go
  cdc/owner/owner.go
  cdc/scheduler/schedule_dispatcher.go
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/ticdc, component/owner

#4998 owner(cdc): clean up metrics when owner resigns
  cdc/owner/owner.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/XS, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4850 verification(ticdc): e2e verification, checksum
  cdc/verification/checker.go
  cdc/verification/checker_test.go
  cdc/verification/mock_checkSumChecker.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc, type/feature, component/verification

#4949 *(dm): support MySQL 8.0 collations
  dm/dm/master/election_test.go
  dm/dm/master/shardddl/pessimist_test.go
  dm/pkg/schema/tracker.go
  dm/tests/all_mode/data/db2.prepare.sql
  dm/tests/new_collation_off/conf/diff_config.toml
  dm/tests/new_collation_off/conf/dm-master.toml
  dm/tests/new_collation_off/conf/dm-task.yaml
  dm/tests/new_collation_off/conf/dm-worker1.toml
  dm/tests/new_collation_off/conf/source2.yaml
  dm/tests/new_collation_off/conf/tidb-config.toml
  dm/tests/new_collation_off/data/db2.increment.sql
  dm/tests/new_collation_off/data/db2.prepare.sql
  dm/tests/new_collation_off/run.sh
  dm/tests/others_integration_2.txt
  go.mod
  go.sum
  pkg/leakutil/leak_helper.go
  pkg/p2p/server_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm

#5016 DM(syncer): fix syncer may be dead cycle when access match inject ddl repeatedly by special ddls
  dm/syncer/err-operator/operator.go
  dm/tests/handle_error/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm, needs-cherry-pick-release-6.0

#5050 tools(both): make gocov compatible with go1.18
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#5025 validator(dm): checkpoint unit-test & fixing some todos
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/config/task.go
  dm/dm/master/server.go
  dm/dm/master/server_test.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/subtask.go
  dm/errors.toml
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
  dm/pkg/terror/error_list.go
  dm/syncer/checkpoint.go
  dm/syncer/data_validator.go
  dm/syncer/data_validator_test.go
  dm/syncer/syncer.go
  dm/syncer/validate_worker.go
  dm/syncer/validate_worker_test.go
  dm/syncer/validator_checkpoint.go
  dm/syncer/validator_checkpoint_test.go
  dm/syncer/validator_cond_test.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
  dm/tests/sequence_sharding_optimistic/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5003 mounter(ticdc): remove mounter worker
  cdc/entry/metrics.go
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/model/mounter.go
  cdc/model/mounter_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/processor.go
  docs/data-flow.dot
  docs/data-flow.svg
  metrics/grafana/ticdc.json
Labels: subject/performance, status/LGT2, status/can-merge, size/XXL, component/sorter, release-note-none, area/ticdc, component/mounter

#5060 metrics(ticdc): split mysql sink row, and refine sink metrics.
  cdc/sink/black_hole.go
  cdc/sink/buffer_sink.go
  cdc/sink/buffer_sink_test.go
  cdc/sink/metrics.go
  cdc/sink/mq.go
  cdc/sink/mq_flush_worker_test.go
  cdc/sink/mysql.go
  cdc/sink/mysql_test.go
  cdc/sink/statistics.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XXL, component/metrics-logging, release-note-none, type/enhancement

#5068 schema(cdc): fix DML construct error caused by 'rename tables' DDL
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/processor/processor.go
  tests/integration_tests/rename_tables/conf/diff_config.toml
  tests/integration_tests/rename_tables/data/test.sql
  tests/integration_tests/rename_tables/run.sh
Labels: component/ddl, status/LGT2, status/can-merge, size/L, release-note, area/ticdc, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4999 pipeline(ticdc): enable table actor by default
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
Labels: status/LGT2, status/can-merge, size/S, release-note, area/ticdc

#4973 pkg/actor(ticdc): generic actor message
  cdc/processor/pipeline/actor_node.go
  cdc/processor/pipeline/actor_node_context.go
  cdc/processor/pipeline/actor_node_context_test.go
  cdc/processor/pipeline/actor_node_test.go
  cdc/processor/pipeline/cyclic_mark.go
  cdc/processor/pipeline/cyclic_mark_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/processor/pipeline/system/system.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/sorter/leveldb/compactor.go
  cdc/sorter/leveldb/compactor_test.go
  cdc/sorter/leveldb/leveldb.go
  cdc/sorter/leveldb/leveldb_test.go
  cdc/sorter/leveldb/reader.go
  cdc/sorter/leveldb/reader_test.go
  cdc/sorter/leveldb/sorter.go
  cdc/sorter/leveldb/sorter_test.go
  cdc/sorter/leveldb/system/system.go
  cdc/sorter/leveldb/system/system_test.go
  cdc/sorter/leveldb/writer.go
  cdc/sorter/leveldb/writer_test.go
  pkg/actor/actor.go
  pkg/actor/actor_test.go
  pkg/actor/doc.go
  pkg/actor/message/message.go
  pkg/actor/message/message_test.go
  pkg/actor/system.go
  pkg/actor/system_test.go
  pkg/actor/testing.go
  pkg/pipeline/context.go
  pkg/pipeline/message/message.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/runner.go
  pkg/pipeline/test.go
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#4928 validator(dm): impl validation status command
  dm/dm/ctl/master/query_validation.go
  dm/dm/master/server.go
  dm/dm/master/server_test.go
  dm/dm/master/workerrpc/interface.go
  dm/dm/master/workerrpc/rawgrpc.go
  dm/dm/pb/dmmaster.pb.go
  dm/dm/pb/dmworker.pb.go
  dm/dm/pbmock/dmworker.go
  dm/dm/proto/dmmaster.proto
  dm/dm/proto/dmworker.proto
  dm/dm/worker/server.go
  dm/dm/worker/server_test.go
  dm/dm/worker/source_worker_test.go
  dm/dm/worker/status.go
  dm/dm/worker/subtask.go
  dm/syncer/data_validator.go
  dm/syncer/data_validator_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm
