Repository pingcap/tiflow, pull requests merged in 2022-06, with the labels that each got.

#5680 cdc: prune dead code
  cdc/entry/schema_storage_test.go
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
  cdc/puller/mock_puller.go
  cdc/puller/mock_puller_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#5678 syncer(dm): update memory cache after FlushPointWithTableInfo
  dm/syncer/checkpoint.go
  dm/tests/_utils/check_process_exit
  dm/tests/sequence_sharding_optimistic/run.sh
  dm/tests/start_task/run.sh
  dm/tests/tracker_ignored_ddl/run.sh
Labels: status/LGT1, size/M, do-not-merge/cherry-pick-not-approved, release-note

#5679 pkg(engine): add version in ldflags and welcome log
  .github/ISSUE_TEMPLATE/engine-bug-report.yml
  Makefile
  engine/cmd/executor/main.go
  engine/cmd/master/main.go
  engine/executor/config.go
  engine/pkg/version/version.go
  engine/pkg/version/version_test.go
  engine/servermaster/config.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5591 project[engine]: Framework support multi projects
  engine/chaos/cases/case_fake_job.go
  engine/client/task_dispatcher.go
  engine/ctl/cmd.go
  engine/enginepb/executor.pb.go
  engine/enginepb/master.pb.go
  engine/enginepb/projects.pb.go
  engine/executor/server.go
  engine/lib/master.go
  engine/lib/worker.go
  engine/pkg/context/context.go
  engine/pkg/errors/errors.go
  engine/pkg/meta/kvclient/client.go
  engine/pkg/orm/client.go
  engine/pkg/promutil/implement_test.go
  engine/pkg/promutil/test/multiprojects_metric_scences.go
  engine/pkg/promutil/util_inner.go
  engine/pkg/promutil/util_inner_test.go
  engine/pkg/tenant/tenant.go
  engine/proto/executor.proto
  engine/proto/master.proto
  engine/proto/projects.proto
  engine/proto/test.proto
  engine/servermaster/jobmanager.go
  engine/servermaster/server.go
  engine/test/e2e/e2e_node_chaos_test.go
  engine/test/e2e/e2e_test_cli.go
  engine/test/e2e/e2e_worker_exit_test.go
  errors.toml
Labels: status/ptal, status/LGT1, status/can-merge, size/XXL, require-LGT1, release-note-none, area/engine

#5703 fb/latency(cdc): add more unit test to agent
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/agent_bench_test.go
  cdc/scheduler/internal/tp/agent_test.go
  cdc/scheduler/internal/tp/coordinator_test.go
Labels: size/XL, release-note-none

#5709 tp: support per-table checkpoint
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/agent_test.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/coordinator_test.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_manager_test.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/replication_set_test.go
  cdc/scheduler/internal/tp/schedulepb/table_schedule.pb.go
  proto/table_schedule.proto
Labels: component/scheduler, status/LGT1, size/XXL, release-note-none, area/ticdc

#5440 Table property filter
  cdc/sorter/encoding/key.go
  cdc/sorter/leveldb/leveldb.go
  cdc/sorter/leveldb/message/task.go
  cdc/sorter/leveldb/reader.go
  cdc/sorter/leveldb/reader_test.go
  engine/cmd/demoserver/kvdatamake.go
  pkg/db/db.go
  pkg/db/db_test.go
  pkg/db/leveldb.go
  pkg/db/pebble.go
  pkg/db/pebble_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#5701 test(engine): remove promutil/test/go.mod to avoid gosetup error
  engine/pkg/promutil/test/go.mod
  engine/pkg/promutil/test/go.sum
  engine/pkg/promutil/test/multiprojects_metric_scences.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5666 capture (ticdc): fix http status panic
  cdc/api/status/status.go
  cdc/api/v1/api.go
  cdc/capture/capture.go
  cdc/capture/capture_test.go
  cdc/server.go
  cdc/server_test.go
  errors.toml
  pkg/errors/errors.go
  pkg/etcd/etcd.go
Labels: status/LGT2, status/can-merge, type/cherry-pick-for-release-5.0, size/M, type/cherry-pick-for-release-5.1, release-note, type/cherry-pick-for-release-5.2, type/cherry-pick-for-release-5.3, type/cherry-pick-for-release-5.4, type/cherry-pick-for-release-6.0

#5710 cdc: integrate two phase scheduler
  cdc/owner/changefeed.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/capture_manager_test.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/coordinator_test.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_manager_test.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/replication_set_test.go
  cdc/scheduler/internal/tp/scheduler_balance.go
  cdc/scheduler/internal/tp/scheduler_balance_test.go
  cdc/scheduler/internal/tp/transport.go
  cdc/scheduler/internal/tp/transport_test.go
  cdc/scheduler/rexport.go
Labels: component/scheduler, status/LGT1, size/XL, release-note-none, area/ticdc

#5646 servermaster,executor(engine): Enable local file resource GC
  engine/executor/config.go
  engine/executor/config_test.go
  engine/executor/server.go
  engine/lib/statusutil/writer.go
  engine/pkg/errors/errors.go
  engine/pkg/externalresource/broker/broker.go
  engine/pkg/externalresource/broker/broker_test.go
  engine/pkg/externalresource/broker/file_manager.go
  engine/pkg/externalresource/broker/file_manager_test.go
  engine/pkg/externalresource/broker/local_broker.go
  engine/pkg/externalresource/integration_test/mock_cluster.go
  engine/pkg/externalresource/storagecfg/config.go
  engine/servermaster/server.go
  errors.toml
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5669 Dockerfile(engine): simplify docker image size
  engine/Dockerfile
  engine/sample/1m1e.yaml
  engine/sample/1m3e.yaml
  engine/sample/3m3e.yaml
  engine/sample/client.sh
  engine/sample/demo.yaml
Labels: status/ptal, status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/engine

#5711 tp(cdc): support manual move table and rebalance
  cdc/processor/pipeline/table.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/agent_test.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/coordinator_test.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/scheduler.go
  cdc/scheduler/internal/tp/scheduler_balance.go
  cdc/scheduler/internal/tp/scheduler_balance_test.go
  cdc/scheduler/internal/tp/scheduler_move_table.go
  cdc/scheduler/internal/tp/scheduler_move_table_test.go
  cdc/scheduler/internal/tp/scheduler_rebalance.go
  cdc/scheduler/internal/tp/scheduler_rebalance_test.go
Labels: status/LGT1, size/XXL, release-note-none, do-not-merge/needs-linked-issue

#5696 executor(engine): support openapi registration for job master
  engine/cmd/executor/main.go
  engine/executor/http.go
  engine/executor/openapi.go
  engine/executor/openapi_test.go
  engine/executor/server.go
  engine/executor/worker/task_runner.go
  engine/executor/worker/task_runner_test.go
  engine/jobmaster/cvsjob/cvs_job_master.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/lib/base_jobmaster.go
  engine/lib/base_jobmaster_test.go
  engine/lib/fake/fake_master.go
  engine/lib/model/typedefs.go
  engine/pkg/promutil/util.go
  engine/pkg/promutil/util_inner.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#5705 externalresource(engine): Add retry for GCRunner
  engine/pkg/externalresource/manager/gc_runner.go
  engine/pkg/externalresource/manager/gc_runner_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5693 ci(engine): fix duplicated checkpoint in fake job
  .github/workflows/dataflow_engine_chaos.yaml
  engine/lib/fake/fake_master.go
Labels: status/ptal, status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/engine

#5717 engine(proto): change job_id to string and remove job_id_str
  engine/ctl/cmd.go
  engine/enginepb/master.pb.go
  engine/proto/master.proto
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  engine/test/e2e/e2e_test.go
  engine/test/e2e/e2e_test_cli.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#5724 engine: fix panic in pebble db
  cdc/sorter/leveldb/compactor_test.go
  cdc/sorter/leveldb/leveldb_test.go
  cdc/sorter/leveldb/reader_test.go
  cdc/sorter/leveldb/system/system.go
  engine/cmd/demoserver/kvdatamake.go
  pkg/db/db_test.go
  pkg/db/pebble.go
  pkg/db/pebble_test.go
Labels: status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none, area/ticdc

#5008 test: add create table case for upgrade test
  dm/tests/tiup/lib.sh
  dm/tests/tiup/upgrade-from-v2.sh
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#5725 pipeline(ticdc): disable table actor
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/processor.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/mysql_worker.go
  cdc/sink/mysql/mysql_worker_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
Labels: status/LGT2, status/can-merge, size/XL, cherry-pick-approved, release-note-none

#5715 sink/mq(ticdc): gracefully close chann
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_flush_worker.go
Labels: component/sink, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc, needs-cherry-pick-release-6.1

#5263 schema(cdc): log err when retry to get snapshot
  cdc/entry/schema_storage.go
Labels: status/LGT2, status/can-merge, first-time-contributor, size/XS, release-note-none

#5697 engine: implement MessageAgent
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/message_agent.go
  engine/jobmaster/dm/message_agent_test.go
  engine/jobmaster/dm/task_manager.go
  engine/jobmaster/dm/task_manager_test.go
  engine/jobmaster/dm/worker_manager.go
  engine/jobmaster/dm/worker_manager_test.go
  engine/jobmaster/example/worker_impl.go
  engine/lib/base_jobmaster.go
  engine/lib/worker.go
  engine/pkg/dm/message_agent.go
  engine/pkg/dm/message_agent_test.go
  engine/pkg/dm/message_pair.go
  engine/pkg/dm/message_pair_test.go
  engine/pkg/dm/mock_message_agent.go
  engine/pkg/dm/topic.go
  engine/pkg/dm/topic_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5716 executor(engine): factor out MetastoreManager
  Makefile
  engine/executor/server.go
  engine/executor/server/metastore.go
  engine/executor/server/metastore_test.go
  engine/executor/server/mocks/metastore_mock.go
  engine/executor/server_test.go
  engine/pkg/meta/kvclient/mock/client_mock.go
  scripts/check-copyright.sh
  scripts/generate-engine-mock.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5752 cli version print warn log if cant connect to server
  cdc/api/v2/api.go
  pkg/api/v2/unsafe.go
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/cmd/version/version.go
Labels: size/M, release-note-none

#5722 cli(ticdc): update cli changfeed-statistics by calling openapi without manipulating etcd
  pkg/cmd/cli/cli_changefeed_statistics.go
Labels: status/LGT2, status/can-merge, size/L, release-note

#5735 chaos(engine): use kind to setup k8s cluster in chaos test
  .github/workflows/dataflow_engine_chaos.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#5747 chaos(dm): fix coredns problem
  .github/workflows/dm_chaos.yaml
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#5728 latency(cdc): 2 phase scheduling processor bug fix
  cdc/processor/manager_test.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/transport.go
Labels: status/LGT1, size/XXL, release-note-none

#5751 tests(ticdc): change cdc cron mq integrations to pull triggered
  .github/workflows/ticdc_integration.yaml
  .github/workflows/ticdc_integration_cron.yaml
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#5763 api (ticdc): add create changefeed api v2
  cdc/api/util.go
  cdc/api/v1/api.go
  cdc/api/v1/validator.go
  cdc/api/v1/validator_test.go
  cdc/api/v2/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  cdc/api/v2/validator.go
  cdc/entry/validator.go
  cdc/model/changefeed.go
  cdc/sink/mq/mq.go
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/config/filter.go
  pkg/config/replica_config.go
  pkg/config/sink.go
Labels: size/XXL, release-note, area/ticdc, do-not-merge/needs-linked-issue, api/v2

#5755 dm: fix the problem that ssl-*-bytes are printed in log
  dm/dm/pb/hide_password.go
  dm/pkg/utils/util.go
  dm/pkg/utils/util_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#5767 cli(cdc): tso use pd client
  cdc/api/status/status.go
  cdc/api/v1/validator.go
  cdc/api/v2/unsafe.go
  cdc/api/v2/validator.go
  cdc/capture/capture.go
  cdc/capture/capture_test.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner_test.go
  cdc/processor/manager_test.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/base/processor_agent.go
  cdc/scheduler/internal/base/processor_agent_test.go
  cdc/server.go
  cdc/server_test.go
  pkg/cmd/cli/cli_capture_list.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_tso_query.go
  pkg/cmd/cli/cli_unsafe_delete_service_gc_safepoint.go
  pkg/cmd/cli/cli_unsafe_reset.go
  pkg/cmd/factory/factory_impl.go
  pkg/cmd/server/server.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
  pkg/context/context.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/etcdkey.go
  pkg/etcd/etcdkey_test.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/reactor_state.go
  pkg/orchestrator/reactor_state_test.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_manager_test.go
  pkg/txnutil/gc/gc_service.go
  pkg/txnutil/gc/gc_service_test.go
  pkg/upstream/manager.go
  pkg/upstream/upstream.go
  pkg/version/version.go
  tests/integration_tests/capture_session_done_during_task/run.sh
  tests/integration_tests/capture_suicide_while_balance_table/run.sh
  tests/integration_tests/gc_safepoint/run.sh
  tests/integration_tests/move_table/main.go
  tests/utils/cdc_state_checker/cdc_monitor.go
  tests/utils/cdc_state_checker/state.go
Labels: size/XXL, release-note

#5446 [WIP-DNM] ectd (ticdc): add etcd meta data magration logic
  cdc/capture/capture.go
  cdc/capture/capture_test.go
  cdc/processor/processor_test.go
  cdc/server.go
  cdc/server_test.go
  errors.toml
  pkg/cmd/factory/factory.go
  pkg/errors/errors.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/etcdkey.go
  pkg/etcd/etcdkey_test.go
  pkg/etcd/migrate.go
  pkg/etcd/migrate_test.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_bank_test.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/reactor_state_test.go
  tests/utils/cdc_state_checker/state.go
Labels: size/XXL, do-not-merge/work-in-progress, release-note, do-not-merge/needs-linked-issue

#5762 servermaster/election(engine): fix Election goroutine leaks
  engine/servermaster/campaign_test.go
  engine/servermaster/cluster/election.go
  engine/servermaster/cluster/election_test.go
  engine/servermaster/server.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5753 election(engine): fix campaign keeps failing when lease is timeout
  engine/servermaster/campaign.go
  engine/servermaster/campaign_test.go
  engine/servermaster/cluster/election.go
  engine/servermaster/cluster/session.go
  engine/servermaster/cluster/session_test.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
Labels: status/ptal, type/bugfix, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5704 syncer/binlogstream (dm): split this package from syncer
  dm/syncer/binlogstream/streamer_controller.go
  dm/syncer/binlogstream/streamer_controller_test.go
  dm/syncer/data_validator.go
  dm/syncer/data_validator_test.go
  dm/syncer/error.go
  dm/syncer/error_test.go
  dm/syncer/relay.go
  dm/syncer/status.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/syncer/util.go
  dm/syncer/util_test.go
  dm/tests/drop_column_with_index/run.sh
  dm/tests/incremental_mode/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#5742 pkg: refactor the signature of CDCEtcdClient get owner id method
  cdc/capture/capture.go
  cdc/scheduler/internal/base/processor_agent.go
  pkg/cmd/cli/cli_capture_list.go
  pkg/etcd/etcd.go
  tests/integration_tests/move_table/main.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#5661 log(engine): support multi-projects/tasks log
  engine/lib/model/typedefs.go
  engine/pkg/logutil/log.go
  engine/pkg/logutil/log_test.go
  go.mod
  go.sum
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5772 checker(dm): fix deadlock when check-task/start-task
  dm/pkg/checker/table_structure.go
  dm/pkg/checker/table_structure_test.go
  dm/tests/check_task/conf/dm-master.toml
  dm/tests/check_task/conf/dm-worker1.toml
  dm/tests/check_task/conf/source1.yaml
  dm/tests/check_task/conf/task-noshard.yaml
  dm/tests/check_task/conf/task-sharding.yaml
  dm/tests/check_task/data/db1.prepare.sql
  dm/tests/check_task/run.sh
  dm/tests/others_integration_1.txt
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#5774 checker(dm): fix deadlock when check-task/start-task (#5772)
  dm/pkg/checker/table_structure.go
  dm/pkg/checker/table_structure_test.go
  dm/tests/check_task/conf/dm-master.toml
  dm/tests/check_task/conf/dm-worker1.toml
  dm/tests/check_task/conf/source1.yaml
  dm/tests/check_task/conf/task-noshard.yaml
  dm/tests/check_task/conf/task-sharding.yaml
  dm/tests/check_task/data/db1.prepare.sql
  dm/tests/check_task/run.sh
  dm/tests/others_integration_1.txt
Labels: status/LGT1, status/can-merge, size/L, cherry-pick-approved, require-LGT1, release-note

#5503 engine: add query status
  engine/Dockerfile-local
  engine/client/master_client.go
  engine/client/mock_clients.go
  engine/dm/README.md
  engine/dm/dump_worker.go
  engine/dm/dump_worker_test.go
  engine/dm/load_worker.go
  engine/dm/load_worker_test.go
  engine/dm/registry.go
  engine/dm/sync_worker.go
  engine/dm/sync_worker_test.go
  engine/dm/unit.go
  engine/enginepb/datarw.pb.go
  engine/enginepb/error.pb.go
  engine/enginepb/executor.pb.go
  engine/enginepb/master.pb.go
  engine/enginepb/metastore.pb.go
  engine/enginepb/projects.pb.go
  engine/enginepb/resources.pb.go
  engine/enginepb/test.pb.go
  engine/executor/cvs/cvstask.go
  engine/executor/dm/api.go
  engine/executor/dm/api_test.go
  engine/executor/dm/unitholder.go
  engine/executor/dm/unitholder_test.go
  engine/executor/dm/worker.go
  engine/executor/dm/worker_test.go
  engine/executor/init.go
  engine/jobmaster/cvsjob/cvs_job_master.go
  engine/jobmaster/dm/api.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/metadata/job.go
  engine/jobmaster/dm/runtime/task_status.go
  engine/jobmaster/dm/runtime/task_status_test.go
  engine/jobmaster/dm/task_manager.go
  engine/jobmaster/dm/task_manager_test.go
  engine/jobmaster/dm/worker_manager.go
  engine/lib/registry/factory.go
  engine/pkg/dm/mock_message_agent.go
  engine/pkg/meta/kvclient/etcdkv/mock.go
  engine/proto/master.proto
  engine/sample/1m1e.yaml
  engine/sample/3m3e.yaml
  engine/sample/build_image_from_local.sh
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
  engine/test/e2e/e2e_dm_test.go
  engine/test/mock/grpc.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5768 framework/worker(engine): fix worker exit sequence
  engine/executor/dm/api.go
  engine/executor/dm/worker.go
  engine/lib/config/timeouts.go
  engine/lib/mock_worker_impl.go
  engine/lib/worker.go
  engine/lib/worker/exit_controller.go
  engine/lib/worker/exit_controller_test.go
  engine/lib/worker_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5760 tp: support balance when add a new capture
  cdc/scheduler/internal/tp/capture_manager_test.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/coordinator_test.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_manager_test.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/replication_set_test.go
  cdc/scheduler/internal/tp/scheduler_balance.go
  cdc/scheduler/internal/tp/scheduler_balance_test.go
  cdc/scheduler/internal/tp/scheduler_rebalance.go
  cdc/scheduler/internal/tp/scheduler_rebalance_test.go
Labels: component/scheduler, status/LGT1, size/XXL, release-note-none, area/ticdc

#5652 syncer(dm): prepare promutil.Factory injection and cache metrics
  dm/checker/checker.go
  dm/dm/config/subtask.go
  dm/dm/master/metrics/metrics.go
  dm/dm/worker/metrics.go
  dm/dm/worker/server.go
  dm/dumpling/dumpling.go
  dm/dumpling/dumpling_test.go
  dm/dumpling/metrics.go
  dm/loader/metrics.go
  dm/pkg/conn/baseconn_test.go
  dm/pkg/metricsproxy/countervec.go
  dm/pkg/metricsproxy/countervec_test.go
  dm/pkg/metricsproxy/gaugevec.go
  dm/pkg/metricsproxy/gaugevec_test.go
  dm/pkg/metricsproxy/histogramvec.go
  dm/pkg/metricsproxy/histogramvec_test.go
  dm/pkg/schema/tracker.go
  dm/relay/metrics.go
  dm/syncer/causality.go
  dm/syncer/causality_test.go
  dm/syncer/checkpoint.go
  dm/syncer/checkpoint_test.go
  dm/syncer/compactor.go
  dm/syncer/compactor_test.go
  dm/syncer/dbconn/db.go
  dm/syncer/dbconn/upstream_db.go
  dm/syncer/dbconn/utils.go
  dm/syncer/ddl.go
  dm/syncer/ddl_test.go
  dm/syncer/dml_worker.go
  dm/syncer/error.go
  dm/syncer/error_test.go
  dm/syncer/expr_filter_group.go
  dm/syncer/job.go
  dm/syncer/metrics/metrics.go
  dm/syncer/online-ddl-tools/online_ddl.go
  dm/syncer/sharding_group.go
  dm/syncer/sharding_group_test.go
  dm/syncer/status.go
  dm/syncer/status_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5777 upstream(ticdc): store pd info in etcd
  cdc/api/v1/api.go
  cdc/api/v1/validator.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  cdc/api/v2/tso.go
  cdc/api/v2/unsafe.go
  cdc/api/v2/validator.go
  cdc/capture/capture.go
  cdc/model/upstream.go
  cdc/owner/changefeed.go
  cdc/owner/owner.go
  cdc/processor/manager.go
  cdc/processor/processor.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/factory/factory.go
  pkg/cmd/factory/factory_impl.go
  pkg/config/replica_config.go
  pkg/config/sink.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/etcdkey.go
  pkg/etcd/etcdkey_test.go
  pkg/orchestrator/reactor_state.go
  pkg/orchestrator/reactor_state_test.go
  pkg/upstream/manager.go
  pkg/upstream/manager_test.go
  pkg/upstream/upstream.go
  pkg/version/version.go
  tests/integration_tests/availability/owner.sh
  tests/integration_tests/availability/run.sh
  tests/integration_tests/http_api/util/test_case.py
Labels: size/XXL, release-note

#5761 latency(cdc): fix ddl does not execute caused by incorrect checkpoint calculation
  cdc/owner/ddl_puller.go
  cdc/owner/ddl_sink.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_manager_test.go
Labels: size/L, release-note-none

#5658 cdc: reduce context switch for stateful events
  cdc/kv/client.go
  cdc/kv/metrics.go
  cdc/kv/region_worker.go
  pkg/workerpool/pool.go
  pkg/workerpool/pool_impl.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#5181 validator(dm): query-status & prometheus monitoring
  dm/dm/pb/dmworker.pb.go
  dm/dm/proto/dmworker.proto
  dm/dm/worker/metrics.go
  dm/dm/worker/status.go
  dm/metrics/grafana/DM-Monitor-Professional.json
  dm/syncer/data_validator.go
  dm/syncer/metrics/validator_metrics.go
  dm/tests/dmctl_command/conf/dm-task2.yaml
  dm/tests/dmctl_command/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5791 fb/latency(cdc): agent fix inconsistent state by tolerant duplicate messages.
  cdc/processor/processor.go
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/agent_test.go
Labels: status/LGT1, size/M, release-note-none

#5773 test(dm): fix unstable validator case
  dm/tests/validator_basic/conf/dm-task-standalone.yaml
  dm/tests/validator_basic/run.sh
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm, needs-cherry-pick-release-6.1

#5795 test(dm): fix one deadlock
  dm/dm/master/server_test.go
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#5712 sink(ticdc): remove force consume when redo is disabled
  cdc/model/mounter.go
  cdc/model/mounter_test.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/sink/black_hole.go
  cdc/sink/flowcontrol/flow_control.go
  cdc/sink/flowcontrol/flow_control_test.go
  cdc/sink/flowcontrol/table_memory_quota.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_test.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/simple_mysql_tester.go
  cdc/sink/mysql/txn_cache.go
  cdc/sink/mysql/txn_cache_test.go
  cdc/sink/sink.go
  cdc/sink/table_sink.go
  cmd/kafka-consumer/main.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/ticdc

#5758 orm(engine): Orm support context
  engine/pkg/orm/client.go
  engine/pkg/orm/client_test.go
  engine/pkg/orm/model/logic_epoch.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#5778 engine(dm): add operate task
  engine/executor/dm/api.go
  engine/executor/dm/api_test.go
  engine/executor/dm/unitholder.go
  engine/executor/dm/unitholder_test.go
  engine/executor/dm/worker.go
  engine/executor/dm/worker_test.go
  engine/jobmaster/dm/api.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/metadata/job.go
  engine/jobmaster/dm/metadata/job_test.go
  engine/jobmaster/dm/task_manager.go
  engine/jobmaster/dm/task_manager_test.go
  engine/pkg/dm/topic.go
  engine/test/e2e/e2e_dm_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5691 sink/mq(ticdc): Optimize 10k Kafka topic creation performance
  cdc/sink/mq/manager/kafka_manager.go
  cdc/sink/mq/manager/kafka_manager_test.go
  cdc/sink/mq/manager/manager.go
  cdc/sink/mq/manager/pulsar_manager.go
  cdc/sink/mq/mq.go
  errors.toml
  pkg/errors/errors.go
  pkg/kafka/cluster_admin_client.go
  pkg/kafka/cluster_admin_client_mock_impl.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-6.1

#5781 chaos(engine): add network chaos cases in dataflow engine
  .github/workflows/dataflow_engine_chaos.yaml
  engine/chaos/cases/case_fake_job.go
  engine/chaos/manifests/network-emulation-dataflow.yaml
  engine/chaos/manifests/network-partition-dataflow.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5802 http&migration(ticdc): Return http error if server is not ready
  cdc/api/middleware/middleware.go
  cdc/api/v1/api.go
  cdc/api/v2/api.go
  cdc/capture/capture.go
  errors.toml
  pkg/cmd/cli/cli_changefeed_resume.go
  pkg/errors/errors.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/etcdkey.go
  pkg/etcd/migrate.go
  pkg/etcd/testing.go
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_bank_test.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/pdutil/pd_api_client.go
  pkg/pdutil/pd_api_client_test.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_service.go
  pkg/txnutil/gc/testing.go
  pkg/upstream/manager.go
  pkg/upstream/manager_test.go
  pkg/upstream/upstream.go
  tests/integration_tests/availability/capture.sh
  tests/integration_tests/availability/owner.sh
  tests/integration_tests/changefeed_error/run.sh
  tests/integration_tests/processor_resolved_ts_fallback/run.sh
  tests/utils/cdc_state_checker/cdc_monitor.go
Labels: status/LGT1, size/XXL, release-note-none

#5780 store (ticdc): refine create ti store
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/store_op.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/cmd/cli/cli_changefeed_helper.go
Labels: status/LGT2, status/can-merge, size/L, release-note, type/enhancement

#5811 cli (ticdc): [create,query, update]changefeed cli use api
  cdc/api/v1/validator.go
  cdc/api/v2/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  cdc/api/v2/validator.go
  cdc/model/http_model.go
  cdc/model/upstream.go
  cmd/kafka-consumer/main.go
  pkg/api/v1/changefeed.go
  pkg/api/v2/api_client.go
  pkg/api/v2/changefeed.go
  pkg/cmd/cli/cli_capture_list.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/cmd/cli/cli_changefeed_helper_test.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/factory/factory.go
  pkg/etcd/etcd.go
  pkg/filter/filter.go
Labels: size/XXL, component/cli, release-note, api/v2

#5828 cli(ticdc): delete changefeed cyclic in cdc cli
  pkg/cmd/cli/cli_changefeed.go
  pkg/cmd/cli/cli_changefeed_cyclic.go
  pkg/cmd/cli/cli_changefeed_cyclic_create_marktables.go
Labels: size/L, release-note, do-not-merge/needs-linked-issue

#5771 tests(ticdc): increase runner swap size to stablize tests
  .github/workflows/ticdc_integration.yaml
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#5823 tp: add metrics
  cdc/metrics.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/capture_manager_test.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/coordinator_test.go
  cdc/scheduler/internal/tp/metrics.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_manager_test.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/replication_set_test.go
  cdc/scheduler/rexport.go
Labels: component/scheduler, status/LGT1, size/XL, component/metrics-logging, release-note-none, area/ticdc

#5800 log(engine): add Logger() interface to BaseMaster/BaseWorker/BaseJobMaster
  engine/lib/base_jobmaster.go
  engine/lib/master.go
  engine/lib/worker.go
  engine/pkg/logutil/log.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#5779 test(dm): fix some unstable tests
  dm/tests/safe_mode/run.sh
  dm/tests/sequence_sharding_optimistic/run.sh
  dm/tests/shardddl2/run.sh
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm, needs-cherry-pick-release-6.1

#5841 tests(ticdc): reorder run integration tests instructions
  tests/integration_tests/README.md
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none

#5829 kv(ticdc): fix data loss when upstream txn conflicts during scan (#5477)
  cdc/entry/mounter.go
  cdc/kv/matcher.go
  cdc/kv/matcher_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/model/kv.go
  cdc/model/kv_test.go
Labels: type/bugfix, component/kv-client, status/LGT1, size/XL, cherry-pick-approved, release-note, area/ticdc

#5844 tp: add info provider
  cdc/scheduler/internal/info_provider.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/info_provider.go
  cdc/scheduler/internal/tp/info_provider_test.go
Labels: component/scheduler, status/LGT1, size/L, release-note-none, area/ticdc

#5842 tp: separate balance scheduler to basic and balance
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/coordinator_test.go
  cdc/scheduler/internal/tp/scheduler.go
  cdc/scheduler/internal/tp/scheduler_balance.go
  cdc/scheduler/internal/tp/scheduler_balance_test.go
  cdc/scheduler/internal/tp/scheduler_basic.go
  cdc/scheduler/internal/tp/scheduler_basic_test.go
  cdc/scheduler/internal/tp/scheduler_rebalance.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/scheduler_config.go
  pkg/config/server_config.go
  pkg/config/server_config_test.go
Labels: component/scheduler, status/LGT1, size/XXL, release-note-none, area/ticdc

#5766 errors(ticdc): fix a typo and remove useless function
  cdc/api/validator/validator.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_puller.go
  cdc/owner/ddl_puller_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  errors.toml
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/errors/errors.go
  pkg/upstream/upstream.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#5835 cli(ticdc): remove pd parameter from cli
  cdc/api/v2/changefeed.go
  cdc/api/v2/validator.go
  pkg/api/v2/changefeed.go
  pkg/cmd/cli/cli_changefeed.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_processor.go
  pkg/cmd/factory/factory.go
  pkg/cmd/factory/factory_impl.go
  pkg/cmd/util/helper.go
  pkg/etcd/etcd.go
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
  tests/integration_tests/availability/owner.sh
  tests/integration_tests/cli/run.sh
  tests/integration_tests/cyclic_ab/conf/diff_config.toml
  tests/integration_tests/cyclic_ab/conf/only_test_simple.toml
  tests/integration_tests/cyclic_ab/run.sh
  tests/integration_tests/cyclic_abc/conf/changefeed.toml
  tests/integration_tests/cyclic_abc/conf/diff_config_down_tls.toml
  tests/integration_tests/cyclic_abc/conf/diff_config_up_down.toml
  tests/integration_tests/cyclic_abc/run.sh
  tests/integration_tests/processor_resolved_ts_fallback/run.sh
Labels: size/XXL, release-note

#5831 api(ticdc): extract forwardToOwnerMiddleware
  cdc/api/v1/api.go
Labels: status/LGT2, status/can-merge, first-time-contributor, size/M, contribution, release-note-none, area/ticdc, component/api

#5851 integration_test (ticdc): fix failed test cases
  tests/integration_tests/cli/run.sh
  tests/integration_tests/ddl_reentrant/run.sh
Labels: size/M, release-note

#5744 executor-manager(engine): fix check alive deadloop
  engine/servermaster/executor_manager.go
  engine/servermaster/executor_manager_test.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
Labels: status/ptal, status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/engine

#5797 fake-master(engine): fix business id mapping during failover
  engine/framework/fake/fake_master.go
Labels: status/ptal, status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, area/engine

#5855 tests(ticdc): fix unstable TestResolvedTs
  cdc/model/mounter_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#5856 api(ticdc): change api v2 code style
  cdc/api/middleware/middleware.go
  cdc/api/v1/api.go
  cdc/api/v2/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  cdc/api/v2/unsafe.go
  cdc/api/v2/validator.go
  pkg/api/internal/rest/request.go
  pkg/api/v2/changefeed.go
  pkg/api/v2/unsafe.go
  tests/integration_tests/http_api/util/test_case.py
Labels: size/L, release-note-none

#5304 owner(ticdc): fix the nil panic
  cdc/owner/owner.go
  tests/integration_tests/http_api/run.sh
Labels: status/LGT2, status/can-merge, size/S, cherry-pick-approved, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, type/cherry-pick-for-release-5.3

#5845 dep: update tidb version
  dm/dumpling/dumpling.go
  dm/dumpling/dumpling_test.go
  dm/dumpling/metrics.go
  dm/tests/full_mode/run.sh
  engine/pkg/promutil/wrapping.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5865 test(dm): fix unstable tests
  Makefile
  dm/dm/master/server.go
  dm/dm/master/server_test.go
  dm/tests/_utils/wait_process_exit
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#5820 fb/latency(cdc): agent to be table state awared, to handle different p2p messages.
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/agent_bench_test.go
  cdc/scheduler/internal/tp/agent_test.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/scheduler_rebalance.go
  cdc/scheduler/internal/tp/table.go
  cdc/scheduler/internal/tp/table_test.go
Labels: status/LGT1, size/XXL, release-note-none

#5857 fix integration test failed
  cdc/api/util.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  pkg/api/v1/changefeed.go
  pkg/cmd/cli/cli_changefeed_list.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_changefeed_resume.go
  tests/integration_tests/_utils/check_etcd_meta_not_exist
  tests/integration_tests/changefeed_error/run.sh
  tests/integration_tests/multi_capture/run.sh
  tests/integration_tests/processor_resolved_ts_fallback/run.sh
  tests/integration_tests/sorter/run.sh
Labels: size/M, release-note

#5859 tests(ticdc): fix unstable TestWriterRedoGC
  cdc/redo/writer/writer_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#5861 api(ticdc): define changefeedinfo api v2 model
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  pkg/api/v2/changefeed.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_changefeed_update_test.go
  tests/integration_tests/cli/run.sh
Labels: size/L, release-note-none

#5794 pb(engine): Remove pb job type and use strict sql mode for framework metastore
  engine/chaos/cases/case_fake_job.go
  engine/ctl/cmd.go
  engine/enginepb/datarw.pb.go
  engine/enginepb/error.pb.go
  engine/enginepb/executor.pb.go
  engine/enginepb/master.pb.go
  engine/enginepb/metastore.pb.go
  engine/enginepb/projects.pb.go
  engine/enginepb/resources.pb.go
  engine/enginepb/test.pb.go
  engine/errors.toml
  engine/executor/openapi.go
  engine/executor/openapi_test.go
  engine/framework/common.go
  engine/framework/master.go
  engine/framework/mock_master_impl.go
  engine/framework/model/master.go
  engine/framework/model/status.go
  engine/framework/model/typedefs.go
  engine/framework/registry/registry_test.go
  engine/framework/worker.go
  engine/model/job.go
  engine/model/job_test.go
  engine/pkg/errors/errors.go
  engine/pkg/orm/client.go
  engine/pkg/orm/client_test.go
  engine/pkg/promutil/implement_test.go
  engine/pkg/promutil/test/multiprojects_metric_scences.go
  engine/pkg/promutil/util.go
  engine/pkg/promutil/util_inner.go
  engine/pkg/promutil/util_inner_test.go
  engine/proto/master.proto
  engine/servermaster/job_fsm.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  engine/servermaster/server.go
  engine/test/e2e/e2e_dm_test.go
  engine/test/e2e/e2e_node_chaos_test.go
  engine/test/e2e/e2e_test.go
  engine/test/e2e/e2e_test_cli.go
  engine/test/e2e/e2e_worker_exit_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5734 mysqlSink(cdc): Fix RemoveTable blocking infinitely
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/mysql_worker.go
  cdc/sink/mysql/mysql_worker_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.1

#5824 syncer(dm): fix different output format for operate-schema get
  dm/syncer/schema.go
  dm/syncer/syncer_test.go
Labels: status/LGT1, status/can-merge, first-time-contributor, size/M, require-LGT1, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#5889 *(ticdc): Release upstream and fix some issues
  cdc/api/v1/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/api/v2/tso.go
  cdc/api/v2/unsafe.go
  cdc/api/v2/validator.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/model/upstream_test.go
  cdc/processor/processor.go
  errors.toml
  pkg/api/v2/api_client.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/errors/errors.go
  pkg/orchestrator/reactor_state.go
  pkg/upstream/manager.go
  pkg/upstream/upstream.go
Labels: size/XL, release-note

#5873 api(ticdc): fix panic after middleware refactor
  cdc/api/interfaces.go
  cdc/api/middleware/middleware.go
  cdc/api/util.go
  cdc/api/v1/api.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#5783 metrics(engine): add e2e test for syncer metrics
  dm/syncer/ddl_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  engine/executor/dm/worker.go
  engine/sample/3m3e.yaml
  engine/test/e2e/e2e_dm_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#5892 sink/mysql(ticdc): add comments
  cdc/sink/mysql/causality.go
  cdc/sink/mysql/causality_test.go
  cdc/sink/mysql/mysql.go
Labels: component/sink, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#5893 cli(ticdc): cli support multi stream
  cdc/api/v1/api.go
  cdc/api/v2/api.go
  cdc/api/v2/model.go
  cdc/api/v2/tso.go
  cdc/api/v2/tso_test.go
  cdc/api/v2/unsafe.go
  cdc/api/v2/validator.go
  cdc/model/changefeed.go
  cdc/model/http_model.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/api/v2/tso.go
  pkg/api/v2/unsafe.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_resume.go
  pkg/cmd/cli/cli_changefeed_statistics.go
  pkg/cmd/cli/cli_unsafe_delete_service_gc_safepoint.go
  pkg/cmd/cli/cli_unsafe_resolve_lock.go
  tests/integration_tests/http_api/util/test_case.py
  tests/integration_tests/http_api_tls/util/test_case.py
Labels: size/XL, release-note

#5878 refine readme add release, golang info
  README.md
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#5894 owner(cdc): backport stale metrics fix to 5.3
  cdc/owner/owner.go
Labels: status/LGT2, status/can-merge, size/S, cherry-pick-approved, release-note

#5858 test(engine): fix unstable TestNewLogger ut
  engine/pkg/logutil/log_test.go
  go.mod
  go.sum
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#5815 engine(dm): add config/binlog/binlog-schema command
  engine/executor/dm/api.go
  engine/executor/dm/api_test.go
  engine/executor/dm/unitholder.go
  engine/executor/dm/unitholder_test.go
  engine/jobmaster/dm/api.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/config/config.go
  engine/jobmaster/dm/config/config_test.go
  engine/pkg/dm/topic.go
  engine/test/e2e/e2e_dm_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5879 sink/mq,sink/mysql(ticdc): remove useless opts for MQ and MySQL sink
  cdc/api/validator/validator.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner/ddl_sink.go
  cdc/owner/feed_state_manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/sink/metrics/statistics.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_test.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_params.go
  cdc/sink/mysql/mysql_params_test.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/sink.go
  cdc/sink/sink_test.go
  cmd/kafka-consumer/main.go
  pkg/applier/redo.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/orchestrator/reactor_state_test.go
  scripts/avro-local-test.sh
  scripts/canal/canal-local-test.sh
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#5869 lightning(dm): export metrics
  dm/dumpling/dumpling.go
  dm/dumpling/dumpling_test.go
  dm/loader/lightning.go
  dm/tests/many_tables/run.sh
  engine/pkg/promutil/registry.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#5897 (WIP)upstream(ticdc): refine upstream manager
  cdc/api/v1/api.go
  cdc/api/v1/validator.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/unsafe.go
  cdc/capture/capture.go
  cdc/owner/changefeed.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/processor/manager.go
  cdc/processor/processor.go
  pkg/cmd/factory/factory_impl.go
  pkg/etcd/etcd.go
  pkg/orchestrator/reactor_state.go
  pkg/upstream/manager.go
  pkg/upstream/manager_test.go
  pkg/upstream/upstream.go
  tests/integration_tests/http_api_tls/util/test_case.py
Labels: size/XL, do-not-merge/work-in-progress, release-note

#5876 test(engine): fix executor manager heartbeat timing bug in unit test
  engine/servermaster/executor_manager.go
  engine/servermaster/executor_manager_test.go
Labels: status/ptal, status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none, area/engine

#5914 api(ticdc) refactor changefeed update v2 using transaction
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/validator.go
  errors.toml
  pkg/errors/errors.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
Labels: size/L, release-note

#5919 ut(ticdc): Add test cases
  cdc/api/interfaces.go
  cdc/api/middleware/middleware.go
  cdc/api/middleware/middleware_test.go
  cdc/api/v2/unsafe.go
  cdc/api/v2/validator.go
  pkg/etcd/etcdkey_test.go
  pkg/upstream/manager.go
  pkg/upstream/manager_test.go
  pkg/upstream/upstream.go
  pkg/upstream/upstream_test.go
  tests/integration_tests/http_api/util/test_case.py
Labels: size/XL, release-note

#5916 dep: update tidb to introduce some change
  dm/dm/worker/task_checker_test.go
  dm/syncer/dbconn/db.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#5921 redo(ticdc): remove useless interface and enable leak test
  cdc/redo/common/main_test.go
  cdc/redo/doc.go
  cdc/redo/main_test.go
  cdc/redo/manager.go
  cdc/redo/reader/file_test.go
  cdc/redo/reader/main_test.go
  cdc/redo/writer/file_test.go
  cdc/redo/writer/main_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#5868 test(dm): fix flaky dm 155 case test
  dm/tests/shardddl4_1/run.sh
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#5912 cli(ticdc): Optimize changefeed remove experience
  cdc/api/owner/owner.go
  cdc/api/util.go
  cdc/api/v1/api.go
  cdc/model/owner.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner_test.go
  cdc/redo/manager.go
  errors.toml
  pkg/api/v1/changefeed.go
  pkg/cmd/cli/cli_changefeed_remove.go
  pkg/errors/errors.go
  tests/integration_tests/changefeed_fast_fail/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#5906 tp: cleanup metrics and fix a bug that ignore schedule task mistakenly
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_manager_test.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/replication_set_test.go
  cdc/scheduler/internal/tp/scheduler_basic.go
  tests/integration_tests/move_table/main.go
Labels: component/scheduler, status/LGT1, size/L, release-note-none, area/ticdc

#5896 utils(dm): fix get tables without using quote schema name
  dm/dm/master/openapi_view.go
  dm/dm/master/openapi_view_test.go
  dm/pkg/checker/onlineddl.go
  dm/pkg/utils/db.go
  dm/pkg/utils/db_test.go
  dm/tests/check_task/conf/task-sharding.yaml
  dm/tests/check_task/data/db1.prepare.sql
  dm/tests/check_task/run.sh
  dm/tests/openapi/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#5922 servermaster(engine): fix leader hangs after etcd leader transfers
  engine/pkg/externalresource/manager/gc_coordinator.go
  engine/pkg/externalresource/manager/gc_runner.go
  engine/servermaster/campaign.go
  engine/servermaster/server.go
  engine/test/e2e/e2e_node_chaos_test.go
  engine/test/e2e/e2e_test_cli.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5944 resource(engine): fix skipping resource meta remove in gc retry
  engine/pkg/externalresource/manager/gc_runner.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#5905 chaos(engine): dump goroutines if test fails
  .github/workflows/dataflow_engine_chaos.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#5948 tp: fix same primary and source error on move table
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/replication_set_test.go
Labels: component/scheduler, status/LGT1, size/S, release-note-none, area/ticdc

#5848 tests(ticdc): add big txn integration test
  pkg/cmd/server/server_test.go
  pkg/config/server_config.go
  tests/integration_tests/big_txn/conf/diff_config.toml
  tests/integration_tests/big_txn/conf/workload
  tests/integration_tests/big_txn/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#5923 pkg/p2p: fix ErrPeerMessageDataLost after ErrPeerMessageTopicCongested is triggered
  pkg/p2p/server.go
  pkg/p2p/server_client_integration_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, area/engine

#5881 syncer(dm): fix the data race issue
  dm/dm/worker/subtask.go
  dm/dm/worker/subtask_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#5952 processor(cdc): simplify get table name.
  cdc/processor/processor.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#5852 fb/latency(cdc): 2 phase scheduling drain capture
  cdc/api/util.go
  cdc/api/v1/api.go
  cdc/model/http_model.go
  cdc/owner/changefeed_test.go
  cdc/owner/mock/owner_mock.go
  cdc/owner/owner.go
  cdc/scheduler/internal/base/schedule_dispatcher.go
  cdc/scheduler/internal/scheduler.go
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/agent_bench_test.go
  cdc/scheduler/internal/tp/agent_test.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/capture_manager_test.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/coordinator_test.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/schedulepb/table_schedule.pb.go
  cdc/scheduler/internal/tp/scheduler.go
  cdc/scheduler/internal/tp/scheduler_balance.go
  cdc/scheduler/internal/tp/scheduler_balance_test.go
  cdc/scheduler/internal/tp/scheduler_basic.go
  cdc/scheduler/internal/tp/scheduler_drain_capture.go
  cdc/scheduler/internal/tp/scheduler_drain_capture_test.go
  cdc/scheduler/internal/tp/scheduler_manager.go
  cdc/scheduler/internal/tp/scheduler_manager_test.go
  cdc/scheduler/internal/tp/scheduler_move_table.go
  cdc/scheduler/internal/tp/scheduler_rebalance.go
  cdc/scheduler/internal/tp/table.go
  cdc/scheduler/rexport.go
  cdc/sorter/leveldb/sorter.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  errors.toml
  pkg/config/scheduler_config.go
  pkg/config/server_config.go
  pkg/errors/errors.go
  proto/table_schedule.proto
  tools/check/go.sum
Labels: status/LGT1, size/XXL, release-note-none

#5966 test(ticdc): Fix bugs and add test cases
  cdc/api/v2/changefeed.go
  cdc/api/v2/model_test.go
  cdc/api/v2/unsafe.go
  cdc/api/v2/unsafe_test.go
  cdc/api/v2/validator.go
  cdc/api/v2/validator_test.go
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
  tests/integration_tests/http_api_tls/run.sh
  tests/integration_tests/http_api_tls/util/test_case.py
Labels: size/XL, release-note

#5890 syncer(dm): first commit about another handle-error
  dm/syncer/binlogstream/stream_modifier.go
  dm/syncer/binlogstream/stream_modifier_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5713 engine(servermaster): init openapi framework and forward job master api
  Makefile
  engine/cmd/executor/main.go
  engine/cmd/master/main.go
  engine/docs/swagger/docs.go
  engine/docs/swagger/swagger.json
  engine/docs/swagger/swagger.yaml
  engine/servermaster/http.go
  engine/servermaster/http_handler.go
  engine/servermaster/http_test.go
  engine/servermaster/jobmanager.go
  engine/servermaster/openapi.go
  engine/servermaster/openapi_test.go
  engine/servermaster/server.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5965 chore(cdc): manually bump tools/check dependency varnamelen
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#5971 fb/latency(cdc): adjust add table finish condition
  cdc/processor/processor.go
  cdc/processor/processor_test.go
Labels: status/LGT1, size/L, release-note-none

#5975 tp: cleanup changes to schedulerv2
  cdc/scheduler/internal/base/agent.go
  cdc/scheduler/internal/base/agent_mock.go
  cdc/scheduler/internal/base/processor_agent.go
  cdc/scheduler/internal/base/protocol/protocol.go
Labels: component/scheduler, status/LGT1, size/M, release-note-none, area/ticdc

#5974 test(ticdc): Add cli ut cases
  pkg/api/v1/mock/capture_mock.go
  pkg/api/v1/mock/changefeed_mock.go
  pkg/api/v1/mock/processor_mock.go
  pkg/api/v1/mock/status_mock.go
  pkg/api/v2/api_client.go
  pkg/api/v2/mock/changefeed_mock.go
  pkg/api/v2/mock/tso_mock.go
  pkg/api/v2/mock/unsafe_mock.go
  pkg/cmd/cli/cli_capture.go
  pkg/cmd/cli/cli_capture_list.go
  pkg/cmd/cli/cli_capture_list_test.go
  pkg/cmd/cli/cli_capture_test.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/cmd/cli/cli_changefeed_list.go
  pkg/cmd/cli/cli_changefeed_list_test.go
  pkg/cmd/cli/cli_changefeed_pause.go
  pkg/cmd/cli/cli_changefeed_pause_test.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_changefeed_query_test.go
  pkg/cmd/cli/cli_changefeed_remove.go
  pkg/cmd/cli/cli_changefeed_remove_test.go
  pkg/cmd/cli/cli_changefeed_resume.go
  pkg/cmd/cli/cli_changefeed_resume_test.go
  pkg/cmd/cli/cli_changefeed_statistics.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_changefeed_update_test.go
  pkg/cmd/cli/cli_processor.go
  pkg/cmd/cli/cli_processor_list_test.go
  pkg/cmd/cli/cli_processor_query_test.go
  pkg/cmd/cli/cli_processor_test.go
  pkg/cmd/cli/cli_unsafe_delete_service_gc_safepoint.go
  pkg/cmd/cli/cli_unsafe_resolve_lock.go
  pkg/cmd/cli/cli_unsafe_resolve_lock_test.go
  pkg/cmd/cli/cli_unsafe_show_metadata.go
  pkg/cmd/cli/cli_unsafe_show_metadata_test.go
  pkg/cmd/factory/factory.go
  pkg/cmd/factory/factory_impl.go
  pkg/p2p/server_client_integration_test.go
  pkg/p2p/server_test.go
Labels: size/XXL, release-note

#5943 pipeline(ticdc): split dataflow in sinkNode
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/sink/table_sink.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#5972 framework(engine): fix stale pong heartbeat causes ack time fallback
  engine/executor/worker/ctx.go
  engine/executor/worker/ctx_test.go
  engine/executor/worker/internal/info.go
  engine/executor/worker/internal/runnables.go
  engine/executor/worker/task_committer.go
  engine/executor/worker/task_committer_test.go
  engine/executor/worker/task_runner.go
  engine/executor/worker/task_runner_test.go
  engine/executor/worker/test_util.go
  engine/framework/internal/worker/master_client.go
  engine/framework/internal/worker/master_client_test.go
  engine/framework/worker.go
  engine/framework/worker_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#6016 logutil(cdc, engine): add some util function to logutil for cdc and engine
  cmd/kafka-consumer/main.go
  pkg/cmd/util/helper.go
  pkg/logutil/context.go
  pkg/logutil/context_test.go
  pkg/logutil/log.go
  pkg/logutil/log_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc, area/engine

#6030 pkg(engine): refine package name
  engine/client/client_test.go
  engine/executor/server.go
  engine/executor/worker/task_committer_test.go
  engine/executor/worker/task_runner_test.go
  engine/framework/taskutil/compat.go
  engine/pkg/etcdutil/config.go
  engine/pkg/etcdutil/join.go
  engine/pkg/etcdutil/join_test.go
  engine/pkg/etcdutil/service.go
  engine/pkg/etcdutil/testing.go
  engine/pkg/serverutil/discovery_keepalive.go
  engine/pkg/serverutil/discovery_keepalive_test.go
  engine/servermaster/campaign.go
  engine/servermaster/cluster/election_test.go
  engine/servermaster/config.go
  engine/servermaster/etcd_test.go
  engine/servermaster/server.go
  engine/test/etcd_utils.go
  engine/test/heartbeat_test.go
  engine/test/util_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#6007 dep(dm): fix panic when resume task which is in dump stage
  dm/dumpling/dumpling.go
  dm/tests/tls/run.sh
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#6035 Cdc add duration log
  cdc/processor/pipeline/metrics.go
  cdc/processor/pipeline/sink.go
  cdc/sink/mysql.go
Labels: status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note-none

#6034 DM: fix validator's unstable integration test
  dm/tests/validator_basic/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#6023 test(ticdc): Add migrator ut test cases
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
Labels: size/XL, release-note

#6041 version(ticdc): bump the default RELEASE_VERSION
  Makefile
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-6.1

#5950 pkg/rpcerror(engine): implement utils for creating rpc-friendly errors.
  engine/enginepb/errorv2.pb.go
  engine/pkg/rpcerror/attributes.go
  engine/pkg/rpcerror/grpc.go
  engine/pkg/rpcerror/grpc_test.go
  engine/pkg/rpcerror/normalize.go
  engine/pkg/rpcerror/normalize_test.go
  engine/proto/errorv2.proto
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5940 framework(engine): refactor worker exiting logic
  engine/framework/base_jobmaster.go
  engine/framework/internal/errors/fail_fast.go
  engine/framework/internal/errors/fail_fast_test.go
  engine/framework/internal/eventloop/runner.go
  engine/framework/internal/master/worker_manager_test.go
  engine/framework/internal/worker/exit_controller.go
  engine/framework/internal/worker/exit_controller_test.go
  engine/framework/internal/worker/master_client.go
  engine/framework/internal/worker/master_client_test.go
  engine/framework/master.go
  engine/framework/worker.go
  engine/framework/worker_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5968 etcdutils(engine): refine etcd join test and prepare etcd lib
  engine/pkg/etcdutil/join_test.go
  engine/test/etcd_utils.go
  engine/test/etcd_utils_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#6040 version(ticdc): fix check version to 6.2.0-alpha
  Makefile
  pkg/version/check.go
Labels: status/LGT2, status/can-merge, size/S, cherry-pick-approved, release-note, area/ticdc

#6044 scheduler, api(cdc): disable owner as the drain capture target.
  cdc/api/util.go
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/processor/pipeline/sorter.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/scheduler.go
  cdc/scheduler/internal/tp/scheduler_balance.go
  cdc/scheduler/internal/tp/scheduler_balance_test.go
  cdc/scheduler/internal/tp/scheduler_basic.go
  cdc/scheduler/internal/tp/scheduler_basic_test.go
  cdc/scheduler/internal/tp/scheduler_drain_capture.go
  cdc/scheduler/internal/tp/scheduler_drain_capture_test.go
  cdc/scheduler/internal/tp/scheduler_manager.go
  cdc/scheduler/internal/tp/scheduler_move_table.go
  cdc/scheduler/internal/tp/scheduler_move_table_test.go
  cdc/scheduler/internal/tp/scheduler_rebalance.go
  cdc/scheduler/internal/tp/scheduler_rebalance_test.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#6059 clients(engine): use non-blocking dial for executors
  engine/client/base_executor_client.go
  engine/client/client_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#5967 api(ticdc) refactor openapi v2 for testablity
  Makefile
  cdc/api/middleware/middleware.go
  cdc/api/middleware/middleware_test.go
  cdc/api/util.go
  cdc/api/v1/api.go
  cdc/api/v1/validator.go
  cdc/api/v2/api.go
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_mock.go
  cdc/api/v2/api_test.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/tso.go
  cdc/api/v2/tso_test.go
  cdc/api/v2/unsafe.go
  cdc/api/v2/unsafe_test.go
  cdc/api/v2/validator.go
  cdc/api/v2/validator_test.go
  cdc/capture/capture.go
  cdc/capture/info_for_api.go
  cdc/capture/mock/capture_info_mock.go
  pkg/api/v2/mock/changefeed_mock.go
  pkg/etcd/client_for_api.go
  pkg/etcd/etcd.go
  pkg/etcd/mock/etcd_client_mock.go
  pkg/upstream/manager.go
  pkg/upstream/upstream.go
  scripts/check-diff-line-width.sh
Labels: status/LGT2, size/XXL, release-note-none

#6055 conn(dm): add timeout for Conn
  dm/pkg/conn/basedb.go
  dm/pkg/conn/basedb_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#6062 tests(ticdc): fix unstable test big_txn
  tests/integration_tests/big_txn/conf/workload
  tests/integration_tests/big_txn/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#6054 pkg/errors(cdc,engine,dm): RFCCode should find the first error with RFCCode in the causer chain
  pkg/errors/helper.go
  pkg/errors/helper_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#5936 filter(ticdc): Move filter from sink to mounter and owner/schema.
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/entry/schema_test_helper.go
  cdc/owner/changefeed.go
  cdc/owner/ddl_sink.go
  cdc/owner/ddl_sink_test.go
  cdc/owner/schema.go
  cdc/owner/schema_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/processor.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_test.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/txn_cache.go
  cdc/sink/mysql/txn_cache_test.go
  cdc/sink/sink.go
  cmd/kafka-consumer/main.go
  pkg/applier/redo.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc, component/mounter

#6099 schedulerV3 (cdc): ignore manual request if capture is stopping
  cdc/scheduler/internal/tp/scheduler_move_table.go
  cdc/scheduler/internal/tp/scheduler_move_table_test.go
  cdc/scheduler/internal/tp/scheduler_rebalance.go
  cdc/scheduler/internal/tp/scheduler_rebalance_test.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/M, release-note-none, type/enhancement

#6106 sinkv2(ticdc): fix progress can not advance issue and add tests
  cdc/sinkv2/tablesink/main_test.go
  cdc/sinkv2/tablesink/progress_tracker.go
  cdc/sinkv2/tablesink/progress_tracker_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#6097 cdc,pkg: accommodate systemd TimeoutStopSec and k8s terminationGracePeriodSeconds
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/capture/capture.go
  cdc/capture/capture_test.go
  cdc/model/http_model.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/agent.go
  cdc/scheduler/internal/base/processor_agent.go
  cdc/scheduler/internal/base/processor_agent_test.go
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/agent_test.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/capture_manager_test.go
  cdc/scheduler/internal/tp/schedulepb/table_schedule.pb.go
  cdc/scheduler/internal/tp/schedulepb/table_schedule_manual_test.go
  cdc/scheduler/internal/tp/table.go
  cdc/server.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/cli/cli.go
  pkg/cmd/redo/redo.go
  pkg/cmd/server/server.go
  pkg/cmd/util/helper.go
  pkg/cmd/util/helper_test.go
  proto/table_schedule.proto
Labels: status/LGT1, size/XXL, release-note-none, area/ticdc, component/api

#6103 migrator(ticdc): Delete old changefeed
  pkg/cmd/cli/cli_unsafe_reset.go
  pkg/config/server_config.go
  pkg/config/server_config_test.go
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
  pkg/upstream/manager.go
  pkg/upstream/upstream.go
Labels: size/L, release-note

#6020 cli(ticdc): Allow overwriting checkpoint ts when resuming a changefeed
  cdc/api/v1/validator.go
  cdc/api/v2/api.go
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_mock.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/model.go
  cdc/api/v2/unsafe_test.go
  cdc/api/v2/validator.go
  cdc/model/owner.go
  cdc/owner/changefeed.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner.go
  cdc/processor/processor.go
  errors.toml
  pkg/api/v2/changefeed.go
  pkg/api/v2/mock/changefeed_mock.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/cmd/cli/cli_changefeed_resume.go
  pkg/cmd/cli/cli_changefeed_resume_test.go
  pkg/cmd/cli/cli_unsafe_delete_service_gc_safepoint.go
  pkg/cmd/cli/cli_unsafe_resolve_lock.go
  pkg/errors/cdc_errors.go
  pkg/etcd/client_for_api.go
  pkg/etcd/etcd.go
  pkg/etcd/mock/etcd_client_mock.go
  pkg/txnutil/gc/gc_service.go
  pkg/txnutil/gc/gc_service_test.go
  tests/integration_tests/changefeed_resume_with_checkpoint_ts/conf/diff_config1.toml
  tests/integration_tests/changefeed_resume_with_checkpoint_ts/conf/diff_config2.toml
  tests/integration_tests/changefeed_resume_with_checkpoint_ts/conf/diff_config3.toml
  tests/integration_tests/changefeed_resume_with_checkpoint_ts/run.sh
Labels: status/LGT2, size/XXL, release-note-none

#6120 test(dm): align TiDB SHOW statement output
  dm/tests/full_mode/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm
