Repository pingcap/tiflow, pull requests merged in 2022-05, with the labels that each got.

#5323 scripts: fix un-catched pattern in check log style
  cdc/kv/client.go
  cdc/kv/region_worker.go
  cdc/model/changefeed.go
  cdc/model/sink.go
  cdc/owner/changefeed.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/producer/kafka/config.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/txn_cache.go
  cdc/sorter/unified/file_backend.go
  cdc/sorter/unified/heap_sorter.go
  cdc/sorter/unified/memory_backend.go
  cdc/sorter/unified/merger.go
  pkg/cyclic/filter.go
  pkg/orchestrator/etcd_worker.go
  pkg/p2p/client.go
  scripts/check-log-style.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/M, component/metrics-logging, release-note

#5325 sorter(ticdc): fix typos
  cdc/sorter/leveldb/compactor.go
  cdc/sorter/leveldb/reader.go
  cdc/sorter/leveldb/writer.go
  pkg/actor/actor.go
  pkg/actor/system.go
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, component/sorter, release-note-none, area/ticdc

#5248 pipeline(ticdc): stop processing data after sink is stopped
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#5306 validator(dm): validation status show status of validator
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/config/task.go
  dm/dm/ctl/master/query_validation.go
  dm/dm/master/server.go
  dm/dm/master/server_test.go
  dm/dm/pb/dmworker.pb.go
  dm/dm/proto/dmworker.proto
  dm/dm/worker/server.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/source_worker_test.go
  dm/dm/worker/status.go
  dm/dm/worker/subtask.go
  dm/errors.toml
  dm/pkg/terror/error_list.go
  dm/syncer/data_validator.go
  dm/syncer/data_validator_test.go
  dm/syncer/syncer.go
  dm/syncer/validate_worker.go
  dm/syncer/validate_worker_test.go
  dm/syncer/validator_checkpoint.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/dmctl_command/conf/dm-task.yaml
  dm/tests/dmctl_command/data/db1.increment.sql
  dm/tests/dmctl_command/data/db2.increment.sql
  dm/tests/dmctl_command/run.sh
  dm/tests/import_v10x/conf/task.yaml
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5296 sink(cdc): adjust error in kafka producer adjust configuration logic.
  cdc/sink/mq/mq.go
  cdc/sink/mq/producer/kafka/config.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  pkg/kafka/cluster_admin_client_mock_impl.go
  scripts/check-log-style.sh
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#5282 upstream (ticdc): add upstream to manage all upstream related resources.
  cdc/api/validator.go
  cdc/capture/capture.go
  cdc/model/changefeed.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_puller.go
  cdc/owner/ddl_puller_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/server.go
  errors.toml
  pkg/context/context.go
  pkg/errors/errors.go
  pkg/pdtime/clock.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_manager_test.go
  pkg/upstream/manager.go
  pkg/upstream/upstream.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, type/enhancement

#5298 dm: fix empty config cause dm-master panic
  dm/dm/config/task.go
  dm/tests/dmctl_basic/check_list/check_task.sh
  dm/tests/dmctl_basic/check_list/start_task.sh
  dm/tests/dmctl_basic/conf/empty-unit-task.yaml
  dm/tests/dmctl_basic/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note, area/dm, needs-cherry-pick-release-6.0

#5337 test(dm): try fix upstream switch CI
  .github/workflows/dm_binlog_999999.yaml
  .github/workflows/dm_chaos.yaml
  .github/workflows/dm_upstream_switch.yaml
  .github/workflows/upgrade_dm_via_tiup.yaml
  dm/tests/upstream_switch/conf/diff_config.toml
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/dm

#5311 metrics(ticdc): changefeed metrics add namespace label
  cdc/entry/metrics.go
  cdc/entry/mounter.go
  cdc/kv/client.go
  cdc/kv/metrics.go
  cdc/kv/region_worker.go
  cdc/kv/token_region.go
  cdc/owner/changefeed.go
  cdc/owner/metrics.go
  cdc/owner/owner.go
  cdc/processor/metrics.go
  cdc/processor/pipeline/metrics.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/processor.go
  cdc/puller/metrics.go
  cdc/puller/puller.go
  cdc/redo/writer/file.go
  cdc/redo/writer/file_test.go
  cdc/redo/writer/metric.go
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
  cdc/sink/buffer_sink.go
  cdc/sink/metrics/metrics.go
  cdc/sink/metrics/statistics.go
  cdc/sink/mq/producer/kafka/metrics.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_worker_test.go
  cdc/sink/sink_manager.go
  cdc/sorter/leveldb/metrics.go
  cdc/sorter/leveldb/reader_test.go
  cdc/sorter/leveldb/sorter.go
  cdc/sorter/leveldb/writer_test.go
  cdc/sorter/memory/entry_sorter.go
  cdc/sorter/memory/metrics.go
  cdc/sorter/metrics.go
  cdc/sorter/unified/heap_sorter.go
  cdc/sorter/unified/merger.go
  cdc/sorter/unified/metrics.go
  cdc/sorter/unified/unified_sorter.go
Labels: status/LGT1, status/can-merge, size/XXL, require-LGT1, release-note-none

#5270 sink(ticdc): migrate test-infra to testify for cdc/sink
  cdc/sink/buffer_sink_test.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/codec_test.go
  cdc/sink/codec/config_test.go
  cdc/sink/codec/craft/codec_test.go
  cdc/sink/codec/craft_test.go
  cdc/sink/codec/interface_test.go
  cdc/sink/codec/json_test.go
  cdc/sink/codec/main_test.go
  cdc/sink/codec/maxwell_test.go
  cdc/sink/codec/schema_registry_test.go
  cdc/sink/main_test.go
  cdc/sink/mysql/causality_test.go
  cdc/sink/mysql/main_test.go
  cdc/sink/mysql/txns_heap_test.go
  cdc/sink/sink_manager_test.go
  cdc/sink/sink_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#5332 server (ticdc): add timeout for statusServer.
  cdc/api/open.go
  cdc/server.go
  cdc/sink/mq/mq.go
Labels: status/ptal, component/sink, status/LGT2, status/can-merge, component/status-server, size/M, release-note, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#4937 owner(ticdc): Add support for region-label to enable meta-region isolation
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/httputil/httputil.go
  pkg/pdutil/clock.go
  pkg/pdutil/clock_test.go
  pkg/pdutil/main_test.go
  pkg/pdutil/region_label.go
  pkg/pdutil/region_label_test.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_manager_test.go
  pkg/upstream/upstream.go
  tests/integration_tests/simple/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note, needs-cherry-pick-release-5.3, area/ticdc, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#5345 test(ticdc): fix move table integration test
  tests/integration_tests/move_table/main.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#5358 sorter, metric(ticdc): fix a metric error in level db sorter
  cdc/sorter/leveldb/reader.go
  cdc/sorter/leveldb/reader_test.go
  cdc/sorter/leveldb/sorter.go
  cdc/sorter/leveldb/writer.go
  cdc/sorter/leveldb/writer_test.go
  cdc/sorter/metrics.go
  cdc/sorter/unified/merger.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/M, component/metrics-logging, release-note, area/ticdc

#5198 dm/syncer: make dm-worker support automatically resolving ConflictSkipWaitRedirect
  dm/_utils/terror_gen/checker_template.go
  dm/pkg/shardddl/optimism/lock.go
  dm/pkg/shardddl/optimism/lock_test.go
  dm/pkg/shardddl/optimism/operation.go
  dm/syncer/checkpoint.go
  dm/syncer/checkpoint_test.go
  dm/syncer/job.go
  dm/syncer/opt_sharding_group.go
  dm/syncer/opt_sharding_group_test.go
  dm/syncer/optimist.go
  dm/syncer/shardddl/optimist.go
  dm/syncer/status_test.go
  dm/syncer/syncer.go
  dm/tests/_utils/check_process_exit
  dm/tests/_utils/shardddl_lib.sh
  dm/tests/shardddl1/run.sh
  dm/tests/shardddl2_1/run.sh
  dm/tests/shardddl3_1/run.sh
  dm/tests/shardddl4_1/run.sh
  dm/tests/shardddl_optimistic/run.sh
  pkg/errorutil/ignore.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#5333 kafka-consumer(ticdc): cherry-pick all changes
  cmd/kafka-consumer/main.go
Labels: status/LGT2, status/can-merge, size/L, cherry-pick-approved, release-note-none, area/ticdc, type/cherry-pick-for-release-5.4

#5314 sink/mq/producer(ticdc): fix test typo
  cdc/sink/mq/producer/kafka/config_test.go
Labels: component/sink, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/ticdc

#5341 tracker(dm): add task name to unistore folder name
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
  dm/syncer/syncer_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#5340 syncer: support start from empty gtid config
  dm/pkg/gtid/gtid.go
  dm/pkg/gtid/gtid_test.go
  dm/relay/local_reader_test.go
  dm/tests/incremental_mode/conf/dm-task.yaml
  dm/tests/incremental_mode/conf/source1.yaml
  dm/tests/incremental_mode/data/db1.prepare.sql
  dm/tests/incremental_mode/data/db2.prepare.sql
  dm/tests/incremental_mode/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm, needs-cherry-pick-release-6.0

#5362 *(ticdc): remove scheduler v1
  cdc/capture/capture.go
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/owner/scheduler.go
  cdc/owner/scheduler_v1.go
  cdc/owner/scheduler_v1_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/etcdkey.go
  pkg/orchestrator/reactor_state.go
  pkg/orchestrator/reactor_state_test.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#5331 validator(dm): better error handling and handle panic
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/master/server_test.go
  dm/dm/worker/source_worker_test.go
  dm/dm/worker/subtask.go
  dm/errors.toml
  dm/pkg/conn/basedb.go
  dm/pkg/retry/strategy.go
  dm/pkg/terror/error_list.go
  dm/pkg/utils/common.go
  dm/pkg/utils/common_test.go
  dm/syncer/data_validator.go
  dm/syncer/data_validator_test.go
  dm/syncer/validate_worker.go
  dm/syncer/validate_worker_test.go
  dm/syncer/validator_checkpoint.go
  dm/syncer/validator_checkpoint_test.go
  dm/tests/dmctl_command/run.sh
  dm/tests/others_integration_1.txt
  dm/tests/sequence_sharding_optimistic/run.sh
  dm/tests/validator_basic/conf/diff_config.toml
  dm/tests/validator_basic/conf/dm-master.toml
  dm/tests/validator_basic/conf/dm-task-standalone.yaml
  dm/tests/validator_basic/conf/dm-worker1.toml
  dm/tests/validator_basic/conf/source1.yaml
  dm/tests/validator_basic/data/db1.increment.sql
  dm/tests/validator_basic/data/db1.prepare.sql
  dm/tests/validator_basic/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5375 tiflow: adjust README files
  README.md
  README_DM.md
  README_TiCDC.md
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#5240 DM/Openapi: support ignore check items
  dm/dm/config/task_converters.go
  dm/dm/config/task_converters_test.go
  dm/dm/master/openapi_controller.go
  dm/dm/master/openapi_controller_test.go
  dm/dm/master/openapi_view.go
  dm/dm/master/openapi_view_test.go
  dm/openapi/gen.client.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm, needs-update-docs

#5373 pkg/chdelay: implement ChannelDelayer
  pkg/chdelay/channel_delayer.go
  pkg/chdelay/channel_delayer_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.0

#5377 sink(ticdc): Enhance the topic expression to allow more flexible dispatching
  cdc/sink/mq/dispatcher/topic/expression.go
  cdc/sink/mq/dispatcher/topic/expression_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#5367 scheduler(ticdc): Fix owner panic issue
  cdc/model/protocol.go
  cdc/model/protocol_test.go
  cdc/owner/scheduler.go
  cdc/processor/agent.go
  cdc/processor/agent_test.go
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/agent.go
  cdc/scheduler/agent_mock.go
  cdc/scheduler/agent_test.go
  cdc/scheduler/schedule_dispatcher.go
  cdc/scheduler/schedule_dispatcher_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc, component/owner, needs-cherry-pick-release-6.0

#5374 sink(ticdc): ignore sync.runtime_Semacquire in mysql leak test
  cdc/sink/mysql/causality_test.go
  cdc/sink/mysql/main_test.go
  cdc/sink/mysql/mysql_params_test.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/mysql_worker_test.go
  cdc/sink/mysql/txn_cache_test.go
  cdc/sink/mysql/txns_heap_test.go
  pkg/leakutil/leak_helper.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#5404 cdc,script(ticdc): add more logs to AsyncClose
  cdc/capture/capture.go
  scripts/check-diff-line-width.sh
Labels: status/LGT2, status/can-merge, size/S, component/metrics-logging, release-note-none, area/ticdc

#5364 DM/Openapi: ignore can not connect error when force delete task
  dm/dm/master/openapi_controller.go
  dm/tests/_utils/test_prepare
  dm/tests/openapi/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#5369 DM/Openapi: improve password input mechanism source
  dm/dm/config/source_config.go
  dm/dm/config/source_converter.go
  dm/dm/master/openapi_controller.go
  dm/dm/master/openapi_controller_test.go
  dm/dm/master/openapi_view_test.go
  dm/dm/master/server.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/tests/openapi/client/openapi_source_check
  dm/tests/openapi/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#5350 tracker(dm): close and recreate tracker when pause and resume
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/worker/source_worker.go
  dm/errors.toml
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
  dm/pkg/shardddl/optimism/lock.go
  dm/pkg/terror/error_list.go
  dm/pkg/utils/db.go
  dm/pkg/utils/db_test.go
  dm/syncer/checkpoint.go
  dm/syncer/checkpoint_test.go
  dm/syncer/dbconn/db.go
  dm/syncer/dbconn/utils.go
  dm/syncer/schema.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/tests/_utils/check_sync_diff
  dm/tests/_utils/test_prepare
  dm/tests/checkpoint_transaction/run.sh
  dm/tests/dmctl_basic/conf/dm-task.yaml
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/dmctl_basic/run.sh
  dm/tests/expression_filter/run.sh
  dm/tests/handle_error_3/run.sh
  dm/tests/many_tables/conf/source1.yaml
  dm/tests/many_tables/run.sh
  dm/tests/new_relay/run.sh
  dm/tests/openapi/client/openapi_task_check
  dm/tests/relay_interrupt/run.sh
  dm/tests/s3_dumpling_lighting/run.sh
  dm/tests/sequence_sharding_optimistic/run.sh
  dm/tests/shardddl1/run.sh
  dm/tests/shardddl2_1/run.sh
  dm/tests/shardddl3_1/run.sh
  dm/tests/shardddl4/run.sh
  dm/tests/shardddl4_1/run.sh
  dm/tests/shardddl_optimistic/run.sh
  dm/tests/sync_collation/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0

#5419 tracker(dm): close and recreate tracker when pause and resume (#5350)
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/worker/source_worker.go
  dm/errors.toml
  dm/pkg/schema/tracker.go
  dm/pkg/terror/error_list.go
  dm/pkg/utils/db.go
  dm/pkg/utils/db_test.go
  dm/syncer/checkpoint.go
  dm/syncer/checkpoint_test.go
  dm/syncer/dbconn/db.go
  dm/syncer/schema.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/tests/_utils/check_sync_diff
  dm/tests/_utils/test_prepare
  dm/tests/dmctl_basic/conf/dm-task.yaml
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/dmctl_basic/run.sh
  dm/tests/expression_filter/run.sh
  dm/tests/handle_error_3/run.sh
  dm/tests/many_tables/conf/source1.yaml
  dm/tests/many_tables/run.sh
  dm/tests/new_relay/run.sh
  dm/tests/openapi/client/openapi_task_check
  dm/tests/relay_interrupt/run.sh
  dm/tests/sequence_sharding_optimistic/run.sh
  dm/tests/shardddl1/run.sh
  dm/tests/shardddl4/run.sh
Labels: status/LGT1, size/XL, do-not-merge/cherry-pick-not-approved, release-note

#5408 owner/(ticdc): fix the disorder problem for ddl events execution
  cdc/model/sink.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_sink.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#5396 cdc: move scheduler and agent to package base
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/agent.go
  cdc/scheduler/internal/base/agent.go
  cdc/scheduler/internal/base/agent_mock.go
  cdc/scheduler/internal/base/agent_test.go
  cdc/scheduler/internal/base/balancer.go
  cdc/scheduler/internal/base/balancer_test.go
  cdc/scheduler/internal/base/checkpoint_sender.go
  cdc/scheduler/internal/base/checkpoint_sender_test.go
  cdc/scheduler/internal/base/info_provider.go
  cdc/scheduler/internal/base/info_provider_test.go
  cdc/scheduler/internal/base/move_table_manager.go
  cdc/scheduler/internal/base/move_table_manager_test.go
  cdc/scheduler/internal/base/owner_scheduler.go
  cdc/scheduler/internal/base/owner_scheduler_test.go
  cdc/scheduler/internal/base/processor_agent.go
  cdc/scheduler/internal/base/processor_agent_test.go
  cdc/scheduler/internal/base/protocol/protocol.go
  cdc/scheduler/internal/base/protocol/protocol_test.go
  cdc/scheduler/internal/base/schedule_dispatcher.go
  cdc/scheduler/internal/base/schedule_dispatcher_test.go
  cdc/scheduler/internal/info_provider.go
  cdc/scheduler/internal/scheduler.go
  cdc/scheduler/internal/table_executor.go
  cdc/scheduler/internal/util/sort_table_ids.go
  cdc/scheduler/internal/util/table_set.go
  cdc/scheduler/internal/util/table_set_test.go
  cdc/scheduler/rexport.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#5401 syncer: fix dm skip mariadb event problem
  dm/syncer/syncer.go
  dm/tests/gtid/data/db1.increment.sql
  dm/tests/gtid/data/db1.increment2.sql
  dm/tests/gtid/data/db2.increment.sql
  dm/tests/gtid/data/db2.increment2.sql
  dm/tests/gtid/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#5389 upstream (ticdc): complete upstream and add unit tests
  cdc/api/validator.go
  cdc/capture/capture.go
  cdc/model/changefeed.go
  cdc/owner/changefeed.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/processor/manager.go
  cdc/processor/processor.go
  pkg/txnutil/gc/testing.go
  pkg/upstream/manager.go
  pkg/upstream/manager_test.go
  pkg/upstream/upstream.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#5383 test: fix binlog 999999 test
  dm/tests/incremental_mode/conf/dm-task.yaml
  dm/tests/incremental_mode/conf/source2.yaml
  dm/tests/incremental_mode/data/db1.prepare.sql
  dm/tests/incremental_mode/data/db2.prepare.sql
  dm/tests/incremental_mode/run.sh
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#5302 sink(ticdc): remove useless buffer sink and sink manager
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/sink/buffer_sink.go
  cdc/sink/buffer_sink_test.go
  cdc/sink/metrics/metrics.go
  cdc/sink/mq/dispatcher/partition/dispatcher.go
  cdc/sink/mq/dispatcher/partition/index_value.go
  cdc/sink/mq/dispatcher/partition/table.go
  cdc/sink/sink_manager.go
  cdc/sink/sink_manager_test.go
  cdc/sink/table_sink.go
  metrics/grafana/ticdc.json
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#5407 dmctl(dm): add more warnings and update help message
  dm/dm/ctl/master/check_task.go
  dm/dm/ctl/master/start_stop_relay.go
  dm/dm/ctl/master/start_task.go
  dm/tests/dmctl_basic/check_list/start_relay.sh
  dm/tests/dmctl_basic/check_list/stop_relay.sh
  dm/tests/dmctl_basic/conf/dm-task6.yaml
  dm/tests/dmctl_basic/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#5427 worker(dm): fix deadlock
  dm/dm/worker/source_worker.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#5428 sink(ticdc): refactor sink interface
  cdc/processor/pipeline/sink_test.go
  cdc/sink/black_hole.go
  cdc/sink/mq/mq.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/simple_mysql_tester.go
  cdc/sink/sink.go
  cdc/sink/table_sink.go
  pkg/applier/redo.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#5430 github(both): improve README.md and simplify PR templates
  .github/pull_request_template.md
  README.md
  README_TiCDC.md
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#5418 sink(ticdc): store checkpointTs by flushedResolvedTsMap in mysql sink
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/mysql_worker.go
  cdc/sink/mysql/txn_cache.go
  cdc/sink/mysql/txn_cache_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#5349 DM/Openapi: support start task by some conditions
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/config/task.go
  dm/dm/config/task_converters.go
  dm/dm/master/openapi_controller.go
  dm/dm/master/openapi_controller_test.go
  dm/errors.toml
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/pkg/ha/task_cli_args.go
  dm/pkg/ha/task_cli_args_test.go
  dm/pkg/terror/error_list.go
  dm/syncer/syncer.go
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5426 test(ticdc): add processor etcd worker delay fail point
  cdc/capture/capture.go
  pkg/chdelay/channel_delayer.go
  pkg/orchestrator/etcd_worker.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-6.0

#5281 sink(ticdc): make mysql sink support split transactions
  cdc/model/mounter.go
  cdc/model/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/sink/flowcontrol/flow_control.go
  cdc/sink/flowcontrol/flow_control_test.go
  cdc/sink/flowcontrol/table_memory_quota.go
  cdc/sink/mysql/txn_cache.go
Labels: status/LGT2, status/can-merge, size/L, release-note, area/ticdc

#5441 config(ticdc): Add alias for "dispatcher" in dispatch rules
  cdc/model/changefeed_test.go
  cdc/sink/mysql/txn_cache.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/util/changefeed.toml
  pkg/cmd/util/helper_test.go
  pkg/cmd/util/main_test.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#5450 cdc: implement replication set
  cdc/scheduler/internal/tp/balance_scheduler.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/replication_set_test.go
  cdc/scheduler/internal/tp/schedulepb/TableSchedule.pb.go
  pkg/errors/errors.go
  proto/TableSchedule.proto
Labels: component/scheduler, status/LGT1, size/XXL, release-note-none, area/ticdc

#5339 sink/codec(cdc): refactor Avro codec
  cdc/model/sink.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/avro_test_data.go
  cdc/sink/codec/canal.go
  cdc/sink/codec/canal_flat.go
  cdc/sink/codec/canal_flat_test.go
  cdc/sink/codec/canal_test.go
  cdc/sink/codec/codec_test.go
  cdc/sink/codec/config.go
  cdc/sink/codec/config_test.go
  cdc/sink/codec/craft.go
  cdc/sink/codec/craft_test.go
  cdc/sink/codec/interface.go
  cdc/sink/codec/json.go
  cdc/sink/codec/json_test.go
  cdc/sink/codec/maxwell.go
  cdc/sink/codec/maxwell_test.go
  cdc/sink/codec/schema_registry.go
  cdc/sink/codec/schema_registry_test.go
  cdc/sink/mq/dispatcher/event_router.go
  cdc/sink/mq/dispatcher/topic/expression.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_flush_worker.go
  cdc/sink/mq/mq_flush_worker_test.go
  cdc/sink/mq/producer/kafka/config_test.go
  go.mod
  go.sum
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/config/config_test_data.go
  pkg/config/mq_sink_protocol.go
  pkg/config/mq_sink_protocol_test.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/server_config_test.go
  tests/mq_protocol_tests/framework/avro/kafka_docker_env_test.go
  tests/mq_protocol_tests/framework/avro/kafka_single_table.go
  tests/mq_protocol_tests/framework/task.go
  tests/mq_protocol_tests/main.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#5451 sink/codec(cdc): add message size check and support schema default
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/model/sink.go
  cdc/sink/codec/avro.go
  cdc/sink/codec/avro_test.go
  cdc/sink/codec/schema_registry.go
  tests/integration_tests/multi_changefeed/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#5413 ticdc(codec): add avro refactor design
  docs/design/2022-05-12-ticdc-avro-protocol-refactor.md
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#5384 validator(dm): enable validation querying when validator's stopped
  dm/dm/worker/server.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/source_worker_test.go
  dm/dm/worker/subtask.go
  dm/dm/worker/subtask_test.go
  dm/syncer/data_validator.go
  dm/syncer/data_validator_test.go
  dm/syncer/validator_checkpoint.go
  dm/tests/dmctl_command/conf/dm-task.yaml
  dm/tests/dmctl_command/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#5342 sink(ticdc): add batch field to resolveTs
  cdc/entry/mounter.go
  cdc/model/mounter.go
  cdc/processor/pipeline/cyclic_mark.go
  cdc/processor/pipeline/cyclic_mark_test.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/sink/black_hole.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_flush_worker.go
  cdc/sink/mq/mq_flush_worker_test.go
  cdc/sink/mq/mq_test.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/simple_mysql_tester.go
  cdc/sink/mysql/txn_cache.go
  cdc/sink/mysql/txn_cache_test.go
  cdc/sink/sink.go
  cdc/sink/table_sink.go
  cdc/sorter/leveldb/writer.go
  cdc/sorter/memory/entry_sorter.go
  cdc/sorter/memory/entry_sorter_test.go
  cdc/sorter/unified/heap_sorter.go
  cdc/sorter/unified/merger.go
  cdc/sorter/unified/unified_sorter.go
  cmd/kafka-consumer/main.go
  pkg/applier/redo.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#5456 sink(ticdc): move codec into mq and remove interface.go
  cdc/sink/mq/codec/avro.go
  cdc/sink/mq/codec/avro_test.go
  cdc/sink/mq/codec/avro_test_data.go
  cdc/sink/mq/codec/canal.go
  cdc/sink/mq/codec/canal_flat.go
  cdc/sink/mq/codec/canal_flat_test.go
  cdc/sink/mq/codec/canal_test.go
  cdc/sink/mq/codec/codec_test.go
  cdc/sink/mq/codec/config.go
  cdc/sink/mq/codec/config_test.go
  cdc/sink/mq/codec/craft.go
  cdc/sink/mq/codec/craft/buffer.go
  cdc/sink/mq/codec/craft/codec_test.go
  cdc/sink/mq/codec/craft/decoder.go
  cdc/sink/mq/codec/craft/encoder.go
  cdc/sink/mq/codec/craft/model.go
  cdc/sink/mq/codec/craft_test.go
  cdc/sink/mq/codec/decoder.go
  cdc/sink/mq/codec/encoder.go
  cdc/sink/mq/codec/java.go
  cdc/sink/mq/codec/json.go
  cdc/sink/mq/codec/json_test.go
  cdc/sink/mq/codec/main_test.go
  cdc/sink/mq/codec/maxwell.go
  cdc/sink/mq/codec/maxwell_test.go
  cdc/sink/mq/codec/message.go
  cdc/sink/mq/codec/message_test.go
  cdc/sink/mq/codec/schema_registry.go
  cdc/sink/mq/codec/schema_registry_test.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_flush_worker.go
  cdc/sink/mq/mq_flush_worker_test.go
  cdc/sink/mq/mq_test.go
  cdc/sink/mq/producer/kafka/config_test.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  cdc/sink/mq/producer/mq_producer.go
  cdc/sink/mq/producer/pulsar/producer.go
  cmd/kafka-consumer/main.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#5447 ui(dm): spec v3 updates
  .gitignore
  dm/ui/locales/en.json
  dm/ui/locales/zh.json
  dm/ui/package.json
  dm/ui/public/mockServiceWorker.js
  dm/ui/src/components/CreateOrUpdateTask/index.tsx
  dm/ui/src/layouts/SiderMenu.tsx
  dm/ui/src/main.tsx
  dm/ui/src/mock.ts
  dm/ui/src/models/task.ts
  dm/ui/src/pages/index.tsx
  dm/ui/src/pages/migration/task/index.tsx
  dm/ui/vite.config.js
  dm/ui/yarn.lock
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5461 sink/mq/codec(ticdc): remove useless Size interface of encoder
  cdc/sink/mq/codec/avro.go
  cdc/sink/mq/codec/canal.go
  cdc/sink/mq/codec/canal_flat.go
  cdc/sink/mq/codec/canal_test.go
  cdc/sink/mq/codec/craft.go
  cdc/sink/mq/codec/encoder.go
  cdc/sink/mq/codec/json.go
  cdc/sink/mq/codec/maxwell.go
  cdc/sink/mq/codec/maxwell_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#5390 DM/Openapi: use reverse proxy instead of redirect
  dm/dm/master/openapi_view.go
  dm/dm/master/openapi_view_test.go
  dm/dm/master/server.go
  dm/tests/openapi/client/openapi_source_check
  dm/tests/openapi/run.sh
  dm/tests/openapi/tls_conf/ca.pem
  dm/tests/openapi/tls_conf/dm-master1.toml
  dm/tests/openapi/tls_conf/dm-master2.toml
  dm/tests/openapi/tls_conf/dm-worker1.toml
  dm/tests/openapi/tls_conf/dm-worker2.toml
  dm/tests/openapi/tls_conf/dm.key
  dm/tests/openapi/tls_conf/dm.pem
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4

#5457 docs(ticdc): update TiCDC integration test readme
  tests/integration_tests/README.md
Labels: component/docs, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#5386 sink(ticdc): fix broken test in cdc/sink/mq & migrate test-infra to testify
  cdc/sink/mq/dispatcher/main_test.go
  cdc/sink/mq/dispatcher/partition/main_test.go
  cdc/sink/mq/dispatcher/topic/main_test.go
  cdc/sink/mq/main_test.go
  cdc/sink/mq/manager/kafka_manager.go
  cdc/sink/mq/manager/kafka_manager_test.go
  cdc/sink/mq/manager/main_test.go
  cdc/sink/mq/manager/pulsar_manager.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_flush_worker_test.go
  cdc/sink/mq/mq_test.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  cdc/sink/mq/producer/kafka/main_test.go
  pkg/kafka/cluster_admin_client_mock_impl.go
  pkg/leakutil/leak_helper.go
Labels: component/sink, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#5399 DNM *(ticdc): etcd key add cluster id and namespace
  cdc/api/status.go
  cdc/capture/capture.go
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner_test.go
  cdc/processor/manager_test.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/base/processor_agent.go
  cdc/scheduler/internal/base/processor_agent_test.go
  pkg/cmd/cli/cli_capture_list.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_changefeed_statistics.go
  pkg/cmd/cli/cli_processor_query.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/etcdkey.go
  pkg/etcd/etcdkey_test.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/reactor_state.go
  pkg/orchestrator/reactor_state_test.go
  tests/integration_tests/capture_session_done_during_task/run.sh
  tests/integration_tests/capture_suicide_while_balance_table/run.sh
  tests/utils/cdc_state_checker/cdc_monitor.go
  tests/utils/cdc_state_checker/state.go
Labels: size/XXL, release-note-none

#5412 DNM *(ticdc): cli support cdc cluster
  cdc/api/status.go
  cdc/capture/capture.go
  cdc/capture/capture_test.go
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner_test.go
  cdc/processor/manager_test.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/base/processor_agent.go
  cdc/scheduler/internal/base/processor_agent_test.go
  cdc/server.go
  cdc/server_test.go
  pkg/cmd/cli/cli_capture_list.go
  pkg/cmd/factory/factory.go
  pkg/cmd/factory/factory_impl.go
  pkg/cmd/server/server.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/etcdkey.go
  pkg/etcd/etcdkey_test.go
  pkg/orchestrator/reactor_state.go
  pkg/orchestrator/reactor_state_test.go
  tests/integration_tests/move_table/main.go
  tests/utils/cdc_state_checker/cdc_monitor.go
  tests/utils/cdc_state_checker/state.go
Labels: size/XL, component/cli, release-note-none, area/ticdc

#5473 tests: use python3 to run http_api test to fix failed integration_tests
  tests/integration_tests/http_api/run.sh
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#5469 sink/codc(ticdc): fix schema-registry options in cli & config file
  cdc/sink/mq/codec/config.go
  cdc/sink/mq/codec/config_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_changefeed_update_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/sink.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#5444 DNM gc(ticdc): gc service id refactor
  cdc/api/validator.go
  cdc/capture/capture.go
  cdc/capture/capture_test.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/owner_test.go
  cdc/scheduler/internal/base/processor_agent_test.go
  cdc/server.go
  cdc/server_test.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_unsafe_delete_service_gc_safepoint.go
  pkg/cmd/cli/cli_unsafe_reset.go
  pkg/cmd/factory/factory_impl.go
  pkg/context/context.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_manager_test.go
  pkg/txnutil/gc/gc_service.go
  pkg/txnutil/gc/gc_service_test.go
  pkg/upstream/manager.go
  pkg/upstream/upstream.go
  tests/integration_tests/gc_safepoint/run.sh
  tests/integration_tests/move_table/main.go
Labels: size/L, release-note-none

#5483 open (ticdc): fix openapi do not work on non-owner node
  cdc/api/open.go
  pkg/httputil/httputil.go
Labels: status/LGT2, status/can-merge, size/XS, release-note

#5476 dm: parse start-time using upstream timezone
  dm/syncer/syncer.go
  dm/syncer/util.go
  dm/tests/openapi/run.sh
  dm/tests/start_task/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-6.0

#5487 test(dm): fix test script syntax and refactor
  dm/tests/_utils/kill_dm_master
  dm/tests/_utils/kill_dm_worker
  dm/tests/_utils/test_prepare
  dm/tests/_utils/wait_process_exit
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#5495 fix(prometheus): revert prometheus client_golang from from v1.12.2 to v1.11.0
  engine/pkg/promutil/registry.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#5462 scheduler(cdc): table executor support 2 phase scheduling
  cdc/processor/manager_test.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/base/agent.go
  cdc/scheduler/internal/base/agent_mock.go
  cdc/scheduler/internal/base/processor_agent.go
  cdc/scheduler/internal/base/protocol/protocol.go
  cdc/scheduler/internal/table_executor.go
  cdc/scheduler/internal/tp/transport.go
  cdc/sorter/leveldb/message/task.go
  cdc/sorter/leveldb/reader.go
  cdc/sorter/leveldb/sorter.go
  cdc/sorter/memory/entry_sorter.go
  cdc/sorter/sorter.go
  cdc/sorter/unified/unified_sorter.go
  pkg/config/db.go
  pkg/pipeline/pipeline.go
  tools/check/go.sum
Labels: size/XXL, release-note-none

#5506 sink/mysql(ticdc): rename syncpointStore.go to syncpoint_store.go
  cdc/sink/mysql/syncpoint_store.go
Labels: component/sink, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/ticdc

#5499 config(ticdc): use 1 minute kv retry time
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
Labels: component/kv-client, status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc, affects-5.3, affects-5.2, affects-5.1, affects-5.0, affects-4.0, needs-cherry-pick-release-5.4, affects-5.4, affects-6.0, needs-cherry-pick-release-6.0, affects-6.1

#5246 pkg/gtid: remove gtid.Set interface
  dm/dm/worker/relay_test.go
  dm/dm/worker/server_test.go
  dm/dm/worker/source_worker.go
  dm/dm/worker/subtask.go
  dm/dm/worker/subtask_test.go
  dm/pkg/binlog/event/common.go
  dm/pkg/binlog/event/common_test.go
  dm/pkg/binlog/event/ddl.go
  dm/pkg/binlog/event/dml.go
  dm/pkg/binlog/event/event.go
  dm/pkg/binlog/event/event_test.go
  dm/pkg/binlog/event/generator.go
  dm/pkg/binlog/event/generator_test.go
  dm/pkg/binlog/event/helper.go
  dm/pkg/binlog/pos_finder.go
  dm/pkg/binlog/position.go
  dm/pkg/binlog/position_test.go
  dm/pkg/binlog/reader/file.go
  dm/pkg/binlog/reader/file_test.go
  dm/pkg/binlog/reader/mock.go
  dm/pkg/binlog/reader/reader.go
  dm/pkg/binlog/reader/tcp.go
  dm/pkg/binlog/reader/tcp_test.go
  dm/pkg/binlog/reader/util.go
  dm/pkg/dumpling/utils.go
  dm/pkg/gtid/gtid.go
  dm/pkg/gtid/gtid_test.go
  dm/pkg/utils/db.go
  dm/pkg/utils/db_test.go
  dm/pkg/v1dbschema/schema.go
  dm/relay/file_util.go
  dm/relay/local_reader.go
  dm/relay/local_reader_test.go
  dm/relay/meta.go
  dm/relay/meta_test.go
  dm/relay/relay.go
  dm/relay/relay_test.go
  dm/relay/upstream_reader.go
  dm/syncer/binlog_locations.go
  dm/syncer/binlog_locations_test.go
  dm/syncer/causality_test.go
  dm/syncer/checkpoint.go
  dm/syncer/checkpoint_test.go
  dm/syncer/compactor_test.go
  dm/syncer/data_validator_test.go
  dm/syncer/dbconn/upstream_db.go
  dm/syncer/ddl_test.go
  dm/syncer/err-operator/operator.go
  dm/syncer/filter_test.go
  dm/syncer/job_test.go
  dm/syncer/sharding-meta/shardmeta.go
  dm/syncer/streamer_controller.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/syncer/validator_checkpoint.go
  dm/syncer/validator_checkpoint_test.go
  dm/tests/_dmctl_tools/check_exit_safe_binlog.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5507 DM: Fix some unstable tests
  dm/tests/_utils/test_prepare
  dm/tests/full_mode/run.sh
  dm/tests/shardddl2/run.sh
  dm/tests/shardddl4_1/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#5516 test(engine): fix start etcd test failure because of duplicated free port
  engine/servermaster/etcd_test.go
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#5502 metric[engine]: framework support metric interface
  engine/lib/base_jobmaster.go
  engine/lib/base_jobmaster_test.go
  engine/lib/common.go
  engine/lib/master.go
  engine/lib/mock_master_impl.go
  engine/lib/mock_master_util.go
  engine/lib/mock_worker_util.go
  engine/lib/registry/registry.go
  engine/lib/worker.go
  engine/pkg/promutil/implement_test.go
  engine/pkg/promutil/util.go
  engine/pkg/promutil/util_inner.go
  engine/pkg/promutil/util_inner_test.go
  engine/servermaster/jobmanager.go
  engine/servermaster/server_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5522 contributing(all): update minimal go version, add engine in commit message
  .github/ISSUE_TEMPLATE/engine-bug-report.yml
  CONTRIBUTING.md
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#5537 ci(engine,dm): enable dataflow engine e2e test in dm
  .github/workflows/dataflow_engine_e2e.yaml
Labels: status/ptal, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/engine

#5470 test(ticdc): add processor etcd worker delay integration test
  tests/integration_tests/processor_etcd_worker_delay/conf/diff_config.toml
  tests/integration_tests/processor_etcd_worker_delay/run.sh
Labels: component/test, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc, needs-cherry-pick-release-6.0

#5501 ci(engine): support verify ci for dataflow engine
  .codecov.yml
  Makefile
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#5514 externalresources(engine): Miscellaneous changes required for implementing resource GC.
  engine/model/cluster.go
  engine/pkg/externalresource/manager/interfaces.go
  engine/pkg/externalresource/manager/mock_client.go
  engine/pkg/externalresource/manager/mock_executor_info_provider.go
  engine/pkg/externalresource/manager/service_test.go
  engine/pkg/externalresource/manager/test_utils.go
  engine/pkg/externalresource/resourcemeta/model/model.go
  engine/pkg/orm/client.go
  engine/pkg/orm/client_test.go
  engine/servermaster/executor_manager.go
  engine/servermaster/server_test.go
  go.mod
  go.sum
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5520 lib/worker(engine): refactor BaseWorker (Part I)
  engine/dm/dump_worker.go
  engine/dm/load_worker.go
  engine/dm/sync_worker.go
  engine/executor/cvsTask/cvstask.go
  engine/jobmaster/cvsJob/cvsJobMaster.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/example/worker_impl.go
  engine/lib/base_jobmaster.go
  engine/lib/base_jobmaster_test.go
  engine/lib/fake/fake_master.go
  engine/lib/fake/fake_worker.go
  engine/lib/mock_worker_impl.go
  engine/lib/statusutil/master_info.go
  engine/lib/statusutil/writer.go
  engine/lib/worker.go
  engine/lib/worker/master_client.go
  engine/lib/worker/master_client_test.go
  engine/lib/worker_test.go
  engine/pkg/p2p/mock_message_sender.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5562 tp: implement capture manager
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/balance_scheduler.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/capture_manager_test.go
  cdc/scheduler/internal/tp/capture_status.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/drain_scheduler.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/replication_set_test.go
  cdc/scheduler/internal/tp/schedulepb/table_schedule.pb.go
  cdc/scheduler/internal/tp/transport.go
  cdc/scheduler/internal/tp/transport_test.go
  errors.toml
  proto/table_schedule.proto
  scripts/check-diff-line-width.sh
  scripts/generate-protobuf.sh
  tools/check/check-errdoc.sh
Labels: component/scheduler, status/LGT1, size/XXL, release-note-none, area/ticdc

#5561 worker[engine]: fix bug that worker impl call 'Exit', but may not return
  engine/lib/worker.go
  engine/lib/worker_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5549 api(ticdc): refactor api packages
  Makefile
  cdc/api/middleware/middleware.go
  cdc/api/owner/main_test.go
  cdc/api/owner/owner.go
  cdc/api/owner/owner_test.go
  cdc/api/status/status.go
  cdc/api/util.go
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/api/v1/main_test.go
  cdc/api/validator/validator.go
  cdc/api/validator/validator_test.go
  cdc/http.go
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/cmd/cli/cli_changefeed_list.go
  pkg/cmd/cli/cli_changefeed_resume.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#5526 metric[engine]:Replace framework metric
  engine/executor/http.go
  engine/executor/metrics.go
  engine/executor/metrics_server.go
  engine/executor/server.go
  engine/executor/server_test.go
  engine/lib/base_jobmaster.go
  engine/lib/master.go
  engine/lib/worker.go
  engine/pkg/promutil/implement.go
  engine/pkg/promutil/implement_test.go
  engine/pkg/promutil/util.go
  engine/servermaster/metrics.go
  engine/servermaster/metrics_server.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5550 config(engine): imitate adjust DM source config
  dm/dm/master/openapi_controller.go
  dm/dm/master/openapi_controller_test.go
  dm/dm/master/openapi_view_test.go
  dm/dm/master/server.go
  engine/jobmaster/dm/checkpoint/agent_test.go
  engine/jobmaster/dm/config/config.go
  engine/jobmaster/dm/config/config_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/message_agent_test.go
  engine/jobmaster/dm/metadata/job.go
  engine/jobmaster/dm/metadata/job_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5559 jobmanager(engine):support WatchJobStatuses
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  engine/servermaster/server_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5581 e2e(engine): test two running DM jobs
  engine/test/e2e/dm-job.yaml
  engine/test/e2e/e2e_dm_test.go
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/engine

#5557 externalresources(engine): implement GCCoordinator & GCRunner
  engine/pkg/externalresource/manager/gc_coordinator.go
  engine/pkg/externalresource/manager/gc_coordinator_test.go
  engine/pkg/externalresource/manager/gc_runner.go
  engine/pkg/externalresource/manager/gc_runner_test.go
  engine/pkg/externalresource/manager/service_test.go
  engine/pkg/externalresource/resourcemeta/model/model.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5552 DM(dmctl/openapi): fix incremental task's source meta check
  dm/dm/config/task.go
  dm/dm/master/openapi_controller_test.go
  dm/dm/master/server.go
  dm/tests/dmctl_basic/check_list/check_task.sh
  dm/tests/dmctl_basic/check_list/start_task.sh
  dm/tests/dmctl_basic/conf/dm-task7.yaml
  dm/tests/dmctl_basic/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm, needs-cherry-pick-release-6.1

#5565 executer_manager(engine): Support watching executor online/offline events
  engine/servermaster/executor_manager.go
  engine/servermaster/executor_manager_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#5553 sink/mq(ticdc): Add support for Confluent Cloud Kafka
  cdc/sink/mq/dispatcher/event_router.go
  cdc/sink/mq/producer/kafka/config.go
  cdc/sink/mq/producer/kafka/config_test.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  errors.toml
  pkg/errors/errors.go
  pkg/kafka/cluster_admin_client_mock_impl.go
  pkg/logutil/log.go
  pkg/security/credential.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.1

#5583 kv(ticdc): fix data loss when upstream txn conflicts during scan (#5477)
  cdc/entry/mounter.go
  cdc/kv/client.go
  cdc/kv/matcher.go
  cdc/kv/matcher_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/model/kv.go
  cdc/model/kv_test.go
Labels: component/kv-client, status/LGT1, size/XL, cherry-pick-approved, release-note, area/ticdc

#5524 server(cdc): avoid printing help messages when cdc server exits
  pkg/cmd/server/server.go
  tests/integration_tests/_utils/check_usage_tips
  tests/integration_tests/_utils/run_cdc_server
  tests/integration_tests/cdc_server_tips/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, needs-cherry-pick-release-6.1

#5603 lib/master(engine): fix PreDispatch failure handling
  engine/client/task_dispatcher.go
  engine/client/task_dispatcher_test.go
  engine/lib/master/worker_manager_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/M, release-note-none

#5601 codec(ticdc): use handlekey instead of primary key for avro
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/sink/mq/codec/avro.go
  cdc/sink/mq/codec/avro_test.go
  tests/mq_protocol_tests/cases/case_handle_key.go
  tests/mq_protocol_tests/main.go
Labels: status/can-merge, status/LGT3, require-LGT3, size/L, release-note-none, needs-cherry-pick-release-6.1

#5585 api(ticdc): setup open api v2
  cdc/api/v2/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  cdc/http.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#5582 dm: fix typo
  dm/CHANGELOG.md
  dm/checker/cmd.go
  dm/dm/worker/subtask.go
  dm/loader/loader.go
  dm/tests/initial_unit/run.sh
Labels: status/ptal, status/LGT1, status/can-merge, size/XXL, require-LGT1, release-note-none, area/dm

#5606 tp: implement replicationManager
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/capture_manager_test.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/coordinator_test.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_manager_test.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/replication_set_test.go
  cdc/scheduler/internal/tp/schedulepb/table_schedule.pb.go
  cdc/scheduler/internal/tp/schedulepb/table_schedule_manual_test.go
  pkg/config/debug.go
  pkg/config/scheduler_config.go
  pkg/config/server_config.go
  pkg/config/server_config_test.go
  proto/table_schedule.proto
Labels: component/scheduler, status/LGT1, size/XXL, release-note-none, area/ticdc

#5452 syncer: fix table checkpoint panic problem
  dm/syncer/job.go
  dm/syncer/opt_sharding_group.go
  dm/syncer/opt_sharding_group_test.go
  dm/syncer/optimist.go
  dm/syncer/shardddl/optimist.go
  dm/syncer/syncer.go
  dm/syncer/util.go
  dm/tests/_utils/shardddl_lib.sh
  dm/tests/_utils/test_prepare
  dm/tests/shardddl2_1/run.sh
  dm/tests/shardddl4_1/conf/diff_config.toml
  dm/tests/shardddl4_1/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5130 dm/ha: rolling update support to new etcd keys
  dm/dm/common/common.go
  dm/dm/ctl/master/config.go
  dm/pkg/ha/relay.go
  dm/pkg/upgrade/upgrade.go
  dm/pkg/upgrade/upgrade_test.go
  go.mod
Labels: status/LGT2, size/L, release-note-none, area/dm

#5600 pipeline(ticdc): fix table actor cyclic node bug
  cdc/processor/pipeline/table_actor.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-6.1

#5534 validator(dm): support start from time & fix & integration test
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/config/task.go
  dm/dm/config/task_cli_args.go
  dm/dm/ctl/master/start_stop_validation.go
  dm/dm/master/scheduler/scheduler.go
  dm/dm/master/scheduler/scheduler_test.go
  dm/dm/master/server.go
  dm/dm/master/server_test.go
  dm/dm/pb/dmmaster.pb.go
  dm/dm/pb/dmworker.pb.go
  dm/dm/proto/dmmaster.proto
  dm/dm/proto/dmworker.proto
  dm/dm/worker/source_worker.go
  dm/dm/worker/subtask.go
  dm/errors.toml
  dm/pkg/binlog/filename.go
  dm/pkg/binlog/filename_test.go
  dm/pkg/terror/error_list.go
  dm/pkg/utils/time.go
  dm/pkg/utils/time_test.go
  dm/syncer/data_validator.go
  dm/syncer/data_validator_test.go
  dm/syncer/syncer.go
  dm/syncer/validate_worker_test.go
  dm/syncer/validator_checkpoint.go
  dm/syncer/validator_checkpoint_test.go
  dm/tests/dmctl_command/conf/dm-task-no-validator.yaml
  dm/tests/dmctl_command/conf/dm-task2-no-validator.yaml
  dm/tests/dmctl_command/run.sh
  dm/tests/validator_basic/conf/dm-task-standalone-no-validator.yaml
  dm/tests/validator_basic/conf/dm-worker2.toml
  dm/tests/validator_basic/conf/source1.yaml
  dm/tests/validator_basic/data/db1.increment.sql
  dm/tests/validator_basic/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5595 redo(ticdc): use uuid in s3 log file to avoid name conflict
  cdc/redo/common/util.go
  cdc/redo/common/util_test.go
  cdc/redo/reader/file_test.go
  cdc/redo/reader/reader_test.go
  cdc/redo/writer/file.go
  cdc/redo/writer/file_test.go
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
  engine/executor/server_test.go
  engine/lib/master.go
  engine/lib/master_test.go
  engine/lib/mock_master_util.go
  engine/pkg/orm/mock.go
  engine/servermaster/executor_manager.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  pkg/uuid/mock.go
  pkg/uuid/uuid.go
  pkg/uuid/uuid_test.go
Labels: status/ptal, type/bugfix, status/LGT2, status/can-merge, size/XL, release-note, component/redolog, needs-cherry-pick-release-5.3, area/ticdc, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#5596 externalresource(engine): Integrate all parts related to GC (Part I)
  engine/client/base_executor_client.go
  engine/client/executor_client.go
  engine/client/mock_clients.go
  engine/pkg/externalresource/integration_test/cluster_stub.go
  engine/pkg/externalresource/integration_test/gc_test.go
  engine/pkg/externalresource/integration_test/mock_cluster.go
  engine/pkg/externalresource/manager/gc_coordinator.go
  engine/pkg/externalresource/manager/gc_coordinator_test.go
  engine/pkg/externalresource/manager/gc_runner.go
  engine/pkg/externalresource/manager/gc_runner_test.go
  engine/pkg/externalresource/manager/interfaces.go
  engine/pkg/externalresource/resourcetypes/interfaces.go
  engine/pkg/externalresource/resourcetypes/local_file.go
  engine/pkg/externalresource/resourcetypes/local_file_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5547 test(pkg/cmd): migrate test-infra to testify for pkg/cmd
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/cmd/cli/cli_changefeed_helper_test.go
  pkg/cmd/cli/cli_changefeed_update_test.go
  pkg/cmd/cli/cli_test.go
  pkg/cmd/cli/main_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#5587 redo(ticdc): fix resolved moves too fast when part of tables are not maintained redo writer
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/writer/blackhole_writer.go
Labels: status/ptal, type/bugfix, status/LGT2, status/can-merge, size/M, release-note, component/redolog, needs-cherry-pick-release-5.3, area/ticdc, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#5566 relay, syncer(dm): rename UUIDSuffix to RelaySubDirSuffix and others
  dm/dm/worker/source_worker.go
  dm/pkg/binlog/filename.go
  dm/pkg/binlog/position.go
  dm/pkg/binlog/position_test.go
  dm/pkg/streamer/hub.go
  dm/pkg/streamer/hub_test.go
  dm/pkg/utils/relay.go
  dm/pkg/utils/relay_test.go
  dm/relay/local_reader.go
  dm/relay/local_reader_test.go
  dm/relay/meta.go
  dm/relay/meta_test.go
  dm/relay/purge_strategy.go
  dm/relay/purger_helper.go
  dm/relay/purger_helper_test.go
  dm/relay/purger_test.go
  dm/relay/relay.go
  dm/relay/relay_test.go
  dm/relay/util.go
  dm/relay/util_test.go
  dm/syncer/relay.go
  dm/syncer/streamer_controller.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#5592 pipeline(ticdc): delete pipeline and node runner
  cdc/capture/capture.go
  cdc/processor/pipeline/cyclic_mark.go
  cdc/processor/pipeline/cyclic_mark_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/processor.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  pkg/pipeline/context.go
  pkg/pipeline/node.go
  pkg/pipeline/pipeline.go
  pkg/pipeline/pipeline_test.go
  pkg/pipeline/runner.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#5393 tls(dm): support init tls without client kay/certs
  cdc/entry/codec.go
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/entry/schema_storage_test.go
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/puller/mock_puller.go
  cdc/sink/mq/codec/avro.go
  cdc/sink/mq/codec/avro_test.go
  cdc/sink/mq/codec/message_test.go
  dm/pkg/conn/basedb.go
  dm/pkg/schema/tracker.go
  dm/pkg/shardddl/optimism/lock.go
  dm/relay/relay.go
  dm/syncer/ddl.go
  dm/syncer/dml.go
  dm/syncer/dml_test.go
  dm/syncer/util.go
  dm/syncer/validate_worker.go
  dm/syncer/validate_worker_test.go
  dm/tests/_utils/wait_process_exit
  dm/tests/tls/conf/source-only-ca.yaml
  dm/tests/tls/run.sh
  go.mod
  go.sum
  pkg/sqlmodel/where_handle.go
  tests/integration_tests/dailytest/db.go
  tests/integration_tests/dailytest/job.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/dm, area/ticdc, needs-cherry-pick-release-6.1

#5621 redo(ticdc): fix a bug that flush log executed before writing logs
  cdc/redo/manager.go
  cdc/redo/manager_test.go
Labels: status/ptal, type/bugfix, status/LGT2, status/can-merge, size/L, release-note, component/redolog, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#5638 test(ticdc): fix log suffix in run_cdc_server script
  tests/integration_tests/_utils/run_cdc_server
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc, needs-cherry-pick-release-6.1

#5623 externalresource(engine): implement Discard local resource & OnWorkerClosed
  engine/lib/worker.go
  engine/pkg/errors/errors.go
  engine/pkg/externalresource/broker/broker.go
  engine/pkg/externalresource/broker/broker_test.go
  engine/pkg/externalresource/broker/file_manager.go
  engine/pkg/externalresource/broker/file_manager_test.go
  engine/pkg/externalresource/broker/interfaces.go
  engine/pkg/externalresource/broker/local_broker.go
  engine/pkg/externalresource/broker/local_file_utils.go
  engine/pkg/externalresource/broker/local_resource_desc.go
  engine/pkg/externalresource/broker/storage_handle.go
  engine/pkg/externalresource/broker/storage_handle_test.go
  engine/pkg/externalresource/integration_test/gc_test.go
  errors.toml
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#5643 metrics(*): fix for promtheus_client breaking change
  cdc/metrics.go
  dm/dm/worker/metrics.go
  engine/pkg/promutil/registry.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-6.1

#5651 test(engine): remove unit test from Github Action.
  .github/workflows/dataflow_engine_ut.yaml
  engine/.github/workflows/dataflow_engine_chaos.yaml
  engine/.github/workflows/dataflow_engine_e2e.yaml
  engine/.github/workflows/dfe_check_and_build.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5660 test: use `T.TempDir` to create temporary test directory
  cdc/owner/changefeed_test.go
  cdc/redo/reader/file_test.go
  cdc/redo/reader/reader_test.go
  cdc/redo/writer/file_test.go
  cdc/redo/writer/writer_test.go
  dm/pkg/storage/utils_test.go
  dm/relay/meta_test.go
  dm/relay/purger_helper_test.go
  dm/relay/purger_test.go
  dm/syncer/checkpoint_test.go
  engine/pkg/etcdutils/join_test.go
  engine/servermaster/etcd_test.go
  engine/servermaster/server_test.go
  pkg/cmd/util/helper_test.go
  pkg/etcd/client_test.go
  pkg/etcd/etcd_test.go
  pkg/logutil/log_test.go
  pkg/orchestrator/etcd_worker_test.go
Labels: status/LGT2, status/can-merge, first-time-contributor, size/L, contribution, release-note-none

#5662 engine: normalize the csv job package path name
  engine/executor/init.go
  engine/jobmaster/cvsjob/cvs_job_master.go
  engine/jobmaster/cvsjob/cvs_job_master_test.go
  engine/servermaster/jobmanager.go
  engine/test/e2e/e2e_test.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#5657 sink/mq(ticdc): flush waits for all events to be acked
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_flush_worker.go
  cdc/sink/mq/mq_flush_worker_test.go
  cdc/sink/mq/producer/kafka/kafka.go
Labels: status/can-merge, status/LGT3, require-LGT3, size/L, release-note, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#5593 scheduler(2pc): agent for 2 phase scheduling
  cdc/processor/manager_test.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/base/agent.go
  cdc/scheduler/internal/base/agent_mock.go
  cdc/scheduler/internal/table_executor.go
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/agent_bench_test.go
  cdc/scheduler/internal/tp/agent_test.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/coordinator_test.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/schedulepb/table_schedule.pb.go
  cdc/scheduler/internal/tp/schedulepb/table_schedule_manual_test.go
  cdc/scheduler/internal/tp/transport.go
  cdc/scheduler/internal/tp/transport_test.go
  pkg/config/config_test_data.go
  proto/table_schedule.proto
Labels: component/scheduler, status/LGT1, size/XXL, release-note-none, area/ticdc

#5654 lib/worker(engine): Move ExitController to another package and add UT
  engine/lib/statusutil/writer.go
  engine/lib/statusutil/writer_test.go
  engine/lib/worker.go
  engine/lib/worker/exit_controller.go
  engine/lib/worker/exit_controller_test.go
  engine/lib/worker/master_info.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#5667 test(dm): show full result of ps on kill fail
  dm/tests/_utils/wait_process_exit
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#5674 tp: support capture init and shutdown
  cdc/processor/pipeline/table.go
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/agent_test.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/capture_manager_test.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/coordinator_test.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_manager_test.go
  cdc/scheduler/internal/tp/replication_set.go
  cdc/scheduler/internal/tp/replication_set_test.go
  cdc/scheduler/internal/tp/schedulepb/table_schedule_manual_test.go
Labels: component/scheduler, status/LGT1, size/XXL, release-note-none, area/ticdc

#5672 promutil(engine): avoid embedding Mutex and prometheus.Registry in Registry
  engine/pkg/promutil/registry.go
  engine/pkg/promutil/registry_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#5676 tp: support basic balance tables
  cdc/scheduler/internal/tp/balance_scheduler.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/capture_manager_test.go
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/replication_manager_test.go
  cdc/scheduler/internal/tp/scheduler_balance.go
  cdc/scheduler/internal/tp/scheduler_balance_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
Labels: component/scheduler, status/LGT1, size/XL, release-note-none, area/ticdc
