Repository pingcap/tiflow, pull requests merged in 2022-12, with the labels that each got.

#7759 sink(ticdc): Fix a slice overwriting problem
  cdc/sinkv2/eventsink/cloudstorage/dml_worker.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#7748 processor/sourcemanager(ticdc): add sorter stats
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sourcemanager/engine/engine.go
  cdc/processor/sourcemanager/engine/memory/event_sorter.go
  cdc/processor/sourcemanager/engine/mock/engine_mock.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/manager.go
Labels: status/LGT2, status/can-merge, size/XL, component/sorter, release-note-none, area/ticdc

#7769 processor/sourcemanager(ticdc): move mounted iter into sourceManager
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sourcemanager/manager.go
Labels: status/LGT2, status/can-merge, size/L, component/sorter, release-note-none, area/ticdc

#7726 syncer(dm): fix log error caused by "COMMIT" in QueryEvent
  dm/syncer/syncer.go
  dm/tests/start_task/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.1

#7730 cdc: add delay for recreating changefeed
  cdc/api/v1/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/owner/mock/owner_mock.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  tests/integration_tests/run.sh
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#7733 checker(dm): port free space lightning precheck
  dm/checker/check_test.go
  dm/checker/checker.go
  dm/config/checking_item.go
  dm/config/checking_item_test.go
  dm/config/source_converter_test.go
  dm/config/task.go
  dm/config/task_test.go
  dm/pkg/checker/lightning.go
  dm/pkg/checker/table_structure.go
  dm/pkg/utils/common.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
  dm/tests/lightning_mode/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#7777 processor(ticdc): cancel the context before closing the processor
  cdc/processor/manager.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sourcemanager/manager.go
  cdc/sinkv2/eventsink/txn/worker.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#7802 test(cdc): fix canal integration
  scripts/canal/docker/Dockerfile
Labels: component/test, status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc

#7772 engine(metrics): add server monitor to engine
  metrics/grafana/tiflow.json
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/engine

#7807 log(engine): update logger in worker manager
  engine/framework/internal/master/worker_manager.go
  engine/framework/internal/master/worker_manager_test.go
  engine/framework/master.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7791 mq(ticdc): fix unstable unit test batch encode
  cdc/sinkv2/eventsink/mq/worker_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#7810 Makefile,scripts: speed up make fmt and fix check-diff-line-width
  Makefile
  scripts/check-diff-line-width.sh
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/ticdc

#7723 scheduler(ticdc): add compat layer
  cdc/processor/tablepb/table.pb.go
  cdc/processor/tablepb/table.proto
  cdc/scheduler/internal/v3/compat/compat.go
  cdc/scheduler/internal/v3/compat/compat_test.go
  cdc/scheduler/schedulepb/table_schedule.pb.go
  cdc/scheduler/schedulepb/table_schedule.proto
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/scheduler_config.go
  pkg/config/server_config_test.go
  pkg/version/check.go
  pkg/version/check_test.go
  pkg/version/creator_version_gate.go
  pkg/version/version.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7811 fakejob(engine): refactor fake job based on master/worker framework
  engine/chaos/cases/case_fake_job.go
  engine/executor/fakejob/register.go
  engine/executor/fakejob/worker.go
  engine/executor/init.go
  engine/executor/server_test.go
  engine/jobmaster/fakejob/job_master.go
  engine/jobmaster/fakejob/register.go
  engine/pkg/fakejob/status.go
  engine/test/e2e/e2e_node_chaos_test.go
  engine/test/e2e/e2e_test_cli.go
  engine/test/e2e/e2e_worker_exit_test.go
Labels: status/ptal, status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none, area/engine

#7820 puller_wrapper (ticdc): set bdr mode in puller wrapper
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sourcemanager/manager.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/sinkv2/eventsink/txn/mysql/mysql.go
  tests/integration_tests/bdr_mode/data/down.sql
  tests/integration_tests/bdr_mode/data/up.sql
  tests/integration_tests/bdr_mode/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5

#7822 test(cdc): fix date-formats test fail
  tests/integration_tests/tidb_mysql_test/r/date_formats.result
  tests/integration_tests/tidb_mysql_test/t/date_formats.test
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-6.5

#7808 sinkv2(cdc): correct source and sink closing order
  cdc/model/changefeed_test.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/mem_quota.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sourcemanager/engine/factory/factory.go
  cdc/processor/sourcemanager/engine/factory/pebble.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/sorter/db/metrics.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
  pkg/db/metrics.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.5

#7819 processor/sinkmanager(ticdc): report checkpoint ts and update last position correctly
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#7740 openapi(engine): adapt error format when get job detail
  engine/pkg/httputil/job_client.go
  engine/pkg/httputil/mock/jobhttpclient_mock.go
  engine/pkg/httputil/mock/jobhttpclient_simple_mock.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  errors.toml
  pkg/errors/engine_errors.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#7779 expression_filter(dm): fix updateOldExprs and updateNewExprs length not same
  dm/syncer/expr_filter_group.go
  dm/syncer/expr_filter_group_test.go
  dm/tests/expression_filter/conf/dm-task2.yaml
  dm/tests/expression_filter/data/db1.increment2.sql
  dm/tests/expression_filter/data/db1.prepare2.sql
  dm/tests/expression_filter/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#7776 network(engine): return network usage by GetJob
  dm/syncer/dbconn/db.go
  engine/executor/dm/api.go
  engine/executor/dm/api_test.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/config/config.go
  engine/jobmaster/dm/config/config_test.go
  engine/pkg/dm/topic.go
  engine/test/e2e/e2e_dm_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#7583 metrics(dm, engine): add support for engine in dm grafana
  metrics/grafana/DM-Monitor-Professional.json
  metrics/grafana/DM-Monitor-Standard.json
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm, area/engine

#7818 tests(dm): migrate pingcap/check to testify for dm/pkg
  dm/pkg/backoff/backoff_test.go
  dm/pkg/dumpling/utils_test.go
  dm/pkg/encrypt/encrypt_test.go
  dm/pkg/func-rollback/rollback_test.go
  dm/pkg/helper/value_test.go
  dm/pkg/retry/strategy_test.go
  dm/pkg/streamer/hub_test.go
  dm/pkg/terror/adapter_test.go
  dm/pkg/terror/terror_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#7812 test(ticdc): add centos-base.repo file directly in canal test
  scripts/canal/docker/CentOS-Base.repo
  scripts/canal/docker/Dockerfile
Labels: status/ptal, component/test, status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/ticdc

#7793 cdc: replace tableID with Span in TableExecutor and agent
  Makefile
  cdc/processor/manager.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/tablepb/table.pb.go
  cdc/processor/tablepb/table.proto
  cdc/scheduler/internal/table_executor.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_bench_test.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/agent/table_test.go
  cdc/scheduler/rexport.go
  cdc/scheduler/schedulepb/table_schedule.proto
Labels: component/scheduler, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7834 sink(ticdc): Add DDL query into `schema.json` file
  cdc/model/schema_storage.go
  cdc/sinkv2/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sinkv2/ddlsink/cloudstorage/cloud_storage_ddl_sink_test.go
  cdc/sinkv2/eventsink/cloudstorage/dml_worker.go
  cdc/sinkv2/eventsink/cloudstorage/dml_worker_test.go
  cmd/storage-consumer/main.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/cloudstorage/table_definition_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#7844 config(ticdc): disable pull based sink
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  tests/integration_tests/processor_err_chan/run.sh
Labels: status/LGT2, status/can-merge, size/S, cherry-pick-approved, release-note-none, area/ticdc

#7846 chaos(engine): pin version of busybox to avoid dns lookup failure
  deployments/engine/helm/tiflow/templates/executor.yaml
  deployments/engine/helm/tiflow/templates/server-master.yaml
Labels: status/ptal, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/engine

#7856 sorter: reduce sorter memory percentage from 30% to 10%
  pkg/config/config_test_data.go
  pkg/config/server_config.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-6.5

#7731 scheduler(ticdc): add package keyspan
  cdc/scheduler/internal/v3/keyspan/reconciler.go
  cdc/scheduler/internal/v3/keyspan/reconciler_test.go
  cdc/scheduler/internal/v3/keyspan/region_cache.go
  pkg/spanz/map.go
  pkg/spanz/map_test.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7835 metrics(dm, engine): add job_id variable to dm grafana
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/openapi_test.go
  engine/jobmaster/dm/task_manager.go
  engine/jobmaster/dm/task_manager_test.go
  engine/test/e2e/e2e_dm_test.go
  metrics/grafana/DM-Monitor-Professional.json
  metrics/grafana/DM-Monitor-Standard.json
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm, area/engine

#7862 processor(ticdc): remove useless start operation and use correct start ts
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
Labels: status/LGT2, status/can-merge, size/L, release-note

#7861 metrics(ticdc): refine exp boundary, record large row from 2k size
  cdc/sinkv2/metrics/metrics.go
  cdc/sinkv2/metrics/mq/metrics.go
  cdc/sinkv2/metrics/txn/metrics.go
  metrics/grafana/ticdc.json
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#7837 sinkv2: fix a bug about redo log mem quota
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/mem_quota.go
  cdc/processor/sinkmanager/mem_quota_test.go
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sinkmanager/redo_cache_test.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_progress_heap.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/tasks.go
  cdc/processor/sourcemanager/engine/engine.go
  cdc/redo/manager.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, needs-cherry-pick-release-6.5

#7832 puller,processor: replace table ID with Span
  cdc/processor/manager_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#7871 pipeline(ticdc): fix sorter node memory leak
  cdc/processor/pipeline/sorter.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc, needs-cherry-pick-release-6.1

#7878 pkg(ticdc): replace json lib with go-json in etcd worker
  pkg/orchestrator/reactor_state.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc

#7876 sinkv2(ticdc): directly advance checkpoint ts if only resolved ts
  cdc/processor/sourcemanager/manager.go
  cdc/sinkv2/tablesink/progress_tracker.go
  cdc/sinkv2/tablesink/progress_tracker_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-6.5

#7892 model(cdc): fix BuildTiDBTableInfo panic when UNIQUE index exists #7891
  cdc/entry/mounter_test.go
  cdc/model/sink.go
Labels: type/bug, status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note-none

#7833 sorter/db,processor: replace table ID with Span
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/processor.go
  cdc/sorter/db/db.go
  cdc/sorter/db/db_test.go
  cdc/sorter/db/message/task.go
  cdc/sorter/db/reader.go
  cdc/sorter/db/reader_test.go
  cdc/sorter/db/sorter.go
  cdc/sorter/db/sorter_test.go
  cdc/sorter/db/system/system.go
  cdc/sorter/db/system/system_test.go
  cdc/sorter/db/writer.go
  cdc/sorter/db/writer_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#7841 dm/cdc: refine foreign key integration test
  dm/tests/foreign_key/run.sh
  tests/integration_tests/foreign_key/data/prepare.sql
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#7897 sink(ticdc): fix eventFragment memory leak in cloud storage sink
  cdc/sinkv2/eventsink/cloudstorage/dml_worker.go
Labels: status/LGT2, status/can-merge, size/XS, release-note, area/ticdc, needs-cherry-pick-release-6.5

#7838 sinkv2,processor: replace table ID with Span
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/sinkv2/eventsink/factory/factory.go
  cdc/sinkv2/eventsink/factory/factory_test.go
  cdc/sinkv2/tablesink/progress_tracker.go
  cdc/sinkv2/tablesink/progress_tracker_test.go
  cdc/sinkv2/tablesink/table_sink_impl.go
  cdc/sinkv2/tablesink/table_sink_impl_test.go
  pkg/config/debug.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#7883 owner(ticdc): refine error message of create changefeed delay
  cdc/owner/owner.go
  cdc/owner/owner_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#7901 chore(ticdc): remove useless comment
  cdc/owner/owner.go
  cdc/processor/manager.go
Labels: status/ptal, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/ticdc

#7851 expression_filter(dm): fix append update filter for non-update item
  dm/syncer/expr_filter_group.go
  dm/syncer/expr_filter_group_test.go
  dm/tests/expression_filter/conf/dm-task2.yaml
  dm/tests/expression_filter/data/db1.increment2.sql
  dm/tests/expression_filter/run.sh
Labels: status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#7894 cdc: cherry pick #5144 into release-5.1
  cdc/entry/mounter_test.go
  cdc/entry/schema/snapshot.go
  cdc/entry/schema/snapshot_test.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/owner/schema.go
  cdc/processor/processor.go
  cmd/util.go
Labels: status/LGT2, status/can-merge, size/XXL, cherry-pick-approved, release-note-none

#7889 sorter(ticdc): split large txn
  cdc/sorter/db/buffer.go
  cdc/sorter/db/buffer_test.go
  cdc/sorter/db/reader.go
  cdc/sorter/db/reader_test.go
  cdc/sorter/db/sorter.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/XL, release-note, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#7881 lightning(dm): update load unit metrics to lightning
  dm/metrics/grafana/DM-Monitor-Professional.json
  dm/metrics/grafana/DM-Monitor-Standard.json
  dm/tests/metrics/run.sh
  metrics/grafana/DM-Monitor-Professional.json
  metrics/grafana/DM-Monitor-Standard.json
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#7911 syncpoint (ticdc): set downstream tidb_enable_external_ts_read = off
  cdc/sink/mysql/mysql_params.go
  cdc/sink/mysql/mysql_params_test.go
  cdc/sink/mysql/mysql_test.go
  pkg/applier/redo_test.go
  pkg/sink/mysql/config_test.go
  pkg/sink/mysql/db_helper.go
  pkg/sink/mysql/mock_db.go
  tests/integration_tests/syncpoint/run.sh
Labels: status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note, needs-cherry-pick-release-6.5

#7912 metrics(ticdc): fix title of etcd worker tick duration
  metrics/grafana/ticdc.json
Labels: status/ptal, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/ticdc

#7839 checker(dm): add downstream CDC/PiTR check for lightning
  dm/checker/checker.go
  dm/config/checking_item.go
  dm/pkg/checker/lightning.go
  dm/tests/lightning_mode/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#7806 scheduler(ticdc): replace tableID with Span
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/owner_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_bench_test.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/info_provider.go
  cdc/scheduler/internal/v3/info_provider_test.go
  cdc/scheduler/internal/v3/member/capture_manager.go
  cdc/scheduler/internal/v3/member/capture_manager_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/replication/replication_set_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler.go
  cdc/scheduler/internal/v3/scheduler/scheduler_balance.go
  cdc/scheduler/internal/v3/scheduler/scheduler_balance_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_basic.go
  cdc/scheduler/internal/v3/scheduler/scheduler_basic_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture.go
  cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_move_table.go
  cdc/scheduler/internal/v3/scheduler/scheduler_move_table_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_rebalance.go
  cdc/scheduler/internal/v3/scheduler/scheduler_rebalance_test.go
  cdc/scheduler/rexport.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7885 sinkv2(cdc): fix and enable redo cache for pull-based-sink
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/tasks.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.5

#7920 engine: fix duration not updated
  engine/jobmaster/dm/api.go
  engine/jobmaster/dm/api_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7899 kv-client(ticdc): use sync pool for resolved ts event
  cdc/kv/client.go
  cdc/kv/region_worker.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#7852 metric(dm): add resumable_err label to unit error count metric
  dm/dumpling/dumpling.go
  dm/dumpling/metrics.go
  dm/loader/lightning.go
  dm/loader/loader.go
  dm/loader/metrics.go
  dm/metrics/alertmanager/dm_worker.rules.yml
  dm/relay/metrics.go
  dm/relay/relay.go
  dm/syncer/metrics/metrics.go
  dm/syncer/syncer.go
  dm/tests/_utils/check_metric
  dm/tests/new_relay/run.sh
  dm/unit/unit.go
  dm/unit/unit_test.go
  dm/worker/task_checker.go
  dm/worker/task_checker_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm

#7921 capture(ticdc): fix cdc panic when async close capture
  cdc/capture/capture.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#7868 sinkv2(cdc): fix sinkv2 grafana
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#7910 syncpoint (ticdc): set downstream tidb_enable_external_ts_read = off
  cdc/sink/mysql/mysql_params.go
  cdc/sink/mysql/mysql_params_test.go
  cdc/sink/mysql/mysql_test.go
  pkg/applier/redo_test.go
  pkg/sink/mysql/config_test.go
  pkg/sink/mysql/db_helper.go
  pkg/sink/mysql/mock_db.go
  tests/integration_tests/syncpoint/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-6.5

#7928 engine(dm): use same enum value as dmpb for engine task stage
  engine/jobmaster/dm/metadata/job.go
  engine/jobmaster/dm/metadata/job_test.go
  metrics/grafana/DM-Monitor-Professional.json
  metrics/grafana/DM-Monitor-Standard.json
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7902 test(dm): add foreign key test
  dm/pkg/conn/basedb.go
  dm/tests/foreign_key/data/db1.increment.sql
  dm/tests/foreign_key/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note

#7938 pkg/security(ticdc): support online load tls config (#7927)
  cdc/server/server_test.go
  engine/pkg/client/executor_client_test.go
  engine/test/e2e/e2e_dm_test.go
  pkg/cmd/cli/cli_changefeed_list_test.go
  pkg/cmd/cli/cli_changefeed_query_test.go
  pkg/fsutil/preallocate_test.go
  pkg/security/credential.go
  pkg/security/test_util.go
Labels: status/LGT2, status/can-merge, size/XL, cherry-pick-approved, release-note, area/ticdc, type/cherry-pick-for-release-6.5

#7919 lightning(dm): use working directory for sort-kv when source-dir is S3
  dm/config/subtask.go
  dm/config/task.go
  dm/loader/lightning.go
  dm/pkg/storage/utils.go
  dm/pkg/storage/utils_test.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
  dm/tests/others_integration_3.txt
  dm/tests/s3_dumpling_lightning/conf/dm-master.toml
  dm/tests/s3_dumpling_lightning/conf/dm-task.yaml
  dm/tests/s3_dumpling_lightning/conf/dm-worker1.toml
  dm/tests/s3_dumpling_lightning/conf/dm-worker2.toml
  dm/tests/s3_dumpling_lightning/conf/source1.yaml
  dm/tests/s3_dumpling_lightning/conf/source2.yaml
  dm/tests/s3_dumpling_lightning/data/clean_data.sql
  dm/tests/s3_dumpling_lightning/data/db1.increment.sql
  dm/tests/s3_dumpling_lightning/data/db1.prepare.sql
  dm/tests/s3_dumpling_lightning/data/db2.increment.sql
  dm/tests/s3_dumpling_lightning/data/db2.prepare.sql
  dm/tests/s3_dumpling_lightning/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7939 kv-client(ticdc): decrease input buffer, correct watermark calculation
  cdc/kv/region_worker.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#7880 pkg(ticdc): merge package regionspan and spanz
  cdc/entry/mounter_test.go
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/region_state.go
  cdc/kv/region_state_bench_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/kv/regionlock/region.go
  cdc/kv/regionlock/region_range_lock.go
  cdc/kv/regionlock/region_range_lock_test.go
  cdc/kv/regionlock/region_test.go
  cdc/model/kv.go
  cdc/model/kv_test.go
  cdc/model/owner.go
  cdc/processor/tablepb/table.go
  cdc/processor/tablepb/table.pb.go
  cdc/processor/tablepb/table.proto
  cdc/puller/ddl_puller.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_bench_test.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/pdutil/api_client_test.go
  pkg/spanz/convert.go
  pkg/spanz/span.go
  pkg/spanz/span_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7947 sinkv2(cdc): add some pull-based-sink metrics
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7949 api(ticdc): add missing memory-quota config
  cdc/api/v2/model.go
  cdc/processor/sinkmanager/mem_quota.go
Labels: status/LGT2, status/can-merge, size/XS, release-note, area/ticdc, component/api, needs-cherry-pick-release-6.5, affects-6.5

#7954 network(dm): meter network usage from upstream & downstream
  dm/config/subtask.go
  dm/syncer/checkpoint.go
  dm/syncer/dbconn/db.go
  dm/syncer/online-ddl-tools/online_ddl.go
  dm/syncer/sharding_group.go
  dm/syncer/syncer.go
  engine/executor/dm/api.go
  engine/executor/dm/api_test.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/config/config.go
  engine/jobmaster/dm/config/config_test.go
  engine/pkg/dm/topic.go
  engine/test/e2e/e2e_dm_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#7957 puller(ticdc): remove GetResolvedTs from Puller interface
  cdc/puller/ddl_puller_test.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#7948 scheduler(ticdc): fix impossible spans panic
  cdc/scheduler/internal/v3/keyspan/reconciler.go
  cdc/scheduler/internal/v3/keyspan/reconciler_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#7843 integration_test (ticdc): fix bdr mod integration test error.
  tests/integration_tests/bdr_mode/data/down.sql
  tests/integration_tests/bdr_mode/data/up.sql
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-6.5

#7943 api(ticdc) Fill id namespace for open api v1
  cdc/api/v1/api.go
  cdc/api/v1/validator.go
  cdc/api/v2/changefeed.go
  pkg/cmd/cli/cli_changefeed_update.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-6.5

#7970 bug-fix: update go-mysql to fix mariadb panic
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-6.5

#7896 lightning(dm): add checksum to task configuation
  dm/_utils/terror_gen/errors_release.txt
  dm/config/task.go
  dm/config/task_test.go
  dm/ctl/common/util_test.go
  dm/errors.toml
  dm/loader/lightning.go
  dm/loader/lightning_test.go
  dm/pkg/retry/errors.go
  dm/pkg/terror/errcode_string.go
  dm/pkg/terror/error_list.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
  dm/tests/lightning_mode/run.sh
  dm/tests/many_tables/conf/dm-task-2.yaml
  dm/tests/many_tables/run.sh
  dm/tests/s3_dumpling_lightning/conf/dm-task.yaml
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#7952 sinkv2(cdc): make pebble engine write smoothly
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.5

#7909 ticdc: disable span replication in mysql/tidb changefeed
  cdc/capture/capture.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/sink/validator.go
  cdc/sink/validator_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#7962 tls(dm): fix the error when only ssl-ca is configured
  dm/dm/config/security.go
  dm/dm/config/security_test.go
  dm/tests/tls/conf/dm-master-no-tls.toml
  dm/tests/tls/conf/dm-task-only-ca.yaml
  dm/tests/tls/conf/dm-worker-no-tls.toml
  dm/tests/tls/conf/source-no-tls.yaml
  dm/tests/tls/run.sh
Labels: status/LGT2, status/can-merge, size/L, cherry-pick-approved, release-note-none, affects-5.4, affects-6.1

#7916 redo(ticdc): replace tableID with Span
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  pkg/spanz/convert.go
  pkg/spanz/convert_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, component/redolog, area/ticdc

#7960 sinkv2 (ticdc): limit batch dml size
  cdc/sinkv2/eventsink/txn/mysql/mysql.go
  cdc/sinkv2/eventsink/txn/mysql/mysql_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note, needs-cherry-pick-release-6.5

#7981 sink(ticdc): use separate ctx for each DML
  cdc/sink/mysql/mysql.go
  cdc/sinkv2/eventsink/txn/mysql/mysql.go
  cdc/sinkv2/eventsink/txn/mysql/mysql_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-6.5

#7976 readme(*): remove deprecated coverage link
  README.md
Labels: status/ptal, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#7977 causality(ticdc): fix slot could not be locked during free
  pkg/causality/internal/slots.go
  pkg/causality/internal/slots_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#7995 *: improve readme and update outdated links
  CONTRIBUTING.md
  README.md
  README_DM.md
  README_TiCDC.md
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7992 mysql(ticdc): handle the case when @@sql_mode is null
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
  pkg/sink/mysql/db_helper.go
Labels: status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#7936 cmd(ticdc): print error msg if an invalid input was read
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_unsafe.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#7988 sinkv2(cdc): fix sink worker for splitTxn is false
  cdc/processor/sinkmanager/table_sink_worker.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5
