Repository pingcap/tiflow, pull requests merged in 2022-09, with the labels that each got.

#6919 engine(dm): use jobID as job name
  engine/executor/dm/worker.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/checkpoint/agent.go
  engine/jobmaster/dm/checkpoint/agent_test.go
  engine/jobmaster/dm/config/config.go
  engine/jobmaster/dm/config/config_test.go
  engine/jobmaster/dm/config/job_template.yaml
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/openapi_test.go
  engine/jobmaster/dm/worker_manager.go
  engine/jobmaster/dm/worker_manager_test.go
  engine/test/e2e/dm-job.yaml
  engine/test/integration_tests/dm_case_sensitive/conf/job.yaml
  engine/test/integration_tests/dm_collation/conf/job.yaml
  engine/test/integration_tests/dm_full_mode/conf/job.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#6935 test(ticdc): add compression test for kafka
  cdc/sink/mq/producer/kafka/config.go
  tests/integration_tests/kafka_compression/conf/diff_config.toml
  tests/integration_tests/kafka_compression/data/gzip_data.sql
  tests/integration_tests/kafka_compression/data/lz4_data.sql
  tests/integration_tests/kafka_compression/data/snappy_data.sql
  tests/integration_tests/kafka_compression/data/zstd_data.sql
  tests/integration_tests/kafka_compression/run.sh
Labels: component/test, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc, needs-cherry-pick-release-6.1

#6816 sinkv2(ticdc): activite sinkv2 mysql sink
  .github/workflows/ticdc_integration.yaml
  Makefile
  cdc/processor/processor.go
  cdc/sink/black_hole.go
  cdc/sink/codec/avro/avro.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mysql/mysql.go
  cdc/sink/sink.go
  cdc/sinkv2/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sinkv2/eventsink/blackhole/black_hole_dml_sink.go
  cdc/sinkv2/eventsink/event_appender.go
  cdc/sinkv2/eventsink/factory/factory.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer.go
  cdc/sinkv2/eventsink/txn/backend.go
  cdc/sinkv2/eventsink/txn/event.go
  cdc/sinkv2/eventsink/txn/mock/backend_mock.go
  cdc/sinkv2/eventsink/txn/mysql/mysql.go
  cdc/sinkv2/eventsink/txn/mysql/mysql_test.go
  cdc/sinkv2/eventsink/txn/txn_sink.go
  cdc/sinkv2/eventsink/txn/txn_sink_test.go
  cdc/sinkv2/eventsink/txn/worker.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
  tests/integration_tests/capture_suicide_while_balance_table/run.sh
  tests/integration_tests/consistent_replicate_gbk/run.sh
  tests/integration_tests/consistent_replicate_nfs/run.sh
  tests/integration_tests/consistent_replicate_s3/run.sh
  tests/integration_tests/consistent_replicate_s3_schev2/run.sh
  tests/integration_tests/ddl_reentrant/run.sh
  tests/integration_tests/kafka_sink_error_resume/run.sh
  tests/integration_tests/kill_owner_with_ddl/run.sh
  tests/integration_tests/multi_changefeed/run.sh
  tests/integration_tests/processor_resolved_ts_fallback/run.sh
  tests/integration_tests/sink_hang/run.sh
  tests/integration_tests/sink_retry/run.sh
  tests/mq_protocol_tests/main.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#6918 discovery(engine): store executor information to database
  engine/executor/config.go
  engine/executor/server.go
  engine/executor/server/metastore.go
  engine/executor/server/metastore_test.go
  engine/executor/server/mocks/metastore_mock.go
  engine/executor/server_test.go
  engine/model/cluster.go
  engine/pkg/config/constants.go
  engine/pkg/orm/client.go
  engine/pkg/rpcerror/grpc.go
  engine/pkg/serverutil/discovery_keepalive_test.go
  engine/servermaster/executor_manager.go
  engine/servermaster/executor_manager_test.go
  engine/servermaster/executormeta/client.go
  engine/servermaster/executormeta/client_mock.go
  engine/servermaster/executormeta/client_test.go
  engine/servermaster/executormeta/model/executor.go
  engine/servermaster/failover.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
  engine/servermaster/serverutil/watch_executors.go
  scripts/generate-engine-mock.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#6939 metrics (ticdc): add some changefeed releated metrics panel in Grafana
  cdc/processor/metrics.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/puller/metrics.go
  cdc/puller/puller.go
  cdc/sink/metrics/statistics.go
  cdc/sorter/db/sorter.go
  cdc/sorter/db/system/system_test.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#6950 error(engine): fix duplicated rpc error name
  engine/servermaster/scheduler/errors.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#6928 cdc: fix a bug that DDLs can be executed multiple times incorrectly
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  tests/integration_tests/owner_resign/conf/diff_config.toml
  tests/integration_tests/owner_resign/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#6446 ddl_puller(ticdc): discard DDLs that irrelevant with changefeed
  cdc/entry/mounter_test.go
  cdc/entry/schema/snapshot.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/entry/schema_test_helper.go
  cdc/owner/schema.go
  cdc/owner/schema_test.go
  cdc/processor/processor.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/errors/helper.go
  pkg/errors/helper_test.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  tests/integration_tests/multi_tables_ddl/conf/diff_config.toml
  tests/integration_tests/multi_tables_ddl/conf/error-1.toml
  tests/integration_tests/multi_tables_ddl/conf/error-2.toml
  tests/integration_tests/multi_tables_ddl/conf/normal.toml
  tests/integration_tests/multi_tables_ddl/data/test.sql
  tests/integration_tests/multi_tables_ddl/run.sh
Labels: status/ptal, component/ddl, component/puller, status/LGT2, status/can-merge, size/XXL, release-note-none, type/enhancement

#6961 test(dm): fix unstable CI
  dm/tests/sharding2/run.sh
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#6920 sink(ticdc): report the kafka topic create failed error
  cdc/sink/mq/manager/kafka_manager.go
  cdc/sink/mq/manager/kafka_manager_test.go
  pkg/sink/kafka/cluster_admin_client_mock_impl.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.1

#6930 meta(engine): rename some meta name
  engine/executor/cvs/cvstask.go
  engine/executor/dm/worker.go
  engine/executor/server.go
  engine/framework/base_jobmaster.go
  engine/framework/base_jobmaster_test.go
  engine/framework/common.go
  engine/framework/fake/fake_master.go
  engine/framework/fake/fake_worker.go
  engine/framework/internal/master/worker_manager.go
  engine/framework/internal/master/worker_manager_test.go
  engine/framework/internal/worker/master_client_test.go
  engine/framework/master.go
  engine/framework/master_test.go
  engine/framework/metadata/metadata.go
  engine/framework/metadata/metadata_test.go
  engine/framework/mock_master_util.go
  engine/framework/model/master.go
  engine/framework/model/messages.go
  engine/framework/model/worker.go
  engine/framework/model/worker_test.go
  engine/framework/statusutil/writer_test.go
  engine/framework/worker.go
  engine/framework/worker_test.go
  engine/jobmaster/cvsjob/cvs_job_master.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/example/master_impl.go
  engine/jobmaster/example/master_impl_test.go
  engine/jobmaster/example/worker_impl.go
  engine/jobmaster/example/worker_impl_test.go
  engine/pkg/externalresource/integration_test/gc_test.go
  engine/pkg/externalresource/manager/gc_coordinator_test.go
  engine/pkg/externalresource/manager/interfaces.go
  engine/pkg/orm/client.go
  engine/pkg/orm/client_test.go
  engine/pkg/orm/mock_test.go
  engine/pkg/orm/util_test.go
  engine/servermaster/job_fsm.go
  engine/servermaster/job_fsm_test.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#6966 serverutil(engine): fix panic in WatchExecutors
  engine/servermaster/serverutil/watch_executors.go
  engine/servermaster/serverutil/watch_executors_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#6852 framework(engine): add StopImpl callback in master impl
  engine/executor/cvs/cvstask.go
  engine/executor/dm/worker.go
  engine/executor/dm/worker_test.go
  engine/executor/worker/test_util.go
  engine/framework/base_jobmaster.go
  engine/framework/base_jobmaster_test.go
  engine/framework/fake/fake_master.go
  engine/framework/fake/fake_worker.go
  engine/framework/internal/eventloop/interfaces.go
  engine/framework/internal/eventloop/runner.go
  engine/framework/internal/eventloop/runner_test.go
  engine/framework/internal/master/worker_manager.go
  engine/framework/master.go
  engine/framework/mock_master_impl.go
  engine/framework/mock_worker_impl.go
  engine/framework/worker.go
  engine/jobmaster/cvsjob/cvs_job_master.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/example/master_impl.go
  engine/jobmaster/example/worker_impl.go
  engine/pkg/orm/client.go
  engine/pkg/orm/client_test.go
  engine/pkg/orm/model/jobop.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  engine/servermaster/jobop/operator.go
  engine/servermaster/jobop/operator_test.go
  engine/test/e2e/e2e_dm_test.go
  errors.toml
  pkg/errors/engine_errors.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#6951 test(engine): add DM sql_mode test case
  dm/config/task.go
  engine/executor/dm/unitholder.go
  engine/test/integration_tests/dm_sql_mode/conf/diff_config.toml
  engine/test/integration_tests/dm_sql_mode/conf/job.yaml
  engine/test/integration_tests/dm_sql_mode/data/db1.increment.sql
  engine/test/integration_tests/dm_sql_mode/data/db1.prepare.sql
  engine/test/integration_tests/dm_sql_mode/data/db2.increment.sql
  engine/test/integration_tests/dm_sql_mode/data/db2.prepare.sql
  engine/test/integration_tests/dm_sql_mode/data/timezone.America-Phoenix.sql
  engine/test/integration_tests/dm_sql_mode/data/timezone.Asia-Shanghai.sql
  engine/test/integration_tests/dm_sql_mode/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#6955 servermaster(engine): add backoff mechanism for job
  engine/framework/model/master.go
  engine/servermaster/job_fsm.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobop/backoff.go
  engine/servermaster/jobop/backoff_manager.go
  engine/servermaster/jobop/backoff_manager_test.go
  engine/servermaster/jobop/backoff_test.go
  errors.toml
  pkg/errors/engine_errors.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#6974 sink(ticdc): add compression for avro test
  tests/mq_protocol_tests/framework/avro/kafka_docker_env_test.go
  tests/mq_protocol_tests/framework/avro/kafka_single_table.go
Labels: component/test, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/ticdc

#6948 metrics: remove metrics proxy
  dm/dumpling/dumpling.go
  dm/dumpling/metrics.go
  dm/loader/metrics.go
  dm/master/metrics/metrics.go
  dm/pkg/conn/baseconn.go
  dm/pkg/conn/baseconn_test.go
  dm/pkg/metricsproxy/countervec.go
  dm/pkg/metricsproxy/countervec_test.go
  dm/pkg/metricsproxy/gaugevec.go
  dm/pkg/metricsproxy/gaugevec_test.go
  dm/pkg/metricsproxy/histogramvec.go
  dm/pkg/metricsproxy/histogramvec_test.go
  dm/pkg/metricsproxy/proxy.go
  dm/pkg/metricsproxy/proxy_test.go
  dm/pkg/metricsproxy/summaryvec.go
  dm/pkg/metricsproxy/summaryvec_test.go
  dm/relay/metrics.go
  dm/syncer/dbconn/db.go
  dm/syncer/metrics/metrics.go
  dm/syncer/metrics/validator_metrics.go
  dm/worker/metrics.go
  dm/worker/subtask.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#6970 table(processor): simplify the interface of table_executor
  cdc/processor/pipeline/table_actor.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/table_executor.go
  cdc/scheduler/internal/v2/agent.go
  cdc/scheduler/internal/v2/agent_mock.go
  cdc/scheduler/internal/v2/agent_test.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/agent/table.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, type/enhancement

#6980 test(engine): fix fake job integration test fail when the worker is finished
  Makefile
  engine/framework/fake/fake_worker.go
  engine/test/integration_tests/tiflow_job_finished/conf/fake_job.json
  engine/test/integration_tests/tiflow_job_finished/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#6969 server(ticdc): move actor system to the server level
  cdc/capture/capture.go
  cdc/processor/pipeline/actor_node_context_test.go
  cdc/processor/pipeline/system/system.go
  cdc/processor/pipeline/system/system_test.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/server/server.go
  cdc/sorter/db/system/system.go
  cdc/sorter/db/system/system_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#6971 sync_point (ticdc): add new config and change sync point table struct
  cdc/api/v1/validator.go
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_sink.go
  cdc/sink/mysql/mysql_syncpoint_store.go
  cdc/sink/mysql/syncpoint_store.go
  errors.toml
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_changefeed_update_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/errors/cdc_errors.go
  pkg/orchestrator/reactor_state_test.go
  tests/integration_tests/move_table/main.go
  tests/integration_tests/syncpoint/conf/changefeed.toml
  tests/integration_tests/syncpoint/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#6975 kvclient(ticdc): refine and adjust logs for better debugging
  cdc/api/util.go
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/model/schema_storage.go
  cdc/owner/changefeed.go
  cdc/owner/feed_state_manager.go
  cdc/owner/owner.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/processor.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  cdc/scheduler/internal/v3/agent/table.go
  cdc/sorter/db/reader.go
  cdc/sorter/db/sorter.go
  pkg/regionspan/region_range_lock.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#6987 chaos(engine): fix kube config can't find in root user
  .github/workflows/dataflow_engine_chaos.yaml
Labels: status/ptal, type/bugfix, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#6845 servermaster, executor(engine): Changing interfaces to support executor labels and selectors
  deployments/engine/docker-compose/3m3e.yaml
  engine/enginepb/master.pb.go
  engine/executor/config.go
  engine/executor/server.go
  engine/framework/base_jobmaster.go
  engine/framework/fake/fake_master.go
  engine/framework/internal/master/worker_creator.go
  engine/framework/internal/master/worker_creator_test.go
  engine/framework/master.go
  engine/framework/master_test.go
  engine/framework/mock_master_util.go
  engine/model/cluster.go
  engine/model/cluster_test.go
  engine/pkg/client/client_mock.go
  engine/pkg/client/executor_service_client.go
  engine/pkg/client/executor_service_client_test.go
  engine/pkg/cmd/executor/executor.go
  engine/pkg/openapi/apiv1.swagger.json
  engine/proto/master.proto
  engine/servermaster/executor_manager.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  engine/servermaster/scheduler/errors.go
  engine/servermaster/scheduler/model/request.go
  engine/servermaster/scheduler/selector_filter_test.go
  engine/servermaster/server.go
  engine/test/integration_tests/dm_case_sensitive/run.sh
  engine/test/integration_tests/dm_full_mode/run.sh
  engine/test/integration_tests/e2e_with_selectors/conf/fake_job.json
  engine/test/integration_tests/e2e_with_selectors/run.sh
  pkg/label/label.go
  pkg/label/label_test.go
  pkg/label/selector.go
  pkg/label/selector_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#6968 sinkv2(ticdc): add more sinkv2 metrics
  cdc/server/metrics.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink.go
  cdc/sinkv2/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sinkv2/eventsink/mq/worker.go
  cdc/sinkv2/eventsink/txn/txn_sink.go
  cdc/sinkv2/eventsink/txn/worker.go
  cdc/sinkv2/metrics/metrics.go
  cdc/sinkv2/metrics/statistics.go
  metrics/grafana/ticdc.json
  pkg/config/debug.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#6993 test(engine): fix integration error when check job status
  Makefile
  engine/test/integration_tests/dm_basic/run.sh
  engine/test/utils/wait_mysql_online.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#6996 cli(ticdc): remove cli reserved etcd key warn log
  pkg/etcd/etcd.go
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note

#6998 kv(ticdc): remove unused RegionTsManager code
  cdc/kv/resolvedts_heap.go
  cdc/kv/resolvedts_heap_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#6908 table partiiton: exchange partition with table 6.3 GA
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  tests/integration_tests/partition_table/data/prepare.sql
  tests/integration_tests/partition_table/run.sh
Labels: status/LGT2, status/can-merge, first-time-contributor, size/XS, release-note

#6925 framework(engine): support fast fail when pre dispatch worker
  dm/pkg/terror/terror.go
  dm/pkg/terror/terror_test.go
  engine/executor/dm/worker.go
  engine/executor/server.go
  engine/executor/server_test.go
  engine/framework/model/master.go
  engine/framework/model/master_test.go
  engine/framework/registry/factory.go
  engine/framework/registry/factory_test.go
  engine/framework/registry/registry.go
  engine/framework/registry/registry_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/pkg/client/errors.go
  engine/pkg/orm/client.go
  engine/pkg/orm/client_test.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  pkg/errors/reflect.go
  pkg/errors/reflect_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#6960 chaos: fix utf8mb3 and utf8mb4_0900_ai_ci for chaos test
  dm/chaos/cases/db.go
  dm/chaos/manifests/sources.yaml
  go.mod
  go.sum
Labels: component/test, status/LGT2, status/can-merge, size/S, area/dm

#7008 lint(*): fix standard library is not checked in depguard
  .golangci.yml
  engine/pkg/meta/internal/registry.go
  engine/pkg/meta/mock/clientconn_mock.go
Labels: status/ptal, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#6991 monitor(engine): add basic Grafana panel for tiflow
  Makefile.engine
  deployments/engine/docker-compose/config/prometheus.yml
  engine/servermaster/metrics.go
  engine/servermaster/server_test.go
  metrics/grafana/tiflow.json
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#7011 test(dm): resume the task for kill-master test
  dm/tests/shardddl3/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#6989 cmd(engine): optimize parameters of tiflow master and executor
  .github/workflows/dataflow_engine_chaos.yaml
  README_Engine.md
  deployments/engine/docker-compose/1m1e.yaml
  deployments/engine/docker-compose/1m3e.yaml
  deployments/engine/docker-compose/3m3e.yaml
  deployments/engine/docker-compose/config/executor.toml
  deployments/engine/docker-compose/config/master.toml
  deployments/engine/docker-compose/config/template_executor.toml
  deployments/engine/docker-compose/config/template_master.toml
  deployments/engine/helm/tiflow/templates/_helpers.tpl
  deployments/engine/helm/tiflow/templates/cases.yaml
  deployments/engine/helm/tiflow/templates/executor.yaml
  deployments/engine/helm/tiflow/templates/server-master.yaml
  deployments/engine/helm/tiflow/values.yaml
  engine/chaos/manifests/chaos-values.yaml
  engine/executor/config.go
  engine/pkg/cmd/executor/executor.go
  engine/pkg/cmd/master/master.go
  engine/pkg/meta/model/config.go
  engine/pkg/meta/model/config_test.go
  engine/servermaster/config.go
  engine/servermaster/config_test.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
  engine/test/integration_tests/dm_new_collation_off/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#7023 tests(engine): ignore errors when removing the container
  engine/test/utils/run_engine.sh
  engine/test/utils/start_engine_cluster
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#7015 sinkv2(ticdc): add more metrics
  cdc/processor/processor.go
  cdc/sinkv2/eventsink/factory/factory.go
  cdc/sinkv2/eventsink/factory/factory_test.go
  cdc/sinkv2/metrics/kafka/collector.go
  cdc/sinkv2/metrics/kafka/metric.go
  cdc/sinkv2/metrics/metrics.go
  cdc/sinkv2/tablesink/table_sink_impl.go
  cdc/sinkv2/tablesink/table_sink_impl_test.go
  metrics/grafana/ticdc.json
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7019 servermaster(engine): add backoff config, fix timeout in chaos test
  deployments/engine/docker-compose/config/master.toml
  deployments/engine/helm/tiflow/values.yaml
  engine/servermaster/config.go
  engine/servermaster/config_test.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobop/backoff.go
  engine/servermaster/jobop/backoff_manager.go
  engine/servermaster/jobop/backoff_manager_test.go
  engine/servermaster/jobop/backoff_test.go
  engine/servermaster/jobop/config.go
  engine/servermaster/server.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#7031 config(ticdc): increase the default table memory quota to 64MiB
  pkg/config/config_test_data.go
  pkg/config/server_config.go
Labels: status/LGT2, status/can-merge, size/XS, release-note

#7032 changefeed(ticdc): add metrics to track lag distribution
  cdc/owner/changefeed.go
  cdc/owner/metrics.go
  cdc/owner/owner.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XL, component/metrics-logging, release-note-none

#7024 pkg/pdutil(ticdc): improve pd time accuracy
  pkg/pdutil/clock.go
  pkg/pdutil/clock_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#7041 owner(ticdc): fix query healthy 500 since changefeed paused.
  cdc/owner/owner.go
  cdc/owner/owner_test.go
Labels: status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none

#7038 sinkv2(ticdc): improve sinkv2 progress tracker
  cdc/sinkv2/tablesink/progress_tracker.go
  cdc/sinkv2/tablesink/progress_tracker_test.go
  cdc/sinkv2/tablesink/table_sink_impl.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#7014 tracker(dm): fix downstream table structure reports key too long (#6661)
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
Labels: status/LGT2, status/can-merge, size/XS, cherry-pick-approved, release-note

#6848 syncer(dm): Fix dm-worker keeps retrying to execute ddl when encountering "invalid connection" error
  dm/_utils/terror_gen/errors_release.txt
  dm/errors.toml
  dm/pkg/retry/errors.go
  dm/pkg/terror/error_list.go
  dm/syncer/error.go
  dm/syncer/error_test.go
  dm/syncer/syncer.go
  dm/syncer/util.go
  dm/syncer/util_test.go
  dm/tests/gbk/conf/source1.yaml
  dm/tests/gbk/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm

#7044 syncpoint (ticdc): refine the ts map table
  cdc/sink/mysql/mysql_syncpoint_store.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc

#7035 framework(engine): record error message when job master closes
  engine/framework/base_jobmaster.go
  engine/framework/base_jobmaster_test.go
  engine/framework/master.go
  engine/framework/metadata/metadata.go
  engine/framework/model/master.go
  engine/framework/model/master_test.go
  engine/pkg/orm/client.go
  engine/pkg/orm/client_test.go
  engine/pkg/orm/model/common.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#7027 syncer(dm): fix corrupt latin1 data when replicating
  dm/syncer/dml.go
  dm/tests/expression_filter/conf/dm-task2.yaml
  dm/tests/expression_filter/data/db1.increment2.sql
  dm/tests/expression_filter/data/db1.prepare2.sql
  dm/tests/expression_filter/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#7042 metrics(ticdc): merge kv client and events metrics monitoring together and simplication.
  cdc/sink/metrics/metrics.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7039 metrics(ticdc) : fix incorrect display of panel about large data event size (MySQL)
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, severity/minor, size/S, area/ticdc

#6886 server(ticdc): do not drain capture by signal handling
  cdc/capture/capture.go
  cdc/capture/capture_test.go
  cdc/capture/mock/capture_mock.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture.go
  cdc/server/server.go
  pkg/cmd/server/server.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#7022 test(dm): add test for json
  dm/tests/all_mode/data/db3.increment.sql
  dm/tests/all_mode/data/db3.prepare.sql
  dm/tests/all_mode/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm

#6992 engine(dm): implement String method for enum type
  engine/executor/cvs/cvstask.go
  engine/executor/dm/api_test.go
  engine/executor/dm/unitholder.go
  engine/executor/dm/worker.go
  engine/executor/dm/worker_test.go
  engine/executor/server.go
  engine/executor/server_test.go
  engine/framework/base_jobmaster_test.go
  engine/framework/common.go
  engine/framework/fake/fake_master.go
  engine/framework/master.go
  engine/framework/master_test.go
  engine/framework/mock_master_impl.go
  engine/framework/mock_master_util.go
  engine/framework/mock_worker_util.go
  engine/framework/model/typedefs.go
  engine/framework/model/typedefs_test.go
  engine/framework/registry/register_fake.go
  engine/framework/registry/registry.go
  engine/framework/registry/registry_test.go
  engine/jobmaster/cvsjob/cvs_job_master.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/checkpoint/agent.go
  engine/jobmaster/dm/checkpoint/agent_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/metadata/job.go
  engine/jobmaster/dm/metadata/job_test.go
  engine/jobmaster/dm/runtime/worker_status.go
  engine/jobmaster/dm/runtime/worker_status_test.go
  engine/jobmaster/dm/task_manager.go
  engine/jobmaster/dm/task_manager_test.go
  engine/jobmaster/dm/worker_manager.go
  engine/jobmaster/dm/worker_manager_test.go
  engine/pkg/dm/topic.go
  engine/pkg/dm/topic_test.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  engine/servermaster/jobop/operator_test.go
  engine/servermaster/server.go
  engine/test/integration_tests/dm_collation/run.sh
  engine/test/integration_tests/dm_many_tables/run.sh
  engine/test/integration_tests/dm_new_collation_off/run.sh
  engine/test/integration_tests/dm_sql_mode/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#6377 puller(ticdc): cherry-pick 5658 to release-5.4
  cdc/kv/client.go
  cdc/kv/metrics.go
  cdc/kv/region_worker.go
  pkg/workerpool/pool.go
  pkg/workerpool/pool_impl.go
Labels: status/LGT2, status/can-merge, size/XL, cherry-pick-approved, release-note-none

#7036 syncer(dm): Fix follow-up bugs after fixing nondeterministic DDL
  dm/syncer/ddl.go
  dm/syncer/syncer.go
  engine/pkg/orm/client.go
  engine/servermaster/jobop/backoff.go
Labels: status/LGT2, status/can-merge, size/M, release-note, area/dm

#7066 syncer(dm): fix corrupt latin1 data when replicating (#7027) (#7055)
  Makefile
  dm/syncer/dml.go
  dm/tests/expression_filter/conf/dm-task2.yaml
  dm/tests/expression_filter/data/db1.increment2.sql
  dm/tests/expression_filter/data/db1.prepare2.sql
  dm/tests/expression_filter/run.sh
Labels: status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note

#7051 metrics: replace processor checkpoint with owner checkpoint
  metrics/alertmanager/ticdc.rules.yml
  metrics/grafana/ticdc.json
Labels: status/LGT1, status/can-merge, size/S, component/metrics-logging, require-LGT1, release-note-none, area/ticdc

#7074 ddl_puller (ticdc): fix schema not found error
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#6913 test(engine): add DM TLS test
  deployments/engine/docker-compose/config/tidb_tls.toml
  deployments/engine/docker-compose/dm_databases_with_tls.yaml
  deployments/engine/docker/dind.Dockerfile
  dm/config/security.go
  dm/config/security_test.go
  dm/config/source_converter.go
  dm/config/task_converters.go
  dm/dumpling/dumpling.go
  dm/loader/lightning.go
  dm/master/server_test.go
  dm/pkg/conn/basedb.go
  dm/pkg/ha/source_test.go
  dm/relay/relay.go
  dm/syncer/util.go
  dm/tests/dmctl_basic/conf/get_master1.toml
  dm/tests/dmctl_basic/conf/get_worker1.toml
  dm/tests/dmctl_basic/conf/get_worker2.toml
  engine/pkg/meta/internal/sqlkv/sql_impl_test.go
  engine/pkg/meta/model/common.go
  engine/test/integration_tests/dm_new_collation_off/run.sh
  engine/test/integration_tests/dm_tls/conf/job.yaml
  engine/test/integration_tests/dm_tls/data/db1.increment.sql
  engine/test/integration_tests/dm_tls/data/db1.prepare.sql
  engine/test/integration_tests/dm_tls/data/db2.increment.sql
  engine/test/integration_tests/dm_tls/data/db2.prepare.sql
  engine/test/integration_tests/dm_tls/run.sh
  engine/test/utils/generate_cert
  engine/test/utils/run_sql
  engine/test/utils/run_sql_file
  engine/test/utils/start_engine_cluster
  engine/test/utils/wait_mysql_online.sh
  go.mod
  go.sum
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#7077 pkg/notify: close notifier properly
  pkg/notify/notify.go
  pkg/notify/notify_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7080 mysql (ticdc): use white list for retryable error
  cdc/sink/mysql.go
Labels: status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note-none

#5695 metrics(ticdc): fix no sorter metrics
  cdc/metrics.go
Labels: release-blocker, status/LGT2, status/can-merge, size/XS, cherry-pick-approved, release-note, affects-5.1

#6225 syncer(dm): adjust safe mode duration when start/resume
  dm/_utils/terror_gen/errors_release.txt
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_test.go
  dm/errors.toml
  dm/pkg/terror/error_list.go
  dm/syncer/safe_mode.go
  dm/syncer/safe_mode_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
  dm/tests/openapi/run.sh
  dm/tests/print_status/run.sh
  dm/tests/safe_mode/conf/dm-task-safe-mode-duration.yaml
  dm/tests/safe_mode/run.sh
  dm/tests/sequence_safe_mode/run.sh
  dm/tests/shardddl1/run.sh
  dm/tests/start_task/run.sh
  engine/jobmaster/dm/config/dm_subtask_3306.toml
  engine/jobmaster/dm/config/dm_subtask_3307.toml
  engine/jobmaster/dm/config/job_template.yaml
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm

#6983 sink(ticdc): remove pulsar sink
  cdc/sink/mq/manager/pulsar_manager.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_test.go
  cdc/sink/mq/producer/pulsar/doc.go
  cdc/sink/mq/producer/pulsar/option.go
  cdc/sink/mq/producer/pulsar/producer.go
  cdc/sink/sink.go
  cdc/sinkv2/eventsink/mq/worker.go
  cmd/cdc/hack/dbus_linux.go
  cmd/cdc/hack/dbus_other.go
  cmd/cdc/main.go
  errors.toml
  go.mod
  go.sum
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/config/sink_test.go
  pkg/errors/cdc_errors.go
  pkg/sink/sink_type.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#7065 test(engine): add fast finished integration test
  engine/servermaster/config.go
  engine/servermaster/server.go
  engine/test/integration_tests/dm_case_sensitive/run.sh
  engine/test/integration_tests/dm_collation/run.sh
  engine/test/integration_tests/dm_full_mode/run.sh
  engine/test/integration_tests/dm_many_tables/run.sh
  engine/test/integration_tests/dm_new_collation_off/run.sh
  engine/test/integration_tests/dm_sql_mode/run.sh
  engine/test/integration_tests/dm_tls/run.sh
  engine/test/integration_tests/e2e_fast_finished/conf/fake_job_fast_0.json
  engine/test/integration_tests/e2e_fast_finished/conf/fake_job_fast_1.json
  engine/test/integration_tests/e2e_fast_finished/conf/fake_job_fast_100.json
  engine/test/integration_tests/e2e_fast_finished/run.sh
  engine/test/integration_tests/tiflow_job_finished/run.sh
  engine/test/utils/create_job
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#7076 redo (ticdc): adjust s3 timeout to 15s
  cdc/redo/writer/file.go
Labels: status/LGT2, status/can-merge, size/XS, release-note, needs-cherry-pick-release-6.1

#7012 owner, redo: make new s3 storage error unretryable
  cdc/redo/common/util.go
  errors.toml
  go.mod
  go.sum
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/errors/cdc_errors.go
  pkg/errors/helper.go
  pkg/errors/helper_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.1

#7069 pd, openapi(ticdc): retry one reset by peer when kill the pd instance, fix healthy panic
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  pkg/errorutil/ignore.go
  pkg/errorutil/ignore_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#7085 config(ticdc): decrease the default table memory quota to 10MiB
  pkg/config/config_test_data.go
  pkg/config/server_config.go
Labels: component/configuration, status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc

#7070 processor/pipeline(ticdc): use correct table pipeline ctx
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table_actor.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7103 test(engine): use smaller dataset to stable e2e test
  engine/test/e2e/docker.json
  engine/test/e2e/e2e_test.go
Labels: status/ptal, status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, area/engine

#7101 cdc: refactor protobuf packages
  cdc/processor/manager_test.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/tablepb/table.go
  cdc/processor/tablepb/table.pb.go
  cdc/processor/tablepb/table.proto
  cdc/puller/puller_test.go
  cdc/scheduler/internal/table_executor.go
  cdc/scheduler/internal/v2/agent_mock.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_bench_test.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/agent/table_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_bench_test.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/info_provider_test.go
  cdc/scheduler/internal/v3/member/capture_manager.go
  cdc/scheduler/internal/v3/member/capture_manager_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/replication/replication_set_test.go
  cdc/scheduler/internal/v3/transport/mock.go
  cdc/scheduler/internal/v3/transport/transport.go
  cdc/scheduler/internal/v3/transport/transport_test.go
  cdc/scheduler/schedulepb/table_schedule.pb.go
  cdc/scheduler/schedulepb/table_schedule.proto
  cdc/scheduler/schedulepb/table_schedule_manual_test.go
  scripts/generate-protobuf.sh
Labels: component/scheduler, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7072 master(engine): exit operator goroutine after job manager closes
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  engine/servermaster/jobop/mock/joboperator_mock.go
  scripts/generate-engine-mock.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#7108 log (ticdc): refine some verbose log
  cdc/processor/pipeline/sink.go
  cdc/redo/manager.go
  pkg/regionspan/region_range_lock.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7111 dep(dm): update TiDB to include new regexp functions
  cdc/entry/schema/snapshot.go
  cdc/entry/schema_storage_test.go
  dm/tests/sql_mode/data/db2.increment.sql
  dm/tests/sql_mode/run.sh
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7110 processor/pipeline(ticdc): set correct state when table actor stopping
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/sink/mock/mock_sink.go
  cdc/sinkv2/tablesink/progress_tracker.go
  cdc/sinkv2/tablesink/progress_tracker_test.go
  cdc/sinkv2/tablesink/table_sink_impl.go
  cdc/sinkv2/tablesink/table_sink_impl_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#7095 error (ticdc): add mysql ddl error blacklist
  cdc/sink/mysql/mysql.go
  pkg/errors/helper.go
  pkg/errorutil/util.go
  pkg/errorutil/util_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7119 server(ticdc): server panic on print log
  cdc/capture/capture.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#7132 sinkv2(ticdc): call callbacks in black hole sink
  cdc/sinkv2/eventsink/blackhole/black_hole_dml_sink.go
  cdc/sinkv2/eventsink/blackhole/black_hole_dml_sink_test.go
  cdc/sinkv2/eventsink/blackhole/main_test.go
Labels: component/sink, status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/ticdc, needs-cherry-pick-release-6.3

#7117 checker(dm): expose verify privileges api
  dm/pkg/checker/privilege.go
  dm/pkg/checker/privilege_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#7122 mq(ticdc): do not assign nil to interface value to prenvent panic on close sink v1
  cdc/processor/pipeline/table_actor.go
  cdc/processor/processor.go
  cdc/sink/mq/manager/kafka_manager.go
  cdc/sink/mq/mq.go
  pkg/config/sink.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3

#7129 test(engine): add query job integration test
  engine/test/integration_tests/dm_many_tables/conf/job.yaml
  engine/test/integration_tests/dm_many_tables/run.sh
  engine/test/utils/run_sql
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#7091 config(engine): engine use tls to connect meta MySQL
  deployments/engine/docker-compose/3m3e_with_tls.yaml
  deployments/engine/docker-compose/config/master_with_tls.toml
  engine/pkg/meta/internal/sqlkv/connection.go
  engine/pkg/meta/model/config.go
  engine/pkg/meta/model/config_test.go
  engine/pkg/meta/util.go
  engine/pkg/meta/util_test.go
  engine/test/integration_tests/dm_case_sensitive/run.sh
  engine/test/integration_tests/dm_collation/run.sh
  engine/test/integration_tests/dm_full_mode/run.sh
  engine/test/integration_tests/dm_tls/conf/job.yaml
  engine/test/integration_tests/dm_tls/run.sh
  engine/test/utils/exec_with_retry
  engine/test/utils/run_sql
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#7059 syncer: log KeyNotFound error for update/delete
  dm/pkg/conn/baseconn.go
  dm/syncer/dml_worker.go
  dm/syncer/dml_worker_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/tests/gbk/run.sh
  dm/tests/shardddl1/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note, area/dm

#7118 schema (ticdc): support exchange partition
  cdc/entry/schema/snapshot.go
  cdc/entry/schema/snapshot_test.go
  cdc/owner/schema.go
  errors.toml
  pkg/errors/cdc_errors.go
  tests/integration_tests/cli/run.sh
  tests/integration_tests/consistent_replicate_s3/conf/diff_config.toml
  tests/integration_tests/consistent_replicate_s3/data/prepare.sql
  tests/integration_tests/consistent_replicate_s3/run.sh
  tests/integration_tests/consistent_replicate_s3_schev2/run.sh
  tests/integration_tests/ddl_reentrant/run.sh
  tests/integration_tests/partition_table/data/prepare.sql
  tests/integration_tests/partition_table/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, needs-cherry-pick-release-6.3

#7152 test(DM): add check log contain to `safe-mode` integration test
  dm/tests/safe_mode/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm, needs-cherry-pick-release-6.3

#6949 election(engine): replace implementation with mysql
  engine/pkg/election/config.go
  engine/pkg/election/config_test.go
  engine/pkg/election/elector.go
  engine/pkg/election/elector_test.go
  engine/pkg/election/mock/storage_mock.go
  engine/pkg/election/storage.go
  engine/pkg/election/storage_sql.go
  engine/pkg/election/storage_sql_test.go
  engine/pkg/election/storage_test.go
  engine/servermaster/campaign.go
  engine/servermaster/config.go
  engine/servermaster/server.go
  engine/test/e2e/e2e_node_chaos_test.go
  scripts/generate-engine-mock.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#7150 kv(ticdc): refine regionTsManager
  cdc/kv/region_worker.go
  cdc/kv/resolvedts_heap.go
  cdc/kv/resolvedts_heap_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7153 etcd (ticdc): delete some dead code.
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/orchestrator/etcd_worker.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7166 discovery,election(engine): remove unused code
  deployments/engine/docker-compose/config/master.toml
  deployments/engine/docker-compose/config/master_with_tls.toml
  deployments/engine/docker-compose/config/template_master.toml
  deployments/engine/helm/tiflow/templates/_helpers.tpl
  engine/model/cluster.go
  engine/model/cluster_test.go
  engine/pkg/cmd/master/master.go
  engine/pkg/etcdutil/config.go
  engine/pkg/etcdutil/main_test.go
  engine/pkg/etcdutil/service.go
  engine/pkg/etcdutil/testing.go
  engine/pkg/serverutil/discovery_keepalive.go
  engine/pkg/serverutil/discovery_keepalive_test.go
  engine/pkg/serverutil/main_test.go
  engine/pkg/srvdiscovery/etcd_impl.go
  engine/pkg/srvdiscovery/etcd_impl_test.go
  engine/pkg/srvdiscovery/interface.go
  engine/pkg/srvdiscovery/main_test.go
  engine/pkg/srvdiscovery/runner.go
  engine/pkg/srvdiscovery/runner_test.go
  engine/servermaster/campaign.go
  engine/servermaster/campaign_test.go
  engine/servermaster/cluster/election.go
  engine/servermaster/cluster/election_test.go
  engine/servermaster/cluster/main_test.go
  engine/servermaster/cluster/session.go
  engine/servermaster/cluster/session_test.go
  engine/servermaster/config.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
  engine/test/etcd_utils.go
  engine/test/etcd_utils_test.go
  engine/test/mock/discovery.go
  engine/test/mock/discovery_runner.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#7079 puller(ticdc): region worker batch process events
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/model/kv.go
  cdc/model/kv_test.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#7175 syncpoint (ticdc): change changefeed column value
  cdc/sink/mysql/mysql_syncpoint_store.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-6.3

#7171 puller(ticdc): remove IsInitialized func from puller
  cdc/puller/ddl_puller_test.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#7195 sinkv2(ticdc): correctly return the error message
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink_test.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.3

#7192 sinkv2(ticdc): flush interval conflict detector bfs
  cdc/sinkv2/eventsink/txn/backend.go
  cdc/sinkv2/eventsink/txn/mysql/mysql.go
  cdc/sinkv2/eventsink/txn/txn_sink_test.go
  cdc/sinkv2/eventsink/txn/worker.go
  pkg/causality/conflict_detector.go
  pkg/causality/internal/node.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.3

#7186 test(engine): migrate DM GBK test
  engine/test/integration_tests/dm_collation/run.sh
  engine/test/integration_tests/dm_sql_mode/data/db1.increment.sql
  engine/test/integration_tests/dm_sql_mode/data/db1.prepare.sql
  engine/test/integration_tests/dm_sql_mode/data/db2.increment.sql
  engine/test/integration_tests/dm_sql_mode/data/db2.prepare.sql
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7185 master-client(engine): fix panic in async reload master info
  .codecov.yml
  engine/framework/internal/worker/master_client.go
  engine/framework/internal/worker/master_client_test.go
  engine/pkg/orm/mock/client_mock.go
  scripts/generate-engine-mock.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#5463 ui(dm): fix db/table pattern
  dm/ui/src/components/CreateOrUpdateTask/MigrateRule.tsx
  dm/ui/src/models/task.ts
  dm/ui/src/pages/migration/task/index.tsx
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#7193 engine(dm): use jsonpb instead json to fix omitempty
  engine/executor/dm/api.go
  engine/executor/dm/api_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#7178 servermaster(engine): generate master id based on name
  deployments/engine/docker-compose/1m1e.yaml
  deployments/engine/docker-compose/1m3e.yaml
  deployments/engine/docker-compose/3m3e.yaml
  deployments/engine/docker-compose/3m3e_with_tls.yaml
  deployments/engine/helm/tiflow/templates/server-master.yaml
  engine/servermaster/executor_manager.go
  engine/servermaster/server.go
  engine/servermaster/service_util.go
  engine/servermaster/service_util_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7200 kv(ticdc): remove dead code from span
  cdc/kv/region_worker_test.go
  pkg/regionspan/span.go
  pkg/regionspan/span_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7184 util: mask sasl-password in sink-uri
  cdc/model/changefeed_test.go
  pkg/util/uri.go
  pkg/util/uri_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note

#7213 sinkv2(ticdc): improve logs for table sink
  cdc/processor/processor.go
  cdc/sinkv2/eventsink/factory/factory.go
  cdc/sinkv2/eventsink/factory/factory_test.go
  cdc/sinkv2/tablesink/table_sink_impl.go
  cdc/sinkv2/tablesink/table_sink_impl_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#7062 framework(engine): operation-friendly fail path
  engine/executor/server.go
  engine/framework/registry/registry.go
  engine/test/integration_tests/dm_full_mode/run.sh
  engine/test/integration_tests/dm_many_tables/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7219 pkg/pdutil(ticdc): fix a deadlock issue
  pkg/pdutil/clock.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc

#7215 codec(ticdc): add unit test to cover maxwell message encode binary data
  cdc/sink/codec/maxwell/maxwell_message_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#7113 chore(ticdc): bump sarama to 1.36.0 to support kafka 3.x
  cdc/sink/mq/producer/kafka/kafka_test.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/M, release-note

#7203 puller(ticdc): remove span hack func call from frontier Forward
  cdc/kv/client.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#7226 p2p(*): use common component name in p2p module
  pkg/p2p/server.go
  pkg/p2p/server_test.go
  pkg/p2p/server_wrapper.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none

#7214 sinkv2(cdc): add more sinkv2 txn sink metrics
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#7130 jobmanager(engine): terminate job if it fails continuously more than several times
  deployments/engine/docker-compose/config/master.toml
  deployments/engine/helm/tiflow/values.yaml
  engine/servermaster/job_fsm.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  engine/servermaster/jobop/backoff.go
  engine/servermaster/jobop/backoff_manager.go
  engine/servermaster/jobop/backoff_manager_test.go
  engine/servermaster/jobop/backoff_test.go
  engine/servermaster/jobop/config.go
  engine/servermaster/jobop/mock/backoffmanager_mock.go
  engine/servermaster/jobop/operator.go
  errors.toml
  pkg/errors/engine_errors.go
  scripts/generate-engine-mock.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#7210 cli(ticdc): Add cluster id for capture cli command
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/model/http_model.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/cli/cli_capture_list.go
  tests/integration_tests/availability/capture.sh
  tests/integration_tests/availability/owner.sh
  tests/integration_tests/availability/processor.sh
  tests/integration_tests/changefeed_reconstruct/run.sh
  tests/integration_tests/http_api/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7232 metrics(ticdc): delete metrics when close the processor and update metrics panel
  cdc/owner/metrics.go
  cdc/owner/owner.go
  cdc/processor/processor.go
  cdc/sinkv2/metrics/statistics.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, type/enhancement

#7208 util(dm): auto split the transaction when it's too large
  dm/pkg/conn/baseconn.go
  dm/pkg/conn/baseconn_test.go
  dm/pkg/conn/basedb_test.go
  dm/syncer/checkpoint.go
  dm/syncer/dbconn/db.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3

#7155 *(engine): add comments to interface
  engine/executor/cvs/cvstask.go
  engine/executor/dm/api_test.go
  engine/executor/dm/worker.go
  engine/executor/dm/worker_test.go
  engine/framework/base_jobmaster.go
  engine/framework/base_jobmaster_test.go
  engine/framework/fake/fake_master.go
  engine/framework/fake/fake_worker.go
  engine/framework/master.go
  engine/framework/master_test.go
  engine/framework/mock_master_impl.go
  engine/framework/mock_worker_impl.go
  engine/framework/worker.go
  engine/framework/worker_test.go
  engine/jobmaster/cvsjob/cvs_job_master.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/example/master_impl.go
  engine/jobmaster/example/worker_impl.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#7216 etcd (ticdc): fix etcd transaction operation out of limit.
  cdc/capture/capture.go
  cdc/owner/changefeed.go
  cdc/processor/manager.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/orchestrator/etcd_worker.go
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-6.1

#7242 lightning(dm): all lightning errors are not auto-resumeable
  dm/_utils/terror_gen/errors_release.txt
  dm/errors.toml
  dm/loader/lightning.go
  dm/pkg/retry/errors.go
  dm/pkg/terror/error_list.go
  dm/worker/server_test.go
  dm/worker/task_checker_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7212 lightning(dm): add current speed in status
  dm/loader/lightning.go
  dm/loader/loader.go
  dm/loader/status.go
  dm/loader/status_test.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/tests/print_status/run.sh
  proto/canal/CanalProtocol.pb.go
  proto/canal/EntryProtocol.pb.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#7245 mounter(ticdc): change log level from info to debug for some logs
  cdc/entry/mounter.go
Labels: status/LGT2, status/can-merge, size/XS, release-note, needs-cherry-pick-release-6.1

#7260 config(ticdc): fix typos
  pkg/config/replica_config_test.go
  pkg/config/sink.go
Labels: component/configuration, status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, area/ticdc

#7057 worker(dm):fix data race of Start/Close of DM-worker's Server
  cmd/dm-worker/main.go
  dm/worker/server.go
  dm/worker/server_test.go
Labels: status/LGT2, status/can-merge, first-time-contributor, size/M, release-note, area/dm

#7240 Fix build on FreeBSD
  .github/workflows/check_and_build.yaml
  .github/workflows/dataflow_engine_chaos.yaml
  .github/workflows/dataflow_engine_e2e.yaml
  .github/workflows/dm_binlog_999999.yaml
  .github/workflows/dm_chaos.yaml
  .github/workflows/dm_upstream_switch.yaml
  .github/workflows/ticdc_integration.yaml
  .github/workflows/upgrade_dm_via_tiup.yaml
  .golangci.yml
  CONTRIBUTING.md
  README_DM.md
  README_TiCDC.md
  deployments/engine/docker/Dockerfile
  deployments/engine/docker/dind.Dockerfile
  deployments/ticdc/docker/Dockerfile
  deployments/ticdc/docker/dev.Dockerfile
  deployments/ticdc/docker/integration-test.Dockerfile
  deployments/ticdc/docker/kafka-consumer.Dockerfile
  dm/Dockerfile
  go.mod
  go.sum
  pkg/fsutil/disk_info_freebsd.go
  tools/check/go.mod
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7251 pipeline(ticdc): Add rate limit for some repeated logs
  cdc/kv/region_worker.go
  cdc/processor/pipeline/table_actor.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7244 dmctl: remove update from operate-source
  dm/ctl/master/operate_source.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, type/enhancement

#7263 sinkv2(ticdc): add mq worker flush duration metric
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer.go
  cdc/sinkv2/eventsink/mq/worker.go
  cdc/sinkv2/eventsink/txn/mysql/mysql.go
  cdc/sinkv2/eventsink/txn/worker.go
  cdc/sinkv2/metrics/metrics.go
  cdc/sinkv2/metrics/mq/kafka/collector.go
  cdc/sinkv2/metrics/mq/kafka/metric.go
  cdc/sinkv2/metrics/mq/metrics.go
  cdc/sinkv2/metrics/statistics.go
  cdc/sinkv2/metrics/txn/metrics.go
  metrics/grafana/ticdc.json
Labels: component/sink, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#7273 test(ticdc): Correct SHA256 checksum for downloaded golang version
  deployments/ticdc/docker/integration-test.Dockerfile
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc

#7259 syncer(dm): split big transaction when flush checkpoint
  dm/syncer/checkpoint.go
  dm/syncer/dbconn/db.go
  dm/syncer/syncer.go
  dm/tests/adjust_gtid/run.sh
  dm/tests/many_tables/conf/tidb-config-small-txn.toml
  dm/tests/many_tables/run.sh
  dm/tests/start_task/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.3
