Repository pingcap/tiflow, pull requests merged in 2022-11, with the labels that each got.

#7498 metrics(ticdc): adjust lag bucket
  cdc/owner/metrics.go
  cdc/owner/metrics_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7424 puller(ticdc): remove some lock from region_state.go
  cdc/kv/client.go
  cdc/kv/region_state.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7495 test(dm): add a test to make sure there's no problem :P
  dm/syncer/syncer_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm, needs-cherry-pick-release-6.1

#7418 syncpoint (ticdc): support external ts read for TiCDC's downstream when syncpoint is enabled.
  cdc/sink/mysql/mysql_syncpoint_store.go
  pkg/errorutil/util.go
  pkg/errorutil/util_test.go
  tests/integration_tests/syncpoint/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note

#7456 checker(dm): prepare to check on both upstream and downstream table structures
  dm/checker/checker.go
  dm/pkg/checker/privilege.go
  dm/pkg/checker/privilege_test.go
  dm/pkg/checker/table_structure.go
  dm/pkg/checker/table_structure_test.go
  dm/pkg/utils/common.go
  dm/pkg/utils/common_test.go
  dm/tests/gbk/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#7515 sorter(ticdc): fix remainEvents metric
  cdc/processor/pipeline/sorter.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#7459 filter (ticdc): add integration test for event filter
  tests/integration_tests/_utils/check_contains
  tests/integration_tests/_utils/check_table_not_exists
  tests/integration_tests/event_filter/conf/cf.toml
  tests/integration_tests/event_filter/conf/diff_config.toml
  tests/integration_tests/event_filter/data/test.sql
  tests/integration_tests/event_filter/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7509 notifier(engine): fix Flush deadloop in closed notifier
  engine/pkg/notifier/notifier.go
  engine/pkg/notifier/notifier_test.go
  engine/servermaster/executor_manager.go
  engine/servermaster/executor_manager_test.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#7451 tls(dm): fix the error when give empty tls config
  dm/pkg/conn/basedb.go
  dm/tests/tls/conf/diff_config-1.toml
  dm/tests/tls/conf/dm-master-no-tls.toml
  dm/tests/tls/conf/dm-task-no-tls.yaml
  dm/tests/tls/conf/dm-worker3.toml
  dm/tests/tls/conf/source-no-tls.yaml
  dm/tests/tls/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7517 sink(ticdc): Fix several issues in cloud storage sink
  cdc/sink/codec/csv/csv_message.go
  cdc/sink/codec/csv/csv_message_test.go
  cdc/sinkv2/eventsink/cloudstorage/dml_worker.go
  cdc/sinkv2/eventsink/cloudstorage/encoding_worker.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/cloudstorage/table_definition_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7511 status(dm): add progress/bps from tidb/dumpling
  dm/dumpling/dumpling.go
  dm/dumpling/dumpling_test.go
  dm/loader/lightning.go
  dm/loader/loader.go
  dm/loader/status.go
  dm/loader/status_test.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/syncer/status.go
  dm/syncer/syncer.go
  dm/tests/print_status/run.sh
  engine/executor/dm/api_test.go
  engine/jobmaster/dm/api_test.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/dm

#7504 sink, config (ticdc): enable transaction split and disable safeMode by default
  cdc/api/v1/validator_test.go
  cdc/api/v2/api_helpers_test.go
  cdc/sink/mysql/mysql_params.go
  cdc/sink/mysql/mysql_params_test.go
  cdc/sink/mysql/mysql_test.go
  cdc/sinkv2/eventsink/txn/mysql/mysql_test.go
  cmd/kafka-consumer/main.go
  pkg/applier/redo_test.go
  pkg/config/sink.go
  pkg/config/sink_test.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/config_test.go
  tests/integration_tests/_utils/run_kafka_consumer
Labels: status/LGT2, status/can-merge, size/M, release-note

#7480 model(cdc): add a function to recover TiDB TableInfo
  cdc/entry/mounter_test.go
  cdc/model/schema_storage.go
  cdc/model/sink.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7518 sink(ticdc): Add integration test for cloud storage sink
  Makefile
  deployments/ticdc/docker-compose/docker-compose-storage-integration.yml
  deployments/ticdc/docker/integration-test.Dockerfile
  tests/integration_tests/_utils/run_storage_consumer
  tests/integration_tests/_utils/stop_tidb_cluster
  tests/integration_tests/csv/conf/changefeed.toml
  tests/integration_tests/csv/conf/diff_config.toml
  tests/integration_tests/csv/data/data.sql
  tests/integration_tests/csv/data/schema.sql
  tests/integration_tests/csv/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note

#7484 sinkmanager(ticdc): impl worker and mem quota
  cdc/model/mounter.go
  cdc/processor/sinkmanager/mem_quota.go
  cdc/processor/sinkmanager/mem_quota_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/processor/sinkmanager/worker.go
  cdc/processor/sinkmanager/worker_impl.go
  pkg/sorter/sorter.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7445 sinkv2(cdc): improve conflict detector throughput in some cases
  pkg/causality/internal/node.go
  pkg/causality/internal/node_test.go
  pkg/causality/internal/slots.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.3

#7491 engine(externalresource): add cleanPersistResource method for filemananger
  engine/pkg/externalresource/broker/broker.go
  engine/pkg/externalresource/broker/broker_test.go
  engine/pkg/externalresource/internal/file_manager.go
  engine/pkg/externalresource/internal/local/file_manager.go
  engine/pkg/externalresource/internal/s3/file_manager.go
  engine/pkg/externalresource/internal/s3/file_manager_test.go
  engine/pkg/externalresource/internal/s3/file_path_util.go
  engine/pkg/externalresource/internal/s3/resource_controller_test.go
  engine/pkg/externalresource/internal/s3/s3_test_utils.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#7502 servermaster(engine): support API level availability check
  engine/pkg/externalresource/integration_test/gc_test.go
  engine/pkg/externalresource/integration_test/mock_cluster.go
  engine/pkg/externalresource/manager/service_test.go
  engine/pkg/rpcutil/mock/featurechecker_mock.go
  engine/pkg/rpcutil/server.go
  engine/pkg/rpcutil/server_test.go
  engine/servermaster/server.go
  engine/servermaster/service_util.go
  engine/servermaster/service_util_test.go
  scripts/generate-mock.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#7527 redo (ticdc): set safeMode to true when redo apply
  pkg/cmd/redo/apply.go
  pkg/cmd/redo/apply_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7534 integration_test (ticdc): set global `tidb_enable_clustered_index = INT_ONLY` before execute any SQL
  tests/integration_tests/_utils/run_sql
  tests/integration_tests/_utils/run_sql_file
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#7503 syncer(dm): remove placement rule table option for tracker
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
Labels: status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note, area/dm

#7474 sinkv2(cdc): implement EventSortEngine based on pebble
  pkg/sorter/manager/manager.go
  pkg/sorter/manager/pebble.go
  pkg/sorter/pebble/db.go
  pkg/sorter/pebble/db_test.go
  pkg/sorter/pebble/doc.go
  pkg/sorter/pebble/encoding/key.go
  pkg/sorter/pebble/encoding/key_test.go
  pkg/sorter/pebble/encoding/value.go
  pkg/sorter/pebble/event_sorter.go
  pkg/sorter/pebble/event_sorter_test.go
  pkg/sorter/sorter.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#7537 sinkv2(cdc): add a memory table based sort engine for tests
  pkg/sorter/memory/doc.go
  pkg/sorter/memory/event_sorter.go
  pkg/sorter/memory/event_sorter_test.go
  pkg/sorter/memory/main_test.go
  pkg/sorter/sorter.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#7531 grafana(ticdc): fix KV client batch resolved region count expression
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XS, component/metrics-logging, release-note-none, area/ticdc

#7536 sinkmanager(ticdc): implement sink manager
  cdc/model/changefeed_test.go
  cdc/processor/sinkmanager/main_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_impl.go
  cdc/processor/sinkmanager/mem_quota.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/processor/sinkmanager/worker.go
  cdc/processor/sinkmanager/worker_impl.go
  cdc/processor/sinkmanager/worker_impl_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/server_config.go
  pkg/sorter/memory/event_sorter.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7558 lint(all): upgrade golangci-lint to v1.50.1
  .golangci.yml
  cdc/kv/matcher.go
  cdc/processor/manager.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/processor/sinkmanager/worker_impl_test.go
  cdc/puller/ddl_puller_test.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/replication/replication_set_test.go
  cdc/sink/codec/avro/avro_test.go
  cdc/sink/codec/csv/csv_message_test.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink_test.go
  cdc/verification/checker.go
  dm/.golangci.yml
  dm/pkg/checker/utils.go
  dm/syncer/causality.go
  dm/syncer/sharding_group.go
  dm/syncer/syncer.go
  dm/worker/server.go
  engine/executor/dm/main_test.go
  engine/executor/main_test.go
  engine/framework/main_test.go
  engine/jobmaster/dm/main_test.go
  engine/pkg/client/main_test.go
  engine/pkg/dm/main_test.go
  engine/pkg/election/elector.go
  engine/pkg/externalresource/manager/main_test.go
  engine/pkg/meta/internal/etcdkv/main_test.go
  engine/servermaster/main_test.go
  engine/servermaster/server.go
  pkg/actor/actor.go
  pkg/cmd/redo/apply.go
  pkg/migrate/migrate_test.go
  pkg/p2p/server_client_integration_test.go
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#7507 dm(engine): add created time for dm's unit
  engine/jobmaster/dm/api.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/metadata/metadata.go
  engine/jobmaster/dm/metadata/unit_state.go
  engine/jobmaster/dm/metadata/unit_state_test.go
  engine/jobmaster/dm/openapi_test.go
  engine/jobmaster/dm/worker_manager.go
  engine/jobmaster/dm/worker_manager_test.go
  engine/pkg/adapter/keyadapter.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#7546 mq(ticdc): encoder group support batch encode protocol
  cdc/sink/codec/canal/canal_json_encoder.go
  cdc/sink/codec/encoder.go
  cdc/sink/codec/encoder_group.go
  cdc/sink/codec/open/open_protocol_encoder.go
  cdc/sinkv2/eventsink/mq/worker.go
  cdc/sinkv2/eventsink/mq/worker_test.go
  cdc/sinkv2/metrics/mq/metrics.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, needs-cherry-pick-release-6.1

#7560 sinkmanager(ticdc): add more tests for worker and manager
  cdc/processor/sinkmanager/manager_impl.go
  cdc/processor/sinkmanager/manager_impl_test.go
  cdc/processor/sinkmanager/mem_quota.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/processor/sinkmanager/worker_impl.go
  cdc/processor/sinkmanager/worker_impl_test.go
Labels: component/sink, component/test, status/LGT1, status/can-merge, size/XXL, require-LGT1, release-note-none, area/ticdc

#7541 sink(ticdc): improve canal json encoder performance
  cdc/sink/codec/canal/canal_json_encoder.go
  cdc/sink/codec/canal/canal_json_encoder_test.go
  cdc/sink/codec/canal/canal_json_message.go
  go.mod
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-6.1

#7567 api(engine/dm): rename CreatedTime to Duration
  engine/jobmaster/dm/api.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/metadata/unit_state.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm, area/engine

#7448 lightning(dm): add config value to use local backend
  dm/_utils/terror_gen/errors_release.txt
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_test.go
  dm/errors.toml
  dm/loader/lightning.go
  dm/pkg/terror/error_list.go
  dm/tests/_utils/run_downstream_cluster
  dm/tests/case_sensitive/run.sh
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
  dm/tests/lightning_mode/conf/diff_config.toml
  dm/tests/lightning_mode/conf/dm-task.yaml
  dm/tests/lightning_mode/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#7571 *(engine): clean up deadcode
  engine/enginepb/errorv2.pb.go
  engine/pkg/workerpool/async_pool.go
  engine/pkg/workerpool/async_pool_impl.go
  engine/proto/errorv2.proto
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#7572 log(all): fix log caller skip
  go.mod
  go.sum
  pkg/logutil/log_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm, area/ticdc, area/engine

#7565 lint(engine): update lint scripts and config
  .golangci.yml
  Makefile
  engine/jobmaster/dm/metadata/cluster_info.go
  engine/jobmaster/dm/metadata/ddl.go
  engine/jobmaster/dm/metadata/job.go
  engine/jobmaster/dm/metadata/state_test.go
  engine/jobmaster/dm/metadata/unit_state.go
  engine/jobmaster/dm/worker_manager.go
  engine/pkg/client/executor_group.go
  engine/pkg/client/executor_service_client.go
  pkg/causality/tests/driver.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7578 mq(ticdc): fix send message time cost duration metrics inaccurate
  cdc/sinkv2/eventsink/mq/worker.go
  cdc/sinkv2/metrics/mq/metrics.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#7570 test(dm): fix query to mock is unordered
  dm/checker/check_test.go
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#7579 framework(engine): simplify CreateWorker API
  engine/framework/base_jobmaster.go
  engine/framework/fake/fake_master.go
  engine/framework/master.go
  engine/framework/master_test.go
  engine/jobmaster/cvsjob/cvs_job_master.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/worker_manager.go
  engine/jobmaster/dm/worker_manager_test.go
  engine/jobmaster/example/master_impl.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#7588 chaos(engine): fix unsupported collation in DM chaos test
  engine/chaos/cases/dm/case.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/dm, area/engine

#7587 dm(engine): openapi returns 503 when job master is not initialized
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/openapi.go
  engine/jobmaster/dm/openapi_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7591 sinkmanager(ticdc): consider table state when generate tasks
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_impl.go
  cdc/processor/sinkmanager/manager_impl_test.go
  cdc/processor/sinkmanager/table_progress_heap.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#7597 test(dm): set clustered index behaviour to old version
  dm/tests/_utils/run_tidb_server
  dm/tests/shardddl3/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#7575 sinkmanager(ticdc): release mem quota when remove a table
  cdc/processor/sinkmanager/manager_impl.go
  cdc/processor/sinkmanager/manager_impl_test.go
  cdc/processor/sinkmanager/mem_quota.go
  cdc/processor/sinkmanager/mem_quota_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/processor/sinkmanager/worker.go
  cdc/processor/sinkmanager/worker_impl.go
  cdc/processor/sinkmanager/worker_impl_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#7585 log(all): replace deprecated log.With
  cdc/scheduler/internal/v2/agent.go
  cdc/scheduler/internal/v2/schedule_dispatcher.go
  engine/pkg/externalresource/manager/service.go
  engine/pkg/rpcutil/middleware.go
  go.mod
  go.sum
  pkg/logutil/log.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none

#7564 checker(dm): considering extended column when precheck
  dm/checker/checker.go
  dm/pkg/checker/table_structure.go
  dm/pkg/checker/table_structure_test.go
  dm/pkg/utils/common.go
  dm/pkg/utils/common_test.go
  dm/tests/_utils/run_tidb_server
  dm/tests/adjust_gtid/run.sh
  dm/tests/extend_column/run.sh
  dm/tests/others_integration_1.txt
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7563 sink(ticdc): Support canal-json protocol in cloud storage sink
  cdc/api/v2/model.go
  cdc/sink/codec/canal/canal_json_decoder.go
  cdc/sink/codec/canal/canal_json_decoder_test.go
  cdc/sink/codec/canal/canal_json_encoder.go
  cdc/sink/codec/canal/canal_json_encoder_test.go
  cdc/sink/codec/common/config.go
  cdc/sink/codec/csv/csv_decoder.go
  cdc/sink/codec/csv/csv_decoder_test.go
  cdc/sink/codec/csv/csv_encoder.go
  cdc/sink/codec/csv/csv_encoder_test.go
  cdc/sink/codec/csv/csv_message.go
  cdc/sink/codec/csv/csv_message_test.go
  cdc/sinkv2/eventsink/cloudstorage/dml_worker.go
  cmd/kafka-consumer/main.go
  cmd/storage-consumer/main.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/config/sink_test.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/cloudstorage/config_test.go
  tests/integration_tests/_utils/run_storage_consumer
  tests/integration_tests/canal_json_storage_basic/conf/changefeed.toml
  tests/integration_tests/canal_json_storage_basic/conf/diff_config.toml
  tests/integration_tests/canal_json_storage_basic/data/data.sql
  tests/integration_tests/canal_json_storage_basic/data/schema.sql
  tests/integration_tests/canal_json_storage_basic/run.sh
  tests/integration_tests/csv/conf/changefeed.toml
  tests/integration_tests/csv/data/data.sql
  tests/integration_tests/csv_storage_basic/conf/changefeed.toml
  tests/integration_tests/csv_storage_basic/conf/diff_config.toml
  tests/integration_tests/csv_storage_basic/data/data.sql
  tests/integration_tests/csv_storage_basic/data/schema.sql
  tests/integration_tests/csv_storage_basic/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#7595 scheduler(ticdc): remove v2 scheduler
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/capture/capture_test.go
  cdc/model/http_model.go
  cdc/owner/changefeed.go
  cdc/owner/mock/status_provider_mock.go
  cdc/owner/owner.go
  cdc/owner/status_provider.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/info_provider.go
  cdc/scheduler/internal/v2/agent.go
  cdc/scheduler/internal/v2/agent_mock.go
  cdc/scheduler/internal/v2/agent_test.go
  cdc/scheduler/internal/v2/balancer.go
  cdc/scheduler/internal/v2/balancer_test.go
  cdc/scheduler/internal/v2/checkpoint_sender.go
  cdc/scheduler/internal/v2/checkpoint_sender_test.go
  cdc/scheduler/internal/v2/info_provider.go
  cdc/scheduler/internal/v2/info_provider_test.go
  cdc/scheduler/internal/v2/move_table_manager.go
  cdc/scheduler/internal/v2/move_table_manager_test.go
  cdc/scheduler/internal/v2/owner_scheduler.go
  cdc/scheduler/internal/v2/owner_scheduler_test.go
  cdc/scheduler/internal/v2/processor_agent.go
  cdc/scheduler/internal/v2/processor_agent_test.go
  cdc/scheduler/internal/v2/protocol/protocol.go
  cdc/scheduler/internal/v2/protocol/protocol_test.go
  cdc/scheduler/internal/v2/schedule_dispatcher.go
  cdc/scheduler/internal/v2/schedule_dispatcher_test.go
  cdc/scheduler/internal/v2/util/sort_table_ids.go
  cdc/scheduler/internal/v2/util/table_set.go
  cdc/scheduler/internal/v2/util/table_set_test.go
  cdc/scheduler/internal/v3/info_provider.go
  cdc/scheduler/internal/v3/info_provider_test.go
  cdc/scheduler/rexport.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  go.mod
  go.sum
  pkg/cmd/cli/cli_changefeed_statistics.go
  pkg/cmd/cli/cli_processor_query.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  tests/integration_tests/consistent_replicate_s3_schev2/conf/changefeed.toml
  tests/integration_tests/consistent_replicate_s3_schev2/conf/diff_config.toml
  tests/integration_tests/consistent_replicate_s3_schev2/conf/server.toml
  tests/integration_tests/consistent_replicate_s3_schev2/conf/workload
  tests/integration_tests/consistent_replicate_s3_schev2/run.sh
Labels: component/scheduler, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7600 framework(engine): refine worker factory errors
  engine/executor/init.go
  engine/executor/server.go
  engine/executor/server_test.go
  engine/framework/fake/errors.go
  engine/framework/fake/errors_test.go
  engine/framework/fake/register.go
  engine/framework/registry/factory.go
  engine/framework/registry/factory_test.go
  engine/framework/registry/registry_test.go
  errors.toml
  pkg/errors/engine_errors.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#7582 sinkv2(cdc): support to enable redo in sink manager
  cdc/processor/pipeline/sink.go
  cdc/processor/sinkmanager/manager_impl.go
  cdc/processor/sinkmanager/manager_impl_test.go
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sinkmanager/redo_cache_test.go
  cdc/processor/sinkmanager/worker.go
  cdc/processor/sinkmanager/worker_impl.go
  cdc/processor/sinkmanager/worker_impl_test.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/writer/writer.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#7604 makefile(all): add go-generate target
  Makefile
  cdc/redo/reader/file.go
  cdc/redo/reader/mock_RedoLogReader.go
  cdc/redo/reader/mock_fileReader.go
  cdc/redo/reader/reader.go
  cdc/redo/writer/file.go
  cdc/redo/writer/mock_RedoLogWriter.go
  cdc/redo/writer/mock_fileWriter.go
  cdc/redo/writer/writer.go
  cdc/verification/checker.go
  cdc/verification/mock_checkSumChecker.go
  scripts/check-copyright.sh
  scripts/generate-msgp-code.sh
  tools/Makefile
  tools/check/go.mod
  tools/check/go.sum
  tools/check/tools.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#7584 *: upgrade tidb version
  cdc/entry/schema_storage_test.go
  cdc/owner/schema_test.go
  go.mod
  go.sum
  pkg/leakutil/leak_helper.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7605 makefile(all): bump the default RELEASE_VERSION
  Makefile
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#7609 makefile(all): fix make check exit code
  Makefile
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none

#7618 engine: unit status use cached source status
  engine/executor/dm/unitholder.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#7594 metrics(engine/dm): add job task stage metrics
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/openapi_test.go
  engine/jobmaster/dm/task_manager.go
  engine/jobmaster/dm/task_manager_test.go
  engine/pkg/promutil/util.go
  engine/pkg/promutil/util_inner.go
  engine/test/e2e/e2e_dm_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm, area/engine

#7611 processor(ticdc): use ddl start ts to drive ddl puller on the processor side.
  cdc/processor/processor.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#7623 dm(engine): fix jobMaster panic
  engine/jobmaster/dm/dm_jobmaster.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#7607 dm(engine): openapi adapts engine error format
  dm/pkg/terror/errcode_string.go
  dm/pkg/terror/terror.go
  engine/jobmaster/dm/openapi.go
  engine/jobmaster/dm/openapi_test.go
  engine/pkg/openapi/common.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm, area/engine

#7620 servermaster(engine): add check and timeout for querying job detail
  engine/servermaster/jobmanager.go
  pkg/httputil/httputil.go
  pkg/httputil/httputil_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7612 log(dm): replace global logger with dm logger
  cmd/dm-syncer/main.go
  cmd/dm-worker/main.go
  dm/pkg/log/log.go
  dm/pkg/log/log_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#7586 tests(dm): migrate pingcap/check to testify for pkg/binlog
  dm/pkg/binlog/common/replication_test.go
  dm/pkg/binlog/common/stage_test.go
  dm/pkg/binlog/event/common_test.go
  dm/pkg/binlog/event/ddl_test.go
  dm/pkg/binlog/event/dml_test.go
  dm/pkg/binlog/event/event_test.go
  dm/pkg/binlog/event/generator_test.go
  dm/pkg/binlog/event/helper_test.go
  dm/pkg/binlog/event/sid_mysql_test.go
  dm/pkg/binlog/file_test.go
  dm/pkg/binlog/pos_finder_test.go
  dm/pkg/binlog/position_test.go
  dm/pkg/binlog/reader/file_test.go
  dm/pkg/binlog/reader/mock_test.go
  dm/pkg/binlog/reader/tcp_test.go
  dm/pkg/binlog/status_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#7635 log(engine): hide sensitive info in log
  engine/enginepb/hide_sensitive.go
  engine/enginepb/hide_sensitive_test.go
  engine/executor/server/metastore.go
  engine/pkg/externalresource/internal/s3/file_manager.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7590 syncer(dm): update dep to remove clone for TableInfo
  dm/pkg/schema/tracker.go
  engine/executor/server.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#7634 lightning(dm): switch to finer granularity finished status
  dm/loader/lightning.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7627 processor(ticdc): fix some bugs about pull-based sink
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager_impl.go
  cdc/processor/sinkmanager/worker_impl.go
  cdc/processor/sourcemanager/engine/factory/factory.go
  cdc/processor/sourcemanager/engine/mounted_iter.go
  cdc/processor/sourcemanager/engine/mounted_iter_test.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  pkg/config/server_config.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7647 framework(engine): fix label lost when job is failover
  engine/framework/internal/master/worker_creator.go
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#7649 processor/sinkmanager(ticdc): improve code struct and remove useless abstraction
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/tasks.go
Labels: component/sink, status/LGT1, status/can-merge, size/XL, require-LGT1, release-note-none, area/ticdc

#7641 openapi(executor): standardize error format when job is not running
  engine/executor/openapi.go
  engine/executor/openapi_test.go
  engine/executor/server.go
  engine/jobmaster/dm/openapi.go
  engine/jobmaster/dm/openapi_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7652 servermaster(engine): increase job backoff retry time
  engine/servermaster/jobop/config.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#7642 engine(dm): async fetch source status
  engine/executor/dm/unitholder.go
  engine/executor/dm/unitholder_test.go
  engine/executor/dm/worker.go
  engine/jobmaster/dm/dm_jobmaster.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7651 engine(dm): adjust the subtask config
  dm/config/task.go
  dm/loader/lightning.go
  engine/executor/dm/api_test.go
  engine/executor/dm/worker.go
  engine/executor/dm/worker_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7662 engine(dm): use new ctx rather than ctx of tick to get source status
  engine/executor/dm/unitholder.go
  engine/executor/dm/unitholder_test.go
  engine/executor/dm/worker.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm, area/engine

#7640 dm(engine): declarative command should consider time
  engine/executor/dm/worker.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/metadata/job.go
  engine/jobmaster/dm/metadata/unit_state.go
  engine/jobmaster/dm/task_manager.go
  engine/jobmaster/dm/task_manager_test.go
  engine/test/integration_tests/dm_collation/data/db2.prepare.sql
  engine/test/integration_tests/dm_collation/run.sh
  engine/test/integration_tests/dm_full_mode/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7548 sink(ticdc): Use dm sqlmodel pkg to generate sql in batch mode
  cdc/entry/mounter_test.go
  cdc/model/sink.go
  cdc/sink/mysql/mysql_test.go
  cdc/sinkv2/eventsink/event_sink.go
  cdc/sinkv2/eventsink/txn/mysql/dml.go
  cdc/sinkv2/eventsink/txn/mysql/mysql.go
  cdc/sinkv2/eventsink/txn/mysql/mysql_test.go
  cdc/sinkv2/eventsink/txn/txn_sink.go
  cdc/sinkv2/tablesink/table_sink_impl.go
  pkg/sink/mysql/config.go
  tests/integration_tests/batch_update_to_no_batch/conf/diff_config.toml
  tests/integration_tests/batch_update_to_no_batch/data/test.sql
  tests/integration_tests/batch_update_to_no_batch/data/test_finish.sql
  tests/integration_tests/batch_update_to_no_batch/data/test_v5.sql
  tests/integration_tests/batch_update_to_no_batch/run.sh
Labels: status/ptal, component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7669 feat(backoff): increase the total backoff time to 48 hours
  engine/servermaster/jobop/config.go
Labels: status/LGT2, status/can-merge, size/XS, release-note, area/engine

#7667 servermaster(engine): return labels in executor list API
  engine/pkg/orm/model/executor.go
  engine/pkg/orm/model/executor_test.go
  engine/servermaster/server.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7671 scheduler(engine): fix scheduler panic
  engine/servermaster/scheduler/scheduler.go
  engine/servermaster/scheduler/scheduler_test.go
  errors.toml
  pkg/errors/engine_errors.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7676 log(engine): remove sensitive info in log
  engine/executor/server/metastore.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#7675 processor/sinkmanager(ticdc): refine error handle and skip empty event
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, component/sorter, release-note-none, area/ticdc

#7679 sinkv2(cdc): fix bugs about enabling redo with pull-based-sink
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/mem_quota.go
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sinkmanager/redo_cache_test.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7681 cli(ticdc): cli support mounter worker-num parameter
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#7689 jobmaster(engine/dm): fix empty worker status for OnWorkerOnline/OnWorkerOffline
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7614 precheck(dm): check downstream's privileges
  dm/checker/check_test.go
  dm/checker/checker.go
  dm/config/checking_item.go
  dm/pkg/checker/conn_checker.go
  dm/pkg/checker/conn_checker_test.go
  dm/pkg/checker/privilege.go
  dm/pkg/checker/privilege_test.go
  dm/tests/check_task/conf/diff_config.toml
  dm/tests/check_task/conf/task-priv.yaml
  dm/tests/check_task/run.sh
  dm/tests/dmctl_command/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#7694 dm_jobmaster: add time out for waiting worker offline
  engine/jobmaster/dm/dm_jobmaster.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#7677 fix log flood when worker error
  engine/executor/dm/worker.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#7701 test(dm): turn off tidb_ddl_enable_fast_reorg
  dm/tests/_utils/run_tidb_server
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#7690 tests(dm): migrate pingcap/check to testify for pkg/utils
  dm/pkg/utils/db_test.go
  dm/pkg/utils/encrypt_test.go
  dm/pkg/utils/file_test.go
  dm/pkg/utils/filename_test.go
  dm/pkg/utils/hash_test.go
  dm/pkg/utils/relay_test.go
  dm/pkg/utils/storage_test.go
  dm/pkg/utils/util_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#7692 sink (ticdc): support base64 encoded password for mysql sink.
  cdc/sink/mysql/mysql.go
  pkg/sink/mysql/db_helper.go
  pkg/sink/mysql/db_helper_test.go
  tests/integration_tests/consistent_replicate_s3/run.sh
  tests/integration_tests/http_api/util/test_case.py
Labels: status/LGT2, status/can-merge, size/L, release-note

#7631 test(engine, dm): add task resume integration test
  deployments/engine/docker-compose/dm_databases.yaml
  deployments/engine/docker-compose/dm_databases_tidb_new_collation_off.yaml
  deployments/engine/docker-compose/dm_databases_with_tls.yaml
  engine/test/integration_tests/dm_many_tables/run.sh
  engine/test/utils/check_sync_diff
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7622 binlog: do not decode rows for block table
  dm/relay/local_reader.go
  dm/syncer/binlogstream/streamer_controller.go
  dm/syncer/data_validator.go
  dm/syncer/syncer.go
  dm/syncer/util.go
  dm/tests/binlog_parse/conf/diff_config.toml
  dm/tests/binlog_parse/conf/dm-master.toml
  dm/tests/binlog_parse/conf/dm-task.yaml
  dm/tests/binlog_parse/conf/dm-worker1.toml
  dm/tests/binlog_parse/conf/source1.yaml
  dm/tests/binlog_parse/data/db1.increment.sql
  dm/tests/binlog_parse/data/db1.increment1.sql
  dm/tests/binlog_parse/data/db1.prepare.sql
  dm/tests/binlog_parse/run.sh
  dm/tests/others_integration_2.txt
  dm/worker/subtask.go
  dm/worker/subtask_test.go
  go.mod
  go.sum
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note, area/dm

#7698 lightning(dm): update dependency for lightning
  dm/loader/lightning.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#7661 dm-worker: use run ctx instead global ctx to fix double write
  dm/worker/server.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#7697 engine/dm: period update status for dm worker
  engine/executor/dm/worker.go
  engine/framework/master.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/task_manager.go
  engine/jobmaster/dm/task_manager_test.go
  engine/jobmaster/dm/worker_manager.go
  engine/jobmaster/dm/worker_manager_test.go
  engine/pkg/dm/ticker/main_test.go
  engine/pkg/dm/ticker/ticker.go
  engine/pkg/dm/ticker/ticker_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#7655 openapi(engine): add filter and limit to list job
  engine/enginepb/master.pb.go
  engine/pkg/openapi/apiv1.swagger.json
  engine/proto/master.proto
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#7702 lightning(dm): ignore checkpoint error should using ExtStorage
  dm/loader/lightning.go
  engine/test/integration_tests/dm_full_mode/conf/job.yaml
  engine/test/integration_tests/dm_full_mode/data/db1.prepare.sql
  engine/test/integration_tests/dm_full_mode/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7617 checker(dm): port some precheck from lightning
  dm/checker/checker.go
  dm/config/checking_item.go
  dm/loader/lightning.go
  dm/pkg/checker/lightning.go
  dm/pkg/checker/lightning_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#7707 sink(cdc): cancel sink operations when network becomes unavailable
  cdc/sink/mysql/mysql.go
  cdc/sinkv2/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sinkv2/eventsink/txn/mysql/mysql.go
  cdc/sinkv2/eventsink/txn/mysql/mysql_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.1

#7713 sink (ticdc): disable safemode and enable transaction split by default
  cdc/api/validator_test.go
  cdc/sink/mysql/mysql_params.go
  cdc/sink/mysql/mysql_params_test.go
  cdc/sink/mysql/mysql_test.go
  pkg/applier/redo_test.go
  pkg/cmd/redo/apply.go
  pkg/cmd/redo/apply_test.go
  pkg/config/sink.go
  pkg/config/sink_test.go
  tests/integration_tests/_utils/run_kafka_consumer
Labels: status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note-none

#7708 relay(dm): update gtid for "COMMIT" query event
  dm/relay/file_util.go
  dm/relay/file_util_test.go
  dm/relay/relay_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-6.1

#7711 engine: make sure get-job-status can see unit status either in task_status or finished_unit_status
  engine/jobmaster/dm/api.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/pkg/dm/message_agent.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#7715 binlog_filter: use table name instead of table id as cache key
  dm/syncer/util.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#7709 processor/sinkmanager(ticdc): fix sink manager advance progess issues
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7722 processor,pkg(ticdc): add Span and package spanz
  cdc/processor/tablepb/table.go
  cdc/processor/tablepb/table.pb.go
  cdc/processor/tablepb/table.proto
  cdc/processor/tablepb/table_test.go
  pkg/spanz/convert.go
  pkg/spanz/map.go
  pkg/spanz/map_test.go
  pkg/spanz/set.go
  pkg/spanz/set_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7522 ticdc: set foreign_key_checks=0 for each connection to support sync table with foreign key
  cdc/sink/mysql/mysql_params.go
  pkg/sink/mysql/db_helper.go
  tests/integration_tests/_utils/start_tidb_cluster_impl
  tests/integration_tests/foreign_key/conf/diff_config.toml
  tests/integration_tests/foreign_key/data/prepare.sql
  tests/integration_tests/foreign_key/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7599 dm: add foreign key test for full phase
  dm/loader/lightning.go
  dm/tests/foreign_key/conf/diff_config.toml
  dm/tests/foreign_key/conf/dm-master.toml
  dm/tests/foreign_key/conf/dm-task.yaml
  dm/tests/foreign_key/conf/dm-worker1.toml
  dm/tests/foreign_key/conf/source1.yaml
  dm/tests/foreign_key/data/db1.prepare.sql
  dm/tests/foreign_key/run.sh
  dm/tests/others_integration_2.txt
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7721 test(engine): update lightning dependency to fix missing finishedBytes
  engine/test/integration_tests/dm_full_mode/run.sh
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#7547 sink/(ticdc): Simplify and optimize some logic in cloud storage sink
  cdc/entry/mounter.go
  cdc/model/schema_storage.go
  cdc/model/sink.go
  cdc/model/sink_gen.go
  cdc/processor/pipeline/sink.go
  cdc/sink/codec/avro/avro.go
  cdc/sink/codec/avro/avro_test.go
  cdc/sink/codec/csv/csv_message.go
  cdc/sink/mysql/txn_cache.go
  cdc/sinkv2/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sinkv2/ddlsink/cloudstorage/cloud_storage_ddl_sink_test.go
  cdc/sinkv2/ddlsink/factory/factory.go
  cdc/sinkv2/eventsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sinkv2/eventsink/cloudstorage/cloud_storage_dml_sink_test.go
  cdc/sinkv2/eventsink/cloudstorage/defragmenter.go
  cdc/sinkv2/eventsink/cloudstorage/defragmenter_test.go
  cdc/sinkv2/eventsink/cloudstorage/dml_worker.go
  cdc/sinkv2/eventsink/cloudstorage/dml_worker_test.go
  cdc/sinkv2/eventsink/cloudstorage/dml_writer.go
  cdc/sinkv2/eventsink/cloudstorage/encoding_worker.go
  cdc/sinkv2/eventsink/cloudstorage/encoding_worker_test.go
  cdc/sinkv2/eventsink/event_appender.go
  cdc/sinkv2/eventsink/factory/factory.go
  cmd/storage-consumer/main.go
  deployments/ticdc/docker/storage-consumer.Dockerfile
  pkg/filter/expr_filter.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/cloudstorage/table_definition_test.go
  pkg/sink/sink_type.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#7472 capture(cdc): fix cdc `NewSession` stuck when send SIGSTOP to pd leader
  cdc/capture/capture.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#7714 config(dm): add on-duplicate-logical, on-duplicate-physical
  dm/_utils/terror_gen/errors_release.txt
  dm/config/task.go
  dm/config/task_converters.go
  dm/config/task_test.go
  dm/errors.toml
  dm/loader/lightning.go
  dm/pkg/terror/errcode_string.go
  dm/pkg/terror/error_list.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/full_mode/conf/dm-task.yaml
  dm/tests/full_mode/run.sh
  dm/tests/import_v10x/conf/task.yaml
  dm/worker/subtask.go
  engine/jobmaster/dm/config/config_test.go
  engine/jobmaster/dm/config/dm_subtask_3306.toml
  engine/jobmaster/dm/config/dm_subtask_3307.toml
  engine/jobmaster/dm/config/job_template.yaml
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#7703 rpcutil(engine): refactor rpc hook to interceptor
  engine/executor/server.go
  engine/pkg/election/elector.go
  engine/pkg/election/elector_test.go
  engine/pkg/election/mock/elector_mock.go
  engine/pkg/externalresource/integration_test/mock_cluster.go
  engine/pkg/externalresource/manager/service.go
  engine/pkg/externalresource/manager/service_test.go
  engine/pkg/rpcutil/checker.go
  engine/pkg/rpcutil/client.go
  engine/pkg/rpcutil/client_test.go
  engine/pkg/rpcutil/middleware.go
  engine/pkg/rpcutil/middleware_test.go
  engine/pkg/rpcutil/mock/checker_mock.go
  engine/pkg/rpcutil/mock/featurechecker_mock.go
  engine/pkg/rpcutil/server.go
  engine/pkg/rpcutil/server_test.go
  engine/servermaster/campaign.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
  engine/servermaster/service_util.go
  engine/servermaster/service_util_test.go
  errors.toml
  pkg/errors/engine_errors.go
  scripts/generate-mock.sh
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#7696 precheck(dm): refine error message & instruction
  dm/checker/check_test.go
  dm/pkg/checker/binlog.go
  dm/pkg/checker/binlog_test.go
  dm/pkg/checker/conn_checker.go
  dm/pkg/checker/mysql_server.go
  dm/pkg/checker/mysql_server_test.go
  dm/pkg/checker/privilege.go
  dm/pkg/checker/table_structure.go
  dm/pkg/checker/table_structure_test.go
  dm/tests/dmctl_command/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm

#7735 sink(ticdc): Add metrics for cloud storage sink
  cdc/sink/codec/csv/csv_encoder.go
  cdc/sinkv2/eventsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sinkv2/eventsink/cloudstorage/dml_worker.go
  cdc/sinkv2/eventsink/cloudstorage/dml_worker_test.go
  cdc/sinkv2/eventsink/cloudstorage/dml_writer.go
  cdc/sinkv2/metrics/cloudstorage/metrics.go
  cdc/sinkv2/metrics/metrics.go
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#7580 relay: add async/batch relay writer
  dm/relay/binlog_writer.go
  dm/relay/binlog_writer_test.go
  dm/relay/local_reader_test.go
  dm/relay/relay.go
  dm/relay/relay_writer.go
  dm/relay/relay_writer_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#7738 processor/owner(ticdc): fix potential data race in DDL sink
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_sink.go
  cdc/owner/ddl_sink_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc, component/owner

#7648 pkg/cfg(ticdc): enable pull based sink by default
  cdc/processor/pipeline/sink.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/mem_quota_test.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/redo/manager.go
  cdc/redo/writer/blackhole_writer.go
  cdc/redo/writer/mock_RedoLogWriter.go
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
  cdc/sinkv2/tablesink/progress_tracker.go
  cdc/sinkv2/tablesink/progress_tracker_test.go
  cdc/sinkv2/tablesink/table_sink.go
  cdc/sinkv2/tablesink/table_sink_impl.go
  cdc/sinkv2/tablesink/table_sink_impl_test.go
  pkg/applier/redo.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  tests/integration_tests/changefeed_resume_with_checkpoint_ts/run.sh
  tests/integration_tests/consistent_replicate_nfs/run.sh
  tests/integration_tests/event_filter/data/test.sql
  tests/integration_tests/event_filter/run.sh
  tests/integration_tests/processor_err_chan/run.sh
  tests/integration_tests/sorter/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#7519 capture(cdc): fix cdc `campagin` stuck when send SIGSTOP to pd leader
  cdc/api/owner/owner.go
  cdc/api/status/status.go
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/api/v1/validator.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/unsafe.go
  cdc/api/v2/unsafe_test.go
  cdc/capture/capture.go
  cdc/capture/capture_test.go
  cdc/capture/mock/capture_mock.go
  cdc/server/server.go
  pkg/etcd/etcd.go
  pkg/etcd/mock/etcd_client_mock.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#7665 sink,scheduler (ticdc): add slow table and big txn log.
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/owner_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/replication/replication_set_test.go
  cdc/scheduler/rexport.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#7630 changefeed,kvClient, sink (ticdc): support bidirectional replication
  cdc/api/v2/model.go
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/owner/changefeed.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/processor.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  cdc/sink/mysql/mysql.go
  cdc/sink/sink_test.go
  cdc/sink/validator.go
  cdc/sink/validator_test.go
  cdc/sinkv2/eventsink/txn/mysql/mysql.go
  cdc/sinkv2/eventsink/txn/mysql/mysql_test.go
  go.mod
  go.sum
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/sink.go
  pkg/pdutil/utils.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/db_helper.go
  pkg/txnutil/gc/testing.go
  tests/integration_tests/bdr_mode/conf/cf.toml
  tests/integration_tests/bdr_mode/conf/diff_config.toml
  tests/integration_tests/bdr_mode/data/down.sql
  tests/integration_tests/bdr_mode/data/finished.sql
  tests/integration_tests/bdr_mode/data/start.sql
  tests/integration_tests/bdr_mode/data/up.sql
  tests/integration_tests/bdr_mode/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#7729 server-master(engine): update readme
  engine/servermaster/README.md
Labels: status/ptal, status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/engine

#7737 processor/sinkmanager(ticdc): background GC sort engine data
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sourcemanager/engine/mock/engine_mock.go
  scripts/generate-mock.sh
Labels: component/sink, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#7739 checker(dm): support wildcard in privilege checking
  dm/pkg/checker/privilege.go
  dm/pkg/checker/privilege_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note, needs-cherry-pick-release-6.1

#7746 version(ticdc): skip checking TiFlash version
  pkg/version/check.go
  pkg/version/check_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, needs-cherry-pick-release-5.0, size/S, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1
