Repository pingcap/tiflow, pull requests merged in 2022-07, with the labels that each got.

#6038 sink(ticdc): add transaction-atomicity parameter to SinkURI
  cdc/api/validator/validator_test.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/sink/flowcontrol/flow_control.go
  cdc/sink/flowcontrol/flow_control_test.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_test.go
  cdc/sink/sink.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/config/sink_test.go
  tests/integration_tests/big_txn/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#6118 sinkv2(ticdc): fix update resolved ts not taking effect issue
  cdc/sinkv2/eventsink/event_appender_test.go
  cdc/sinkv2/eventsink/main_test.go
  cdc/sinkv2/tablesink/event_table_sink.go
  cdc/sinkv2/tablesink/event_table_sink_test.go
  cdc/sinkv2/tablesink/progress_tracker_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#6113 SchedulerV3: basic scheduler don't add tables to the stopping capture
  cdc/scheduler/internal/tp/agent.go
  cdc/scheduler/internal/tp/agent_test.go
  cdc/scheduler/internal/tp/capture_manager.go
  cdc/scheduler/internal/tp/scheduler_basic.go
  cdc/scheduler/internal/tp/scheduler_basic_test.go
  cdc/scheduler/internal/tp/scheduler_rebalance.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/XL, release-note-none, type/enhancement, area/ticdc

#6119 syncer(dm): add the function GetTimezoneByStatusVars()
  dm/pkg/binlog/event/util.go
  dm/pkg/binlog/event/util_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#6141 sink/mysql(ticdc): make mysql sink to handle ipv6 address correctly
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_syncpoint_store.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/simple_mysql_tester.go
Labels: component/sink, status/LGT2, status/can-merge, size/M, release-note, area/ticdc

#5683 redo(ticdc): make implementation in manager asynchronously
  cdc/metrics.go
  cdc/model/sink.go
  cdc/model/sink_gen.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/redo/common/metric.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/writer/blackhole_writer.go
  cdc/redo/writer/file.go
  cdc/redo/writer/file_test.go
  cdc/redo/writer/metric.go
  cdc/redo/writer/mock_RedoLogWriter.go
  cdc/redo/writer/mock_fileWriter.go
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
  cdc/sink/mq/codec/avro.go
  cdc/sink/mq/codec/canal.go
  cdc/sink/mq/codec/canal_flat.go
  cdc/sink/mq/codec/canal_flat_test.go
  cdc/sink/mq/codec/craft.go
  cdc/sink/mq/codec/craft/encoder.go
  cdc/sink/mq/codec/craft/model.go
  cdc/sink/mq/codec/craft_test.go
  cdc/sink/mq/codec/decoder.go
  cdc/sink/mq/codec/json.go
  cdc/sink/mq/codec/json_test.go
  cdc/sink/mq/codec/maxwell.go
  cdc/sink/mq/codec/message.go
  cdc/sink/mq/codec/message_test.go
  cmd/kafka-consumer/main.go
  metrics/grafana/ticdc.json
  pkg/applier/redo.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  tests/integration_tests/consistent_replicate_nfs/conf/workload
  tests/integration_tests/consistent_replicate_nfs/run.sh
  tests/integration_tests/consistent_replicate_s3/conf/workload
  tests/integration_tests/consistent_replicate_s3/run.sh
  tests/integration_tests/consistent_replicate_schedulerv3/conf/workload
  tests/integration_tests/consistent_replicate_schedulerv3/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#6096 tests(cdc): migrate pingcap/check to testify, remove unused leaktest
  Makefile
  cdc/model/owner_test.go
  pkg/txnutil/gc/gc_manager_test.go
  pkg/txnutil/gc/gc_service_test.go
  pkg/txnutil/gc/main_test.go
  pkg/util/testleak/leaktest.go
  scripts/add-leaktest.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#6139 pipeline(ticdc): remove replConfig in pipeline
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#6162 test(ticdc): Fix merge master to feature branch test failed issues
  cdc/api/v1/api_test.go
  tests/integration_tests/changefeed_resume_with_checkpoint_ts/run.sh
Labels: size/XS, release-note-none

#6136 chaos(engine): reduce network partition duration in test
  engine/chaos/cases/case_fake_job.go
  engine/chaos/manifests/network-emulation-dataflow.yaml
  engine/chaos/manifests/network-partition-dataflow.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#6154 scheduler(cdc): fix latency spike when a new capture online
  cdc/scheduler/internal/tp/coordinator.go
  cdc/scheduler/internal/tp/metrics.go
  cdc/scheduler/internal/tp/replication_manager.go
  cdc/scheduler/internal/tp/scheduler_balance.go
  cdc/scheduler/internal/tp/scheduler_balance_test.go
  cdc/scheduler/internal/tp/scheduler_drain_capture.go
  cdc/scheduler/internal/tp/scheduler_manager.go
  cdc/scheduler/internal/tp/scheduler_manager_test.go
  cdc/scheduler/internal/tp/scheduler_rebalance.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#6143 chaos(engine): add time shift chaos test
  .github/workflows/dataflow_engine_chaos.yaml
  engine/chaos/manifests/time-shift-dataflow.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#6142 cli(ticdc): Stablize the changefeed list result
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/model/changefeed.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#6131 dm(engine): fetch source status when API call
  dm/dm/config/source_config.go
  dm/dm/config/subtask.go
  dm/dm/worker/source_worker.go
  dm/dumpling/dumpling.go
  dm/pkg/binlog/file.go
  dm/pkg/binlog/pos_finder.go
  dm/pkg/binlog/position.go
  dm/pkg/binlog/status.go
  dm/pkg/binlog/status_test.go
  dm/pkg/conn/baseconn.go
  dm/pkg/conn/utils.go
  dm/pkg/dumpling/utils.go
  dm/pkg/streamer/hub.go
  dm/pkg/utils/file.go
  dm/pkg/utils/filename.go
  dm/pkg/utils/filename_test.go
  dm/relay/file.go
  dm/relay/local_reader.go
  dm/relay/meta.go
  dm/relay/relay.go
  dm/relay/relay_writer.go
  dm/syncer/binlogstream/streamer_controller.go
  dm/syncer/data_validator.go
  dm/syncer/status.go
  dm/syncer/syncer.go
  engine/executor/dm/unitholder.go
  engine/executor/dm/unitholder_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#6166 docs(ticdc): fix incompatible configuration of transaction-atomicity
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#6165 api(ticdc): add changefeed unit tests
  cdc/api/status/status.go
  cdc/api/v1/api.go
  cdc/api/v1/validator.go
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_mock.go
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/api_test.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/api/v2/tso.go
  cdc/api/v2/tso_test.go
  cdc/api/v2/unsafe.go
  cdc/api/v2/unsafe_test.go
  cdc/api/v2/validator.go
  cdc/capture/capture.go
  cdc/capture/mock/capture_mock.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/etcd/client_for_api.go
  pkg/etcd/mock/etcd_client_mock.go
  pkg/upstream/manager.go
  pkg/upstream/manager_test.go
Labels: status/LGT2, size/XXL, release-note-none

#6049 pkg/causality(cdc): Implement a new conflict detector
  go.mod
  go.sum
  pkg/causality/conflict_detector.go
  pkg/causality/internal/node.go
  pkg/causality/internal/node_test.go
  pkg/causality/internal/slots.go
  pkg/causality/internal/slots_test.go
  pkg/causality/tests/driver.go
  pkg/causality/tests/integration_test.go
  pkg/causality/tests/worker.go
  pkg/causality/tests/workload.go
  pkg/causality/worker.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#6111 cmd(engine): add pkg/cmd package, use tiflow as binary name
  .github/workflows/dataflow_engine_chaos.yaml
  Makefile
  cmd/engine/main.go
  engine/Dockerfile
  engine/Dockerfile-local
  engine/ansible/roles/executor/templates/start.sh.j2
  engine/ansible/roles/master/templates/start.sh.j2
  engine/chaos/manifests/Dockerfile
  engine/chaos/manifests/executor.yaml
  engine/chaos/manifests/server-master.yaml
  engine/cmd/executor/main.go
  engine/cmd/master/main.go
  engine/executor/config.go
  engine/executor/config_test.go
  engine/executor/init.go
  engine/executor/server.go
  engine/executor/server_test.go
  engine/pkg/cmd/cmd.go
  engine/pkg/cmd/executor/executor.go
  engine/pkg/cmd/master/master.go
  engine/pkg/cmd/util/helper.go
  engine/pkg/cmd/version/version.go
  engine/sample/1m1e.yaml
  engine/sample/1m3e.yaml
  engine/sample/3m3e.yaml
  engine/servermaster/campaign_test.go
  engine/servermaster/config.go
  engine/servermaster/config_test.go
  engine/servermaster/member_test.go
  engine/servermaster/server_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#6172 test(ticdc): Define http model add ut
  cdc/api/v1/api.go
  cdc/api/v1/validator.go
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  pkg/cmd/cli/cli_unsafe_resolve_lock.go
Labels: size/L, release-note-none

#6170 config(engine): Refine meta storeConfig(Part1)
  engine/executor/server/metastore.go
  engine/executor/server/metastore_test.go
  engine/executor/server/mocks/metastore_mock.go
  engine/pkg/cmd/master/master.go
  engine/pkg/dbutil/config.go
  engine/pkg/dbutil/util.go
  engine/pkg/meta/kvclient/client.go
  engine/pkg/meta/kvclient/etcdkv/etcd_client.go
  engine/pkg/meta/kvclient/etcdkv/etcd_client_test.go
  engine/pkg/meta/metaclient/config.go
  engine/pkg/orm/client.go
  engine/pkg/orm/client_test.go
  engine/servermaster/config.go
  engine/servermaster/config_test.go
  engine/servermaster/metastore_manager.go
  engine/servermaster/metastore_manager_test.go
  engine/servermaster/server.go
  engine/test/e2e/e2e_test_cli.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#6185 chaos(engine): fix time shift case, use correct string type
  engine/chaos/manifests/time-shift-dataflow.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#6184 cli(ticdc): add cli checks while using --pd
  errors.toml
  pkg/cmd/factory/factory_impl.go
  pkg/errors/cdc_errors.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/etcdkey.go
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#6181 cli(engine): move master-client-cli to tiflow sub command
  Makefile
  engine/Dockerfile
  engine/cmd/master-client/main.go
  engine/ctl/cmd.go
  engine/ctl/ctl.go
  engine/executor/config.go
  engine/pkg/cmd/cli/cli.go
  engine/pkg/cmd/cli/cli_job.go
  engine/pkg/cmd/cli/cli_job_create.go
  engine/pkg/cmd/cli/cli_job_pause.go
  engine/pkg/cmd/cli/cli_job_query.go
  engine/pkg/cmd/cmd.go
  engine/pkg/cmd/executor/executor.go
  engine/sample/client.sh
  errors.toml
  pkg/errors/engine_errors.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#6179 meta(engine): Refine meta adjust meta pkg (Part2)
  engine/executor/dm/worker_test.go
  engine/executor/server.go
  engine/executor/server/metastore.go
  engine/executor/server/metastore_test.go
  engine/executor/server/mocks/metastore_mock.go
  engine/framework/base_jobmaster.go
  engine/framework/base_jobmaster_test.go
  engine/framework/master.go
  engine/framework/mock_master_impl.go
  engine/framework/mock_master_util.go
  engine/framework/mock_worker_impl.go
  engine/framework/mock_worker_util.go
  engine/framework/registry/factory_test.go
  engine/framework/worker.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/metadata/ddl.go
  engine/jobmaster/dm/metadata/job.go
  engine/jobmaster/dm/metadata/job_test.go
  engine/jobmaster/dm/metadata/metadata.go
  engine/jobmaster/dm/metadata/state.go
  engine/jobmaster/dm/metadata/state_test.go
  engine/jobmaster/dm/task_manager_test.go
  engine/jobmaster/dm/worker_manager_test.go
  engine/pkg/dataset/dataset.go
  engine/pkg/dataset/dataset_test.go
  engine/pkg/meta/client.go
  engine/pkg/meta/example.go
  engine/pkg/meta/internal/etcdkv/etcd_impl.go
  engine/pkg/meta/internal/etcdkv/etcd_impl_test.go
  engine/pkg/meta/internal/etcdkv/mock.go
  engine/pkg/meta/internal/etcdkv/mock_test.go
  engine/pkg/meta/internal/etcdkv/namespace/LICENSE
  engine/pkg/meta/internal/etcdkv/namespace/kv.go
  engine/pkg/meta/internal/etcdkv/namespace/kv_test.go
  engine/pkg/meta/internal/etcdkv/namespace/util.go
  engine/pkg/meta/internal/etcdkv/namespace/util_test.go
  engine/pkg/meta/internal/etcdkv/util.go
  engine/pkg/meta/metaclient/client.go
  engine/pkg/meta/mock/client_mock.go
  engine/pkg/meta/mock/simple_mockclient.go
  engine/pkg/meta/mock/simple_mockclient_test.go
  engine/pkg/meta/model/client.go
  engine/pkg/meta/model/common.go
  engine/pkg/meta/model/common_test.go
  engine/pkg/meta/model/config.go
  engine/pkg/meta/model/kv.go
  engine/pkg/meta/model/op.go
  engine/pkg/meta/model/op_test.go
  engine/pkg/orm/client.go
  engine/pkg/orm/client_test.go
  engine/servermaster/config.go
  engine/servermaster/metastore_manager.go
  engine/servermaster/metastore_manager_test.go
  engine/servermaster/server.go
  engine/test/e2e/e2e_test_cli.go
  scripts/generate-engine-mock.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#6183 validator(dm): add new it & fix some tips in dmctl
  dm/dm/ctl/master/start_stop_validation.go
  dm/tests/validator_basic/conf/sharding-task.yaml
  dm/tests/validator_basic/conf/source2.yaml
  dm/tests/validator_basic/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/dm

#6190 sink(ticdc): precheck the sink URI and give some hints
  cdc/sink/sink.go
  cdc/sink/validator.go
  cdc/sink/validator_test.go
  pkg/util/uri.go
  pkg/util/uri_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#6169 master(dm): DM didn't show error reason when meet SQL error
  dm/dm/master/openapi_controller.go
  dm/dm/master/openapi_controller_test.go
  dm/openapi/fixtures/task.go
Labels: status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none, area/dm

#6176 sink/mq(ticdc): split json.go and add callback
  cdc/sink/mq/codec/avro.go
  cdc/sink/mq/codec/canal.go
  cdc/sink/mq/codec/canal_flat.go
  cdc/sink/mq/codec/canal_flat_test.go
  cdc/sink/mq/codec/canal_test.go
  cdc/sink/mq/codec/codec_test.go
  cdc/sink/mq/codec/column.go
  cdc/sink/mq/codec/column_test.go
  cdc/sink/mq/codec/craft.go
  cdc/sink/mq/codec/craft_test.go
  cdc/sink/mq/codec/encoder.go
  cdc/sink/mq/codec/json.go
  cdc/sink/mq/codec/maxwell.go
  cdc/sink/mq/codec/maxwell_test.go
  cdc/sink/mq/codec/message.go
  cdc/sink/mq/codec/message_key.go
  cdc/sink/mq/codec/message_test.go
  cdc/sink/mq/codec/open_protocol_decoder.go
  cdc/sink/mq/codec/open_protocol_encoder.go
  cdc/sink/mq/codec/open_protocol_encoder_test.go
  cdc/sink/mq/codec/open_protocol_message.go
  cdc/sink/mq/mq_flush_worker.go
  cdc/sink/mq/mq_test.go
  cmd/kafka-consumer/main.go
  errors.toml
  pkg/errors/cdc_errors.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#6200 *(engine): rename remaining df prefix to tiflow
  .github/ISSUE_TEMPLATE/engine-bug-report.yml
  .github/workflows/dataflow_engine_chaos.yaml
  Makefile
  engine/Dockerfile
  engine/chaos/manifests/Dockerfile
  engine/chaos/manifests/cases.yaml
  engine/sample/demo.yaml
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#6196 metrics(cdc): add scheduler metrics
  metrics/grafana/ticdc.json
  scripts/check-ticdc-dashboard.sh
Labels: status/LGT2, status/can-merge, size/XXL, component/metrics-logging, release-note-none, area/ticdc

#6212 cli(ticdc) add checks on pdAddrs in cdc cli
  Makefile
  cdc/capture/capture.go
  pkg/cmd/cli/cli_tso_query.go
  pkg/cmd/factory/factory_impl.go
  pkg/cmd/factory/factory_impl_test.go
  pkg/cmd/factory/mock/factory_mock.go
Labels: status/LGT2, status/can-merge, size/XL, do-not-merge/release-note-label-needed

#6188 syncer(dm): solve the issue of nondeterministic DDLs may cause data inconsistency
  dm/syncer/data_validator.go
  dm/syncer/job.go
  dm/syncer/syncer.go
  dm/syncer/util.go
  dm/tests/many_tables/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm

#6222 api(ticdc): fix api model filter bug
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/capture/capture.go
  pkg/cmd/cli/cli_changefeed_create_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#6201 tests(ticdc): fix unstable s3 test
  tests/integration_tests/consistent_replicate_gbk/run.sh
  tests/integration_tests/consistent_replicate_nfs/run.sh
  tests/integration_tests/consistent_replicate_s3/run.sh
  tests/integration_tests/consistent_replicate_schedulerv3/run.sh
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#6219 sink (ticdc): Fix a data race in black hole sink.
  cdc/sink/black_hole.go
  cdc/sink/black_hole_test.go
  cdc/sink/metrics/statistics.go
Labels: status/LGT2, status/can-merge, size/L, release-note, needs-cherry-pick-release-6.1

#6217 syncer(dm): batch processing error when too many tables
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
  dm/syncer/checkpoint_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#6207 cdc: flush meta correctly when flush log
  cdc/processor/processor.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/writer/blackhole_writer.go
  cdc/redo/writer/mock_RedoLogWriter.go
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#6232 migration(ticdc): fix backup key issue
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/migrate/migrate.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#6215 filter (ticdc): add dml expression filter
  cdc/model/mounter.go
  errors.toml
  pkg/config/config_test_data.go
  pkg/config/filter.go
  pkg/errors/cdc_errors.go
  pkg/filter/expr_filter.go
  pkg/filter/expr_filter_bench_test.go
  pkg/filter/expr_filter_test.go
  pkg/filter/filter_test_helper.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#6223 chaos(engine): use multiple worker nodes in kind cluster
  .github/workflows/dataflow_engine_chaos.yaml
  engine/chaos/manifests/kind-cluster.yaml
Labels: status/ptal, status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, area/engine

#6231 scheduler(ticdc): fix panic when drain an imbalanced cluster
  cdc/scheduler/internal/v3/scheduler_drain_capture.go
  cdc/scheduler/internal/v3/scheduler_drain_capture_test.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#6228 pkg/causality: fix race caused by TestNodeFree
  pkg/causality/internal/node_test.go
Labels: component/test, status/LGT2, status/can-merge, size/XS, release-note-none, type/enhancement, area/ticdc

#6250 chaos(engine): add a delay after chaos test fails
  .github/workflows/dataflow_engine_chaos.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#6246 fake(engine): fix worker stucks when creating etcd watch chan
  engine/framework/fake/fake_worker.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#6264 *(engine): cleanup unused code and update outdated docs
  Makefile
  engine/README.md
  engine/ansible/README.md
  engine/ansible/deploy.yml
  engine/ansible/destroy.yml
  engine/ansible/group_vars/all
  engine/ansible/hosts
  engine/ansible/roles/common/files/README.md
  engine/ansible/roles/common/tasks/main.yml
  engine/ansible/roles/executor/tasks/main.yml
  engine/ansible/roles/executor/tasks/start.yml
  engine/ansible/roles/executor/tasks/stop.yml
  engine/ansible/roles/executor/templates/start.sh.j2
  engine/ansible/roles/executor/templates/stop.sh.j2
  engine/ansible/roles/master/tasks/main.yml
  engine/ansible/roles/master/tasks/start.yml
  engine/ansible/roles/master/tasks/stop.yml
  engine/ansible/roles/master/templates/etcd.yml.j2
  engine/ansible/roles/master/templates/start.sh.j2
  engine/ansible/roles/master/templates/stop.sh.j2
  engine/ansible/roles/metrics/tasks/main.yml
  engine/ansible/roles/metrics/tasks/start.yml
  engine/ansible/roles/metrics/tasks/stop.yml
  engine/ansible/roles/metrics/templates/prometheus.yml.j2
  engine/ansible/start.yml
  engine/ansible/stop.yml
  engine/pkg/metadata/kv.go
  engine/pkg/metadata/kv_etcd.go
  engine/pkg/metadata/kv_mock.go
  engine/pkg/metadata/main_test.go
  engine/test/context.go
  engine/test/util_test.go
  engine/tools/Makefile
  engine/tools/check_tidy.sh
  engine/tools/go.mod
  engine/tools/go.sum
  engine/tools/tools.go
  scripts/generate-engine-proto.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#6258 chaos(engine): fix business metastore name in chaos test
  .github/workflows/dataflow_engine_chaos.yaml
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/engine

#6252 schema(cdc): remove useless cas in AdvanceResolvedTs
  cdc/entry/schema_storage.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#6260 test(engine): add unit tests for meta
  engine/pkg/meta/client_test.go
  engine/pkg/meta/connection_test.go
  engine/pkg/meta/internal/etcdkv/connection_test.go
  engine/pkg/meta/internal/registry_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#6265 api(cdc): drain capture return 503 if not all captures initialized
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/owner/changefeed_test.go
  cdc/owner/owner.go
  cdc/scheduler/internal/scheduler.go
  cdc/scheduler/internal/v2/schedule_dispatcher.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_bench_test.go
  cdc/scheduler/internal/v3/coordinator_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#6253 puller(cdc): refactor the puller
  cdc/model/changefeed.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_puller.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/processor.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/regionspan/span.go
Labels: component/puller, status/LGT2, status/can-merge, size/XXL, release-note-none, type/enhancement, area/ticdc

#6203 config(ticdc): enable scheduler v3 by default
  .gitignore
  cdc/capture/capture.go
  cdc/capture/capture_test.go
  cdc/owner/changefeed.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/info_provider.go
  cdc/scheduler/internal/v3/agent.go
  cdc/scheduler/internal/v3/capture_manager.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/replication_manager.go
  cdc/scheduler/internal/v3/replication_set.go
  cdc/scheduler/internal/v3/scheduler_balance.go
  cdc/scheduler/internal/v3/scheduler_basic.go
  cdc/scheduler/internal/v3/scheduler_drain_capture.go
  cdc/scheduler/internal/v3/scheduler_manager.go
  cdc/scheduler/internal/v3/scheduler_move_table.go
  cdc/scheduler/internal/v3/scheduler_rebalance.go
  cdc/scheduler/internal/v3/table.go
  cdc/scheduler/internal/v3/transport.go
  cdc/scheduler/rexport.go
  deployments/ticdc/docker/integration-test.Dockerfile
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  tests/integration_tests/_utils/cleanup_process
  tests/integration_tests/_utils/kill_cdc_pid
  tests/integration_tests/availability/owner.sh
  tests/integration_tests/capture_suicide_while_balance_table/run.sh
  tests/integration_tests/cdc_server_tips/run.sh
  tests/integration_tests/changefeed_auto_stop/run.sh
  tests/integration_tests/changefeed_reconstruct/run.sh
  tests/integration_tests/consistent_replicate_schedulerv3/conf/changefeed.toml
  tests/integration_tests/consistent_replicate_schedulerv3/conf/diff_config.toml
  tests/integration_tests/consistent_replicate_schedulerv3/conf/server.toml
  tests/integration_tests/consistent_replicate_schedulerv3/conf/workload
  tests/integration_tests/consistent_replicate_schedulerv3/run.sh
  tests/integration_tests/http_api/run.sh
  tests/integration_tests/kill_owner_with_ddl/run.sh
Labels: component/scheduler, component/configuration, status/LGT2, status/can-merge, size/XL, release-note, area/ticdc

#6243 cdc: change redo meta resolved timestamp correctly
  cdc/processor/pipeline/sink.go
  cdc/redo/common/redo.go
  cdc/redo/common/redo_gen.go
  cdc/redo/common/redo_gen_test.go
  cdc/redo/common/redo_test.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/reader/reader.go
  cdc/redo/reader/reader_test.go
  cdc/redo/writer/blackhole_writer.go
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
  tests/integration_tests/consistent_replicate_gbk/run.sh
  tests/integration_tests/consistent_replicate_nfs/run.sh
  tests/integration_tests/consistent_replicate_s3/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#6276 dm(validator): hide source flags
  dm/dm/ctl/master/start_stop_validation.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#6213 worker(dm): fix Server Start/Close race
  dm/_utils/terror_gen/errors_release.txt
  dm/dm/worker/server.go
  dm/errors.toml
  dm/pkg/terror/error_list.go
  dm/tests/import_goroutine_leak/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#6256 tests(engine): add deployments and integration tests
  .github/workflows/check_and_build.yaml
  .github/workflows/dataflow_engine_e2e.yaml
  Makefile
  engine/README.md
  engine/deployments/docker-compose/1m1e.yaml
  engine/deployments/docker-compose/1m3e.yaml
  engine/deployments/docker-compose/1meta.yaml
  engine/deployments/docker-compose/1prometheus.yaml
  engine/deployments/docker-compose/3m3e.yaml
  engine/deployments/docker-compose/config/alertmanager.yml
  engine/deployments/docker-compose/config/demo.json
  engine/deployments/docker-compose/config/etcd.yml
  engine/deployments/docker-compose/config/executor.toml
  engine/deployments/docker-compose/config/fake_job.json
  engine/deployments/docker-compose/config/master.toml
  engine/deployments/docker-compose/config/mysql.cnf
  engine/deployments/docker-compose/config/mysql_meta.cnf
  engine/deployments/docker-compose/config/prometheus.yml
  engine/deployments/docker-compose/demo.yaml
  engine/deployments/docker-compose/dm_databases.yaml
  engine/deployments/docker/Dockerfile
  engine/deployments/docker/dev.Dockerfile
  engine/deployments/run-engine.sh
  engine/sample/README.md
  engine/sample/build_image_from_local.sh
  engine/sample/deploy.sh
  engine/sample/prepare.sh
  engine/sample/stop.sh
  engine/test/e2e/e2e_node_chaos_test.go
  engine/test/integration_tests/README.md
  engine/test/integration_tests/dm_basic/run.sh
  engine/test/integration_tests/e2e_basic/run.sh
  engine/test/integration_tests/e2e_node_failure/run.sh
  engine/test/integration_tests/e2e_worker_error/run.sh
  engine/test/integration_tests/run.sh
  engine/test/utils/run_engine.sh
  engine/test/utils/start_engine_cluster
  engine/test/utils/stop_engine_cluster
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#6271 labels(engine): implement pkg/label
  pkg/label/label.go
  pkg/label/label_test.go
  pkg/label/selector.go
  pkg/label/selector_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, type/enhancement, area/engine

#6285 test(ticdc): refine test case data col type
  cdc/sink/mq/codec/canal_encoder_test.go
  cdc/sink/mq/codec/canal_json_encoder_test.go
  cdc/sink/mq/codec/canal_test_util.go
  cdc/sink/mq/codec/craft_encoder_test.go
  cdc/sink/mq/codec/maxwell_encoder_test.go
  cdc/sink/mq/codec/open_protocol_encoder_test.go
  cdc/sink/mq/mq_flush_worker_test.go
  cdc/sink/mq/mq_test.go
Labels: component/test, status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none, area/ticdc

#6209 client(engine): Refactor the executor client
  engine/enginepb/mock/broker_mock.go
  engine/enginepb/mock/executor_mock.go
  engine/pkg/client/broker_service.go
  engine/pkg/client/broker_service_test.go
  engine/pkg/client/client_mock.go
  engine/pkg/client/errors.go
  engine/pkg/client/executor_client.go
  engine/pkg/client/executor_client_test.go
  engine/pkg/client/executor_group.go
  engine/pkg/client/executor_group_test.go
  engine/pkg/client/executor_service.go
  engine/pkg/client/executor_service_test.go
  engine/pkg/client/internal/call.go
  engine/pkg/client/internal/call_test.go
  engine/pkg/client/test_util.go
  engine/pkg/rpcerror/grpc.go
  scripts/generate-engine-mock.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, type/enhancement, area/engine

#6283 cli(ticdc): Cleanup service GC safe point correctly
  cdc/api/v2/api_helpers.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/owner/changefeed.go
  cdc/owner/feed_state_manager.go
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/txnutil/gc/gc_service.go
  pkg/txnutil/gc/gc_service_test.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/L, needs-cherry-pick-release-5.1, release-note-none, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#5973 syncer(dm): new way to implement handle-error
  dm/dm/worker/subtask.go
  dm/pkg/binlog/position.go
  dm/pkg/conn/mockdb.go
  dm/syncer/binlogstream/stream_modifier.go
  dm/syncer/binlogstream/stream_modifier_test.go
  dm/syncer/binlogstream/streamer_controller.go
  dm/syncer/binlogstream/streamer_controller_test.go
  dm/syncer/data_validator.go
  dm/syncer/ddl.go
  dm/syncer/err-operator/operator.go
  dm/syncer/err-operator/operator_test.go
  dm/syncer/handle_error.go
  dm/syncer/handle_error_test.go
  dm/syncer/syncer.go
  dm/tests/full_mode/run.sh
  dm/tests/handle_error/run.sh
  engine/executor/dm/unitholder_test.go
Labels: status/LGT2, size/XXL, do-not-merge/hold, release-note-none, area/dm

#6312 apiV2 (ticdc): fix update changefeed return info
  cdc/api/v2/changefeed.go
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, component/cli, release-note-none

#6287 server(ticdc): add some reserved cluster id
  pkg/config/server_config.go
  pkg/config/server_config_test.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#6310 error (ticdc): add changefeed not retry error
  cdc/model/changefeed.go
  cdc/model/errors.go
  cdc/model/errors_test.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/errors/helper.go
  pkg/errors/helper_test.go
  pkg/txnutil/gc/gc_manager_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, type/enhancement, area/ticdc

#6307 syncer(dm): merge feature branch
  dm/dm/worker/subtask.go
  dm/pkg/binlog/position.go
  dm/pkg/conn/mockdb.go
  dm/syncer/binlogstream/stream_modifier.go
  dm/syncer/binlogstream/stream_modifier_test.go
  dm/syncer/binlogstream/streamer_controller.go
  dm/syncer/binlogstream/streamer_controller_test.go
  dm/syncer/data_validator.go
  dm/syncer/ddl.go
  dm/syncer/err-operator/operator.go
  dm/syncer/err-operator/operator_test.go
  dm/syncer/handle_error.go
  dm/syncer/handle_error_test.go
  dm/syncer/syncer.go
  dm/tests/handle_error/run.sh
  engine/executor/dm/unitholder_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#6313 cdc: flush redo meta in owner instead of processor
  cdc/owner/changefeed.go
  cdc/processor/processor.go
  cdc/redo/common/redo.go
  cdc/redo/common/redo_gen.go
  cdc/redo/common/redo_gen_test.go
  cdc/redo/common/redo_test.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/reader/reader.go
  cdc/redo/reader/reader_test.go
  cdc/redo/writer/blackhole_writer.go
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
  tests/integration_tests/consistent_replicate_gbk/run.sh
  tests/integration_tests/consistent_replicate_nfs/run.sh
  tests/integration_tests/consistent_replicate_s3/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#6314 chore: io/ioutil change to package io and os
  cdc/redo/reader/file.go
  cdc/redo/reader/reader.go
  cdc/redo/writer/file.go
  cdc/redo/writer/file_test.go
  cdc/sorter/unified/file_backend_test.go
  cmd/cdc/hack/dbus_linux.go
  dm/pkg/schema/tracker.go
  engine/executor/config_test.go
  engine/executor/server_test.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/pkg/externalresource/broker/file_manager.go
  engine/pkg/externalresource/broker/local_broker.go
  engine/pkg/meta/internal/etcdkv/mock.go
  engine/servermaster/server_test.go
  engine/test/e2e/e2e_dm_test.go
  engine/test/e2e/e2e_test.go
  pkg/api/internal/rest/request.go
  pkg/api/internal/rest/request_test.go
  pkg/logutil/log_test.go
  pkg/tcpserver/tcp_server_test.go
  tests/integration_tests/move_table/main.go
Labels: status/LGT2, status/can-merge, size/L, contribution, release-note

#6320 cdc: ignore redo log meta regress for restarting
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-6.1

#6248 db(dm): use `net.JoinHostPort` to generate host-port part of URI
  cdc/entry/schema_storage_test.go
  cdc/entry/schema_test_helper.go
  cdc/redo/writer/file_test.go
  dm/dm/master/openapi_view.go
  dm/pkg/conn/basedb.go
  dm/pkg/parser/common.go
  dm/pkg/schema/tracker.go
  dm/pkg/utils/time.go
  dm/tests/s3_dumpling_lighting/run.sh
  go.mod
  go.sum
  pkg/filter/filter_test_helper.go
Labels: status/LGT2, status/can-merge, size/L, release-note, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#6026 filter(cdc): support multi-schema change DDL action
  cdc/sink/mq/codec/canal_entry.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#6316 test(dm): fix unstable test for two concurrent sources
  dm/tests/shardddl2/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1

#6325 capture(cdc): adjust the rate limiter for campaign the owner.
  cdc/capture/capture.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#6332 processor(cdc): remove useless state change in the sink node
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#6344 sinkv2(ticdc): make event sink close waiting for all callbacks be called
  cdc/model/sink.go
  cdc/processor/pipeline/table.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/mysql_worker.go
  cdc/sink/mysql/mysql_worker_test.go
  cdc/sinkv2/tablesink/event_table_sink.go
  cdc/sinkv2/tablesink/event_table_sink_test.go
  cdc/sinkv2/tablesink/progress_tracker.go
  cdc/sinkv2/tablesink/progress_tracker_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#6359 scheduler(ticdc): add changefeed to logs
  cdc/processor/pipeline/sorter.go
  cdc/scheduler/internal/v3/agent.go
  cdc/scheduler/internal/v3/agent_bench_test.go
  cdc/scheduler/internal/v3/agent_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_bench_test.go
  cdc/scheduler/internal/v3/replication_manager.go
  cdc/scheduler/internal/v3/replication_manager_test.go
  cdc/scheduler/internal/v3/replication_set.go
  cdc/scheduler/internal/v3/replication_set_test.go
  cdc/scheduler/internal/v3/scheduler_balance.go
  cdc/scheduler/internal/v3/scheduler_basic.go
  cdc/scheduler/internal/v3/scheduler_basic_test.go
  cdc/scheduler/internal/v3/scheduler_drain_capture.go
  cdc/scheduler/internal/v3/scheduler_drain_capture_test.go
  cdc/scheduler/internal/v3/scheduler_manager.go
  cdc/scheduler/internal/v3/scheduler_move_table.go
  cdc/scheduler/internal/v3/scheduler_move_table_test.go
  cdc/scheduler/internal/v3/scheduler_rebalance.go
  cdc/scheduler/internal/v3/scheduler_rebalance_test.go
  cdc/scheduler/internal/v3/table.go
  cdc/scheduler/internal/v3/table_test.go
Labels: status/LGT1, status/can-merge, size/XL, component/metrics-logging, require-LGT1, release-note-none, area/ticdc

#6284 capture(cdc): do not pass context to the etcd client to prevent etcd operation does not take effects
  cdc/capture/capture.go
  cdc/capture/capture_test.go
  cdc/owner/owner.go
  cdc/scheduler/internal/v3/capture_manager.go
  cdc/scheduler/internal/v3/capture_manager_test.go
  cdc/server.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, type/enhancement, area/ticdc

#6323 server(engine): log server config when it starts
  engine/executor/config.go
  engine/executor/config_test.go
  engine/executor/server.go
  engine/servermaster/config.go
  engine/servermaster/server.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#6358 server(cdc): introduce server package and add the interface
  cdc/server/metrics.go
  cdc/server/metrics_server.go
  cdc/server/server.go
  cdc/server/server_test.go
  pkg/cmd/server/server.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#6361 config (ticdc): Fix sink protocol can no specify by config file.
  pkg/config/sink.go
  pkg/config/sink_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#6349 syncer(dm): handle `;` in SQL comment when load table structure
  dm/syncer/syncer.go
  dm/tests/downstream_more_column/data/db1.increment.sql
  dm/tests/downstream_more_column/data/db1.prepare.sql
  dm/tests/downstream_more_column/run.sh
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#6366 redo(ticdc): handle error correctly in redo manager
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/writer/blackhole_writer.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.1

#6385 puller(ticdc): hotfix for 5.4.1- reduce context switch for stateful events
  cdc/kv/client.go
  cdc/kv/metrics.go
  cdc/kv/region_worker.go
  pkg/workerpool/pool.go
  pkg/workerpool/pool_impl.go
Labels: status/LGT2, status/can-merge, size/XL, cherry-pick-approved, release-note-none

#6382 chore(engine): remove unused repo configuration
  engine/.codecov.yml
  engine/.gitignore
  engine/.golangci.yml
Labels: status/ptal, status/LGT1, status/can-merge, size/L, require-LGT1, release-note-none, area/engine

#6390 ddl_sink (ticdc): fix ddl sink nil point panic
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_sink.go
  tests/integration_tests/syncpoint/run.sh
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#6306 master(engine): add log allow list for some rpc methods
  engine/pkg/externalresource/integration_test/mock_cluster.go
  engine/pkg/externalresource/manager/service_test.go
  engine/pkg/rpcutil/server.go
  engine/pkg/rpcutil/server_test.go
  engine/servermaster/campaign_test.go
  engine/servermaster/member_test.go
  engine/servermaster/server.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#6363 redo(ticdc): Pre-create redolog dir before file allocation
  cdc/redo/writer/file.go
  cdc/redo/writer/writer.go
  pkg/fsutil/file_allocator_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.1

#5491 cdc: make cdc support concurrent ddl
  cdc/entry/mounter.go
  cdc/entry/schema/snapshot.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/model/owner.go
  cdc/owner/schema.go
  cdc/processor/processor.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/regionspan/span.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#6295 sink(ticdc): implement txn sink and backend interface
  cdc/sinkv2/eventsink/txn/backend.go
  cdc/sinkv2/eventsink/txn/event.go
  cdc/sinkv2/eventsink/txn/main_test.go
  cdc/sinkv2/eventsink/txn/txn_sink.go
  cdc/sinkv2/eventsink/txn/txn_sink_test.go
  cdc/sinkv2/eventsink/txn/worker.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#6392 chaos(engine): fix metastore selector in k8s
  engine/chaos/cases/config.go
  engine/chaos/manifests/conf/server-master.toml
  engine/chaos/manifests/metastore.yaml
Labels: status/ptal, status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/engine

#6410 kv(cdc): set enableOldValue correctly
  cdc/kv/region_worker.go
Labels: status/LGT2, status/can-merge, size/S, cherry-pick-approved, release-note-none

#6351 owner(ticdc): Fix an unexpected stop problem for changefeed backoff
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.2

#6403 sink(ticdc): precheck before split the update event
  cdc/entry/mounter.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-4.0, needs-cherry-pick-release-5.0, size/M, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#6365 chaos(engine): fix missing checkout PR in manually workflow
  .github/workflows/dataflow_engine_chaos.yaml
Labels: status/ptal, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/engine

#6404 test(dm): fix some unstable test
  dm/tests/gtid/conf/source1.yaml
  dm/tests/gtid/conf/source2.yaml
  dm/tests/shardddl_optimistic/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#6424 tests(ticdc): use python3 to run http_api test to fix failed integration_test
  tests/integration_tests/http_api/run.sh
Labels: status/LGT1, status/can-merge, size/S, cherry-pick-approved, require-LGT1, release-note-none

#6374 cli (ticdc): fix query changefeed does not contain config info and mask sink uri.
  cdc/api/v1/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_changefeed_query_test.go
  pkg/util/uri.go
  pkg/util/uri_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note

#6216 engine(DM): implement dm openapi
  engine/client/master_client.go
  engine/client/mock_clients.go
  engine/enginepb/datarw.pb.go
  engine/enginepb/error.pb.go
  engine/enginepb/errorv2.pb.go
  engine/enginepb/executor.pb.go
  engine/enginepb/master.pb.go
  engine/enginepb/metastore.pb.go
  engine/enginepb/projects.pb.go
  engine/enginepb/resources.pb.go
  engine/enginepb/test.pb.go
  engine/jobmaster/dm/api.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/openapi.go
  engine/jobmaster/dm/openapi/gen.server.go
  engine/jobmaster/dm/openapi/gen.types.go
  engine/jobmaster/dm/openapi/spec/dm.yaml
  engine/jobmaster/dm/openapi/spec/server-gen-cfg.yaml
  engine/jobmaster/dm/openapi/spec/types-gen-cfg.yaml
  engine/jobmaster/dm/openapi_test.go
  engine/proto/master.proto
  engine/servermaster/jobmanager.go
  engine/servermaster/jobmanager_test.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
  engine/test/e2e/e2e_dm_test.go
  engine/test/mock/grpc.go
  tests/utils/many_sorters_test/many_sorters.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#6431 ddl_sink (ticdc): fix ddl sink nil point panic (#6390)
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_sink.go
  tests/integration_tests/syncpoint/run.sh
Labels: status/LGT1, status/can-merge, size/M, cherry-pick-approved, require-LGT1, release-note

#6440 sink(cdc): reset the txn length counter while iterating tables
  cdc/sink/mysql/txn_cache.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#6278 sink(ticdc): translate INSERT automatically when mysql sink disables safe mode
  cdc/model/sink.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/txns_heap.go
  dm/pkg/retry/errors.go
  tests/integration_tests/sink_retry/run.sh
Labels: component/sink, subject/performance, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#6438 cli(ticdc): remove dead code
  pkg/cmd/cli/cli_capture.go
  pkg/cmd/cli/cli_capture_test.go
  pkg/cmd/cli/cli_changefeed.go
  pkg/cmd/cli/cli_processor.go
  pkg/version/check.go
  pkg/version/check_test.go
  tests/integration_tests/availability/capture.sh
  tests/integration_tests/availability/owner.sh
  tests/integration_tests/availability/processor.sh
  tests/integration_tests/http_api/run.sh
Labels: status/LGT2, status/can-merge, size/XL, component/cli, release-note-none, area/ticdc

#6411 capture(cdc): refactor capture run to prevent call close the capture multiple times.
  cdc/capture/capture.go
  pkg/etcd/client.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#6452 feat(meta): enlarge the meta length
  engine/framework/model/master.go
  engine/framework/model/status.go
  engine/pkg/externalresource/resourcemeta/model/model.go
  engine/pkg/orm/client_test.go
  engine/pkg/orm/model/project.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#6329 syncer(dm): Fix DM incorrectly skips tables with foreign keys
  dm/pkg/parser/common.go
  dm/pkg/parser/common_test.go
  dm/tests/dm_syncer/data/db1.prepare.sql
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm

#6455 engine: refine the address command line argument name
  engine/README.md
  engine/chaos/cases/case_fake_job.go
  engine/chaos/cases/config.go
  engine/chaos/manifests/executor.yaml
  engine/chaos/manifests/server-master.yaml
  engine/client/client_test.go
  engine/deployments/docker-compose/1m1e.yaml
  engine/deployments/docker-compose/1m3e.yaml
  engine/deployments/docker-compose/3m3e.yaml
  engine/deployments/docker-compose/config/executor.toml
  engine/deployments/docker-compose/config/master.toml
  engine/executor/config.go
  engine/executor/config_test.go
  engine/executor/server.go
  engine/executor/server_test.go
  engine/pkg/cmd/executor/executor.go
  engine/pkg/cmd/master/master.go
  engine/servermaster/config.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
  engine/test/heartbeat_test.go
  engine/test/util_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note, type/enhancement, area/engine

#6338 ddl: move the code out of syncer
  dm/syncer/optimist.go
  dm/syncer/shardddl.go
  dm/syncer/syncer.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#6340 syncer(dm): move location recorder to binlogstream package
  dm/pkg/binlog/event/common.go
  dm/pkg/binlog/event/dml.go
  dm/syncer/binlog_locations_test.go
  dm/syncer/binlogstream/binlog_locations.go
  dm/syncer/binlogstream/binlog_locations_test.go
  dm/syncer/binlogstream/streamer_controller.go
  dm/syncer/syncer.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm

#6449 sinkv2(ticdc): make table sink close cancellable
  cdc/sinkv2/tablesink/progress_tracker.go
  cdc/sinkv2/tablesink/progress_tracker_test.go
  cdc/sinkv2/tablesink/table_sink.go
  cdc/sinkv2/tablesink/table_sink_impl.go
  cdc/sinkv2/tablesink/table_sink_impl_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#6457 cli (ticdc): fix changefeed list does not contains failed changefeed
  pkg/cmd/cli/cli_changefeed_list.go
  pkg/cmd/cli/cli_changefeed_list_test.go
Labels: status/LGT2, status/can-merge, size/M, component/cli, release-note-none, needs-cherry-pick-release-6.2

#6391 rfc(dm): add rfc for continuous data validation
  dm/docs/RFCS/20220721_continuous_data_validation.md
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/dm

#6462 sink(ticdc): add start ts to mysql log and refine get tso
  cdc/processor/pipeline/sorter.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, component/metrics-logging, release-note

#6412 sinkv2(ticdc): impl kafka producer
  cdc/sinkv2/eventsink/mq/kafka_sink.go
  cdc/sinkv2/eventsink/mq/mq_sink.go
  cdc/sinkv2/eventsink/mq/mq_sink_test.go
  cdc/sinkv2/eventsink/mq/producer/kafka_mock_producer.go
  cdc/sinkv2/eventsink/mq/producer/kafka_producer.go
  cdc/sinkv2/eventsink/mq/producer/kafka_producer_test.go
  cdc/sinkv2/eventsink/mq/producer/main_test.go
  cdc/sinkv2/eventsink/mq/producer/producer.go
  cdc/sinkv2/eventsink/mq/worker.go
  cdc/sinkv2/eventsink/mq/worker_test.go
  errors.toml
  pkg/errors/cdc_errors.go
Labels: component/sink, status/can-merge, status/LGT3, require-LGT3, size/XXL, release-note-none, area/ticdc

#6469 owner(ticdc): fix nil scheduler panic
  cdc/owner/owner.go
  cdc/owner/owner_test.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc, needs-cherry-pick-release-6.2

#6473 typo(ticdc): Fix spelling of 'true'
  pkg/actor/system.go
  pkg/util/failpoint.go
  tests/mq_protocol_tests/main.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#6461 owner(ticdc): fix protocol incompatibility in sink scheme during owner bootstrap
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/processor/processor_test.go
  errors.toml
  pkg/config/sink.go
  pkg/config/sink_test.go
  pkg/errors/cdc_errors.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#6478 scheduler(ticdc): transit to Absent when captures are empty
  cdc/scheduler/internal/v3/replication_set.go
  cdc/scheduler/internal/v3/replication_set_test.go
Labels: component/scheduler, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc, needs-cherry-pick-release-6.2

#6476 migrator(ticdc): fix update changefeed failed bug
  pkg/api/internal/rest/request.go
  pkg/migrate/migrate.go
  pkg/migrate/migrate_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.2

#6471 engine(dm): replace log with embedded logger
  engine/executor/dm/worker.go
  engine/executor/dm/worker_test.go
  engine/framework/logutil/util.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/checkpoint/agent.go
  engine/jobmaster/dm/checkpoint/agent_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/openapi_test.go
  engine/jobmaster/dm/task_manager.go
  engine/jobmaster/dm/task_manager_test.go
  engine/jobmaster/dm/worker_manager.go
  engine/jobmaster/dm/worker_manager_test.go
  engine/pkg/dm/message_agent.go
  engine/pkg/dm/message_agent_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/engine

#6466 orm(engine): Implement orm log
  engine/pkg/meta/internal/sqlkv/sql_impl.go
  engine/pkg/orm/client.go
  engine/pkg/orm/log.go
  engine/pkg/orm/log_test.go
  engine/pkg/orm/util.go
  pkg/logutil/log.go
  pkg/logutil/log_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/engine

#6495 build: merge gen-proto scripts into one
  Makefile
  dm/generate-dm.sh
  engine/enginepb/datarw.pb.go
  engine/enginepb/error.pb.go
  engine/enginepb/errorv2.pb.go
  engine/enginepb/executor.pb.go
  engine/enginepb/master.pb.go
  engine/enginepb/metastore.pb.go
  engine/enginepb/projects.pb.go
  engine/enginepb/resources.pb.go
  engine/enginepb/test.pb.go
  scripts/download-protoc.sh
  scripts/generate-engine-proto.sh
  scripts/generate-protobuf.sh
  tools/check/go.mod
  tools/check/go.sum
  tools/check/tools.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/dm, area/engine

#6389 engine(servermaster): remove embedded etcd
  .github/workflows/dataflow_engine_e2e.yaml
  engine/chaos/cases/case_fake_job.go
  engine/chaos/manifests/conf/server-master.toml
  engine/chaos/manifests/server-master.yaml
  engine/client/client_test.go
  engine/deployments/docker-compose/1m1e.yaml
  engine/deployments/docker-compose/1m3e.yaml
  engine/deployments/docker-compose/1meta.yaml
  engine/deployments/docker-compose/3m3e.yaml
  engine/deployments/docker-compose/config/master.toml
  engine/executor/metrics.go
  engine/framework/metadata/metadata.go
  engine/pkg/adapter/keyadapter.go
  engine/pkg/cmd/master/master.go
  engine/pkg/etcdclient/client.go
  engine/pkg/etcdutil/join.go
  engine/pkg/etcdutil/join_test.go
  engine/pkg/etcdutil/service.go
  engine/pkg/rpcutil/client.go
  engine/pkg/rpcutil/server.go
  engine/pkg/serverutil/discovery_keepalive.go
  engine/pkg/srvdiscovery/runner.go
  engine/servermaster/campaign.go
  engine/servermaster/campaign_test.go
  engine/servermaster/config.go
  engine/servermaster/etcd.go
  engine/servermaster/etcd_test.go
  engine/servermaster/member.go
  engine/servermaster/member_test.go
  engine/servermaster/metrics.go
  engine/servermaster/server.go
  engine/servermaster/server_test.go
  engine/test/e2e/e2e_node_chaos_test.go
  engine/test/e2e/e2e_test_cli.go
  engine/test/e2e/e2e_worker_exit_test.go
  engine/test/e2e/tispace.json
  engine/test/heartbeat_test.go
  engine/test/util_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#6407 engine(DM): adjust target db when init job
  dm/master/openapi_controller.go
  dm/master/openapi_view.go
  dm/master/server.go
  dm/master/server_test.go
  dm/pkg/conn/mockdb.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/test/e2e/e2e_dm_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/engine

#6498 test(dm): fix unstable tests
  dm/tests/shardddl1_1/run.sh
  dm/tests/sharding/run.sh
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/dm, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#6500 actions(dm): fix default MySQL image changed to CentOS based
  dm/tests/upstream_switch/Dockerfile
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#6512 chaos(engine): fix etcd-endpoints for servermaster
  engine/chaos/manifests/conf/server-master.toml
  engine/chaos/manifests/metastore.yaml
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#6499 sinkv2(ticdc): impl kafka ddl sink producer and add tests
  cdc/sinkv2/ddlsink/mq/ddlproducer/ddl_producer.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_mock_producer.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/main_test.go
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink_test.go
  cdc/sinkv2/eventsink/mq/dmlproducer/dml_producer.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_mock_producer.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer_test.go
  cdc/sinkv2/eventsink/mq/dmlproducer/main_test.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink_test.go
  cdc/sinkv2/eventsink/mq/worker.go
  cdc/sinkv2/eventsink/mq/worker_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#6507 pkg/version(ticdc): bump compatible versions
  pkg/version/check.go
Labels: status/LGT2, status/can-merge, size/S, cherry-pick-approved, release-note-none

#6517 test(dm): fix an unstable test and prepare to split tests
  dm/tests/others_integration_3.txt
  dm/tests/run.sh
  dm/tests/shardddl3_1/run.sh
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#6519 test(dm): wait data is replicated to fix unstable test
  dm/tests/gtid/run.sh
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1

#5185 checker(dm): check the number of connections before starting
  dm/checker/checker.go
  dm/config/checking_item.go
  dm/dumpling/dumpling.go
  dm/loader/loader.go
  dm/pkg/checker/conn_checker.go
  dm/pkg/checker/conn_checker_test.go
  dm/tests/dmctl_command/conf/dm-task3.yaml
  dm/tests/dmctl_command/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-2.0.5, needs-cherry-pick-release-2.0.6, needs-cherry-pick-release-2.0.7, needs-cherry-pick-release-6.0

#6513 sink(ticdc): warning on using pulsar sink
  cdc/model/changefeed.go
  cdc/sink/mq/mq.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/config/sink.go
Labels: component/sink, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc, needs-cherry-pick-release-6.2

#6503 cli(cdc): handle error correctly with wrong pd address but with a grpc service
  pkg/cmd/cli/cli_unsafe_reset.go
  pkg/cmd/factory/factory_impl.go
  pkg/cmd/factory/factory_impl_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note

#6534 test(dm): fix unstable test due to rely on sleep X seconds
  dm/tests/checkpoint_transaction/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#6210 owner(ticdc): do not campaign owner when liveness is stopping
  Makefile
  cdc/api/status/status.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/unsafe_test.go
  cdc/capture/capture.go
  cdc/capture/capture_test.go
  cdc/capture/election.go
  cdc/capture/mock/capture_mock.go
  cdc/owner/changefeed_test.go
  cdc/scheduler/internal/v2/processor_agent.go
  cdc/scheduler/internal/v3/agent.go
  cdc/scheduler/rexport.go
  cdc/server/server.go
  pkg/cmd/cli/cli_processor_query.go
  pkg/cmd/cli/cli_unsafe_reset.go
  pkg/cmd/factory/factory.go
  pkg/cmd/factory/factory_impl.go
  pkg/cmd/factory/mock/factory_mock.go
  pkg/context/context.go
  pkg/etcd/client_for_api.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/mock/etcd_client_mock.go
  pkg/etcd/testing.go
  pkg/migrate/migrate.go
  pkg/orchestrator/etcd_worker.go
  tests/integration_tests/move_table/main.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc, component/owner, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#6549 srvdiscovery(engine): disable etcd auto sync, add timeout to snapshot op
  engine/pkg/config/constants.go
  engine/pkg/srvdiscovery/etcd_impl.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/engine

#6454 version(cdc): allow version inconsistant since v6.3.0
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  pkg/context/context.go
  pkg/p2p/server.go
  pkg/p2p/server_test.go
  pkg/version/check.go
  pkg/version/check_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none
