Repository pingcap/tiflow, pull requests merged in 2023-01, with the labels that each got.

#8008 changefeed(ticdc): fix memory quota incompatible from 6.5.0
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/M, release-note, area/ticdc, needs-cherry-pick-release-6.5

#7996 sinkv2(cdc): fix some races of source manager
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sourcemanager/engine/factory/factory.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5

#8005 p2p(ticdc): use a larger max receive message size
  cdc/server/server.go
  engine/pkg/p2p/message_sender.go
  engine/pkg/p2p/server_integration_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/messages.go
  pkg/config/messages_test.go
  pkg/p2p/client.go
  pkg/p2p/client_connector.go
  pkg/p2p/client_test.go
  pkg/p2p/message_router_test.go
  pkg/p2p/mock_cluster.go
  pkg/p2p/server.go
  pkg/p2p/server_client_integration_test.go
  pkg/p2p/server_wrapper.go
  pkg/p2p/server_wrapper_test.go
Labels: type/bugfix, status/LGT2, status/can-merge, size/M, release-note, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8003 *(ticdc): reduce collect table stats frequency
  cdc/processor/processor.go
  cdc/scheduler/internal/table_executor.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_bench_test.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/member/capture_manager.go
  cdc/scheduler/internal/v3/member/capture_manager_test.go
  cdc/scheduler/schedulepb/table_schedule.pb.go
  cdc/scheduler/schedulepb/table_schedule.proto
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/scheduler_config.go
  pkg/config/server_config_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/ticdc

#7978 processor(ticdc): replace tableID with Span in sourcemanager and sinkmanager
  cdc/processor/pipeline/puller.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/mem_quota.go
  cdc/processor/sinkmanager/mem_quota_test.go
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sinkmanager/redo_cache_test.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_progress_heap.go
  cdc/processor/sinkmanager/table_progress_heap_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/processor/sinkmanager/tasks.go
  cdc/processor/sourcemanager/engine/engine.go
  cdc/processor/sourcemanager/engine/memory/event_sorter.go
  cdc/processor/sourcemanager/engine/memory/event_sorter_test.go
  cdc/processor/sourcemanager/engine/mock/engine_mock.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter_test.go
  cdc/processor/sourcemanager/manager.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/sinkv2/eventsink/mq/worker.go
  cdc/sinkv2/eventsink/mq/worker_test.go
  pkg/config/debug.go
  pkg/spanz/sync_map.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#7972 lightning(dm): coordinate multiple DMWorker
  dm/common/common.go
  dm/loader/lightning.go
  dm/loader/util.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server.go
  dm/pkg/ha/lightning_coordinate.go
  dm/pkg/ha/lightning_coordinate_test.go
  dm/tests/lightning_mode/run.sh
  dm/tests/many_tables/run.sh
  dm/tests/s3_dumpling_lightning/conf/dm-task.yaml
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#7523 ShardDDL(engine/dm): implement shard ddl in dm jobmaster
  dm/pkg/conn/basedb.go
  dm/pkg/conn/mockdb.go
  engine/jobmaster/dm/api.go
  engine/jobmaster/dm/checkpoint/agent.go
  engine/jobmaster/dm/checkpoint/agent_test.go
  engine/jobmaster/dm/ddl_coordinator.go
  engine/jobmaster/dm/ddl_coordinator_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/metadata/ddl.go
  engine/jobmaster/dm/metadata/ddl_test.go
  engine/jobmaster/dm/metadata/job.go
  engine/jobmaster/dm/metadata/metadata.go
  engine/pkg/adapter/keyadapter.go
  engine/pkg/dm/topic.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none, area/engine

#7980 api,config(ticdc): support update transaction-atomicity and protocol via config file
  cdc/api/v1/validator.go
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/changefeed.go
  errors.toml
  pkg/config/sink.go
  pkg/config/sink_test.go
  pkg/errors/cdc_errors.go
Labels: status/LGT2, status/can-merge, size/XL, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8010 scheduler(ticdc): optimize owner memory allocation
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/keyspan/reconciler.go
  cdc/scheduler/internal/v3/keyspan/reconciler_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager.go
  cdc/scheduler/internal/v3/scheduler/scheduler_move_table.go
  pkg/spanz/map.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#8030 sinkv2(ticdc): remove redundant nextToMount in MountedEventIter
  cdc/processor/sourcemanager/engine/mounted_iter.go
  cdc/processor/sourcemanager/engine/mounted_iter_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5

#8034 tests(engine): fix unstable unit test in jobmanager
  engine/servermaster/jobmanager_test.go
Labels: status/ptal, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/engine

#8029 puller(ticdc): fix frontier metrics label
  cdc/processor/pipeline/puller.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#8025 fix(ui): update pattern
  dm/ui/src/components/CreateOrUpdateTask/MigrateRule.tsx
Labels: status/LGT2, status/can-merge, size/XS, release-note

#8042 encoder(ticdc): do not close the output channel to prevent data race.
  cdc/sink/codec/encoder_group.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-6.5

#7857 mysql (ticdc): back port batch dml to release 6.1
  cdc/entry/mounter_test.go
  cdc/model/sink.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_params.go
  cdc/sink/mysql/mysql_params_test.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/mysql_worker.go
  cdc/sink/mysql/mysql_worker_test.go
  pkg/applier/redo_test.go
  pkg/sqlmodel/multivalue.go
  tests/integration_tests/_utils/run_kafka_consumer
  tests/integration_tests/batch_dml/conf/diff_config.toml
  tests/integration_tests/batch_dml/data/test.sql
  tests/integration_tests/batch_dml/data/test_finish.sql
  tests/integration_tests/batch_dml/data/test_v5.sql
  tests/integration_tests/batch_dml/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, cherry-pick-approved, release-note-none

#8020 apiv2(ticdc): delete changefeed
  cdc/api/v2/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  pkg/api/v1/changefeed.go
  pkg/api/v2/changefeed.go
  pkg/api/v2/mock/changefeed_mock.go
  pkg/api/v2/mock/tso_mock.go
  pkg/api/v2/mock/unsafe_mock.go
  pkg/cmd/cli/cli_changefeed_remove.go
  pkg/cmd/cli/cli_changefeed_remove_test.go
  scripts/generate-mock.sh
  tests/integration_tests/http_api_tls/run.sh
  tests/integration_tests/http_api_tls/util/test_case.py
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8058 tests(ticdc): gen multi rows update with generated column scenario
  pkg/sqlmodel/multirow_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#8026 apiv2(ticdc): pause changefeed
  cdc/api/v2/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  pkg/api/v1/changefeed.go
  pkg/api/v2/changefeed.go
  pkg/api/v2/mock/changefeed_mock.go
  pkg/cmd/cli/cli_changefeed_pause.go
  pkg/cmd/cli/cli_changefeed_pause_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8038 apiv2(ticdc): health api
  cdc/api/v2/api.go
  cdc/api/v2/health.go
  cdc/api/v2/health_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8036 apiv2(ticdc): status api
  cdc/api/v2/api.go
  cdc/api/v2/status.go
  cdc/api/v2/status_test.go
  pkg/api/v1/api_client.go
  pkg/api/v2/api_client.go
  pkg/api/v2/mock/status_mock.go
  pkg/api/v2/status.go
  pkg/cmd/cli/cli_capture_list_test.go
  pkg/cmd/factory/factory_impl.go
  pkg/cmd/factory/factory_impl_test.go
  scripts/generate-mock.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8052 mqsink(ticdc): add kafka client interface
  cdc/sink/mq/mq.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  cdc/sinkv2/ddlsink/factory/factory.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/ddl_producer.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_mock_producer.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink_test.go
  cdc/sinkv2/eventsink/factory/factory.go
  cdc/sinkv2/eventsink/factory/factory_test.go
  cdc/sinkv2/eventsink/mq/dmlproducer/dml_producer.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_mock_producer.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer_test.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink_test.go
  cdc/sinkv2/util/helper.go
  pkg/sink/kafka/client.go
  pkg/sink/kafka/client_mock_impl.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8049 processor,scheduler(ticdc): clean up unused method and metrics
  cdc/processor/metrics.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/agent.go
  cdc/scheduler/internal/table_executor.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  metrics/alertmanager/ticdc.rules.yml
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8054 ddl_puller(ticdc): fix flashback ddl error
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note

#8063 sink(ticdc): rename kafka config to options and move it to the pkg
  cdc/sink/mq/manager/kafka_manager.go
  cdc/sink/mq/manager/kafka_manager_test.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/producer/kafka/config_test.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer_test.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/util/helper.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/sarama.go
  pkg/sink/kafka/sarama_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8021 cdc: replace BtreeMap with HashMap in TiCDC
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/mem_quota.go
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/tablepb/table.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/keyspan/reconciler.go
  cdc/scheduler/internal/v3/keyspan/reconciler_test.go
  cdc/scheduler/internal/v3/keyspan/region_cache.go
  cdc/scheduler/internal/v3/member/capture_manager.go
  cdc/scheduler/internal/v3/member/capture_manager_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/scheduler/scheduler.go
  cdc/scheduler/internal/v3/scheduler/scheduler_balance.go
  cdc/scheduler/internal/v3/scheduler/scheduler_basic.go
  cdc/scheduler/internal/v3/scheduler/scheduler_basic_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_move_table.go
  cdc/scheduler/internal/v3/scheduler/scheduler_move_table_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_rebalance.go
  pkg/spanz/btree_map.go
  pkg/spanz/btree_map_test.go
  pkg/spanz/convert.go
  pkg/spanz/convert_test.go
  pkg/spanz/hash_map.go
  pkg/spanz/hash_map_test.go
  pkg/spanz/map_bench_test.go
  pkg/spanz/set.go
  pkg/spanz/sync_map.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#8072 sinkv2(ticdc): remove duplicate DDL statistics
  cdc/sinkv2/ddlsink/mysql/mysql_ddl_sink.go
Labels: component/sink, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#8059 disable batch update dmls
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
Labels: status/LGT2, status/can-merge, size/S, cherry-pick-approved, release-note

#8053 sink(ticdc): refactor kafka cluster admin client interface to hide sarama
  cdc/sink/mq/manager/kafka_manager.go
  cdc/sink/mq/manager/kafka_manager_test.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  cdc/sink/mq/producer/kafka/metrics.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer_test.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/metrics/mq/kafka/collector.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/cluster_admin_client_mock_impl.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8064 apiv2(ticdc): drain capture
  cdc/api/v2/api.go
  cdc/api/v2/capture.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8073 apiv2(ticdc): set log level
  cdc/api/v2/api.go
  cdc/api/v2/log.go
  cdc/api/v2/model.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8090 error,sink (ticdc): add mysql error black list
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_test.go
  pkg/errorutil/ignore.go
Labels: status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note-none

#8083 sink(ticdc): add knob to controll enable kafka sink v2 and add basic dependency scaffold
  go.mod
  go.sum
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  pkg/sink/kafka/v2/manual_balancer.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8070 scheduler(ticdc): split more evenly
  cdc/processor/processor.go
  cdc/scheduler/internal/v3/keyspan/reconciler.go
  cdc/scheduler/internal/v3/keyspan/reconciler_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#8077 sink(ticdc): Kafka client hide sarama config
  cdc/sink/mq/mq.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer_test.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  pkg/sink/kafka/client.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/sarama.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8067 apiv2(ticdc): resign owner
  cdc/api/v2/api.go
  cdc/api/v2/owner.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8099 config(ticdc): remove debug.enable-new-scheduler
  .gitignore
  cdc/server/server.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  tests/integration_tests/_utils/start_tidb_cluster_impl
  tests/integration_tests/_utils/start_tls_tidb_cluster_impl
  tests/integration_tests/_utils/stop_tidb_cluster
  tests/utils/cdc_state_checker/cdc_monitor.go
  tests/utils/cdc_state_checker/main.go
  tests/utils/cdc_state_checker/reactor.go
  tests/utils/cdc_state_checker/state.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#8094 metrics(ticdc): correct some grafana metric descriptions
  metrics/grafana/ticdc.json
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc

#8068 sinkv2(cdc): seperate redo and sink memory quota
  cdc/model/changefeed_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/mem_quota.go
  cdc/processor/sinkmanager/mem_quota_test.go
  cdc/processor/sinkmanager/metrics.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  metrics/grafana/ticdc.json
  pkg/config/config_test_data.go
  pkg/config/server_config.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.5

#8050 mysql(ticdc): add mysql backend performance metrics observer
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/metrics.go
  cdc/owner/owner_test.go
  cdc/server/metrics.go
  pkg/sink/observer/dummy.go
  pkg/sink/observer/metrics.go
  pkg/sink/observer/observer.go
  pkg/sink/observer/tidb.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#8105 sinkv2(ticdc): remove useless event ID in the table sink
  cdc/sinkv2/tablesink/table_sink_impl.go
  cdc/sinkv2/tablesink/table_sink_impl_test.go
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/ticdc

#8066 apiv2(ticdc): list captures
  cdc/api/v2/api.go
  cdc/api/v2/capture.go
  cdc/api/v2/model.go
  pkg/api/v1/api_client.go
  pkg/api/v2/api_client.go
  pkg/api/v2/capture.go
  pkg/api/v2/mock/capture_mock.go
  pkg/cmd/cli/cli_capture_list.go
  pkg/cmd/cli/cli_capture_list_test.go
  scripts/generate-mock.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8069 pkg(ticdc): add a faster raw string rendering version of GenUpdateSQL
  pkg/sqlmodel/multirow.go
  pkg/sqlmodel/multirow_bench_test.go
  pkg/sqlmodel/multirow_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#8100 config(ticdc): move region-per-span to changefeed config
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner/changefeed.go
  cdc/processor/manager.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/compat/compat.go
  cdc/scheduler/internal/v3/compat/compat_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/info_provider_test.go
  cdc/scheduler/internal/v3/keyspan/reconciler_test.go
  cdc/sink/validator.go
  cdc/sink/validator_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/scheduler_config.go
  pkg/config/server_config_test.go
  pkg/orchestrator/reactor_state_test.go
  tests/integration_tests/cli/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8075 redo(ticdc): use uuid in redo meta filename
  Makefile
  cdc/api/v2/model.go
  cdc/owner/changefeed_test.go
  cdc/redo/common/metric.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/reader/file.go
  cdc/redo/writer/file.go
  cdc/redo/writer/writer.go
  cdc/redo/writer/writer_test.go
  cdc/sinkv2/eventsink/txn/worker.go
  deployments/ticdc/docker/test.Dockerfile
  engine/pkg/externalresource/internal/s3/file_manager.go
  errors.toml
  metrics/grafana/ticdc.json
  pkg/config/consistent.go
  pkg/config/replica_config.go
  pkg/errors/cdc_errors.go
  pkg/redo/config.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8136 ticdc: workround for get source id error
  pkg/pdutil/utils.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#8101 kafka(ticdc): Hide async producer sarama
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer.go
  pkg/sink/kafka/client.go
  pkg/sink/kafka/client_mock_impl.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#7951 metrics (ticdc): add ticdc summary dashboard
  metrics/grafana/TiCDC-Monitor-Summary.json
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8133 processor(ticdc):remove deprecated table pipeline
  cdc/capture/capture.go
  cdc/processor/manager_test.go
  cdc/processor/metrics.go
  cdc/processor/pipeline/actor_node.go
  cdc/processor/pipeline/actor_node_context.go
  cdc/processor/pipeline/actor_node_context_test.go
  cdc/processor/pipeline/actor_node_test.go
  cdc/processor/pipeline/main_test.go
  cdc/processor/pipeline/metrics.go
  cdc/processor/pipeline/puller.go
  cdc/processor/pipeline/sink.go
  cdc/processor/pipeline/sink_test.go
  cdc/processor/pipeline/sorter.go
  cdc/processor/pipeline/sorter_test.go
  cdc/processor/pipeline/system/system.go
  cdc/processor/pipeline/system/system_test.go
  cdc/processor/pipeline/table_actor.go
  cdc/processor/pipeline/table_actor_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/tablepb/table.go
  cdc/server/server.go
  pkg/config/debug.go
  pkg/context/context.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8093 kafka(ticdc): a new kafka admin client implementation based on kafka-go
  cdc/sink/mq/manager/kafka_manager.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  cdc/sink/mq/producer/kafka/metrics.go
  cdc/sinkv2/metrics/mq/kafka/collector.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/cluster_admin_client_mock_impl.go
  pkg/sink/kafka/v2/admin.go
  pkg/sink/kafka/v2/admin_test.go
  pkg/sink/kafka/v2/client.go
  pkg/sink/kafka/v2/mock/client_mock.go
  scripts/generate-mock.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8120 apiv2(ticdc): implement the get processor
  cdc/api/v2/api.go
  cdc/api/v2/api_test.go
  cdc/api/v2/model.go
  cdc/api/v2/processor.go
  cdc/api/v2/processor_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
Labels: status/LGT2, status/can-merge, size/XL, release-note-none
