Repository pingcap/tiflow, pull requests merged in 2023-10, with the labels that each got.

#9828 scheduler (ticdc): does not return error when resolvedTs less than checkpoint
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/replication/replication_set_test.go
Labels: size/M, release-note, approved, lgtm

#9824 kafka(ticdc): bump sarama to v1.41.2
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer_test.go
  cmd/kafka-consumer/main.go
  go.mod
  go.sum
  pkg/leakutil/leak_helper.go
  pkg/logutil/log.go
  pkg/security/sasl.go
  pkg/sink/codec/common/message.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client_mock_impl.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/metrics_collector.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/oauth2_token_provider.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/sarama.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/kafka/sarama_factory_test.go
  pkg/sink/kafka/sarama_test.go
Labels: size/M, release-note, ok-to-test, approved, lgtm

#9832 config(ticdc): mask more security query parameter
  pkg/util/uri.go
  pkg/util/uri_test.go
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9833 scheduler (ticdc): does not return error when resolvedTs less than checkpoint
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/replication/replication_set_test.go
Labels: size/M, cherry-pick-approved, release-note, approved, lgtm

#9844 cdc: disable kv-client.enable-multiplexing by default
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
Labels: size/S, cherry-pick-approved, release-note-none, approved, lgtm

#9846 ddlManager (ticdc): Fix a bug that could lead to TiCDC replicating DDL events of ineligible tables.
  cdc/owner/ddl_manager.go
  cdc/owner/schema.go
  cdc/owner/schema_test.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9852 sink(cdc): fix the bug that mq sink can lost callbacks
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  tests/integration_tests/mq_sink_lost_callback/conf/diff_config.toml
  tests/integration_tests/mq_sink_lost_callback/run.sh
  tests/integration_tests/run_group.sh
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9825 kafka(ticdc): index-value dispatcher support set index names.
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_mock.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/model.go
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
  cdc/sink/dmlsink/mq/dispatcher/event_router.go
  cdc/sink/dmlsink/mq/dispatcher/event_router_test.go
  cdc/sink/dmlsink/mq/dispatcher/partition/default.go
  cdc/sink/dmlsink/mq/dispatcher/partition/default_test.go
  cdc/sink/dmlsink/mq/dispatcher/partition/dispatcher.go
  cdc/sink/dmlsink/mq/dispatcher/partition/index_value.go
  cdc/sink/dmlsink/mq/dispatcher/partition/index_value_test.go
  cdc/sink/dmlsink/mq/dispatcher/partition/key.go
  cdc/sink/dmlsink/mq/dispatcher/partition/key_test.go
  cdc/sink/dmlsink/mq/dispatcher/partition/table.go
  cdc/sink/dmlsink/mq/dispatcher/partition/table_test.go
  cdc/sink/dmlsink/mq/dispatcher/partition/ts.go
  cdc/sink/dmlsink/mq/dispatcher/partition/ts_test.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cmd/kafka-consumer/main.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  errors.toml
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/config/sink.go
  pkg/errors/cdc_errors.go
  pkg/errors/helper.go
Labels: size/XL, release-note, approved, lgtm

#9792 metadata(cdc): add observation implementation (part 2)
  cdc/model/errors.go
  cdcv2/metadata/errors.go
  cdcv2/metadata/memory/main_test.go
  cdcv2/metadata/memory/memory.go
  cdcv2/metadata/memory/memory_test.go
  cdcv2/metadata/metadata.go
  cdcv2/metadata/model.go
  cdcv2/metadata/sql/client.go
  cdcv2/metadata/sql/client_orm.go
  cdcv2/metadata/sql/client_test.go
  cdcv2/metadata/sql/model.go
  cdcv2/metadata/sql/observation.go
  cdcv2/metadata/sql/tables.go
  cdcv2/metadata/sql/tables_test.go
  cdcv2/metadata/sql/uuid.go
  errors.toml
  go.mod
  pkg/cmd/server/server_test.go
  pkg/config/replica_config.go
  pkg/config/server_config.go
  pkg/errors/cdc_errors.go
  pkg/pdutil/api_client.go
  pkg/security/credential.go
  pkg/upstream/manager.go
  pkg/upstream/upstream.go
Labels: size/XXL, require-LGT1, release-note, approved, lgtm

#9856 ddl: support report error when replicate incompatible ddl
  cdc/owner/schema_test.go
  dm/pkg/storage/utils.go
  dm/syncer/dbconn/utils.go
  dm/syncer/ddl.go
  dm/syncer/filter.go
  dm/syncer/syncer.go
  dm/tests/incompatible_ddl_changes/conf/dm-master.toml
  dm/tests/incompatible_ddl_changes/conf/dm-task.yaml
  dm/tests/incompatible_ddl_changes/conf/dm-task1.yaml
  dm/tests/incompatible_ddl_changes/conf/dm-worker1.toml
  dm/tests/incompatible_ddl_changes/conf/source1.yaml
  dm/tests/incompatible_ddl_changes/data/db1.increment.sql
  dm/tests/incompatible_ddl_changes/data/db1.prepare.sql
  dm/tests/incompatible_ddl_changes/run.sh
  dm/tests/run_group.sh
  dm/tests/shardddl1/run.sh
  go.mod
  go.sum
  pkg/sink/cloudstorage/path.go
  pkg/util/external_storage.go
Labels: size/XXL, release-note, approved, lgtm

#9872 config, changefeed (ticdc): add changefeed error stuck duration config
  Makefile
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/orchestrator/reactor_state.go
  pkg/orchestrator/reactor_state_test.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9879 kafka(ticdc): fix kafka dml sink report error to sink manager
  cdc/sink/dmlsink/mq/mq_dml_sink.go
Labels: size/S, cherry-pick-approved, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9860 p2p(ticdc): remove etcd dependency from p2p agent
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/rexport.go
  pkg/etcd/etcd.go
  pkg/etcd/mock/etcd_client_mock.go
Labels: size/L, release-note-none, approved, lgtm

#9842 client(cdc): use a small backoff to load regions
  cdc/kv/shared_client.go
  cdc/kv/shared_stream.go
Labels: size/S, release-note-none, approved, lgtm

#9882 sorter(cdc): fix panics of accessing sort engine
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter_test.go
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9865 controller(ticdc): add CreateChangefeed func for controller
  cdc/api/v1/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/capture/capture.go
  cdc/controller/controller.go
  cdc/controller/controller_test.go
  cdc/controller/mock/controller_mock.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/mock/etcd_client_mock.go
Labels: size/M, release-note-none, approved, lgtm

#9864 metadata(cdc): implement sql UUID generator and refactor client
  cdcv2/metadata/metadata.go
  cdcv2/metadata/model.go
  cdcv2/metadata/sql/client.go
  cdcv2/metadata/sql/client_orm.go
  cdcv2/metadata/sql/observation.go
  cdcv2/metadata/sql/uuid.go
  cdcv2/metadata/sql/uuid_test.go
  errors.toml
  go.mod
  pkg/errors/cdc_errors.go
Labels: size/XXL, release-note, approved, lgtm

#9894 kafka(ticdc): fix kafka dml sink report error to sink manager (#9879)
  cdc/sink/dmlsink/mq/mq_dml_sink.go
Labels: size/S, release-note-none, approved, lgtm

#9893 reset internal state of feedStateManager when shouldBeRunning is false
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner.go
  pkg/orchestrator/reactor_state.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9851 scheduler(ticdc): fix invlaid checkpoint when redo enabled
  cdc/owner/changefeed.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/scheduler/internal/v3/agent/main_test.go
  cdc/scheduler/internal/v3/compat/main_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_bench_test.go
  cdc/scheduler/internal/v3/keyspan/main_test.go
  cdc/scheduler/internal/v3/member/main_test.go
  cdc/scheduler/internal/v3/replication/main_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/replication/replication_set_test.go
  cdc/scheduler/internal/v3/scheduler/main_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler.go
  cdc/scheduler/internal/v3/scheduler/scheduler_balance.go
  cdc/scheduler/internal/v3/scheduler/scheduler_balance_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_basic.go
  cdc/scheduler/internal/v3/scheduler/scheduler_basic_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture.go
  cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_move_table.go
  cdc/scheduler/internal/v3/scheduler/scheduler_move_table_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_rebalance.go
  cdc/scheduler/internal/v3/scheduler/scheduler_rebalance_test.go
  cdc/scheduler/internal/v3/transport/main_test.go
Labels: size/XXL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9897 gc(ticdc): fix data race in gc manager
  pkg/txnutil/gc/gc_manager.go
Labels: size/XS, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#9885 owner(ticdc): Add update changefeed func for owner
  cdc/api/v1/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/capture/capture.go
  cdc/capture/mock/capture_mock.go
  cdc/owner/mock/owner_mock.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
Labels: size/L, release-note-none, approved, lgtm

#9867 dm: support dm worker incremental validator cutover switch
  dm/ctl/master/update_validation.go
  dm/ctl/master/validation_cmd.go
  dm/master/server.go
  dm/master/workerrpc/interface.go
  dm/master/workerrpc/rawgrpc.go
  dm/pb/dmmaster.pb.go
  dm/pb/dmworker.pb.go
  dm/pbmock/dmmaster.go
  dm/pbmock/dmworker.go
  dm/proto/dmmaster.proto
  dm/proto/dmworker.proto
  dm/syncer/data_validator.go
  dm/worker/server.go
  dm/worker/source_worker.go
  dm/worker/subtask.go
Labels: size/XXL, release-note-none, approved, lgtm

#9783 owner(ticdc): decouple changefeed from reactor
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
Labels: size/XXL, release-note-none, approved, lgtm

#9863 kafka(ticdc): support columns dispatcher.
  cdc/api/v2/model.go
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
  cdc/sink/dmlsink/mq/dispatcher/event_router.go
  cdc/sink/dmlsink/mq/dispatcher/partition/columns.go
  cdc/sink/dmlsink/mq/dispatcher/partition/columns_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/config/sink.go
  tests/integration_tests/mq_sink_dispatcher/conf/changefeed.toml
  tests/integration_tests/mq_sink_dispatcher/conf/diff_config.toml
  tests/integration_tests/mq_sink_dispatcher/conf/new_changefeed.toml
  tests/integration_tests/mq_sink_dispatcher/run.sh
  tests/integration_tests/run_group.sh
Labels: size/XL, release-note, approved, lgtm, needs-cherry-pick-release-7.5

#9912 kv-client(cdc): add more metrics and logs
  cdc/kv/client.go
  cdc/kv/metrics.go
  cdc/kv/regionlock/region_range_lock.go
  cdc/kv/regionlock/region_range_lock_test.go
  cdc/kv/shared_client.go
  cdc/kv/shared_client_test.go
  cdc/kv/sharedconn/conn_and_client.go
  cdc/kv/sharedconn/conn_and_client_test.go
  cdc/processor/sourcemanager/manager.go
  cdc/puller/ddl_puller.go
Labels: size/L, release-note-none, approved, lgtm

#9903 codec(ticdc): add simple encoder and decoder interface declaration.
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder.go
Labels: size/L, release-note-none, approved, lgtm

#9917 changefeed(ticdc): check changefeed info is nil to prevent panic
  pkg/upstream/manager.go
Labels: size/XS, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#9914 server(ticc): add feature flag for cdc v2
  cdc/server/server.go
  cdcv2/capture/capture.go
  pkg/cmd/server/server_test.go
  pkg/config/cdc_v2.go
  pkg/config/cdc_v2_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
Labels: size/XL, release-note-none, approved, lgtm

#9922 owner(ticdc): refine status provider interface
  cdc/owner/mock/status_provider_mock.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/owner/status_provider.go
Labels: size/L, release-note-none, approved, lgtm

#9932 Revert bef3924c in release 7.1
  cdc/owner/changefeed.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/scheduler/internal/v3/agent/main_test.go
  cdc/scheduler/internal/v3/compat/main_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_bench_test.go
  cdc/scheduler/internal/v3/keyspan/main_test.go
  cdc/scheduler/internal/v3/member/main_test.go
  cdc/scheduler/internal/v3/replication/main_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/replication/replication_set_test.go
  cdc/scheduler/internal/v3/scheduler/main_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler.go
  cdc/scheduler/internal/v3/scheduler/scheduler_balance.go
  cdc/scheduler/internal/v3/scheduler/scheduler_balance_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_basic.go
  cdc/scheduler/internal/v3/scheduler/scheduler_basic_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture.go
  cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_move_table.go
  cdc/scheduler/internal/v3/scheduler/scheduler_move_table_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_rebalance.go
  cdc/scheduler/internal/v3/scheduler/scheduler_rebalance_test.go
  cdc/scheduler/internal/v3/transport/main_test.go
Labels: size/XXL, cherry-pick-approved, release-note, approved, lgtm

#9843 metadata(cdc): add unit tests (part 3)
  cdc/model/errors_test.go
  cdcv2/metadata/model.go
  cdcv2/metadata/sql/client.go
  cdcv2/metadata/sql/client_orm.go
  cdcv2/metadata/sql/client_test.go
  cdcv2/metadata/sql/observation.go
  pkg/config/replica_config.go
Labels: size/XXL, release-note, approved, lgtm

#9931 capture(ticdc): remove reactor from owner and controller interface
  cdc/capture/capture.go
  cdc/controller/controller.go
  cdc/controller/mock/controller_mock.go
  cdc/owner/mock/owner_mock.go
  cdc/owner/owner.go
Labels: size/M, release-note-none, approved, lgtm

#9933 kv-client(cdc): log slowest regions and region holes
  cdc/kv/regionlock/region_range_lock.go
  cdc/kv/shared_client.go
Labels: size/M, release-note-none, approved, lgtm

#9936 mysql(ticdc): use string join to build multi statement sql.
  cdc/sink/dmlsink/txn/mysql/mysql.go
Labels: size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#9829 Removed String() call in favor of variable substitution.
  dm/pkg/binlog/position.go
  dm/syncer/checkpoint.go
  dm/syncer/syncer.go
Labels: first-time-contributor, size/S, contribution, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, ok-to-test, approved, lgtm

#9953 scheduler(ticdc): revert 3b8d55 and do not return error when resolvedTs less than checkpoint
  cdc/owner/changefeed.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/scheduler/internal/v3/agent/main_test.go
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/compat/main_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_bench_test.go
  cdc/scheduler/internal/v3/keyspan/main_test.go
  cdc/scheduler/internal/v3/member/main_test.go
  cdc/scheduler/internal/v3/replication/main_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/replication/replication_set_test.go
  cdc/scheduler/internal/v3/scheduler/main_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler.go
  cdc/scheduler/internal/v3/scheduler/scheduler_balance.go
  cdc/scheduler/internal/v3/scheduler/scheduler_balance_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_basic.go
  cdc/scheduler/internal/v3/scheduler/scheduler_basic_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture.go
  cdc/scheduler/internal/v3/scheduler/scheduler_drain_capture_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_move_table.go
  cdc/scheduler/internal/v3/scheduler/scheduler_move_table_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_rebalance.go
  cdc/scheduler/internal/v3/scheduler/scheduler_rebalance_test.go
  cdc/scheduler/internal/v3/transport/main_test.go
Labels: size/XXL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#9927 consumer(ticdc): kafka consumer start pprof to detect memory consumption
  .golangci.yml
  cmd/kafka-consumer/main.go
  pkg/sink/codec/avro/confluent_schema_registry.go
Labels: size/L, release-note-none, approved, lgtm

#9955 kafka(ticdc): topic manager return the partition number specified in the sink-uri
  cdc/sink/ddlsink/mq/mq_ddl_sink_test.go
  cdc/sink/dmlsink/mq/manager/kafka_manager.go
  cdc/sink/dmlsink/mq/manager/kafka_manager_test.go
  cdc/sink/util/helper.go
  cdc/sink/util/helper_test.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#9963 kv-client(cdc): fix the bug that region errors can be lost
  cdc/kv/region_state.go
  cdc/kv/shared_client_test.go
  cdc/kv/shared_region_worker.go
  cdc/kv/shared_stream.go
Labels: size/L, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#9911 codec(ticdc): kafka simple encoding protocol support encoding checkpoint event.
  pkg/config/sink_protocol.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
Labels: size/L, release-note-none, approved, lgtm
