Repository pingcap/tiflow, pull requests merged in 2023-07, with the labels that each got.

#9252 ci: add component management to `.codecov.yaml` and migrate flag manage
  .codecov.yml
  Makefile
Labels: size/M, release-note-none, skip-issue-check, approved, lgtm

#9314 test(ticdc): add consistent partition table test
  cdc/owner/ddl_manager.go
  tests/integration_tests/consistent_partition_table/conf/changefeed.toml
  tests/integration_tests/consistent_partition_table/conf/diff_config.toml
  tests/integration_tests/consistent_partition_table/data/create.sql
  tests/integration_tests/consistent_partition_table/data/prepare.sql
  tests/integration_tests/consistent_partition_table/run.sh
  tests/integration_tests/run_group.sh
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9322 sink (ticdc): add retry backoff and limit for sinkManager
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
Labels: size/M, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#9198 tests, consumer(ticdc): fix storage consumer
  cmd/storage-consumer/main.go
  tests/integration_tests/big_txn/run.sh
Labels: size/S, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9312 schema(ticdc): fix some redundant logic and incorrect comment
  cdc/entry/schema/snapshot.go
  cdc/model/schema_storage.go
  cdc/model/sink.go
Labels: size/S, release-note-none, approved, lgtm

#9335 codec(ticdc): remove 2nd parameter from the decoder interface.
  cdc/entry/mounter_test.go
  cmd/kafka-consumer/main.go
  cmd/storage-consumer/main.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/decoder_test.go
  pkg/sink/codec/builder/codec_test.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/craft/craft_decoder.go
  pkg/sink/codec/craft/craft_encoder_test.go
  pkg/sink/codec/csv/csv_decoder.go
  pkg/sink/codec/csv/csv_decoder_test.go
  pkg/sink/codec/decoder.go
  pkg/sink/codec/internal/batch_tester.go
  pkg/sink/codec/open/open_protocol_decoder.go
  pkg/sink/codec/open/open_protocol_decoder_test.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
Labels: size/L, release-note-none, approved, lgtm

#9244 sink(ticdc): fix create storage sink
  pkg/util/external_storage.go
Labels: size/XS, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9326 changefeed (ticdc):Manual cherry pick #9138, #9194 to release 7.1
  cdc/api/v1/api_test.go
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/api_test.go
  cdc/api/v2/changefeed_test.go
  cdc/model/changefeed.go
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_manager.go
  cdc/owner/feed_state_manager.go
  cdc/owner/mock/status_provider_mock.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/owner/status_provider.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/scheduler.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/info_provider_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/rexport.go
  cdc/scheduler/schedulepb/barrier.go
  pkg/etcd/etcd_test.go
  pkg/migrate/migrate_test.go
  pkg/orchestrator/reactor_state_test.go
  tests/integration_tests/consistent_replicate_ddl/run.sh
Labels: size/XXL, cherry-pick-approved, release-note, approved, lgtm

#9337 codec(ticdc): adjust open protocol only output udated column
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_message.go
  pkg/sink/codec/open/open_protocol_message_test.go
Labels: size/L, release-note-none, approved, lgtm

#9282 kafka(ticdc): remove parallel from kafka dml producer unit test
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer_test.go
Labels: size/S, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#9353 checker(dm): handle expression UNIQUE index
  dm/pkg/checker/table_structure_test.go
  dm/pkg/checker/utils.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9356 kafka(ticdc): use sarama mock producer in the unit test to workaround the data race
  cdc/sink/ddlsink/mq/ddlproducer/ddl_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_mock_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/ddlsink/mq/mq_ddl_sink_test.go
  cdc/sink/dmlsink/factory/factory_test.go
  cdc/sink/dmlsink/mq/dmlproducer/dml_producer.go
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_mock_producer.go
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer_test.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink_test.go
  cdc/sink/dmlsink/mq/worker_test.go
  pkg/sink/kafka/mock_factory.go
Labels: size/XXL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9355 p2p(ticdc): fix panic issue when peer is not found
  pkg/p2p/server.go
Labels: size/XS, release-note-none, approved, lgtm

#9368 kafka(ticdc): simplify the kafka sink initialization and close process
  cdc/sink/ddlsink/mq/ddlproducer/ddl_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_mock_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/ddlsink/mq/mq_ddl_sink.go
  cdc/sink/dmlsink/mq/dmlproducer/dml_producer.go
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_mock_producer.go
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer_test.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/worker_test.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/kafka/sarama_factory_test.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/factory_test.go
Labels: size/XL, release-note-none, approved, lgtm

#9347 config(ticdc): add large message handle option config
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed.go
  cdc/sink/ddlsink/mq/mq_ddl_sink_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/config_test.go
  pkg/sink/codec/open/open_protocol_decoder_test.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/v2/factory_test.go
Labels: size/XXL, release-note-none, approved, lgtm

#9366 sink(ticdc): add hex encode to csv
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/config/sink_test.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/csv/csv_decoder.go
  pkg/sink/codec/csv/csv_message.go
  pkg/sink/codec/csv/csv_message_test.go
Labels: size/XL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9369 sink, processor(ticdc): do not close table sink when closing sinkManager
  cdc/processor/sinkmanager/manager.go
Labels: size/XS, cherry-pick-approved, release-note, approved, lgtm

#9381 sink, processor(ticdc): do not close table sink when closing sinkManager
  cdc/processor/sinkmanager/manager.go
Labels: size/XS, cherry-pick-approved, release-note, approved, lgtm

#9358 changefeed (ticdc): remove error state and add pending, warning state
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/api/v2/processor.go
  cdc/api/v2/processor_test.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/model/http_model_test.go
  cdc/owner/changefeed.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner.go
  pkg/cmd/cli/cli_changefeed_list_test.go
  pkg/migrate/migrate_test.go
  tests/integration_tests/changefeed_error/run.sh
Labels: size/XL, release-note-none, approved, lgtm

#9385 sink (ticdc): Add retry limit for ddl sink
  cdc/owner/ddl_sink.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  pkg/filter/filter_test.go
  pkg/retry/error_retry.go
  pkg/retry/error_retry_test.go
Labels: size/L, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#9386 changefeed (ticdc): don't set changefeed to failed state when error retry reach limit
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  pkg/txnutil/gc/gc_manager.go
Labels: size/S, cherry-pick-approved, release-note-none, approved, lgtm

#9374 sink(ticdc): output column id as the unique flag for each column
  cdc/api/v2/model.go
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink_test.go
  cdc/sink/ddlsink/factory/factory.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/config/config_test_data.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/cloudstorage/config_test.go
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/cloudstorage/table_definition_test.go
Labels: size/L, release-note, approved, lgtm

#9341 owner(ticdc): add ticdc controller to schedule changefeed (part 1)
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/api/v2/owner.go
  cdc/api/v2/owner_test.go
  cdc/capture/capture.go
  cdc/capture/mock/capture_mock.go
  cdc/controller/controller.go
  cdc/controller/controller_test.go
  cdc/controller/mock/controller_mock.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  pkg/orchestrator/etcd_worker.go
  pkg/util/identity.go
  scripts/generate-mock.sh
Labels: size/XXL, release-note-none, approved, lgtm

#9376 kafka(ticdc): kafka support claim-check functionality
  cdc/api/v2/model.go
  cdc/model/sink.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/dmlsink/factory/factory_test.go
  cdc/sink/dmlsink/mq/claim_check.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink_test.go
  cdc/sink/dmlsink/mq/worker.go
  cdc/sink/dmlsink/mq/worker_test.go
  cdc/sink/metrics/mq/metrics.go
  cmd/kafka-consumer/main.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  go.mod
  go.sum
  pkg/config/config_test_data.go
  pkg/config/sink.go
  pkg/sink/codec/builder/codec_test.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/config_test.go
  pkg/sink/codec/common/message.go
  pkg/sink/codec/encoder.go
  pkg/sink/codec/internal/message_key.go
  pkg/sink/codec/open/open_protocol_decoder.go
  pkg/sink/codec/open/open_protocol_decoder_test.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
Labels: size/XXL, release-note-none, approved, lgtm

#9400 metrics(ticdc): add claim check monitoring panels
  metrics/grafana/ticdc.json
Labels: size/XXL, release-note-none, approved, lgtm

#9384 codec(ticdc): canal-json support large message handle
  cmd/kafka-consumer/main.go
  cmd/storage-consumer/main.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_json_txn_event_encoder.go
Labels: size/XL, release-note-none, approved, lgtm

#9397 chore(ui): upgrade dependencies
  dm/ui/package.json
  dm/ui/yarn.lock
Labels: size/M, release-note, approved, lgtm

#9396 owner(ticdc): do not resign owner when ErrNotOwner is encountered
  cdc/capture/capture.go
  cdc/capture/election.go
  cdc/owner/owner.go
  pkg/orchestrator/etcd_worker.go
Labels: size/M, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9394 controller(ticdc): add query interface to controller
  cdc/api/middleware/middleware.go
  cdc/api/status/status.go
  cdc/api/util.go
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/api/v2/api.go
  cdc/api/v2/capture.go
  cdc/api/v2/capture_test.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/controller.go
  cdc/api/v2/controller_test.go
  cdc/api/v2/health.go
  cdc/api/v2/health_test.go
  cdc/api/v2/processor_test.go
  cdc/api/v2/status.go
  cdc/api/v2/status_test.go
  cdc/api/v2/tso_test.go
  cdc/api/v2/unsafe_test.go
  cdc/capture/capture.go
  cdc/capture/mock/capture_mock.go
  cdc/controller/controller.go
  cdc/controller/controller_test.go
  cdc/controller/mock/controller_mock.go
  cdc/controller/query.go
  cdc/model/changefeed.go
  cdc/owner/mock/status_provider_mock.go
  cdc/owner/owner.go
  cdc/owner/status_provider.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
Labels: size/XXL, release-note-none, approved, lgtm

#9412 api(ticdc): forward changefeed related api to changefeed owner capture
  cdc/api/middleware/middleware.go
  cdc/api/util.go
  cdc/api/v2/api.go
  cdc/api/v2/api_test.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/processor_test.go
  cdc/controller/controller.go
  cdc/controller/mock/controller_mock.go
  cdc/controller/query.go
Labels: size/L, release-note-none, approved, lgtm

#9393 ticdc 2 pulsar : add pulsar config from sink-uri & pulsar errors
  docs/design/2023-07-04-ticdc-pulsar-sink.md
  errors.toml
  go.mod
  go.sum
  pkg/errors/cdc_errors.go
  pkg/sink/pulsar/config.go
  pkg/sink/pulsar/config_test.go
  pkg/sink/sink_type.go
Labels: first-time-contributor, size/XXL, contribution, ok-to-test, approved, lgtm

#9228 engine: support new task mode for dm
  dm/checker/check_test.go
  dm/checker/checker.go
  dm/config/helper.go
  dm/config/helper_test.go
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_test.go
  dm/master/scheduler/scheduler.go
  dm/syncer/checkpoint.go
  dm/syncer/syncer.go
  dm/worker/server.go
  dm/worker/subtask.go
  engine/executor/dm/worker.go
  engine/jobmaster/dm/checkpoint/agent.go
  engine/jobmaster/dm/task_manager.go
  engine/jobmaster/dm/worker_manager.go
  engine/test/e2e/e2e_dm_test.go
  engine/test/integration_tests/dm_dump_sync_mode/run.sh
  engine/test/integration_tests/run_group.sh
Labels: size/XXL, release-note-none, approved, lgtm

#9417 api(ticdc): api v1 forward request to changefeed owner
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/api/v2/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/processor.go
  cdc/api/v2/processor_test.go
  cdc/controller/controller.go
  cdc/controller/mock/controller_mock.go
  cdc/controller/query.go
Labels: size/XL, release-note-none, approved, lgtm

#9424 Fix tiflash block-cache size && remove useless config
  tests/integration_tests/_utils/start_tidb_cluster_impl
Labels: first-time-contributor, size/S, release-note-none, approved, lgtm

#9426 kafka(ticdc): kafka consumer refactor and adjust codec interface
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/worker.go
  cmd/kafka-consumer/main.go
  pkg/config/sink.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/common/message.go
  pkg/sink/codec/encoder.go
  pkg/sink/codec/open/open_protocol_encoder.go
Labels: size/L, release-note-none, approved, lgtm

#9432 api(ticdc): parse the kafka config
  cdc/api/v2/model.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
Labels: size/L, cherry-pick-approved, release-note-none, approved, lgtm

#9423 api(ticdc): adjust the api forward rules
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/api/v1/validator.go
  cdc/api/v2/api.go
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_mock.go
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
Labels: size/L, release-note-none, approved, lgtm

#9401 sink (pulsar): add Expression Pulsar Validate for topic name and unit test .
  cdc/sink/dmlsink/mq/dispatcher/topic/expression.go
  cdc/sink/dmlsink/mq/dispatcher/topic/expression_pulsar_test.go
Labels: first-time-contributor, size/L, contribution, ok-to-test, approved, lgtm

#9429 codec(ticdc): refactor avro encoder to make it easier to extend
  cdc/entry/mounter_test.go
  cmd/kafka-consumer/main.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/avro/avro_test_data.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/decoder_test.go
  pkg/sink/codec/avro/schema_registry.go
  pkg/sink/codec/avro/schema_registry_test.go
Labels: size/XXL, release-note-none, approved, lgtm

#9435 consumer(ticdc): kafka consumer refactor
  cmd/kafka-consumer/main.go
Labels: size/XXL, release-note-none, approved, lgtm

#9438 engine: register loader metric
  dm/loader/lightning.go
  dm/loader/lightning_test.go
  dm/loader/metrics.go
Labels: size/L, release-note-none, approved, lgtm

#9445 pkg/orchestrator(ticdc): add timeout before remove capture
  cdc/capture/capture.go
  cdc/controller/controller_test.go
  cdc/owner/owner_test.go
  cdc/processor/manager_test.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_bank_test.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/interfaces.go
  pkg/orchestrator/reactor_state.go
  pkg/orchestrator/reactor_state_test.go
Labels: size/L, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm
