Repository pingcap/tiflow, pull requests merged in 2023-06, with the labels that each got.

#9049 cli(ticdc): cli support namespace
  pkg/api/v2/changefeed.go
  pkg/api/v2/mock/changefeed_mock.go
  pkg/api/v2/mock/processor_mock.go
  pkg/api/v2/processor.go
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_list.go
  pkg/cmd/cli/cli_changefeed_list_test.go
  pkg/cmd/cli/cli_changefeed_pause.go
  pkg/cmd/cli/cli_changefeed_pause_test.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_changefeed_query_test.go
  pkg/cmd/cli/cli_changefeed_remove.go
  pkg/cmd/cli/cli_changefeed_remove_test.go
  pkg/cmd/cli/cli_changefeed_resume.go
  pkg/cmd/cli/cli_changefeed_resume_test.go
  pkg/cmd/cli/cli_changefeed_statistics.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_changefeed_update_test.go
  pkg/cmd/cli/cli_processor_query.go
  pkg/cmd/cli/cli_processor_query_test.go
  tests/integration_tests/avro_basic/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#9107 pkg/sink(ticdc): add GetTopicConfig support
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/cluster_admin_client_mock_impl.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/v2/admin.go
  pkg/sink/kafka/v2/admin_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#9032 codec(cdc) Removing logging of message bodies to avoid PII issues
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_txn_event_encoder.go
  pkg/sink/codec/open/open_protocol_encoder.go
Labels: status/LGT2, status/can-merge, first-time-contributor, severity/minor, size/XS, contribution, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, needs-ok-to-test

#9079 config(ticdc): enable-old-value always false if using avro or csv as the encoding protocol
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_test.go
  cdc/entry/mounter.go
  cdc/entry/mounter_group.go
  cdc/entry/mounter_test.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  errors.toml
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/config/sink_test.go
  pkg/errors/cdc_errors.go
  pkg/orchestrator/reactor_state.go
  pkg/sink/codec/builder/codec_test.go
  pkg/sink/codec/builder/encoder_builder.go
  pkg/sink/codec/canal/canal_encoder.go
  pkg/sink/codec/canal/canal_encoder_test.go
  pkg/sink/codec/canal/canal_entry.go
  pkg/sink/codec/canal/canal_entry_test.go
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_json_txn_event_encoder.go
  pkg/sink/codec/canal/canal_json_txn_event_encoder_test.go
  pkg/sink/codec/canal/canal_test_util.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/config_test.go
  pkg/sink/codec/craft/craft_encoder.go
  pkg/sink/codec/craft/craft_encoder_test.go
  pkg/sink/codec/craft/model.go
  pkg/sink/codec/maxwell/maxwell_encoder.go
  pkg/sink/codec/maxwell/maxwell_encoder_test.go
  pkg/sink/codec/maxwell/maxwell_message.go
  pkg/sink/codec/maxwell/maxwell_message_test.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/codec/open/open_protocol_message.go
  pkg/sink/codec/open/open_protocol_message_test.go
  pkg/version/creator_version_gate.go
  tests/integration_tests/multi_changefeed/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note, needs-cherry-pick-release-6.5, approved, lgtm

#9128 metrics(ticdc): fix inaccurate kafka v2 batch time metrics.
  go.mod
  go.sum
  pkg/sink/kafka/v2/metrics_collector.go
Labels: size/S, release-note-none, approved, lgtm

#9123 scheduler, processor(ticdc): replace some panic with error
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/redo_log_worker_test.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sourcemanager/engine/engine.go
  cdc/processor/sourcemanager/engine/memory/event_sorter.go
  cdc/processor/sourcemanager/engine/memory/event_sorter_test.go
  cdc/processor/sourcemanager/engine/mock/engine_mock.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter_test.go
  cdc/processor/sourcemanager/manager.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  errors.toml
  pkg/errors/cdc_errors.go
Labels: status/LGT2, status/can-merge, size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9135 codec(ticdc): refactor avro encoder to use code config directly to avoid duplicate option
  cmd/kafka-consumer/main.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/decoder_test.go
  pkg/sink/codec/common/config.go
Labels: size/L, release-note-none, approved, lgtm

#9148 puller(ticdc): remove table info from context
  cdc/contextutil/ctx.go
  cdc/contextutil/ctx_test.go
  cdc/processor/processor.go
  cdc/puller/ddl_puller.go
  cdc/puller/memorysorter/entry_sorter.go
Labels: size/L, release-note-none, approved, lgtm

#9136 config(ticdc): expose changefeed level config delete_only_output_handle_key_columns
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/sink/codec/canal/canal_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/config_test.go
  pkg/sink/codec/craft/craft_encoder.go
  pkg/sink/codec/maxwell/maxwell_encoder.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/kafka/options_test.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, approved, lgtm

#9122 metrics(ticdc): grafana dashboard support namespace selection
  metrics/grafana/TiCDC-Monitor-Summary.json
  metrics/grafana/ticdc.json
Labels: size/XXL, release-note-none, approved, lgtm

#8816 Makefile: bump version to v7.2.0
  Makefile
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, approved, lgtm

#9141 metric(ticdc): fix ddl sink context has no changefeed id bug
  cdc/owner/ddl_sink.go
Labels: size/XS, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#9132 api(ticdc): fix api v1 not parse protocol from uri bug
  cdc/api/v1/validator.go
Labels: size/S, release-note, needs-cherry-pick-release-7.1, approved, lgtm

#9156 util(ticdc): remove capture addr from context
  cdc/contextutil/ctx.go
  cdc/contextutil/ctx_test.go
  cdc/owner/changefeed.go
  cdc/processor/processor.go
  cdc/redo/manager.go
  cdc/redo/meta_manager.go
  cdc/redo/meta_manager_test.go
  cdc/sink/metrics/statistics.go
  pkg/cmd/server/server.go
  pkg/sink/kafka/options.go
Labels: size/M, release-note-none, approved, lgtm

#9138 chngefeed (ticdc): move resolvedTs into globalBarrierTs when redo log is enabled.
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_manager.go
  cdc/owner/owner_test.go
  cdc/processor/processor.go
  cdc/scheduler/internal/scheduler.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/info_provider_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/rexport.go
  cdc/scheduler/schedulepb/barrier.go
  tests/integration_tests/consistent_replicate_ddl/run.sh
Labels: status/ptal, size/XL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9174 changefeed (ticdc): remove status of a changefeed after it is removed
  cdc/owner/changefeed.go
  cdc/processor/processor.go
Labels: status/ptal, size/XS, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9191 tests(ticdc): fix the flaky test
  tests/integration_tests/kafka_compression/run.sh
Labels: size/XS, cherry-pick-approved, release-note-none, approved, lgtm

#9146 sink(ticdc): Optimize the performance when getting the metadata of Kafka topics
  cdc/sink/mq/manager/kafka_manager.go
  cdc/sink/mq/manager/kafka_manager_test.go
  cdc/sink/mq/manager/manager.go
  cdc/sink/mq/manager/pulsar_manager.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/producer/kafka/config.go
  cdc/sink/mq/producer/kafka/config_test.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/oauth2_token_provider.go
  cdc/sink/mq/producer/kafka/oauth2_token_provider_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  go.mod
  go.sum
  pkg/config/sink.go
  pkg/kafka/cluster_admin_client.go
  pkg/kafka/cluster_admin_client_mock_impl.go
  pkg/security/sasl.go
Labels: size/XXL, cherry-pick-approved, release-note, approved, lgtm

#9181 test(dm): uncomment a test after tidb-tools update dependency
  dm/tests/case_sensitive/run.sh
Labels: size/M, release-note-none, skip-issue-check, approved, lgtm

#9164 codec(ticdc): open-protocol support encode only handle key column if the message size large than the max message bytes
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/config_test.go
  pkg/sink/codec/internal/message_key.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_message.go
  pkg/sink/codec/open/open_protocol_message_test.go
Labels: size/L, release-note-none, approved, lgtm

#9192 pkg/p2p(ticdc): refactor p2p message client
  cdc/capture/capture.go
  cdc/server/server.go
  pkg/p2p/client.go
  pkg/p2p/grpc_client.go
  pkg/p2p/grpc_client_test.go
  pkg/p2p/message_router.go
  pkg/p2p/message_router_test.go
  pkg/p2p/mock_cluster.go
  pkg/p2p/server.go
  pkg/p2p/server_ack_manager.go
  pkg/p2p/server_stream_handle.go
Labels: size/XXL, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9113 dm: add strict optimist mode
  dm/_utils/terror_gen/errors_release.txt
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_converters.go
  dm/config/task_converters_test.go
  dm/errors.toml
  dm/openapi/fixtures/task.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/pkg/terror/errcode_string.go
  dm/pkg/terror/error_list.go
  dm/syncer/ddl.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
  dm/tests/shardddl4_1/conf/double-source-strict-optimistic.yaml
  dm/tests/shardddl4_1/conf/single-source-strict-optimistic.yaml
  dm/tests/shardddl4_1/run.sh
  engine/jobmaster/dm/config/config.go
  engine/jobmaster/dm/config/dm_subtask_3306.toml
  engine/jobmaster/dm/config/dm_subtask_3307.toml
  engine/jobmaster/dm/config/job_template.yaml
Labels: size/XXL, release-note, area/dm, approved, lgtm

#9044 puller (ticdc): Clean up puller metrics
  cdc/processor/processor.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_bench_test.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/metrics.go
  cdc/puller/puller.go
Labels: status/LGT1, size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9214 ddlManager (ticdc): only log once when executing a ddl
  cdc/owner/ddl_manager.go
Labels: size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9223 cdc: recycle memory for unbounded channel
  pkg/chann/chann.go
Labels: size/XS, release-note-none, approved, lgtm

#9187 codec(ticdc): decoder support only handle key columns
  cmd/kafka-consumer/main.go
  cmd/storage-consumer/main.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/decoder_test.go
  pkg/sink/codec/builder/codec_test.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/craft/craft_decoder.go
  pkg/sink/codec/craft/craft_encoder_test.go
  pkg/sink/codec/csv/csv_decoder.go
  pkg/sink/codec/csv/csv_decoder_test.go
  pkg/sink/codec/decoder.go
  pkg/sink/codec/internal/batch_tester.go
  pkg/sink/codec/open/open_protocol_decoder.go
  pkg/sink/codec/open/open_protocol_decoder_test.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
Labels: size/L, release-note-none, approved, lgtm

#9175 mysql (ticdc): only set write source when downstream is supported
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  pkg/applier/redo_test.go
  pkg/sink/mysql/config.go
Labels: size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9232 sorter(cdc): use correct resolved timestamp to check progress
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sourcemanager/engine/engine.go
  cdc/processor/sourcemanager/engine/memory/event_sorter.go
  cdc/processor/sourcemanager/engine/mock/engine_mock.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter_test.go
  cdc/processor/sourcemanager/manager.go
Labels: size/L, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#9240 processor (ticdc): remove remain event metric
  cdc/processor/metrics.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sourcemanager/engine/engine.go
  cdc/processor/sourcemanager/engine/memory/event_sorter.go
  cdc/processor/sourcemanager/engine/mock/engine_mock.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/manager.go
  metrics/grafana/ticdc.json
Labels: size/XL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9199 codec(ticdc): refactor avro decoder by split the decode row method into small pieces
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/decoder.go
Labels: size/L, release-note-none, approved, lgtm

#9194 changefeed (ticdc): remove resolvedTs from etcd
  cdc/api/v1/api_test.go
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/api_test.go
  cdc/api/v2/changefeed_test.go
  cdc/model/changefeed.go
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state_manager.go
  cdc/owner/mock/status_provider_mock.go
  cdc/owner/owner.go
  cdc/owner/status_provider.go
  cdc/processor/processor_test.go
  pkg/etcd/etcd_test.go
  pkg/migrate/migrate_test.go
  pkg/orchestrator/reactor_state_test.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9218 ci: skip some CI builds when only changed to documents and OWNERS files
  .github/workflows/check_and_build.yaml
  .github/workflows/ticdc_integration.yaml
Labels: size/S, release-note-none, skip-issue-check, needs-cherry-pick-release-7.1, approved, lgtm

#9261 metrics (ticdc): remove stale alert rules
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  metrics/alertmanager/ticdc.rules.yml
Labels: size/M, release-note-none, approved, lgtm

#9263 shardddl: return error if conflict happened when receive conflict detect operation
  dm/syncer/ddl.go
  dm/tests/shardddl4_1/run.sh
Labels: size/XS, release-note, approved, lgtm, needs-cherry-pick-release-7.2

#9265 metrics (ticdc): add changefeed status alert rules
  metrics/alertmanager/ticdc.rules.yml
Labels: size/M, release-note-none, approved, lgtm

#8373 dm: MySQL 8.0 Compressed Binlogs
  dm/syncer/binlogstream/binlog_locations.go
  dm/syncer/syncer.go
  go.mod
  go.sum
Labels: status/LGT2, size/M, release-note, approved, lgtm

#9276 scheduler, processor(ticdc): advance redo resolvedTs before start sink
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/redo_log_advancer_test.go
  cdc/redo/manager.go
  cdc/scheduler/internal/table_executor.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/agent/table.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9277 scheduler, processor(ticdc): advance redo resolvedTs before start sink
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/redo_log_advancer_test.go
  cdc/redo/manager.go
  cdc/scheduler/internal/table_executor.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/agent/table.go
Labels: size/L, cherry-pick-approved, release-note, approved, lgtm

#9274 avro(ticdc): calculate checksum locally by follow tidb rules
  cdc/entry/mounter_test.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/decoder_test.go
  pkg/sink/codec/avro/mock_schema_registry.go
  pkg/sink/codec/avro/schema_registry_test.go
Labels: size/XXL, release-note-none, approved, lgtm

#9211 pkg/p2p(ticdc): implement local client and server
  cdc/capture/capture.go
  engine/pkg/p2p/server.go
  engine/pkg/p2p/server_integration_test.go
  engine/servermaster/server.go
  engine/test/integration_tests/dm_full_mode/run.sh
  pkg/p2p/client.go
  pkg/p2p/client_batch_sender.go
  pkg/p2p/grpc_client.go
  pkg/p2p/grpc_client_test.go
  pkg/p2p/message_router.go
  pkg/p2p/message_router_test.go
  pkg/p2p/mock_cluster.go
  pkg/p2p/model.go
  pkg/p2p/server.go
  pkg/p2p/server_client_integration_test.go
  pkg/p2p/server_stream_handle.go
  pkg/p2p/server_test.go
Labels: size/XL, release-note, approved, lgtm

#9262 mounter(ticdc): enum type default value set explicitly to avoid wrong enum value fetched by the encoder
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  pkg/sink/codec/avro/avro.go
Labels: size/M, release-note-none, approved, lgtm

#9287 pkg/sink(ticdc): Update Kafka cluster every 30min
  pkg/sink/kafka/metrics_collector.go
Labels: size/S, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9226 puller(cdc): prepare stream multiplexing code struct
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/metrics.go
  cdc/kv/region_state.go
  cdc/kv/region_state_bench_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/kv/regionlock/region_range_lock.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sourcemanager/manager.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
  cdc/puller/frontier/frontier.go
  go.mod
  go.sum
  metrics/grafana/ticdc.json
  pkg/chann/chann.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/kvclient.go
  pkg/config/server_config.go
  pkg/leakutil/leak_helper.go
Labels: status/can-merge, size/XXL, release-note-none, approved, lgtm

#9298 pdutil (ticdc): refine pd clock interface
  cdc/kv/region_worker.go
  cdc/owner/changefeed.go
  cdc/owner/feed_state_manager.go
  cdc/processor/processor.go
  cdc/scheduler/internal/v3/coordinator.go
  pkg/pdutil/clock.go
  pkg/pdutil/clock_test.go
  pkg/txnutil/gc/gc_manager.go
Labels: size/M, release-note, needs-cherry-pick-release-6.5, approved, lgtm

#9299 example(ticdc): add avro checksum verification example
  examples/golang/avro-checksum-verification/README.md
  examples/golang/avro-checksum-verification/go.mod
  examples/golang/avro-checksum-verification/go.sum
  examples/golang/avro-checksum-verification/main.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/avro/decoder.go
Labels: size/XXL, release-note-none, approved, lgtm

#9297 dm: add strict-optimistic-shard-mode for v6.5.3
  dm/_utils/terror_gen/errors_release.txt
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_converters.go
  dm/config/task_converters_test.go
  dm/errors.toml
  dm/openapi/fixtures/task.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/pkg/terror/errcode_string.go
  dm/pkg/terror/error_list.go
  dm/syncer/ddl.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
  dm/tests/shardddl4_1/conf/double-source-strict-optimistic.yaml
  dm/tests/shardddl4_1/conf/single-source-strict-optimistic.yaml
  dm/tests/shardddl4_1/run.sh
  engine/jobmaster/dm/config/config.go
  engine/jobmaster/dm/config/dm_subtask_3306.toml
  engine/jobmaster/dm/config/dm_subtask_3307.toml
  engine/jobmaster/dm/config/job_template.yaml
Labels: size/XXL, release-note, approved, lgtm

#9210 test(dm): reset SQL mode when exit test case
  dm/tests/case_sensitive/run.sh
Labels: size/XS, cherry-pick-approved, release-note, approved, lgtm

#9296 scheduler(ticdc): adjust some logic in scheduler
  cdc/owner/changefeed.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/info_provider_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/scheduler/scheduler_basic.go
  pkg/spanz/btree_map.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9304 cdc: fail the changefeed blocking global gc and suppressing the gc-ttl
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/errors/helper.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_manager_test.go
Labels: size/M, release-note, approved, lgtm

#9281 redo, processor(ticdc): set flushed resolvedTs when start table
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test_helper.go
  cdc/redo/manager.go
  cdc/redo/meta_manager.go
  cdc/scheduler/internal/table_executor.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/agent/table.go
Labels: size/XL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9310 sink(cdc): reduce lock when closing table sinks
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/sink/tablesink/table_sink_impl_test.go
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, approved, lgtm
