Repository pingcap/tiflow, pull requests merged in 2023-09, with the labels that each got.

#9642 Updated tidb dependency
  .github/workflows/check_and_build.yaml
  .github/workflows/dataflow_engine_chaos.yaml
  .github/workflows/dm_binlog_999999.yaml
  .github/workflows/dm_chaos.yaml
  .github/workflows/dm_upstream_switch.yaml
  .github/workflows/upgrade_dm_via_tiup.yaml
  .golangci.yml
  cdc/owner/schema_test.go
  dm/checker/checker.go
  dm/loader/lightning.go
  dm/pkg/conn/mockdb.go
  engine/jobmaster/example/worker_impl.go
  engine/pkg/externalresource/broker/broker_integration_test.go
  engine/pkg/externalresource/broker/broker_test.go
  engine/pkg/externalresource/integration_test/gc_test.go
  engine/pkg/externalresource/internal/bucket/file_manager.go
  engine/pkg/externalresource/internal/local/file_manager_test.go
  go.mod
  go.sum
  pkg/util/external_storage.go
Labels: size/XL, release-note, approved, lgtm

#9662 puller(cdc): fix a code race
  cdc/puller/multiplexing_puller.go
Labels: size/XS, release-note-none, approved, lgtm

#9664 scheduller(ticc): fix uneven write keys distribution
  cdc/scheduler/internal/v3/keyspan/mock.go
  cdc/scheduler/internal/v3/keyspan/reconciler.go
  cdc/scheduler/internal/v3/keyspan/reconciler_test.go
  cdc/scheduler/internal/v3/keyspan/splitter_region_count.go
  cdc/scheduler/internal/v3/keyspan/splitter_region_count_test.go
  cdc/scheduler/internal/v3/keyspan/splitter_write.go
  cdc/scheduler/internal/v3/keyspan/splitter_write_test.go
Labels: size/XXL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9224 config(ticdc): deprecate changefeed level config enable-old-value
  cdc/api/v1/validator.go
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/entry/mounter.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/owner/feed_state_manager_test.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/redo_log_worker_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/sink/dmlsink/mq/dispatcher/event_router.go
  cdc/sink/dmlsink/mq/dispatcher/event_router_test.go
  cdc/sink/dmlsink/mq/dispatcher/partition/default.go
  cdc/sink/dmlsink/mq/dispatcher/partition/default_test.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  deployments/ticdc/docker-compose/configs/canal-test-config.toml
  deployments/ticdc/docker-compose/configs/enable-oldvalue-config.toml
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/migrate/migrate_test.go
  pkg/orchestrator/reactor_state_test.go
  pkg/sink/codec/common/config.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/config_test.go
  pkg/version/check.go
  pkg/version/check_test.go
  pkg/version/creator_version_gate.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/api_v2/model.go
  tests/integration_tests/force_replicate_table/conf/changefeed.toml
  tests/integration_tests/multi_changefeed/conf/changefeed1.toml
  tests/integration_tests/multi_changefeed/conf/changefeed2.toml
  tests/integration_tests/multi_changefeed/run.sh
  tests/integration_tests/new_ci_collation/conf/diff_config.toml
  tests/integration_tests/new_ci_collation/conf/tidb_config.toml
  tests/integration_tests/new_ci_collation/data/test1.sql
  tests/integration_tests/new_ci_collation/data/test2.sql
  tests/integration_tests/new_ci_collation/run.sh
  tests/integration_tests/new_ci_collation_with_old_value/conf/changefeed.toml
  tests/integration_tests/new_ci_collation_with_old_value/data/test1.sql
  tests/integration_tests/new_ci_collation_without_old_value/conf/changefeed.toml
  tests/integration_tests/new_ci_collation_without_old_value/conf/diff_config.toml
  tests/integration_tests/new_ci_collation_without_old_value/conf/tidb_config.toml
  tests/integration_tests/new_ci_collation_without_old_value/data/test2.sql
  tests/integration_tests/new_ci_collation_without_old_value/run.sh
  tests/integration_tests/run_group.sh
Labels: size/XXL, release-note, approved, lgtm

#9681 tests (ticdc): fix unstable integration: http_api
  tests/integration_tests/http_api/util/test_case.py
Labels: size/M, release-note-none, approved, lgtm

#9648 metrics (ticdc): fix error metrics expression
  metrics/grafana/TiCDC-Monitor-Summary.json
  metrics/grafana/ticdc.json
Labels: size/M, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9679 config(ticdc): refine the kafka config adjust and validation
  pkg/compression/compress.go
  pkg/config/large_message.go
  pkg/config/large_message_test.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/sink/codec/common/config.go
Labels: size/L, release-note-none, approved, lgtm

#9674 pulsar (ticdc): pulsar use ticdc log
  pkg/sink/pulsar/factory.go
  pkg/sink/pulsar/logger.go
Labels: size/L, release-note-none, approved, lgtm

#9668 kafka(ticdc): fix panic issue when sasl enabled by config file
  cdc/sink/codec/common/config_test.go
  pkg/config/sink.go
Labels: size/S, cherry-pick-approved, release-note-none, approved, lgtm

#9656 config(ticdc): remove unused cdc server configuration
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/db.go
  pkg/config/server_config.go
  pkg/config/sorter.go
Labels: size/L, release-note-none, approved, lgtm

#9466 kafka(ticdc): embed the claim check into the encoder to make sending message to external storage concurrently
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/pulsar_dml_sink.go
  cdc/sink/dmlsink/mq/worker.go
  cdc/sink/dmlsink/mq/worker_test.go
  metrics/grafana/ticdc.json
  pkg/config/config_test_data.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/builder/codec_test.go
  pkg/sink/codec/builder/encoder_builder.go
  pkg/sink/codec/canal/canal_encoder.go
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/common/message.go
  pkg/sink/codec/craft/craft_encoder.go
  pkg/sink/codec/encoder.go
  pkg/sink/codec/encoder_group.go
  pkg/sink/codec/maxwell/maxwell_encoder.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/kafka/claimcheck/claim_check.go
Labels: size/XXL, release-note-none, approved, lgtm

#9687 owner(ticdc): fix changefeed backoff
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9657 pulsar (ticdc): fix some pulsar sink related error
  cdc/api/v2/api_helpers.go
  cdc/model/changefeed.go
  cdc/sink/ddlsink/mq/ddlproducer/pulsar_ddl_producer.go
  cdc/sink/dmlsink/mq/dispatcher/event_router.go
  cdc/sink/dmlsink/mq/dmlproducer/pulsar_dml_producer.go
  cdc/sink/dmlsink/mq/pulsar_dml_sink.go
  pkg/config/sink.go
  pkg/sink/pulsar/config.go
  pkg/sink/pulsar/config_test.go
  pkg/sink/pulsar/factory.go
  pkg/sink/sink_type.go
Labels: size/M, release-note-none, approved, lgtm

#9700 dm: track table schema for online ddl when use binlog skip
  dm/syncer/syncer.go
Labels: size/S, release-note, area/dm, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9661 etcd, pd (ticdc): refine pdClient and etcdClient initialization
  cdc/capture/capture.go
  cdc/server/server.go
  pkg/etcd/client.go
  pkg/etcd/metrics.go
  pkg/upstream/manager.go
  pkg/upstream/manager_test.go
  pkg/upstream/upstream.go
  pkg/util/comparison.go
  pkg/util/comparison_test.go
  tests/integration_tests/http_proxies/run-proxy.go
  tests/integration_tests/http_proxies/run.sh
Labels: size/XXL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9686 sink(cdc): fix "dead dmlSink" error in sink workers
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/redo_log_worker_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9707 dm: reset optimistic sharding group keeper when syncer resume
  dm/syncer/opt_sharding_group.go
  dm/syncer/opt_sharding_group_test.go
  dm/syncer/syncer.go
Labels: size/S, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9666 sink(cdc): improve table sink advance timeout machanism
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_advancer_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9691 *(ticdc): do not print password in cdc log
  cdc/api/v1/api.go
  cdc/api/v2/changefeed.go
  cdc/model/changefeed.go
  cdc/owner/changefeed.go
  cdc/sink/ddlsink/mq/ddlproducer/pulsar_ddl_mock_producer.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/ddlsink/mq/pulsar_ddl_sink.go
  cdc/sink/dmlsink/mq/dmlproducer/pulsar_dml_producer.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/pulsar_dml_sink.go
  cdc/syncpointstore/mysql_syncpoint_store.go
  cmd/kafka-consumer/main.go
  pkg/config/consistent.go
  pkg/config/replica_config.go
  pkg/config/sink.go
  pkg/sink/codec/avro/confluent_schema_registry.go
  pkg/util/uri.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9722 proxy(ticdc): add error log for http proxy
  tests/integration_tests/http_proxies/run-proxy.go
Labels: size/S, release-note-none, approved, lgtm

#9723 sink(ticdc): fix csv update
  cdc/model/sink.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/sinkv2/eventsink/blackhole/black_hole_dml_sink.go
  cdc/sinkv2/eventsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sinkv2/eventsink/event.go
  cdc/sinkv2/eventsink/event_sink.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink.go
  cdc/sinkv2/eventsink/txn/txn_sink.go
  cdc/sinkv2/tablesink/table_sink_impl.go
  cdc/sinkv2/tablesink/table_sink_impl_test.go
  tests/integration_tests/multi_changefeed/run.sh
  tests/integration_tests/storage_csv_update/conf/changefeed.toml
  tests/integration_tests/storage_csv_update/conf/diff_config.toml
  tests/integration_tests/storage_csv_update/data/data.sql
  tests/integration_tests/storage_csv_update/data/schema.sql
  tests/integration_tests/storage_csv_update/data/update.sql
  tests/integration_tests/storage_csv_update/run.sh
Labels: size/XXL, cherry-pick-approved, release-note, approved, lgtm

#9740 kv(ticdc): Remove store connect backoff
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/processor/pipeline/puller.go
  cdc/processor/processor.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
Labels: size/L, cherry-pick-approved, release-note-none, approved, lgtm

#9688 sink(ticdc): split the updat events all at once
  cdc/api/v2/model_test.go
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/sink/ddlsink/factory/factory.go
  cdc/sink/dmlsink/blackhole/black_hole_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/event.go
  cdc/sink/dmlsink/event_sink.go
  cdc/sink/dmlsink/factory/factory.go
  cdc/sink/dmlsink/mq/dispatcher/partition/index_value.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/pulsar_dml_sink.go
  cdc/sink/dmlsink/txn/txn_dml_sink.go
  cdc/sink/tablesink/table_sink_impl.go
  cdc/sink/tablesink/table_sink_impl_test.go
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/sink.go
  pkg/sink/codec/encoder_group.go
  pkg/sink/sink_type.go
Labels: size/XL, release-note-none, approved, lgtm

#9742 sink(cdc): only check sink stuck for MQ sinks
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/sink/dmlsink/factory/factory.go
  tests/integration_tests/hang_sink_suicide/run.sh
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9744 config(ticdc): add ut for pr 9691
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/util/uri.go
  pkg/util/uri_test.go
Labels: size/L, release-note-none, approved, lgtm

#9696 kafka(ticdc): large message handle key columns cherry-pick to release-7.1
  cdc/api/v2/model.go
  cmd/kafka-consumer/main.go
  cmd/storage-consumer/main.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/config/config_test_data.go
  pkg/config/large_message.go
  pkg/config/large_message_test.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/sink/codec/builder/codec_test.go
  pkg/sink/codec/canal/canal_encoder.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_json_txn_event_encoder.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/config_test.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/craft/craft_decoder.go
  pkg/sink/codec/craft/craft_encoder.go
  pkg/sink/codec/csv/csv_decoder.go
  pkg/sink/codec/decoder.go
  pkg/sink/codec/internal/column.go
  pkg/sink/codec/internal/message_key.go
  pkg/sink/codec/maxwell/maxwell_encoder.go
  pkg/sink/codec/open/open_protocol_decoder.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/codec/open/open_protocol_message.go
  pkg/sink/codec/open/open_protocol_message_test.go
  tests/integration_tests/canal_json_handle_key_only/conf/changefeed.toml
  tests/integration_tests/canal_json_handle_key_only/conf/diff_config.toml
  tests/integration_tests/canal_json_handle_key_only/data/data.sql
  tests/integration_tests/canal_json_handle_key_only/run.sh
  tests/integration_tests/open_protocol_handle_key_only/conf/changefeed.toml
  tests/integration_tests/open_protocol_handle_key_only/conf/diff_config.toml
  tests/integration_tests/open_protocol_handle_key_only/data/data.sql
  tests/integration_tests/open_protocol_handle_key_only/run.sh
  tests/integration_tests/run_group.sh
Labels: size/XXL, cherry-pick-approved, release-note, needs-cherry-pick-release-7.1, approved, lgtm

#9735 kafka(ticdc): claim check set the timeout default to 5m to prevent stuck too long if the external storage is unavailable.
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  pkg/sink/kafka/claimcheck/claim_check.go
Labels: size/S, release-note-none, approved, lgtm

#9732 metrics (ticdc): fix lag bucket
  cdc/owner/metrics.go
  cdc/owner/metrics_test.go
Labels: size/XS, release-note-none, approved, lgtm

#9730 cmd (ticdc): add pulsar consumer
  Makefile
  cdc/sink/ddlsink/mq/ddlproducer/pulsar_ddl_producer.go
  cdc/sink/ddlsink/mq/mq_ddl_sink.go
  cdc/sink/dmlsink/mq/dispatcher/event_router.go
  cdc/sink/dmlsink/mq/pulsar_dml_sink.go
  cdc/sink/util/helper.go
  cmd/pulsar-consumer/main.go
Labels: size/XXL, release-note-none, approved, lgtm

#9759 sink(ticdc): fix csv update
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/redo_log_worker_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/sink/dmlsink/blackhole/black_hole_dml_sink.go
  tests/integration_tests/run_group.sh
  tests/integration_tests/storage_csv_update/conf/changefeed.toml
  tests/integration_tests/storage_csv_update/conf/diff_config.toml
  tests/integration_tests/storage_csv_update/data/data.sql
  tests/integration_tests/storage_csv_update/data/schema.sql
  tests/integration_tests/storage_csv_update/data/update.sql
  tests/integration_tests/storage_csv_update/run.sh
Labels: size/XL, release-note-none, approved, lgtm

#9746 server(ticdc): fix panic issue if capture is not initialized
  cdc/server/server.go
  pkg/cmd/server/server.go
Labels: size/XS, release-note-none, approved, lgtm

#9713 openAPI (ticdc): fix openapi use old addrs to create pdClient
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9761 kafka(ticdc): event router simplify to make it easier
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/ddlsink/mq/mq_ddl_sink.go
  cdc/sink/ddlsink/mq/mq_ddl_sink_test.go
  cdc/sink/ddlsink/mq/pulsar_ddl_sink.go
  cdc/sink/dmlsink/mq/dispatcher/event_router.go
  cdc/sink/dmlsink/mq/dispatcher/event_router_test.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/pulsar_dml_sink.go
  cmd/kafka-consumer/main.go
  cmd/pulsar-consumer/main.go
Labels: size/XL, release-note-none, approved, lgtm

#9701 ddl(ticdc): async exec add index ddl
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink_test.go
  pkg/applier/redo_test.go
Labels: size/L, release-note, approved, lgtm

#9753 sink(ticdc): fix csv update
  cdc/model/sink.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/redo_log_worker_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/sink/dmlsink/blackhole/black_hole_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/event.go
  cdc/sink/dmlsink/event_sink.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/txn/txn_dml_sink.go
  cdc/sink/tablesink/table_sink_impl.go
  cdc/sink/tablesink/table_sink_impl_test.go
  tests/integration_tests/multi_changefeed/run.sh
  tests/integration_tests/run_group.sh
  tests/integration_tests/storage_csv_update/conf/changefeed.toml
  tests/integration_tests/storage_csv_update/conf/diff_config.toml
  tests/integration_tests/storage_csv_update/data/data.sql
  tests/integration_tests/storage_csv_update/data/schema.sql
  tests/integration_tests/storage_csv_update/data/update.sql
  tests/integration_tests/storage_csv_update/run.sh
Labels: size/XXL, cherry-pick-approved, release-note, approved, lgtm

#9770 pulsar (ticdc): fix pulsar sink related errors
  cdc/sink/dmlsink/mq/manager/pulsar_manager.go
  cmd/pulsar-consumer/main.go
  pkg/config/sink.go
Labels: size/M, release-note-none, ok-to-test, approved, lgtm

#9772 sink(cdc): fix the check about resolvedTs and checkpointTs
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9755 kafka(ticdc): event router allow hard code topics and set the schema optional in the topic expression
  cdc/sink/dmlsink/mq/dispatcher/event_router.go
  cdc/sink/dmlsink/mq/dispatcher/event_router_test.go
  cdc/sink/dmlsink/mq/dispatcher/topic/dispatcher.go
  cdc/sink/dmlsink/mq/dispatcher/topic/dispatcher_test.go
  cdc/sink/dmlsink/mq/dispatcher/topic/expression.go
  cdc/sink/dmlsink/mq/dispatcher/topic/expression_test.go
  tests/integration_tests/multi_topics/conf/changefeed.toml
  tests/integration_tests/multi_topics/data/step1.sql
  tests/integration_tests/multi_topics/run.sh
Labels: size/L, release-note-none, ok-to-test, approved, lgtm

#9752 pkg/election(ticdc): implement gorm based election
  errors.toml
  pkg/election/elector.go
  pkg/election/elector_test.go
  pkg/election/mock/storage_mock.go
  pkg/election/storage.go
  pkg/election/storage_orm.go
  pkg/election/storage_orm_test.go
  pkg/election/storage_sql.go
  pkg/election/storage_sql_test.go
  pkg/errors/cdc_errors.go
Labels: size/XL, release-note-none, area/ticdc, type/feature, ok-to-test, approved, lgtm

#9786 server(ticdc): use TiDB gcTuner in a more reasonable way
  cdc/server/server.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
Labels: size/M, release-note, needs-cherry-pick-release-7.1, approved, lgtm

#9785 sink(ticdc): fix csv delimiter
  pkg/config/sink.go
  pkg/config/sink_test.go
Labels: size/S, contribution, release-note, ok-to-test, approved, lgtm

#9781 tests(ticdc): add utf8mb4_0900_ai_ci tests
  scripts/download-integration-test-binaries.sh
  tests/integration_tests/new_ci_collation/data/test1.sql
  tests/integration_tests/new_ci_collation/data/test2.sql
Labels: first-time-contributor, size/M, release-note-none, approved, lgtm

#9670 cdc: support remove and add partitioning
  cdc/entry/schema/snapshot.go
  cdc/owner/ddl_manager.go
  pkg/filter/filter.go
  pkg/sink/codec/canal/canal_entry.go
  tests/integration_tests/partition_table/conf/diff_config.toml
  tests/integration_tests/partition_table/data/prepare.sql
Labels: size/M, release-note, approved, lgtm

#9798 sink(cdc): fix the check about resolvedTs and checkpointTs (#9772)
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
Labels: size/L, release-note-none, ok-to-test, approved, lgtm

#9799 kvclient(cdc): fix an out of range panic in client
  cdc/kv/client.go
Labels: size/XS, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9802 kvclient(cdc): fix an out of range panic in client (#9799)
  cdc/kv/client.go
Labels: size/XS, release-note-none, approved, lgtm

#9729 test(ticdc): add csv update test
  tests/integration_tests/run_group.sh
  tests/integration_tests/storage_csv_update/conf/changefeed.toml
  tests/integration_tests/storage_csv_update/conf/diff_config.toml
  tests/integration_tests/storage_csv_update/data/data.sql
  tests/integration_tests/storage_csv_update/data/schema.sql
  tests/integration_tests/storage_csv_update/data/update.sql
  tests/integration_tests/storage_csv_update/run.sh
Labels: size/XL, release-note, needs-cherry-pick-release-7.1, ok-to-test, approved, lgtm

#9779 processor(ticdc): decouple processor from reactor
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
Labels: size/XL, release-note-none, approved, lgtm

#9728 metrics, pulsar (ticdc): add pulsar metrics panel
  metrics/grafana/ticdc.json
Labels: size/XXL, contribution, release-note-none, ok-to-test, approved, lgtm

#9778 kafka(ticdc): open-protocol do not build previous messages to fix callback mismatch
  metrics/grafana/ticdc.json
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/open/open_protocol_decoder.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/codec/open/open_protocol_message.go
  pkg/sink/kafka/claimcheck/claim_check.go
  pkg/sink/kafka/cluster_admin_client_mock_impl.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/options_test.go
  tests/integration_tests/open_protocol_claim_check/data/data.sql
  tests/integration_tests/open_protocol_claim_check/run.sh
Labels: size/XL, release-note-none, ok-to-test, approved, lgtm

#9789 dm: sync partition DDL even if upstream schema is not equal in optimistic mode
  dm/master/shardddl/optimist_test.go
  dm/pkg/shardddl/optimism/lock.go
  dm/pkg/shardddl/optimism/lock_test.go
  dm/tests/shardddl2/run.sh
Labels: size/M, contribution, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, needs-ok-to-test, approved, lgtm

#9797 kvclient(cdc): make TiCDC available during rolling upgrade
  cdc/kv/client_test.go
  cdc/kv/shared_client.go
  cdc/kv/shared_client_test.go
  cdc/kv/shared_region_worker.go
  cdc/kv/shared_stream.go
  cdc/kv/sharedconn/conn_and_client.go
  cdc/kv/sharedconn/conn_and_client_test.go
  cdc/kv/sharedconn/main_test.go
  cdc/processor/processor.go
  cdc/processor/sourcemanager/manager.go
  cdc/puller/ddl_puller.go
Labels: size/XXL, contribution, release-note-none, ok-to-test, approved, lgtm

#9790 ticdc: update go mod tidb v7.4
  cdc/owner/schema_test.go
  cdc/redo/writer/file/file_test.go
  dm/checker/checker.go
  dm/pkg/parser/common.go
  dm/pkg/storage/utils_test.go
  go.mod
  go.sum
Labels: size/L, release-note-none, approved, lgtm

#9771 kv(ticdc): remove backoff from newStream func
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/kv/shared_client.go
  cdc/kv/shared_client_test.go
  cdc/processor/processor.go
  cdc/processor/sourcemanager/manager.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9738 metadata(cdc): add sql implementation (part 1)
  cdcv2/metadata/sql/client.go
  cdcv2/metadata/sql/client_orm.go
  cdcv2/metadata/sql/client_test.go
  cdcv2/metadata/sql/main_test.go
  cdcv2/metadata/sql/model.go
  cdcv2/metadata/sql/tables.go
  cdcv2/metadata/sql/tables_test.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/errors/engine_errors.go
Labels: size/XXL, release-note, ok-to-test, approved, lgtm

#9816 puller(cdc): enlarge table resolved ts buffer size
  cdc/puller/multiplexing_puller.go
Labels: size/XS, release-note-none, approved, lgtm

#9811 kvclient(cdc): remove some noicy logs in the module
  cdc/kv/region_state.go
  cdc/kv/region_worker.go
  cdc/kv/shared_client.go
  cdc/kv/shared_region_worker.go
  cdc/kv/shared_stream.go
Labels: size/L, release-note-none, approved, lgtm

#9820 Makefile: bump version to v7.5.0-master
  Makefile
Labels: size/S, release-note-none, approved, lgtm
