Repository pingcap/tiflow, pull requests merged in 2023-05, with the labels that each got.

#8464 gc (ticdc): optimize the algorithm calculating gc safepoint
  cdc/api/v2/changefeed_test.go
  cdc/model/changefeed_test.go
  cdc/owner/changefeed.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/errors/helper.go
  pkg/errors/helper_test.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_manager_test.go
  tests/integration_tests/changefeed_fast_fail/run.sh
  tests/integration_tests/changefeed_resume_with_checkpoint_ts/run.sh
  tests/integration_tests/multi_tables_ddl/run.sh
  tests/integration_tests/multi_tables_ddl_v2/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note

#8852 canaljson(ticdc): only output updated column for canal json protocol
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_json_txn_event_encoder.go
  pkg/sink/codec/encoder.go
  pkg/sink/codec/open/open_protocol_message.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8895 tests(ticdc): fix broken storage tests
  tests/integration_tests/csv_storage_multi_tables_ddl/run.sh
  tests/integration_tests/lossy_ddl/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note, needs-cherry-pick-release-6.5

#8860 kvclient(cdc): remove rate limiter for scanning and error handling
  Makefile
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/kv/token_region.go
  cdc/kv/token_region_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8884 capture (ticdc): fix processor exit unexpectedly when some pd node fail
  cdc/capture/capture.go
  cdc/capture/election.go
  tests/integration_tests/availability/owner.sh
Labels: status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8813 Etcd (ticdc, dm):add AutoSyncInterval for Etcd client
  cdc/server/server.go
  dm/pkg/etcdutil/etcdutil.go
Labels: status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8893 pkg/sink(ticdc): iterate all Kafka configs to support KOP
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/v2/admin.go
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8912 tests(ticdc): add exchange partition test to lossy DDL case
  tests/integration_tests/lossy_ddl/data/prepare.sql
  tests/integration_tests/lossy_ddl/run.sh
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#8872 api(ticdc): add changefeed status api
  cdc/api/v2/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  cdc/model/errors.go
  cdc/model/http_model_test.go
  cdc/model/owner.go
  cdc/owner/changefeed.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8881 sink(ticdc): change the directory of storage sink only when ddl event occurs
  Makefile
  cdc/owner/schema.go
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink_test.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink_test.go
  cdc/sink/dmlsink/cloudstorage/dml_worker.go
  cdc/sink/dmlsink/cloudstorage/dml_worker_test.go
  cmd/storage-consumer/main.go
  pkg/sink/cloudstorage/main_test.go
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_key.go
  pkg/sink/cloudstorage/path_key_test.go
  pkg/sink/cloudstorage/path_test.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/cloudstorage/table_definition_test.go
  tests/integration_tests/canal_json_storage_basic/run.sh
  tests/integration_tests/canal_json_storage_partition_table/data/prepare.sql
  tests/integration_tests/canal_json_storage_partition_table/run.sh
  tests/integration_tests/csv_storage_basic/run.sh
  tests/integration_tests/csv_storage_multi_tables_ddl/run.sh
  tests/integration_tests/csv_storage_partition_table/data/prepare.sql
  tests/integration_tests/csv_storage_partition_table/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#8850 codec(ticdc): add avro decoder
  cmd/kafka-consumer/main.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/avro/avro_test_data.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/decoder_test.go
  pkg/sink/codec/avro/schema_registry.go
  pkg/sink/codec/avro/schema_registry_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8855 sink(ticdc): move changefeed uri parameter to config file
  cdc/api/v2/model.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  go.mod
  go.sum
  pkg/config/config_test_data.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/cloudstorage/config_test.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/config_test.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/sarama_test.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/config_test.go
  scripts/check-diff-line-width.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8918 sink(ticdc): add index config to storage sink
  cdc/api/v2/model.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink_test.go
  cdc/sink/dmlsink/cloudstorage/dml_worker_test.go
  cmd/storage-consumer/main.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/util/helper_test.go
  pkg/config/sink.go
  pkg/config/sink_test.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/cloudstorage/config_test.go
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_key.go
  pkg/sink/cloudstorage/path_key_test.go
  pkg/sink/cloudstorage/path_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8926 tests(ticdc): add reorganize partition test to lossy DDL case
  tests/integration_tests/lossy_ddl/data/prepare.sql
  tests/integration_tests/lossy_ddl/run.sh
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none

#8873 pkg/config(ticdc): Support InsecureSkipVerify option when using tls
  cdc/api/v2/model.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/config/sink.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/sarama.go
  pkg/sink/kafka/v2/factory.go
  tests/integration_tests/cli/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5

#8908 p2p(ticdc): add keep alive configuration for p2p server
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/messages.go
  pkg/p2p/server.go
  pkg/p2p/server_wrapper.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8917 integrity(ticdc): add integrity package and move some files, reorder columns at the mounter
  cdc/api/v2/model.go
  cdc/entry/mounter.go
  cdc/entry/mounter_group.go
  cdc/entry/mounter_test.go
  cdc/model/sink.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/integrity/checksum.go
  pkg/integrity/integrity.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/common/config_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-7.1

#8923 p2p(ticdc): remove message peer when capture is removed
  cdc/capture/capture.go
  pkg/p2p/server.go
  pkg/p2p/server_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8933 deployments(ticdc): install wget and add cache
  deployments/ticdc/docker/integration-test.Dockerfile
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#8955 schema, sink(ticdc): fix exchange partition
  cdc/entry/schema/snapshot.go
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  tests/integration_tests/canal_json_storage_partition_table/data/prepare.sql
  tests/integration_tests/csv_storage_partition_table/data/prepare.sql
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8960 mounter(ticdc): fix extend column info order to match the columns info
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/model/schema_storage.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/schema_registry.go
  scripts/check-diff-line-width.sh
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8949 sink(cdc): handle sink errors more fast and light
  cdc/model/codec/codec.go
  cdc/model/sink.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_sink.go
  cdc/owner/ddl_sink_test.go
  cdc/owner/owner_test.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/sink/tablesink/table_sink.go
  cdc/sink/tablesink/table_sink_impl.go
  pkg/errors/helper.go
  pkg/errors/helper_test.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/mysql/config.go
  pkg/sink/observer/observer.go
  pkg/sink/observer/tidb.go
  pkg/sink/observer/tidb_test.go
  tests/integration_tests/changefeed_error/run.sh
  tests/integration_tests/ddl_only_block_related_table/run.sh
  tests/integration_tests/ddl_reentrant/run.sh
  tests/integration_tests/kafka_sink_error_resume/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8981 makefile, cmd(ticdc): log version in consumer
  Makefile
  cmd/kafka-consumer/main.go
  cmd/storage-consumer/main.go
  deployments/ticdc/docker/kafka-consumer.Dockerfile
  deployments/ticdc/docker/storage-consumer.Dockerfile
Labels: status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8885 integration-test (ticdc): providing option of downloading public accessible version of binaries for integration test
  deployments/ticdc/docker-compose/docker-compose-kafka-integration.yml
  deployments/ticdc/docker-compose/docker-compose-mysql-integration.yml
  deployments/ticdc/docker-compose/docker-compose-storage-integration.yml
  deployments/ticdc/docker/integration-test.Dockerfile
  scripts/download-integration-test-binaries.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8989 (sink/cdc): fix stop table dead lock introduced in #8949
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/tablepb/table.go
  cdc/sink/tablesink/progress_tracker.go
  cdc/sink/tablesink/progress_tracker_test.go
  cdc/sink/tablesink/state/state.go
  cdc/sink/tablesink/table_sink.go
  cdc/sink/tablesink/table_sink_impl.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8964 owner, redo(ticdc): decouple globalResolvedTs and globalBarrierTs
  Makefile
  cdc/model/owner.go
  cdc/owner/changefeed.go
  cdc/owner/ddl_manager.go
  cdc/owner/ddl_manager_test.go
  cdc/redo/manager.go
  cdc/redo/meta_manager.go
  tests/integration_tests/consistent_replicate_ddl/conf/diff_config.toml
  tests/integration_tests/consistent_replicate_ddl/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8983 (processor/cdc): report module internal warnings
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  cdc/entry/mounter_group.go
  cdc/model/changefeed.go
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/owner/changefeed.go
  cdc/owner/ddl_sink.go
  cdc/owner/feed_state_manager.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_log_advancer_test.go
  cdc/processor/sourcemanager/manager.go
  cdc/puller/ddl_puller.go
  cdc/redo/manager.go
  cdc/redo/meta_manager.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  pkg/util/runnable.go
  pkg/util/time.go
  tests/integration_tests/_utils/check_changefeed_status
  tests/integration_tests/changefeed_error/run.sh
  tests/integration_tests/kafka_sink_error_resume/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8752 chore: migrate to new prow reviewing
  OWNERS
Labels: status/LGT2, status/can-merge, first-time-contributor, size/M, release-note-none

#8982 (sorter/cdc): disable block cache by default
  cdc/processor/sourcemanager/engine/pebble/db.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
  pkg/config/sorter.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#9011 sink(ticdc): set default value of DateSeparator to day(#8998)
  cdc/api/v2/model_test.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink_test.go
  cdc/sink/dmlsink/cloudstorage/dml_worker_test.go
  pkg/cmd/util/helper_test.go
  pkg/config/replica_config.go
  pkg/sink/cloudstorage/config_test.go
  pkg/sink/cloudstorage/path_test.go
  tests/integration_tests/api_v2/cases.go
Labels: status/LGT1, status/can-merge, size/S, cherry-pick-approved, require-LGT1, release-note

#9010 (sink/cdc): fix some bugs introduced by #8949
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_advancer.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/event_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink_test.go
  cdc/sink/dmlsink/txn/txn_dml_sink.go
  cdc/sink/tablesink/progress_tracker.go
  cdc/sink/tablesink/table_sink.go
  cdc/sink/tablesink/table_sink_impl.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
  tests/integration_tests/sink_hang/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8990 test(ticdc): add more unit test to cover checksum functionality
  cdc/entry/mounter_test.go
  go.mod
  go.sum
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/avro/decoder_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8930 scheduler (ticdc): add region number limit for table span
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/keyspan/reconciler.go
  cdc/scheduler/internal/v3/keyspan/splitter_region_count.go
  cdc/scheduler/internal/v3/keyspan/splitter_write.go
  cdc/scheduler/internal/v3/keyspan/splitter_write_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#9024 sorter(cdc): add config cache-size
  cdc/processor/sourcemanager/engine/factory/pebble.go
  cdc/processor/sourcemanager/engine/pebble/db.go
  cdc/processor/sourcemanager/engine/pebble/db_test.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter_test.go
  cdc/server/server.go
  pkg/cmd/server/server.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
  pkg/config/sorter.go
  tests/integration_tests/_utils/run_cdc_server
  tests/integration_tests/consistent_replicate_storage_file_large_value/conf/changefeed.toml
  tests/integration_tests/consistent_replicate_storage_file_large_value/conf/diff_config.toml
  tests/integration_tests/consistent_replicate_storage_file_large_value/conf/workload
  tests/integration_tests/consistent_replicate_storage_file_large_value/data/prepare.sql
  tests/integration_tests/consistent_replicate_storage_file_large_value/run.sh
  tests/integration_tests/run_group.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8998 sink(ticdc): set default value of DateSeparator to day
  cdc/api/v2/model_test.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink_test.go
  cdc/sink/dmlsink/cloudstorage/dml_worker_test.go
  pkg/cmd/util/helper_test.go
  pkg/config/replica_config.go
  pkg/sink/cloudstorage/config_test.go
  pkg/sink/cloudstorage/path_test.go
  tests/integration_tests/api_v2/cases.go
Labels: status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#9026 * (ticdc): bump sarama to v1.38.1 to avoid panic
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8938 pkg/sink(ticdc): add oauth support for sarama Kafka sink
  cdc/api/v2/model.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer_test.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  docs/design/2023-03-15-ticdc-storage-sink.md
  docs/package-lock.json
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  go.mod
  pkg/config/sink.go
  pkg/security/sasl.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/oauth2_token_provider.go
  pkg/sink/kafka/oauth2_token_provider_test.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/sarama.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/kafka/sarama_factory_test.go
  pkg/sink/kafka/sarama_test.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/factory_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#9046 kafka(ticdc): use context to close the mq dml sink and the metrics collector
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/metrics_collector.go
  pkg/sink/kafka/v2/metrics_collector.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#9006 metrics(ticdc):update ticdc alert rule
  metrics/alertmanager/ticdc.rules.yml
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/S, release-note-none

#9000 dm: add meta binlog precheck
  dm/checker/check_test.go
  dm/checker/checker.go
  dm/config/checking_item.go
  dm/config/checking_item_test.go
  dm/master/openapi_controller.go
  dm/master/server.go
  dm/pkg/checker/binlog.go
  dm/tests/incremental_mode/run.sh
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/run.sh
  engine/jobmaster/dm/config/config.go
  engine/jobmaster/dm/config/config_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note, area/dm

#9028 api(ticdc): persist ignore-ineligible-table parameter value
  cdc/api/v2/model.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#8836 pkg/config(ticdc): hide fields that are not required for specific protocols
  cdc/api/v1/validator_test.go
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/entry/schema_test_helper.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/model/http_model.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_sink.go
  cdc/owner/owner_test.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/sink/ddlsink/factory/factory.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink_test.go
  cdc/sink/dmlsink/cloudstorage/dml_worker_test.go
  cdc/sink/dmlsink/factory/factory.go
  cdc/sink/dmlsink/mq/dispatcher/event_router.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/validator/validator.go
  cdc/sink/validator/validator_test.go
  cmd/kafka-consumer/main.go
  cmd/storage-consumer/main.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_changefeed_update_test.go
  pkg/cmd/util/changefeed_storage_sink.toml
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/config/sink_test.go
  pkg/migrate/migrate_test.go
  pkg/orchestrator/reactor_state_test.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/cloudstorage/config_test.go
  pkg/sink/cloudstorage/path_test.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/config_test.go
  pkg/util/pointer.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/api_v2/model.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#9040 sink(ticdc): add table default value definition for storage sink
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/cloudstorage/table_definition_test.go
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#9074 sink(cdc): close MemoryQuota to stop SinkManager correctly
  cdc/processor/memquota/mem_quota.go
  cdc/processor/memquota/mem_quota_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_log_advancer_test.go
  cdc/processor/sinkmanager/redo_log_worker_test.go
  cdc/processor/sinkmanager/table_sink_advancer_test.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#9068 codec(ticdc): fix avro decode update event incorrectly and do not verify empty checksum
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/decoder_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#9078 cdc: region worker should handle stale events correctly
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8992 owner(ticdc): fix exchange partition ddl
  cdc/entry/schema/snapshot.go
  cdc/entry/schema_storage.go
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/owner/schema.go
  tests/integration_tests/canal_json_storage_partition_table/data/prepare.sql
  tests/integration_tests/csv_storage_partition_table/data/prepare.sql
  tests/integration_tests/ddl_reentrant/run.sh
  tests/integration_tests/partition_table/data/prepare.sql
Labels: status/LGT2, status/can-merge, size/XL, release-note

#9085 processor, scheduler(ticdc): report resolvedTs when removing table
  cdc/processor/processor.go
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/internal/v3/replication/replication_set_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#9091 sink(cdc): clear memquota when restart a table sink
  cdc/processor/memquota/mem_quota.go
  cdc/processor/memquota/mem_quota_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/table_sink_worker.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#9039 tests(ticdc): add more test for `lossy_ddl`
  tests/integration_tests/lossy_ddl/data/prepare.sql
  tests/integration_tests/lossy_ddl/run.sh
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#9021 owner, scheduler(ticdc): handle barrier of resolvedTs and checkpointTs in scheduler
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_manager.go
  cdc/owner/ddl_manager_test.go
  cdc/owner/metrics.go
  cdc/scheduler/internal/scheduler.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_bench_test.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/schedulepb/barrier.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#9090 config(ticdc): fix deafult setting of DateSeparator
  cdc/api/v2/model_test.go
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/sink/cloudstorage/config_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#9060 sink(ticdc): Optimize the performance when getting the metadata of Kafka topics
  cdc/sink/ddlsink/mq/mq_ddl_sink.go
  cdc/sink/dmlsink/mq/manager/kafka_manager.go
  cdc/sink/dmlsink/mq/manager/kafka_manager_test.go
  cdc/sink/dmlsink/mq/manager/manager.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/cluster_admin_client_mock_impl.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/v2/admin.go
  pkg/sink/kafka/v2/admin_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#9043 api(ticdc): open api v2 support namespace
  cdc/api/v2/api_helpers.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/processor.go
  cdc/api/v2/unsafe.go
  cdc/model/changefeed.go
  cdc/sink/validator/validator.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  tests/integration_tests/api_v2/cases.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8913 sink(ticdc): remove buffer pool in storage sink worker
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/dml_worker.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1

#8931 tests(ticdc): add avro integration test to cover avro functionality
  Makefile
  deployments/ticdc/docker/integration-test.Dockerfile
  pkg/sink/codec/avro/schema_registry.go
  scripts/download-integration-test-binaries.sh
  tests/integration_tests/_utils/run_kafka_consumer
  tests/integration_tests/avro_basic/conf/changefeed.toml
  tests/integration_tests/avro_basic/conf/diff_config.toml
  tests/integration_tests/avro_basic/data/data.sql
  tests/integration_tests/avro_basic/run.sh
  tests/integration_tests/run_group.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none
