Repository pingcap/tiflow, pull requests merged in 2023-02, with the labels that each got.

#8119 apiv2(ticdc): implement the list processors
  cdc/api/v2/api.go
  cdc/api/v2/model.go
  cdc/api/v2/processor.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8125 syntax(DM): fix syntax error
  dm/config/source_config.go
  dm/config/task.go
  dm/master/openapi_view_test.go
  dm/master/scheduler/scheduler.go
  dm/master/scheduler/scheduler_test.go
  dm/master/scheduler/worker.go
  dm/master/server.go
  dm/master/server_test.go
  dm/openapi/spec/dm.yaml
  dm/pkg/ha/bound.go
  dm/pkg/ha/doc.go
  dm/proto/dmworker.proto
  dm/tests/dmctl_basic/check_list/start_relay.sh
  dm/tests/dmctl_basic/check_list/stop_relay.sh
  dm/tests/lightning_load_task/run.sh
  dm/tests/openapi/run.sh
  dm/tests/validator_basic/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8138 kafka(cdc): add context as the first parameter to some methods
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/sink/mq/manager/kafka_manager.go
  cdc/sink/mq/manager/kafka_manager_test.go
  cdc/sink/mq/manager/manager.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink.go
  cdc/sinkv2/util/helper.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8151 deployments(ticdc): fix broken links
  deployments/ticdc/docker-compose/docker-compose-kafka-integration.yml
Labels: component/test, status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none, area/ticdc

#7644 syncer(dm): fix unstable multi-schema change tests
  dm/tests/gbk/run.sh
Labels: status/LGT2, status/can-merge, size/L

#8111 apiv2(ticdc): implmenet the GET changefeed
  cdc/api/v2/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/model.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8155 kafka(ticdc): remove sarama keyword from error and methods to make the code more general
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_test.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  cdc/sink/mq/producer/kafka/metrics.go
  cdc/sink/sink.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/util/helper.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/sink/kafka/v2/main_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8137 observer(ticdc): collect certain quantile metrics
  pkg/sink/observer/tidb.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#8165 kafka(ticdc): simplify the client interface by remove partition and topic methods
  cdc/sink/mq/manager/kafka_manager.go
  cdc/sink/mq/manager/kafka_manager_test.go
  cdc/sink/mq/mq.go
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/util/helper.go
  pkg/sink/kafka/client.go
  pkg/sink/kafka/client_mock_impl.go
  pkg/sink/kafka/cluster_admin_client_mock_impl.go
  pkg/sink/kafka/v2/kafka-go-client.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8154 pkg/sink(ticdc): make require acks configuration configurable
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/sarama.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note, area/ticdc

#8163 pkg/actor(ticdc): remove dead code
  cdc/server/metrics.go
  pkg/actor/actor.go
  pkg/actor/actor_test.go
  pkg/actor/doc.go
  pkg/actor/message/message.go
  pkg/actor/message/message_test.go
  pkg/actor/metrics.go
  pkg/actor/system.go
  pkg/actor/system_test.go
  pkg/actor/testing.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#8156 sinkv2(cdc): fix panics about table scheduling or blackhole sink
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sourcemanager/engine/memory/event_sorter.go
  cdc/processor/sourcemanager/engine/memory/event_sorter_test.go
  cdc/processor/sourcemanager/engine/metrics.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter_test.go
  cdc/redo/manager.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5

#8169 mq(ticdc): Add context for producer
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  pkg/sink/kafka/client.go
  pkg/sink/kafka/v2/kafka-go-client.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8176 pkg/config(ticdc): remove useless configs
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  pkg/config/server_config_test.go
  pkg/config/sorter.go
  pkg/config/table_actor.go
  tests/integration_tests/server_config_compatibility/conf/server.toml
  tests/integration_tests/server_config_compatibility/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8167 sink(ticdc): Optimize error handling method for storage sink
  cdc/sinkv2/eventsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sinkv2/eventsink/cloudstorage/dml_worker.go
  cdc/sinkv2/eventsink/cloudstorage/dml_worker_test.go
  cdc/sinkv2/eventsink/cloudstorage/dml_writer.go
  cdc/sinkv2/eventsink/cloudstorage/encoding_worker.go
  cdc/sinkv2/eventsink/cloudstorage/encoding_worker_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-6.5

#8126 *(all): update dependencies on tidb and pd.
  Makefile
  cdc/api/v2/changefeed_test.go
  cdc/entry/schema/snapshot.go
  cdc/entry/schema/snapshot_test.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/owner/schema_test.go
  cdc/server/server_test.go
  cdc/sink/codec/maxwell/maxwell_message.go
  dm/master/election_test.go
  dm/master/etcd_test.go
  dm/master/openapi_view_test.go
  dm/master/server_test.go
  dm/master/workerrpc/workerrpc_test.go
  dm/pkg/election/election_test.go
  dm/pkg/etcdutil/etcdutil_test.go
  dm/pkg/retry/errors.go
  dm/tests/all_mode/run.sh
  dm/tests/check_task/run.sh
  dm/tests/full_mode/run.sh
  dm/tests/handle_error/run.sh
  dm/tests/lightning_mode/run.sh
  dm/tests/many_tables/run.sh
  dm/tests/print_status/run.sh
  dm/tests/shardddl1_1/run.sh
  dm/tests/sync_collation/run.sh
  dm/tests/tracker_ignored_ddl/run.sh
  dm/unit/unit_test.go
  dm/worker/server_test.go
  dm/worker/source_worker_test.go
  engine/test/integration_tests/dm_collation/run.sh
  engine/test/integration_tests/dm_full_mode/run.sh
  go.mod
  go.sum
  pkg/etcd/etcd.go
  pkg/p2p/message_router_test.go
  pkg/pdutil/utils.go
  pkg/pdutil/utils_test.go
  pkg/txnutil/gc/testing.go
  pkg/version/check_test.go
  tests/integration_tests/multi_source/main.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note

#8179 *(ticdc): fix some major problems about pull-based-sink
  cdc/entry/metrics.go
  cdc/entry/mounter_group.go
  cdc/entry/schema_storage.go
  cdc/processor/memquota/mem_quota.go
  cdc/processor/memquota/mem_quota_test.go
  cdc/processor/memquota/metrics.go
  cdc/processor/metrics.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/metrics.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/tasks.go
  cdc/processor/sourcemanager/engine/metrics.go
  cdc/processor/sourcemanager/engine/mounted_iter.go
  cdc/processor/sourcemanager/engine/mounted_iter_test.go
  cdc/processor/sourcemanager/manager.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, needs-cherry-pick-release-6.5

#8192 dep(*): update tidb to include a change
  dm/master/scheduler/scheduler_test.go
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8193 dm: fix checkpoint not updated when last event is ddl and skipped
  dm/syncer/ddl.go
  dm/syncer/syncer.go
  dm/tests/all_mode/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note, area/dm, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8191 sinkv2(ticdc): add max-multi-update-row config in mysql sink
  cdc/sinkv2/eventsink/txn/mysql/mysql.go
  cdc/sinkv2/eventsink/txn/mysql/mysql_test.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/config_test.go
  pkg/sqlmodel/row_change.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#8181 redo(ticdc): set default timeout for accessing external storage to 15 minutes
  cdc/redo/writer/file.go
  cdc/redo/writer/writer.go
  engine/pkg/externalresource/internal/s3/storage_factory.go
  go.mod
  pkg/redo/config.go
  pkg/util/external_storage.go
Labels: status/LGT2, status/can-merge, size/L, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8183 kafka(ticdc): add metrics collector interface.
  cdc/sink/mq/producer/kafka/kafka_test.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer.go
  cdc/sinkv2/metrics/mq/metrics.go
  pkg/sink/kafka/client.go
  pkg/sink/kafka/client_mock_impl.go
  pkg/sink/kafka/metrics.go
  pkg/sink/kafka/metrics_collector.go
  pkg/sink/kafka/v2/kafka-go-client.go
  pkg/sink/kafka/v2/metrics_collector.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8180 dmctl: fix error and add test for `binlog-schema delete`
  dm/ctl/master/source_table_schema.go
  dm/tests/sequence_sharding_optimistic/run.sh
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8196 sink(ticdc): do not return error when close the sink
  cdc/owner/ddl_sink.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/sink/validator.go
  cdc/sinkv2/ddlsink/blackhole/black_hole_ddl_sink.go
  cdc/sinkv2/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sinkv2/ddlsink/ddl_sink.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink.go
  cdc/sinkv2/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sinkv2/ddlsink/mysql/mysql_ddl_sink_test.go
  cdc/sinkv2/eventsink/blackhole/black_hole_dml_sink.go
  cdc/sinkv2/eventsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sinkv2/eventsink/cloudstorage/cloud_storage_dml_sink_test.go
  cdc/sinkv2/eventsink/event_sink.go
  cdc/sinkv2/eventsink/factory/factory.go
  cdc/sinkv2/eventsink/factory/factory_test.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink_test.go
  cdc/sinkv2/eventsink/txn/txn_sink.go
  cdc/sinkv2/eventsink/txn/txn_sink_test.go
  cdc/sinkv2/tablesink/table_sink_impl_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8200 *: add test case for resource control feature
  tests/integration_tests/resourcecontrol/conf/diff_config.toml
  tests/integration_tests/resourcecontrol/data/prepare.sql
  tests/integration_tests/resourcecontrol/run.sh
Labels: status/LGT2, status/can-merge, first-time-contributor, size/M, release-note-none, area/ticdc

#8217 dep(*): update tidb dependency
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/M, release-note

#8182 apiv2(ticdc): switch processors cli library to API V2
  cdc/api/v2/processor.go
  pkg/api/v2/api_client.go
  pkg/api/v2/mock/processor_mock.go
  pkg/api/v2/processor.go
  pkg/cmd/cli/cli_capture_list_test.go
  pkg/cmd/cli/cli_processor_list.go
  pkg/cmd/cli/cli_processor_list_test.go
  pkg/cmd/cli/cli_processor_query.go
  pkg/cmd/cli/cli_processor_query_test.go
  scripts/generate-mock.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8218 dep(*): update tidb dependency (#8217)
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/M, cherry-pick-approved, release-note, cherry-pick-approved（已编辑）

#8219 sinkV2(ticdc): sink manager close the sink factory at the last
  cdc/processor/sinkmanager/manager.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#8228 kafka(ticdc): reset the admin client to fix broken pipe
  pkg/sink/kafka/admin.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.6

#8224 sink(ticdc): remove kafka sinkv1 and blackhole sinkv1
  cdc/owner/ddl_sink.go
  cdc/owner/ddl_sink_test.go
  cdc/server/metrics.go
  cdc/sink/black_hole.go
  cdc/sink/black_hole_test.go
  cdc/sink/flowcontrol/flow_control.go
  cdc/sink/flowcontrol/flow_control_test.go
  cdc/sink/flowcontrol/main_test.go
  cdc/sink/flowcontrol/table_memory_quota.go
  cdc/sink/mq/main_test.go
  cdc/sink/mq/mq.go
  cdc/sink/mq/mq_flush_worker.go
  cdc/sink/mq/mq_flush_worker_test.go
  cdc/sink/mq/mq_test.go
  cdc/sink/mq/producer/kafka/kafka.go
  cdc/sink/mq/producer/kafka/kafka_test.go
  cdc/sink/mq/producer/kafka/metrics.go
  cdc/sink/mq/producer/mq_producer.go
  cdc/sink/sink.go
  cdc/sink/table_sink.go
  cdc/sink/validator.go
  cdc/sinkv2/ddlsink/factory/factory.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_mock_producer.go
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink_test.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_mock_producer.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink.go
  cdc/sinkv2/eventsink/mq/worker.go
  cdc/sinkv2/eventsink/mq/worker_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  pkg/sink/kafka/config.go
  pkg/sink/kafka/main_test.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/options_test.go
  tests/integration_tests/canal_json_adapter_compatibility/conf/server.toml
  tests/integration_tests/canal_json_adapter_compatibility/run.sh
  tests/integration_tests/server_config_compatibility/conf/server.toml
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#8234 kafka(ticdc): sarama admin client use cached topic and partitions
  cdc/sink/mq/manager/kafka_manager.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/cluster_admin_client_mock_impl.go
  pkg/sink/kafka/v2/admin.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.6

#8233 config(ticdc): enable pull based sink
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  tests/integration_tests/processor_err_chan/run.sh
Labels: status/LGT2, status/can-merge, size/S, cherry-pick-approved, release-note-none

#8194 kafka(ticdc): add factory interface
  cdc/sinkv2/ddlsink/factory/factory.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/ddl_producer.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_mock_producer.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sinkv2/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink_test.go
  cdc/sinkv2/eventsink/factory/factory.go
  cdc/sinkv2/eventsink/factory/factory_test.go
  cdc/sinkv2/eventsink/mq/dmlproducer/dml_producer.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_mock_producer.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer.go
  cdc/sinkv2/eventsink/mq/dmlproducer/kafka_dml_producer_test.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink_test.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/client_mock_impl.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/metrics_collector.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/kafka/v2/admin.go
  pkg/sink/kafka/v2/admin_test.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/metrics_collector.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8222 apiv2(ticdc): changefeed cli using open api v2
  cdc/api/v2/changefeed.go
  pkg/api/v1/api_client.go
  pkg/api/v1/changefeed.go
  pkg/api/v1/mock/changefeed_mock.go
  pkg/api/v1/mock/processor_mock.go
  pkg/api/v1/processor.go
  pkg/api/v2/changefeed.go
  pkg/api/v2/mock/changefeed_mock.go
  pkg/cmd/cli/cli_capture_list_test.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/cmd/cli/cli_changefeed_list.go
  pkg/cmd/cli/cli_changefeed_list_test.go
  pkg/cmd/cli/cli_changefeed_pause_test.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_changefeed_query_test.go
  pkg/cmd/cli/cli_changefeed_remove.go
  pkg/cmd/cli/cli_changefeed_remove_test.go
  pkg/cmd/cli/cli_changefeed_resume.go
  pkg/cmd/cli/cli_changefeed_resume_test.go
  pkg/cmd/cli/cli_changefeed_statistics.go
  pkg/cmd/cli/cli_changefeed_update_test.go
  pkg/cmd/cli/cli_processor_list_test.go
  pkg/cmd/cli/cli_processor_query_test.go
  pkg/cmd/factory/factory.go
  pkg/cmd/factory/factory_impl.go
  pkg/cmd/factory/mock/factory_mock.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8236 *(ticdc): use sinkv2 in the redo log applier
  cdc/api/v1/validator.go
  cdc/api/v2/api_helpers.go
  cdc/sink/mock/mock_sink.go
  cdc/sink/sink_test.go
  cdc/sinkv2/eventsink/txn/txn_sink.go
  cdc/sinkv2/validator/main_test.go
  cdc/sinkv2/validator/validator.go
  cdc/sinkv2/validator/validator_test.go
  pkg/applier/redo.go
  pkg/applier/redo_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, component/redolog, area/ticdc

#8243 kafka(ticdc): verify kafka sink v2 configurations
  cdc/sink/mq/manager/kafka_manager_test.go
  cdc/sinkv2/ddlsink/mq/kafka_ddl_sink.go
  cdc/sinkv2/ddlsink/mq/mq_ddl_sink.go
  cdc/sinkv2/eventsink/mq/kafka_dml_sink.go
  cdc/sinkv2/eventsink/mq/mq_dml_sink.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/cluster_admin_client_mock_impl.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/kafka/v2/admin.go
  pkg/sink/kafka/v2/admin_test.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/factory_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8259 cli(ticdc): remove changefeed metainfo api from cli
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/model.go
  pkg/api/v2/changefeed.go
  pkg/api/v2/mock/changefeed_mock.go
  pkg/cmd/cli/cli_changefeed_query.go
  pkg/cmd/cli/cli_changefeed_query_test.go
  pkg/cmd/cli/cli_changefeed_remove.go
  pkg/cmd/cli/cli_changefeed_remove_test.go
  pkg/cmd/cli/cli_changefeed_resume.go
  pkg/cmd/cli/cli_changefeed_resume_test.go
  pkg/cmd/cli/cli_changefeed_statistics.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_changefeed_update_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8254 sink(ticdc): use an unbounded chan in conflict detector
  pkg/causality/conflict_detector.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5, affects-6.5, needs-cherry-pick-release-6.6, affects-6.6

#8260 cmd(ticdc): use sinkV2 in kafka comsumer
  cdc/sinkv2/eventsink/event_appender.go
  cdc/sinkv2/eventsink/event_appender_test.go
  cdc/sinkv2/eventsink/factory/factory.go
  cmd/kafka-consumer/main.go
  tests/integration_tests/_utils/run_kafka_consumer
Labels: component/sink, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#8261 * : manual cherry-pick 8126 to release 6.5
  Makefile
  cdc/api/v2/changefeed_test.go
  cdc/entry/schema/snapshot.go
  cdc/entry/schema/snapshot_test.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/owner/schema_test.go
  cdc/server/server_test.go
  cdc/sink/codec/maxwell/maxwell_message.go
  dm/master/election_test.go
  dm/master/etcd_test.go
  dm/master/openapi_view_test.go
  dm/master/server_test.go
  dm/master/workerrpc/workerrpc_test.go
  dm/pkg/election/election_test.go
  dm/pkg/etcdutil/etcdutil_test.go
  dm/pkg/retry/errors.go
  dm/tests/all_mode/run.sh
  dm/tests/check_task/run.sh
  dm/tests/full_mode/run.sh
  dm/tests/handle_error/run.sh
  dm/tests/many_tables/run.sh
  dm/tests/print_status/run.sh
  dm/tests/shardddl1_1/run.sh
  dm/tests/sync_collation/run.sh
  dm/tests/tracker_ignored_ddl/run.sh
  dm/worker/server_test.go
  dm/worker/source_worker_test.go
  engine/test/integration_tests/dm_collation/run.sh
  engine/test/integration_tests/dm_full_mode/run.sh
  go.mod
  go.sum
  pkg/etcd/etcd.go
  pkg/p2p/message_router_test.go
  pkg/pdutil/utils.go
  pkg/pdutil/utils_test.go
  pkg/txnutil/gc/testing.go
  pkg/version/check_test.go
  tests/integration_tests/multi_source/main.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, cherry-pick-approved, release-note

#8188 consumer(ticdc): Replace sinkv1 with sinkv2 in storage consumer
  cmd/storage-consumer/main.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8212 test(ticdc): fix bank failure caused by wrong snapshot in db session
  tests/integration_tests/bank/case.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8284 Makefile(ticdc): bump the version to v6.7.0
  Makefile
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#8282 sink(ticdc): remove mysql sinkv1
  cdc/owner/ddl_sink.go
  cdc/owner/ddl_sink_test.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/server/metrics.go
  cdc/sink/metrics/metrics.go
  cdc/sink/metrics/statistics.go
  cdc/sink/mysql/causality.go
  cdc/sink/mysql/causality_test.go
  cdc/sink/mysql/main_test.go
  cdc/sink/mysql/mysql.go
  cdc/sink/mysql/mysql_params.go
  cdc/sink/mysql/mysql_params_test.go
  cdc/sink/mysql/mysql_test.go
  cdc/sink/mysql/mysql_worker.go
  cdc/sink/mysql/mysql_worker_test.go
  cdc/sink/mysql/simple_mysql_tester.go
  cdc/sink/mysql/txn_cache.go
  cdc/sink/mysql/txn_cache_test.go
  cdc/sink/mysql/txns_heap.go
  cdc/sink/mysql/txns_heap_test.go
  cdc/sink/sink.go
  cdc/sinkv2/metrics/metrics.go
  cdc/sinkv2/metrics/tablesink/metrics.go
  cdc/syncpointstore/mysql_syncpoint_store.go
  cdc/syncpointstore/syncpoint_store.go
  go.mod
  pkg/applier/redo.go
  pkg/sink/mysql/config.go
Labels: status/can-merge, status/LGT3, require-LGT3, size/XXL, release-note-none

#8287 sinkv2(ticdc): observe row size in MQ sink
  cdc/sinkv2/eventsink/mq/worker.go
Labels: status/LGT2, status/can-merge, size/XS, release-note, needs-cherry-pick-release-6.5

#8283 changefeed(ticdc): fix ddl sink data race
  cdc/owner/ddl_sink.go
Labels: status/LGT2, status/can-merge, size/M, release-note

#8268 cdc: add changefeed epoch to prevent unexpected state
  cdc/api/v1/validator.go
  cdc/api/v1/validator_test.go
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_test.go
  cdc/model/changefeed.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/compat/compat.go
  cdc/scheduler/internal/v3/compat/compat_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/rexport.go
  cdc/scheduler/schedulepb/table_schedule.pb.go
  cdc/scheduler/schedulepb/table_schedule.proto
Labels: status/LGT2, status/can-merge, needs-cherry-pick-release-5.0, size/XXL, needs-cherry-pick-release-5.1, release-note, needs-cherry-pick-release-5.2, needs-cherry-pick-release-5.3, area/ticdc, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8292 sink(ticdc): close conflict detector after workers are closed
  cdc/sinkv2/eventsink/txn/txn_sink.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#8296 redo(ticdc): limit worker number in redo reader
  cdc/redo/reader/file.go
  cdc/redo/reader/reader.go
  pkg/cmd/redo/meta.go
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8275 tests(ticdc): fix table filter in tests
  tests/integration_tests/big_txn/run.sh
  tests/integration_tests/changefeed_auto_stop/run.sh
  tests/integration_tests/changefeed_error/run.sh
  tests/integration_tests/changefeed_reconstruct/run.sh
  tests/integration_tests/consistent_replicate_gbk/conf/workload
  tests/integration_tests/consistent_replicate_nfs/run.sh
  tests/integration_tests/consistent_replicate_storage_file/run.sh
  tests/integration_tests/consistent_replicate_storage_s3/run.sh
  tests/integration_tests/kafka_messages/run.sh
  tests/integration_tests/move_table/run.sh
  tests/integration_tests/multi_capture/run.sh
  tests/integration_tests/sorter/run.sh
  tests/integration_tests/syncpoint/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#7998 sink(ticdc): support TTL table for cdc sink
  cdc/owner/ddl_sink.go
  cdc/owner/ddl_sink_test.go
  pkg/filter/filter.go
  tests/integration_tests/ddl_attributes/data/prepare.sql
  tests/integration_tests/ddl_attributes/run.sh
Labels: status/LGT2, status/can-merge, first-time-contributor, size/M, release-note

#8310 metric(ticdc): remove sinkv1 panels
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#8201 dm: display instruction separately if precheck error is terror.Error
  dm/_utils/terror_gen/errors_release.txt
  dm/errors.toml
  dm/pkg/checker/utils.go
  dm/pkg/checker/utils_test.go
  dm/pkg/election/election_test.go
  dm/pkg/terror/error_list.go
  dm/pkg/terror/terror.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8314 redo(cdc): fix the bug that sink emits events post the barrier
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sinkmanager/redo_cache_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#8249 tests(ticdc): add some integration tests to cover kafka sink v2
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer_test.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  go.mod
  go.sum
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/sarama.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/kafka/sarama_factory_test.go
  pkg/sink/kafka/sarama_test.go
  pkg/sink/kafka/v2/admin.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/factory_test.go
  tests/integration_tests/big_txn_v2/conf/diff_config.toml
  tests/integration_tests/big_txn_v2/conf/server.toml
  tests/integration_tests/big_txn_v2/conf/workload
  tests/integration_tests/big_txn_v2/run.sh
  tests/integration_tests/kafka_big_messages/conf/server.toml
  tests/integration_tests/kafka_big_messages_v2/conf/diff_config.toml
  tests/integration_tests/kafka_big_messages_v2/run.sh
  tests/integration_tests/multi_tables_ddl/conf/server.toml
  tests/integration_tests/multi_tables_ddl_v2/conf/diff_config.toml
  tests/integration_tests/multi_tables_ddl_v2/conf/error-1.toml
  tests/integration_tests/multi_tables_ddl_v2/conf/error-2.toml
  tests/integration_tests/multi_tables_ddl_v2/conf/normal.toml
  tests/integration_tests/multi_tables_ddl_v2/data/test.sql
  tests/integration_tests/multi_tables_ddl_v2/run.sh
  tests/integration_tests/multi_topics_v2/conf/changefeed.toml
  tests/integration_tests/multi_topics_v2/conf/diff_config.toml
  tests/integration_tests/multi_topics_v2/conf/server.toml
  tests/integration_tests/multi_topics_v2/data/step1.sql
  tests/integration_tests/multi_topics_v2/data/step2.sql
  tests/integration_tests/multi_topics_v2/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8317 sink(cdc): improve metrics about conflict detector and sink queue
  cdc/sink/dmlsink/txn/event.go
  cdc/sink/dmlsink/txn/worker.go
  cdc/sink/metrics/txn/metrics.go
  metrics/grafana/ticdc.json
  pkg/causality/conflict_detector.go
  pkg/causality/tests/worker.go
  pkg/causality/worker.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#8307 sink(ticdc): check message size for `canal-json` protocol
  cdc/model/changefeed_test.go
  cdc/sink/dmlsink/mq/worker_test.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/canal/canal_json_encoder.go
  pkg/sink/codec/canal/canal_json_encoder_test.go
  pkg/sink/codec/open/open_protocol_encoder.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.5

#8319 redo(ticdc): fix resolvedTs and split transaction in applier
  cdc/model/mounter.go
  cdc/sink/tablesink/table_sink_impl.go
  pkg/applier/redo.go
  tests/integration_tests/consistent_replicate_nfs/conf/diff_config.toml
  tests/integration_tests/consistent_replicate_nfs/conf/workload
  tests/integration_tests/consistent_replicate_nfs/run.sh
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-6.5

#8322 capture(ticdc): add retry logic when checking pd version
  pkg/version/check.go
  pkg/version/check_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5

#8344 config(ticdc): mark per table memory quota deprecated
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
  pkg/config/server_config_test.go
  tests/integration_tests/server_config_compatibility/conf/server.toml
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/ticdc

#8338 sink(ticdc): remove deprecated batch-replace feature
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/config_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#8331 owner(ticdc): fix changefeed state is automatically changed bug
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#8346 cdc/api/v2: add missing scheduler config
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc

#8140 sink(ticdc): Implement prep stmt cache in mysql sink
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  go.mod
  go.sum
  pkg/applier/redo_test.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/config_test.go
  third-party-license.txt
Labels: component/sink, status/LGT2, status/can-merge, first-time-contributor, size/L, release-note, area/ticdc

#8328 *: upgrade golang version to 1.20
  .github/workflows/check_and_build.yaml
  .github/workflows/dataflow_engine_chaos.yaml
  .github/workflows/dm_binlog_999999.yaml
  .github/workflows/dm_chaos.yaml
  .github/workflows/dm_upstream_switch.yaml
  .github/workflows/ticdc_integration.yaml
  .github/workflows/upgrade_dm_via_tiup.yaml
  .golangci.yml
  CONTRIBUTING.md
  README_DM.md
  README_TiCDC.md
  cdc/capture/capture_test.go
  cdc/model/codec/codec.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/tablesink/state/state_test.go
  cdc/sink/util/helper_test.go
  deployments/engine/docker/Dockerfile
  deployments/engine/docker/dind.Dockerfile
  deployments/ticdc/docker/Dockerfile
  deployments/ticdc/docker/dev.Dockerfile
  deployments/ticdc/docker/integration-test.Dockerfile
  deployments/ticdc/docker/kafka-consumer.Dockerfile
  deployments/ticdc/docker/storage-consumer.Dockerfile
  dm/Dockerfile
  dm/syncer/syncer.go
  dm/tests/dmctl_command/run.sh
  engine/framework/model/master_test.go
  engine/servermaster/http_test.go
  engine/test/e2e/e2e_dm_test.go
  go.mod
  pkg/filter/sql_event_filter_test.go
  pkg/label/label_test.go
  pkg/label/selector_test.go
  pkg/security/sasl_test.go
  pkg/sink/kafka/sarama_test.go
  tools/check/go.mod
  tools/check/go.sum
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8358 pkg(ticdc): clean up pipeline package
  pkg/pipeline/context.go
  pkg/pipeline/main_test.go
  pkg/pipeline/message/message.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#8337 processor(ticdc): Extract all closures to make code maintainable
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/tasks.go
  cdc/processor/sourcemanager/engine/engine.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#8359 tests (ticdc): fix http_api integration test case
  tests/integration_tests/http_api/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-6.5

#8356 cdc: split spans based on capture number
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/compat/compat.go
  cdc/scheduler/internal/v3/compat/compat_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/info_provider_test.go
  cdc/scheduler/internal/v3/keyspan/reconciler.go
  cdc/scheduler/internal/v3/keyspan/reconciler_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/scheduler_config.go
  pkg/version/creator_version_gate.go
  pkg/version/creator_version_gate_test.go
  tests/integration_tests/cli/run.sh
Labels: component/scheduler, status/LGT2, status/can-merge, size/XL, release-note, area/ticdc

#8369 kafka(ticdc): kafka sink v2 confirm messages directly
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/kafka/sarama_factory_test.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/factory_test.go
  pkg/sink/kafka/v2/manual_balancer.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8323 kafka(ticdc): support gssapi for kafka go
  go.mod
  pkg/sink/kafka/v2/admin.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/gssapi.go
  pkg/sink/kafka/v2/gssapi_test.go
  pkg/sink/kafka/v2/mock/gssapi_mock.go
  scripts/generate-mock.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8370 cdc: fix sourcemanager.Close deadlock
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sourcemanager/engine/engine.go
  cdc/processor/sourcemanager/engine/memory/event_sorter.go
  cdc/processor/sourcemanager/engine/mock/engine_mock.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
Labels: status/LGT2, status/can-merge, size/M, release-note, area/ticdc, needs-cherry-pick-release-6.5

#8376 pkg/chann(ticdc): remove close method of DrainableChann
  pkg/chann/drainable_chann.go
Labels: status/LGT1, status/can-merge, size/M, require-LGT1, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#8360 observer(ticdc): reduce observer logs when error happens
  cdc/owner/changefeed.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#8088 sink(ticdc): add one errors to ddl unretryable black list.
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  pkg/errorutil/util.go
  pkg/errorutil/util_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8353 apiv2(ticdc): Add swagger doc
  cdc/api/v1/api.go
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/health.go
  cdc/api/v2/log.go
  cdc/api/v2/model.go
  cdc/api/v2/owner.go
  cdc/api/v2/processor.go
  cdc/api/v2/status.go
  cdc/model/http_model.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/cli/cli_changefeed_query.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#8392 kafka(ticdc): ignore sarama admin create topic exist
  pkg/sink/kafka/admin.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none
