Repository pingcap/tiflow, pull requests merged in 2023-08, with the labels that each got.

#9459 tests (ticdc): remove ticdc github action ci
  .github/workflows/ticdc_integration.yaml
Labels: size/L, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm

#9444 kafka(ticdc): add test to cover handle-key-only functionality
  cmd/kafka-consumer/main.go
  cmd/storage-consumer/main.go
  pkg/config/sink.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/common/config_test.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/internal/column.go
  tests/integration_tests/canal_json_handle_key_only/conf/changefeed.toml
  tests/integration_tests/canal_json_handle_key_only/conf/diff_config.toml
  tests/integration_tests/canal_json_handle_key_only/data/data.sql
  tests/integration_tests/canal_json_handle_key_only/run.sh
  tests/integration_tests/run_group.sh
Labels: size/XXL, release-note-none, approved, lgtm, needs-cherry-pick-release-7.3

#9473 api(ticdc): fix api middleware issue
  cdc/api/middleware/middleware.go
  tests/integration_tests/http_api/util/test_case.py
  tests/integration_tests/http_api_tls/util/test_case.py
Labels: size/XS, release-note-none, approved, lgtm

#9448 pkg/orchestrator(ticdc): add timeout before remove capture
  cdc/capture/capture.go
  cdc/capture/election.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_bank_test.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/interfaces.go
  pkg/orchestrator/reactor_state.go
  pkg/orchestrator/reactor_state_test.go
  pkg/p2p/server.go
Labels: size/L, release-note, approved, lgtm

#9414 owner(cdc): add a new metadata interface
  cdc/metadata/errors.go
  cdc/metadata/main_test.go
  cdc/metadata/memory/main_test.go
  cdc/metadata/memory/memory.go
  cdc/metadata/memory/memory_test.go
  cdc/metadata/metadata.go
Labels: size/XXL, release-note-none, approved, lgtm

#9479 config(ticdc): handle key only not allow force-replicate
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/config_test.go
Labels: size/M, release-note-none, approved, lgtm

#9481 kafka(ticdc): fix sarama admin client reset by error.
  pkg/sink/kafka/admin.go
Labels: size/S, release-note-none, approved, lgtm

#9484 apiV2 (ticdc): list changefeed shows warning message
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/owner/feed_state_manager.go
  pkg/retry/error_retry.go
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.3

#9471 puller(ticdc): fix renameTables ddl job
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
Labels: size/M, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9462 example(ticdc): add canal json consume handle key only example.
  examples/golang/canal-json-handle-key-only/README.md
  examples/golang/canal-json-handle-key-only/go.mod
  examples/golang/canal-json-handle-key-only/go.sum
  examples/golang/canal-json-handle-key-only/main.go
Labels: size/XXL, release-note-none, approved, lgtm

#9454 codec(ticdc): open protocol decoder support handle only message
  cmd/kafka-consumer/main.go
  pkg/sink/codec/builder/codec_test.go
  pkg/sink/codec/open/open_protocol_decoder.go
  pkg/sink/codec/open/open_protocol_decoder_test.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  tests/integration_tests/open_protocol_handle_key_only/conf/changefeed.toml
  tests/integration_tests/open_protocol_handle_key_only/conf/diff_config.toml
  tests/integration_tests/open_protocol_handle_key_only/data/data.sql
  tests/integration_tests/open_protocol_handle_key_only/run.sh
  tests/integration_tests/run_group.sh
Labels: size/XXL, release-note-none, approved, lgtm

#9451 processor(ticdc): do not ignore ErrRedoWriterStopped
  cdc/processor/processor.go
  cdc/processor/processor_test.go
Labels: size/XS, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9498 sqlmodel(dm): generate key in lower case
  pkg/sqlmodel/causality.go
  pkg/sqlmodel/causality_test.go
  pkg/sqlmodel/row_change_test.go
Labels: first-time-contributor, size/M, contribution, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, ok-to-test, approved, lgtm

#9521 ddlPuller (ticdc): fix rename table ddl
  cdc/entry/schema/snapshot.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
Labels: size/M, release-note-none, approved, lgtm

#9470 kafka(ticdc): kafka sink use txn appender
  cdc/sink/dmlsink/factory/factory.go
  cdc/sink/dmlsink/factory/factory_test.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink_test.go
Labels: size/M, release-note-none, approved, lgtm

#9534 mysql(ticdc): consider collation when build the causality key
  cdc/entry/mounter.go
  cdc/model/sink.go
  cdc/model/sink_gen.go
  cdc/sink/dmlsink/txn/event.go
  cdc/sink/dmlsink/txn/event_test.go
  cdc/sink/dmlsink/txn/txn_dml_sink_test.go
Labels: size/XL, release-note-none, approved, lgtm

#9522 dm: fix validator deadlock and enhance retry
  dm/pkg/retry/errors.go
  dm/pkg/retry/strategy.go
  dm/syncer/data_validator.go
  dm/syncer/data_validator_test.go
  dm/syncer/validate_worker.go
  dm/syncer/validate_worker_test.go
  dm/syncer/validator_checkpoint.go
  dm/syncer/validator_checkpoint_test.go
  dm/unit/unit.go
  dm/unit/unit_test.go
Labels: size/L, release-note, area/dm, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9527 sink(cdc): clean backends if table sink is stuck too long
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_advancer_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/orchestrator/reactor_state_test.go
  tests/integration_tests/hang_sink_suicide/conf/changefeed.toml
  tests/integration_tests/hang_sink_suicide/conf/diff_config.toml
  tests/integration_tests/hang_sink_suicide/run.sh
  tests/integration_tests/run_group.sh
Labels: size/XL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9541 owner(ticdc): calculate pending changefeed in gc
  cdc/controller/controller.go
  cdc/controller/controller_test.go
  cdc/model/changefeed.go
  cdc/owner/changefeed.go
  cdc/owner/feed_state_manager.go
  pkg/errors/helper.go
  pkg/errors/helper_test.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_manager_test.go
Labels: size/L, release-note, approved, lgtm

#9524 kafka(ticdc): add unit test to cover claim-check functionality and use uuid to generate object key
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/worker.go
  cdc/sink/metrics/mq/metrics.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_json_txn_event_encoder.go
  pkg/sink/codec/common/message.go
  pkg/sink/codec/open/open_protocol_decoder.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/kafka/claimcheck/claim_check.go
  pkg/sink/kafka/claimcheck/metrics.go
Labels: size/XL, release-note-none, approved, lgtm

#9525 upstream(ticdc): init client go global cfg
  pkg/upstream/upstream.go
Labels: size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9437 sink(ticdc): split RowChangeEvent if unique key is updated
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/sink/dmlsink/event.go
  cdc/sink/tablesink/table_sink_impl.go
  tests/integration_tests/http_api/util/test_case.py
  tests/integration_tests/http_api_tls/util/test_case.py
Labels: size/XL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9546 owner, sink(ticdc): cherry-pick memory quota, gc and failover related fix
  cdc/capture/capture.go
  cdc/capture/election.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/sinkv2/tablesink/table_sink_impl.go
  cdc/sinkv2/tablesink/table_sink_impl_test.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/errors/helper.go
  pkg/orchestrator/etcd_worker.go
  pkg/orchestrator/etcd_worker_bank_test.go
  pkg/orchestrator/etcd_worker_test.go
  pkg/orchestrator/interfaces.go
  pkg/orchestrator/reactor_state.go
  pkg/orchestrator/reactor_state_test.go
  pkg/p2p/server.go
  pkg/txnutil/gc/gc_manager.go
  pkg/txnutil/gc/gc_manager_test.go
Labels: size/XL, release-note, approved, lgtm

#9530 sink(cdc): fix internal retry algothrim
  cdc/owner/changefeed.go
  cdc/owner/ddl_sink.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/processor/sinkmanager/manager.go
  pkg/errors/helper_test.go
  pkg/retry/error_retry.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9549 filter (ticdc): simplify filter interface and apply event filter rule in ddlPuller
  cdc/owner/schema.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/filter/sql_event_filter.go
  pkg/filter/sql_event_filter_test.go
Labels: size/XL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9519 kv-client(ticdc): fix panic when close receiveFromStream
  cdc/kv/client.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
Labels: size/XL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9564 sink(ticdc): always check nil pointer of advanceTimeoutInSec
  cdc/processor/sinkmanager/manager.go
  pkg/config/replica_config.go
  pkg/config/sink.go
Labels: size/S, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9581 sink(cdc): ddl sink errors shouldn't fail changefeed quickly
  cdc/entry/mounter.go
  cdc/model/errors.go
  cdc/model/errors_test.go
  cdc/owner/ddl_sink.go
  cdc/owner/feed_state_manager.go
  cdc/processor/sinkmanager/manager.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  pkg/errors/helper.go
  pkg/errors/helper_test.go
  pkg/filter/expr_filter.go
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9573 kafka(ticdc): large message handle key columns cherry-pick to release-6.5
  cdc/api/v2/model.go
  cdc/sink/codec/builder/codec_test.go
  cdc/sink/codec/canal/canal_encoder.go
  cdc/sink/codec/canal/canal_json_decoder.go
  cdc/sink/codec/canal/canal_json_decoder_test.go
  cdc/sink/codec/canal/canal_json_encoder.go
  cdc/sink/codec/canal/canal_json_encoder_test.go
  cdc/sink/codec/canal/canal_json_message.go
  cdc/sink/codec/common/config.go
  cdc/sink/codec/common/config_test.go
  cdc/sink/codec/common/helper.go
  cdc/sink/codec/craft/craft_decoder.go
  cdc/sink/codec/craft/craft_encoder.go
  cdc/sink/codec/csv/csv_decoder.go
  cdc/sink/codec/decoder.go
  cdc/sink/codec/internal/column.go
  cdc/sink/codec/internal/message_key.go
  cdc/sink/codec/maxwell/maxwell_encoder.go
  cdc/sink/codec/open/open_protocol_decoder.go
  cdc/sink/codec/open/open_protocol_encoder.go
  cdc/sink/codec/open/open_protocol_encoder_test.go
  cdc/sink/codec/open/open_protocol_message.go
  cdc/sink/codec/open/open_protocol_message_test.go
  cdc/sink/mq/mq_test.go
  cmd/kafka-consumer/main.go
  cmd/storage-consumer/main.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/config/config_test_data.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  tests/integration_tests/canal_json_handle_key_only/conf/changefeed.toml
  tests/integration_tests/canal_json_handle_key_only/conf/diff_config.toml
  tests/integration_tests/canal_json_handle_key_only/data/data.sql
  tests/integration_tests/canal_json_handle_key_only/run.sh
  tests/integration_tests/open_protocol_handle_key_only/conf/changefeed.toml
  tests/integration_tests/open_protocol_handle_key_only/conf/diff_config.toml
  tests/integration_tests/open_protocol_handle_key_only/data/data.sql
  tests/integration_tests/open_protocol_handle_key_only/run.sh
Labels: size/XXL, cherry-pick-approved, release-note, approved, lgtm

#9597 kv-client(ticdc): evictAllRegions after close receiveEvents goroutine
  cdc/kv/client.go
  cdc/kv/region_worker.go
Labels: size/XS, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9601 sink(ticdc): add limit to storage ddl sink
  cdc/sinkv2/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sinkv2/ddlsink/cloudstorage/cloud_storage_ddl_sink_test.go
Labels: size/S, cherry-pick-approved, release-note, approved, lgtm

#9611 test(dm): fix integration test about utf8mb4_0900_ai_ci
  dm/tests/sync_collation/run.sh
Labels: size/XS, release-note-none, area/dm, approved, lgtm

#9577 filter (ticdc): add a lock to protect the parser from being called concurrently.
  pkg/filter/sql_event_filter.go
  pkg/filter/utils_test.go
Labels: size/M, release-note-none, approved, lgtm

#9607 dm: fix lag keeps growing when failed ddl is skipped and no following ddl
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/worker/subtask.go
Labels: size/M, release-note, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9621 sink(ticdc): cherry pick data loss fix to release 6.5
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
Labels: size/M, cherry-pick-approved, release-note, approved, lgtm

#9623 sink(ticdc): cherry pick data loss fix to hotfix release
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
Labels: size/M, release-note-none, approved, lgtm

#9604 go: update to 1.21
  CONTRIBUTING.md
  Makefile
  README_DM.md
  README_TiCDC.md
  cdc/server/server_test.go
  deployments/engine/docker/Dockerfile
  deployments/engine/docker/dind.Dockerfile
  deployments/ticdc/docker/Dockerfile
  deployments/ticdc/docker/dev.Dockerfile
  deployments/ticdc/docker/integration-test.Dockerfile
  deployments/ticdc/docker/kafka-consumer.Dockerfile
  deployments/ticdc/docker/storage-consumer.Dockerfile
  dm/Dockerfile
  examples/golang/avro-checksum-verification/go.mod
  examples/golang/canal-json-handle-key-only/go.mod
  go.mod
  go.sum
  tools/check/go.mod
Labels: size/M, release-note-none, approved, lgtm

#9593 changefeed (ticdc): make changefeed list show warning message report by sinkmanager
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  tests/integration_tests/changefeed_error/run.sh
  tests/integration_tests/kafka_sink_error_resume/run.sh
Labels: size/L, release-note, needs-cherry-pick-release-7.1, approved, lgtm

#9512 kafka(ticdc): kafka sink support compression after encoding event into message
  cdc/api/v2/model.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/ddlsink/mq/pulsar_ddl_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/defragmenter_test.go
  cdc/sink/dmlsink/cloudstorage/encoding_worker_test.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink_test.go
  cdc/sink/dmlsink/mq/worker_test.go
  cdc/sink/util/helper.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  errors.toml
  go.mod
  go.sum
  metrics/grafana/ticdc.json
  pkg/compression/compress.go
  pkg/config/config_test_data.go
  pkg/config/large_message.go
  pkg/config/sink.go
  pkg/errors/cdc_errors.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/builder/codec_test.go
  pkg/sink/codec/builder/encoder_builder.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/common/compress.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/metrics.go
  pkg/sink/codec/metrics.go
  pkg/sink/codec/open/open_protocol_decoder.go
  pkg/sink/codec/open/open_protocol_decoder_test.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/kafka/claimcheck/claim_check.go
  pkg/sink/kafka/metrics.go
  pkg/sink/kafka/metrics_collector.go
  tests/integration_tests/canal_json_handle_key_only/conf/changefeed.toml
  tests/integration_tests/canal_json_handle_key_only/run.sh
  tests/integration_tests/open_protocol_handle_key_only/conf/changefeed.toml
  tests/integration_tests/open_protocol_handle_key_only/run.sh
Labels: size/XXL, release-note, approved, lgtm

#9618 sink(ticdc): fix data loss
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
Labels: size/M, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9608 sink(ticdc): add limit to storage ddl sink
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink_test.go
Labels: size/S, release-note, needs-cherry-pick-release-7.1, approved, lgtm

#9634 gc(ticdc): do not block gc if there is no changefeed
  cdc/controller/controller.go
  cdc/controller/controller_test.go
Labels: size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9447 sink (ticdc): add glue schema registry
  cdc/api/v2/api_helpers.go
  cdc/api/v2/model.go
  cdc/entry/mounter_test.go
  cmd/kafka-consumer/main.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  errors.toml
  go.mod
  go.sum
  pkg/config/config_test_data.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/errors/cdc_errors.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/avro/confluent_schema_registry.go
  pkg/sink/codec/avro/confluent_schema_registry_test.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/avro/decoder_test.go
  pkg/sink/codec/avro/glue_client.go
  pkg/sink/codec/avro/glue_schema_registry.go
  pkg/sink/codec/avro/glue_schema_registry_test.go
  pkg/sink/codec/avro/mock_schema_registry.go
  pkg/sink/codec/avro/schema_manager.go
  pkg/sink/codec/builder/encoder_builder.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/config_test.go
Labels: component/sink, size/XXL, release-note, approved, lgtm

#9631 kafka(ticdc): add more unit test and integration test to cover large message handle functionality.
  pkg/config/large_message.go
  pkg/config/large_message_test.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/common/config_test.go
  tests/integration_tests/canal_json_claim_check/conf/changefeed.toml
  tests/integration_tests/canal_json_claim_check/conf/diff_config.toml
  tests/integration_tests/canal_json_claim_check/data/data.sql
  tests/integration_tests/canal_json_claim_check/run.sh
  tests/integration_tests/open_protocol_claim_check/conf/changefeed.toml
  tests/integration_tests/open_protocol_claim_check/conf/diff_config.toml
  tests/integration_tests/open_protocol_claim_check/data/data.sql
  tests/integration_tests/open_protocol_claim_check/run.sh
  tests/integration_tests/run_group.sh
Labels: size/XXL, release-note-none, approved, lgtm

#9578 ticdc(sink) move pulsar sink-uri configs to sink of replica config
  .gitignore
  cdc/api/v2/model.go
  cdc/sink/ddlsink/mq/ddlproducer/ddl_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/pulsar_ddl_mock_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/pulsar_ddl_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/pulsar_ddl_producer_test.go
  cdc/sink/ddlsink/mq/pulsar_ddl_sink.go
  cdc/sink/ddlsink/mq/pulsar_ddl_sink_test.go
  cdc/sink/dmlsink/mq/manager/pulsar_manager.go
  cdc/sink/dmlsink/mq/manager/pulsar_manager_mock.go
  cdc/sink/dmlsink/mq/manager/pulsar_manager_test.go
  cdc/sink/util/helper_test.go
  docs/package-lock.json
  docs/package.json
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/config/config_test_data.go
  pkg/config/replica_config_test.go
  pkg/config/sink.go
  pkg/config/sink_test.go
  pkg/sink/pulsar/config.go
  pkg/sink/pulsar/config_test.go
  pkg/sink/pulsar/factory.go
Labels: size/XXL, contribution, release-note-none, ok-to-test, approved, lgtm

#9622 ticdc(sink) Write DML events to pulsar
  cdc/sink/ddlsink/mq/ddlproducer/pulsar_ddl_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/pulsar_ddl_producer_test.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/ddlsink/mq/pulsar_ddl_sink.go
  cdc/sink/dmlsink/factory/factory.go
  cdc/sink/dmlsink/mq/dispatcher/event_router.go
  cdc/sink/dmlsink/mq/dispatcher/event_router_test.go
  cdc/sink/dmlsink/mq/dmlproducer/dml_producer.go
  cdc/sink/dmlsink/mq/dmlproducer/pulsar_dml_mock_producer.go
  cdc/sink/dmlsink/mq/dmlproducer/pulsar_dml_producer.go
  cdc/sink/dmlsink/mq/dmlproducer/pulsar_dml_producer_test.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/pulsar_dml_sink.go
  cdc/sink/dmlsink/mq/worker.go
  cdc/sink/metrics/mq/metrics.go
  cdc/sink/metrics/mq/pulsar.go
  cmd/kafka-consumer/main.go
  pkg/config/sink.go
  pkg/sink/pulsar/config.go
  pkg/sink/pulsar/factory.go
Labels: size/XXL, contribution, ok-to-test, approved, lgtm

#9496 Makefile: bump version to v7.4.0-master
  Makefile
Labels: size/XS, release-note-none, approved, lgtm

#9163 puller(cdc): share grpc streams and goroutines in tables
  cdc/kv/client.go
  cdc/kv/metrics.go
  cdc/kv/region_state.go
  cdc/kv/region_worker.go
  cdc/kv/regionlock/region.go
  cdc/kv/regionlock/region_range_lock.go
  cdc/kv/regionlock/region_test.go
  cdc/kv/shared_client.go
  cdc/kv/shared_client_test.go
  cdc/kv/shared_region_worker.go
  cdc/kv/shared_region_worker_test.go
  cdc/processor/sinkmanager/redo_log_worker_test.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sourcemanager/engine/engine.go
  cdc/processor/sourcemanager/engine/memory/event_sorter.go
  cdc/processor/sourcemanager/engine/mock/engine_mock.go
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
  cdc/processor/sourcemanager/manager.go
  cdc/processor/sourcemanager/puller/multiplexing_puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/metrics.go
  cdc/puller/multiplexing_puller.go
  cdc/puller/multiplexing_puller_test.go
  engine/framework/worker_test.go
  go.mod
  go.sum
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/kvclient.go
  pkg/config/server_config.go
  pkg/spanz/hash_map.go
  tests/integration_tests/http_api_tls/run.sh
  tests/integration_tests/processor_err_chan/conf/server.toml
  tests/integration_tests/processor_err_chan/run.sh
Labels: size/XXL, release-note-none, approved, lgtm

#9646 config (ticdc): add checking for changefeed scheduler config
  cdc/puller/ddl_puller.go
  metrics/alertmanager/ticdc.rules.yml
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/scheduler_config.go
Labels: size/M, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm
