Repository pingcap/tiflow, pull requests merged in 2023-12, with the labels that each got.

#10182 puller(ticdc): detect resolved ts stuck in puller
  cdc/puller/puller.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
Labels: size/M, release-note-none, approved, lgtm

#10202 puller(cdc): debug frontier
  cdc/kv/client.go
  cdc/kv/shared_client.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/puller.go
Labels: size/L, release-note-none, approved, lgtm

#10225 scheduler(ticdc): Updating ReplicationSet.stats only when stats is not empty
  cdc/scheduler/internal/v3/replication/replication_set.go
Labels: size/XS, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#9970 csv: delimiter supports at most 2 characters
  pkg/config/sink.go
  pkg/config/sink_test.go
Labels: first-time-contributor, size/M, release-note, approved, lgtm

#10227 redo(ticdc): use multi part s3 uploader in redo
  cdc/api/v2/model.go
  cdc/redo/writer/memory/file_worker.go
  pkg/config/consistent.go
  pkg/util/external_storage.go
  tests/integration_tests/consistent_replicate_storage_s3/conf/changefeed.toml
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10205 syncer(dm): Improve logging of ignored TableMap/FormatDesc
  dm/syncer/syncer.go
Labels: size/XS, release-note, approved, lgtm

#10253 kv-client(cdc): debug frontier
  cdc/kv/client.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/processor/sinkmanager/tasks.go
  cdc/processor/sinkmanager/tasks_test.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/puller.go
Labels: size/L, release-note-none, needs-1-more-lgtm

#10258 puller(ticdc): fix stuck detect issue
  cdc/puller/puller.go
Labels: size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10265 codec(ticdc): move canal test util to the utils, it should be shared among all prot…
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_test_util.go
  pkg/sink/codec/utils/test_utils.go
  scripts/check-diff-line-width.sh
Labels: size/XXL, release-note-none, approved, lgtm

#10244 util: Add JSONWriter
  go.mod
  go.sum
  pkg/util/json_writer.go
  pkg/util/json_writer_test.go
Labels: first-time-contributor, size/XXL, contribution, release-note-none, needs-ok-to-test, approved, lgtm

#10211 checker(dm): Replace URL in error
  dm/pkg/checker/binlog.go
Labels: size/XS, release-note-none, approved, lgtm

#10155 dm: parse metadata without flavor
  dm/loader/util.go
  dm/pkg/dumpling/utils.go
  dm/pkg/dumpling/utils_test.go
  dm/pkg/gtid/gtid.go
  dm/pkg/gtid/gtid_test.go
  dm/syncer/checkpoint.go
  dm/syncer/syncer.go
Labels: size/M, release-note, approved, lgtm

#10276 owner(ticdc): decouple feed state manager
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/owner.go
  pkg/orchestrator/reactor_state.go
Labels: size/XXL, release-note-none, approved, lgtm

#10273 sorter(ticdc) make the name more clear
  cdc/capture/capture.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/manager_test_helper.go
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sinkmanager/redo_cache_test.go
  cdc/processor/sinkmanager/redo_log_advancer.go
  cdc/processor/sinkmanager/redo_log_advancer_test.go
  cdc/processor/sinkmanager/redo_log_worker_test.go
  cdc/processor/sinkmanager/table_progress_heap.go
  cdc/processor/sinkmanager/table_progress_heap_test.go
  cdc/processor/sinkmanager/table_sink_advancer.go
  cdc/processor/sinkmanager/table_sink_advancer_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/tasks.go
  cdc/processor/sinkmanager/tasks_test.go
  cdc/processor/sourcemanager/manager.go
  cdc/processor/sourcemanager/puller/dummy_puller_wrapper.go
  cdc/processor/sourcemanager/puller/multiplexing_puller_wrapper.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/processor/sourcemanager/sorter/engine.go
  cdc/processor/sourcemanager/sorter/factory/factory.go
  cdc/processor/sourcemanager/sorter/factory/pebble.go
  cdc/processor/sourcemanager/sorter/memory/doc.go
  cdc/processor/sourcemanager/sorter/memory/event_sorter.go
  cdc/processor/sourcemanager/sorter/memory/event_sorter_test.go
  cdc/processor/sourcemanager/sorter/memory/main_test.go
  cdc/processor/sourcemanager/sorter/metrics.go
  cdc/processor/sourcemanager/sorter/mock/engine_mock.go
  cdc/processor/sourcemanager/sorter/mounted_iter.go
  cdc/processor/sourcemanager/sorter/mounted_iter_test.go
  cdc/processor/sourcemanager/sorter/pebble/db.go
  cdc/processor/sourcemanager/sorter/pebble/db_test.go
  cdc/processor/sourcemanager/sorter/pebble/doc.go
  cdc/processor/sourcemanager/sorter/pebble/encoding/key.go
  cdc/processor/sourcemanager/sorter/pebble/encoding/key_test.go
  cdc/processor/sourcemanager/sorter/pebble/encoding/value.go
  cdc/processor/sourcemanager/sorter/pebble/event_sorter.go
  cdc/processor/sourcemanager/sorter/pebble/event_sorter_test.go
  cdc/server/metrics.go
  cdc/server/server.go
  cdcv2/capture/capture.go
  pkg/context/context.go
  scripts/generate-mock.sh
Labels: size/XXL, release-note-none, approved, lgtm

#10278 simple (ticdc): fix table schema indexes does not contain primary key
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/model/schema_storage.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/simple/message_test.go
Labels: size/XXL, release-note-none, approved, lgtm

#10283 cloudstorage(ticdc): write meta file if not found and add ut for 10137
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_test.go
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10174 sink to csv: output old value to CSV files
  cdc/api/v2/model.go
  pkg/cmd/util/changefeed_storage_sink.toml
  pkg/config/config_test_data.go
  pkg/config/sink.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/csv/csv_message.go
  pkg/sink/codec/csv/csv_message_test.go
Labels: size/L, release-note, approved, lgtm

#10197 cdc: Add Debezium protocol
  cdc/sink/util/helper.go
  errors.toml
  go.mod
  go.sum
  pkg/config/sink_protocol.go
  pkg/errors/cdc_errors.go
  pkg/sink/codec/builder/encoder_builder.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/debezium/codec.go
  pkg/sink/codec/debezium/codec_test.go
  pkg/sink/codec/debezium/debezium_test.go
  pkg/sink/codec/debezium/encoder.go
  pkg/sink/codec/debezium/testdata/datatype.dbz.json
  pkg/sink/codec/debezium/testdata/datatype.ddl.sql
  pkg/sink/codec/debezium/testdata/datatype.dml.sql
Labels: first-time-contributor, size/XXL, contribution, release-note, needs-ok-to-test, approved, lgtm

#10292 puller(ticdc): add ut for 10258
  cdc/puller/puller_test.go
Labels: size/M, release-note-none, approved, lgtm

#10194 dm: add openapi physical import config
  dm/config/task.go
  dm/config/task_converters.go
  dm/openapi/fixtures/task.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/tests/lightning_mode/conf/dm-master.toml
  dm/tests/lightning_mode/conf/task.json
  dm/tests/lightning_mode/run.sh
Labels: size/XL, release-note-none, approved, lgtm

#10252 kv-client(cdc): handle ServerIsBusy errors
  cdc/kv/client.go
  cdc/kv/shared_client.go
  go.mod
  go.sum
Labels: size/L, release-note-none, approved, lgtm

#10139 redo(cdc): custom redo event cache and disable it by default
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  dm/tests/lightning_mode/run.sh
  dm/tests/tls/run.sh
  pkg/config/config_test_data.go
  pkg/config/consistent.go
  pkg/config/replica_config.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10319 redo(cdc): custom redo event cache and disable it by default (#10139)
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  dm/tests/lightning_mode/run.sh
  dm/tests/tls/run.sh
  pkg/config/config_test_data.go
  pkg/config/consistent.go
  pkg/config/replica_config.go
Labels: size/L, release-note, approved, lgtm

#10251 codec(ticdc): simple support large message handle functionality
  cdc/model/changefeed.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_manager.go
  cdc/owner/ddl_manager_test.go
  cdc/owner/ddl_sink.go
  cmd/kafka-consumer/main.go
  pkg/config/large_message.go
  pkg/sink/codec/builder/encoder_builder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/utils/test_utils.go
  pkg/upstream/manager_test.go
  tests/integration_tests/kafka_simple_claim_check/conf/changefeed.toml
  tests/integration_tests/kafka_simple_claim_check/conf/diff_config.toml
  tests/integration_tests/kafka_simple_claim_check/data/data.sql
  tests/integration_tests/kafka_simple_claim_check/data/ddl.sql
  tests/integration_tests/kafka_simple_claim_check/run.sh
  tests/integration_tests/kafka_simple_handle_key_only/conf/changefeed.toml
  tests/integration_tests/kafka_simple_handle_key_only/conf/diff_config.toml
  tests/integration_tests/kafka_simple_handle_key_only/data/data.sql
  tests/integration_tests/kafka_simple_handle_key_only/data/ddl.sql
  tests/integration_tests/kafka_simple_handle_key_only/run.sh
  tests/integration_tests/run_group.sh
Labels: size/XXL, release-note-none, approved, lgtm

#10321 puller(cdc): debug frontier (#10202) (#10269)
  cdc/kv/client.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/puller.go
Labels: size/L, release-note, approved, lgtm

#10302 kv-client(cdc): add more tests for special events with empty entries
  cdc/kv/client.go
  cdc/kv/utils.go
  cdc/kv/utils_test.go
Labels: size/M, release-note-none, approved, lgtm

#10320 cloudstorage(ticdc): write meta file if not found and add ut for 101…
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_test.go
Labels: size/M, release-note, approved, lgtm

#10314 sqlmodel(*): optimize O(N*N) generated column check to O(N)
  pkg/sqlmodel/multirow.go
  pkg/sqlmodel/row_change.go
  pkg/sqlmodel/utils.go
  pkg/sqlmodel/utils_test.go
Labels: size/M, release-note-none, approved, lgtm

#10323 sink-mysql(cdc) set variables first and then execute DMLs
  cdc/sink/dmlsink/txn/mysql/mysql.go
Labels: size/M, release-note-none, approved, lgtm

#10326 kv-client(cdc): fix metrics for kvclient.SharedClient
  cdc/kv/shared_client.go
  metrics/grafana/ticdc.json
Labels: size/S, release-note-none, approved, lgtm

#10324 *: fix package sourcegraph/appdash not found
  go.mod
  go.sum
Labels: size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10297 puller(ticdc): refactor ddl puller remove verbose code and reduce logs
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/model/owner.go
  cdc/processor/processor.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
  errors.toml
  pkg/errors/cdc_errors.go
Labels: size/XL, release-note-none, approved, lgtm

#10294 codec(ticdc): simple protocol DDL message encode 2 table schema
  cdc/entry/schema_test_helper.go
  cdc/owner/changefeed_test.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/simple/message_test.go
Labels: size/XL, release-note-none, approved, lgtm

#10133 TiCDC support checking if data is entirely replicated to Downstream
  cdc/api/v1/api_test.go
  cdc/api/v2/api.go
  cdc/api/v2/api_test.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/mock/status_provider_mock.go
  cdc/owner/owner.go
  cdc/owner/status_provider.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/tablepb/table.pb.go
  cdc/processor/tablepb/table.proto
  cdc/scheduler/internal/scheduler.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cdc/scheduler/internal/v3/replication/replication_set.go
  cdc/scheduler/schedulepb/watermark.go
  cdc/sink/tablesink/table_sink.go
  cdc/sink/tablesink/table_sink_impl.go
  cdc/sink/tablesink/table_sink_impl_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/synced_status_config.go
  pkg/orchestrator/reactor_state_test.go
  tests/integration_tests/run_group.sh
  tests/integration_tests/synced_status/conf/changefeed-redo.toml
  tests/integration_tests/synced_status/conf/changefeed.toml
  tests/integration_tests/synced_status/run.sh
Labels: size/XXL, release-note, approved, lgtm

#10347 mq (ticdc): make some code more readable.
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/worker.go
  cdc/sink/dmlsink/mq/worker_test.go
  pkg/sink/codec/encoder.go
  pkg/sink/codec/encoder_group.go
Labels: size/L, release-note-none, approved, lgtm

#10327 schemaStorage(ticdc): unify 2 schema storage implementation
  cdc/entry/mounter_test.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/entry/schema_test_helper.go
  cdc/owner/changefeed.go
  cdc/owner/ddl_manager.go
  cdc/owner/ddl_manager_test.go
  cdc/owner/metrics.go
  cdc/owner/schema.go
  cdc/owner/schema_test.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/manager_test_helper.go
  cdc/puller/ddl_puller_test.go
  pkg/sink/codec/debezium/debezium_test.go
  pkg/sink/codec/simple/encoder.go
Labels: size/XXL, release-note-none, approved, lgtm

#10277 changefeed(ticdc): remove some panic log
  cdc/kv/client.go
  cdc/owner/changefeed.go
  cdc/owner/ddl_sink.go
  cdc/owner/ddl_sink_test.go
  cdc/processor/processor.go
  cdc/redo/writer/memory/file_worker.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  errors.toml
  pkg/errors/cdc_errors.go
Labels: size/M, release-note, approved, lgtm

#10084 security: support mtls configuration
  pkg/cmd/util/ticdc.toml
  pkg/config/config_test_data.go
  pkg/security/credential.go
  pkg/tcpserver/tcp_server.go
Labels: first-time-contributor, size/M, release-note, approved, lgtm

#10360 mq (ticdc): improve readability of some code
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/defragmenter.go
  cdc/sink/dmlsink/cloudstorage/dml_worker.go
Labels: size/L, release-note-none, approved, lgtm

#10346 dm: set enable cluster index to off for downstream tracker
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
Labels: size/S, release-note, needs-cherry-pick-release-6.5, approved, lgtm

#10357 csv(cdc): delimiter supports at most 3 characters
  pkg/config/sink.go
  pkg/config/sink_test.go
Labels: size/S, release-note-none, approved, lgtm

#10307 cdc: Support schema for Debezium output protocol
  pkg/config/sink.go
  pkg/sink/codec/builder/encoder_builder.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/debezium/codec.go
  pkg/sink/codec/debezium/codec_test.go
  pkg/sink/codec/debezium/debezium_test.go
  pkg/sink/codec/debezium/encoder.go
  pkg/util/json_writer.go
  pkg/util/json_writer_test.go
Labels: size/XXL, release-note, approved, lgtm

#10335 conflict detector(cdc): fix potential dead lock when a transaction generated multiple same hash
  cdc/sink/dmlsink/txn/event.go
  cdc/sink/dmlsink/txn/event_test.go
  cdc/sink/dmlsink/txn/worker.go
  pkg/causality/conflict_detector.go
  pkg/causality/internal/node.go
  pkg/causality/internal/slots.go
  pkg/causality/tests/integration_test.go
  pkg/causality/tests/worker.go
  pkg/causality/worker.go
Labels: type/bugfix, size/XL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10333 puller(cdc): more tests and logs for frontier and kv-client
  cdc/kv/client.go
  cdc/kv/region_state.go
  cdc/kv/region_worker.go
  cdc/kv/regionlock/region_range_lock.go
  cdc/kv/regionlock/region_range_lock_test.go
  cdc/kv/shared_client.go
  cdc/kv/shared_region_worker.go
  cdc/puller/frontier/frontier_test.go
  pkg/spanz/convert.go
  pkg/spanz/convert_test.go
Labels: size/XL, release-note-none, approved, lgtm

#10380 binlog-filter: log error instead of return it
  dm/tests/all_mode/conf/dm-task.yaml
  go.mod
  go.sum
Labels: size/XS, release-note, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10372 debezium(ticdc): cli support debezium-disable-schema
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/orchestrator/reactor_state_test.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/api_v2/model.go
Labels: size/S, release-note-none, approved, lgtm

#10390 dm: set enable cluster index to off for downstream tracker (#10346)
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
Labels: size/S, release-note, approved, lgtm

#10387 kv(ticdc): Remove store connect backoff (#9740)
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/processor/pipeline/puller.go
  cdc/processor/processor.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
Labels: size/L, release-note, approved, lgtm
