Repository pingcap/tiflow, pull requests merged in 2023-11, with the labels that each got.

#9981 kv-client(cdc): add more logs to help debug slow regions
  cdc/kv/client.go
  cdc/kv/region_worker.go
  pkg/txnutil/lock_resolver.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#9813 mysql (ticdc): fix batch dml delete sql gennerate error
  cdc/entry/mounter_test.go
  cdc/model/sink.go
Labels: size/M, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#9887 redo(ticdc): fix redo initialization block the owner
  cdc/owner/changefeed.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/meta_manager.go
  cdc/redo/meta_manager_test.go
  cdc/redo/writer/blackhole/blackhole_log_writer.go
  cdc/redo/writer/factory/factory.go
  cdc/redo/writer/file/file.go
  cdc/redo/writer/memory/encoding_worker.go
  cdc/redo/writer/memory/file_worker.go
  cdc/redo/writer/memory/mem_log_writer.go
  cdc/redo/writer/memory/mem_log_writer_test.go
  cdc/redo/writer/writer.go
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/replication/replication_manager_test.go
  cmd/kafka-consumer/main.go
  pkg/redo/config.go
  tests/integration_tests/changefeed_error/run.sh
Labels: size/XXL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#9941 config, changefeed (ticdc): add sql mode config for changefeed
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed.go
  cdc/owner/ddl_sink.go
  cdc/owner/ddl_sink_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/filter/expr_filter.go
  pkg/filter/expr_filter_bench_test.go
  pkg/filter/expr_filter_test.go
  pkg/filter/filter.go
  pkg/filter/sql_event_filter.go
  pkg/filter/sql_event_filter_test.go
  pkg/filter/utils_test.go
  pkg/orchestrator/reactor_state_test.go
  scripts/check-diff-line-width.sh
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#9945 Makefile: bump version to v7.6.0-master
  Makefile
Labels: size/XS, release-note-none, approved, lgtm

#9999 redo(ticdc): use meta flush interval in redo ddl manager
  cdc/redo/manager.go
  cdc/redo/manager_test.go
Labels: size/M, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#9978 dm: add more event for incompatible ddl changes
  dm/syncer/ddl.go
  dm/tests/incompatible_ddl_changes/conf/dm-task1.yaml
  dm/tests/incompatible_ddl_changes/run.sh
  go.mod
  go.sum
Labels: size/L, release-note-none, ok-to-test, approved, lgtm

#10000 redo(ticdc): add meta flush interval configuration (#9959) (#9971)
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/owner/changefeed_test.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/meta_manager.go
  cdc/redo/meta_manager_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/config/config_test_data.go
  pkg/config/consistent.go
  pkg/config/replica_config.go
  pkg/redo/config.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/api_v2/model.go
Labels: size/XXL, release-note, approved, lgtm

#9944 dm: reduce gSet.String() usage by using zeroGSet for checking empty
  dm/pkg/binlog/event/common.go
  dm/pkg/binlog/event/event.go
  dm/pkg/binlog/position.go
  dm/pkg/gtid/gtid.go
  dm/pkg/gtid/gtid_test.go
  dm/syncer/checkpoint.go
  dm/syncer/syncer.go
Labels: size/L, release-note-none, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10028 redo(ticdc): remove some repeat code
  cdc/redo/meta_manager.go
  cdc/redo/reader/reader.go
Labels: first-time-contributor, size/S, release-note, approved, lgtm

#9943 ddl(ticdc): add detail information for ddl puller
  cdc/puller/ddl_puller.go
Labels: size/S, release-note, approved, lgtm

#10031 redo(ticdc): fix meta manager wrong flush interval bug
  cdc/redo/manager.go
  cdc/redo/meta_manager.go
Labels: size/XS, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#10037 kafka(ticdc): claim check do not use filepath join to build the full file path.
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/kafka/claimcheck/claim_check.go
  pkg/sink/kafka/claimcheck/claim_check_test.go
Labels: size/M, release-note-none, approved, lgtm

#10027 sink(ticdc): use subDir in storage.Walk
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_test.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10046 filter(ticdc): change case-sensitive parameter default value to false
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed_test.go
  cdc/owner/changefeed_test.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/meta_manager_test.go
  cdc/redo/writer/memory/encoding_worker.go
  cdc/redo/writer/memory/file_worker.go
  cdc/redo/writer/memory/main_test.go
  cdc/redo/writer/memory/mem_log_writer.go
  cdc/sinkv2/eventsink/cloudstorage/cloud_storage_dml_sink.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/config/config_test_data.go
  pkg/config/consistent.go
  pkg/config/replica_config.go
  pkg/redo/config.go
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_test.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/api_v2/model.go
Labels: size/L, release-note-none, approved, lgtm

#10025 redo(ticdc): add writer related parameter
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/owner/changefeed_test.go
  cdc/processor/processor_test.go
  cdc/redo/manager.go
  cdc/redo/manager_test.go
  cdc/redo/meta_manager_test.go
  cdc/redo/writer/memory/encoding_worker.go
  cdc/redo/writer/memory/file_worker.go
  cdc/redo/writer/memory/main_test.go
  cdc/redo/writer/memory/mem_log_writer.go
  pkg/config/config_test_data.go
  pkg/config/consistent.go
  pkg/config/replica_config.go
  pkg/redo/config.go
  tests/integration_tests/api_v2/model.go
Labels: size/M, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10003 validator: add more tests for validation update and fix previous bugs
  dm/ctl/master/update_validation.go
  dm/master/server.go
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/syncer/data_validator.go
  dm/syncer/syncer.go
  dm/tests/dmctl_command/run.sh
  dm/tests/validator_basic/conf/dm-task-standalone-long-interval.yaml
  dm/tests/validator_basic/run.sh
Labels: size/XXL, release-note-none, approved, lgtm

#10043 kafka(ticdc): column selector allow filter out columns if there are at least primary key or one unique key
  cdc/entry/schema_storage_test.go
  cdc/model/schema_storage.go
  cdc/sink/dmlsink/mq/transformer/columnselector/column_selector.go
  cdc/sink/dmlsink/mq/transformer/columnselector/column_selector_test.go
Labels: size/XL, release-note-none, approved, lgtm

#10054 puller(cdc): add metrics for slowest changefeed puller
  cdc/scheduler/internal/v3/replication/metrics.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  metrics/grafana/ticdc.json
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10034 owner(cdc): add owner for cdc v2
  cdc/owner/changefeed.go
  cdc/processor/processor.go
  cdcv2/capture/capture.go
  cdcv2/owner/owner.go
Labels: size/XL, release-note, approved, lgtm

#10049 config(ticdc): change case-sensitive default value
  cdc/api/v2/model_test.go
  cdc/model/changefeed_test.go
  pkg/config/replica_config.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/cli/run.sh
Labels: size/S, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10073 config(ticdc): change case-sensitive default value
  cdc/api/v2/model_test.go
  cdc/model/changefeed_test.go
  pkg/config/replica_config.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/cli/run.sh
Labels: size/S, cherry-pick-approved, release-note, approved, lgtm

#10080 ddl_manager (ticdc): fix in bdr mode cdc can not replicate a table's dmls after drop and re-create it
  cdc/owner/ddl_manager.go
  tests/integration_tests/bdr_mode/data/start.sql
  tests/integration_tests/bdr_mode/data/up.sql
Labels: size/M, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10087 codec(ticdc): canal-json decouple java type from the mysql type
  pkg/sink/codec/canal/canal_entry.go
  pkg/sink/codec/canal/canal_entry_test.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
Labels: size/M, release-note-none, approved, lgtm

#10085 sink(cdc): avoid sinking redundant events in some rare cases with redo enabled
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sinkmanager/redo_cache_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10096 sink(cdc): avoid sinking redundant events in some rare cases with redo enabled
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sinkmanager/redo_cache_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/scheduler/internal/v3/agent/agent.go
Labels: size/L, release-note-none, approved, lgtm

#9961 Makefile(ticdc): support build cdc in fips mode
  Makefile
  cmd/cdc/fips.go
  pkg/version/check.go
  pkg/version/check_test.go
Labels: first-time-contributor, size/M, release-note, approved, lgtm

#10102 redo(ticdc): fix redo zero flush interval panic issue
  cdc/redo/manager.go
Labels: size/S, release-note-none, approved, lgtm

#10099 use upstream pd client in api v2
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
Labels: size/M, release-note-none, approved, lgtm

#10083 metrics(ticdc): fix grafana configuration of ticdc
  metrics/grafana/ticdc.json
Labels: size/XXL, release-note, approved, lgtm

#10023 redo(ticdc): fix redo balckhole storage issues
  cdc/model/changefeed.go
  cdc/model/changefeed_test.go
  cdc/redo/meta_manager.go
  pkg/orchestrator/reactor_state_test.go
  pkg/sink/sink_type.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/api_v2/model.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10123 codec(ticdc): canal-json decouple get value from java type and refactor unit test
  cdc/model/schema_storage.go
  cdc/model/sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink_test.go
  cdc/sink/dmlsink/mq/worker_test.go
  pkg/sink/codec/canal/canal_encoder_test.go
  pkg/sink/codec/canal/canal_entry.go
  pkg/sink/codec/canal/canal_entry_test.go
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_json_txn_event_encoder_test.go
  pkg/sink/codec/canal/canal_test_util.go
  pkg/sink/codec/canal/type_test.go
  pkg/sink/codec/utils/field_types.go
Labels: size/XXL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm

#10135 kv-client(cdc): add more logs and metrics for kv-client
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/region_state.go
  cdc/kv/region_state_bench_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/kv/regionlock/region_range_lock.go
  cdc/kv/regionlock/region_range_lock_test.go
  cdc/processor/processor.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
Labels: size/XXL, release-note-none

#10045 ddlManager (ticdc): add bootstrap sending function
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_manager.go
  cdc/owner/ddl_sink.go
Labels: size/L, release-note-none, approved, lgtm

#10040 sink(ticdc): add total write bytes counter to sink
  cdc/sink/dmlsink/cloudstorage/dml_worker.go
  cdc/sink/dmlsink/mq/worker.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/metrics/metrics.go
  cdc/sink/metrics/statistics.go
Labels: size/M, release-note, approved, lgtm

#10078 mereics(ticdc): add cdc_resolvedts_high_delay alert
  cdc/processor/processor.go
  cdc/redo/manager.go
  cdc/redo/meta_manager.go
  cdc/redo/writer/memory/encoding_worker.go
  cdc/redo/writer/memory/file_worker.go
  cdc/redo/writer/memory/mem_log_writer.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  metrics/alertmanager/ticdc.rules.yml
Labels: size/L, release-note, approved, lgtm

#10132 sink(cdc): always handle sink failures for cases with sync-point enabled
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/sink/dmlsink/blackhole/black_hole_dml_sink.go
  cdc/sink/tablesink/table_sink.go
  cdc/sink/tablesink/table_sink_impl.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10138 cloudstorage(ticdc): Remove nfs schema file check
  pkg/sink/cloudstorage/path.go
Labels: size/XS, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10146 [security]: upgrade dependency
  cdc/api/v2/changefeed_test.go
  dm/ui/package.json
  dm/ui/yarn.lock
  go.mod
  go.sum
Labels: size/L, cherry-pick-approved, release-note, ok-to-test, approved, lgtm

#10097 sink(ticdc): cleanup expired files by day for storage sink
  cdc/api/v2/model.go
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink_test.go
  go.mod
  go.sum
  pkg/config/sink.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_test.go
  pkg/util/external_storage.go
  tests/integration_tests/run_group.sh
  tests/integration_tests/storage_cleanup/conf/changefeed-default.toml
  tests/integration_tests/storage_cleanup/conf/changefeed.toml
  tests/integration_tests/storage_cleanup/conf/diff_config.toml
  tests/integration_tests/storage_cleanup/data/data.sql
  tests/integration_tests/storage_cleanup/data/schema.sql
  tests/integration_tests/storage_cleanup/run.sh
Labels: size/XXL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#9990 sink(ticdc): add more log and metrics to storage sink
  cdc/owner/changefeed.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/dml_worker.go
  cdc/sink/metrics/cloudstorage/metrics.go
  pkg/config/sink.go
Labels: size/M, release-note, approved, lgtm

#10116 api(ticdc): support create simple protocol changefeed
  cdc/model/changefeed.go
  cdc/owner/changefeed.go
  cdc/owner/ddl_manager.go
  cdc/owner/ddl_manager_test.go
  cdc/sink/util/helper.go
  pkg/sink/codec/builder/encoder_builder.go
  pkg/sink/codec/simple/encoder.go
  pkg/sink/codec/simple/encoder_test.go
Labels: size/M, release-note-none, approved, lgtm

#10165 cdc: cherry picks #9982 and #10054
  cdc/kv/client.go
  cdc/kv/region_state.go
  cdc/kv/region_state_bench_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/scheduler/internal/v3/replication/metrics.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  metrics/grafana/ticdc.json
  pkg/regionspan/region_range_lock.go
  pkg/regionspan/region_range_lock_test.go
  pkg/txnutil/lock_resolver.go
Labels: size/XXL, release-note-none, approved, lgtm

#9954 sink(ticdc): use multi part s3 uploader in storage sink
  cdc/api/v2/model.go
  cdc/redo/meta_manager_test.go
  cdc/sink/dmlsink/cloudstorage/dml_worker.go
  pkg/config/sink.go
  pkg/sink/cloudstorage/config.go
  pkg/sink/cloudstorage/config_test.go
Labels: size/M, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#9793 fix(ui): move vite plugin to repo
  dm/ui/.eslintrc.js
  dm/ui/package.json
  dm/ui/plugins/vite-plugin-i18next-scanner/index.js
  dm/ui/plugins/vite-plugin-i18next-scanner/package.json
  dm/ui/plugins/vite-plugin-i18next-scanner/worker.js
  dm/ui/plugins/vite-plugin-next-react-router/index.js
  dm/ui/plugins/vite-plugin-next-react-router/package.json
  dm/ui/tsconfig.json
  dm/ui/vite.config.js
  dm/ui/yarn.lock
Labels: size/XXL, release-note, approved, lgtm

#10170 cdc: fixes minor bugs #10168 and #10169
  cdc/kv/client.go
  cdc/kv/shared_client.go
  cdc/processor/sinkmanager/tasks.go
  cdc/processor/sinkmanager/tasks_test.go
Labels: size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10195 kvclient(ticdc): fix the workerpool data race
  cdc/kv/region_worker.go
Labels: size/XS, cherry-pick-approved, release-note, approved, lgtm
