Repository pingcap/tiflow, pull requests merged in 2023-03, with the labels that each got.

#8343 changefeed (ticdc): add ddl manager
  cdc/model/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_manager.go
  cdc/owner/schema.go
  cdc/puller/ddl_puller.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note-none

#8394 config(ticdc): adjust config name
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed_test.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/compat/compat.go
  cdc/scheduler/internal/v3/compat/compat_test.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/keyspan/reconciler_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/scheduler_config.go
  tests/integration_tests/cli/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#8399 deployments(ticdc): remove useless sha256sum check
  deployments/ticdc/docker/integration-test.Dockerfile
Labels: status/LGT1, status/can-merge, size/XS, require-LGT1, release-note-none

#8372 sink(ticdc): add table sink advancer
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_advancer.go
  cdc/processor/sinkmanager/table_sink_advancer_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, area/ticdc

#8349 sink: unify sql format between dmlsink and sqlmodel module
  cdc/sink/dmlsink/txn/mysql/dml.go
  cdc/sink/dmlsink/txn/mysql/dml_test.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#8405 processor(ticdc): clean up dead code
  cdc/processor/doc.go
  cdc/processor/manager.go
  cdc/processor/manager_test.go
  cdc/processor/mock/manager_mock.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#8416 tests(ticdc): fix flaky test TestWriteDML
  cdc/redo/writer/memory/main_test.go
  cdc/redo/writer/memory/mem_log_writer.go
  cdc/redo/writer/memory/mem_log_writer_test.go
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none

#8419 sink(ticdc): use a global variable to ensure that the batch ID is monotonically increasing
  cdc/processor/sinkmanager/table_sink_advancer.go
  cdc/processor/sinkmanager/table_sink_advancer_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8363 redo(ticdc): add unit tests for redo meta manager
  cdc/redo/main_test.go
  cdc/redo/meta_manager.go
  cdc/redo/meta_manager_test.go
  cdc/redo/writer/file/file_log_writer_test.go
  cdc/redo/writer/file/file_test.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-6.5

#8418 model(ticdc): remove dead code
  cdc/model/changefeed.go
  cdc/model/owner.go
  cdc/model/sink.go
  cdc/model/sink_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#8426 owner(ticdc): only update epoch when state changes
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#8387 sink(ticdc): make the size of prep stmt cache adaptive based on the value of max_prepared_stmt_count and worker count
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/config_test.go
  pkg/sink/mysql/db_helper.go
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-6.6

#8409 apiv2(ticdc): refine open api v2 status code
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/owner.go
  cdc/api/v2/unsafe.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  tests/integration_tests/http_api_tls/util/test_case.py
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8421 sink(ticdc): convert values of pre-columns properly
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  tests/integration_tests/charset_gbk/data/test.sql
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8434 apiv2(ticdc): use time.Time in changefeed info
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/model.go
  pkg/cmd/cli/cli_changefeed_query.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8362 redo(ticdc): support for applying ddl event in applier
  cdc/model/codec/codec.go
  cdc/model/codec/codec_test.go
  cdc/model/sink.go
  cdc/model/sink_gen.go
  cdc/redo/reader/blackhole_reader.go
  cdc/redo/reader/file.go
  cdc/redo/reader/reader.go
  cdc/redo/reader/reader_test.go
  cdc/sink/ddlsink/factory/factory.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink_test.go
  pkg/applier/main_test.go
  pkg/applier/redo.go
  pkg/applier/redo_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XXL, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8412 ticdc(test): add more ut for kafka sink v2
  pkg/sink/kafka/v2/factory_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8445 *: upgrade tidb dependencies to newest
  cdc/entry/schema/snapshot.go
  dm/checker/checker.go
  dm/pkg/checker/lightning.go
  dm/pkg/checker/lightning_test.go
  go.mod
  go.sum
  pkg/sink/codec/csv/csv_decoder.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.6

#8452 sink (ticdc): disable batch update dml when downstream is mysql
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  tests/integration_tests/charset_gbk/data/test.sql
Labels: status/LGT2, status/can-merge, size/L, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8432 sink(ticdc): rename sinkv2 to sink in metrics
  cdc/sink/metrics/cloudstorage/metrics.go
  cdc/sink/metrics/metrics.go
  cdc/sink/metrics/mq/metrics.go
  cdc/sink/metrics/tablesink/metrics.go
  cdc/sink/metrics/txn/metrics.go
  metrics/grafana/TiCDC-Monitor-Summary.json
  metrics/grafana/ticdc.json
  pkg/sink/kafka/metrics.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, component/metrics-logging, release-note-none, area/ticdc

#8400 consumer(ticdc): fix resolvedTs and split transaction in storage consumer
  cdc/model/mounter.go
  cdc/model/mounter_test.go
  cmd/storage-consumer/main.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, needs-cherry-pick-release-6.5

#8447 sinkmanager(ticdc): bind metric labels value once
  cdc/processor/sinkmanager/table_sink_worker.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#8448 tests(ticdc): remove outdated integration test `processor_panic`
  tests/integration_tests/processor_panic/config.toml
  tests/integration_tests/processor_panic/diff_config.toml
  tests/integration_tests/processor_panic/main.go
  tests/integration_tests/processor_panic/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#8455 ddlsink(ticdc): correct some variable names
  cdc/sink/ddlsink/factory/factory.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
Labels: status/ptal, status/LGT2, status/can-merge, size/S, release-note-none, area/ticdc

#8450 entry(ticdc): clean up Synced state
  cdc/entry/mounter.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_storage_test.go
  cdc/entry/schema_test_helper.go
  pkg/filter/filter_test_helper.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none, area/ticdc

#8454 pkg(ticdc): remove deprecated interval tree merge function
  pkg/util/overlap_merge.go
  pkg/util/overlap_merge_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc, skip-issue-check

#8451 tests(ticdc): remove outdated integration test sorter
  tests/integration_tests/sorter/conf/diff_config.toml
  tests/integration_tests/sorter/conf/ticdc_unified_sorter.toml
  tests/integration_tests/sorter/conf/workload
  tests/integration_tests/sorter/run.sh
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#8469 errors(ticdc): clean up unused errors
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/errors/helper_test.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8444 apiv2(ticdc): add integration test for api v2
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/api_v2/main.go
  tests/integration_tests/api_v2/model.go
  tests/integration_tests/api_v2/request.go
  tests/integration_tests/api_v2/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8475 apiv2(ticdc): add ut test
  cdc/api/v2/capture.go
  cdc/api/v2/capture_test.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/log.go
  cdc/api/v2/log_test.go
  cdc/api/v2/model.go
  cdc/api/v2/owner_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8477 metrics(ticdc): fix conflict detect metric template
  metrics/grafana/ticdc.json
Labels: status/ptal, status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc, needs-cherry-pick-release-6.5

#8239 storage(dm): add gcs support for dm(engine)
  engine/executor/dm/worker.go
  engine/framework/base_jobmaster.go
  engine/framework/worker.go
  engine/jobmaster/dm/api_test.go
  engine/jobmaster/dm/dm_jobmaster.go
  engine/jobmaster/dm/dm_jobmaster_test.go
  engine/jobmaster/dm/openapi_test.go
  engine/jobmaster/dm/utils.go
  engine/jobmaster/dm/worker_manager.go
  engine/jobmaster/dm/worker_manager_test.go
  engine/pkg/externalresource/broker/broker.go
  engine/pkg/externalresource/broker/broker_integration_test.go
  engine/pkg/externalresource/broker/broker_test.go
  engine/pkg/externalresource/broker/interfaces.go
  engine/pkg/externalresource/broker/mock_broker.go
  engine/pkg/externalresource/broker/storage_handle.go
  engine/pkg/externalresource/internal/bucket/file_manager.go
  engine/pkg/externalresource/internal/bucket/file_manager_integration_test.go
  engine/pkg/externalresource/internal/bucket/file_manager_test.go
  engine/pkg/externalresource/internal/bucket/file_path_util.go
  engine/pkg/externalresource/internal/bucket/main_test.go
  engine/pkg/externalresource/internal/bucket/resource_controller.go
  engine/pkg/externalresource/internal/bucket/resource_controller_test.go
  engine/pkg/externalresource/internal/bucket/resource_desc.go
  engine/pkg/externalresource/internal/bucket/s3_dummy_resouce.go
  engine/pkg/externalresource/internal/bucket/s3_test_utils.go
  engine/pkg/externalresource/internal/bucket/storage_creator.go
  engine/pkg/externalresource/manager/gc_coordinator.go
  engine/pkg/externalresource/manager/gc_coordinator_test.go
  engine/pkg/externalresource/manager/gc_runner.go
  engine/pkg/externalresource/manager/gc_runner_test.go
  engine/pkg/externalresource/model/config.go
  engine/pkg/externalresource/model/config_test.go
  engine/pkg/externalresource/model/model.go
  engine/pkg/externalresource/model/model_test.go
  engine/servermaster/config.go
  engine/servermaster/config_test.go
  engine/servermaster/server.go
  engine/test/integration_tests/external_resource/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#8481 apiv2(ticdc): add ut for api default value
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8488 cli(ticdc): validate changefeed id in changefeed query command
  pkg/api/v2/changefeed.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#8489 config(ticdc): adjust config name
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed_test.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/compat/compat_test.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/keyspan/reconciler.go
  cdc/scheduler/internal/v3/keyspan/reconciler_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/scheduler_config.go
  tests/integration_tests/api_v2/model.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8278 consumer(ticdc): support handling DDL events in cloud storage consumer
  cmd/storage-consumer/main.go
  tests/integration_tests/_utils/run_storage_consumer
  tests/integration_tests/canal_json_storage_basic/run.sh
  tests/integration_tests/csv_storage_basic/run.sh
  tests/integration_tests/multi_tables_ddl/conf/error-1.toml
  tests/integration_tests/multi_tables_ddl/conf/error-2.toml
  tests/integration_tests/multi_tables_ddl/conf/normal.toml
  tests/integration_tests/multi_tables_ddl/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8465 config(dm): limit the length of hostname in binlog replication to 60
  dm/relay/relay.go
  dm/syncer/util.go
Labels: status/LGT2, status/can-merge, size/S, release-note

#8497 *: upgrade tidb version
  go.mod
  go.sum
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8476 feat(dm): using downstream DB to store lighting checkpoint
  dm/loader/lightning.go
  dm/loader/lightning_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note

#8436 sink(ticdc): use validateAndAdjustBound in redo log worker
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sinkmanager/redo_log_advancer.go
  cdc/processor/sinkmanager/redo_log_advancer_test.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/redo_log_worker_test.go
  cdc/processor/sinkmanager/table_sink_advancer.go
  cdc/processor/sinkmanager/table_sink_advancer_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sinkmanager/tasks.go
  cdc/processor/sinkmanager/tasks_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note-none, component/redolog

#8467 bugfix(ticdc): abort the changefeed creation if the downstream is MQ with the syncpoint feature enabled
  cdc/api/v2/api_helpers_test.go
  cdc/owner/owner.go
  cdc/sink/validator/validator.go
  cdc/sink/validator/validator_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8495 feat(cdc): allow updating of failed changefeed
  cdc/api/v1/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8504 apiv2(ticdc): add more integration tests about api v2
  tests/integration_tests/api_v2/cases.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8486 kafka(ticdc): add kafka go metrics collector and update monitoring panels
  cdc/sink/ddlsink/mq/ddlproducer/ddl_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_mock_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer_test.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/metrics/mq/metrics.go
  metrics/grafana/ticdc.json
  pkg/sink/kafka/metrics.go
  pkg/sink/kafka/metrics_collector.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/metrics_collector.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none

#8499 cdc: remove the delay for creating changefeed
  cdc/api/v1/api.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/owner/mock/owner_mock.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none

#8505 scheduler(ticdc): add splitter interface
  cdc/owner/changefeed.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/info_provider_test.go
  cdc/scheduler/internal/v3/keyspan/mock.go
  cdc/scheduler/internal/v3/keyspan/reconciler.go
  cdc/scheduler/internal/v3/keyspan/reconciler_test.go
  cdc/scheduler/internal/v3/keyspan/splitter_region_count.go
  cdc/scheduler/internal/v3/keyspan/splitter_region_count_test.go
  cdc/scheduler/rexport.go
Labels: status/LGT1, status/can-merge, size/XXL, require-LGT1, release-note-none, area/ticdc

#8502 mounter(ticdc): mount float32 value correctly to avoid the precision lost.
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#8511 processor(ticdc): make tests happy
  cdc/processor/manager_test.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/manager_test_helper.go
  cdc/processor/sinkmanager/redo_log_worker_test.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sourcemanager/engine/memory/event_sorter.go
  cdc/processor/sourcemanager/manager.go
  cdc/processor/sourcemanager/puller/dummy_puller_wrapper.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc

#8525 metrics(ticdc): move checkpoint ts and resolved ts p99 panels into lag analyze row
  metrics/grafana/ticdc.json
Labels: status/LGT2, status/can-merge, size/XL, release-note

#8526 kafka(ticdc): fix kafka sink panic when kill the downstream kafka
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
Labels: status/LGT2, status/can-merge, size/XS, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#8395 sink(ticdc): support multi statements in mysql backend
  cdc/sink/dmlsink/txn/mysql/mysql.go
  pkg/applier/redo_test.go
  pkg/sink/mysql/config.go
Labels: status/ptal, status/LGT2, status/can-merge, size/L, release-note, area/ticdc

#8530 sink(ticdc): reuse index number in storage sink
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_test.go
Labels: component/sink, status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc

#8496 scheduler(ticdc): split span by region written keys
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/keyspan/mock.go
  cdc/scheduler/internal/v3/keyspan/reconciler.go
  cdc/scheduler/internal/v3/keyspan/splitter_write.go
  cdc/scheduler/internal/v3/keyspan/splitter_write_test.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/replica_config_test.go
  pkg/config/scheduler_config.go
  pkg/pdutil/api_client.go
  pkg/pdutil/api_client_test.go
  pkg/spanz/span.go
  pkg/spanz/span_test.go
  tests/integration_tests/api_v2/model.go
Labels: status/LGT2, status/can-merge, size/XXL, release-note, area/ticdc

#8494 redo(ticdc): limit memory usage in applier
  cdc/processor/memquota/mem_quota.go
  cdc/redo/reader/reader.go
  errors.toml
  go.mod
  pkg/applier/redo.go
  pkg/errors/cdc_errors.go
  pkg/util/memory_checker.go
Labels: status/LGT2, status/can-merge, size/L, release-note

#8547 schema(ticdc): add unit test for handle key column
  cdc/entry/schema_storage_test.go
  cdc/model/sink.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8114 Support ALTER TABLE t REORGANIZE PARTITION
  cdc/entry/schema/snapshot.go
  cdc/entry/schema_storage_test.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/filter/utils_test.go
  pkg/sink/codec/canal/canal_entry.go
  tests/integration_tests/partition_table/data/prepare.sql
Labels: status/LGT2, status/can-merge, first-time-contributor, size/S, release-note

#8378 syncer(dm): discard checkpoint snapshot when syncer reset
  dm/syncer/checkpoint.go
  dm/syncer/checkpoint_test.go
  dm/syncer/syncer.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, area/dm, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8535 scheduler (ticdc): Add Barrier into scheduler heartbeat.
  cdc/model/changefeed.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_manager.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/scheduler/internal/agent.go
  cdc/scheduler/internal/scheduler.go
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/agent/agent_test.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_bench_test.go
  cdc/scheduler/internal/v3/coordinator_test.go
  cdc/scheduler/internal/v3/member/capture_manager.go
  cdc/scheduler/internal/v3/member/capture_manager_test.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager.go
  cdc/scheduler/schedulepb/table_schedule.pb.go
  cdc/scheduler/schedulepb/table_schedule.proto
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#8532 sink(cdc): fallback when preparing statements meets error
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/metrics/txn/metrics.go
  pkg/sink/mysql/config.go
  pkg/sink/mysql/config_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.6

#8556 dm: refine instrunction
  dm/pkg/checker/table_structure.go
  dm/pkg/checker/table_structure_test.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/dm

#8560 kafka(ticdc): ddl sink create admin client check error.
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#8567 codec(ticdc): avro decode float by using float32
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/avro/avro_test_data.go
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2, needs-cherry-pick-release-6.3, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#8501 dm: support schema isolation for lightning checkpoint when writing to downstream DB
  dm/loader/lightning.go
  dm/loader/lightning_test.go
  dm/pkg/cputil/table.go
  dm/pkg/cputil/table_test.go
  dm/pkg/utils/string.go
  dm/tests/all_mode/run.sh
  engine/test/integration_tests/dm_full_mode/run.sh
  engine/test/integration_tests/dm_lightning_checkpoint/conf/diff_config.toml
  engine/test/integration_tests/dm_lightning_checkpoint/conf/job.yaml
  engine/test/integration_tests/dm_lightning_checkpoint/conf/job2.yaml
  engine/test/integration_tests/dm_lightning_checkpoint/data/db1.prepare.sql
  engine/test/integration_tests/dm_lightning_checkpoint/data/db2.prepare.sql
  engine/test/integration_tests/dm_lightning_checkpoint/run.sh
  engine/test/integration_tests/e2e_fast_finished/run.sh
  engine/test/integration_tests/e2e_with_selectors/run.sh
  engine/test/utils/create_job
Labels: status/LGT2, status/can-merge, size/XL, release-note

#8580 redo(ticdc): fix data race issue in meta manager tests
  cdc/redo/main_test.go
  cdc/redo/meta_manager_test.go
Labels: status/LGT1, status/can-merge, size/S, require-LGT1, release-note-none, component/redolog, area/ticdc

#8553 mysql(ticdc): fix wrong dml order when batch DML is enabled
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#8265 ddl (ticdc): make ddl only block related tables
  cdc/entry/schema_storage.go
  cdc/model/owner.go
  cdc/model/owner_test.go
  cdc/owner/barrier.go
  cdc/owner/barrier_test.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_manager.go
  cdc/owner/ddl_manager_test.go
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
  cdc/owner/schema.go
  cdc/owner/schema_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/processor/sinkmanager/tasks.go
  cdc/puller/ddl_puller.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/scheduler/scheduler_manager.go
  tests/integration_tests/bdr_mode/run.sh
  tests/integration_tests/ddl_only_block_related_table/conf/diff_config.toml
  tests/integration_tests/ddl_only_block_related_table/conf/diff_config_2.toml
  tests/integration_tests/ddl_only_block_related_table/data/finishe.sql
  tests/integration_tests/ddl_only_block_related_table/data/start.sql
  tests/integration_tests/ddl_only_block_related_table/run.sh
  tests/integration_tests/ddl_reentrant/run.sh
  tests/integration_tests/multi_tables_ddl/run.sh
Labels: status/LGT2, status/can-merge, size/XXL, release-note

#8585 sink(cdc): don't block table sink when dml backends exit
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/sink/dmlsink/blackhole/black_hole_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/event_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/txn/txn_dml_sink.go
  cdc/sink/dmlsink/txn/worker.go
  cdc/sink/tablesink/progress_tracker.go
  cdc/sink/tablesink/progress_tracker_test.go
  cdc/sink/tablesink/table_sink.go
  cdc/sink/tablesink/table_sink_impl.go
  cdc/sink/tablesink/table_sink_impl_test.go
  pkg/applier/redo.go
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6

#8550 mq(ticdc): Add ut for kafka go sink
  pkg/sink/kafka/v2/admin_test.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/factory_test.go
  pkg/sink/kafka/v2/manual_balancer_test.go
  pkg/sink/kafka/v2/metrics_collector.go
  pkg/sink/kafka/v2/metrics_collector_test.go
  pkg/sink/kafka/v2/mock/writer_mock.go
  pkg/sink/kafka/v2/writer.go
  scripts/generate-mock.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none

#8590 Makefile: bump version to v7.1.0
  Makefile
Labels: status/LGT2, status/can-merge, size/XS, release-note-none

#8600 tests(ticdc): fix inaccurate DDL finish ts
  tests/integration_tests/bank/bank.go
  tests/integration_tests/bank/case.go
  tests/integration_tests/bank/run.sh
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc, needs-cherry-pick-release-7.0

#8607 kv(ticdc): fix syncRegionFeedStateMap concurrent access
  cdc/kv/region_state.go
  cdc/kv/region_state_bench_test.go
  cdc/kv/region_worker.go
Labels: status/LGT2, status/can-merge, size/L, release-note-none, area/ticdc, needs-cherry-pick-release-6.4, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#8589 sorter(ticdc): use correct cgroup memory limit in some scenarios
  cdc/server/server.go
  go.mod
  go.sum
  pkg/util/memory.go
  pkg/util/memory_test.go
Labels: status/ptal, status/LGT2, status/can-merge, size/M, release-note, area/ticdc, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0

#8619 dm-worker: fix Lightning version info
  Makefile
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-7.0

#8411 tests(ticdc): add ddl test for redo
  cdc/owner/changefeed.go
  cdc/owner/ddl_manager.go
  cdc/owner/ddl_manager_test.go
  cdc/redo/reader/file.go
  cdc/redo/reader/mock_fileReader.go
  pkg/applier/redo.go
  tests/integration_tests/consistent_replicate_ddl/conf/changefeed.toml
  tests/integration_tests/consistent_replicate_ddl/conf/diff_config.toml
  tests/integration_tests/consistent_replicate_ddl/conf/workload
  tests/integration_tests/consistent_replicate_ddl/run.sh
Labels: status/LGT2, status/can-merge, size/XL, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0

#8627 sink(ticdc): add max allowed packet parmameters in sink dsn
  pkg/sink/mysql/db_helper.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, area/ticdc, needs-cherry-pick-release-7.0

#8620 redo(ticdc): fix resolvedTs regression in applier's memory quota record
  pkg/applier/redo.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.0

#8579 kafka(ticdc): close the async write asynchronously to prevent block the cdc server
  pkg/sink/kafka/v2/admin.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/factory_test.go
  pkg/sink/kafka/v2/metrics_collector.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8652 sink(ticdc): turn off multi statement sql by default
  pkg/sink/mysql/config.go
Labels: status/LGT2, status/can-merge, size/XS, cherry-pick-approved, release-note-none, area/ticdc

#8542 mq(ticdc): add txn event encoder
  cdc/sink/ddlsink/mq/mq_ddl_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink_test.go
  cdc/sink/dmlsink/cloudstorage/defragmenter_test.go
  cdc/sink/dmlsink/cloudstorage/encoding_worker.go
  cdc/sink/dmlsink/cloudstorage/encoding_worker_test.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/worker.go
  cdc/sink/dmlsink/mq/worker_test.go
  cmd/kafka-consumer/main.go
  cmd/storage-consumer/main.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/builder/codec_test.go
  pkg/sink/codec/builder/encoder_builder.go
  pkg/sink/codec/canal/canal_encoder.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_decoder_test.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_json_txn_event_encoder.go
  pkg/sink/codec/canal/canal_json_txn_event_encoder_test.go
  pkg/sink/codec/craft/craft_decoder.go
  pkg/sink/codec/craft/craft_encoder.go
  pkg/sink/codec/craft/craft_encoder_test.go
  pkg/sink/codec/csv/csv_decoder.go
  pkg/sink/codec/csv/csv_encoder.go
  pkg/sink/codec/csv/csv_encoder_test.go
  pkg/sink/codec/decoder.go
  pkg/sink/codec/encoder.go
  pkg/sink/codec/encoder_group.go
  pkg/sink/codec/internal/batch_tester.go
  pkg/sink/codec/maxwell/maxwell_encoder.go
  pkg/sink/codec/open/open_protocol_decoder.go
  pkg/sink/codec/open/open_protocol_encoder.go
Labels: component/sink, status/LGT2, status/can-merge, size/XXL, release-note, area/ticdc

#8653 dm: fix lightning config problem
  dm/_utils/terror_gen/errors_release.txt
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_test.go
  dm/errors.toml
  dm/loader/lightning.go
  dm/loader/lightning_test.go
  dm/pkg/terror/errcode_string.go
  dm/pkg/terror/error_list.go
  dm/tests/dmctl_basic/conf/get_task.yaml
  dm/tests/import_v10x/conf/task.yaml
Labels: status/LGT2, status/can-merge, size/XXL, release-note-none, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#8638 dm: Fix panic in openapi
  dm/master/openapi_view.go
Labels: status/LGT2, status/can-merge, size/XS, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5

#8670 *(pkg): retry on invalid connection
  dm/pkg/retry/errors.go
  pkg/errorutil/util.go
  pkg/errorutil/util_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-6.6, needs-cherry-pick-release-7.0

#8680 DM: fix default physical import mode disk quota
  dm/loader/lightning.go
  dm/loader/lightning_test.go
Labels: status/LGT2, status/can-merge, size/XS, cherry-pick-approved, release-note-none

#8629 config (ticdc): fix a data race in changefeed initializing
  cdc/api/v2/api_helpers.go
  cdc/sink/ddlsink/factory/factory.go
  cdc/sink/dmlsink/factory/factory.go
  cdc/sink/dmlsink/factory/factory_test.go
  pkg/config/replica_config.go
  pkg/sink/observer/observer.go
Labels: status/LGT2, status/can-merge, size/M, release-note-none

#8687 engine(dm): fix unstable engine test dm_lightning_checkpoint
  engine/test/integration_tests/dm_lightning_checkpoint/run.sh
Labels: status/ptal, component/test, status/LGT2, status/can-merge, size/XS, release-note, area/dm

#8665 sinkManager (ticdc): Fix a sorter panic issue caused by uint64 overflow.
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
Labels: status/LGT2, status/can-merge, size/S, release-note, needs-cherry-pick-release-7.0

#8671 DM: fix default physical import mode disk quota
  dm/loader/lightning.go
  dm/loader/lightning_test.go
Labels: status/LGT2, status/can-merge, size/XS, release-note-none, needs-cherry-pick-release-7.0

#8540 doc(ticdc): add design document for storage sink
  docs/design/2023-03-15-ticdc-storage-sink.md
Labels: component/docs, status/LGT2, status/can-merge, size/XL, release-note-none, area/ticdc, needs-cherry-pick-release-7.0

#8705 syncer(dm): fix wrong MySQL latin1 decoder
  dm/syncer/dml.go
  dm/tests/expression_filter/conf/dm-task2.yaml
  dm/tests/expression_filter/data/db1.increment2.sql
  dm/tests/expression_filter/data/db1.prepare2.sql
  dm/tests/expression_filter/run.sh
Labels: status/LGT2, status/can-merge, size/S, release-note-none, needs-cherry-pick-release-5.3, needs-cherry-pick-release-5.4, needs-cherry-pick-release-6.0, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.2

#8587 docs (ticdc): add a RFC of make ddl only blocks related table.
  docs/RFCS/20230320_ddl_block_related_table.md
  docs/media/ddl_block_related_table_1.png
  docs/media/ddl_block_related_table_2.png
Labels: status/LGT2, status/can-merge, size/M, release-note, needs-cherry-pick-release-6.5
