Repository pingcap/tiflow, pull requests merged in 2024-06, with the labels that each got.

#11222 encoder(ticdc): fix simple decoder set index column offset incorrect
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/utils/test_utils.go
Labels: size/M, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11234 *(cdc): accept access denied error when query tidb_version
  cdc/sinkv2/eventsink/txn/mysql/mysql_test.go
  pkg/sink/mysql/db_helper.go
Labels: size/XS, release-note-none, approved, lgtm

#11198 dep: update tidb package
  dm/checker/checker.go
  dm/checker/cmd.go
  dm/tests/check_task/run.sh
  go.mod
  go.sum
Labels: size/L, release-note-none, area/dm, skip-issue-check, needs-cherry-pick-release-6.5, approved, lgtm

#11235 codec(ticdc): simple decoder set column flag incorrectly since miss index id
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
Labels: size/M, release-note-none, approved, lgtm

#11247 ticdc: Add test for ddl `exchange partition ... without validation`
  tests/integration_tests/ddl_reentrant/run.sh
Labels: size/XS, release-note, approved, lgtm

#11214 mysql(ticdc): remove error filter when check isTiDB in backend init
  pkg/sink/mysql/db_helper.go
Labels: size/XS, release-note-none, approved, lgtm

#11252 kafka(ticdc): producer accept message struct as parameter to simplify the signature
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/factory_test.go
Labels: size/L, release-note-none, approved, lgtm

#11223 codec(ticdc): csv and maxwell unit test use schema test helper to reduce code complexity
  pkg/sink/codec/csv/csv_decoder_test.go
  pkg/sink/codec/csv/csv_encoder_test.go
  pkg/sink/codec/maxwell/maxwell_encoder_test.go
  pkg/sink/codec/maxwell/maxwell_message_test.go
  pkg/sink/codec/utils/field_types.go
Labels: size/L, release-note-none, approved, lgtm

#11269 puller(ticdc): fix wrong update splitting behavior after table scheduling
  cdc/model/kv.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/manager_test_helper.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sourcemanager/manager.go
  cdc/processor/sourcemanager/puller/dummy_puller_wrapper.go
  cdc/processor/sourcemanager/puller/multiplexing_puller_wrapper.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/multiplexing_puller.go
  cdc/puller/multiplexing_puller_test.go
Labels: size/L, cherry-pick-approved, release-note-none, approved, lgtm

#11251 cdc: log slow conflict detect every 60s
  cdc/sink/dmlsink/txn/worker.go
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11280 owner(cdc): drain warnings when closing changefeed
  cdc/owner/changefeed.go
  cdc/owner/feed_state_manager.go
Labels: size/S, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#11279 sorter(cdc): fix a bug that Pebble sorter can be stucked when closing a processor
  cdc/processor/sourcemanager/sorter/pebble/event_sorter.go
Labels: size/XS, release-note-none, approved, lgtm

#11226 pkg/config, sink(ticdc): support output raw change event for mq and cloud storage sink
  cdc/api/v2/model.go
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/processor/sinkmanager/table_sink_wrapper_test.go
  cdc/sink/dmlsink/blackhole/black_hole_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/event.go
  cdc/sink/dmlsink/event_sink.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/pulsar_dml_sink.go
  cdc/sink/dmlsink/txn/txn_dml_sink.go
  cdc/sink/tablesink/table_sink_impl.go
  cdc/sink/tablesink/table_sink_impl_test.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  errors.toml
  pkg/config/sink.go
  pkg/errors/cdc_errors.go
  pkg/sink/codec/csv/csv_message.go
  tests/integration_tests/csv_storage_update_pk_clustered/conf/changefeed1.toml
  tests/integration_tests/csv_storage_update_pk_clustered/conf/changefeed2.toml
  tests/integration_tests/csv_storage_update_pk_clustered/conf/changefeed3.toml
  tests/integration_tests/csv_storage_update_pk_clustered/conf/changefeed4.toml
  tests/integration_tests/csv_storage_update_pk_clustered/conf/diff_config.toml
  tests/integration_tests/csv_storage_update_pk_clustered/data/prepare.sql
  tests/integration_tests/csv_storage_update_pk_clustered/data/run.sql
  tests/integration_tests/csv_storage_update_pk_clustered/result/changefeed1_pk.res
  tests/integration_tests/csv_storage_update_pk_clustered/result/changefeed1_uk.res
  tests/integration_tests/csv_storage_update_pk_clustered/result/changefeed2_pk.res
  tests/integration_tests/csv_storage_update_pk_clustered/result/changefeed2_uk.res
  tests/integration_tests/csv_storage_update_pk_clustered/result/changefeed3_pk.res
  tests/integration_tests/csv_storage_update_pk_clustered/result/changefeed3_uk.res
  tests/integration_tests/csv_storage_update_pk_clustered/result/changefeed4_pk.res
  tests/integration_tests/csv_storage_update_pk_clustered/result/changefeed4_uk.res
  tests/integration_tests/csv_storage_update_pk_clustered/run.sh
  tests/integration_tests/csv_storage_update_pk_nonclustered/conf/changefeed1.toml
  tests/integration_tests/csv_storage_update_pk_nonclustered/conf/changefeed2.toml
  tests/integration_tests/csv_storage_update_pk_nonclustered/conf/changefeed3.toml
  tests/integration_tests/csv_storage_update_pk_nonclustered/conf/changefeed4.toml
  tests/integration_tests/csv_storage_update_pk_nonclustered/conf/diff_config.toml
  tests/integration_tests/csv_storage_update_pk_nonclustered/data/prepare.sql
  tests/integration_tests/csv_storage_update_pk_nonclustered/data/run.sql
  tests/integration_tests/csv_storage_update_pk_nonclustered/result/changefeed1_pk.res
  tests/integration_tests/csv_storage_update_pk_nonclustered/result/changefeed1_uk.res
  tests/integration_tests/csv_storage_update_pk_nonclustered/result/changefeed2_pk.res
  tests/integration_tests/csv_storage_update_pk_nonclustered/result/changefeed2_uk.res
  tests/integration_tests/csv_storage_update_pk_nonclustered/result/changefeed3_pk.res
  tests/integration_tests/csv_storage_update_pk_nonclustered/result/changefeed3_uk.res
  tests/integration_tests/csv_storage_update_pk_nonclustered/result/changefeed4_pk.res
  tests/integration_tests/csv_storage_update_pk_nonclustered/result/changefeed4_uk.res
  tests/integration_tests/csv_storage_update_pk_nonclustered/run.sh
  tests/integration_tests/run_group.sh
Labels: size/XXL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, affect-ticdc-config-docs, needs-cherry-pick-release-8.1

#11262 ddl(ticdc): support batch create table ddl
  cdc/entry/mounter.go
  cdc/entry/schema/snapshot.go
  cdc/entry/schema_storage.go
  cdc/puller/ddl_puller.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  tests/integration_tests/batch_add_table/conf/changefeed.toml
  tests/integration_tests/batch_add_table/data/prepare.sql
  tests/integration_tests/batch_add_table/data/test.sql
  tests/integration_tests/batch_add_table/run.sh
Labels: size/L, release-note-none, approved, lgtm

#11253 ticdc: change the calculation of first sync point ts
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  tests/integration_tests/run_group.sh
  tests/integration_tests/syncpoint_check_ts/conf/changefeed.toml
  tests/integration_tests/syncpoint_check_ts/run.sh
Labels: size/L, release-note, approved, lgtm, affect-ticdc-config-docs

#11296 puller(ticdc): fix wrong update splitting behavior after table scheduling
  cdc/model/kv.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/manager_test_helper.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_wrapper.go
  cdc/processor/sourcemanager/manager.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
  cdc/puller/multiplexing_puller.go
  cdc/puller/multiplexing_puller_test.go
Labels: size/L, release-note-none, approved, lgtm

#11182 pkg/p2p(ticdc): fix default p2p config
  cdc/puller/multiplexing_puller.go
  cdc/scheduler/internal/v3/agent/table.go
  cdc/scheduler/internal/v3/transport/transport.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/messages.go
Labels: size/M, release-note-none, approved, lgtm, affect-ticdc-config-docs

#11312 s3(ticdc): do not report unretryable error when initializing s3 storage
  pkg/redo/config.go
Labels: size/XS, release-note-none, approved, lgtm

#11217 entry (ticdc): speed up schema snapshot initialization
  cdc/entry/schema/snapshot.go
  cdc/entry/schema_test.go
  cdc/entry/validator.go
  go.mod
  go.sum
  tests/integration_tests/batch_add_table/run.sh
  tests/integration_tests/http_api_tls/run.sh
Labels: size/L, release-note-none, approved, lgtm

#11320 redo(ticdc): fix orderliness of redo
  cdc/model/sink.go
  cdc/redo/reader/reader.go
  cdc/redo/reader/reader_test.go
Labels: size/L, cherry-pick-approved, release-note-none, approved, lgtm

#11324 Revert "cdc: log slow conflict detect every 60s (#11251) (#11287)"
  cdc/sinkv2/eventsink/txn/worker.go
Labels: size/M, cherry-pick-approved, release-note-none, approved, lgtm

#11313 metrics(ticdc): Fix kafka compress ratio issue
  metrics/grafana/ticdc.json
  pkg/sink/codec/common/compress.go
  pkg/sink/kafka/metrics_collector.go
Labels: size/XS, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#10990 cmd (ticdc): a better Kafka consumer
  Makefile
  cmd/kafka-consumer/consumer.go
  cmd/kafka-consumer/event_group.go
  cmd/kafka-consumer/main.go
  cmd/kafka-consumer/option.go
  cmd/kafka-consumer/writer.go
  deployments/ticdc/docker/kafka-consumer.Dockerfile
  go.mod
  go.sum
Labels: size/XXL, contribution, release-note-none, area/ticdc, ok-to-test, approved, lgtm

#11328 tools: bump golang.org/x/tools to v0.22.0 to fix panic on the mac os sonoma
  dm/master/openapi_controller.go
  dm/master/openapi_controller_test.go
  dm/master/server.go
  engine/pkg/meta/mock/simple_mockclient.go
  tools/check/go.mod
  tools/check/go.sum
Labels: size/M, release-note-none, area/dm, area/engine, approved, lgtm

#11239 simple (ticdc): support send all tables bootstrap message at changefeed start
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/entry/schema_test_helper.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_manager.go
  cdc/owner/ddl_manager_test.go
  cdc/owner/ddl_sink.go
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/sink.go
  pkg/config/sink_test.go
  pkg/orchestrator/reactor_state_test.go
  tests/integration_tests/kafka_simple_basic/conf/changefeed.toml
Labels: size/L, release-note-none, approved, lgtm, affect-ticdc-config-docs

#11330 kv: remove useless grpc pool
  cdc/kv/grpc_pool.go
  cdc/kv/grpc_pool_impl.go
  cdc/kv/grpc_pool_impl_test.go
  cdc/kv/shared_client.go
  pkg/upstream/upstream.go
Labels: size/XL, release-note-none, approved, lgtm

#11013 sink(ticdc): add ut case for open protocol
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/codec/open/open_protocol_message.go
Labels: size/M, release-note-none, approved, lgtm

#11338 ticdc : http & https support in pulsar schema for pulsar downstream type changefeed creation.
  cdc/sink/ddlsink/factory/factory.go
  cdc/sink/ddlsink/mq/pulsar_ddl_sink_test.go
  cdc/sink/dmlsink/factory/factory.go
  cdc/sink/dmlsink/mq/dmlproducer/pulsar_dml_producer_test.go
  pkg/config/sink.go
  pkg/sink/pulsar/config.go
  pkg/sink/pulsar/config_test.go
  pkg/sink/sink_type.go
Labels: first-time-contributor, size/XL, contribution, release-note, ok-to-test, approved, lgtm, affect-ticdc-config-docs

#11348 metrics(ticdc): add kafka compression ratio description for grafana
  metrics/grafana/ticdc.json
Labels: size/XS, release-note-none, approved, lgtm, affects-7.5, affects-8.1

#11350 consumer(ticdc): do not panic the consumer if visit the kafka broker meet error
  cmd/kafka-consumer/consumer.go
  cmd/kafka-consumer/writer.go
Labels: size/S, release-note-none, approved, lgtm

#11359 filter(ticdc): Add `lightning_task_info` as the system table schema that should not be replicated by TiCDC
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/filter/utils.go
Labels: size/XS, release-note, approved, lgtm
