Repository pingcap/tiflow, pull requests merged in 2024-11, with the labels that each got.

#11709 *(dm): add redact log config for dm worker
  cmd/dm-worker/main.go
  dm/pkg/conn/baseconn.go
  dm/pkg/conn/basedb.go
  dm/pkg/log/log.go
  dm/syncer/dbconn/db.go
  dm/tests/dmctl_basic/conf/get_worker1.toml
  dm/tests/dmctl_basic/conf/get_worker2.toml
  dm/worker/config.go
Labels: size/M, contribution, release-note, area/dm, needs-update-docs, ok-to-test, approved, lgtm

#11703 tests: add foreign key tests with log filter
  tests/integration_tests/foreign_key/conf/cf.toml
  tests/integration_tests/foreign_key/conf/diff_config.toml
  tests/integration_tests/foreign_key/data/prepare.sql
  tests/integration_tests/foreign_key/run.sh
Labels: size/S, release-note-none, approved, lgtm

#11715 scheduler(ticdc): fix span loss bug when split regions
  cdc/scheduler/internal/v3/keyspan/splitter_write.go
  cdc/scheduler/internal/v3/keyspan/splitter_write_test.go
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#11720 mounter(ticdc): calculate raw bytes checksum by using handle
  cdc/entry/mounter.go
  cdc/puller/ddl_puller_test.go
  go.mod
  go.sum
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/common/helper.go
Labels: size/L, release-note-none, approved, lgtm, needs-cherry-pick-release-8.5, needs-cherry-pick-release-8.4

#11740 syncer(dm): add more comment about causality(or dependency detect)
  dm/syncer/causality.go
Labels: size/S, release-note, area/dm, skip-issue-check, approved, lgtm

#11729 dm: support dump task mode in openapi
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/tests/_utils/run_dm_ctl_with_retry
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/run.sh
Labels: first-time-contributor, size/L, contribution, release-note, area/dm, ok-to-test, approved, lgtm

#11733 ddl_puller.go(ticdc): fix DDLs are ignored when schema versions are out of order
  cdc/puller/ddl_puller.go
Labels: size/XS, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#11747 ticdc(redo, sink): return correct error in redo writer & fix default retryer
  cdc/redo/writer/memory/encoding_worker.go
  cdc/redo/writer/memory/mem_log_writer_test.go
  pkg/redo/config.go
  pkg/sink/kafka/claimcheck/claim_check.go
  pkg/util/external_storage.go
Labels: size/M, release-note, approved, lgtm

#11770 fix resign owner api not processed by owner node bug
  cdc/api/v2/api.go
  tests/integration_tests/availability/owner.sh
Labels: size/M, release-note-none, approved, lgtm

#11776 *: upgrade tidb to include fix
  dm/pkg/parser/common_test.go
  go.mod
  go.sum
Labels: size/L, release-note, area/dm, approved, lgtm, needs-cherry-pick-release-8.5

#11783 Redact query arguments in dm log
  dm/syncer/dbconn/db.go
Labels: size/XS, contribution, release-note, area/dm, ok-to-test, approved, lgtm

#11743 dm: handle the query in metadata from binlog
  dm/pkg/dumpling/utils.go
  dm/pkg/dumpling/utils_test.go
Labels: size/S, release-note-none, area/dm, approved, lgtm

#11775 sink(ticdc): limit encoder-concurrency to avoid crash
  pkg/sink/codec/encoder_group.go
Labels: size/XS, release-note-none, approved, lgtm

#11745 dm: fix upstream switch job test
  .github/workflows/dataflow_engine_chaos.yaml
  .github/workflows/dm_upstream_switch.yaml
  dm/tests/upstream_switch/case.sh
Labels: size/M, release-note-none, area/dm, approved, lgtm

#11726 dm: fix binlog 999999 test
  .github/workflows/dm_binlog_999999.yaml
Labels: component/test, first-time-contributor, size/M, contribution, release-note, area/dm, ok-to-test, approved, lgtm

#11191 alert(ticdc): fix ticdc alert rules
  cdc/api/v2/api_helpers.go
  metrics/alertmanager/ticdc.rules.yml
Labels: size/S, release-note-none, approved, lgtm

#11407 tests(ticdc): fix bank test
  cdc/owner/ddl_manager.go
  tests/integration_tests/bank/case.go
  tests/integration_tests/bank/run.sh
Labels: size/M, release-note, approved, lgtm

#11742 dm: add TCP connection IO traffic statistics to sync stage status in OpenAPI response
  cdc/processor/tablepb/table.pb.go
  dm/config/subtask.go
  dm/config/subtask_test.go
  dm/config/task_converters.go
  dm/config/task_converters_test.go
  dm/config/task_test.go
  dm/master/openapi_controller.go
  dm/master/openapi_view_test.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/pb/dmworker.pb.go
  dm/proto/dmworker.proto
  dm/syncer/status.go
  dm/syncer/syncer.go
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/run.sh
  engine/enginepb/datarw.pb.go
  engine/enginepb/executor.pb.go
  engine/enginepb/master.pb.go
  engine/enginepb/projects.pb.go
  engine/enginepb/resources.pb.go
  engine/enginepb/test.pb.go
  tools/check/go.mod
  tools/check/go.sum
Labels: first-time-contributor, size/XXL, contribution, release-note, area/dm, area/engine, ok-to-test, approved, lgtm
