Repository pingcap/tiflow, pull requests merged in 2024-05, with the labels that each got.

#10919 *(ticdc): split old update kv entry after restarting changefeed
  cdc/model/kv.go
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sourcemanager/manager.go
  cdc/redo/reader/reader.go
  cdc/sink/dmlsink/factory/factory.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  cmd/kafka-consumer/main.go
  cmd/pulsar-consumer/main.go
  cmd/storage-consumer/main.go
  errors.toml
  pkg/applier/redo.go
  pkg/applier/redo_test.go
  pkg/errors/cdc_errors.go
  pkg/errors/helper.go
  pkg/sink/codec/open/open_protocol_decoder.go
  tests/integration_tests/changefeed_dup_error_restart/conf/diff_config.toml
  tests/integration_tests/changefeed_dup_error_restart/conf/workload
  tests/integration_tests/changefeed_dup_error_restart/run.sh
  tests/integration_tests/force_replicate_table/run.sh
  tests/integration_tests/kafka_simple_handle_key_only_avro/conf/diff_config.toml
  tests/integration_tests/run_group.sh
Labels: size/XXL, release-note, approved, lgtm

#11024 kafka(ticdc): Fix java example license issue
  examples/java/pom.xml
Labels: size/S, release-note-none, approved, lgtm, needs-cherry-pick-release-8.1

#11021 sink (ticdc): fix sourceID error
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test_helper.go
  pkg/sink/mysql/config.go
Labels: size/M, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11023 test(ticdc): enable sequence test
  scripts/download-integration-test-binaries.sh
  tests/integration_tests/sequence/run.sh
Labels: size/XS, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#10854 ticdc: support detecting the Kafka cluster version automatically
  pkg/sink/kafka/options.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/sarama.go
  pkg/sink/kafka/sarama_factory_test.go
  pkg/sink/kafka/sarama_test.go
Labels: first-time-contributor, size/L, contribution, release-note-none, needs-ok-to-test, approved, lgtm

#10907 ticdc: Support `create table` ddl only appear in tidb_ddl_history instead of tidb_ddl_job table
  cdc/entry/mounter.go
  cdc/puller/ddl_puller.go
  pkg/spanz/span.go
  tests/integration_tests/batch_add_table/run.sh
  tests/integration_tests/multi_source/run.sh
Labels: size/L, release-note-none, approved, lgtm

#10971 sink(ticdc): only enable batch dml for more than one row
  cdc/sink/dmlsink/txn/mysql/dml.go
  cdc/sink/dmlsink/txn/mysql/dml_test.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
Labels: size/M, release-note-none, approved, lgtm

#11031 simple (ticdc): fix bootstrap event is not sent
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  pkg/sink/codec/bootstraper.go
Labels: size/XS, cherry-pick-approved, release-note-none, approved, lgtm

#10207 syncer(dm): Ignore SET statement for MariaDB
  dm/syncer/syncer.go
Labels: size/M, release-note, approved, lgtm

#11064 schema(ticdc): query the primary key column names in an easier way
  cdc/entry/schema_storage_test.go
  cdc/model/schema_storage.go
Labels: size/M, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#11061 checker(dm): make precheck warn/error limit public
  dm/checker/check_test.go
  dm/checker/checker.go
  dm/checker/cmd.go
Labels: size/L, release-note, approved, lgtm

#11070 dep: update tidb-tools
  dm/pkg/utils/common.go
  go.mod
  go.sum
Labels: size/M, release-note, skip-issue-check, approved, lgtm

#11077 kv (ticdc): reduce some verbose log
  cdc/kv/shared_client.go
  cdc/kv/shared_client_test.go
  pkg/txnutil/lock_resolver.go
Labels: size/M, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11058 tests(ticdc): simple protocol claim check integration test enable checksum
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/marshaller.go
  pkg/sink/codec/simple/message.go
  tests/integration_tests/kafka_simple_claim_check/conf/changefeed.toml
  tests/integration_tests/kafka_simple_claim_check/run.sh
  tests/integration_tests/kafka_simple_claim_check_avro/conf/changefeed.toml
  tests/integration_tests/kafka_simple_claim_check_avro/run.sh
  tests/integration_tests/kafka_simple_handle_key_only/conf/changefeed.toml
  tests/integration_tests/kafka_simple_handle_key_only/run.sh
  tests/integration_tests/kafka_simple_handle_key_only_avro/conf/changefeed.toml
  tests/integration_tests/kafka_simple_handle_key_only_avro/run.sh
Labels: size/XXL, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#11042 owner(ticdc): update changefeed configuration changefeed-error-stuck-duration correctly
  cdc/owner/feed_state_manager.go
  cdc/owner/feed_state_manager_test.go
Labels: size/L, contribution, release-note-none, ok-to-test, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11076 pdClient (ticdc): Enable the pdClient forwarding function to make cdc more stable during network isolation between the PD leader
  cdc/api/v2/api_helpers.go
  cdc/server/server.go
  pkg/config/server_config.go
  pkg/migrate/migrate.go
  pkg/upstream/upstream.go
Labels: size/S, release-note, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11011 redo(ticdc): return internal error in redo writer
  cdc/redo/writer/memory/encoding_worker.go
  cdc/redo/writer/memory/file_worker.go
  cdc/redo/writer/memory/mem_log_writer_test.go
Labels: size/M, release-note-none, approved, lgtm

#11087 dm: fix panic of openapi operate-schema
  dm/tests/openapi/run.sh
  dm/worker/subtask.go
Labels: size/S, release-note, approved, lgtm

#11094 *: move binlog-filter package to tiflow
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cmd/dm-syncer/config.go
  dm/config/source_config.go
  dm/config/source_config_test.go
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_converters.go
  dm/config/task_converters_test.go
  dm/config/task_test.go
  dm/master/bootstrap_test.go
  dm/syncer/ddl.go
  dm/syncer/filter.go
  dm/syncer/filter_test.go
  dm/syncer/syncer.go
  dm/syncer/syncer_test.go
  dm/worker/source_worker.go
  engine/jobmaster/dm/config/config.go
  pkg/binlog-filter/filter.go
  pkg/binlog-filter/filter_test.go
  pkg/binlog-filter/util.go
  pkg/config/filter.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/filter/sql_event_filter.go
  pkg/filter/sql_event_filter_test.go
  pkg/filter/utils.go
Labels: size/XXL, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5, affect-ticdc-config-docs

#11101 ci: add prow OWNERS for dm and engine modules
  OWNERS_ALIASES
  cmd/dm-ctl/OWNERS
  cmd/dm-master/OWNERS
  cmd/dm-syncer/OWNERS
  cmd/dm-worker/OWNERS
  dm/OWNERS
  engine/OWNERS
Labels: size/M, release-note-none, approved, lgtm

#11098 codec(ticdc): simple protocol introduce mock marshaller to improve ut coverage
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/simple/mock/marshaller.go
  scripts/generate-mock.sh
Labels: size/L, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5

#10954 pkg/causality(cdc): refactor and simplify conflict detector
  cdc/sink/dmlsink/txn/event.go
  cdc/sink/dmlsink/txn/event_test.go
  pkg/causality/conflict_detector.go
  pkg/causality/internal/main_test.go
  pkg/causality/internal/node.go
  pkg/causality/internal/node_test.go
  pkg/causality/internal/slots.go
  pkg/causality/internal/slots_test.go
  pkg/causality/tests/integration_test.go
  pkg/causality/tests/worker.go
  pkg/causality/txn_cache.go
  pkg/causality/txn_cache_test.go
Labels: size/XL, release-note, approved, lgtm

#11112 dep(dm): move column-mapping from tidb-tools to tiflow repo
  dm/config/subtask.go
  dm/config/task.go
  dm/config/task_converters.go
  dm/syncer/syncer_test.go
  engine/jobmaster/dm/config/config.go
  pkg/column-mapping/column.go
  pkg/column-mapping/column_test.go
Labels: size/XXL, release-note-none, area/dm, area/engine, approved, lgtm

#11116 dm: support empty check for physical mode
  dm/checker/check_test.go
  dm/checker/checker.go
  dm/config/checking_item.go
  dm/config/checking_item_test.go
  dm/pkg/checker/binlog.go
  dm/pkg/checker/lightning.go
  dm/pkg/checker/lightning_test.go
  dm/pkg/dumpling/utils.go
Labels: size/L, release-note, area/dm, approved, lgtm

#11095 snapshot (ticdc): reduce list tables time consumption
  cdc/entry/schema/snapshot.go
Labels: size/M, release-note, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11089 codec(ticdc): simple decoder set the table id on handle key only event and make consumer more strict on the ts order
  cmd/kafka-consumer/main.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/message.go
Labels: size/L, release-note-none, approved, lgtm

#11117 (redo)ticdc: fix the event orderliness in redo log
  cdc/redo/reader/reader.go
  cdc/redo/reader/reader_test.go
  pkg/applier/redo.go
Labels: size/XXL, release-note-none, approved, lgtm

#11099 cdc: adjust sorter options to avoid Seek CPU usage exploding
  cdc/processor/sourcemanager/sorter/pebble/db.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/db.go
  pkg/config/server_config.go
  pkg/spanz/hash_map.go
Labels: size/S, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, affect-ticdc-config-docs, needs-cherry-pick-release-8.1

#11048 ticdc: fix detecting kafka version
  pkg/sink/kafka/options.go
  pkg/sink/kafka/sarama.go
  pkg/sink/kafka/sarama_factory_test.go
Labels: size/M, contribution, release-note-none, needs-ok-to-test, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11129 *(cdc): accept access denied error when query tidb_version
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  pkg/sink/mysql/db_helper.go
Labels: size/XS, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11122 dep(*): remove usage of tidb-tools/pkg/{dbutil, utils}
  cmd/tiflow/main.go
  dm/ctl/common/util.go
  dm/master/election.go
  dm/master/etcd.go
  dm/master/metrics/metrics.go
  dm/master/server.go
  dm/master/server_test.go
  dm/master/workerrpc/rawgrpc.go
  dm/pkg/checker/mysql_server.go
  dm/pkg/checker/utils.go
  dm/pkg/utils/common.go
  dm/tests/_dmctl_tools/check_master_http_apis.go
  dm/tests/_dmctl_tools/check_master_online.go
  dm/tests/_dmctl_tools/check_master_online_http.go
  dm/tests/_dmctl_tools/check_worker_online.go
  dm/tests/many_tables/run.sh
  dm/worker/join.go
  dm/worker/metrics.go
  dm/worker/server.go
  engine/jobmaster/dm/checkpoint/agent.go
  go.mod
  go.sum
  pkg/errors/helper.go
  pkg/errors/helper_test.go
Labels: size/XL, release-note, area/dm, area/engine, approved, lgtm

#11144 sink(ticdc): quick fail on create table error without primary key when downstream sql_require_primary_key is set
  pkg/errorutil/util.go
  pkg/errorutil/util_test.go
Labels: size/XS, release-note-none, approved, lgtm

#10961 *(ticdc): Cp 10832 to release 7.5
  cdc/api/middleware/middleware.go
  cdc/api/v1/api.go
  cdc/async/async_initializer.go
  cdc/async/async_initializer_test.go
  cdc/capture/capture.go
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test_helper.go
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/coordinator_test.go
  pkg/config/replica_config.go
  pkg/context/context.go
  pkg/pdutil/utils.go
  pkg/sink/mysql/config.go
  tests/integration_tests/http_api/run.sh
  tests/integration_tests/http_api/util/test_case.py
  tests/integration_tests/http_api_tls/util/test_case.py
Labels: size/XXL, cherry-pick-approved, release-note, approved, lgtm

#11068 test(ticdc): Add more test cases
  tests/integration_tests/api_v2/cases.go
Labels: size/S, release-note-none, approved, lgtm

#11164 dep(*): move diff package to the tiflow and get rid of the tidb-tools
  .golangci.yml
  dm/chaos/cases/diff.go
  dm/pkg/conn/db.go
  engine/chaos/cases/dm/case.go
  go.mod
  go.sum
  pkg/diff/README.md
  pkg/diff/checkpoint.go
  pkg/diff/checkpoint_test.go
  pkg/diff/chunk.go
  pkg/diff/chunk_test.go
  pkg/diff/diff.go
  pkg/diff/diff_test.go
  pkg/diff/merge.go
  pkg/diff/merge_test.go
  pkg/diff/spliter_test.go
  pkg/diff/util.go
  pkg/diff/util_test.go
  pkg/importer/config.go
  pkg/importer/data.go
  pkg/importer/db.go
  pkg/importer/importer.go
  pkg/importer/job.go
  pkg/importer/parser.go
  pkg/importer/rand.go
  tests/integration_tests/util/db.go
Labels: size/XXL, release-note-none, area/dm, area/engine, approved, lgtm, needs-cherry-pick-release-7.5

#11159 puller(ticdc): fix resolvedTs get stuck when region split and merge (hotfix)
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  scripts/download-integration-test-binaries.sh
  tests/integration_tests/sequence/run.sh
Labels: size/S, release-note, approved, lgtm

#11167 *(ticdc): remove controller module
  cdc/api/middleware/middleware.go
  cdc/api/status/status.go
  cdc/api/util.go
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/api/v1/validator.go
  cdc/api/v2/api.go
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_mock.go
  cdc/api/v2/api_helpers_test.go
  cdc/api/v2/api_test.go
  cdc/api/v2/capture.go
  cdc/api/v2/capture_test.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/api/v2/health.go
  cdc/api/v2/health_test.go
  cdc/api/v2/owner.go
  cdc/api/v2/owner_test.go
  cdc/api/v2/processor.go
  cdc/api/v2/processor_test.go
  cdc/api/v2/status.go
  cdc/api/v2/status_test.go
  cdc/api/v2/tso_test.go
  cdc/api/v2/unsafe_test.go
  cdc/capture/capture.go
  cdc/capture/mock/capture_mock.go
  cdc/controller/controller.go
  cdc/controller/controller_test.go
  cdc/controller/mock/controller_mock.go
  cdc/controller/query.go
  cdc/owner/mock/owner_mock.go
  cdc/owner/mock/status_provider_mock.go
  cdc/owner/owner.go
  cdc/owner/owner_test.go
  cdc/owner/status_provider.go
  cdc/server/server.go
  cdcv2/capture/capture.go
  cdcv2/controller/controller.go
  cdcv2/owner/owner.go
  pkg/orchestrator/etcd_worker.go
  pkg/util/identity.go
  scripts/generate-mock.sh
Labels: size/XXL, release-note-none, approved, lgtm

#11050 chore: fix some typo about Changefeed
  cdc/owner/feed_state.go
  cdc/owner/feed_state_manager.go
  cdc/owner/owner_test.go
  pkg/orchestrator/reactor_state.go
Labels: size/S, contribution, release-note-none, ok-to-test, approved, lgtm

#11178 schema(ticdc): remove the useless indices offset field from the table info
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
Labels: size/XS, release-note-none, approved, lgtm

#11165 api (ticdc): check http request context in api helper
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_mock.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
Labels: size/L, release-note-none, approved, lgtm

#11162 syncpoint (ticdc): make syncpoint support base64 encoded password
  cdc/sink/mysql/mysql_syncpoint_store.go
  tests/integration_tests/syncpoint/data/prepare.sql
  tests/integration_tests/syncpoint/run.sh
Labels: size/S, cherry-pick-approved, release-note, approved, lgtm

#11166 sink (ticdc): fix kafka metrics
  metrics/grafana/ticdc.json
  pkg/sink/kafka/metrics.go
  pkg/sink/kafka/metrics_collector.go
  pkg/sink/kafka/v2/metrics_collector.go
  pkg/sink/kafka/v2/metrics_collector_test.go
Labels: size/M, release-note, approved, lgtm

#11184 kvClient (ticdc): revert e5999e3 to remove useless metrics
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/metrics.go
  cdc/kv/region_worker.go
  cdc/processor/pipeline/puller.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sourcemanager/manager.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
Labels: size/L, cherry-pick-approved, release-note, approved, lgtm

#11192 filter(ticdc): Fix verify table rules
  pkg/filter/utils.go
  pkg/filter/utils_test.go
Labels: size/S, release-note-none, approved, lgtm

#11195 model(ticdc): add one method to get the row changed event corresponding table id
  cdc/model/sink.go
  cdc/model/sink_test.go
  cdc/sink/dmlsink/event_appender.go
  cdc/sink/dmlsink/txn/event.go
  cmd/kafka-consumer/main.go
  cmd/pulsar-consumer/main.go
  pkg/applier/redo.go
  pkg/sink/codec/bootstraper.go
  pkg/sink/codec/craft/model.go
  pkg/sink/codec/maxwell/maxwell_message.go
  pkg/sink/codec/open/open_protocol_message.go
  pkg/sink/codec/simple/encoder_test.go
Labels: size/M, release-note-none, approved, lgtm

#11193 *: copy seahash from blainsmith.com/go/seahash
  cdc/kv/shared_client.go
  go.mod
  go.sum
  pkg/spanz/hash_map.go
  pkg/util/seahash/LICENSE.md
  pkg/util/seahash/seahash.go
  pkg/util/seahash/seahash_test.go
  scripts/check-copyright.sh
Labels: size/XL, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11204 *: tidy go mod
  go.mod
Labels: size/XS, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1
