Repository pingcap/tiflow, pull requests merged in 2024-02, with the labels that each got.

#10589 tests: specify tidb commit
  scripts/download-integration-test-binaries.sh
Labels: size/XS, release-note-none, approved, lgtm

#10530 tests: correct pd binary for tests
  scripts/download-integration-test-binaries.sh
Labels: size/XS, release-note-none, approved, lgtm

#10587 filter (ticdc): fix synpoint table is replicated in BDR mode
  cdc/syncpointstore/mysql_syncpoint_store.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/filter/utils.go
  pkg/filter/utils_test.go
  tests/integration_tests/bdr_mode/conf/cf.toml
  tests/integration_tests/bdr_mode/conf/down.toml
  tests/integration_tests/bdr_mode/conf/up.toml
  tests/integration_tests/bdr_mode/run.sh
Labels: size/M, release-note, approved, lgtm

#10509 filter (ticdc): enhance event filter
  dm/syncer/ddl.go
  dm/tests/incompatible_ddl_changes/conf/dm-task1.yaml
  dm/tests/incompatible_ddl_changes/run.sh
  go.mod
  go.sum
  pkg/filter/expr_filter.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/filter/sql_event_filter.go
  pkg/filter/sql_event_filter_test.go
  pkg/filter/utils.go
  pkg/filter/utils_test.go
Labels: size/XXL, release-note-none, approved, lgtm

#10506 kv-client(cdc): introduce a more simple frontier
  cdc/kv/client.go
  cdc/kv/region_state.go
  cdc/kv/region_worker_test.go
  cdc/kv/regionlock/region_range_lock.go
  cdc/kv/regionlock/region_range_lock_test.go
  cdc/kv/shared_client.go
  cdc/kv/shared_client_test.go
  cdc/kv/shared_region_worker.go
  cdc/kv/shared_region_worker_test.go
  cdc/puller/frontier/frontier_test.go
  pkg/cmd/server/server_test.go
  pkg/config/config_test_data.go
  pkg/config/kvclient.go
  pkg/config/server_config.go
Labels: size/XXL, release-note-none, approved, lgtm, affect-ticdc-config-docs

#10585 kv (ticdc): Improve the codebase of kvClient.
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
Labels: size/XL, release-note-none, approved, lgtm, affect-ticdc-config-docs

#10600 redo (ticdc): add comments for redo log config and make TestLogManagerInOwner more stable
  cdc/redo/manager_test.go
  pkg/config/consistent.go
Labels: size/L, release-note-none, approved, lgtm, affect-ticdc-config-docs

#10002 test (ticdc): add cross database ddls cases
  cdc/puller/frontier/frontier_test.go
  tests/integration_tests/ddl_manager/conf/diff_config.toml
  tests/integration_tests/ddl_manager/data/prepare.sql
Labels: size/S, release-note-none, approved, lgtm

#10605 pulsar/logger: ensure the .With*() fields are logged
  cmd/pulsar-consumer/main.go
  pkg/sink/pulsar/factory.go
  pkg/sink/pulsar/logger.go
  pkg/sink/pulsar/logger_test.go
Labels: type/bugfix, size/L, release-note-none, area/ticdc, approved, lgtm, needs-cherry-pick-release-7.5

#10310 cdc: Add integration tests with Debezium
  tests/integration_tests/_utils/start_tidb_cluster_impl
  tests/integration_tests/debezium/README.md
  tests/integration_tests/debezium/docker-compose.yml
  tests/integration_tests/debezium/go.mod
  tests/integration_tests/debezium/go.sum
  tests/integration_tests/debezium/run.sh
  tests/integration_tests/debezium/sql/data_types.sql
  tests/integration_tests/debezium/sql/debezium/LICENSE.txt
  tests/integration_tests/debezium/sql/debezium/README.txt
  tests/integration_tests/debezium/sql/debezium/binary_column_test.sql
  tests/integration_tests/debezium/sql/debezium/binary_mode_test.sql
  tests/integration_tests/debezium/sql/debezium/connector_test.sql
  tests/integration_tests/debezium/sql/debezium/connector_test_ro.sql
  tests/integration_tests/debezium/sql/debezium/datetime_key_test.sql
  tests/integration_tests/debezium/sql/debezium/db_default_charset.sql
  tests/integration_tests/debezium/sql/debezium/db_default_charset_noutf.sql
  tests/integration_tests/debezium/sql/debezium/decimal_column_test.sql
  tests/integration_tests/debezium/sql/debezium/enum_column_test.sql
  tests/integration_tests/debezium/sql/debezium/multitable_dbz_871.sql
  tests/integration_tests/debezium/sql/debezium/mysql_dbz_6533.sql
  tests/integration_tests/debezium/sql/debezium/nationalized_character_test.sql
  tests/integration_tests/debezium/sql/debezium/numeric_column_test.sql
  tests/integration_tests/debezium/sql/debezium/readbinlog_test.sql
  tests/integration_tests/debezium/sql/debezium/real_test.sql
  tests/integration_tests/debezium/sql/debezium/regression_test.sql
  tests/integration_tests/debezium/sql/debezium/skip_messages_test.sql
  tests/integration_tests/debezium/sql/debezium/strategy_test.sql
  tests/integration_tests/debezium/sql/debezium/table_column_comment_test.sql
  tests/integration_tests/debezium/sql/debezium/timestamp_column_test.sql
  tests/integration_tests/debezium/sql/debezium/tinyint_test.sql
  tests/integration_tests/debezium/sql/debezium/topic_name_sanitization_test.sql
  tests/integration_tests/debezium/sql/debezium/unsigned_integer_test.sql
  tests/integration_tests/debezium/sql/dml.sql
  tests/integration_tests/debezium/src/db_helper.go
  tests/integration_tests/debezium/src/logger.go
  tests/integration_tests/debezium/src/main.go
  tests/integration_tests/debezium/src/test_cases.go
  tests/integration_tests/run_group.sh
  tests/integration_tests/tidb_mysql_test/r/alter_table.result
  tests/integration_tests/tidb_mysql_test/r/mysql_replace.result
  tests/integration_tests/tidb_mysql_test/t/alter_table.test
  tests/integration_tests/tidb_mysql_test/t/mysql_replace.test
Labels: size/XXL, release-note-none, approved, lgtm

#10594 dm : fix tiup upgrade case
  .github/workflows/upgrade_dm_via_tiup.yaml
  dm/tests/tiup/conf/topo.yaml
  dm/tests/tiup/lib.sh
  dm/tests/tiup/upgrade-from-v2.sh
Labels: size/M, release-note, approved, lgtm

#10610 config(ticdc): remove useless config variables
  pkg/cmd/server/server_test.go
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/server_config.go
  pkg/config/sorter.go
  tests/integration_tests/server_config_compatibility/conf/server.toml
Labels: size/M, release-note-none, approved, lgtm, affect-ticdc-config-docs

#10611 pulsar (ticdc): fix tls encryption and oauth2.0
  cdc/sink/dmlsink/factory/factory.go
  errors.toml
  pkg/config/sink.go
  pkg/errors/cdc_errors.go
  pkg/sink/pulsar/factory.go
Labels: type/bugfix, size/M, release-note, approved, lgtm, affect-ticdc-config-docs

#10591 dm: remove dependency of secret key from dmctl & remove decrypt command
  dm/chaos/cases/source.go
  dm/checker/checker.go
  dm/common/config/config.go
  dm/common/config/config_test.go
  dm/config/security_test.go
  dm/config/source_config.go
  dm/config/source_config_test.go
  dm/config/source_converter_test.go
  dm/config/subtask.go
  dm/config/subtask_test.go
  dm/config/task.go
  dm/config/task_converters.go
  dm/config/task_converters_test.go
  dm/config/task_test.go
  dm/ctl/common/config.go
  dm/ctl/common/util.go
  dm/ctl/common/util_test.go
  dm/ctl/ctl.go
  dm/ctl/master/config.go
  dm/ctl/master/handle_error.go
  dm/ctl/master/operate_schema.go
  dm/ctl/master/operate_source.go
  dm/master/bootstrap.go
  dm/master/bootstrap_test.go
  dm/master/config.go
  dm/master/config_test.go
  dm/master/openapi_controller.go
  dm/master/openapi_view.go
  dm/master/scheduler/scheduler_test.go
  dm/master/server.go
  dm/master/server_test.go
  dm/pb/dmmaster.pb.go
  dm/pbmock/dmmaster.go
  dm/pkg/ha/source.go
  dm/pkg/upgrade/upgrade.go
  dm/pkg/utils/encrypt.go
  dm/proto/dmmaster.proto
  dm/relay/config.go
  dm/tests/dmctl_basic/check_list/config.sh
  dm/tests/dmctl_basic/run.sh
  dm/tests/dmctl_command/run.sh
  dm/tests/new_relay/run.sh
  dm/worker/server.go
  dm/worker/server_test.go
  dm/worker/source_worker.go
  dm/worker/source_worker_test.go
  engine/jobmaster/dm/dm_jobmaster.go
Labels: size/XXL, release-note, approved, lgtm

#10620 tests (ticdc): make bdr_mode integration test more stable
  tests/integration_tests/bdr_mode/data/up.sql
Labels: size/XS, release-note-none, approved, lgtm

#10631 *: fix dm integration test failure
  pkg/sqlmodel/multirow.go
  pkg/sqlmodel/multirow_test.go
  pkg/sqlmodel/row_change_test.go
Labels: size/M, release-note-none, approved, lgtm

#10630 mysql(ticdc): fix the data race in the conflict detector
  pkg/causality/internal/node.go
Labels: size/XS, release-note-none, approved, lgtm

#10564 mounter(ticdc): calculate row level checksum for timestmap by using UTC time zone
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  dm/checker/checker.go
  dm/dumpling/dumpling.go
  dm/loader/lightning.go
  dm/pkg/checker/binlog.go
  dm/pkg/checker/lightning.go
  dm/pkg/conn/basedb.go
  dm/pkg/conn/mockdb.go
  dm/pkg/schema/tracker.go
  dm/pkg/utils/common.go
  dm/relay/relay.go
  dm/syncer/expr_filter_group.go
  dm/syncer/util.go
  engine/jobmaster/dm/checkpoint/agent_test.go
  engine/pkg/meta/model/config.go
  examples/golang/avro-checksum-verification/go.mod
  examples/golang/avro-checksum-verification/go.sum
  examples/golang/avro-checksum-verification/main.go
  go.mod
  go.sum
  pkg/filter/expr_filter.go
  pkg/filter/expr_filter_test.go
  pkg/sink/codec/common/verify_checksum.go
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/marshaller.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/simple/message.json
  scripts/download-integration-test-binaries.sh
  tests/integration_tests/kafka_simple_basic/run.sh
Labels: size/XXL, release-note, approved, lgtm

#10597 codec(ticdc): add more unit test to cover simple protocol functionality
  cdc/sink/ddlsink/mq/mq_ddl_sink_test.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
Labels: size/L, release-note-none, approved, lgtm

#10638 codec(ticdc): add partition related ddl event unit test to the simple protocol
  pkg/sink/codec/simple/encoder_test.go
Labels: size/L, release-note-none, approved, lgtm

#10648 compile(*): support go 1.22
  go.mod
  go.sum
Labels: size/XS, release-note-none, approved, lgtm

#10640 test(ticdc): add pulsar integration test docker file
  deployments/ticdc/docker/pulsar-integration-test.Dockerfile
Labels: size/S, release-note-none, approved, lgtm

#10652 sorter(cdc): correct stale table range cleaning and metric it
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sourcemanager/sorter/metrics.go
  cdc/processor/sourcemanager/sorter/pebble/event_sorter.go
Labels: size/M, release-note-none, approved, lgtm

#10618 sorter(ticdc): optimize sorter and fix corner case of updating resolvedTs
  cdc/owner/changefeed.go
  cdc/processor/sourcemanager/sorter/pebble/event_sorter.go
Labels: size/L, release-note, approved, lgtm

#10656 test(ticdc): pulsar consumer support oauth and mtls auth
  cmd/pulsar-consumer/main.go
Labels: size/M, release-note-none, approved, lgtm

#10662 codec(ticdc): simple protocol encode index for the enum and set type
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/common/verify_checksum.go
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/marshaller.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/simple/message_test.go
Labels: size/XL, release-note-none, approved, lgtm

#10670 pulsar(ticdc): run_pulsar_consumer support more args
  tests/integration_tests/_utils/run_pulsar_consumer
  tests/integration_tests/autorandom/run.sh
  tests/integration_tests/batch_add_table/run.sh
  tests/integration_tests/big_txn/run.sh
  tests/integration_tests/canal_json_basic/run.sh
  tests/integration_tests/canal_json_content_compatible/run.sh
  tests/integration_tests/capture_session_done_during_task/run.sh
  tests/integration_tests/cdc/run.sh
  tests/integration_tests/cdc_server_tips/run.sh
  tests/integration_tests/changefeed_auto_stop/run.sh
  tests/integration_tests/changefeed_error/run.sh
  tests/integration_tests/changefeed_finish/run.sh
  tests/integration_tests/changefeed_pause_resume/run.sh
  tests/integration_tests/changefeed_reconstruct/run.sh
  tests/integration_tests/charset_gbk/run.sh
  tests/integration_tests/cli/run.sh
  tests/integration_tests/clustered_index/run.sh
  tests/integration_tests/common_1/run.sh
  tests/integration_tests/ddl_attributes/run.sh
  tests/integration_tests/ddl_manager/run.sh
  tests/integration_tests/ddl_only_block_related_table/run.sh
  tests/integration_tests/ddl_puller_lag/run.sh
  tests/integration_tests/ddl_sequence/run.sh
  tests/integration_tests/default_value/run.sh
  tests/integration_tests/drop_many_tables/run.sh
  tests/integration_tests/event_filter/run.sh
  tests/integration_tests/force_replicate_table/run.sh
  tests/integration_tests/foreign_key/run.sh
  tests/integration_tests/gc_safepoint/run.sh
  tests/integration_tests/generate_column/run.sh
  tests/integration_tests/kv_client_stream_reconnect/run.sh
  tests/integration_tests/many_pk_or_uk/run.sh
  tests/integration_tests/move_table/run.sh
  tests/integration_tests/multi_capture/run.sh
  tests/integration_tests/multi_rocks/run.sh
  tests/integration_tests/multi_source/run.sh
  tests/integration_tests/new_ci_collation/run.sh
  tests/integration_tests/owner_resign/run.sh
  tests/integration_tests/partition_table/run.sh
  tests/integration_tests/processor_err_chan/run.sh
  tests/integration_tests/processor_etcd_worker_delay/run.sh
  tests/integration_tests/processor_resolved_ts_fallback/run.sh
  tests/integration_tests/processor_stop_delay/run.sh
  tests/integration_tests/region_merge/run.sh
  tests/integration_tests/resolve_lock/run.sh
  tests/integration_tests/resourcecontrol/run.sh
  tests/integration_tests/row_format/run.sh
  tests/integration_tests/savepoint/run.sh
  tests/integration_tests/simple/run.sh
  tests/integration_tests/sink_hang/run.sh
  tests/integration_tests/sink_retry/run.sh
  tests/integration_tests/split_region/run.sh
  tests/integration_tests/tidb_mysql_test/run.sh
  tests/integration_tests/tiflash/run.sh
Labels: size/L, release-note-none, approved, lgtm

#10644 sql-mode(ticdc): dealing with SQL Mode more correctly
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed.go
  cdc/model/sink.go
  cdc/owner/ddl_sink.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink_test.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  dm/pkg/utils/common.go
  dm/syncer/expr_filter_group.go
  go.mod
  go.sum
  pkg/applier/redo_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/filter/expr_filter.go
  pkg/filter/expr_filter_bench_test.go
  pkg/filter/expr_filter_test.go
  pkg/filter/filter.go
  pkg/orchestrator/reactor_state_test.go
  pkg/sink/mysql/config_test.go
  pkg/sink/mysql/db_helper.go
  pkg/sink/mysql/mock_db.go
  pkg/sink/observer/observer_test.go
  tests/integration_tests/run_group.sh
  tests/integration_tests/sql_mode/run.sh
Labels: size/XL, release-note-none, approved, lgtm, affect-ticdc-config-docs

#10617 cli(ticdc): support configure credentials and tls certificate via cli
  pkg/cmd/cli/cli.go
  pkg/cmd/cli/cli_changefeed_helper.go
  pkg/cmd/cli/cli_changefeed_update.go
  pkg/cmd/cli/cli_configure_credentials.go
  pkg/cmd/cli/cli_unsafe.go
  pkg/cmd/factory/factory.go
  pkg/cmd/factory/factory_impl.go
  pkg/upstream/upstream.go
  tests/integration_tests/_utils/run_cdc_cli_tso_query
  tests/integration_tests/cli_tls_with_auth/run.sh
  tests/integration_tests/run_group.sh
  tests/integration_tests/tidb_mysql_test/t/bigint.test
Labels: size/XXL, release-note, approved, lgtm, affect-ticdc-config-docs

#10667 ticdc:Fix too much unnecessary log for lastSyncedTs
  cdc/owner/changefeed.go
Labels: size/S, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5
