Repository pingcap/tiflow, pull requests merged in 2024-12, with the labels that each got.

#11814 test(ticdc): update the default value of ttl_job_interval
  tests/integration_tests/ddl_attributes/run.sh
Labels: size/XS, release-note-none, approved, lgtm

#11804 ddl(ticdc): fix query splitting issue by using TiDB parser
  cdc/entry/schema_storage.go
  cdc/puller/ddl_puller.go
  pkg/ddl/util.go
  pkg/ddl/util_test.go
  tests/integration_tests/batch_add_table/run.sh
Labels: size/L, release-note-none, approved, lgtm, needs-cherry-pick-release-8.5

#11751 dm: fix integration test in rocky8.9
  dm/tests/_utils/run_downstream_cluster
  dm/tests/_utils/run_sql
  dm/tests/many_tables/run.sh
  dm/tests/requirements.txt
  dm/tests/tls/run.sh
Labels: size/M, contribution, release-note, area/dm, ok-to-test, approved, lgtm

#11772 puller: fix a bug that may cause error when replicate truncate table ddl
  cdc/owner/ddl_manager.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
Labels: size/M, release-note, approved, lgtm

#11828 consumer(ticdc): remove order events
  cmd/kafka-consumer/consumer.go
  cmd/kafka-consumer/event_group.go
Labels: size/S, release-note-none, approved, lgtm

#11830 snapshot(ticdc): fix the data race when log set to debug caused by print logs
  cdc/entry/schema/snapshot.go
Labels: size/XS, release-note-none, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#11815 debug(ticdc): add more logs to the kafka sink and enable sarama log
  cdc/sink/dmlsink/mq/dmlproducer/kafka_dml_producer.go
  cmd/kafka-consumer/main.go
  dm/tests/download-integration-test-binaries.sh
  go.mod
  go.sum
  pkg/logutil/log.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/common/message.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/v2/factory.go
  pkg/sink/kafka/v2/factory_test.go
  scripts/download-integration-test-binaries.sh
  tests/integration_tests/_utils/test_prepare
Labels: size/L, release-note-none, area/dm, approved, lgtm

#11845 codec(ticdc): simple protocol set table id by using the physical table id
  cdc/entry/schema_test_helper.go
  cdc/model/sink.go
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
Labels: size/XL, release-note, approved, lgtm, needs-cherry-pick-release-8.5

#11843 dm: fix start task check when both shard-mode and TLS are configured
  dm/ctl/master/start_task.go
  dm/tests/tls/conf/dm-task-3.yaml
  dm/tests/tls/run.sh
Labels: size/M, release-note-none, area/dm, approved, lgtm

#11749 dm: add a stand-alone load mode
  dm/_utils/terror_gen/errors_release.txt
  dm/config/helper.go
  dm/config/helper_test.go
  dm/config/subtask.go
  dm/config/task.go
  dm/errors.toml
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/pkg/terror/error_list.go
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/conf/diff_config_no_shard_one_source.toml
  dm/tests/openapi/run.sh
  dm/worker/subtask.go
  engine/executor/dm/worker.go
Labels: first-time-contributor, size/L, release-note, area/dm, area/engine, approved, lgtm

#11841 consumer(ticdc): add more logs to the consumer
  cmd/kafka-consumer/event_group.go
  cmd/kafka-consumer/main.go
  cmd/kafka-consumer/option.go
  cmd/kafka-consumer/writer.go
  deployments/ticdc/docker/kafka-consumer.Dockerfile
Labels: size/XL, release-note-none, approved, lgtm

#11886 snapshot(ticdc): fix ddl puller and ddl manager stuck caused by two dead lock
  cdc/entry/schema/snapshot.go
  cdc/entry/schema_storage.go
Labels: size/XS, release-note-none, approved, lgtm

#11866 *: prompt k8s.io/api version
  cdc/puller/ddl_puller.go
  dm/checker/checker.go
  go.mod
  go.sum
Labels: size/M, release-note, area/dm, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#11881 test(ticdc): fix region_merge test case
  tests/integration_tests/region_merge/run.sh
Labels: size/S, release-note-none, approved, lgtm

#11853 redo(ticdc): Fix RedoLogWriter unit test
  cdc/redo/writer/memory/mem_log_writer_test.go
Labels: size/S, release-note-none, approved, lgtm

#11895 consumer(ticdc): canal-json decoder cache table info for each message to avoid allocate memory on each new message
  cmd/kafka-consumer/writer.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/encoder.go
  pkg/sink/codec/simple/message.go
Labels: size/XL, release-note-none, approved, lgtm

#11913 dm: delete file ignore blob file not exist
  dm/pkg/storage/utils.go
  go.mod
Labels: size/S, contribution, release-note, area/dm, ok-to-test, approved, lgtm

#11836 ddl(ticdc): process only `JobStateDone` DDL jobs and remove the need to capture the `tidb_ddl_history`
  cdc/entry/mounter.go
  cdc/puller/ddl_puller.go
  pkg/spanz/span.go
Labels: size/L, release-note-none, approved, lgtm, needs-cherry-pick-release-8.5

#11869 schemaStorage(ticdc): remove `schemaVersion` in `schemaStorage`
  cdc/entry/schema/snapshot.go
  cdc/entry/schema_storage.go
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#11856 ddl(ticdc): ignore ddl with schemaversion 0
  cdc/entry/schema_storage.go
  cdc/puller/ddl_puller.go
  tests/integration_tests/ddl_with_exists/conf/diff_config.toml
  tests/integration_tests/ddl_with_exists/run.sh
  tests/integration_tests/ddl_with_exists/test.go
  tests/integration_tests/run_group.sh
Labels: size/L, release-note, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11903 puller: fix retry logic when check store version failed
  cdc/kv/shared_client.go
  cdc/kv/shared_client_test.go
  cdc/kv/shared_stream.go
  pkg/version/check.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#11911 codec(ticdc): reduce canal-json decode memory consumption by using buffered json decoder
  cmd/storage-consumer/main.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_json_txn_event_decoder.go
  pkg/sink/codec/canal/canal_json_txn_event_decoder_test.go
Labels: size/XXL, release-note-none, approved, lgtm

#11875 codec(ticdc): canal-json encode table id
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_json_txn_event_decoder.go
  pkg/sink/codec/canal/canal_json_txn_event_decoder_test.go
Labels: size/L, release-note, approved, lgtm

#11904 dm: use nightly tidb instead of latest to fix table not exist error
  dm/tests/mariadb_master_down_and_up/docker-compose.yml
  dm/tests/upstream_switch/docker-compose.yml
Labels: size/XS, release-note, area/dm, approved, lgtm

#11750 dm: fix MariaDB up down test
  .github/workflows/dm_mariadb_master_down_and_up.yaml
  dm/tests/mariadb_master_down_and_up/case.sh
  dm/tests/mariadb_master_down_and_up/docker-compose.yml
Labels: size/S, release-note-none, area/dm, approved, lgtm

#11944 dm: download docker-compose in github action
  .github/workflows/dm_mariadb_master_down_and_up.yaml
Labels: size/XS, release-note-none, approved, lgtm

#11926 ddl(ticdc): support restoring add index statements with pre-split option
  cdc/owner/ddl_sink_test.go
  go.mod
  go.sum
Labels: size/L, release-note-none, approved, lgtm

#11934 consumer(ticdc): do not sort to detect out of order events
  cmd/kafka-consumer/event_group.go
  cmd/kafka-consumer/writer.go
Labels: size/L, release-note-none, approved, lgtm

#11870 kafka(ticdc): sarama do not retry if produce message failed to prevent out of order
  pkg/logutil/log.go
  pkg/sink/kafka/sarama.go
Labels: size/S, release-note, approved, lgtm

#11844 dm: openapi support multi TLS security config for downstream db and cluster
  dm/checker/checker.go
  dm/config/security/security.go
  dm/config/security_test.go
  dm/config/task.go
  dm/config/task_converters.go
  dm/config/task_converters_test.go
  dm/config/task_test.go
  dm/loader/lightning.go
  dm/loader/lightning_test.go
  dm/master/openapi_controller_test.go
  dm/openapi/fixtures/task.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
  dm/tests/_utils/run_downstream_cluster_with_tls
  dm/tests/openapi/client/openapi_source_check
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/run.sh
  dm/tests/openapi/tls_conf/ca2.pem
  dm/tests/openapi/tls_conf/tidb.key
  dm/tests/openapi/tls_conf/tidb.pem
  dm/tests/tls/conf/generate_tls.sh
Labels: size/XXL, contribution, release-note, area/dm, ok-to-test, approved, lgtm
