Repository pingcap/tiflow, pull requests merged in 2024-10, with the labels that each got.

#11624 cordinator(ticdc): Fix Puller Resolved TS Lag Calculation and Deprecate current_ts Field in Stats
  cdc/processor/processor.go
  cdc/processor/tablepb/table.proto
  cdc/scheduler/internal/v3/coordinator.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
Labels: size/S, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11632 integration test(ticdc): Reintroduce `--wildcards` Option in tar Command for download-integration-test-binaries.sh
  scripts/download-integration-test-binaries.sh
Labels: size/XS, release-note-none, approved, lgtm

#11006 processor(ticdc): remove ctx from puller to simplify the signature
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/owner_test.go
  cdc/processor/processor.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
Labels: size/M, release-note-none, approved, lgtm

#11224 puller(ticdc): always split update kv entries in sink safe mode
  cdc/processor/processor.go
  cdc/processor/processor_test.go
  cdc/processor/sourcemanager/manager.go
  pkg/sink/mysql/config.go
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11641 api(ticdc): Not show the error info during query the changefeed when state is stopped, finished and removed
  cdc/api/v2/changefeed.go
  tests/integration_tests/changefeed_error/run.sh
Labels: size/S, release-note-none, approved, lgtm

#11649 sink(ticdc): add event key output for debezium
  cdc/model/sink.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/debezium/codec.go
  pkg/sink/codec/debezium/codec_test.go
  pkg/sink/codec/debezium/debezium_test.go
  pkg/sink/codec/debezium/encoder.go
  pkg/sink/codec/debezium/testdata/datatype.dbz.key.json
  tests/integration_tests/debezium/README.md
  tests/integration_tests/debezium/run.sh
  tests/integration_tests/debezium/sql/debezium/real_test.sql
  tests/integration_tests/debezium/src/test_cases.go
Labels: size/XXL, release-note, approved, lgtm

#11678 *(ticdc): add integration test for safe mode
  tests/integration_tests/run_group.sh
  tests/integration_tests/safe_mode/conf/diff_config.toml
  tests/integration_tests/safe_mode/data/create_table.sql
  tests/integration_tests/safe_mode/data/insert.sql
  tests/integration_tests/safe_mode/data/update.sql
  tests/integration_tests/safe_mode/run.sh
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11681 ci(dm): Fix DM `import_v10x` Test Failure Due to TiDB int Type Display Change
  dm/tests/import_v10x/run.sh
Labels: size/XS, release-note-none, area/dm, approved, lgtm

#11677 cmd(ticdc): Export All cdc Subcommands
  pkg/cmd/cmd.go
Labels: size/S, release-note-none, approved, lgtm, affect-ticdc-config-docs

#11637 sink(cdc): avoid temporary memory allocations for avro
  cdc/model/sink.go
  pkg/sink/codec/avro/avro.go
Labels: size/L, release-note-none, approved, lgtm

#11701 dm: add retry for dm-worker to join dm-master
  dm/worker/join.go
Labels: size/M, release-note, area/dm, approved, lgtm

#11686 dm: fix chaos test
  .github/workflows/dataflow_engine_chaos.yaml
  .github/workflows/dm_binlog_999999.yaml
  .github/workflows/dm_chaos.yaml
  .github/workflows/dm_mariadb_master_down_and_up.yaml
  .github/workflows/dm_upstream_switch.yaml
  .github/workflows/upgrade_dm_via_tiup.yaml
  dm/chaos/cases/cases.go
  dm/chaos/cases/task.go
  dm/chaos/manifests/dm-master.yaml
  dm/chaos/manifests/dm-worker.yaml
  dm/chaos/manifests/sources.yaml
  dm/chaos/manifests/tidb.yaml
Labels: size/M, release-note, area/dm, approved, lgtm

#11669 metric(cdc): fix uncorrect metric WorkerBusyRatio
  cdc/kv/metrics.go
  cdc/redo/common/metric.go
  cdc/redo/manager.go
  cdc/redo/meta_manager.go
  cdc/redo/writer/file/file.go
  cdc/redo/writer/file/file_test.go
  cdc/redo/writer/memory/file_worker.go
  cdc/sink/dmlsink/cloudstorage/dml_worker.go
  cdc/sink/metrics/cloudstorage/metrics.go
  metrics/grafana/TiCDC-Monitor-Summary.json
  metrics/grafana/ticdc.json
Labels: size/L, release-note-none, approved, lgtm

#11483 kafka(ticdc): fix kafka consumer doesn't check partition and old message
  cmd/kafka-consumer/writer.go
Labels: size/L, contribution, release-note-none, ok-to-test, approved, lgtm
