Repository pingcap/tiflow, pull requests merged in 2024-01, with the labels that each got.

#10376 sink-to-mysql(cdc) simplify conflict detector, prevent workload skew issue
  pkg/causality/conflict_detector.go
  pkg/causality/internal/node.go
  pkg/causality/internal/node_test.go
  pkg/causality/internal/slots_test.go
Labels: size/L, release-note-none, approved, lgtm

#10395 puller(cdc): more tests and logs for frontier and kv-client
  cdc/kv/client.go
  cdc/kv/region_state.go
  cdc/kv/region_state_bench_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/scheduler/internal/v3/replication/metrics.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  metrics/grafana/ticdc.json
  pkg/regionspan/region_range_lock.go
  pkg/regionspan/region_range_lock_test.go
  pkg/txnutil/lock_resolver.go
Labels: size/XXL, release-note, approved, lgtm

#10396 cp 6b082ea
  cdc/kv/client.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/puller.go
Labels: size/L, release-note, approved, lgtm

#10373 capture(ticdc): add deploy info to capture
  cdc/capture/capture.go
  cdc/model/capture.go
  cdc/model/capture_test.go
  pkg/etcd/etcdkey.go
Labels: size/M, release-note, approved, lgtm

#10399 cdc: update info message for ‘/api/v2/changefeeds/{changefeed_id}/synced’
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  tests/integration_tests/synced_status/run.sh
Labels: size/M, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10397 Cp 10339
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/frontier/list.go
  cdc/puller/puller.go
Labels: size/L, release-note, approved, lgtm

#10339 puller(ticdc): add more log for puller
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/frontier/list.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10398 Cp 10333
  cdc/kv/client.go
  cdc/kv/region_worker.go
  cdc/puller/puller.go
  pkg/regionspan/region_range_lock.go
  pkg/regionspan/region_range_lock_test.go
Labels: size/L, release-note, approved, lgtm

#10389 kvclient(ticdc): add worker busy monitor
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/metrics.go
  cdc/kv/region_worker.go
  cdc/kv/shared_region_worker.go
  cdc/model/changefeed_test.go
  cdc/processor/processor.go
  cdc/processor/sourcemanager/manager.go
  cdc/processor/sourcemanager/puller/dummy_puller_wrapper.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
Labels: size/XL, release-note, approved, lgtm

#10392 chore(pkg/config): add OWNERS file to support auto label on pull request
  pkg/config/OWNERS
Labels: size/XS, release-note-none, skip-issue-check, approved, lgtm

#10418 kvclient(ticdc): add worker busy monitor
  cdc/api/v2/model.go
  cdc/kv/client.go
  cdc/kv/client_bench_test.go
  cdc/kv/client_test.go
  cdc/kv/metrics.go
  cdc/kv/region_worker.go
  cdc/model/changefeed_test.go
  cdc/processor/pipeline/puller.go
  cdc/processor/processor.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  cdc/processor/sourcemanager/manager.go
  cdc/processor/sourcemanager/puller/puller_wrapper.go
  cdc/puller/ddl_puller.go
  cdc/puller/puller.go
  cdc/puller/puller_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
Labels: size/XL, release-note, approved, lgtm

#10366 encoder (ticdc): simple protocol send bootstrap event periodically
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/sink.go
  cdc/model/sink_gen.go
  cdc/model/sink_gen_test.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/pulsar_dml_sink.go
  cdc/sink/dmlsink/mq/worker.go
  cdc/sink/dmlsink/mq/worker_test.go
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/sink.go
  pkg/orchestrator/reactor_state_test.go
  pkg/sink/codec/bootstraper.go
  pkg/sink/codec/bootstraper_test.go
  pkg/sink/codec/encoder.go
  pkg/sink/codec/encoder_group.go
  pkg/sink/codec/simple/decoder.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/api_v2/model.go
  tests/integration_tests/kafka_simple_basic/conf/changefeed.toml
  tests/integration_tests/kafka_simple_basic/data/data.sql
  tests/integration_tests/kafka_simple_basic/data/pre_ddl.sql
  tests/integration_tests/kafka_simple_basic/run.sh
  tests/integration_tests/kafka_simple_claim_check/data/data.sql
  tests/integration_tests/kafka_simple_claim_check/run.sh
  tests/integration_tests/kafka_simple_handle_key_only/data/data.sql
  tests/integration_tests/kafka_simple_handle_key_only/data/ddl.sql
  tests/integration_tests/kafka_simple_handle_key_only/run.sh
Labels: size/XXL, release-note-none, approved, lgtm, affect-ticdc-config-docs

#10415 dm: support MySQL 8.0 GA
  dm/pkg/checker/mysql_server.go
  dm/pkg/checker/mysql_server_test.go
  dm/pkg/checker/utils_test.go
  dm/tests/dmctl_command/run.sh
  dm/tests/extend_column/run.sh
Labels: size/S, release-note, approved, lgtm

#10350 sink-to-cloudstorage (cdc) use slice after initialized
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
Labels: size/XS, release-note-none, approved, lgtm

#10414 test: enable tls test for DM
  dm/master/config.go
  dm/tests/tls/run.sh
Labels: size/M, release-note-none, approved, lgtm

#10417 encoder (CDC) shrink the `bytes.Buffer` to reduce memory usage
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
  pkg/sink/codec/canal/canal_json_txn_event_encoder.go
  pkg/sink/codec/csv/csv_encoder.go
  pkg/sink/codec/encoder.go
Labels: size/S, release-note-none, approved, lgtm

#10312 (pkg/generateDeleteSQL) reduce redundant calculation
  cdc/sink/dmlsink/txn/mysql/mysql.go
  pkg/sqlmodel/multirow.go
Labels: size/S, release-note-none, approved, lgtm

#10425 cp 9983
  cdc/kv/client.go
  cdc/kv/region_state.go
  cdc/kv/region_state_bench_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
  cdc/kv/regionlock/region_range_lock.go
  cdc/kv/regionlock/region_range_lock_test.go
Labels: size/XXL, release-note-none

#10426 Cp 10202
  cdc/kv/client.go
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/puller.go
Labels: size/L, release-note, do-not-merge/needs-triage-completed, affect-ticdc-config-docs

#10427 cp 10339 to hotfix
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/frontier/list.go
  cdc/puller/puller.go
Labels: size/L, release-note

#10428 puller(cdc): more tests and logs for frontier and kv-client (#10333)
  cdc/kv/client.go
  cdc/kv/region_worker.go
  cdc/kv/regionlock/region_range_lock.go
  cdc/kv/regionlock/region_range_lock_test.go
  cdc/puller/frontier/frontier_test.go
  pkg/spanz/convert.go
  pkg/spanz/convert_test.go
Labels: size/XL, release-note

#10443 codec(ticdc): simple protocol do not encode decimal for the float and double
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/marshaller.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/simple/message.json
  pkg/sink/codec/simple/message_test.go
  pkg/sink/codec/utils/test_utils.go
Labels: size/M, release-note-none, approved, lgtm

#10409 Rebalance testcases into groups
  dm/tests/run_group.sh
Labels: first-time-contributor, size/S, release-note, approved, lgtm

#10422 api(ticdc): only update upstreamInfo that has changed
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/owner/mock/owner_mock.go
  cdc/owner/owner.go
  cdcv2/owner/owner.go
  errors.toml
  pkg/errors/cdc_errors.go
  pkg/etcd/client_test.go
  pkg/etcd/etcd.go
  pkg/etcd/etcd_test.go
  pkg/etcd/etcdkey_test.go
  pkg/etcd/mock/etcd_client_mock.go
  pkg/etcd/util_test.go
Labels: size/XL, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10444 dm: merge dm on cloud accelerate chunk related code into master
  dm/loader/lightning.go
  dm/loader/lightning_test.go
  dm/pkg/storage/utils.go
  dm/syncer/syncer.go
Labels: size/M, release-note-none, approved, lgtm

#10456 codec(ticdc): simple protocol avro schema adjust to follow official convention.
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/simple/message.json
  pkg/sink/codec/simple/message_test.go
Labels: size/M, release-note-none, approved, lgtm

#10458 cdc: remove unused code and add some logs
  cdc/model/sink.go
  cdc/processor/sinkmanager/metrics.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/worker.go
Labels: size/S, release-note-none, approved, lgtm

#10446 makefile: remove codecov upload in makefile
  Makefile
Labels: size/XS, release-note-none, approved, lgtm

#10468 fix the comment of SourceManager.multiplexing
  cdc/processor/sourcemanager/manager.go
Labels: first-time-contributor, size/XS, release-note-none, approved, lgtm

#10472 chore: make the codecov status informational to not affect the PR commit status
  .codecov.yml
Labels: size/XS, release-note-none, approved, lgtm

#10471 test(ticdc): fix http_api integration test
  cdc/api/middleware/middleware.go
  cdc/api/v1/api.go
  tests/integration_tests/http_api/run.sh
  tests/integration_tests/http_api/util/test_case.py
  tests/integration_tests/http_api_tls/util/test_case.py
Labels: size/S, release-note-none, approved, lgtm

#10475 codec(ticdc): simple protocol add table id as message field
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/marshaller.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/simple/message.json
  pkg/sink/codec/simple/message_test.go
Labels: size/M, release-note-none, approved, lgtm

#10477 codec(ticdc): add unit test to cover integer value checksum calculation.
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/simple/message.json
Labels: size/L, release-note-none, approved, lgtm

#10466 mysql (ticdc): Improve the performance of the mysql sink by refining the transaction event batching logic
  cdc/sink/dmlsink/txn/txn_dml_sink.go
  cdc/sink/dmlsink/txn/worker.go
  cdc/sink/metrics/txn/metrics.go
  metrics/grafana/ticdc.json
Labels: size/L, release-note-none, approved, lgtm

#10488 puller(ticdc): fix resolvedTs get stuck when region split and merge
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
  cdc/puller/puller.go
Labels: size/M, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10484 metrics(ticdc): fix slowest table metrics in scheduler
  cdc/scheduler/internal/v3/replication/replication_manager.go
Labels: size/XS, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10508 puller(ticdc): fix resolvedTs get stuck when region split and merge
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
Labels: size/S, release-note-none, approved, lgtm

#10459 owner, metrics(ticdc): fix metrics
  cdc/owner/changefeed.go
  cdc/owner/metrics.go
  metrics/grafana/TiCDC-Monitor-Summary.json
  metrics/grafana/ticdc.json
Labels: size/L, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10492 cdc: fix build table info
  cdc/entry/mounter_test.go
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
  cdc/model/sink.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  pkg/applier/redo_test.go
Labels: size/XXL, release-note-none, approved, lgtm

#10479 Fix the panic message of MemQuota.Record
  cdc/processor/memquota/mem_quota.go
Labels: size/XS, release-note-none, approved, lgtm

#10351 sink(ticdc): use pd clock in storage sink
  cdc/api/v1/validator.go
  cdc/api/v2/api_helpers.go
  cdc/processor/sinkmanager/manager.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink_test.go
  cdc/sink/dmlsink/cloudstorage/dml_worker.go
  cdc/sink/dmlsink/cloudstorage/dml_worker_test.go
  cdc/sink/dmlsink/factory/factory.go
  cdc/sink/validator/validator.go
  cdc/sink/validator/validator_test.go
  cmd/kafka-consumer/main.go
  cmd/pulsar-consumer/main.go
  cmd/storage-consumer/main.go
  errors.toml
  pkg/applier/redo.go
  pkg/errors/cdc_errors.go
  pkg/pdutil/clock.go
  pkg/sink/cloudstorage/path.go
  pkg/sink/cloudstorage/path_test.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10487 disable region detail logs in kv-client by default
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/kv/shared_client.go
  cdc/kv/shared_client_test.go
  cdc/kv/shared_region_worker.go
  cdc/kv/shared_region_worker_test.go
  cdc/kv/shared_stream.go
  cdc/puller/multiplexing_puller_test.go
  pkg/config/config_test_data.go
  pkg/config/debug.go
  pkg/config/server_config.go
  scripts/download-integration-test-binaries.sh
Labels: size/L, release-note-none, approved, lgtm, affect-ticdc-config-docs

#10527 *: fix tiflash ci failure
  tests/integration_tests/_utils/tiflash-users.toml
Labels: size/XS, release-note-none, approved, lgtm

#10507 filter(ticdc): Remove useless code about MySQLReplicationRules
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/changefeed_test.go
  pkg/cmd/cli/cli_changefeed_create_test.go
  pkg/config/filter.go
  pkg/filter/utils.go
  pkg/migrate/migrate_test.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/api_v2/model.go
Labels: size/L, release-note-none, approved, lgtm, affect-ticdc-config-docs

#10528 mounter(ticdc): fix truncate table partition cause mounter failed issue
  cdc/entry/mounter.go
  cdc/entry/schema/snapshot.go
  cdc/entry/schema/snapshot_test.go
Labels: size/M, release-note-none, approved, lgtm

#10467 redo (cdc) remove inefficient redoCache to simply the code and reduce maintenance burden
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/processor/sinkmanager/manager.go
  cdc/processor/sinkmanager/manager_test.go
  cdc/processor/sinkmanager/redo_cache.go
  cdc/processor/sinkmanager/redo_cache_test.go
  cdc/processor/sinkmanager/redo_log_advancer.go
  cdc/processor/sinkmanager/redo_log_advancer_test.go
  cdc/processor/sinkmanager/redo_log_worker.go
  cdc/processor/sinkmanager/redo_log_worker_test.go
  cdc/processor/sinkmanager/table_sink_worker.go
  cdc/processor/sinkmanager/table_sink_worker_test.go
  pkg/config/config_test_data.go
  pkg/config/consistent.go
  pkg/config/replica_config.go
Labels: size/XXL, release-note-none, approved, lgtm, affect-ticdc-config-docs

#10476 simple (ticdc): add bootstrap sending function configuration
  cdc/api/v2/model.go
  cdc/api/v2/model_test.go
  cdc/model/sink.go
  cdc/model/sink_gen.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  pkg/cmd/util/helper_test.go
  pkg/config/config_test_data.go
  pkg/config/replica_config.go
  pkg/config/sink.go
  pkg/orchestrator/reactor_state_test.go
  pkg/sink/codec/bootstraper.go
  pkg/sink/codec/bootstraper_test.go
  pkg/sink/codec/encoder_group.go
  tests/integration_tests/api_v2/cases.go
  tests/integration_tests/api_v2/model.go
Labels: size/XL, release-note-none, approved, lgtm, affect-ticdc-config-docs

#10535 puller(ticdc): upgrade pd client to fix panic issue
  go.mod
  go.sum
Labels: size/XS, release-note-none, approved, lgtm

#10518 pkg/filter(ticdc): ignore ddl in ddl_manager
  cdc/entry/schema_storage.go
  cdc/owner/changefeed.go
  cdc/owner/ddl_manager.go
  cdc/owner/ddl_manager_test.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
  cmd/filter-helper/main.go
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/filter/sql_event_filter.go
  pkg/filter/sql_event_filter_test.go
  tests/integration_tests/event_filter/conf/cf.toml
  tests/integration_tests/event_filter/conf/diff_config.toml
  tests/integration_tests/event_filter/data/test.sql
  tests/integration_tests/event_filter/data/test_alter.sql
  tests/integration_tests/event_filter/data/test_truncate.sql
  tests/integration_tests/event_filter/run.sh
Labels: size/XXL, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10526 [RFC] large transactions don't block watermark advancing
  docs/design/2024-01-22-ticdc-large-txn-not-block-wm.md
  docs/media/large-txn-no-block-wm-1.png
  docs/media/large-txn-no-block-wm-2.png
  docs/media/large-txn-no-block-wm-3.png
  docs/media/large-txn-no-block-wm-4.png
  docs/media/large-txn-no-block-wm-5.png
  docs/media/large-txn-no-block-wm-6.png
  docs/media/large-txn-no-block-wm-7.png
  docs/media/large-txn-no-block-wm-8.png
Labels: size/L, release-note-none, approved, lgtm

#10542 Add new column "is-updated" for output-old-value in csv protocol
  cdc/api/v2/model.go
  pkg/sink/codec/csv/csv_message.go
  pkg/sink/codec/csv/csv_message_test.go
Labels: size/M, release-note, approved, lgtm

#10533 codec(ticdc): remove integer and boolean from the schema
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.json
Labels: size/XS, release-note-none, approved, lgtm

#10505 entry (ticdc):remove useless code in entry package
  cdc/entry/codec.go
  cdc/entry/codec_test.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_test.go
  cdc/entry/schema_test_helper.go
Labels: size/XL, release-note-none, approved, lgtm

#10546 api(ticdc): Check min service gc safepoint when resume changefeed
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_mock.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
Labels: size/M, release-note-none, approved, lgtm

#10548 feat: add goproxy env for dockerfile
  deployments/engine/docker/Dockerfile
Labels: first-time-contributor, size/XS, release-note, skip-issue-check, approved, lgtm

#10551 cli(ticdc): verify start-ts to make sure it's not in the future
  cdc/api/v1/validator.go
  cdc/api/v2/api_helpers.go
  cdc/api/v2/api_helpers_test.go
Labels: size/M, release-note, approved, lgtm

#10558 puller(ticdc): fix resolvedTs get stuck when region split and merge (hotfix)
  cdc/puller/frontier/frontier.go
  cdc/puller/frontier/frontier_test.go
Labels: size/M, release-note, approved, lgtm

#10561 csv(ticdc): Add a new config "output_handle_key" in csv protocol to support output handle key info in csv protocol
  cdc/api/v2/model.go
  cdc/entry/mounter.go
  cdc/model/sink.go
  pkg/config/config_test_data.go
  pkg/config/sink.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/csv/csv_message.go
  pkg/sink/codec/csv/csv_message_test.go
Labels: size/M, release-note-none, approved, lgtm, affect-ticdc-config-docs

#10550 codec(ticdc): simple protocol fix primary key not found and adjust schema
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/marshaller.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/simple/message.json
Labels: size/XL, release-note-none, approved, lgtm

#10562 sink(ticdc): Remove useless gen code for sink
  cdc/model/sink.go
  cdc/model/sink_gen.go
  cdc/model/sink_gen_test.go
Labels: size/XXL, release-note, approved, lgtm

#10559 kv (ticdc): fix kvClient reconnection downhill loop
  cdc/entry/schema_test_helper.go
  cdc/kv/client.go
  cdc/kv/client_test.go
  cdc/kv/region_worker.go
  cdc/kv/region_worker_test.go
Labels: component/kv-client, size/XXL, release-note, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5

#10549 upstream, api(ticdc): support topology and config
  cdc/api/v2/unsafe_test.go
  cdc/capture/capture.go
  cdc/http.go
  cdc/server/server.go
  cdcv2/capture/capture.go
  pkg/etcd/client.go
  pkg/security/credential.go
  pkg/upstream/main_test.go
  pkg/upstream/manager.go
  pkg/upstream/manager_test.go
  pkg/upstream/upstream.go
  pkg/upstream/upstream_test.go
Labels: size/XL, release-note-none, approved, lgtm
