Repository pingcap/tiflow, pull requests merged in 2024-09, with the labels that each got.

#11545 dep(*): update tidb to include DM SchemaTracker fix (#11410)
  dm/syncer/expr_filter_group.go
  go.mod
  go.sum
Labels: size/S, cherry-pick-approved, release-note, approved, lgtm

#11548 sorter: fix the bug that value can be corrupted when accessing sorter
  cdc/processor/sourcemanager/engine/pebble/event_sorter.go
Labels: size/S, cherry-pick-approved, release-note-none, approved, lgtm

#11560 changefeed(ticdc): fix barrier ts set incorrectly cause monitor become year
  cdc/owner/changefeed.go
Labels: size/XS, release-note-none, approved, lgtm

#11564 test(ticdc,dm): modify download-integration-test-binaries script
  dm/tests/download-integration-test-binaries.sh
  scripts/download-integration-test-binaries.sh
Labels: size/M, contribution, release-note-none, area/dm, ok-to-test, approved, lgtm

#11567 scheduler(ticdc): modify scheduler monitoring
  cdc/scheduler/internal/v3/replication/replication_set.go
Labels: size/XS, contribution, release-note-none, ok-to-test, approved, lgtm

#11547 metrics(ticdc): fix some missing db sorter related metrics
  cdc/scheduler/internal/v3/agent/agent.go
  cdc/scheduler/internal/v3/replication/replication_manager.go
  metrics/grafana/ticdc.json
  pkg/config/db.go
  pkg/config/debug.go
  pkg/config/kvclient.go
  pkg/config/server_config.go
Labels: size/XXL, release-note-none, approved, lgtm, affect-ticdc-config-docs

#11571 ci: udpate OWNERS_ALIASES file
  OWNERS_ALIASES
Labels: size/XS, release-note, approved, lgtm

#11577 sorter: correct wrong metric about next duration
  cdc/processor/sourcemanager/sorter/pebble/event_sorter.go
Labels: size/S, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#11573 changefeed(ticdc): send bootstrap message asynchronously to prevent block other changefeeds
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/owner/ddl_manager.go
  cdc/owner/ddl_manager_test.go
Labels: size/XL, release-note-none, approved, lgtm

#11506 mysql(ticdc): remove returned error and modify the log in `CheckIsTiDB `
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/syncpointstore/mysql_syncpoint_store.go
  pkg/sink/mysql/db_helper.go
  pkg/sink/observer/observer.go
Labels: size/M, release-note-none, approved, lgtm

#11186 kvclient(cdc): handle out-of-order prewrite events for pipelined DMLs
  cdc/kv/matcher.go
  cdc/kv/matcher_test.go
Labels: size/M, release-note-none, approved, lgtm

#11526 mounter(ticdc): release-7.5 ignore checksum v2
  cdc/entry/mounter.go
Labels: size/XS, cherry-pick-approved, release-note-none, approved, lgtm

#11523 mounter(ticdc): ignore checksum v2
  cdc/entry/mounter.go
Labels: size/XS, cherry-pick-approved, release-note-none, approved, lgtm

#11584 test(ticdc): fix data inconsistence on integration_tests
  tests/integration_tests/kafka_simple_basic/data/data.sql
  tests/integration_tests/kafka_simple_basic_avro/data/data.sql
Labels: size/XS, contribution, release-note-none, needs-ok-to-test, approved, lgtm

#11572 chore: support specify the branch for downloading dependencies through env variable
  dm/tests/download-compatibility-test-binaries.sh
  dm/tests/download-integration-test-binaries.sh
  scripts/download-integration-test-binaries.sh
Labels: size/XXL, release-note-none, area/dm, approved, lgtm

#11580 ddl(ticdc): Add error handling for mismatched `Job.Query` and `Job.BinlogInfo.MultipleTableInfos` in TiCDC
  cdc/puller/ddl_puller.go
  errors.toml
  pkg/errors/cdc_errors.go
Labels: size/S, release-note-none, approved, lgtm

#11579 kv(ticdc): kv client should handle region congested error explicitly
  cdc/kv/shared_client.go
  go.mod
  go.sum
Labels: size/S, release-note-none, approved, lgtm

#11541 sink(ticdc): reduce log print when using CDC sync data to Kafka with nil values in column
  cdc/model/sink.go
Labels: size/XS, contribution, release-note-none, ok-to-test, approved, lgtm

#11538 ticdc: Support Vector data type | tidb=master pd=master tikv=master
  cdc/entry/codec.go
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/entry/schema_storage_test.go
  cdc/entry/schema_test_helper.go
  cdc/sink/ddlsink/mysql/format_ddl.go
  cdc/sink/ddlsink/mysql/format_ddl_test.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sink/dmlsink/txn/mysql/dml.go
  cdc/sink/dmlsink/txn/mysql/dml_test.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  dm/pkg/conn/mockdb.go
  dm/syncer/expr_filter_group_test.go
  dm/tests/download-compatibility-test-binaries.sh
  dm/tests/download-integration-test-binaries.sh
  go.mod
  go.sum
  pkg/filter/filter_test_helper.go
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/canal/canal_entry.go
  pkg/sink/codec/canal/canal_entry_test.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/common/verify_checksum.go
  pkg/sink/codec/craft/message_decoder.go
  pkg/sink/codec/craft/message_encoder.go
  pkg/sink/codec/csv/csv_message.go
  pkg/sink/codec/csv/csv_message_test.go
  pkg/sink/codec/debezium/codec.go
  pkg/sink/codec/internal/column.go
  pkg/sink/codec/internal/java.go
  pkg/sink/codec/maxwell/maxwell_message.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/utils/test_utils.go
  pkg/sink/mysql/config.go
  scripts/download-integration-test-binaries.sh
  tests/integration_tests/kafka_simple_basic/data/data.sql
  tests/integration_tests/kafka_simple_basic_avro/data/data.sql
  tests/integration_tests/run_group.sh
  tests/integration_tests/vector/conf/diff_config.toml
  tests/integration_tests/vector/data/data.sql
  tests/integration_tests/vector/run.sh
Labels: size/XXL, contribution, release-note, area/dm, area/ticdc, area/engine, ok-to-test, approved, lgtm

#11617 cdc: use typed args for renametables and adapt args v2
  cdc/entry/schema/snapshot.go
  cdc/entry/schema_storage.go
  cdc/entry/schema_test.go
  cdc/entry/schema_test_helper.go
  cdc/owner/ddl_manager_test.go
  cdc/puller/ddl_puller.go
  cdc/puller/ddl_puller_test.go
Labels: size/XL, release-note, skip-issue-check, approved, lgtm

#11604 dm: fix leader did not retire after delete the key
  dm/pkg/election/election.go
  dm/pkg/election/election_test.go
Labels: size/L, release-note, area/dm, approved, lgtm

#11620 ticdc: Support Vector data type
  cdc/entry/codec.go
  cdc/entry/mounter.go
  cdc/entry/mounter_test.go
  cdc/sink/ddlsink/mysql/format_ddl.go
  cdc/sink/ddlsink/mysql/format_ddl_test.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sink/dmlsink/txn/mysql/dml.go
  cdc/sink/dmlsink/txn/mysql/dml_test.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  dm/tests/download-compatibility-test-binaries.sh
  go.mod
  go.sum
  pkg/sink/codec/avro/avro.go
  pkg/sink/codec/canal/canal_entry.go
  pkg/sink/codec/canal/canal_entry_test.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/common/verify_checksum.go
  pkg/sink/codec/craft/message_decoder.go
  pkg/sink/codec/craft/message_encoder.go
  pkg/sink/codec/csv/csv_message.go
  pkg/sink/codec/csv/csv_message_test.go
  pkg/sink/codec/debezium/codec.go
  pkg/sink/codec/internal/column.go
  pkg/sink/codec/internal/java.go
  pkg/sink/codec/maxwell/maxwell_message.go
  pkg/sink/codec/open/open_protocol_encoder_test.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
  pkg/sink/codec/utils/test_utils.go
  pkg/sink/mysql/config.go
  scripts/download-integration-test-binaries.sh
  tests/integration_tests/run_group.sh
  tests/integration_tests/vector/conf/diff_config.toml
  tests/integration_tests/vector/data/data.sql
  tests/integration_tests/vector/run.sh
Labels: size/XXL, release-note, area/dm, area/ticdc, approved, lgtm

#11622 kvclient(ticdc): add table id to kv client logs
  cdc/kv/region_state.go
  cdc/kv/shared_client.go
  cdc/kv/shared_region_worker.go
  cdc/kv/shared_stream.go
  cdc/processor/processor.go
  cdc/processor/tablepb/table.go
Labels: size/L, release-note-none, approved, lgtm

#11595 sink: avoid memory allocations for transforming ColumnData to Column
  cdc/model/sink.go
  cdc/model/sink_gen.go
  cdc/model/sink_gen_test.go
  cdc/sink/dmlsink/txn/event.go
  cdc/sink/dmlsink/txn/event_test.go
  cdc/sink/dmlsink/txn/mysql/dml.go
  cdc/sink/dmlsink/txn/mysql/dml_test.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  docs/swagger/docs.go
  docs/swagger/swagger.json
  docs/swagger/swagger.yaml
  pkg/sink/codec/canal/canal_entry.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/craft/model.go
  pkg/sink/codec/csv/csv_message.go
  pkg/sink/codec/csv/csv_message_test.go
  pkg/sink/codec/debezium/codec.go
  pkg/sink/codec/internal/column.go
  pkg/sink/codec/open/open_protocol_message.go
  pkg/sink/codec/open/open_protocol_message_test.go
  pkg/util/bitflag.go
  tools/check/go.sum
Labels: size/XXL, release-note-none, approved, lgtm

#11634 sink(ticdc): update defaultSupportVectorVersion
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
Labels: size/XS, release-note-none, approved, lgtm

#11630 gomod(dm): upgrade go-mysql to 1.9.1
  dm/debug-tools/binlog-event-blackhole/fetcher.go
  go.mod
  go.sum
Labels: first-time-contributor, size/XS, contribution, release-note-none, area/dm, ok-to-test, approved, lgtm
