Repository pingcap/tiflow, pull requests merged in 2024-08, with the labels that each got.

#11456 dep(*): use release-8.1 tidb package
  go.mod
  go.sum
Labels: size/M, cherry-pick-approved, release-note, approved, lgtm

#11465 schematracker(dm): Increase max-index-length config for dm schema tracker
  dm/pkg/schema/tracker.go
  dm/pkg/schema/tracker_test.go
Labels: first-time-contributor, size/M, contribution, release-note, area/dm, ok-to-test, approved, lgtm

#11395 kafka(ticdc): claim check support large message raw value format
  cdc/api/v2/model.go
  pkg/config/config_test_data.go
  pkg/config/large_message.go
  pkg/config/large_message_test.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/kafka/claimcheck/claim_check.go
  pkg/sink/kafka/claimcheck/claim_check_test.go
Labels: size/XL, release-note, approved, lgtm, affect-ticdc-config-docs

#11452 pkg/version(*): Improve Go version reporting
  Makefile
  pkg/version/version.go
Labels: size/XS, release-note-none, approved, lgtm

#11442 ticdc: fix cleartext Transmission
  cmd/kafka-consumer/main.go
  cmd/storage-consumer/main.go
  pkg/cmd/redo/apply.go
Labels: size/XS, contribution, release-note-none, needs-ok-to-test, approved, lgtm

#11469 mounter(ticdc): do not report error is verify old value checksum v1 failed
  cdc/entry/mounter.go
Labels: size/M, release-note-none, approved, lgtm

#11472 alter(ticdc): fix alter calculation for cdc_multiple_owners and cdc_no_owners
  metrics/alertmanager/ticdc.rules.yml
Labels: size/XS, release-note-none, approved, lgtm

#11474 metrics(ticdc): fix metrics calculation for Ownership history
  metrics/grafana/ticdc.json
Labels: size/XS, release-note-none, approved, lgtm

#11476 sink, ddl(ticdc): support add index ddl in downstream
  cdc/owner/ddl_manager.go
  cdc/sink/ddlsink/mysql/async_ddl.go
  cdc/sink/ddlsink/mysql/async_ddl_test.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink_test.go
  pkg/errors/reexport.go
Labels: size/XXL, release-note-none, area/engine, approved, lgtm

#11161 sink(ticdc): return invalid topic expression in ErrKafkaInvalidTopicExpression
  cdc/sink/dmlsink/mq/dispatcher/topic/expression.go
  cdc/sink/dmlsink/mq/dispatcher/topic/expression_test.go
  errors.toml
  pkg/errors/cdc_errors.go
Labels: size/M, release-note, approved, lgtm

#11393 docs(ticdc): delete an outdated sentence
  README_TiCDC.md
Labels: first-time-contributor, size/XS, contribution, release-note-none, needs-ok-to-test, approved, lgtm

#11495 chore: update OWNERS_ALIASES
  OWNERS_ALIASES
Labels: size/XS, release-note, skip-issue-check, approved, lgtm

#11494 kafka(ticdc): Revert "kafka(ticdc): claim check support large message raw value for…
  cdc/api/v2/model.go
  pkg/config/config_test_data.go
  pkg/config/large_message.go
  pkg/config/large_message_test.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/open/open_protocol_encoder.go
  pkg/sink/codec/simple/decoder.go
  pkg/sink/codec/simple/encoder.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/kafka/claimcheck/claim_check.go
  pkg/sink/kafka/claimcheck/claim_check_test.go
Labels: size/XL, cherry-pick-approved, release-note-none, approved, lgtm, affect-ticdc-config-docs, needs-cherry-pick-release-8.3

#11491 mysql sink(ticdc): Refactor DB Connection Creation to Facilitate Unit Testing
  cdc/sink/ddlsink/mysql/async_ddl_test.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink_test.go
  cdc/sink/dmlsink/txn/mysql/mysql.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  cdc/sink/dmlsink/txn/txn_dml_sink.go
  errors.toml
  pkg/applier/redo_test.go
  pkg/errors/cdc_errors.go
  pkg/sink/mysql/db_helper.go
  pkg/sink/mysql/factory.go
  pkg/sink/observer/observer.go
Labels: first-time-contributor, size/XL, release-note-none, approved, lgtm

#11504 parser(dm): support ALTER DATABASE default database
  dm/pkg/parser/common.go
  dm/pkg/parser/common_test.go
Labels: size/S, release-note, area/dm, approved, lgtm

#11462 sink(ticdc): refactor the error handing in SinkConfig.applyParameterBySinkURI()
  pkg/config/sink.go
Labels: first-time-contributor, size/M, release-note-none, approved, lgtm, affect-ticdc-config-docs

#11510 metrics(ticdc): fix ddl executed count metrics
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sink/metrics/metrics.go
  cdc/sink/metrics/statistics.go
  metrics/grafana/ticdc.json
Labels: size/XL, release-note, approved, lgtm

#11509 docs(ticdc): Update Integration Test Documentation to Avoid Version Mismatch Issues in TiCDC
  tests/integration_tests/README.md
Labels: size/XS, release-note-none, approved, lgtm

#11518 tests(ticdc): enable brd mode test
  tests/integration_tests/bdr_mode/run.sh
Labels: size/XS, release-note-none, approved, lgtm

#11514 metrics(ticdc): set the y axis min value to zero prevent negative value
  metrics/grafana/ticdc.json
Labels: size/XL, release-note-none, approved, lgtm

#11533 kafka(ticdc): make kafka metrics more robust
  cdc/entry/mounter_group.go
  cdc/processor/memquota/mem_quota.go
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/ddlsink/mq/mq_ddl_sink.go
  cdc/sink/ddlsink/mq/pulsar_ddl_sink.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  cdc/sink/dmlsink/cloudstorage/dml_worker_test.go
  cdc/sink/dmlsink/mq/mq_dml_sink.go
  cdc/sink/dmlsink/mq/worker.go
  cdc/sink/dmlsink/mq/worker_test.go
  cdc/sink/dmlsink/txn/mysql/mysql_test.go
  cdc/sink/dmlsink/txn/txn_dml_sink.go
  cdc/sink/metrics/statistics.go
  metrics/grafana/ticdc.json
  pkg/sink/codec/encoder_group.go
  pkg/sink/codec/metrics.go
  pkg/sink/kafka/metrics.go
  pkg/sink/kafka/metrics_collector.go
Labels: size/XXL, release-note-none, approved, lgtm
