Repository pingcap/tiflow, pull requests merged in 2025-01, with the labels that each got.

#11956 filter(ticdc): fix incorrect event filter with "rename" DDLs
  pkg/filter/sql_event_filter.go
  pkg/filter/sql_event_filter_test.go
  tests/integration_tests/event_filter/conf/cf.toml
  tests/integration_tests/event_filter/conf/diff_config.toml
  tests/integration_tests/event_filter/data/test.sql
  tests/integration_tests/event_filter/data/test_rename.sql
  tests/integration_tests/event_filter/run.sh
Labels: size/L, release-note, approved, lgtm

#11737 test(ticdc): modify generated column test
  tests/integration_tests/generate_column/conf/changefeed.toml
  tests/integration_tests/generate_column/data/stored.sql
  tests/integration_tests/generate_column/data/virtual.sql
  tests/integration_tests/generate_column/run.sh
Labels: size/M, release-note-none, approved, lgtm

#11877 sink(ticdc): add parameter to enable watermark events in the Debezium protocol
  pkg/sink/codec/debezium/encoder.go
Labels: size/XS, release-note-none, approved, lgtm

#11933 dm: refine openapi table migrate rule source/target
  dm/config/task_converters.go
  dm/config/task_converters_test.go
  dm/openapi/gen.server.go
  dm/openapi/gen.types.go
  dm/openapi/spec/dm.yaml
Labels: size/L, contribution, release-note, area/dm, ok-to-test, approved, lgtm

#11977 kafka(ticdc): sarama do not retry if produce message failed to prevent out of order
  pkg/logutil/log.go
  pkg/sink/kafka/sarama.go
Labels: size/S, release-note, approved, lgtm

#11957 puller: close kvclient correctly when stopping a processor
  cdc/processor/processor.go
  cdc/processor/sourcemanager/manager.go
  cdc/puller/ddl_puller.go
  cdc/puller/multiplexing_puller.go
Labels: size/M, release-note-none, approved, lgtm

#11975 sink(ticdc): fix incorrect table info in delete event
  cmd/pulsar-consumer/main.go
  pkg/sink/codec/canal/canal_json_message.go
Labels: size/S, release-note-none, approved, lgtm

#11976 sink(ticdc): fix incorrect default value for the not null timestamp field in the Debezium protocol
  pkg/sink/codec/debezium/codec.go
  tests/integration_tests/debezium/sql/debezium/default_value.sql
Labels: size/S, release-note-none, approved, lgtm

#11978 codec(ticdc): decoder set the table id directly
  cmd/kafka-consumer/writer.go
  cmd/pulsar-consumer/main.go
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/avro/decoder.go
  pkg/sink/codec/canal/canal_json_decoder.go
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_json_txn_event_decoder.go
  pkg/sink/codec/common/helper.go
  pkg/sink/codec/open/open_protocol_decoder.go
  pkg/sink/codec/open/open_protocol_message.go
Labels: size/XXL, release-note-none, approved, lgtm

#11985 dm: add system table filter default for dump task
  dm/dumpling/dumpling.go
  dm/dumpling/dumpling_test.go
  dm/pkg/dumpling/utils.go
  dm/tests/openapi/client/openapi_task_check
  dm/tests/openapi/run.sh
Labels: size/L, contribution, release-note, area/dm, ok-to-test, approved, lgtm

#11996 config AutoSyncInterval to etcd client
  pkg/etcd/client.go
Labels: size/XS, release-note-none, approved, lgtm

#11992 codec(ticdc): Revert "codec(ticdc): canal-json encode table id (#11875)"
  pkg/sink/codec/canal/canal_json_message.go
  pkg/sink/codec/canal/canal_json_row_event_encoder.go
  pkg/sink/codec/canal/canal_json_row_event_encoder_test.go
  pkg/sink/codec/canal/canal_json_txn_event_decoder.go
  pkg/sink/codec/canal/canal_json_txn_event_decoder_test.go
Labels: size/L, release-note-none, approved, lgtm

#11995 sink(ticdc): fix incorrect encoding default value in Avro protocol
  pkg/sink/codec/avro/avro.go
  tests/integration_tests/avro_basic/data/data.sql
  tests/integration_tests/avro_basic/run.sh
Labels: size/S, release-note, approved, lgtm

#11988 *: build sync_diff_inspector from source code to run tests
  .github/workflows/dm_binlog_999999.yaml
  Makefile
  dm/tests/README.md
  dm/tests/download-compatibility-test-binaries.sh
  dm/tests/download-integration-test-binaries.sh
  dm/tests/mariadb_master_down_and_up/case.sh
  dm/tests/mariadb_master_down_and_up/lib.sh
  dm/tests/tiup/lib.sh
  dm/tests/tiup/upgrade-from-v1.sh
  dm/tests/tiup/upgrade-from-v2.sh
  dm/tests/tiup/upgrade-tidb.sh
  dm/tests/upstream_switch/case.sh
  dm/tests/upstream_switch/lib.sh
  scripts/download-integration-test-binaries.sh
  scripts/download-sync-diff.sh
  sync_diff_inspector/checkpoints/checkpoints.go
  sync_diff_inspector/chunk/chunk.go
  sync_diff_inspector/diff/diff.go
  sync_diff_inspector/report/report_test.go
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/common/common_test.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/splitter/bucket.go
  sync_diff_inspector/splitter/index_fields_test.go
  sync_diff_inspector/splitter/splitter_test.go
  sync_diff_inspector/utils/table.go
  sync_diff_inspector/utils/utils.go
  sync_diff_inspector/utils/utils_test.go
  tests/integration_tests/README.md
Labels: size/XL, release-note, area/dm, approved, lgtm

#12014 sink(ticdc): fix incorrect encoding default value in Avro protocol
  pkg/sink/codec/avro/avro.go
  scripts/download-integration-test-binaries.sh
Labels: size/S, release-note, approved, lgtm

#12018 sink(ticdc): fix incorrect encoding default value in Avro protocol
  pkg/sink/codec/avro/avro.go
  tests/integration_tests/avro_basic/data/data.sql
Labels: size/S, release-note-none, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#12019 sink(ticdc): fix incorrect encoding default value in Avro protocol
  pkg/sink/codec/avro/avro.go
Labels: size/S, release-note, approved, lgtm

#12027 *: add warning to deprecate config sink.enable-partition-separator in the future
  pkg/cmd/cli/cli_changefeed_create.go
  pkg/cmd/cli/cli_changefeed_update.go
Labels: size/M, release-note-none, approved, lgtm

#11708 codec(ticdc): canal-json message do not end by terminator if using kafka sink
  cdc/sink/codec/canal/canal_json_encoder.go
  cdc/sink/codec/common/config.go
Labels: size/XS, cherry-pick-approved, release-note, approved, lgtm

#12003 api(cdc): fix create changefeed after scale-in pd
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  tests/integration_tests/synced_status_with_redo/run.sh
Labels: size/L, release-note, approved, lgtm

#11667 sourcemanager(ticdc): close all pullers asyncrhonsly to prevent block too long
  cdc/processor/sourcemanager/manager.go
Labels: size/XS, cherry-pick-approved, release-note, approved, lgtm
