Repository pingcap/tiflow, pull requests merged in 2025-05, with the labels that each got.

#12159 sync_diff_inspector: fix flaky test TestMysqlRouter
  sync_diff_inspector/source/chunks_iter.go
  sync_diff_inspector/source/source_test.go
  sync_diff_inspector/splitter/limit.go
  sync_diff_inspector/splitter/random.go
  sync_diff_inspector/splitter/splitter_test.go
Labels: size/M, release-note, approved, lgtm

#12176 codec(ticdc): fix test in debezium protocol
  pkg/sink/codec/debezium/codec_test.go
  tests/integration_tests/debezium/sql/ddl.sql
Labels: size/S, release-note-none, approved, lgtm

#12188 kvclient(ticdc): fix the resolve last run status gc
  cdc/kv/shared_client.go
Labels: first-time-contributor, size/XS, release-note-none, approved, lgtm
