Repository pingcap/tiflow, pull requests merged in 2025-07, with the labels that each got.

#12215 test(ticdc): remove incorrect query execution plan in tidb_cdc_test
  tests/integration_tests/tidb_mysql_test/r/date_formats.result
  tests/integration_tests/tidb_mysql_test/t/date_formats.test
Labels: size/XS, release-note-none, approved, lgtm

#12211 event filter: fix panic when evaluate expressions for table with virtual columns
  cdc/model/mounter.go
  cdc/model/mounter_test.go
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
  pkg/filter/expr_filter.go
  pkg/filter/expr_filter_test.go
  tests/integration_tests/event_filter/conf/cf.toml
  tests/integration_tests/event_filter/data/test.sql
  tests/integration_tests/event_filter/run.sh
  tests/integration_tests/syncpoint/run.sh
Labels: size/XL, release-note, area/dm, area/ticdc, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#12222 scheduler: Speed ​​up region scanning before table splitting
  cdc/scheduler/internal/v3/keyspan/mock.go
  cdc/scheduler/internal/v3/keyspan/splitter_region_count.go
Labels: size/M, release-note, approved, lgtm

#12229 eventfilter: simplify the way to eval virtual column
  pkg/filter/expr_filter.go
Labels: size/S, release-note, approved, lgtm

#12236 sink(ticdc): calculate partition by the orignal column name
  cdc/model/schema_storage.go
  cdc/sink/dmlsink/mq/dispatcher/partition/columns.go
  cdc/sink/dmlsink/mq/dispatcher/partition/columns_test.go
  cdc/sink/dmlsink/mq/dispatcher/partition/index_value.go
  cdc/sink/dmlsink/mq/dispatcher/partition/index_value_test.go
Labels: size/M, release-note-none, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#12252 event filter: fix panic when evaluate expressions for table with virtual columns
  cdc/model/mounter.go
  cdc/model/mounter_test.go
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
  pkg/filter/expr_filter.go
  pkg/filter/expr_filter_test.go
  tests/integration_tests/event_filter/conf/cf.toml
  tests/integration_tests/event_filter/data/test.sql
  tests/integration_tests/event_filter/run.sh
  tests/integration_tests/syncpoint/run.sh
Labels: size/XL, release-note, approved, lgtm

#12251 cloudstorage: fix a bug that may cause storage sink get stuck (#12142…
  cdc/sinkv2/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sinkv2/eventsink/cloudstorage/cloud_storage_dml_sink.go
  pkg/util/external_storage.go
  pkg/util/external_storage_test.go
Labels: size/L, release-note, approved, lgtm

#12254 sink(ticdc): check virtual columns in column dispatcher
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
  cdc/sink/dmlsink/mq/dispatcher/event_router.go
  cdc/sink/dmlsink/mq/dispatcher/partition/columns.go
  cdc/sink/dmlsink/mq/dispatcher/partition/columns_test.go
Labels: size/M, release-note, approved, lgtm

#12250 *: bump jwt and jose2go
  go.mod
  go.sum
Labels: size/S, cherry-pick-approved, release-note-none, approved, lgtm

#12259 cloudstorage: fix a bug that may cause storage sink get stuck (#12142…
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  pkg/util/external_storage.go
  pkg/util/external_storage_test.go
Labels: size/L, release-note

#12245 chann(ticdc): fix a panic that send on closed channel
  cdc/owner/changefeed.go
  cdc/owner/changefeed_test.go
  cdc/processor/processor.go
Labels: size/M, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5
