Repository pingcap/tiflow, pull requests merged in 2025-09, with the labels that each got.

#12311 fix(log): remove the value from the log of etcd worker put key
  pkg/orchestrator/etcd_worker.go
Labels: size/XS, release-note-none, approved, lgtm

#12334 DM: Update dependencies to remove security alerts.
  .github/workflows/dm_ui_lint.yaml
  dm/ui/package.json
  go.mod
  go.sum
Labels: size/S, release-note-none, area/dm, ok-to-test, approved, lgtm

#12343 *: bump jwt
  cmd/oauth2-server/main.go
  go.mod
  go.sum
Labels: size/M, release-note-none, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5
