Repository pingcap/tiflow, pull requests merged in 2025-02, with the labels that each got.

#12044 sink(ticdc): fix incorrect sanitize
  pkg/sink/codec/avro/avro_test.go
  pkg/sink/codec/common/helper.go
  tests/integration_tests/debezium/docker-compose.yml
Labels: size/S, cherry-pick-approved, release-note, approved, lgtm

#12041 test(ticdc): fix multi_source test
  tests/integration_tests/multi_source/main.go
Labels: size/XS, release-note-none, approved, lgtm

#12048 build: add sync-diff-inspector target into `build` make task
  Makefile
Labels: size/XS, release-note-none, approved, lgtm

#12038 sink(ticdc): fix incorrect `default` field
  cdc/entry/mounter_test.go
  cdc/model/codec/codec.go
  cdc/model/schema_storage.go
  cdc/model/sink.go
  pkg/sink/cloudstorage/table_definition.go
  pkg/sink/codec/debezium/codec.go
  pkg/sink/codec/debezium/helper.go
  pkg/sink/codec/debezium/helper_test.go
  pkg/sink/codec/simple/avro.go
  pkg/sink/codec/simple/encoder_test.go
  pkg/sink/codec/simple/message.go
Labels: size/M, release-note, needs-cherry-pick-release-6.1, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#12063 feat(ticdc): prevent using the same TiDB cluster as both upstream and downstream
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/api/v2/api_helpers.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  errors.toml
  pkg/check/cluster.go
  pkg/check/cluster_test.go
  pkg/errors/cdc_errors.go
Labels: size/XL, release-note, approved, lgtm

#12069 ticdc:bug fix - added pulsar+http and pulsar+https protocols in IsMQScheme to honor MQ fields in changefeed
  pkg/sink/sink_type.go
Labels: size/XS, contribution, release-note, ok-to-test, approved, lgtm, needs-cherry-pick-release-8.5

#12058 Fix changefeed stuck problem when overwrite resume with a forward checkpointTs
  cdc/owner/changefeed.go
  tests/integration_tests/overwrite_resume_with_syncpoint/conf/changefeed.toml
  tests/integration_tests/overwrite_resume_with_syncpoint/run.sh
  tests/integration_tests/run_group.sh
Labels: size/M, cherry-pick-approved, release-note, approved, lgtm
