Repository pingcap/tiflow, pull requests merged in 2025-04, with the labels that each got.

#12113 codec(ticdc): modify DDL type support about debezium protocol
  pkg/sink/codec/debezium/codec.go
  tests/integration_tests/debezium/go.mod
  tests/integration_tests/debezium/go.sum
  tests/integration_tests/debezium/sql/ddl.sql
Labels: size/L, release-note-none, approved, lgtm, needs-cherry-pick-release-9.0-beta.1

#12112 kafka(ticdc): ddl sink close the underline sink if send ddl or checkpoint failed and refactor the kafka ddl sink
  cdc/owner/ddl_sink.go
  cdc/sink/ddlsink/mq/ddlproducer/kafka_ddl_producer.go
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/ddlsink/mq/mq_ddl_sink.go
  cdc/sink/ddlsink/mq/pulsar_ddl_sink.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/kafka/v2/factory.go
Labels: size/L, release-note-none, approved, lgtm

#12120 CI: Upgrade to actions/cache@v4
  .github/workflows/check_and_build.yaml
  .github/workflows/dataflow_engine_chaos.yaml
  .github/workflows/dm_binlog_999999.yaml
  .github/workflows/dm_chaos.yaml
  .github/workflows/dm_mariadb_master_down_and_up.yaml
  .github/workflows/dm_upstream_switch.yaml
Labels: size/S, release-note-none, approved, lgtm

#12134 kafka(ticdc): bump sarama fix kafka stuck
  go.mod
  go.sum
Labels: size/M, release-note, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1

#12140 *: bump tidb 8.5
  cdc/puller/ddl_puller.go
  go.mod
  go.sum
Labels: size/M, cherry-pick-approved, release-note-none, approved, lgtm

#12118 dm: upgrade go-mysql to v1.12.0
  go.mod
  go.sum
Labels: size/S, release-note-none, approved, lgtm

#12132 sink(ticdc): Treat column and index names as case insensitive
  cdc/model/schema_storage.go
  cdc/model/schema_storage_test.go
  cdc/sink/dmlsink/mq/dispatcher/partition/columns.go
  cdc/sink/dmlsink/mq/dispatcher/partition/columns_test.go
  cdc/sink/dmlsink/mq/dispatcher/partition/index_value.go
  cdc/sink/dmlsink/mq/dispatcher/partition/index_value_test.go
  tests/integration_tests/mq_sink_dispatcher/conf/changefeed.toml
  tests/integration_tests/mq_sink_dispatcher/conf/diff_config.toml
  tests/integration_tests/mq_sink_dispatcher/conf/new_changefeed.toml
  tests/integration_tests/mq_sink_dispatcher/run.sh
Labels: size/L, release-note, approved, lgtm

#12142 cloudstorage: fix a bug that may cause storage sink get stuck
  cdc/sink/ddlsink/cloudstorage/cloud_storage_ddl_sink.go
  cdc/sink/dmlsink/cloudstorage/cloud_storage_dml_sink.go
  pkg/util/external_storage.go
  pkg/util/external_storage_test.go
Labels: size/L, release-note, needs-cherry-pick-release-6.5, needs-cherry-pick-release-7.1, approved, lgtm, needs-cherry-pick-release-7.5, needs-cherry-pick-release-8.1, needs-cherry-pick-release-8.5

#12123 sink(ticdc): waiting the asynchronous ddl to synchronize
  cdc/owner/ddl_sink.go
  cdc/owner/ddl_sink_test.go
  cdc/sink/ddlsink/mysql/async_ddl.go
  cdc/sink/ddlsink/mysql/async_ddl_test.go
  cdc/sink/ddlsink/mysql/mysql_ddl_sink.go
  errors.toml
  pkg/errors/cdc_errors.go
  tests/integration_tests/ddl_wait/conf/diff_config.toml
  tests/integration_tests/ddl_wait/run.sh
  tests/integration_tests/ddl_wait/test.go
  tests/integration_tests/run_group.sh
Labels: size/XXL, release-note, approved, lgtm

#12151 remove undefined panel
  metrics/grafana/tiflow.json
Labels: severity/minor, size/M, release-note-none, approved, lgtm

#12078 *(dm): retry statement execution on invalid connections in some scenarios
  dm/_utils/terror_gen/errors_release.txt
  dm/errors.toml
  dm/pkg/conn/baseconn.go
  dm/pkg/conn/baseconn_test.go
  dm/pkg/retry/errors.go
  dm/pkg/retry/strategy.go
  dm/pkg/terror/errcode_string.go
  dm/pkg/terror/error_list.go
  dm/syncer/dbconn/db.go
  dm/tests/all_mode/run.sh
  dm/tests/many_tables/run.sh
Labels: first-time-contributor, size/XXL, contribution, release-note, area/dm, ok-to-test, approved, lgtm

#12154 DM: Add $k8s_cluster and $tidb_cluster as potential filter to Grafana panels.
  metrics/grafana/DM-Monitor-Professional.json
  metrics/grafana/DM-Monitor-Standard.json
Labels: size/XL, release-note-none, approved, lgtm
