Repository pingcap/tiflow, pull requests merged in 2025-06, with the labels that each got.

#12183 codec(ticdc): support header line for CSV protocol
  cdc/api/v2/model.go
  cdc/sink/dmlsink/cloudstorage/dml_worker.go
  pkg/config/config_test_data.go
  pkg/config/sink.go
  pkg/sink/codec/common/config.go
  pkg/sink/codec/csv/csv_decoder.go
  pkg/sink/codec/csv/csv_encoder.go
  pkg/sink/codec/csv/csv_encoder_test.go
  pkg/sink/codec/csv/csv_message.go
  pkg/sink/codec/csv/csv_message_test.go
  tests/integration_tests/csv_storage_basic/conf/changefeed.toml
  tests/integration_tests/csv_storage_basic/data/data.sql
  tests/integration_tests/csv_storage_basic/run.sh
Labels: size/L, release-note, approved, lgtm, affect-ticdc-config-docs

#12196 kafka(ticdc): bump sarama fix kafka stuck
  go.mod
  go.sum
Labels: size/XS, release-note, area/dm, area/engine, approved, lgtm

#12173 sarama: add keep-alive mechanism for sarama connections
  cdc/sink/ddlsink/mq/kafka_ddl_sink.go
  cdc/sink/ddlsink/mq/mq_ddl_sink.go
  cdc/sink/ddlsink/mq/mq_ddl_sink_test.go
  cdc/sink/ddlsink/mq/pulsar_ddl_sink.go
  cdc/sink/dmlsink/mq/kafka_dml_sink.go
  cdc/sink/dmlsink/mq/manager/kafka_manager.go
  cdc/sink/dmlsink/mq/manager/kafka_manager_test.go
  cdc/sink/util/helper.go
  cdc/sink/util/helper_test.go
  pkg/sink/kafka/admin.go
  pkg/sink/kafka/cluster_admin_client.go
  pkg/sink/kafka/cluster_admin_client_mock_impl.go
  pkg/sink/kafka/factory.go
  pkg/sink/kafka/mock_factory.go
  pkg/sink/kafka/options.go
  pkg/sink/kafka/options_test.go
  pkg/sink/kafka/sarama.go
  pkg/sink/kafka/sarama_factory.go
  pkg/sink/kafka/sarama_factory_test.go
  pkg/sink/kafka/v2/admin.go
  pkg/sink/kafka/v2/factory.go
Labels: size/XXL, release-note, approved, lgtm
