Repository pingcap/tiflow, pull requests merged in 2025-03, with the labels that each got.

#12060 build: add new task for integration tests of sync_diff_inspector
  Makefile
  dm/pkg/shardddl/optimism/lock_test.go
  dm/syncer/validate_worker.go
  sync_diff_inspector/tests/README.md
  sync_diff_inspector/tests/_utils/check_contains
  sync_diff_inspector/tests/_utils/check_contains_count
  sync_diff_inspector/tests/_utils/check_contains_regex
  sync_diff_inspector/tests/run.sh
  sync_diff_inspector/tests/sync_diff_inspector/checkpoint/config_base.toml
  sync_diff_inspector/tests/sync_diff_inspector/checkpoint/config_base_continous.toml
  sync_diff_inspector/tests/sync_diff_inspector/checkpoint/config_base_rand.toml
  sync_diff_inspector/tests/sync_diff_inspector/checkpoint/run.sh
  sync_diff_inspector/tests/sync_diff_inspector/config_base_mysql.toml
  sync_diff_inspector/tests/sync_diff_inspector/config_base_tidb.toml
  sync_diff_inspector/tests/sync_diff_inspector/expression/config.toml
  sync_diff_inspector/tests/sync_diff_inspector/expression/run.sh
  sync_diff_inspector/tests/sync_diff_inspector/json/config_base.toml
  sync_diff_inspector/tests/sync_diff_inspector/json/run.sh
  sync_diff_inspector/tests/sync_diff_inspector/run.sh
  sync_diff_inspector/tests/sync_diff_inspector/shard/config_base.toml
  sync_diff_inspector/tests/sync_diff_inspector/shard/config_router_1.toml
  sync_diff_inspector/tests/sync_diff_inspector/shard/config_router_2.toml
  sync_diff_inspector/tests/sync_diff_inspector/shard/config_router_3.toml
  sync_diff_inspector/tests/sync_diff_inspector/shard/config_router_4.toml
  sync_diff_inspector/tests/sync_diff_inspector/shard/config_router_5.toml
  sync_diff_inspector/tests/sync_diff_inspector/shard/run.sh
  sync_diff_inspector/tests/sync_diff_inspector/snapshot/config_base.toml
  sync_diff_inspector/tests/sync_diff_inspector/snapshot/run.sh
  sync_diff_inspector/tests/sync_diff_inspector/table_config/config.toml
  sync_diff_inspector/tests/sync_diff_inspector/table_config/run.sh
  sync_diff_inspector/tests/sync_diff_inspector/table_skip/config_base.toml
  sync_diff_inspector/tests/sync_diff_inspector/table_skip/config_router.toml
  sync_diff_inspector/tests/sync_diff_inspector/table_skip/run.sh
  sync_diff_inspector/tests/sync_diff_inspector/time_zone/config.toml
  sync_diff_inspector/tests/sync_diff_inspector/time_zone/run.sh
  sync_diff_inspector/tests/sync_diff_inspector/tls/config.toml
  sync_diff_inspector/tests/sync_diff_inspector/tls/run.sh
  sync_diff_inspector/utils/table.go
Labels: size/L, release-note-none, approved, lgtm

#12080 puller: fix potential stuck
  cdc/kv/shared_stream.go
Labels: size/XS, release-note-none, approved, lgtm, needs-cherry-pick-release-8.5

#12085 test(ticdc): fix duplicate entry about multi_source test
  tests/integration_tests/multi_source/main.go
Labels: size/XS, release-note-none, approved, lgtm

#12087 scheduler: support mysql sink split table
  pkg/config/replica_config.go
Labels: size/XS, release-note, area/ticdc

#12102 server(ticdc): export ticdc server options struct for public use in new architecture
  pkg/cmd/server/server.go
Labels: size/S, release-note-none, approved, lgtm

#12105 server(ticdc): make options struct fields public for ticdc new architecture
  pkg/cmd/server/server.go
  pkg/cmd/server/server_test.go
Labels: size/L, release-note-none, approved, lgtm

#12095 utils: skip workload schema hack
  pkg/filter/filter.go
  pkg/filter/filter_test.go
  pkg/filter/utils.go
Labels: first-time-contributor, size/XS, release-note-none, approved, lgtm

#12108 codec(ticdc): fix unsupport DDL type about debezium protocol
  cmd/kafka-consumer/writer.go
  pkg/sink/codec/debezium/codec.go
Labels: size/XS, release-note-none, approved, lgtm

#12106 *(ticdc): support ssl when fetching downstream cluster id
  cdc/api/v1/api.go
  cdc/api/v1/api_test.go
  cdc/api/v2/changefeed.go
  cdc/api/v2/changefeed_test.go
  cdc/entry/validator.go
  cdc/model/changefeed.go
  cdc/processor/processor_test.go
  cdc/puller/ddl_puller_test.go
  cdc/puller/memorysorter/entry_sorter_test.go
  cdc/scheduler/internal/v3/keyspan/splitter_write_test.go
  pkg/check/cluster.go
  pkg/check/cluster_test.go
  tests/integration_tests/_utils/check_table_exists
  tests/integration_tests/_utils/start_tidb_cluster
  tests/integration_tests/_utils/start_tidb_cluster_impl
  tests/integration_tests/down_db_require_secure_transport/run.sh
  tests/integration_tests/run_group.sh
Labels: size/XL, release-note-none, approved, lgtm

#12092 consumer(ticdc): adjust consumer log level
  cmd/kafka-consumer/event_group.go
  cmd/kafka-consumer/writer.go
Labels: size/XS, release-note-none, approved, lgtm
